{"total_count": 11, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/googleapis/python-logging/issues/60", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/60/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/60/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/60/events", "html_url": "https://github.com/googleapis/python-logging/issues/60", "id": 675386172, "node_id": "MDU6SXNzdWU2NzUzODYxNzI=", "number": 60, "title": "Warning: a recent release failed", "user": {"login": "failure-checker[bot]", "id": 58094317, "node_id": "MDM6Qm90NTgwOTQzMTc=", "avatar_url": "https://avatars2.githubusercontent.com/in/47470?v=4", "gravatar_id": "", "url": "https://api.github.com/users/failure-checker%5Bbot%5D", "html_url": "https://github.com/apps/failure-checker", "followers_url": "https://api.github.com/users/failure-checker%5Bbot%5D/followers", "following_url": "https://api.github.com/users/failure-checker%5Bbot%5D/following{/other_user}", "gists_url": "https://api.github.com/users/failure-checker%5Bbot%5D/gists{/gist_id}", "starred_url": "https://api.github.com/users/failure-checker%5Bbot%5D/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/failure-checker%5Bbot%5D/subscriptions", "organizations_url": "https://api.github.com/users/failure-checker%5Bbot%5D/orgs", "repos_url": "https://api.github.com/users/failure-checker%5Bbot%5D/repos", "events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/events{/privacy}", "received_events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/received_events", "type": "Bot", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1814803587, "node_id": "MDU6TGFiZWwxODE0ODAzNTg3", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20process", "name": "type: process", "color": "c5def5", "default": false, "description": "A process-releated concern. May include testing, release, or the like."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-08-08T01:01:25Z", "updated_at": "2020-08-12T04:19:44Z", "closed_at": "2020-08-12T04:19:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "The release PR #50 is still in a pending state after several hours", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/55", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/55/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/55/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/55/events", "html_url": "https://github.com/googleapis/python-logging/issues/55", "id": 664001432, "node_id": "MDU6SXNzdWU2NjQwMDE0MzI=", "number": 55, "title": "Implement new client options ", "user": {"login": "busunkim96", "id": 8822365, "node_id": "MDQ6VXNlcjg4MjIzNjU=", "avatar_url": "https://avatars1.githubusercontent.com/u/8822365?v=4", "gravatar_id": "", "url": "https://api.github.com/users/busunkim96", "html_url": "https://github.com/busunkim96", "followers_url": "https://api.github.com/users/busunkim96/followers", "following_url": "https://api.github.com/users/busunkim96/following{/other_user}", "gists_url": "https://api.github.com/users/busunkim96/gists{/gist_id}", "starred_url": "https://api.github.com/users/busunkim96/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/busunkim96/subscriptions", "organizations_url": "https://api.github.com/users/busunkim96/orgs", "repos_url": "https://api.github.com/users/busunkim96/repos", "events_url": "https://api.github.com/users/busunkim96/events{/privacy}", "received_events_url": "https://api.github.com/users/busunkim96/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1814803575, "node_id": "MDU6TGFiZWwxODE0ODAzNTc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20feature%20request", "name": "type: feature request", "color": "c5def5", "default": false, "description": "\u2018Nice-to-have\u2019 improvement, new feature or different behavior or design."}], "state": "closed", "locked": false, "assignee": {"login": "Daniel-Sanche", "id": 3914119, "node_id": "MDQ6VXNlcjM5MTQxMTk=", "avatar_url": "https://avatars1.githubusercontent.com/u/3914119?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Daniel-Sanche", "html_url": "https://github.com/Daniel-Sanche", "followers_url": "https://api.github.com/users/Daniel-Sanche/followers", "following_url": "https://api.github.com/users/Daniel-Sanche/following{/other_user}", "gists_url": "https://api.github.com/users/Daniel-Sanche/gists{/gist_id}", "starred_url": "https://api.github.com/users/Daniel-Sanche/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Daniel-Sanche/subscriptions", "organizations_url": "https://api.github.com/users/Daniel-Sanche/orgs", "repos_url": "https://api.github.com/users/Daniel-Sanche/repos", "events_url": "https://api.github.com/users/Daniel-Sanche/events{/privacy}", "received_events_url": "https://api.github.com/users/Daniel-Sanche/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "Daniel-Sanche", "id": 3914119, "node_id": "MDQ6VXNlcjM5MTQxMTk=", "avatar_url": "https://avatars1.githubusercontent.com/u/3914119?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Daniel-Sanche", "html_url": "https://github.com/Daniel-Sanche", "followers_url": "https://api.github.com/users/Daniel-Sanche/followers", "following_url": "https://api.github.com/users/Daniel-Sanche/following{/other_user}", "gists_url": "https://api.github.com/users/Daniel-Sanche/gists{/gist_id}", "starred_url": "https://api.github.com/users/Daniel-Sanche/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Daniel-Sanche/subscriptions", "organizations_url": "https://api.github.com/users/Daniel-Sanche/orgs", "repos_url": "https://api.github.com/users/Daniel-Sanche/repos", "events_url": "https://api.github.com/users/Daniel-Sanche/events{/privacy}", "received_events_url": "https://api.github.com/users/Daniel-Sanche/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 2, "created_at": "2020-07-22T19:35:38Z", "updated_at": "2020-08-12T20:28:41Z", "closed_at": "2020-08-12T20:28:41Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "Add support for the three new client_options `quota_project_id`, `scopes`, and `credentials_file`.  These options are implemented on the mirogenerator, so the completion of the migration may automatically fulfill this.\r\n\r\nhttps://googleapis.dev/python/google-api-core/latest/client_options.html", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/47", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/47/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/47/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/47/events", "html_url": "https://github.com/googleapis/python-logging/issues/47", "id": 647078629, "node_id": "MDU6SXNzdWU2NDcwNzg2Mjk=", "number": 47, "title": "Docs: remove Python 2.7 support and change descriptions on virtual environment", "user": {"login": "ymotongpoo", "id": 145104, "node_id": "MDQ6VXNlcjE0NTEwNA==", "avatar_url": "https://avatars1.githubusercontent.com/u/145104?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ymotongpoo", "html_url": "https://github.com/ymotongpoo", "followers_url": "https://api.github.com/users/ymotongpoo/followers", "following_url": "https://api.github.com/users/ymotongpoo/following{/other_user}", "gists_url": "https://api.github.com/users/ymotongpoo/gists{/gist_id}", "starred_url": "https://api.github.com/users/ymotongpoo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ymotongpoo/subscriptions", "organizations_url": "https://api.github.com/users/ymotongpoo/orgs", "repos_url": "https://api.github.com/users/ymotongpoo/repos", "events_url": "https://api.github.com/users/ymotongpoo/events{/privacy}", "received_events_url": "https://api.github.com/users/ymotongpoo/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1814803802, "node_id": "MDU6TGFiZWwxODE0ODAzODAy", "url": "https://api.github.com/repos/googleapis/python-logging/labels/triage%20me", "name": "triage me", "color": "FF69B4", "default": false, "description": "I really want to be triaged."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-06-29T03:09:59Z", "updated_at": "2020-07-01T16:54:04Z", "closed_at": "2020-07-01T16:54:04Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "#### Environment details\r\n\r\n  - OS type and version: any\r\n  - Python version: any\r\n  - pip version: any\r\n  - `google-cloud-logging` version: any\r\n\r\n#### Steps to reproduce\r\n\r\n  1. Read [Installation](https://github.com/googleapis/python-logging#installation) section of `README.rst`\r\n  2. Find the step to install `virtualenv`\r\n\r\n#### Code example\r\n\r\nGiven Python 2.7 support is removed in January 1, 2020 and the oldest supported version is Python 3.5, we can expect that all environments are with `venv` that is included in the standard modules and is alternative of `virtualenv` in this use case. So we can replace the installation documents with the following descriptions:\r\n\r\n* macOS/Linux\r\n\r\n```\r\npython -m venv <your-env>\r\nsource <your-env>/bin/activate\r\n<your-env>/bin/pip install google-cloud-logging\r\n```\r\n\r\n* Windows\r\n\r\n```\r\npython -m venv <your-env>\r\n<your-env>\\Scripts\\activate\r\n<your-env>\\Scripts\\pip.exe install google-cloud-logging\r\n```\r\n\r\n#### Stack trace\r\n\r\nN/A\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/45", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/45/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/45/events", "html_url": "https://github.com/googleapis/python-logging/issues/45", "id": 646677931, "node_id": "MDU6SXNzdWU2NDY2Nzc5MzE=", "number": 45, "title": "Synthesis failed for python-logging", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1840715666, "node_id": "MDU6TGFiZWwxODQwNzE1NjY2", "url": "https://api.github.com/repos/googleapis/python-logging/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814803657, "node_id": "MDU6TGFiZWwxODE0ODAzNjU3", "url": "https://api.github.com/repos/googleapis/python-logging/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814803535, "node_id": "MDU6TGFiZWwxODE0ODAzNTM1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2020-06-27T12:55:44Z", "updated_at": "2020-07-01T21:35:19Z", "closed_at": "2020-07-01T21:35:19Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-logging. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\non-logging/self/2/sponge_log.log\n2020-06-27 05:55:35,479 autosynth [DEBUG] > Running: /tmpfs/src/github/synthtool/env/bin/python3 -m synthtool --metadata synth.metadata synth.py --\n2020-06-27 05:55:35,687 synthtool [DEBUG] > Executing /home/kbuilder/.cache/synthtool/python-logging/synth.py.\nOn branch autosynth-self-2\nnothing to commit, working tree clean\n2020-06-27 05:55:35,816 synthtool [DEBUG] > Ensuring dependencies.\n2020-06-27 05:55:35,827 synthtool [DEBUG] > Using precloned repo /home/kbuilder/.cache/synthtool/synthtool\n2020-06-27 05:55:35,831 synthtool [DEBUG] > Cloning googleapis.\n2020-06-27 05:55:35,832 synthtool [DEBUG] > Using precloned repo /home/kbuilder/.cache/synthtool/googleapis\n2020-06-27 05:55:35,835 synthtool [DEBUG] > Generating code for: //google/logging/v2:logging-v2-py.\n2020-06-27 05:55:42,756 synthtool [ERROR] > Failed executing bazel --max_idle_secs=60 build //google/logging/v2:logging-v2-py:\n\nLoading: \nLoading: 0 packages loaded\nLoading: 0 packages loaded\nINFO: SHA256 (https://github.com/protocolbuffers/protobuf/archive/fe1790ca0df67173702f70d5646b82f48f412b99.zip) = 419f654d36998a51de2e0b79a67885ec48f8d803615ce66ec82cd15f54936730\nDEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"419f654d36998a51de2e0b79a67885ec48f8d803615ce66ec82cd15f54936730\"\nDEBUG: Call stack for the definition of repository 'com_google_protobuf' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:34:1\nLoading: 0 packages loaded\nLoading: 0 packages loaded\nINFO: SHA256 (https://github.com/googleapis/gapic-generator/archive/a59457d24bd6f3c962c8e699c708121c928eedc8.zip) = 843bcf262d44f6a2c1c131844ff8ef40daf95dd3b7c95dd761656f9e010d06d7\nDEBUG: Rule 'com_google_api_codegen' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"843bcf262d44f6a2c1c131844ff8ef40daf95dd3b7c95dd761656f9e010d06d7\"\nDEBUG: Call stack for the definition of repository 'com_google_api_codegen' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:62:1\nLoading: 0 packages loaded\nINFO: SHA256 (https://github.com/googleapis/protoc-docs-plugin/archive/b2502d56b5ec2d47e063976da773206af295362d.zip) = 765ec120bb165ae98c3bae78705d2a127e64016e59738552e909fc8b11d06338\nDEBUG: Rule 'protoc_docs_plugin' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"765ec120bb165ae98c3bae78705d2a127e64016e59738552e909fc8b11d06338\"\nDEBUG: Call stack for the definition of repository 'protoc_docs_plugin' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:179:1\nLoading: 0 packages loaded\nINFO: SHA256 (https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz) = d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10\nDEBUG: Rule 'bazel_gazelle' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10\"\nDEBUG: Call stack for the definition of repository 'bazel_gazelle' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:200:1\nINFO: SHA256 (https://github.com/googleapis/gapic-generator-go/archive/v0.13.3.tar.gz) = c18388bb1f1318dc5b00d9727beb9f9a079b64c2ef96a93cee83b5e11e172f02\nDEBUG: Rule 'com_googleapis_gapic_generator_go' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"c18388bb1f1318dc5b00d9727beb9f9a079b64c2ef96a93cee83b5e11e172f02\"\nDEBUG: Call stack for the definition of repository 'com_googleapis_gapic_generator_go' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:209:1\nINFO: Build option --protocopt has changed, discarding analysis cache.\nAnalyzing: target //google/logging/v2:logging-v2-py (1 packages loaded, 0 targets configured)\nERROR: While resolving toolchains for target @pypi_black//:black: invalid registered toolchain '@gapic_generator_python//:pyenv3_toolchain': no such package '@gapic_generator_python//': The repository '@gapic_generator_python' could not be resolved\nERROR: Analysis of target '//google/logging/v2:logging-v2-py' failed; build aborted: invalid registered toolchain '@gapic_generator_python//:pyenv3_toolchain': no such package '@gapic_generator_python//': The repository '@gapic_generator_python' could not be resolved\nINFO: Elapsed time: 6.911s\nINFO: 0 processes.\nFAILED: Build did NOT complete successfully (30 packages loaded, 93 targets configured)\nFAILED: Build did NOT complete successfully (30 packages loaded, 93 targets configured)\n\n2020-06-27 05:55:42,757 synthtool [DEBUG] > Wrote metadata to synth.metadata.\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/github/synthtool/synthtool/__main__.py\", line 102, in <module>\n    main()\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/tmpfs/src/github/synthtool/synthtool/__main__.py\", line 94, in main\n    spec.loader.exec_module(synth_module)  # type: ignore\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/home/kbuilder/.cache/synthtool/python-logging/synth.py\", line 29, in <module>\n    include_protos=True,\n  File \"/tmpfs/src/github/synthtool/synthtool/gcp/gapic_bazel.py\", line 46, in py_library\n    return self._generate_code(service, version, \"python\", **kwargs)\n  File \"/tmpfs/src/github/synthtool/synthtool/gcp/gapic_bazel.py\", line 180, in _generate_code\n    shell.run(bazel_run_args)\n  File \"/tmpfs/src/github/synthtool/synthtool/shell.py\", line 39, in run\n    raise exc\n  File \"/tmpfs/src/github/synthtool/synthtool/shell.py\", line 33, in run\n    encoding=\"utf-8\",\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py\", line 438, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['bazel', '--max_idle_secs=60', 'build', '//google/logging/v2:logging-v2-py']' returned non-zero exit status 1.\n2020-06-27 05:55:42,799 autosynth [ERROR] > Synthesis failed\n2020-06-27 05:55:42,799 autosynth [DEBUG] > Running: git reset --hard HEAD\nHEAD is now at 6dde25e chore: Migrate python-logging synth.py from artman to bazel (#35)\n2020-06-27 05:55:42,805 autosynth [DEBUG] > Running: git checkout autosynth-self\nSwitched to branch 'autosynth-self'\n2020-06-27 05:55:42,809 autosynth [ERROR] > Command '['/tmpfs/src/github/synthtool/env/bin/python3', '-m', 'synthtool', '--metadata', 'synth.metadata', 'synth.py', '--']' returned non-zero exit status 1.\n2020-06-27 05:55:43,006 autosynth [INFO] > PR already exists: https://github.com/googleapis/python-logging/pull/43\n2020-06-27 05:55:43,006 autosynth [DEBUG] > Running: git clean -fdx\nRemoving __pycache__/\nRemoving google/__pycache__/\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 657, in <module>\n    main()\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 506, in main\n    return _inner_main(temp_dir)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 637, in _inner_main\n    commit_count = synthesize_loop(x, multiple_prs, change_pusher, synthesizer)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 367, in synthesize_loop\n    synthesize_inner_loop(fork, synthesizer)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 411, in synthesize_inner_loop\n    synthesizer, len(toolbox.versions) - 1\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 266, in synthesize_version_in_new_branch\n    synthesizer.synthesize(synth_log_path, self.environ)\n  File \"/tmpfs/src/github/synthtool/autosynth/synthesizer.py\", line 120, in synthesize\n    synth_proc.check_returncode()  # Raise an exception.\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py\", line 389, in check_returncode\n    self.stderr)\nsubprocess.CalledProcessError: Command '['/tmpfs/src/github/synthtool/env/bin/python3', '-m', 'synthtool', '--metadata', 'synth.metadata', 'synth.py', '--']' returned non-zero exit status 1.\n\n```\n\nGoogle internal developers can see the full log [here](http://sponge2/results/invocations/a5363fc2-a05f-48ab-bef5-ec3365f70a0c/targets/github%2Fsynthtool;config=default/tests;query=python-logging;failed=false).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/44", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/44/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/44/events", "html_url": "https://github.com/googleapis/python-logging/issues/44", "id": 645864895, "node_id": "MDU6SXNzdWU2NDU4NjQ4OTU=", "number": 44, "title": "getting started sample shows how to iterate over empty logs list", "user": {"login": "simonz130", "id": 32641282, "node_id": "MDQ6VXNlcjMyNjQxMjgy", "avatar_url": "https://avatars0.githubusercontent.com/u/32641282?v=4", "gravatar_id": "", "url": "https://api.github.com/users/simonz130", "html_url": "https://github.com/simonz130", "followers_url": "https://api.github.com/users/simonz130/followers", "following_url": "https://api.github.com/users/simonz130/following{/other_user}", "gists_url": "https://api.github.com/users/simonz130/gists{/gist_id}", "starred_url": "https://api.github.com/users/simonz130/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/simonz130/subscriptions", "organizations_url": "https://api.github.com/users/simonz130/orgs", "repos_url": "https://api.github.com/users/simonz130/repos", "events_url": "https://api.github.com/users/simonz130/events{/privacy}", "received_events_url": "https://api.github.com/users/simonz130/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1814803623, "node_id": "MDU6TGFiZWwxODE0ODAzNjIz", "url": "https://api.github.com/repos/googleapis/python-logging/labels/priority:%20p2", "name": "priority: p2", "color": "fef2c0", "default": false, "description": "Lowest priority. Fix may not be included in next release."}], "state": "closed", "locked": false, "assignee": {"login": "simonz130", "id": 32641282, "node_id": "MDQ6VXNlcjMyNjQxMjgy", "avatar_url": "https://avatars0.githubusercontent.com/u/32641282?v=4", "gravatar_id": "", "url": "https://api.github.com/users/simonz130", "html_url": "https://github.com/simonz130", "followers_url": "https://api.github.com/users/simonz130/followers", "following_url": "https://api.github.com/users/simonz130/following{/other_user}", "gists_url": "https://api.github.com/users/simonz130/gists{/gist_id}", "starred_url": "https://api.github.com/users/simonz130/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/simonz130/subscriptions", "organizations_url": "https://api.github.com/users/simonz130/orgs", "repos_url": "https://api.github.com/users/simonz130/repos", "events_url": "https://api.github.com/users/simonz130/events{/privacy}", "received_events_url": "https://api.github.com/users/simonz130/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "simonz130", "id": 32641282, "node_id": "MDQ6VXNlcjMyNjQxMjgy", "avatar_url": "https://avatars0.githubusercontent.com/u/32641282?v=4", "gravatar_id": "", "url": "https://api.github.com/users/simonz130", "html_url": "https://github.com/simonz130", "followers_url": "https://api.github.com/users/simonz130/followers", "following_url": "https://api.github.com/users/simonz130/following{/other_user}", "gists_url": "https://api.github.com/users/simonz130/gists{/gist_id}", "starred_url": "https://api.github.com/users/simonz130/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/simonz130/subscriptions", "organizations_url": "https://api.github.com/users/simonz130/orgs", "repos_url": "https://api.github.com/users/simonz130/repos", "events_url": "https://api.github.com/users/simonz130/events{/privacy}", "received_events_url": "https://api.github.com/users/simonz130/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 0, "created_at": "2020-06-25T21:34:31Z", "updated_at": "2020-07-01T17:14:05Z", "closed_at": "2020-07-01T17:14:05Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/42", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/42/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/42/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/42/events", "html_url": "https://github.com/googleapis/python-logging/issues/42", "id": 642395259, "node_id": "MDU6SXNzdWU2NDIzOTUyNTk=", "number": 42, "title": "Synthesis failed for python-logging", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1840715666, "node_id": "MDU6TGFiZWwxODQwNzE1NjY2", "url": "https://api.github.com/repos/googleapis/python-logging/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814803657, "node_id": "MDU6TGFiZWwxODE0ODAzNjU3", "url": "https://api.github.com/repos/googleapis/python-logging/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814803535, "node_id": "MDU6TGFiZWwxODE0ODAzNTM1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2020-06-20T15:21:24Z", "updated_at": "2020-06-27T00:00:52Z", "closed_at": "2020-06-27T00:00:52Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-logging. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\n a new branch to retain commits you create, you may\ndo so (now or later) by using -b with the checkout command again. Example:\n\n  git checkout -b <new-branch-name>\n\nHEAD is now at cdddf13 feat: implement multiple version for nodejs lib (#504)\n2020-06-20 08:21:16,778 autosynth [DEBUG] > Running: git checkout aaff764c185e18a6c73227357c3df5fa60fec85a\nNote: checking out 'aaff764c185e18a6c73227357c3df5fa60fec85a'.\n\nYou are in 'detached HEAD' state. You can look around, make experimental\nchanges and commit them, and you can discard any commits you make in this\nstate without impacting any branches by performing another checkout.\n\nIf you want to create a new branch to retain commits you create, you may\ndo so (now or later) by using -b with the checkout command again. Example:\n\n  git checkout -b <new-branch-name>\n\nHEAD is now at aaff764c chore: enable gapicv2 and annotate protos for recommendationengine/v1beta1 API\n2020-06-20 08:21:16,885 autosynth [DEBUG] > Running: git branch -f autosynth-self-2\n2020-06-20 08:21:16,890 autosynth [DEBUG] > Running: git checkout autosynth-self-2\nSwitched to branch 'autosynth-self-2'\n2020-06-20 08:21:16,895 autosynth [INFO] > Running synthtool\n2020-06-20 08:21:16,895 autosynth [INFO] > ['/tmpfs/src/github/synthtool/env/bin/python3', '-m', 'synthtool', '--metadata', 'synth.metadata', 'synth.py', '--']\n2020-06-20 08:21:16,895 autosynth [DEBUG] > log_file_path: /tmpfs/src/github/synthtool/logs/googleapis/python-logging/self/2/sponge_log.log\n2020-06-20 08:21:16,897 autosynth [DEBUG] > Running: /tmpfs/src/github/synthtool/env/bin/python3 -m synthtool --metadata synth.metadata synth.py --\n2020-06-20 08:21:17,111 synthtool [DEBUG] > Executing /home/kbuilder/.cache/synthtool/python-logging/synth.py.\nOn branch autosynth-self-2\nnothing to commit, working tree clean\n2020-06-20 08:21:17,244 synthtool [DEBUG] > Ensuring dependencies.\n2020-06-20 08:21:17,256 synthtool [DEBUG] > Using precloned repo /home/kbuilder/.cache/synthtool/synthtool\n2020-06-20 08:21:17,260 synthtool [DEBUG] > Cloning googleapis.\n2020-06-20 08:21:17,261 synthtool [DEBUG] > Using precloned repo /home/kbuilder/.cache/synthtool/googleapis\n2020-06-20 08:21:17,264 synthtool [DEBUG] > Generating code for: //google/logging/v2:logging-v2-py.\n2020-06-20 08:21:21,077 synthtool [ERROR] > Failed executing bazel --max_idle_secs=60 build //google/logging/v2:logging-v2-py:\n\nLoading: \nLoading: 0 packages loaded\nLoading: 0 packages loaded\nINFO: SHA256 (https://github.com/googleapis/gapic-generator/archive/a59457d24bd6f3c962c8e699c708121c928eedc8.zip) = 843bcf262d44f6a2c1c131844ff8ef40daf95dd3b7c95dd761656f9e010d06d7\nLoading: 0 packages loaded\nDEBUG: Rule 'com_google_api_codegen' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"843bcf262d44f6a2c1c131844ff8ef40daf95dd3b7c95dd761656f9e010d06d7\"\nDEBUG: Call stack for the definition of repository 'com_google_api_codegen' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:62:1\nINFO: SHA256 (https://github.com/googleapis/protoc-java-resource-names-plugin/archive/64dafb71ea9a385a8da89989f0b9dab925bf4610.zip) = f475903e83904dbbe3651abae8cbf57ed804960a0dadd9cbde41b746db645052\nDEBUG: Rule 'com_google_protoc_java_resource_names_plugin' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"f475903e83904dbbe3651abae8cbf57ed804960a0dadd9cbde41b746db645052\"\nDEBUG: Call stack for the definition of repository 'com_google_protoc_java_resource_names_plugin' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:155:1\nLoading: 0 packages loaded\nINFO: SHA256 (https://github.com/googleapis/gapic-generator-go/archive/v0.13.3.tar.gz) = c18388bb1f1318dc5b00d9727beb9f9a079b64c2ef96a93cee83b5e11e172f02\nDEBUG: Rule 'com_googleapis_gapic_generator_go' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = \"c18388bb1f1318dc5b00d9727beb9f9a079b64c2ef96a93cee83b5e11e172f02\"\nDEBUG: Call stack for the definition of repository 'com_googleapis_gapic_generator_go' which is a http_archive (rule definition at /home/kbuilder/.cache/bazel/_bazel_kbuilder/a732f932c2cbeb7e37e1543f189a2a73/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):\n - <builtin>\n - /home/kbuilder/.cache/synthtool/googleapis/WORKSPACE:209:1\nAnalyzing: target //google/logging/v2:logging-v2-py (1 packages loaded, 0 targets configured)\nERROR: While resolving toolchains for target @pypi_black//:black: invalid registered toolchain '@gapic_generator_python//:pyenv3_toolchain': no such package '@gapic_generator_python//': The repository '@gapic_generator_python' could not be resolved\nERROR: Analysis of target '//google/logging/v2:logging-v2-py' failed; build aborted: invalid registered toolchain '@gapic_generator_python//:pyenv3_toolchain': no such package '@gapic_generator_python//': The repository '@gapic_generator_python' could not be resolved\nINFO: Elapsed time: 3.797s\nINFO: 0 processes.\nFAILED: Build did NOT complete successfully (10 packages loaded, 14 targets configured)\nFAILED: Build did NOT complete successfully (10 packages loaded, 14 targets configured)\n\n2020-06-20 08:21:21,078 synthtool [DEBUG] > Wrote metadata to synth.metadata.\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/github/synthtool/synthtool/__main__.py\", line 102, in <module>\n    main()\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/tmpfs/src/github/synthtool/synthtool/__main__.py\", line 94, in main\n    spec.loader.exec_module(synth_module)  # type: ignore\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/home/kbuilder/.cache/synthtool/python-logging/synth.py\", line 29, in <module>\n    include_protos=True,\n  File \"/tmpfs/src/github/synthtool/synthtool/gcp/gapic_bazel.py\", line 46, in py_library\n    return self._generate_code(service, version, \"python\", **kwargs)\n  File \"/tmpfs/src/github/synthtool/synthtool/gcp/gapic_bazel.py\", line 180, in _generate_code\n    shell.run(bazel_run_args)\n  File \"/tmpfs/src/github/synthtool/synthtool/shell.py\", line 39, in run\n    raise exc\n  File \"/tmpfs/src/github/synthtool/synthtool/shell.py\", line 33, in run\n    encoding=\"utf-8\",\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py\", line 438, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['bazel', '--max_idle_secs=60', 'build', '//google/logging/v2:logging-v2-py']' returned non-zero exit status 1.\n2020-06-20 08:21:21,158 autosynth [ERROR] > Synthesis failed\n2020-06-20 08:21:21,159 autosynth [DEBUG] > Running: git reset --hard HEAD\nHEAD is now at 6dde25e chore: Migrate python-logging synth.py from artman to bazel (#35)\n2020-06-20 08:21:21,166 autosynth [DEBUG] > Running: git checkout autosynth-self\nSwitched to branch 'autosynth-self'\n2020-06-20 08:21:21,173 autosynth [ERROR] > Command '['/tmpfs/src/github/synthtool/env/bin/python3', '-m', 'synthtool', '--metadata', 'synth.metadata', 'synth.py', '--']' returned non-zero exit status 1.\n2020-06-20 08:21:21,369 autosynth [INFO] > PR already exists: https://github.com/googleapis/python-logging/pull/41\n2020-06-20 08:21:21,370 autosynth [DEBUG] > Running: git clean -fdx\nRemoving __pycache__/\nRemoving google/__pycache__/\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 649, in <module>\n    main()\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 506, in main\n    return _inner_main(temp_dir)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 629, in _inner_main\n    commit_count = synthesize_loop(x, multiple_prs, change_pusher, synthesizer)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 367, in synthesize_loop\n    synthesize_inner_loop(fork, synthesizer)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 411, in synthesize_inner_loop\n    synthesizer, len(toolbox.versions) - 1\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 266, in synthesize_version_in_new_branch\n    synthesizer.synthesize(synth_log_path, self.environ)\n  File \"/tmpfs/src/github/synthtool/autosynth/synthesizer.py\", line 120, in synthesize\n    synth_proc.check_returncode()  # Raise an exception.\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py\", line 389, in check_returncode\n    self.stderr)\nsubprocess.CalledProcessError: Command '['/tmpfs/src/github/synthtool/env/bin/python3', '-m', 'synthtool', '--metadata', 'synth.metadata', 'synth.py', '--']' returned non-zero exit status 1.\n\n```\n\nGoogle internal developers can see the full log [here](http://sponge2/results/invocations/e93a3b66-0b9d-4731-8049-5d33389af1dc/targets/github%2Fsynthtool;config=default/tests;query=python-logging;failed=false).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/33", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/33/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/33/events", "html_url": "https://github.com/googleapis/python-logging/issues/33", "id": 586064196, "node_id": "MDU6SXNzdWU1ODYwNjQxOTY=", "number": 33, "title": "Enable retries on RESOURCE_EXHAUSTED", "user": {"login": "predatorhmo", "id": 4621172, "node_id": "MDQ6VXNlcjQ2MjExNzI=", "avatar_url": "https://avatars2.githubusercontent.com/u/4621172?v=4", "gravatar_id": "", "url": "https://api.github.com/users/predatorhmo", "html_url": "https://github.com/predatorhmo", "followers_url": "https://api.github.com/users/predatorhmo/followers", "following_url": "https://api.github.com/users/predatorhmo/following{/other_user}", "gists_url": "https://api.github.com/users/predatorhmo/gists{/gist_id}", "starred_url": "https://api.github.com/users/predatorhmo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/predatorhmo/subscriptions", "organizations_url": "https://api.github.com/users/predatorhmo/orgs", "repos_url": "https://api.github.com/users/predatorhmo/repos", "events_url": "https://api.github.com/users/predatorhmo/events{/privacy}", "received_events_url": "https://api.github.com/users/predatorhmo/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1814803604, "node_id": "MDU6TGFiZWwxODE0ODAzNjA0", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20question", "name": "type: question", "color": "c5def5", "default": false, "description": "Request for information or clarification. Not an issue."}], "state": "closed", "locked": false, "assignee": {"login": "busunkim96", "id": 8822365, "node_id": "MDQ6VXNlcjg4MjIzNjU=", "avatar_url": "https://avatars1.githubusercontent.com/u/8822365?v=4", "gravatar_id": "", "url": "https://api.github.com/users/busunkim96", "html_url": "https://github.com/busunkim96", "followers_url": "https://api.github.com/users/busunkim96/followers", "following_url": "https://api.github.com/users/busunkim96/following{/other_user}", "gists_url": "https://api.github.com/users/busunkim96/gists{/gist_id}", "starred_url": "https://api.github.com/users/busunkim96/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/busunkim96/subscriptions", "organizations_url": "https://api.github.com/users/busunkim96/orgs", "repos_url": "https://api.github.com/users/busunkim96/repos", "events_url": "https://api.github.com/users/busunkim96/events{/privacy}", "received_events_url": "https://api.github.com/users/busunkim96/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "busunkim96", "id": 8822365, "node_id": "MDQ6VXNlcjg4MjIzNjU=", "avatar_url": "https://avatars1.githubusercontent.com/u/8822365?v=4", "gravatar_id": "", "url": "https://api.github.com/users/busunkim96", "html_url": "https://github.com/busunkim96", "followers_url": "https://api.github.com/users/busunkim96/followers", "following_url": "https://api.github.com/users/busunkim96/following{/other_user}", "gists_url": "https://api.github.com/users/busunkim96/gists{/gist_id}", "starred_url": "https://api.github.com/users/busunkim96/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/busunkim96/subscriptions", "organizations_url": "https://api.github.com/users/busunkim96/orgs", "repos_url": "https://api.github.com/users/busunkim96/repos", "events_url": "https://api.github.com/users/busunkim96/events{/privacy}", "received_events_url": "https://api.github.com/users/busunkim96/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 2, "created_at": "2020-03-23T09:35:23Z", "updated_at": "2020-03-27T10:39:09Z", "closed_at": "2020-03-24T16:46:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nIn project I'm working on we started to face **Log ingestion requests per minute** issue. In this case, python throws exception with **RESOURCE_EXHAUSTED** error status code, which also means that this log message is lost for Stackdriver.\r\n\r\nAs I saw from source code (pls correct me if I'm wrong), there's some kind of retry mechanism implemented during writing logs, but only for certain error codes. So it would be great to have ability to customize retries when write logs to Stackdriver (I my case I want to enable retry on **RESOURCE_EXHAUSTED** error)\r\n\r\nThanks in advance.\r\n\r\nAttaching link to question on Stackoverflow: https://stackoverflow.com/questions/60799003/configure-stackdriver-logging-to-retry-on-resource-exhausted\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/27", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/27/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/27/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/27/events", "html_url": "https://github.com/googleapis/python-logging/issues/27", "id": 570767708, "node_id": "MDU6SXNzdWU1NzA3Njc3MDg=", "number": 27, "title": "Testing: drop majyk coverage number: `--cov-fail-under=97`", "user": {"login": "tseaver", "id": 242750, "node_id": "MDQ6VXNlcjI0Mjc1MA==", "avatar_url": "https://avatars2.githubusercontent.com/u/242750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tseaver", "html_url": "https://github.com/tseaver", "followers_url": "https://api.github.com/users/tseaver/followers", "following_url": "https://api.github.com/users/tseaver/following{/other_user}", "gists_url": "https://api.github.com/users/tseaver/gists{/gist_id}", "starred_url": "https://api.github.com/users/tseaver/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tseaver/subscriptions", "organizations_url": "https://api.github.com/users/tseaver/orgs", "repos_url": "https://api.github.com/users/tseaver/repos", "events_url": "https://api.github.com/users/tseaver/events{/privacy}", "received_events_url": "https://api.github.com/users/tseaver/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1870733728, "node_id": "MDU6TGFiZWwxODcwNzMzNzI4", "url": "https://api.github.com/repos/googleapis/python-logging/labels/testing", "name": "testing", "color": "5aaae2", "default": false, "description": ""}, {"id": 1814803587, "node_id": "MDU6TGFiZWwxODE0ODAzNTg3", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20process", "name": "type: process", "color": "c5def5", "default": false, "description": "A process-releated concern. May include testing, release, or the like."}], "state": "closed", "locked": false, "assignee": {"login": "tseaver", "id": 242750, "node_id": "MDQ6VXNlcjI0Mjc1MA==", "avatar_url": "https://avatars2.githubusercontent.com/u/242750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tseaver", "html_url": "https://github.com/tseaver", "followers_url": "https://api.github.com/users/tseaver/followers", "following_url": "https://api.github.com/users/tseaver/following{/other_user}", "gists_url": "https://api.github.com/users/tseaver/gists{/gist_id}", "starred_url": "https://api.github.com/users/tseaver/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tseaver/subscriptions", "organizations_url": "https://api.github.com/users/tseaver/orgs", "repos_url": "https://api.github.com/users/tseaver/repos", "events_url": "https://api.github.com/users/tseaver/events{/privacy}", "received_events_url": "https://api.github.com/users/tseaver/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "tseaver", "id": 242750, "node_id": "MDQ6VXNlcjI0Mjc1MA==", "avatar_url": "https://avatars2.githubusercontent.com/u/242750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tseaver", "html_url": "https://github.com/tseaver", "followers_url": "https://api.github.com/users/tseaver/followers", "following_url": "https://api.github.com/users/tseaver/following{/other_user}", "gists_url": "https://api.github.com/users/tseaver/gists{/gist_id}", "starred_url": "https://api.github.com/users/tseaver/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tseaver/subscriptions", "organizations_url": "https://api.github.com/users/tseaver/orgs", "repos_url": "https://api.github.com/users/tseaver/repos", "events_url": "https://api.github.com/users/tseaver/events{/privacy}", "received_events_url": "https://api.github.com/users/tseaver/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 0, "created_at": "2020-02-25T19:01:48Z", "updated_at": "2020-02-26T09:46:59Z", "closed_at": "2020-02-26T09:46:59Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/25", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/25/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/25/events", "html_url": "https://github.com/googleapis/python-logging/issues/25", "id": 568302868, "node_id": "MDU6SXNzdWU1NjgzMDI4Njg=", "number": 25, "title": "Synthesis failed for python-logging", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803799, "node_id": "MDU6TGFiZWwxODE0ODAzNzk5", "url": "https://api.github.com/repos/googleapis/python-logging/labels/:rotating_light:", "name": ":rotating_light:", "color": "FFFFFF", "default": false, "description": "This issue needs some love."}, {"id": 1840715666, "node_id": "MDU6TGFiZWwxODQwNzE1NjY2", "url": "https://api.github.com/repos/googleapis/python-logging/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814803657, "node_id": "MDU6TGFiZWwxODE0ODAzNjU3", "url": "https://api.github.com/repos/googleapis/python-logging/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814803535, "node_id": "MDU6TGFiZWwxODE0ODAzNTM1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-02-20T13:34:12Z", "updated_at": "2020-04-06T17:09:55Z", "closed_at": "2020-02-20T23:24:52Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-logging. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\nCloning into 'working_repo'...\nSwitched to branch 'autosynth'\nRunning synthtool\n['/tmpfs/src/git/autosynth/env/bin/python3', '-m', 'synthtool', 'synth.py', '--']\nsynthtool > Executing /tmpfs/src/git/autosynth/working_repo/synth.py.\nOn branch autosynth\nnothing to commit, working tree clean\nHEAD detached at FETCH_HEAD\nnothing to commit, working tree clean\nsynthtool > Ensuring dependencies.\nsynthtool > Pulling artman image.\nlatest: Pulling from googleapis/artman\nDigest: sha256:6aec9c34db0e4be221cdaf6faba27bdc07cfea846808b3d3b964dfce3a9a0f9b\nStatus: Image is up to date for googleapis/artman:latest\nsynthtool > Cloning googleapis.\nsynthtool > Running generator for google/logging/artman_logging.yaml.\nsynthtool > Generated code into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2.\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/logging.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/logging.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/logging_config.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/logging_config.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/log_entry.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/log_entry.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/logging_metrics.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/logging_metrics.proto\nsynthtool > Placed proto files into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto.\n.coveragerc\n.flake8\n.github/CONTRIBUTING.md\n.github/ISSUE_TEMPLATE/bug_report.md\n.github/ISSUE_TEMPLATE/feature_request.md\n.github/ISSUE_TEMPLATE/support_request.md\n.github/PULL_REQUEST_TEMPLATE.md\n.github/release-please.yml\n.gitignore\n.kokoro/build.sh\n.kokoro/continuous/common.cfg\n.kokoro/continuous/continuous.cfg\n.kokoro/docs/common.cfg\n.kokoro/docs/docs.cfg\n.kokoro/presubmit/common.cfg\n.kokoro/presubmit/presubmit.cfg\n.kokoro/publish-docs.sh\n.kokoro/release.sh\n.kokoro/release/common.cfg\n.kokoro/release/release.cfg\n.kokoro/trampoline.sh\nCODE_OF_CONDUCT.md\nCONTRIBUTING.rst\nLICENSE\nMANIFEST.in\ndocs/_static/custom.css\ndocs/_templates/layout.html\ndocs/conf.py.j2\nnoxfile.py.j2\nrenovate.json\nsetup.cfg\nRunning session blacken\nCreating virtual environment (virtualenv) using python3.6 in .nox/blacken\npip install black\nError: pip is not installed into the virtualenv, it is located at /tmpfs/src/git/autosynth/env/bin/pip. Pass external=True into run() to explicitly allow this.\nSession blacken failed.\nsynthtool > Failed executing nox -s blacken:\n\nNone\nsynthtool > Wrote metadata to synth.metadata.\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 102, in <module>\n    main()\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 94, in main\n    spec.loader.exec_module(synth_module)  # type: ignore\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 205, in _call_with_frames_removed\n  File \"/tmpfs/src/git/autosynth/working_repo/synth.py\", line 48, in <module>\n    s.shell.run([\"nox\", \"-s\", \"blacken\"], hide_output=False)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 39, in run\n    raise exc\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 33, in run\n    encoding=\"utf-8\",\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py\", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['nox', '-s', 'blacken']' returned non-zero exit status 1.\n\nSynthesis failed\n\n```\n\nGoogle internal developers can see the full log [here](https://sponge/bc296324-7867-4eae-a113-8090e6bcc834).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/20", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/20/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/20/events", "html_url": "https://github.com/googleapis/python-logging/issues/20", "id": 563204311, "node_id": "MDU6SXNzdWU1NjMyMDQzMTE=", "number": 20, "title": "Synthesis failed for python-logging", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803799, "node_id": "MDU6TGFiZWwxODE0ODAzNzk5", "url": "https://api.github.com/repos/googleapis/python-logging/labels/:rotating_light:", "name": ":rotating_light:", "color": "FFFFFF", "default": false, "description": "This issue needs some love."}, {"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1840715666, "node_id": "MDU6TGFiZWwxODQwNzE1NjY2", "url": "https://api.github.com/repos/googleapis/python-logging/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814803657, "node_id": "MDU6TGFiZWwxODE0ODAzNjU3", "url": "https://api.github.com/repos/googleapis/python-logging/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814803535, "node_id": "MDU6TGFiZWwxODE0ODAzNTM1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 10, "created_at": "2020-02-11T13:24:27Z", "updated_at": "2020-02-19T02:31:01Z", "closed_at": "2020-02-19T02:31:01Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-logging. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\nCloning into 'working_repo'...\nSwitched to branch 'autosynth'\nRunning synthtool\n['/tmpfs/src/git/autosynth/env/bin/python3', '-m', 'synthtool', 'synth.py', '--']\nsynthtool > Executing /tmpfs/src/git/autosynth/working_repo/synth.py.\nsynthtool > Ensuring dependencies.\nsynthtool > Pulling artman image.\nlatest: Pulling from googleapis/artman\nDigest: sha256:6aec9c34db0e4be221cdaf6faba27bdc07cfea846808b3d3b964dfce3a9a0f9b\nStatus: Image is up to date for googleapis/artman:latest\nsynthtool > Cloning googleapis.\nsynthtool > Running generator for google/logging/artman_logging.yaml.\nsynthtool > Generated code into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2.\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/logging.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/logging.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/logging_config.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/logging_config.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/log_entry.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/log_entry.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/logging/v2/logging_metrics.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto/logging_metrics.proto\nsynthtool > Placed proto files into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/logging-v2/google/cloud/logging_v2/proto.\n.coveragerc\n.flake8\n.github/CONTRIBUTING.md\n.github/ISSUE_TEMPLATE/bug_report.md\n.github/ISSUE_TEMPLATE/feature_request.md\n.github/ISSUE_TEMPLATE/support_request.md\n.github/PULL_REQUEST_TEMPLATE.md\n.github/release-please.yml\n.gitignore\n.kokoro/build.sh\n.kokoro/continuous/common.cfg\n.kokoro/continuous/continuous.cfg\n.kokoro/docs/common.cfg\n.kokoro/docs/docs.cfg\n.kokoro/presubmit/common.cfg\n.kokoro/presubmit/presubmit.cfg\n.kokoro/publish-docs.sh\n.kokoro/release.sh\n.kokoro/release/common.cfg\n.kokoro/release/release.cfg\n.kokoro/trampoline.sh\nCODE_OF_CONDUCT.md\nCONTRIBUTING.rst\nLICENSE\nMANIFEST.in\ndocs/_static/custom.css\ndocs/_templates/layout.html\ndocs/conf.py.j2\nnoxfile.py.j2\nrenovate.json\nsetup.cfg\nRunning session blacken\nCreating virtual environment (virtualenv) using python3.6 in .nox/blacken\npip install black\nError: pip is not installed into the virtualenv, it is located at /tmpfs/src/git/autosynth/env/bin/pip. Pass external=True into run() to explicitly allow this.\nSession blacken failed.\nsynthtool > Failed executing nox -s blacken:\n\nNone\nsynthtool > Wrote metadata to synth.metadata.\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 99, in <module>\n    main()\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 91, in main\n    spec.loader.exec_module(synth_module)  # type: ignore\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 205, in _call_with_frames_removed\n  File \"/tmpfs/src/git/autosynth/working_repo/synth.py\", line 48, in <module>\n    s.shell.run([\"nox\", \"-s\", \"blacken\"], hide_output=False)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 39, in run\n    raise exc\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 33, in run\n    encoding=\"utf-8\",\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py\", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['nox', '-s', 'blacken']' returned non-zero exit status 1.\n\nSynthesis failed\n\n```\n\nGoogle internal developers can see the full log [here](https://sponge/0ad5873d-3057-4798-a0b0-db4db3218285).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-logging/issues/9", "repository_url": "https://api.github.com/repos/googleapis/python-logging", "labels_url": "https://api.github.com/repos/googleapis/python-logging/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-logging/issues/9/comments", "events_url": "https://api.github.com/repos/googleapis/python-logging/issues/9/events", "html_url": "https://github.com/googleapis/python-logging/issues/9", "id": 560388968, "node_id": "MDU6SXNzdWU1NjAzODg5Njg=", "number": 9, "title": "Create a google-cloud-audit virtual package", "user": {"login": "rsalmond", "id": 4367945, "node_id": "MDQ6VXNlcjQzNjc5NDU=", "avatar_url": "https://avatars0.githubusercontent.com/u/4367945?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rsalmond", "html_url": "https://github.com/rsalmond", "followers_url": "https://api.github.com/users/rsalmond/followers", "following_url": "https://api.github.com/users/rsalmond/following{/other_user}", "gists_url": "https://api.github.com/users/rsalmond/gists{/gist_id}", "starred_url": "https://api.github.com/users/rsalmond/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rsalmond/subscriptions", "organizations_url": "https://api.github.com/users/rsalmond/orgs", "repos_url": "https://api.github.com/users/rsalmond/repos", "events_url": "https://api.github.com/users/rsalmond/events{/privacy}", "received_events_url": "https://api.github.com/users/rsalmond/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814803275, "node_id": "MDU6TGFiZWwxODE0ODAzMjc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/api:%20logging", "name": "api: logging", "color": "ad8a22", "default": false, "description": "Issues related to the Stackdriver Logging API."}, {"id": 1814803575, "node_id": "MDU6TGFiZWwxODE0ODAzNTc1", "url": "https://api.github.com/repos/googleapis/python-logging/labels/type:%20feature%20request", "name": "type: feature request", "color": "c5def5", "default": false, "description": "\u2018Nice-to-have\u2019 improvement, new feature or different behavior or design."}], "state": "closed", "locked": false, "assignee": {"login": "busunkim96", "id": 8822365, "node_id": "MDQ6VXNlcjg4MjIzNjU=", "avatar_url": "https://avatars1.githubusercontent.com/u/8822365?v=4", "gravatar_id": "", "url": "https://api.github.com/users/busunkim96", "html_url": "https://github.com/busunkim96", "followers_url": "https://api.github.com/users/busunkim96/followers", "following_url": "https://api.github.com/users/busunkim96/following{/other_user}", "gists_url": "https://api.github.com/users/busunkim96/gists{/gist_id}", "starred_url": "https://api.github.com/users/busunkim96/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/busunkim96/subscriptions", "organizations_url": "https://api.github.com/users/busunkim96/orgs", "repos_url": "https://api.github.com/users/busunkim96/repos", "events_url": "https://api.github.com/users/busunkim96/events{/privacy}", "received_events_url": "https://api.github.com/users/busunkim96/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "busunkim96", "id": 8822365, "node_id": "MDQ6VXNlcjg4MjIzNjU=", "avatar_url": "https://avatars1.githubusercontent.com/u/8822365?v=4", "gravatar_id": "", "url": "https://api.github.com/users/busunkim96", "html_url": "https://github.com/busunkim96", "followers_url": "https://api.github.com/users/busunkim96/followers", "following_url": "https://api.github.com/users/busunkim96/following{/other_user}", "gists_url": "https://api.github.com/users/busunkim96/gists{/gist_id}", "starred_url": "https://api.github.com/users/busunkim96/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/busunkim96/subscriptions", "organizations_url": "https://api.github.com/users/busunkim96/orgs", "repos_url": "https://api.github.com/users/busunkim96/repos", "events_url": "https://api.github.com/users/busunkim96/events{/privacy}", "received_events_url": "https://api.github.com/users/busunkim96/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 10, "created_at": "2019-05-09T22:28:26Z", "updated_at": "2020-07-31T20:38:59Z", "closed_at": "2020-07-31T20:38:59Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": " **Is your feature request related to a problem? Please describe.**\r\nYes, users of the logging module are [opening spurious bugs](https://github.com/googleapis/google-cloud-python/issues/5322) and [conflating issues](https://github.com/googleapis/google-cloud-python/issues/3218) due to the lack of a clear path to deserializing AuditLog objects\r\n\r\nWithout the presence of a python compiled copy of [the AuditLog protocol definition](https://github.com/googleapis/googleapis/blob/master/google/cloud/audit/audit_log.proto), users of the logging client library cannot deserialize [audit log entries](https://cloud.google.com/logging/docs/audit/understanding-audit-logs) that have been returned by the logging API in the form of a serialized `proto_payload`.\r\n\r\nLast summer @tseaver [rightly points out](https://github.com/googleapis/google-cloud-python/issues/5514#issuecomment-399200147) that it cannot be expected for the logging module to assume the type of a field declared as `Any`. However given that the [LogEntry protocol definition](https://github.com/jmorenog/googleapis-googleapis/blob/2b09d506fa548359bec747ef7757e43dd58e348f/google/api/servicecontrol/v1/log_entry.proto#L54-L57) suggests that AuditLog is the _only_ currently accepted type it seems a poor developer experience for users to need to understand protobuf well enough to download and compile the definition themselves.\r\n\r\n **Describe the solution you'd like**\r\nThe creation of a new `google-cloud-audit` virtual package containing the python version of the AuditLog protocol definition.\r\n\r\n **Describe alternatives you've considered**\r\nAs a workaround I have followed [this users link to stackoverflow](https://github.com/googleapis/google-cloud-python/issues/5313#issuecomment-399237060) and compiled the AuditLog pb definition into my project manually.", "performed_via_github_app": null, "score": 1.0}]}