{"total_count": 29, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/59", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/59/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/59/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/59/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/59", "id": 498102675, "node_id": "MDU6SXNzdWU0OTgxMDI2NzU=", "number": 59, "title": "getfilesystemencoding can be None, causing error", "user": {"login": "wryun", "id": 81507, "node_id": "MDQ6VXNlcjgxNTA3", "avatar_url": "https://avatars3.githubusercontent.com/u/81507?v=4", "gravatar_id": "", "url": "https://api.github.com/users/wryun", "html_url": "https://github.com/wryun", "followers_url": "https://api.github.com/users/wryun/followers", "following_url": "https://api.github.com/users/wryun/following{/other_user}", "gists_url": "https://api.github.com/users/wryun/gists{/gist_id}", "starred_url": "https://api.github.com/users/wryun/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/wryun/subscriptions", "organizations_url": "https://api.github.com/users/wryun/orgs", "repos_url": "https://api.github.com/users/wryun/repos", "events_url": "https://api.github.com/users/wryun/events{/privacy}", "received_events_url": "https://api.github.com/users/wryun/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2019-09-25T07:31:17Z", "updated_at": "2019-09-27T07:37:34Z", "closed_at": "2019-09-27T07:08:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "In Python before 3.2, it's possible to get None from this. However AWS Codebuild is setting things up, this causes pathlib2 to explode:\r\n\r\n```\r\n...\r\n  File \"/codebuild/output/src991325250/src/github.com/.../ve-web/local/lib/python2.7/site-packages/pathlib2/__init__.py\", line 928, in _make_child \r\n    drv, root, parts = self._parse_args(args) \r\n  File \"/codebuild/output/src991325250/src/github.com/.../ve-web/local/lib/python2.7/site-packages/pathlib2/__init__.py\", line 885, in _parse_args \r\n    parts.append(a.encode(sys.getfilesystemencoding())) \r\nTypeError: encode() argument 1 must be string, not None \r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/56", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/56/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/56/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/56/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/56", "id": 453874922, "node_id": "MDU6SXNzdWU0NTM4NzQ5MjI=", "number": 56, "title": "Unusable on Windows/Python2.7 with unicode paths", "user": {"login": "Suor", "id": 284103, "node_id": "MDQ6VXNlcjI4NDEwMw==", "avatar_url": "https://avatars0.githubusercontent.com/u/284103?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Suor", "html_url": "https://github.com/Suor", "followers_url": "https://api.github.com/users/Suor/followers", "following_url": "https://api.github.com/users/Suor/following{/other_user}", "gists_url": "https://api.github.com/users/Suor/gists{/gist_id}", "starred_url": "https://api.github.com/users/Suor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Suor/subscriptions", "organizations_url": "https://api.github.com/users/Suor/orgs", "repos_url": "https://api.github.com/users/Suor/repos", "events_url": "https://api.github.com/users/Suor/events{/privacy}", "received_events_url": "https://api.github.com/users/Suor/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 12, "created_at": "2019-06-09T08:14:58Z", "updated_at": "2019-06-14T08:36:04Z", "closed_at": "2019-06-14T08:36:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "The issue is that `sys.getfilesystemencoding() == \"mcbs\"` on Windows/Python 2.7, which is lossy. So one looses info when passes path as unicode to `Path`.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/54", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/54/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/54/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/54/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/54", "id": 434474686, "node_id": "MDU6SXNzdWU0MzQ0NzQ2ODY=", "number": 54, "title": "resolve raises a WindowsError in py2.7 when a path does not exist.", "user": {"login": "danbradham", "id": 3354242, "node_id": "MDQ6VXNlcjMzNTQyNDI=", "avatar_url": "https://avatars3.githubusercontent.com/u/3354242?v=4", "gravatar_id": "", "url": "https://api.github.com/users/danbradham", "html_url": "https://github.com/danbradham", "followers_url": "https://api.github.com/users/danbradham/followers", "following_url": "https://api.github.com/users/danbradham/following{/other_user}", "gists_url": "https://api.github.com/users/danbradham/gists{/gist_id}", "starred_url": "https://api.github.com/users/danbradham/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/danbradham/subscriptions", "organizations_url": "https://api.github.com/users/danbradham/orgs", "repos_url": "https://api.github.com/users/danbradham/repos", "events_url": "https://api.github.com/users/danbradham/events{/privacy}", "received_events_url": "https://api.github.com/users/danbradham/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-04-17T20:36:13Z", "updated_at": "2019-05-14T14:25:12Z", "closed_at": "2019-05-14T14:25:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "the **resolve** method is not behaving as expected in python2.7 when called with a path that does not exist.\r\n\r\n**Expected behavior**\r\n```\r\nPython 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> from pathlib import Path\r\n>>> Path('~/does_not_exist').resolve()\r\nWindowsPath('~/does_not_exist')\r\n```\r\n```\r\nPython 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> from pathlib2 import Path\r\n>>> Path('~/does_not_exist').resolve()\r\nWindowsPath('~/does_not_exist')\r\n```\r\n\r\n**Actual behavior**\r\n```\r\nPython 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> from pathlib2 import Path\r\n>>> Path('~/does_not_exist').resolve()\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Projects\\python\\construct_org\\construct\\venv27\\lib\\site-packages\\pathlib2\\__init__.py\", line 1343, in resolve\r\n    self.stat()\r\n  File \"C:\\Projects\\python\\construct_org\\construct\\venv27\\lib\\site-packages\\pathlib2\\__init__.py\", line 1356, in stat\r\n    return self._accessor.stat(self)\r\n  File \"C:\\Projects\\python\\construct_org\\construct\\venv27\\lib\\site-packages\\pathlib2\\__init__.py\", line 541, in wrapped\r\n    return strfunc(str(pathobj), *args)\r\nWindowsError: [Error 3] The system cannot find the path specified: '~\\\\does_not_exist'\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/52", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/52/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/52/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/52/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/52", "id": 424930445, "node_id": "MDU6SXNzdWU0MjQ5MzA0NDU=", "number": 52, "title": "handle collections deprecation", "user": {"login": "gaborbernat", "id": 690238, "node_id": "MDQ6VXNlcjY5MDIzOA==", "avatar_url": "https://avatars1.githubusercontent.com/u/690238?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gaborbernat", "html_url": "https://github.com/gaborbernat", "followers_url": "https://api.github.com/users/gaborbernat/followers", "following_url": "https://api.github.com/users/gaborbernat/following{/other_user}", "gists_url": "https://api.github.com/users/gaborbernat/gists{/gist_id}", "starred_url": "https://api.github.com/users/gaborbernat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gaborbernat/subscriptions", "organizations_url": "https://api.github.com/users/gaborbernat/orgs", "repos_url": "https://api.github.com/users/gaborbernat/repos", "events_url": "https://api.github.com/users/gaborbernat/events{/privacy}", "received_events_url": "https://api.github.com/users/gaborbernat/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2019-03-25T14:24:35Z", "updated_at": "2019-03-26T14:14:18Z", "closed_at": "2019-03-26T14:14:18Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "```\r\n/pathlib2/__init__.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\r\n    from collections import Sequence\r\n\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/49", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/49/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/49/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/49", "id": 417228161, "node_id": "MDU6SXNzdWU0MTcyMjgxNjE=", "number": 49, "title": "Path().glob() returns paths with corrupted case on Windows", "user": {"login": "nikos-r35", "id": 7923787, "node_id": "MDQ6VXNlcjc5MjM3ODc=", "avatar_url": "https://avatars0.githubusercontent.com/u/7923787?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nikos-r35", "html_url": "https://github.com/nikos-r35", "followers_url": "https://api.github.com/users/nikos-r35/followers", "following_url": "https://api.github.com/users/nikos-r35/following{/other_user}", "gists_url": "https://api.github.com/users/nikos-r35/gists{/gist_id}", "starred_url": "https://api.github.com/users/nikos-r35/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nikos-r35/subscriptions", "organizations_url": "https://api.github.com/users/nikos-r35/orgs", "repos_url": "https://api.github.com/users/nikos-r35/repos", "events_url": "https://api.github.com/users/nikos-r35/events{/privacy}", "received_events_url": "https://api.github.com/users/nikos-r35/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-03-05T10:34:14Z", "updated_at": "2019-05-07T11:24:25Z", "closed_at": "2019-05-07T11:24:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "Using Python 3.7.2 with pathlib2 2.3.3 on Windows 10.\r\n\r\n```\r\nD:\\tmp>dir /S\r\n \u0422\u043e\u043c \u0432 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 D \u0438\u043c\u0435\u0435\u0442 \u043c\u0435\u0442\u043a\u0443 Data\r\n \u0421\u0435\u0440\u0438\u0439\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0442\u043e\u043c\u0430: 6408-3709\r\n\r\n \u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435 \u043f\u0430\u043f\u043a\u0438 D:\\tmp\r\n\r\n05.03.2019  13:28    <DIR>          .\r\n05.03.2019  13:28    <DIR>          ..\r\n05.03.2019  13:28    <DIR>          MySubDir\r\n05.03.2019  13:23                 0 My_File.txt\r\n               1 \u0444\u0430\u0439\u043b\u043e\u0432              0 \u0431\u0430\u0439\u0442\r\n\r\n \u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435 \u043f\u0430\u043f\u043a\u0438 D:\\tmp\\MySubDir\r\n\r\n05.03.2019  13:28    <DIR>          .\r\n05.03.2019  13:28    <DIR>          ..\r\n05.03.2019  13:28    <DIR>          MySubDir2\r\n05.03.2019  13:23                 0 my_file2.txt\r\n               1 \u0444\u0430\u0439\u043b\u043e\u0432              0 \u0431\u0430\u0439\u0442\r\n\r\n \u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435 \u043f\u0430\u043f\u043a\u0438 D:\\tmp\\MySubDir\\MySubDir2\r\n\r\n05.03.2019  13:28    <DIR>          .\r\n05.03.2019  13:28    <DIR>          ..\r\n05.03.2019  13:28                 0 my_file3.TXT\r\n               1 \u0444\u0430\u0439\u043b\u043e\u0432              0 \u0431\u0430\u0439\u0442\r\n\r\n     \u0412\u0441\u0435\u0433\u043e \u0444\u0430\u0439\u043b\u043e\u0432:\r\n               3 \u0444\u0430\u0439\u043b\u043e\u0432              0 \u0431\u0430\u0439\u0442\r\n               8 \u043f\u0430\u043f\u043e\u043a  978\u00a0329\u00a0309\u00a0184 \u0431\u0430\u0439\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u043e\r\n```\r\n\r\n```\r\nPython 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> from pathlib2 import *\r\n>>> p = Path('.')\r\n>>> print([x for x in p.glob('My_File.txt')])\r\n[WindowsPath('my_file.txt')]\r\n>>> print([x for x in p.glob('*')])\r\n[WindowsPath('MySubDir'), WindowsPath('My_File.txt')]\r\n>>> print([x for x in p.glob('*/my_file2.txt')])\r\n[WindowsPath('MySubDir/my_file2.txt')]\r\n>>> print([x for x in p.glob('MySubDir/MySubDir2/my_file3.TXT')])\r\n[WindowsPath('mysubdir/mysubdir2/my_file3.txt')]\r\n>>> print([x for x in p.glob('*MySubDir/MySubDir2/my_file3.TXT')])\r\n[WindowsPath('MySubDir/mysubdir2/my_file3.txt')]\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/48", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/48/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/48/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/48/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/48", "id": 409780454, "node_id": "MDU6SXNzdWU0MDk3ODA0NTQ=", "number": 48, "title": "A support for absolute path in `glob()` is required", "user": {"login": "minherz", "id": 3994488, "node_id": "MDQ6VXNlcjM5OTQ0ODg=", "avatar_url": "https://avatars2.githubusercontent.com/u/3994488?v=4", "gravatar_id": "", "url": "https://api.github.com/users/minherz", "html_url": "https://github.com/minherz", "followers_url": "https://api.github.com/users/minherz/followers", "following_url": "https://api.github.com/users/minherz/following{/other_user}", "gists_url": "https://api.github.com/users/minherz/gists{/gist_id}", "starred_url": "https://api.github.com/users/minherz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/minherz/subscriptions", "organizations_url": "https://api.github.com/users/minherz/orgs", "repos_url": "https://api.github.com/users/minherz/repos", "events_url": "https://api.github.com/users/minherz/events{/privacy}", "received_events_url": "https://api.github.com/users/minherz/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-02-13T12:25:23Z", "updated_at": "2019-03-13T12:49:52Z", "closed_at": "2019-03-12T18:15:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "Currently, it is required to split a wildcard path to a directory part before to be able to list all relevant files using `glob()` call. It will be useful to feature support of the absolute path in `glob()` as well as relative.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/47", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/47/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/47/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/47/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/47", "id": 390936648, "node_id": "MDU6SXNzdWUzOTA5MzY2NDg=", "number": 47, "title": "Calling Path.exists() on non-existent drive raises WindowsError", "user": {"login": "assumptionsoup", "id": 278467, "node_id": "MDQ6VXNlcjI3ODQ2Nw==", "avatar_url": "https://avatars0.githubusercontent.com/u/278467?v=4", "gravatar_id": "", "url": "https://api.github.com/users/assumptionsoup", "html_url": "https://github.com/assumptionsoup", "followers_url": "https://api.github.com/users/assumptionsoup/followers", "following_url": "https://api.github.com/users/assumptionsoup/following{/other_user}", "gists_url": "https://api.github.com/users/assumptionsoup/gists{/gist_id}", "starred_url": "https://api.github.com/users/assumptionsoup/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/assumptionsoup/subscriptions", "organizations_url": "https://api.github.com/users/assumptionsoup/orgs", "repos_url": "https://api.github.com/users/assumptionsoup/repos", "events_url": "https://api.github.com/users/assumptionsoup/events{/privacy}", "received_events_url": "https://api.github.com/users/assumptionsoup/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2018-12-14T02:08:55Z", "updated_at": "2019-03-11T09:14:18Z", "closed_at": "2019-01-08T11:15:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "Any idea why this is happening?\r\n\r\n```\r\n>>> import pathlib2 as pathlib\r\n>>> pathlib.Path(r\"E:\\Whatever\\blah.txt\").exists()\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"P:\\common\\rez\\packages\\pathlib2\\2.3.2\\pathlib2\\__init__.py\", line 1549, in exists\r\n    self.stat()\r\n  File \"P:\\common\\rez\\packages\\pathlib2\\2.3.2\\pathlib2\\__init__.py\", line 1356, in stat\r\n    return self._accessor.stat(self)\r\n  File \"P:\\common\\rez\\packages\\pathlib2\\2.3.2\\pathlib2\\__init__.py\", line 541, in wrapped\r\n    return strfunc(str(pathobj), *args)\r\nWindowsError: [Error 21] The device is not ready: 'E:\\\\Whatever\\\\blah.txt'\r\n>>> import os\r\n>>> os.path.exists(r\"E:\\Whatever\\blah.txt\")\r\nFalse\r\n>>> pathlib.Path(r\"C:\\whatever\\blah.txt\").exists()\r\nFalse\r\n```\r\n\r\nI tested this with version 2.3.2 and the latest commit 87f9a0e8c69a593c92d02aec9e4d6baefe012252", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/46", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/46/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/46/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/46/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/46", "id": 361585827, "node_id": "MDU6SXNzdWUzNjE1ODU4Mjc=", "number": 46, "title": "Pathlib2 switched to new syntax in setup.py without bumping major or minor version", "user": {"login": "zvezdan", "id": 2942065, "node_id": "MDQ6VXNlcjI5NDIwNjU=", "avatar_url": "https://avatars0.githubusercontent.com/u/2942065?v=4", "gravatar_id": "", "url": "https://api.github.com/users/zvezdan", "html_url": "https://github.com/zvezdan", "followers_url": "https://api.github.com/users/zvezdan/followers", "following_url": "https://api.github.com/users/zvezdan/following{/other_user}", "gists_url": "https://api.github.com/users/zvezdan/gists{/gist_id}", "starred_url": "https://api.github.com/users/zvezdan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/zvezdan/subscriptions", "organizations_url": "https://api.github.com/users/zvezdan/orgs", "repos_url": "https://api.github.com/users/zvezdan/repos", "events_url": "https://api.github.com/users/zvezdan/events{/privacy}", "received_events_url": "https://api.github.com/users/zvezdan/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-09-19T05:39:25Z", "updated_at": "2018-11-29T12:52:37Z", "closed_at": "2018-11-29T12:52:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "The switch to new syntax for conditional dependencies in _pathlib2-2.3.2_ causes issues to automated build tooling that uses _pex_. This line: https://github.com/mcmtroffaes/pathlib2/blob/develop/setup.py#L47 used to be done in `extras_require` instead of `install_requires`.\r\n\r\nRecent versions of _setuptools_ and _wheel_ are able to parse this new syntax, but older versions enforced by _pex_ are not: https://github.com/pantsbuild/pex/blob/v1.4.5/pex/version.py#L9\r\nUntil recently, _wheel_ was also forced to version that is not able to parse new syntax: https://github.com/pantsbuild/pex/blob/v1.4.4/pex/version.py#L11\r\n\r\nThis would be less of an issue if _pathlib2_ bumped a version in major or minor instead of just patch part of the version number. This is a breaking change for build systems that worked just fine with _pathlib2-2.3.0_.\r\n\r\nI'm asking if we can do one or both of the following to fix this issue.\r\n\r\n1. Revert to `extras_require` in version 2.3.x of _pathlib_, preferably 2.x and perhaps use it only for the next major version?\r\n2. Perhaps avoid using the new syntax entirely? This is a backport package and those who need a backport package most probably do not have up-to-date environment anyway to parse the new features.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/45", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/45/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/45/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/45", "id": 348372011, "node_id": "MDU6SXNzdWUzNDgzNzIwMTE=", "number": 45, "title": "resolve() is always strict with Python 2.7 on Windows", "user": {"login": "matthew16550", "id": 39400458, "node_id": "MDQ6VXNlcjM5NDAwNDU4", "avatar_url": "https://avatars2.githubusercontent.com/u/39400458?v=4", "gravatar_id": "", "url": "https://api.github.com/users/matthew16550", "html_url": "https://github.com/matthew16550", "followers_url": "https://api.github.com/users/matthew16550/followers", "following_url": "https://api.github.com/users/matthew16550/following{/other_user}", "gists_url": "https://api.github.com/users/matthew16550/gists{/gist_id}", "starred_url": "https://api.github.com/users/matthew16550/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/matthew16550/subscriptions", "organizations_url": "https://api.github.com/users/matthew16550/orgs", "repos_url": "https://api.github.com/users/matthew16550/repos", "events_url": "https://api.github.com/users/matthew16550/events{/privacy}", "received_events_url": "https://api.github.com/users/matthew16550/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-08-07T15:26:04Z", "updated_at": "2019-01-07T09:15:04Z", "closed_at": "2019-01-07T09:15:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm using pathlib2 version 2.3.2.\r\n\r\nOn Windows with Python 2.7 the strict=False option has no effect:\r\n```\r\nPython 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import pathlib2\r\n>>> pathlib2.Path('foo').resolve(False)\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"c:\\Python27\\lib\\site-packages\\pathlib2\\__init__.py\", line 1343, in resolve\r\n    self.stat()\r\n  File \"c:\\Python27\\lib\\site-packages\\pathlib2\\__init__.py\", line 1356, in stat\r\n    return self._accessor.stat(self)\r\n  File \"c:\\Python27\\lib\\site-packages\\pathlib2\\__init__.py\", line 541, in wrapped\r\n    return strfunc(str(pathobj), *args)\r\nWindowsError: [Error 2] The system cannot find the file specified: 'foo'\r\n```\r\n\r\nOn OSX with Python 2.7 it works ok:\r\n```\r\nPython 2.7.15 (default, Jun 17 2018, 13:05:56)\r\n[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import pathlib2\r\n>>> pathlib2.Path('/foo').resolve(False)\r\nPosixPath('/foo')\r\n```\r\n\r\nAnd on Windows with Python 3.7 it works ok:\r\n```\r\nPython 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import pathlib2\r\n>>> pathlib2.Path('foo').resolve(False)\r\nWindowsPath('foo')\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/44", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/44/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/44/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/44", "id": 334078962, "node_id": "MDU6SXNzdWUzMzQwNzg5NjI=", "number": 44, "title": "Permission to add stubs for pathlib2 to typeshed", "user": {"login": "li-dan", "id": 26881569, "node_id": "MDQ6VXNlcjI2ODgxNTY5", "avatar_url": "https://avatars1.githubusercontent.com/u/26881569?v=4", "gravatar_id": "", "url": "https://api.github.com/users/li-dan", "html_url": "https://github.com/li-dan", "followers_url": "https://api.github.com/users/li-dan/followers", "following_url": "https://api.github.com/users/li-dan/following{/other_user}", "gists_url": "https://api.github.com/users/li-dan/gists{/gist_id}", "starred_url": "https://api.github.com/users/li-dan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/li-dan/subscriptions", "organizations_url": "https://api.github.com/users/li-dan/orgs", "repos_url": "https://api.github.com/users/li-dan/repos", "events_url": "https://api.github.com/users/li-dan/events{/privacy}", "received_events_url": "https://api.github.com/users/li-dan/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-06-20T13:33:29Z", "updated_at": "2018-06-20T15:53:01Z", "closed_at": "2018-06-20T15:53:01Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am interested in adding a [PEP 484](https://www.python.org/dev/peps/pep-0484/) stub file for pathlib2 to the [typeshed](https://github.com/python/typeshed). Before accepting stubs for third party libraries, they need the maintainers to give permission, as detailed [here](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library).\r\n\r\nIs it okay to add a stub file for pathlib2 to the typeshed?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/43", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/43/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/43/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/43/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/43", "id": 333098236, "node_id": "MDU6SXNzdWUzMzMwOTgyMzY=", "number": 43, "title": "Pathlib does not compare Windows and MinGW paths as equal", "user": {"login": "Paebbels", "id": 956109, "node_id": "MDQ6VXNlcjk1NjEwOQ==", "avatar_url": "https://avatars0.githubusercontent.com/u/956109?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Paebbels", "html_url": "https://github.com/Paebbels", "followers_url": "https://api.github.com/users/Paebbels/followers", "following_url": "https://api.github.com/users/Paebbels/following{/other_user}", "gists_url": "https://api.github.com/users/Paebbels/gists{/gist_id}", "starred_url": "https://api.github.com/users/Paebbels/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Paebbels/subscriptions", "organizations_url": "https://api.github.com/users/Paebbels/orgs", "repos_url": "https://api.github.com/users/Paebbels/repos", "events_url": "https://api.github.com/users/Paebbels/events{/privacy}", "received_events_url": "https://api.github.com/users/Paebbels/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-06-17T22:30:59Z", "updated_at": "2018-06-18T13:49:22Z", "closed_at": "2018-06-18T13:49:22Z", "author_association": "NONE", "active_lock_reason": null, "body": "`pathlib` does not compare absolute paths from Windows and MinGW as equal.\r\n\r\nWindows absolute path: `C:\\path\\to\\tool`  \r\nMinGW absolute path: `/c/path/to/tool`  \r\nCygwin absolute path: `/cygdrive/c/path/to/tool`  \r\n\r\nI consider this a bug, because it's the same bug but 3 different writings and pathlib is not able to identify the equality.\r\n\r\n**This issues is also listed here:**\r\n\r\n* [Python issue 33890](https://bugs.python.org/issue33890) - Pathlib does not compare Windows and MinGW paths as equal\r\n* [How to compare absolute Windows and MinGW paths with pathlib?](https://stackoverflow.com/questions/50900779/how-to-compare-absolute-windows-and-mingw-paths-with-pathlib)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/40", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/40/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/40/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/40/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/40", "id": 312767332, "node_id": "MDU6SXNzdWUzMTI3NjczMzI=", "number": 40, "title": "Cannot instantiate subclass", "user": {"login": "stevecj", "id": 388671, "node_id": "MDQ6VXNlcjM4ODY3MQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/388671?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stevecj", "html_url": "https://github.com/stevecj", "followers_url": "https://api.github.com/users/stevecj/followers", "following_url": "https://api.github.com/users/stevecj/following{/other_user}", "gists_url": "https://api.github.com/users/stevecj/gists{/gist_id}", "starred_url": "https://api.github.com/users/stevecj/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stevecj/subscriptions", "organizations_url": "https://api.github.com/users/stevecj/orgs", "repos_url": "https://api.github.com/users/stevecj/repos", "events_url": "https://api.github.com/users/stevecj/events{/privacy}", "received_events_url": "https://api.github.com/users/stevecj/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-04-10T04:16:30Z", "updated_at": "2018-04-10T10:04:07Z", "closed_at": "2018-04-10T10:04:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "Should it be possible to subclass Path and create instances without having to figure out a special trick?\r\n\r\nWhen I try to create an instance of a subclass, I get\u2026\r\n\r\n```\r\ntype object 'Path' has no attribute '_flavour'\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/39", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/39/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/39/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/39/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/39", "id": 302067506, "node_id": "MDU6SXNzdWUzMDIwNjc1MDY=", "number": 39, "title": "Python 3.6.4: AttributeError: module 'test.support' has no attribute 'android_not_root'", "user": {"login": "mgorny", "id": 110765, "node_id": "MDQ6VXNlcjExMDc2NQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/110765?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mgorny", "html_url": "https://github.com/mgorny", "followers_url": "https://api.github.com/users/mgorny/followers", "following_url": "https://api.github.com/users/mgorny/following{/other_user}", "gists_url": "https://api.github.com/users/mgorny/gists{/gist_id}", "starred_url": "https://api.github.com/users/mgorny/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mgorny/subscriptions", "organizations_url": "https://api.github.com/users/mgorny/orgs", "repos_url": "https://api.github.com/users/mgorny/repos", "events_url": "https://api.github.com/users/mgorny/events{/privacy}", "received_events_url": "https://api.github.com/users/mgorny/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-03-04T08:29:29Z", "updated_at": "2018-04-20T07:28:55Z", "closed_at": "2018-04-19T07:40:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "When trying to run tests on Python 3.6.4:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"test_pathlib2.py\", line 48, in <module>\r\n    android_not_root = support.android_not_root\r\nAttributeError: module 'test.support' has no attribute 'android_not_root'\r\n```\r\n\r\nDidn't anyone tell you that using private Python modules is a recipe for disaster?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/36", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/36/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/36/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/36/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/36", "id": 291681015, "node_id": "MDU6SXNzdWUyOTE2ODEwMTU=", "number": 36, "title": "Consider `tox` for testing", "user": {"login": "clbarnes", "id": 8995328, "node_id": "MDQ6VXNlcjg5OTUzMjg=", "avatar_url": "https://avatars0.githubusercontent.com/u/8995328?v=4", "gravatar_id": "", "url": "https://api.github.com/users/clbarnes", "html_url": "https://github.com/clbarnes", "followers_url": "https://api.github.com/users/clbarnes/followers", "following_url": "https://api.github.com/users/clbarnes/following{/other_user}", "gists_url": "https://api.github.com/users/clbarnes/gists{/gist_id}", "starred_url": "https://api.github.com/users/clbarnes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/clbarnes/subscriptions", "organizations_url": "https://api.github.com/users/clbarnes/orgs", "repos_url": "https://api.github.com/users/clbarnes/repos", "events_url": "https://api.github.com/users/clbarnes/events{/privacy}", "received_events_url": "https://api.github.com/users/clbarnes/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-01-25T19:06:51Z", "updated_at": "2019-03-11T09:17:20Z", "closed_at": "2019-03-11T09:17:06Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "As a backport library, pathlib2 rightly tests against many different versions of python, and as such contains a complex system of shims filling in and renaming stdlib stuff. Running the tests to make sure that these all still work after any change means maintaining 9 different virtualenvs, which is a hassle and a barrier to entry for contributors.\r\n\r\n[Tox](https://tox.readthedocs.io/en/latest/) (and its extension for parallel testing, [detox](https://pypi.python.org/pypi/detox)) could control setting up and tearing down all the different virtualenvs, making it *much* easier to test locally, and keeping the test environment consistent between the local and CI environments.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/35", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/35/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/35/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/35/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/35", "id": 279792587, "node_id": "MDU6SXNzdWUyNzk3OTI1ODc=", "number": 35, "title": "`os.path.join` compatibility", "user": {"login": "clbarnes", "id": 8995328, "node_id": "MDQ6VXNlcjg5OTUzMjg=", "avatar_url": "https://avatars0.githubusercontent.com/u/8995328?v=4", "gravatar_id": "", "url": "https://api.github.com/users/clbarnes", "html_url": "https://github.com/clbarnes", "followers_url": "https://api.github.com/users/clbarnes/followers", "following_url": "https://api.github.com/users/clbarnes/following{/other_user}", "gists_url": "https://api.github.com/users/clbarnes/gists{/gist_id}", "starred_url": "https://api.github.com/users/clbarnes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/clbarnes/subscriptions", "organizations_url": "https://api.github.com/users/clbarnes/orgs", "repos_url": "https://api.github.com/users/clbarnes/repos", "events_url": "https://api.github.com/users/clbarnes/events{/privacy}", "received_events_url": "https://api.github.com/users/clbarnes/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2017-12-06T15:23:32Z", "updated_at": "2019-06-07T12:50:18Z", "closed_at": "2019-06-07T12:50:18Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "In python 3, `os.path.join(pathlib.Path('my/path'), 'my.file')` returns a string, `my/path/my.file`.\r\n\r\nHowever, `os.path.join(pathlib2.Path('my/path'), 'my.file')` raises an AttributeError:\r\n\r\n```python\r\n     68         if b.startswith('/'):\r\n     69             path = b\r\n---> 70         elif path == '' or path.endswith('/'):\r\n     71             path +=  b\r\n     72         else:\r\n\r\nAttributeError: 'PosixPath' object has no attribute 'endswith'\r\n```\r\n\r\nThis is an issue for someone trying to gradually port a large codebase over to using `Path`s\r\n\r\nWhile strictly speaking, this may be due to py2's implementation of `os.path.join` rather than `pathlib2`'s implementation of `PurePath`, it may be useful to reverse engineer compatibility for such a common path operation.\r\n\r\nUsually, this would require implementing `startswith`, `endswith`, and `__iadd__` on `PurePath`. However, giving `pathlib2.PurePath` a significant amount of behaviour not seen in the 'real' `PurePath` doesn't seem like a good idea. Is there another way round it? Is it possible for importing `pathlib2` to insert a shim into `os.path`?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/34", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/34/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/34/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/34", "id": 276829307, "node_id": "MDU6SXNzdWUyNzY4MjkzMDc=", "number": 34, "title": "Unicode issues", "user": {"login": "Dobatymo", "id": 7647594, "node_id": "MDQ6VXNlcjc2NDc1OTQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/7647594?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Dobatymo", "html_url": "https://github.com/Dobatymo", "followers_url": "https://api.github.com/users/Dobatymo/followers", "following_url": "https://api.github.com/users/Dobatymo/following{/other_user}", "gists_url": "https://api.github.com/users/Dobatymo/gists{/gist_id}", "starred_url": "https://api.github.com/users/Dobatymo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Dobatymo/subscriptions", "organizations_url": "https://api.github.com/users/Dobatymo/orgs", "repos_url": "https://api.github.com/users/Dobatymo/repos", "events_url": "https://api.github.com/users/Dobatymo/events{/privacy}", "received_events_url": "https://api.github.com/users/Dobatymo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-11-26T14:37:16Z", "updated_at": "2019-06-07T12:55:36Z", "closed_at": "2019-06-07T12:55:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "Python 2.7.13, pathlib2-2.3.0\r\n\r\nIf the the input to path is unicode, the output of Path functions is not unicode but str. In python 3 both will be unicode.\r\n\r\nIn python 2 str input should result in str, unicode in unicode output. This would also be consistent to how python 2 stdlib functions work.\r\n\r\n```python\r\n>>> from pathlib2 import Path\r\n>>> Path(u\"/asd\").parts\r\n('\\\\', 'asd')\r\n>>> Path(u\"/asd\").name\r\n'asd'\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/31", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/31/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/31/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/31", "id": 244997937, "node_id": "MDU6SXNzdWUyNDQ5OTc5Mzc=", "number": 31, "title": "os.scandir only supported by python 3.6", "user": {"login": "marbre", "id": 8095156, "node_id": "MDQ6VXNlcjgwOTUxNTY=", "avatar_url": "https://avatars2.githubusercontent.com/u/8095156?v=4", "gravatar_id": "", "url": "https://api.github.com/users/marbre", "html_url": "https://github.com/marbre", "followers_url": "https://api.github.com/users/marbre/followers", "following_url": "https://api.github.com/users/marbre/following{/other_user}", "gists_url": "https://api.github.com/users/marbre/gists{/gist_id}", "starred_url": "https://api.github.com/users/marbre/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/marbre/subscriptions", "organizations_url": "https://api.github.com/users/marbre/orgs", "repos_url": "https://api.github.com/users/marbre/repos", "events_url": "https://api.github.com/users/marbre/events{/privacy}", "received_events_url": "https://api.github.com/users/marbre/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-07-24T07:49:36Z", "updated_at": "2017-07-25T07:32:37Z", "closed_at": "2017-07-25T07:32:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "I recently tried to version bump the Gentoo Linux pathlib2 ebuild. Unfortunately, the tests fail with `ImportError: No module named scandir`. With a quick look to the python docs it seems that `os.scandir` is only available with python 3.6. I would suggest to either drop scandir or modify the supported python versions in the setup.py accordingly.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/30", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/30/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/30/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/30", "id": 236251779, "node_id": "MDU6SXNzdWUyMzYyNTE3Nzk=", "number": 30, "title": "tests fail for: UnicodeEncodeError: 'ascii' codec can't encode character u'\\u0100' in position 0: ordinal not in range(128)", "user": {"login": "yurivict", "id": 271906, "node_id": "MDQ6VXNlcjI3MTkwNg==", "avatar_url": "https://avatars2.githubusercontent.com/u/271906?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yurivict", "html_url": "https://github.com/yurivict", "followers_url": "https://api.github.com/users/yurivict/followers", "following_url": "https://api.github.com/users/yurivict/following{/other_user}", "gists_url": "https://api.github.com/users/yurivict/gists{/gist_id}", "starred_url": "https://api.github.com/users/yurivict/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yurivict/subscriptions", "organizations_url": "https://api.github.com/users/yurivict/orgs", "repos_url": "https://api.github.com/users/yurivict/repos", "events_url": "https://api.github.com/users/yurivict/events{/privacy}", "received_events_url": "https://api.github.com/users/yurivict/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 15, "created_at": "2017-06-15T16:48:19Z", "updated_at": "2017-07-25T10:12:11Z", "closed_at": "2017-07-25T10:12:11Z", "author_association": "NONE", "active_lock_reason": null, "body": "Tests are:\r\n```\r\npython2 test_pathlib2.py\r\npython2 test_pathlib2_with_py2_unicode_literals.py\r\n```\r\nThey fail for 2.2.1 and 2.3.0.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/28", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/28/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/28/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/28/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/28", "id": 234797781, "node_id": "MDU6SXNzdWUyMzQ3OTc3ODE=", "number": 28, "title": "pathlib.resolve(strict=False) only includes first child", "user": {"login": "phill-85", "id": 4619659, "node_id": "MDQ6VXNlcjQ2MTk2NTk=", "avatar_url": "https://avatars2.githubusercontent.com/u/4619659?v=4", "gravatar_id": "", "url": "https://api.github.com/users/phill-85", "html_url": "https://github.com/phill-85", "followers_url": "https://api.github.com/users/phill-85/followers", "following_url": "https://api.github.com/users/phill-85/following{/other_user}", "gists_url": "https://api.github.com/users/phill-85/gists{/gist_id}", "starred_url": "https://api.github.com/users/phill-85/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/phill-85/subscriptions", "organizations_url": "https://api.github.com/users/phill-85/orgs", "repos_url": "https://api.github.com/users/phill-85/repos", "events_url": "https://api.github.com/users/phill-85/events{/privacy}", "received_events_url": "https://api.github.com/users/phill-85/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-06-09T11:22:20Z", "updated_at": "2017-06-12T17:59:18Z", "closed_at": "2017-06-12T14:32:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "This issue has been fixed in Python, just wanted to make sue you guys were aware of it!\r\nhttp://bugs.python.org/issue30177", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/25", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/25/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/25/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/25", "id": 213415958, "node_id": "MDU6SXNzdWUyMTM0MTU5NTg=", "number": 25, "title": "_try_except_permissionerror_iter() passed unexpected argument to except_iter", "user": {"login": "IlyaSukhanov", "id": 1637068, "node_id": "MDQ6VXNlcjE2MzcwNjg=", "avatar_url": "https://avatars0.githubusercontent.com/u/1637068?v=4", "gravatar_id": "", "url": "https://api.github.com/users/IlyaSukhanov", "html_url": "https://github.com/IlyaSukhanov", "followers_url": "https://api.github.com/users/IlyaSukhanov/followers", "following_url": "https://api.github.com/users/IlyaSukhanov/following{/other_user}", "gists_url": "https://api.github.com/users/IlyaSukhanov/gists{/gist_id}", "starred_url": "https://api.github.com/users/IlyaSukhanov/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/IlyaSukhanov/subscriptions", "organizations_url": "https://api.github.com/users/IlyaSukhanov/orgs", "repos_url": "https://api.github.com/users/IlyaSukhanov/repos", "events_url": "https://api.github.com/users/IlyaSukhanov/events{/privacy}", "received_events_url": "https://api.github.com/users/IlyaSukhanov/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-03-10T18:25:59Z", "updated_at": "2017-03-16T14:45:53Z", "closed_at": "2017-03-16T14:45:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "except_iter() function is often defined without an argument and then passed to _try_except_permissionerror_iter() which invokes except_iter() with an exception as argument. As a result there are several scenarios where pathlib2 errors our with less than clear stack trace.\r\n\r\nFor example when glob is called on dir to which process does not have read access Pathlib2 raises TypeError:\r\n```\r\n  File \"/usr/local/lib/python2.7/dist-packages/foo/bar.py\", line 80, in list_unprocessed\r\n    for f in self.path.glob(glob)\r\n  File \"/usr/local/lib/python2.7/dist-packages/pathlib2.py\", line 1281, in glob\r\n    for p in selector.select_from(self):\r\n  File \"/usr/local/lib/python2.7/dist-packages/pathlib2.py\", line 686, in _select_from\r\n    for x in _try_except_permissionerror_iter(try_iter, except_iter):\r\n  File \"/usr/local/lib/python2.7/dist-packages/pathlib2.py\", line 97, in _try_except_permissionerror_iter\r\n    for x in except_iter(exc):\r\nTypeError: except_iter() takes no arguments (1 given)\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/24", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/24/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/24/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/24/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/24", "id": 208293516, "node_id": "MDU6SXNzdWUyMDgyOTM1MTY=", "number": 24, "title": "Pathlib2 2.2.1 fails to install on TravisCI", "user": {"login": "relwell", "id": 232917, "node_id": "MDQ6VXNlcjIzMjkxNw==", "avatar_url": "https://avatars0.githubusercontent.com/u/232917?v=4", "gravatar_id": "", "url": "https://api.github.com/users/relwell", "html_url": "https://github.com/relwell", "followers_url": "https://api.github.com/users/relwell/followers", "following_url": "https://api.github.com/users/relwell/following{/other_user}", "gists_url": "https://api.github.com/users/relwell/gists{/gist_id}", "starred_url": "https://api.github.com/users/relwell/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/relwell/subscriptions", "organizations_url": "https://api.github.com/users/relwell/orgs", "repos_url": "https://api.github.com/users/relwell/repos", "events_url": "https://api.github.com/users/relwell/events{/privacy}", "received_events_url": "https://api.github.com/users/relwell/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-02-17T00:25:58Z", "updated_at": "2017-03-16T15:00:59Z", "closed_at": "2017-03-16T15:00:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "You can refer to https://github.com/solrcloudpy/solrcloudpy/pull/41 as a history of me trying to figure out why my project's builds are failing, and isolating it to version 2.2.1 instead of 2.2.0. My project has IPython as dependency, which has Pathlib2 as a dependency. Since I wasn't pegged to 2.2.0, previous builds passed, but builds that use 2.2.1 fail.\r\n\r\nYou can see in [this build in particular](https://travis-ci.org/solrcloudpy/solrcloudpy/builds/202455533#L264-L273) that version 2.2.1 fails because it now claims to only support Python version 3.5 or greater.\r\n\r\nIf we have introduced a breaking change where pathlib2 no longer supports 2.7, this probably should be a major version bump rather than a patch bump.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/23", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/23/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/23/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/23/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/23", "id": 205122543, "node_id": "MDU6SXNzdWUyMDUxMjI1NDM=", "number": 23, "title": "resovle() does not throw OSError when the path does not exits", "user": {"login": "anuragagarwal561994", "id": 6075379, "node_id": "MDQ6VXNlcjYwNzUzNzk=", "avatar_url": "https://avatars1.githubusercontent.com/u/6075379?v=4", "gravatar_id": "", "url": "https://api.github.com/users/anuragagarwal561994", "html_url": "https://github.com/anuragagarwal561994", "followers_url": "https://api.github.com/users/anuragagarwal561994/followers", "following_url": "https://api.github.com/users/anuragagarwal561994/following{/other_user}", "gists_url": "https://api.github.com/users/anuragagarwal561994/gists{/gist_id}", "starred_url": "https://api.github.com/users/anuragagarwal561994/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/anuragagarwal561994/subscriptions", "organizations_url": "https://api.github.com/users/anuragagarwal561994/orgs", "repos_url": "https://api.github.com/users/anuragagarwal561994/repos", "events_url": "https://api.github.com/users/anuragagarwal561994/events{/privacy}", "received_events_url": "https://api.github.com/users/anuragagarwal561994/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-02-03T10:34:30Z", "updated_at": "2017-06-12T14:33:54Z", "closed_at": "2017-06-12T14:33:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "On Mac resolve throws OSError when the path does not exists but not linux.\r\n\r\nPython: 2.7", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/20", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/20/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/20/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/20", "id": 201650413, "node_id": "MDU6SXNzdWUyMDE2NTA0MTM=", "number": 20, "title": "You cannot have a py2.py3-none-any.whl if there are version dependent dependancies", "user": {"login": "AvdN", "id": 1210650, "node_id": "MDQ6VXNlcjEyMTA2NTA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1210650?v=4", "gravatar_id": "", "url": "https://api.github.com/users/AvdN", "html_url": "https://github.com/AvdN", "followers_url": "https://api.github.com/users/AvdN/followers", "following_url": "https://api.github.com/users/AvdN/following{/other_user}", "gists_url": "https://api.github.com/users/AvdN/gists{/gist_id}", "starred_url": "https://api.github.com/users/AvdN/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/AvdN/subscriptions", "organizations_url": "https://api.github.com/users/AvdN/orgs", "repos_url": "https://api.github.com/users/AvdN/repos", "events_url": "https://api.github.com/users/AvdN/events{/privacy}", "received_events_url": "https://api.github.com/users/AvdN/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-01-18T18:09:05Z", "updated_at": "2017-01-19T12:40:21Z", "closed_at": "2017-01-19T12:31:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "Installing `pathlib2` version 2.2.0 using `pip` on a Python 3.5 or Python 3.6 will get the wheel and thus install `scandir`. Because the setup.py contains code that depends on the version of Python that runs setup.py, no single py2.py3-none-any wheel can be used as there is no such version dependency within the wheel's metadata file.\r\n\r\nThis is especially harmful because `scandir` (version 1.4) includes test data in its zip file for which the filenames generates errors on extraction on Docker image Ubuntu 16.04 with Python3 installed. Scandir also doesn't seem to be able to handle systems without compiler. \r\n\r\nThis broke one of Docker containers and my current solution is to pin the install on pathlib2. \r\nThe quick solution would be to remove the wheel file from PyPI any new versions should remove the dependency on scandir in `setup.py` until scandir has solved its problems.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/14", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/14/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/14/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/14/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/14", "id": 197224419, "node_id": "MDU6SXNzdWUxOTcyMjQ0MTk=", "number": 14, "title": "Explicit license in source files", "user": {"login": "pcpa", "id": 374719, "node_id": "MDQ6VXNlcjM3NDcxOQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/374719?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pcpa", "html_url": "https://github.com/pcpa", "followers_url": "https://api.github.com/users/pcpa/followers", "following_url": "https://api.github.com/users/pcpa/following{/other_user}", "gists_url": "https://api.github.com/users/pcpa/gists{/gist_id}", "starred_url": "https://api.github.com/users/pcpa/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pcpa/subscriptions", "organizations_url": "https://api.github.com/users/pcpa/orgs", "repos_url": "https://api.github.com/users/pcpa/repos", "events_url": "https://api.github.com/users/pcpa/events{/privacy}", "received_events_url": "https://api.github.com/users/pcpa/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 139036540, "node_id": "MDU6TGFiZWwxMzkwMzY1NDA=", "url": "https://api.github.com/repos/mcmtroffaes/pathlib2/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": true, "assignee": {"login": "mcmtroffaes", "id": 158568, "node_id": "MDQ6VXNlcjE1ODU2OA==", "avatar_url": "https://avatars0.githubusercontent.com/u/158568?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mcmtroffaes", "html_url": "https://github.com/mcmtroffaes", "followers_url": "https://api.github.com/users/mcmtroffaes/followers", "following_url": "https://api.github.com/users/mcmtroffaes/following{/other_user}", "gists_url": "https://api.github.com/users/mcmtroffaes/gists{/gist_id}", "starred_url": "https://api.github.com/users/mcmtroffaes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mcmtroffaes/subscriptions", "organizations_url": "https://api.github.com/users/mcmtroffaes/orgs", "repos_url": "https://api.github.com/users/mcmtroffaes/repos", "events_url": "https://api.github.com/users/mcmtroffaes/events{/privacy}", "received_events_url": "https://api.github.com/users/mcmtroffaes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "mcmtroffaes", "id": 158568, "node_id": "MDQ6VXNlcjE1ODU2OA==", "avatar_url": "https://avatars0.githubusercontent.com/u/158568?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mcmtroffaes", "html_url": "https://github.com/mcmtroffaes", "followers_url": "https://api.github.com/users/mcmtroffaes/followers", "following_url": "https://api.github.com/users/mcmtroffaes/following{/other_user}", "gists_url": "https://api.github.com/users/mcmtroffaes/gists{/gist_id}", "starred_url": "https://api.github.com/users/mcmtroffaes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mcmtroffaes/subscriptions", "organizations_url": "https://api.github.com/users/mcmtroffaes/orgs", "repos_url": "https://api.github.com/users/mcmtroffaes/repos", "events_url": "https://api.github.com/users/mcmtroffaes/events{/privacy}", "received_events_url": "https://api.github.com/users/mcmtroffaes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2016-12-22T17:23:37Z", "updated_at": "2017-01-09T08:56:09Z", "closed_at": "2017-01-09T08:56:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "  I am working on having a python-pathlib2 package in Fedora.\r\n[Review Request: python-pathlib2 - Object-oriented filesystem paths](https://bugzilla.redhat.com/show_bug.cgi?id=1406962)\r\n  One issue is about having only a LICENSE.rst file.\r\n\r\n  It should be enough to have a confirmation that all files are\r\nunder MIT license.\r\n  Otherwise, something like 3 lines header should be enough,\r\nas there is already the LICENSE.rst file. For example:\r\n\r\n```\r\n# Copyright (c) 2014 Matthias C. M. Troffaes\r\n# Copyright (c) 2012-2014 Antoine Pitrou and contributors\r\n# Distributed under the terms of the MIT License.\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/13", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/13/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/13/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/13", "id": 192949832, "node_id": "MDU6SXNzdWUxOTI5NDk4MzI=", "number": 13, "title": "UnicodeEncodeError in Path() for a path with non-ASCII characters", "user": {"login": "native-api", "id": 2670332, "node_id": "MDQ6VXNlcjI2NzAzMzI=", "avatar_url": "https://avatars3.githubusercontent.com/u/2670332?v=4", "gravatar_id": "", "url": "https://api.github.com/users/native-api", "html_url": "https://github.com/native-api", "followers_url": "https://api.github.com/users/native-api/followers", "following_url": "https://api.github.com/users/native-api/following{/other_user}", "gists_url": "https://api.github.com/users/native-api/gists{/gist_id}", "starred_url": "https://api.github.com/users/native-api/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/native-api/subscriptions", "organizations_url": "https://api.github.com/users/native-api/orgs", "repos_url": "https://api.github.com/users/native-api/repos", "events_url": "https://api.github.com/users/native-api/events{/privacy}", "received_events_url": "https://api.github.com/users/native-api/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2016-12-01T20:11:17Z", "updated_at": "2019-06-07T06:17:56Z", "closed_at": "2017-01-09T08:33:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\n>>> pathlib2.Path(u'/c/Documents and Settings/User/\\u041c\\u043e\\u0438 \\u0434\\u043e\\u043a\\u0443\\u043c\\u0435\\u043d\\u0442\\u044b/.ipython/profile_default/db')\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/usr/lib/python2.7/site-packages/pathlib2.py\", line 1095, in __new__\r\n    self = cls._from_parts(args, init=False)\r\n  File \"/usr/lib/python2.7/site-packages/pathlib2.py\", line 760, in _from_parts\r\n    drv, root, parts = self._parse_args(args)\r\n  File \"/usr/lib/python2.7/site-packages/pathlib2.py\", line 748, in _parse_args\r\n    parts.append(str(a))\r\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 31-33: ordinal not in range(128)\r\n```\r\n\r\nAs you may have guessed, this appears when starting `ipython` in Cygwin if Cygwin's home dir is a junction to the Windows one.\r\n\r\nSince `str` is Unicode in Python 3, I believe the error is specific to the backport.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/12", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/12/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/12/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/12", "id": 180409974, "node_id": "MDU6SXNzdWUxODA0MDk5NzQ=", "number": 12, "title": "pathlib assumes windows if a module named nt is importable", "user": {"login": "mkomitee", "id": 826, "node_id": "MDQ6VXNlcjgyNg==", "avatar_url": "https://avatars0.githubusercontent.com/u/826?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mkomitee", "html_url": "https://github.com/mkomitee", "followers_url": "https://api.github.com/users/mkomitee/followers", "following_url": "https://api.github.com/users/mkomitee/following{/other_user}", "gists_url": "https://api.github.com/users/mkomitee/gists{/gist_id}", "starred_url": "https://api.github.com/users/mkomitee/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mkomitee/subscriptions", "organizations_url": "https://api.github.com/users/mkomitee/orgs", "repos_url": "https://api.github.com/users/mkomitee/repos", "events_url": "https://api.github.com/users/mkomitee/events{/privacy}", "received_events_url": "https://api.github.com/users/mkomitee/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-09-30T21:52:23Z", "updated_at": "2016-10-03T07:29:24Z", "closed_at": "2016-10-03T07:29:23Z", "author_association": "NONE", "active_lock_reason": null, "body": "Having an importable module named nt doesn't necessarily mean that the system is windows. \n\nIt may be better to use sys.platform or some similar value in sys to determine what operating system is in use.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/10", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/10/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/10/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/10", "id": 164214532, "node_id": "MDU6SXNzdWUxNjQyMTQ1MzI=", "number": 10, "title": "resync against upstream pathlib?", "user": {"login": "jrobeson", "id": 56908, "node_id": "MDQ6VXNlcjU2OTA4", "avatar_url": "https://avatars0.githubusercontent.com/u/56908?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jrobeson", "html_url": "https://github.com/jrobeson", "followers_url": "https://api.github.com/users/jrobeson/followers", "following_url": "https://api.github.com/users/jrobeson/following{/other_user}", "gists_url": "https://api.github.com/users/jrobeson/gists{/gist_id}", "starred_url": "https://api.github.com/users/jrobeson/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jrobeson/subscriptions", "organizations_url": "https://api.github.com/users/jrobeson/orgs", "repos_url": "https://api.github.com/users/jrobeson/repos", "events_url": "https://api.github.com/users/jrobeson/events{/privacy}", "received_events_url": "https://api.github.com/users/jrobeson/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-07-07T02:09:39Z", "updated_at": "2016-07-11T07:13:28Z", "closed_at": "2016-07-11T07:13:28Z", "author_association": "NONE", "active_lock_reason": null, "body": "I was doing a comparison between pathlib as exists in python git mirror and in this repository. Are you still planning on doing any more releases to keep up with changes up to 3.5?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/8", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/8/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/8/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/8", "id": 120970081, "node_id": "MDU6SXNzdWUxMjA5NzAwODE=", "number": 8, "title": "use \u201cpathlib\u201d as module name", "user": {"login": "flying-sheep", "id": 291575, "node_id": "MDQ6VXNlcjI5MTU3NQ==", "avatar_url": "https://avatars0.githubusercontent.com/u/291575?v=4", "gravatar_id": "", "url": "https://api.github.com/users/flying-sheep", "html_url": "https://github.com/flying-sheep", "followers_url": "https://api.github.com/users/flying-sheep/followers", "following_url": "https://api.github.com/users/flying-sheep/following{/other_user}", "gists_url": "https://api.github.com/users/flying-sheep/gists{/gist_id}", "starred_url": "https://api.github.com/users/flying-sheep/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/flying-sheep/subscriptions", "organizations_url": "https://api.github.com/users/flying-sheep/orgs", "repos_url": "https://api.github.com/users/flying-sheep/repos", "events_url": "https://api.github.com/users/flying-sheep/events{/privacy}", "received_events_url": "https://api.github.com/users/flying-sheep/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2015-12-08T09:39:40Z", "updated_at": "2016-08-30T14:23:28Z", "closed_at": "2015-12-08T13:00:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "i want to use\n\n``` py\nfrom pathlib import Path\nPath('foo').mkdir(exist_ok=True)\n```\n\ninstead of\n\n``` py\ntry:\n    from pathlib import Path\nexcept ImportError:\n    from pathlib2 import Path\nPath('foo').mkdir(exist_ok=True)\n```\n\nthis should be no problem since the stdlib pathlib should be backwards compatible.\n\nin order to make the change backwards compatible, you could make `setup.py` create both `pathlib.py` and a symlink named `pathlib2.py`\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/5", "repository_url": "https://api.github.com/repos/mcmtroffaes/pathlib2", "labels_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/5/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pathlib2/issues/5/events", "html_url": "https://github.com/mcmtroffaes/pathlib2/issues/5", "id": 114880815, "node_id": "MDU6SXNzdWUxMTQ4ODA4MTU=", "number": 5, "title": "need py3.5 pathlib .expanduser method", "user": {"login": "drhirsch", "id": 7458697, "node_id": "MDQ6VXNlcjc0NTg2OTc=", "avatar_url": "https://avatars2.githubusercontent.com/u/7458697?v=4", "gravatar_id": "", "url": "https://api.github.com/users/drhirsch", "html_url": "https://github.com/drhirsch", "followers_url": "https://api.github.com/users/drhirsch/followers", "following_url": "https://api.github.com/users/drhirsch/following{/other_user}", "gists_url": "https://api.github.com/users/drhirsch/gists{/gist_id}", "starred_url": "https://api.github.com/users/drhirsch/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/drhirsch/subscriptions", "organizations_url": "https://api.github.com/users/drhirsch/orgs", "repos_url": "https://api.github.com/users/drhirsch/repos", "events_url": "https://api.github.com/users/drhirsch/events{/privacy}", "received_events_url": "https://api.github.com/users/drhirsch/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": true, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2015-11-03T18:33:20Z", "updated_at": "2016-01-24T17:05:59Z", "closed_at": "2015-11-04T10:59:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "In Python 3.5.0:\n\n```\n  from pathlib import Path\n  f = Path('~')\n  f.expanduser()\n```\n\ngives the home directory full path.\n\nIn Python 3.4.3 with pathlib2 2.0.1:\n\n```\n  from pathlib2 import Path\n  f = Path('~')\n  f.expanduser()\n```\n\ngives `AttributeError: 'PosixPath' object has no attribute 'expanduser'`\n", "performed_via_github_app": null, "score": 1.0}]}