{"total_count": 59, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/plaid/plaid-python/issues/238", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/238/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/238/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/238/events", "html_url": "https://github.com/plaid/plaid-python/issues/238", "id": 665728006, "node_id": "MDU6SXNzdWU2NjU3MjgwMDY=", "number": 238, "title": "Why plaid doesn't respect the account that was selected by the user", "user": {"login": "alirezaseifi", "id": 2680670, "node_id": "MDQ6VXNlcjI2ODA2NzA=", "avatar_url": "https://avatars3.githubusercontent.com/u/2680670?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alirezaseifi", "html_url": "https://github.com/alirezaseifi", "followers_url": "https://api.github.com/users/alirezaseifi/followers", "following_url": "https://api.github.com/users/alirezaseifi/following{/other_user}", "gists_url": "https://api.github.com/users/alirezaseifi/gists{/gist_id}", "starred_url": "https://api.github.com/users/alirezaseifi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alirezaseifi/subscriptions", "organizations_url": "https://api.github.com/users/alirezaseifi/orgs", "repos_url": "https://api.github.com/users/alirezaseifi/repos", "events_url": "https://api.github.com/users/alirezaseifi/events{/privacy}", "received_events_url": "https://api.github.com/users/alirezaseifi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-07-26T07:34:46Z", "updated_at": "2020-07-27T05:35:15Z", "closed_at": "2020-07-27T05:35:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "Here is the code and I'd like to limit the accounts to `credit: ['credit card'],` only\r\n\r\nso the following code works and it's limiting the accounts in Plaid link to only credit cards\r\n```\r\naccountSubtypes: {\r\ncredit: ['credit card'],\r\n},\r\n```\r\n\r\neven thought when I try to get the access_token or get balance it returns all the accounts balances instead of the one that user selected and there's no way for us to know which account was selected by the user.\r\n\r\nhow do I limit the transactions or balance to only one account that User selected at plaid link?\r\n```\r\n\r\n{\r\n\"access_token\": \"access-sandbox-54ada025-8217-4295-a1b9-a1095defb21e\",\r\n\"item_id\": \"74B7Q4x6kqFAel77JmB8HXqA8w4M9vugLgjQG\",\r\n\"request_id\": \"nu1pbdlws41FGxx\"\r\n}\r\n127.0.0.1 - - [24/Jul/2020 22:11:15] \"POST /get_access_token HTTP/1.1\" 200 -\r\n{\r\n\"accounts\": [\r\n{\r\n\"account_id\": \"mmqdLmGQxyS67NkkWlDbSl39PEDey5CLXyZAD\",\r\n\"balances\": {\r\n\"available\": 100,\r\n\"current\": 110,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"0000\",\r\n\"name\": \"Plaid Checking\",\r\n\"official_name\": \"Plaid Gold Standard 0% Interest Checking\",\r\n\"subtype\": \"checking\",\r\n\"type\": \"depository\"\r\n},\r\n{\r\n\"account_id\": \"y4jL34XG1qFB5G33KmXpTJ6lLZz1XQCyw6RDQ\",\r\n\"balances\": {\r\n\"available\": 200,\r\n\"current\": 210,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"1111\",\r\n\"name\": \"Plaid Saving\",\r\n\"official_name\": \"Plaid Silver Standard 0.1% Interest Saving\",\r\n\"subtype\": \"savings\",\r\n\"type\": \"depository\"\r\n},\r\n{\r\n\"account_id\": \"9PxQVPaqXrcADkooKJnqHa9lKjy6owuRgxNEW\",\r\n\"balances\": {\r\n\"available\": null,\r\n\"current\": 1000,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"2222\",\r\n\"name\": \"Plaid CD\",\r\n\"official_name\": \"Plaid Bronze Standard 0.2% Interest CD\",\r\n\"subtype\": \"cd\",\r\n\"type\": \"depository\"\r\n},\r\n{\r\n\"account_id\": \"vx4Z5xwEQXfKqmPPWbX7IPKaLGMmkDCW16QXj\",\r\n\"balances\": {\r\n\"available\": null,\r\n\"current\": 410,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": 2000,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"3333\",\r\n\"name\": \"Plaid Credit Card\",\r\n\"official_name\": \"Plaid Diamond 12.5% APR Interest Credit Card\",\r\n\"subtype\": \"credit card\",\r\n\"type\": \"credit\"\r\n},\r\n{\r\n\"account_id\": \"RzrvVzaWn3fdDBAAXq6rfP6JrpjDVWCRApVG9\",\r\n\"balances\": {\r\n\"available\": 43200,\r\n\"current\": 43200,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"4444\",\r\n\"name\": \"Plaid Money Market\",\r\n\"official_name\": \"Plaid Platinum Standard 1.85% Interest Money Market\",\r\n\"subtype\": \"money market\",\r\n\"type\": \"depository\"\r\n},\r\n{\r\n\"account_id\": \"6azjma3RDlTA4eQQgDP8HKB84L7PjAugeD7xl\",\r\n\"balances\": {\r\n\"available\": null,\r\n\"current\": 320.76,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"5555\",\r\n\"name\": \"Plaid IRA\",\r\n\"official_name\": null,\r\n\"subtype\": \"ira\",\r\n\"type\": \"investment\"\r\n},\r\n{\r\n\"account_id\": \"X4av14eyJPF7wjMMoxdmT1xBoegzdNTdLKAx6\",\r\n\"balances\": {\r\n\"available\": null,\r\n\"current\": 23631.9805,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"6666\",\r\n\"name\": \"Plaid 401k\",\r\n\"official_name\": null,\r\n\"subtype\": \"401k\",\r\n\"type\": \"investment\"\r\n},\r\n{\r\n\"account_id\": \"DgMARgLPX7Cb1DKKGJxPHoZN7beM3BsvJWqXe\",\r\n\"balances\": {\r\n\"available\": null,\r\n\"current\": 65262,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"7777\",\r\n\"name\": \"Plaid Student Loan\",\r\n\"official_name\": null,\r\n\"subtype\": \"student\",\r\n\"type\": \"loan\"\r\n},\r\n{\r\n\"account_id\": \"Vdxv1djbJ4CPBLDDr8jnfq4BaEke3bIWEgMn1\",\r\n\"balances\": {\r\n\"available\": null,\r\n\"current\": 56302.06,\r\n\"iso_currency_code\": \"USD\",\r\n\"limit\": null,\r\n\"unofficial_currency_code\": null\r\n},\r\n\"mask\": \"8888\",\r\n\"name\": \"Plaid Mortgage\",\r\n\"official_name\": null,\r\n\"subtype\": \"mortgage\",\r\n\"type\": \"loan\"\r\n}\r\n],\r\n\"item\": {\r\n\"available_products\": [\r\n\"assets\",\r\n\"auth\",\r\n\"balance\",\r\n\"credit_details\",\r\n\"identity\",\r\n\"income\",\r\n\"liabilities\"\r\n],\r\n\"billed_products\": [\r\n\"transactions\"\r\n],\r\n\"consent_expiration_time\": null,\r\n\"error\": null,\r\n\"institution_id\": \"ins_9\",\r\n\"item_id\": \"74B7Q4x6kqFAel77JmB8HXqA8w4M9vugLgjQG\",\r\n\"webhook\": \"\"\r\n},\r\n\"request_id\": \"BIfNW9aA8D2pWti\"\r\n}\r\n127.0.0.1 - - [24/Jul/2020 22:11:25] \"GET /balance HTTP/1.1\" 200 -\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/236", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/236/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/236/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/236/events", "html_url": "https://github.com/plaid/plaid-python/issues/236", "id": 664214164, "node_id": "MDU6SXNzdWU2NjQyMTQxNjQ=", "number": 236, "title": "Release notes?", "user": {"login": "dgildeh", "id": 1935421, "node_id": "MDQ6VXNlcjE5MzU0MjE=", "avatar_url": "https://avatars0.githubusercontent.com/u/1935421?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dgildeh", "html_url": "https://github.com/dgildeh", "followers_url": "https://api.github.com/users/dgildeh/followers", "following_url": "https://api.github.com/users/dgildeh/following{/other_user}", "gists_url": "https://api.github.com/users/dgildeh/gists{/gist_id}", "starred_url": "https://api.github.com/users/dgildeh/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dgildeh/subscriptions", "organizations_url": "https://api.github.com/users/dgildeh/orgs", "repos_url": "https://api.github.com/users/dgildeh/repos", "events_url": "https://api.github.com/users/dgildeh/events{/privacy}", "received_events_url": "https://api.github.com/users/dgildeh/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-07-23T05:34:29Z", "updated_at": "2020-07-23T05:36:19Z", "closed_at": "2020-07-23T05:36:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "I just updated my project and noticed you've bumped up 2 Major version since I last installed the package, you're now on 5. However I can't find any docs or releases in this repo to describe what's changed since I originally installed the package. Bumping up the release number by a Major version should be a big deal - so what has changed from 3->4->5 and can you add a change log or release notes going forwards so we can see what you've changed or added between releases?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/231", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/231/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/231/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/231/events", "html_url": "https://github.com/plaid/plaid-python/issues/231", "id": 651899045, "node_id": "MDU6SXNzdWU2NTE4OTkwNDU=", "number": 231, "title": "Installing the latest version and attempting to use it results in ModuleNotFoundError: No module named 'yml_check'", "user": {"login": "Mattwmaster58", "id": 26337069, "node_id": "MDQ6VXNlcjI2MzM3MDY5", "avatar_url": "https://avatars3.githubusercontent.com/u/26337069?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Mattwmaster58", "html_url": "https://github.com/Mattwmaster58", "followers_url": "https://api.github.com/users/Mattwmaster58/followers", "following_url": "https://api.github.com/users/Mattwmaster58/following{/other_user}", "gists_url": "https://api.github.com/users/Mattwmaster58/gists{/gist_id}", "starred_url": "https://api.github.com/users/Mattwmaster58/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Mattwmaster58/subscriptions", "organizations_url": "https://api.github.com/users/Mattwmaster58/orgs", "repos_url": "https://api.github.com/users/Mattwmaster58/repos", "events_url": "https://api.github.com/users/Mattwmaster58/events{/privacy}", "received_events_url": "https://api.github.com/users/Mattwmaster58/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-07-07T00:28:40Z", "updated_at": "2020-07-07T00:30:38Z", "closed_at": "2020-07-07T00:30:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "Plaid version: 0.1.7", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/225", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/225/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/225/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/225/events", "html_url": "https://github.com/plaid/plaid-python/issues/225", "id": 636363372, "node_id": "MDU6SXNzdWU2MzYzNjMzNzI=", "number": 225, "title": "Creating a public token with force_error override fails", "user": {"login": "Karuhanga", "id": 12200860, "node_id": "MDQ6VXNlcjEyMjAwODYw", "avatar_url": "https://avatars1.githubusercontent.com/u/12200860?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Karuhanga", "html_url": "https://github.com/Karuhanga", "followers_url": "https://api.github.com/users/Karuhanga/followers", "following_url": "https://api.github.com/users/Karuhanga/following{/other_user}", "gists_url": "https://api.github.com/users/Karuhanga/gists{/gist_id}", "starred_url": "https://api.github.com/users/Karuhanga/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Karuhanga/subscriptions", "organizations_url": "https://api.github.com/users/Karuhanga/orgs", "repos_url": "https://api.github.com/users/Karuhanga/repos", "events_url": "https://api.github.com/users/Karuhanga/events{/privacy}", "received_events_url": "https://api.github.com/users/Karuhanga/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-06-10T15:53:09Z", "updated_at": "2020-06-18T15:49:07Z", "closed_at": "2020-06-10T17:42:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "[https://plaid.com/docs/#custom-sandbox](https://plaid.com/docs/#custom-sandbox)\r\n\r\nTried this;\r\n```\r\nclient.Sandbox.public_token.create(\"ins_3\", [\"transactions\"], dict(override_username='user_custom', override_password= dict(force_error=\"ITEM_LOGIN_REQUIRED\")))\r\n```\r\n\r\nIt fails with;\r\n```\r\nplaid.errors.InvalidRequestError: the following fields are not recognized by this endpoint: options.force_error\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/222", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/222/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/222/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/222/events", "html_url": "https://github.com/plaid/plaid-python/issues/222", "id": 622237403, "node_id": "MDU6SXNzdWU2MjIyMzc0MDM=", "number": 222, "title": "No error class defined for AUTH_ERROR type", "user": {"login": "eric-cc-su", "id": 9936937, "node_id": "MDQ6VXNlcjk5MzY5Mzc=", "avatar_url": "https://avatars3.githubusercontent.com/u/9936937?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eric-cc-su", "html_url": "https://github.com/eric-cc-su", "followers_url": "https://api.github.com/users/eric-cc-su/followers", "following_url": "https://api.github.com/users/eric-cc-su/following{/other_user}", "gists_url": "https://api.github.com/users/eric-cc-su/gists{/gist_id}", "starred_url": "https://api.github.com/users/eric-cc-su/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eric-cc-su/subscriptions", "organizations_url": "https://api.github.com/users/eric-cc-su/orgs", "repos_url": "https://api.github.com/users/eric-cc-su/repos", "events_url": "https://api.github.com/users/eric-cc-su/events{/privacy}", "received_events_url": "https://api.github.com/users/eric-cc-su/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-05-21T04:26:51Z", "updated_at": "2020-06-25T00:12:10Z", "closed_at": "2020-06-25T00:12:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "[Plaid docs](https://plaid.com/docs/#auth-errors) describe an `AUTH_ERROR` error_type covering error codes:\r\n- `PRODUCT_NOT_READY`\r\n- `VERIFICATION_EXPIRED`\r\n\r\nFollowing the existing pattern of using PlaidError child classes to map errors with known `error_type` values, it would make sense that an `AuthError` child class should exist as well.\r\n\r\nIf there is a reason why such a class should not exist I would be interested to know why.\r\n\r\nIt may be useful to note that there seems to be a discrepancy where the docs do not list `AUTH_ERROR` in the [Error Overview section](https://plaid.com/docs/#errors-overview) under the `error_type` field. Whether that is related to this issue is unclear.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/216", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/216/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/216/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/216/events", "html_url": "https://github.com/plaid/plaid-python/issues/216", "id": 602629361, "node_id": "MDU6SXNzdWU2MDI2MjkzNjE=", "number": 216, "title": "http_request in plaid/requester.py fails with Attribute Error", "user": {"login": "WilliamParks", "id": 5242291, "node_id": "MDQ6VXNlcjUyNDIyOTE=", "avatar_url": "https://avatars0.githubusercontent.com/u/5242291?v=4", "gravatar_id": "", "url": "https://api.github.com/users/WilliamParks", "html_url": "https://github.com/WilliamParks", "followers_url": "https://api.github.com/users/WilliamParks/followers", "following_url": "https://api.github.com/users/WilliamParks/following{/other_user}", "gists_url": "https://api.github.com/users/WilliamParks/gists{/gist_id}", "starred_url": "https://api.github.com/users/WilliamParks/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/WilliamParks/subscriptions", "organizations_url": "https://api.github.com/users/WilliamParks/orgs", "repos_url": "https://api.github.com/users/WilliamParks/repos", "events_url": "https://api.github.com/users/WilliamParks/events{/privacy}", "received_events_url": "https://api.github.com/users/WilliamParks/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "skylarmb", "id": 7543705, "node_id": "MDQ6VXNlcjc1NDM3MDU=", "avatar_url": "https://avatars1.githubusercontent.com/u/7543705?v=4", "gravatar_id": "", "url": "https://api.github.com/users/skylarmb", "html_url": "https://github.com/skylarmb", "followers_url": "https://api.github.com/users/skylarmb/followers", "following_url": "https://api.github.com/users/skylarmb/following{/other_user}", "gists_url": "https://api.github.com/users/skylarmb/gists{/gist_id}", "starred_url": "https://api.github.com/users/skylarmb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/skylarmb/subscriptions", "organizations_url": "https://api.github.com/users/skylarmb/orgs", "repos_url": "https://api.github.com/users/skylarmb/repos", "events_url": "https://api.github.com/users/skylarmb/events{/privacy}", "received_events_url": "https://api.github.com/users/skylarmb/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "skylarmb", "id": 7543705, "node_id": "MDQ6VXNlcjc1NDM3MDU=", "avatar_url": "https://avatars1.githubusercontent.com/u/7543705?v=4", "gravatar_id": "", "url": "https://api.github.com/users/skylarmb", "html_url": "https://github.com/skylarmb", "followers_url": "https://api.github.com/users/skylarmb/followers", "following_url": "https://api.github.com/users/skylarmb/following{/other_user}", "gists_url": "https://api.github.com/users/skylarmb/gists{/gist_id}", "starred_url": "https://api.github.com/users/skylarmb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/skylarmb/subscriptions", "organizations_url": "https://api.github.com/users/skylarmb/orgs", "repos_url": "https://api.github.com/users/skylarmb/repos", "events_url": "https://api.github.com/users/skylarmb/events{/privacy}", "received_events_url": "https://api.github.com/users/skylarmb/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2020-04-19T05:46:02Z", "updated_at": "2020-06-26T01:17:20Z", "closed_at": "2020-06-26T01:16:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "The method http_request in plaid.requester is a wrapper around _requests_http_request, in the same file. \r\n\r\nhttp_request sends a \"method\" value of none to _requests_http_request, which then calls lower() from it.\r\n\r\n```\r\ndef _requests_http_request(\r\n        url,\r\n        method,\r\n        data,\r\n        headers,\r\n        timeout=DEFAULT_TIMEOUT):\r\n    normalized_method = method.lower()\r\n     # Rest of function removed here for brevity\r\n\r\ndef http_request(\r\n        url,\r\n        method=None,\r\n        data=None,\r\n        headers=None,\r\n        timeout=DEFAULT_TIMEOUT,\r\n        is_json=True):\r\n    response = _requests_http_request(\r\n        url,\r\n        method,\r\n        data or {},\r\n        headers or {},\r\n        timeout)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/202", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/202/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/202/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/202/events", "html_url": "https://github.com/plaid/plaid-python/issues/202", "id": 556598066, "node_id": "MDU6SXNzdWU1NTY1OTgwNjY=", "number": 202, "title": "API version pinning documented incorrectly", "user": {"login": "hkhanna", "id": 222784, "node_id": "MDQ6VXNlcjIyMjc4NA==", "avatar_url": "https://avatars2.githubusercontent.com/u/222784?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hkhanna", "html_url": "https://github.com/hkhanna", "followers_url": "https://api.github.com/users/hkhanna/followers", "following_url": "https://api.github.com/users/hkhanna/following{/other_user}", "gists_url": "https://api.github.com/users/hkhanna/gists{/gist_id}", "starred_url": "https://api.github.com/users/hkhanna/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hkhanna/subscriptions", "organizations_url": "https://api.github.com/users/hkhanna/orgs", "repos_url": "https://api.github.com/users/hkhanna/repos", "events_url": "https://api.github.com/users/hkhanna/events{/privacy}", "received_events_url": "https://api.github.com/users/hkhanna/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-01-29T02:18:57Z", "updated_at": "2020-01-31T22:35:29Z", "closed_at": "2020-01-31T22:35:29Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "The versioning section in the README uses the wrong kwarg to set the Client to a specific version. \r\n\r\nThe README says the kwarg is `version`:\r\n```\r\nclient = Client(\r\n  ...\r\n  version='2019-05-29'  # Specify API version\r\n)\r\n```\r\nA review of the source indicates that it should actually be `api_version`:\r\n```\r\nclient = Client(\r\n  ...\r\n  api_version='2019-05-29'  # Specify API version\r\n)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/201", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/201/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/201/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/201/events", "html_url": "https://github.com/plaid/plaid-python/issues/201", "id": 554921819, "node_id": "MDU6SXNzdWU1NTQ5MjE4MTk=", "number": 201, "title": "Using a mutable value as default", "user": {"login": "frnhr", "id": 1173748, "node_id": "MDQ6VXNlcjExNzM3NDg=", "avatar_url": "https://avatars2.githubusercontent.com/u/1173748?v=4", "gravatar_id": "", "url": "https://api.github.com/users/frnhr", "html_url": "https://github.com/frnhr", "followers_url": "https://api.github.com/users/frnhr/followers", "following_url": "https://api.github.com/users/frnhr/following{/other_user}", "gists_url": "https://api.github.com/users/frnhr/gists{/gist_id}", "starred_url": "https://api.github.com/users/frnhr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/frnhr/subscriptions", "organizations_url": "https://api.github.com/users/frnhr/orgs", "repos_url": "https://api.github.com/users/frnhr/repos", "events_url": "https://api.github.com/users/frnhr/events{/privacy}", "received_events_url": "https://api.github.com/users/frnhr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-01-24T19:49:43Z", "updated_at": "2020-05-04T23:08:19Z", "closed_at": "2020-05-04T23:08:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "Using mutable default values is almost not what was intended.\r\n\r\nRef:\r\n * \"Important warning\" under [4.7.1. Default Argument Values](https://docs.python.org/3/tutorial/controlflow.html#default-argument-values) in the official Python docs tutorial\r\n * [Mutable Default Arguments ](https://docs.python-guide.org/writing/gotchas/)\r\n * Warning `B006` in [List of warnings](https://github.com/PyCQA/flake8-bugbear/blob/master/README.rst) in flake8-bugbear\r\n\r\n\r\nPlease update:\r\n\r\n``` python\r\nclass Institutions(API):\r\n    ...\r\n    def search(self, query, _options={}, products=None):\r\n        ...\r\n```\r\n\r\nto something like this:\r\n\r\n``` python\r\nclass Institutions(API):\r\n    ...\r\n    def search(self, query, _options=None, products=None): \r\n        _options = options or None\r\n        ...\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/194", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/194/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/194/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/194/events", "html_url": "https://github.com/plaid/plaid-python/issues/194", "id": 545408521, "node_id": "MDU6SXNzdWU1NDU0MDg1MjE=", "number": 194, "title": "Plaid is not defined error message. ", "user": {"login": "Leke-Ariyo", "id": 37749047, "node_id": "MDQ6VXNlcjM3NzQ5MDQ3", "avatar_url": "https://avatars3.githubusercontent.com/u/37749047?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Leke-Ariyo", "html_url": "https://github.com/Leke-Ariyo", "followers_url": "https://api.github.com/users/Leke-Ariyo/followers", "following_url": "https://api.github.com/users/Leke-Ariyo/following{/other_user}", "gists_url": "https://api.github.com/users/Leke-Ariyo/gists{/gist_id}", "starred_url": "https://api.github.com/users/Leke-Ariyo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Leke-Ariyo/subscriptions", "organizations_url": "https://api.github.com/users/Leke-Ariyo/orgs", "repos_url": "https://api.github.com/users/Leke-Ariyo/repos", "events_url": "https://api.github.com/users/Leke-Ariyo/events{/privacy}", "received_events_url": "https://api.github.com/users/Leke-Ariyo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-01-05T12:04:54Z", "updated_at": "2020-06-02T21:29:51Z", "closed_at": "2020-06-02T21:29:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "Python 3.7.6 (default, Dec 30 2019, 19:38:26) \r\n[Clang 11.0.0 (clang-1100.0.33.16)] on darwin\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> plaid\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nNameError: name 'plaid' is not defined\r\n\r\nI have plaid-python>=3.0.0 in my requirements.txt file and was able to successfully install it. Also I imported it in my server.py line 4. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/193", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/193/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/193/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/193/events", "html_url": "https://github.com/plaid/plaid-python/issues/193", "id": 545126848, "node_id": "MDU6SXNzdWU1NDUxMjY4NDg=", "number": 193, "title": "Retrieve Transactions Example ", "user": {"login": "pythonympho", "id": 38021888, "node_id": "MDQ6VXNlcjM4MDIxODg4", "avatar_url": "https://avatars2.githubusercontent.com/u/38021888?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pythonympho", "html_url": "https://github.com/pythonympho", "followers_url": "https://api.github.com/users/pythonympho/followers", "following_url": "https://api.github.com/users/pythonympho/following{/other_user}", "gists_url": "https://api.github.com/users/pythonympho/gists{/gist_id}", "starred_url": "https://api.github.com/users/pythonympho/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pythonympho/subscriptions", "organizations_url": "https://api.github.com/users/pythonympho/orgs", "repos_url": "https://api.github.com/users/pythonympho/repos", "events_url": "https://api.github.com/users/pythonympho/events{/privacy}", "received_events_url": "https://api.github.com/users/pythonympho/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-01-03T19:25:10Z", "updated_at": "2020-06-02T21:30:37Z", "closed_at": "2020-06-02T21:30:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "The retrieve transactions example is not listing the transactions.  Does anyone have a sure way to print the transactions into the terminal window or export to .csv?  ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/192", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/192/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/192/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/192/events", "html_url": "https://github.com/plaid/plaid-python/issues/192", "id": 541812875, "node_id": "MDU6SXNzdWU1NDE4MTI4NzU=", "number": 192, "title": "TypeError: can only concatenate str (not \"NoneType\") to str", "user": {"login": "spencerlawrence36", "id": 15065899, "node_id": "MDQ6VXNlcjE1MDY1ODk5", "avatar_url": "https://avatars1.githubusercontent.com/u/15065899?v=4", "gravatar_id": "", "url": "https://api.github.com/users/spencerlawrence36", "html_url": "https://github.com/spencerlawrence36", "followers_url": "https://api.github.com/users/spencerlawrence36/followers", "following_url": "https://api.github.com/users/spencerlawrence36/following{/other_user}", "gists_url": "https://api.github.com/users/spencerlawrence36/gists{/gist_id}", "starred_url": "https://api.github.com/users/spencerlawrence36/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/spencerlawrence36/subscriptions", "organizations_url": "https://api.github.com/users/spencerlawrence36/orgs", "repos_url": "https://api.github.com/users/spencerlawrence36/repos", "events_url": "https://api.github.com/users/spencerlawrence36/events{/privacy}", "received_events_url": "https://api.github.com/users/spencerlawrence36/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-12-23T16:03:59Z", "updated_at": "2020-03-28T15:16:38Z", "closed_at": "2020-03-28T15:16:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello, I'm just getting started with the Plaid API.  I've set my environment variables and confirmed they work fine.\r\n\r\nCode: \r\n```\r\nimport os\r\nfrom plaid import Client as PlaidClient\r\n\r\nplaid_client = PlaidClient(client_id=os.getenv('PLAID_CLIENT_ID'), secret=os.getenv('PLAID_SECRET'),\r\n                           public_key=os.getenv('PLAID_PUBLIC_ID'), environment=os.getenv('PLAID_ENV'))\r\n\r\ndef get_some_transactions(access_token, start_date, end_date):\r\n    return plaid_client.Transactions.get(access_token, start_date, end_date)\r\n\r\nsome_transactions = get_some_transactions(os.getenv('CHASE_ACCESS_TOKEN'), '2019-12-01', '2019-12-23')\r\nprint(some_transactions['total_transactions'])\r\n```\r\n\r\nOutput:\r\n```Traceback (most recent call last):\r\n  File \"get_transactions.py\", line 12, in <module>\r\n    some_transactions = get_some_transactions(os.getenv('CHASE_ACCESS_TOKEN'), '2019-12-01', '2019-12-23')\r\n  File \"get_transactions.py\", line 10, in get_some_transactions\r\n    return plaid_client.Transactions.get(access_token, start_date, end_date)\r\n  File \"/usr/local/lib/python3.7/site-packages/plaid/api/transactions.py\", line 49, in get\r\n    'options': options,\r\n  File \"/usr/local/lib/python3.7/site-packages/plaid/client.py\", line 98, in post\r\n    return self._post(path, post_data, is_json)\r\n  File \"/usr/local/lib/python3.7/site-packages/plaid/client.py\", line 119, in _post\r\n    urljoin('https://' + self.environment + '.plaid.com', path),\r\nTypeError: can only concatenate str (not \"NoneType\") to str\r\n```\r\n\r\nNote that I am using Python 3.7.5.  Is this an issue with Python versioning?  Not sure how to debug from this point. \r\n\r\nThanks\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/190", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/190/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/190/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/190/events", "html_url": "https://github.com/plaid/plaid-python/issues/190", "id": 536173896, "node_id": "MDU6SXNzdWU1MzYxNzM4OTY=", "number": 190, "title": "error while getting processor token of Modern Treasury ", "user": {"login": "Saurabh-Sn", "id": 14322809, "node_id": "MDQ6VXNlcjE0MzIyODA5", "avatar_url": "https://avatars3.githubusercontent.com/u/14322809?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Saurabh-Sn", "html_url": "https://github.com/Saurabh-Sn", "followers_url": "https://api.github.com/users/Saurabh-Sn/followers", "following_url": "https://api.github.com/users/Saurabh-Sn/following{/other_user}", "gists_url": "https://api.github.com/users/Saurabh-Sn/gists{/gist_id}", "starred_url": "https://api.github.com/users/Saurabh-Sn/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Saurabh-Sn/subscriptions", "organizations_url": "https://api.github.com/users/Saurabh-Sn/orgs", "repos_url": "https://api.github.com/users/Saurabh-Sn/repos", "events_url": "https://api.github.com/users/Saurabh-Sn/events{/privacy}", "received_events_url": "https://api.github.com/users/Saurabh-Sn/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-12-11T06:41:05Z", "updated_at": "2020-04-04T16:54:17Z", "closed_at": "2020-04-04T16:53:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "'Processor' object has no attribute 'modernTreasuryProcessorTokenCreate'Type a message\r\n![image_2019_12_11T05_12_47_227Z](https://user-images.githubusercontent.com/14322809/70597798-47a05b00-1c0f-11ea-882f-4ba02ca1cfb7.jpg)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/186", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/186/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/186/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/186/events", "html_url": "https://github.com/plaid/plaid-python/issues/186", "id": 504329934, "node_id": "MDU6SXNzdWU1MDQzMjk5MzQ=", "number": 186, "title": "Incorrect Python Documentation", "user": {"login": "JuanPabloRN30", "id": 9343704, "node_id": "MDQ6VXNlcjkzNDM3MDQ=", "avatar_url": "https://avatars0.githubusercontent.com/u/9343704?v=4", "gravatar_id": "", "url": "https://api.github.com/users/JuanPabloRN30", "html_url": "https://github.com/JuanPabloRN30", "followers_url": "https://api.github.com/users/JuanPabloRN30/followers", "following_url": "https://api.github.com/users/JuanPabloRN30/following{/other_user}", "gists_url": "https://api.github.com/users/JuanPabloRN30/gists{/gist_id}", "starred_url": "https://api.github.com/users/JuanPabloRN30/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/JuanPabloRN30/subscriptions", "organizations_url": "https://api.github.com/users/JuanPabloRN30/orgs", "repos_url": "https://api.github.com/users/JuanPabloRN30/repos", "events_url": "https://api.github.com/users/JuanPabloRN30/events{/privacy}", "received_events_url": "https://api.github.com/users/JuanPabloRN30/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-10-08T23:30:00Z", "updated_at": "2020-03-26T23:02:43Z", "closed_at": "2020-03-26T23:02:43Z", "author_association": "NONE", "active_lock_reason": null, "body": "On the integration with Dwolla the \"Step 4: Write server-side handler\"\r\n\r\nthe snippet example:\r\n`dwolla_response = \r\nclient.Processor.dwollaProcessorTokenCreate(access_token, \r\naccount_id)`\r\n\r\nshould be:\r\n`dwolla_response = \r\nclient.Processor.dwollaBankAccountTokenCreate(access_token, account_id)`\r\n\r\nThis can generate confusion. Please update the docs! :)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/180", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/180/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/180/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/180/events", "html_url": "https://github.com/plaid/plaid-python/issues/180", "id": 480078218, "node_id": "MDU6SXNzdWU0ODAwNzgyMTg=", "number": 180, "title": "Liabilities not present in plaid-python==3.3.3", "user": {"login": "hackath0r", "id": 2417654, "node_id": "MDQ6VXNlcjI0MTc2NTQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/2417654?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hackath0r", "html_url": "https://github.com/hackath0r", "followers_url": "https://api.github.com/users/hackath0r/followers", "following_url": "https://api.github.com/users/hackath0r/following{/other_user}", "gists_url": "https://api.github.com/users/hackath0r/gists{/gist_id}", "starred_url": "https://api.github.com/users/hackath0r/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hackath0r/subscriptions", "organizations_url": "https://api.github.com/users/hackath0r/orgs", "repos_url": "https://api.github.com/users/hackath0r/repos", "events_url": "https://api.github.com/users/hackath0r/events{/privacy}", "received_events_url": "https://api.github.com/users/hackath0r/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-08-13T10:24:15Z", "updated_at": "2019-08-20T15:29:38Z", "closed_at": "2019-08-20T15:29:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "I can see that Liabilities is exposed to the client in the master branch. However, after installing the latest version (3.3) of plaid-python from pip, Liabilities is not present.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/176", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/176/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/176/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/176/events", "html_url": "https://github.com/plaid/plaid-python/issues/176", "id": 470703337, "node_id": "MDU6SXNzdWU0NzA3MDMzMzc=", "number": 176, "title": "Python docs not explaining API version parameter", "user": {"login": "Skorkmaz88", "id": 1834237, "node_id": "MDQ6VXNlcjE4MzQyMzc=", "avatar_url": "https://avatars3.githubusercontent.com/u/1834237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Skorkmaz88", "html_url": "https://github.com/Skorkmaz88", "followers_url": "https://api.github.com/users/Skorkmaz88/followers", "following_url": "https://api.github.com/users/Skorkmaz88/following{/other_user}", "gists_url": "https://api.github.com/users/Skorkmaz88/gists{/gist_id}", "starred_url": "https://api.github.com/users/Skorkmaz88/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Skorkmaz88/subscriptions", "organizations_url": "https://api.github.com/users/Skorkmaz88/orgs", "repos_url": "https://api.github.com/users/Skorkmaz88/repos", "events_url": "https://api.github.com/users/Skorkmaz88/events{/privacy}", "received_events_url": "https://api.github.com/users/Skorkmaz88/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-07-20T18:44:55Z", "updated_at": "2019-07-22T17:15:30Z", "closed_at": "2019-07-22T17:15:30Z", "author_association": "NONE", "active_lock_reason": null, "body": "Neither python docs nor the readme file explains or demonstrates how API version parameter works in the client class' constructor. Assumption is , give in the source code it is mentioned as string, it is the date with dashes as in the website as string , is that correct ?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/174", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/174/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/174/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/174/events", "html_url": "https://github.com/plaid/plaid-python/issues/174", "id": 468850313, "node_id": "MDU6SXNzdWU0Njg4NTAzMTM=", "number": 174, "title": "plaid.errors.APIError: an unexpected error occurred", "user": {"login": "dan-iel-lee", "id": 43528934, "node_id": "MDQ6VXNlcjQzNTI4OTM0", "avatar_url": "https://avatars0.githubusercontent.com/u/43528934?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dan-iel-lee", "html_url": "https://github.com/dan-iel-lee", "followers_url": "https://api.github.com/users/dan-iel-lee/followers", "following_url": "https://api.github.com/users/dan-iel-lee/following{/other_user}", "gists_url": "https://api.github.com/users/dan-iel-lee/gists{/gist_id}", "starred_url": "https://api.github.com/users/dan-iel-lee/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dan-iel-lee/subscriptions", "organizations_url": "https://api.github.com/users/dan-iel-lee/orgs", "repos_url": "https://api.github.com/users/dan-iel-lee/repos", "events_url": "https://api.github.com/users/dan-iel-lee/events{/privacy}", "received_events_url": "https://api.github.com/users/dan-iel-lee/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-07-16T20:33:19Z", "updated_at": "2019-07-23T00:16:41Z", "closed_at": "2019-07-23T00:16:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm getting the error `plaid.errors.APIError: an unexpected error occurred` when I use plaid-python to call the transactions endpoint. The thing is, I made no change to my code since my last time running it (when it worked fine), and I really can't figure out what's going on.\r\n\r\n**Here's where I call client.Transactions.get:**\r\n```\r\ndef getTransactions(items, start_date, end_date):\r\n    transactions = []\r\n    for item in items:\r\n        # for each item, get item transactions, and add to list\r\n        access_token = item.access_token\r\n        new_trans = client.Transactions.get(access_token,\r\n                                        dateFormat(start_date),\r\n                                        dateFormat(end_date))['transactions']\r\n        transactions.extend(new_trans)\r\n    return transactions\r\n```\r\nwhere client is assigned earlier as\r\n`client = Client(PLAID_CLIENT_ID, PLAID_SECRET, PLAID_PUBLIC_KEY, PLAID_ENV)`\r\n(I've checked and the constants are all correct)\r\n\r\n**And here's my stack trace:**\r\n```\r\nTraceback (most recent call last):\r\n...\r\n  File \"/Users/daniellee/Coding/bread2/bread/api/plaid_helpers.py\", line 68, in getSpending\r\n    transactions = getTransactions(items, start_date, end_date)\r\n  File \"/Users/daniellee/Coding/bread2/bread/api/plaid_helpers.py\", line 63, in getTransactions\r\n    dateFormat(end_date))['transactions']\r\n  File \"/Users/daniellee/Coding/bread2/venv/lib/python3.7/site-packages/plaid/api/transactions.py\", line 49, in get\r\n    'options': options,\r\n  File \"/Users/daniellee/Coding/bread2/venv/lib/python3.7/site-packages/plaid/client.py\", line 91, in post\r\n    return self._post(path, post_data, is_json)\r\n  File \"/Users/daniellee/Coding/bread2/venv/lib/python3.7/site-packages/plaid/client.py\", line 114, in _post\r\n    headers=headers,\r\n  File \"/Users/daniellee/Coding/bread2/venv/lib/python3.7/site-packages/plaid/requester.py\", line 68, in http_request\r\n    raise PlaidError.from_response(response_body)\r\nplaid.errors.APIError: an unexpected error occurred\r\n```\r\n\r\nI've tried debugging it, and found that all the plaid codes (client id, secret, public key, item access token) are correct in `client`. I'm using sandbox mode.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/158", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/158/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/158/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/158/events", "html_url": "https://github.com/plaid/plaid-python/issues/158", "id": 421542689, "node_id": "MDU6SXNzdWU0MjE1NDI2ODk=", "number": 158, "title": "Add Changelog to releases", "user": {"login": "tomhamiltonstubber", "id": 8955690, "node_id": "MDQ6VXNlcjg5NTU2OTA=", "avatar_url": "https://avatars1.githubusercontent.com/u/8955690?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tomhamiltonstubber", "html_url": "https://github.com/tomhamiltonstubber", "followers_url": "https://api.github.com/users/tomhamiltonstubber/followers", "following_url": "https://api.github.com/users/tomhamiltonstubber/following{/other_user}", "gists_url": "https://api.github.com/users/tomhamiltonstubber/gists{/gist_id}", "starred_url": "https://api.github.com/users/tomhamiltonstubber/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tomhamiltonstubber/subscriptions", "organizations_url": "https://api.github.com/users/tomhamiltonstubber/orgs", "repos_url": "https://api.github.com/users/tomhamiltonstubber/repos", "events_url": "https://api.github.com/users/tomhamiltonstubber/events{/privacy}", "received_events_url": "https://api.github.com/users/tomhamiltonstubber/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-03-15T14:21:39Z", "updated_at": "2019-07-03T18:25:25Z", "closed_at": "2019-07-03T18:25:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi guys,\r\n\r\nCan you update the releases with a change log please? Sounds like there might be breaking changes in a 3.0.0 release.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/143", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/143/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/143/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/143/events", "html_url": "https://github.com/plaid/plaid-python/issues/143", "id": 407892163, "node_id": "MDU6SXNzdWU0MDc4OTIxNjM=", "number": 143, "title": "AttributeError: module 'plaid' has no attribute 'Client'", "user": {"login": "DShep68", "id": 26091162, "node_id": "MDQ6VXNlcjI2MDkxMTYy", "avatar_url": "https://avatars0.githubusercontent.com/u/26091162?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DShep68", "html_url": "https://github.com/DShep68", "followers_url": "https://api.github.com/users/DShep68/followers", "following_url": "https://api.github.com/users/DShep68/following{/other_user}", "gists_url": "https://api.github.com/users/DShep68/gists{/gist_id}", "starred_url": "https://api.github.com/users/DShep68/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DShep68/subscriptions", "organizations_url": "https://api.github.com/users/DShep68/orgs", "repos_url": "https://api.github.com/users/DShep68/repos", "events_url": "https://api.github.com/users/DShep68/events{/privacy}", "received_events_url": "https://api.github.com/users/DShep68/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2019-02-07T20:52:34Z", "updated_at": "2020-05-12T18:47:55Z", "closed_at": "2020-05-12T18:47:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to run the server.py file on my mac but I continue to have this error that says no attribute client and I'm not sure where to go from here. Please let me know some ways to fix this issue", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/142", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/142/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/142/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/142/events", "html_url": "https://github.com/plaid/plaid-python/issues/142", "id": 405130090, "node_id": "MDU6SXNzdWU0MDUxMzAwOTA=", "number": 142, "title": "e: the provided API keys are not enabled for the Dwolla ACH integration.", "user": {"login": "ngcheesing", "id": 17897597, "node_id": "MDQ6VXNlcjE3ODk3NTk3", "avatar_url": "https://avatars1.githubusercontent.com/u/17897597?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ngcheesing", "html_url": "https://github.com/ngcheesing", "followers_url": "https://api.github.com/users/ngcheesing/followers", "following_url": "https://api.github.com/users/ngcheesing/following{/other_user}", "gists_url": "https://api.github.com/users/ngcheesing/gists{/gist_id}", "starred_url": "https://api.github.com/users/ngcheesing/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ngcheesing/subscriptions", "organizations_url": "https://api.github.com/users/ngcheesing/orgs", "repos_url": "https://api.github.com/users/ngcheesing/repos", "events_url": "https://api.github.com/users/ngcheesing/events{/privacy}", "received_events_url": "https://api.github.com/users/ngcheesing/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-01-31T08:23:27Z", "updated_at": "2019-01-31T20:13:24Z", "closed_at": "2019-01-31T20:13:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I tried to use plaid processor api to get dwolla response for processor token, I got an error that the provided API keys are not enabled for the Dwolla ACH integration. please see https://plaid.com/docs/link/dwolla/ for more information.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/141", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/141/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/141/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/141/events", "html_url": "https://github.com/plaid/plaid-python/issues/141", "id": 404642920, "node_id": "MDU6SXNzdWU0MDQ2NDI5MjA=", "number": 141, "title": "Change log is missing", "user": {"login": "Perlence", "id": 1044300, "node_id": "MDQ6VXNlcjEwNDQzMDA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1044300?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Perlence", "html_url": "https://github.com/Perlence", "followers_url": "https://api.github.com/users/Perlence/followers", "following_url": "https://api.github.com/users/Perlence/following{/other_user}", "gists_url": "https://api.github.com/users/Perlence/gists{/gist_id}", "starred_url": "https://api.github.com/users/Perlence/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Perlence/subscriptions", "organizations_url": "https://api.github.com/users/Perlence/orgs", "repos_url": "https://api.github.com/users/Perlence/repos", "events_url": "https://api.github.com/users/Perlence/events{/privacy}", "received_events_url": "https://api.github.com/users/Perlence/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-01-30T07:51:07Z", "updated_at": "2019-01-31T04:13:27Z", "closed_at": "2019-01-30T23:22:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "I couldn't find the detailed log of library changes, is there one? I find upgrading the library without referring to a change log unsettling, it's not clear what can go wrong.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/132", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/132/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/132/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/132/events", "html_url": "https://github.com/plaid/plaid-python/issues/132", "id": 347655396, "node_id": "MDU6SXNzdWUzNDc2NTUzOTY=", "number": 132, "title": "Hi, I want to see lists of all categories/category id's", "user": {"login": "TheoSeo93", "id": 29108558, "node_id": "MDQ6VXNlcjI5MTA4NTU4", "avatar_url": "https://avatars0.githubusercontent.com/u/29108558?v=4", "gravatar_id": "", "url": "https://api.github.com/users/TheoSeo93", "html_url": "https://github.com/TheoSeo93", "followers_url": "https://api.github.com/users/TheoSeo93/followers", "following_url": "https://api.github.com/users/TheoSeo93/following{/other_user}", "gists_url": "https://api.github.com/users/TheoSeo93/gists{/gist_id}", "starred_url": "https://api.github.com/users/TheoSeo93/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/TheoSeo93/subscriptions", "organizations_url": "https://api.github.com/users/TheoSeo93/orgs", "repos_url": "https://api.github.com/users/TheoSeo93/repos", "events_url": "https://api.github.com/users/TheoSeo93/events{/privacy}", "received_events_url": "https://api.github.com/users/TheoSeo93/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "ravron", "id": 5354796, "node_id": "MDQ6VXNlcjUzNTQ3OTY=", "avatar_url": "https://avatars1.githubusercontent.com/u/5354796?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ravron", "html_url": "https://github.com/ravron", "followers_url": "https://api.github.com/users/ravron/followers", "following_url": "https://api.github.com/users/ravron/following{/other_user}", "gists_url": "https://api.github.com/users/ravron/gists{/gist_id}", "starred_url": "https://api.github.com/users/ravron/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ravron/subscriptions", "organizations_url": "https://api.github.com/users/ravron/orgs", "repos_url": "https://api.github.com/users/ravron/repos", "events_url": "https://api.github.com/users/ravron/events{/privacy}", "received_events_url": "https://api.github.com/users/ravron/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "ravron", "id": 5354796, "node_id": "MDQ6VXNlcjUzNTQ3OTY=", "avatar_url": "https://avatars1.githubusercontent.com/u/5354796?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ravron", "html_url": "https://github.com/ravron", "followers_url": "https://api.github.com/users/ravron/followers", "following_url": "https://api.github.com/users/ravron/following{/other_user}", "gists_url": "https://api.github.com/users/ravron/gists{/gist_id}", "starred_url": "https://api.github.com/users/ravron/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ravron/subscriptions", "organizations_url": "https://api.github.com/users/ravron/orgs", "repos_url": "https://api.github.com/users/ravron/repos", "events_url": "https://api.github.com/users/ravron/events{/privacy}", "received_events_url": "https://api.github.com/users/ravron/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2018-08-04T23:26:30Z", "updated_at": "2019-03-14T09:55:59Z", "closed_at": "2019-03-14T09:55:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "I can't see the list of it anywhere from the website. Where can I see that?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/131", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/131/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/131/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/131/events", "html_url": "https://github.com/plaid/plaid-python/issues/131", "id": 343359908, "node_id": "MDU6SXNzdWUzNDMzNTk5MDg=", "number": 131, "title": "client ID is only authorized to use Plaid Link", "user": {"login": "holtc", "id": 3432492, "node_id": "MDQ6VXNlcjM0MzI0OTI=", "avatar_url": "https://avatars3.githubusercontent.com/u/3432492?v=4", "gravatar_id": "", "url": "https://api.github.com/users/holtc", "html_url": "https://github.com/holtc", "followers_url": "https://api.github.com/users/holtc/followers", "following_url": "https://api.github.com/users/holtc/following{/other_user}", "gists_url": "https://api.github.com/users/holtc/gists{/gist_id}", "starred_url": "https://api.github.com/users/holtc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/holtc/subscriptions", "organizations_url": "https://api.github.com/users/holtc/orgs", "repos_url": "https://api.github.com/users/holtc/repos", "events_url": "https://api.github.com/users/holtc/events{/privacy}", "received_events_url": "https://api.github.com/users/holtc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-07-21T22:20:12Z", "updated_at": "2018-07-23T23:55:08Z", "closed_at": "2018-07-23T21:06:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to create an Item through the python library, not using link, which seems to be supported according to the present code.  However, the response contains the following error:\r\n\r\nplaid.errors.InvalidInputError: your client ID is only authorized to use Plaid Link. head to the docs (https://plaid.com/docs) to get started.\r\n\r\nIs there any way to create an Item without using Link?  Might be related to [this](https://github.com/plaid/plaid-ruby/issues/168)?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/125", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/125/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/125/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/125/events", "html_url": "https://github.com/plaid/plaid-python/issues/125", "id": 326002255, "node_id": "MDU6SXNzdWUzMjYwMDIyNTU=", "number": 125, "title": "PlaidError.message in python 3", "user": {"login": "pyinto", "id": 19248049, "node_id": "MDQ6VXNlcjE5MjQ4MDQ5", "avatar_url": "https://avatars1.githubusercontent.com/u/19248049?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pyinto", "html_url": "https://github.com/pyinto", "followers_url": "https://api.github.com/users/pyinto/followers", "following_url": "https://api.github.com/users/pyinto/following{/other_user}", "gists_url": "https://api.github.com/users/pyinto/gists{/gist_id}", "starred_url": "https://api.github.com/users/pyinto/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pyinto/subscriptions", "organizations_url": "https://api.github.com/users/pyinto/orgs", "repos_url": "https://api.github.com/users/pyinto/repos", "events_url": "https://api.github.com/users/pyinto/events{/privacy}", "received_events_url": "https://api.github.com/users/pyinto/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-05-24T07:47:46Z", "updated_at": "2019-06-17T07:15:20Z", "closed_at": "2019-06-17T07:15:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/120", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/120/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/120/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/120/events", "html_url": "https://github.com/plaid/plaid-python/issues/120", "id": 316391914, "node_id": "MDU6SXNzdWUzMTYzOTE5MTQ=", "number": 120, "title": "AttributeError: module 'plaid' has no attribute 'Client'", "user": {"login": "spider-hand", "id": 35469843, "node_id": "MDQ6VXNlcjM1NDY5ODQz", "avatar_url": "https://avatars0.githubusercontent.com/u/35469843?v=4", "gravatar_id": "", "url": "https://api.github.com/users/spider-hand", "html_url": "https://github.com/spider-hand", "followers_url": "https://api.github.com/users/spider-hand/followers", "following_url": "https://api.github.com/users/spider-hand/following{/other_user}", "gists_url": "https://api.github.com/users/spider-hand/gists{/gist_id}", "starred_url": "https://api.github.com/users/spider-hand/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/spider-hand/subscriptions", "organizations_url": "https://api.github.com/users/spider-hand/orgs", "repos_url": "https://api.github.com/users/spider-hand/repos", "events_url": "https://api.github.com/users/spider-hand/events{/privacy}", "received_events_url": "https://api.github.com/users/spider-hand/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 11, "created_at": "2018-04-20T19:53:06Z", "updated_at": "2020-03-16T03:48:35Z", "closed_at": "2018-04-20T22:36:04Z", "author_association": "NONE", "active_lock_reason": null, "body": " Hi, I'm trying to embed your quick start code into my program. This error\r\n\r\n```\r\n  client = plaid.Client(client_id = PLAID_CLIENT_ID, secret=PLAID_SECRET,\r\nAttributeError: module 'plaid' has no attribute 'Client'\r\n```\r\n\r\n happens when I combined your code into my program even though I run the quick start code successfully. I actually just copied the whole program. How can I fix this error? ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/116", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/116/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/116/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/116/events", "html_url": "https://github.com/plaid/plaid-python/issues/116", "id": 309437361, "node_id": "MDU6SXNzdWUzMDk0MzczNjE=", "number": 116, "title": "suppress_warnings flag clarification", "user": {"login": "jannainm", "id": 13946885, "node_id": "MDQ6VXNlcjEzOTQ2ODg1", "avatar_url": "https://avatars1.githubusercontent.com/u/13946885?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jannainm", "html_url": "https://github.com/jannainm", "followers_url": "https://api.github.com/users/jannainm/followers", "following_url": "https://api.github.com/users/jannainm/following{/other_user}", "gists_url": "https://api.github.com/users/jannainm/gists{/gist_id}", "starred_url": "https://api.github.com/users/jannainm/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jannainm/subscriptions", "organizations_url": "https://api.github.com/users/jannainm/orgs", "repos_url": "https://api.github.com/users/jannainm/repos", "events_url": "https://api.github.com/users/jannainm/events{/privacy}", "received_events_url": "https://api.github.com/users/jannainm/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-03-28T16:19:40Z", "updated_at": "2018-04-03T21:24:17Z", "closed_at": "2018-04-03T21:24:17Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "In client.py the suppress_warnings flag returns a warning `...Swap out url for https://api.plaid.com...` if not set to True upon client initialization. After reviewing the code it seems this flag must be set to True in order to use the development environment. However, I don't see it mentioned anywhere else in the code. \r\n\r\nPerhaps this flag could be named something more indicative of its purpose. I am not clear if I am actually suppressing warnings the api would have returned otherwise. Also, the url contained in the warning message is a bit unclear. I believe the urls follow an https://environment.plaid.com scheme, so I am not sure why it mentions swapping out the url for https://api.plaid.com.\r\n\r\nI may be missing something so if anyone can provide clarification on this or point me to any documentation where it is mentioned I will close the issue. Thanks for all your work on the client.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/111", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/111/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/111/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/111/events", "html_url": "https://github.com/plaid/plaid-python/issues/111", "id": 280515902, "node_id": "MDU6SXNzdWUyODA1MTU5MDI=", "number": 111, "title": "Expecting value: line 1 column 1 (char 0)", "user": {"login": "kchodorow", "id": 17042, "node_id": "MDQ6VXNlcjE3MDQy", "avatar_url": "https://avatars2.githubusercontent.com/u/17042?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kchodorow", "html_url": "https://github.com/kchodorow", "followers_url": "https://api.github.com/users/kchodorow/followers", "following_url": "https://api.github.com/users/kchodorow/following{/other_user}", "gists_url": "https://api.github.com/users/kchodorow/gists{/gist_id}", "starred_url": "https://api.github.com/users/kchodorow/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kchodorow/subscriptions", "organizations_url": "https://api.github.com/users/kchodorow/orgs", "repos_url": "https://api.github.com/users/kchodorow/repos", "events_url": "https://api.github.com/users/kchodorow/events{/privacy}", "received_events_url": "https://api.github.com/users/kchodorow/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-12-08T15:00:09Z", "updated_at": "2018-01-23T19:00:55Z", "closed_at": "2018-01-23T18:34:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "My code is calling `plaid_client.Transactions.get(token, self._start_date, self._end_date, offset=len(transactions))` which mostly has been working great but occasionally throws the following error:\r\n\r\n```\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.948010 2017] [:error] [pid 12503] An error occurred while resolving field Mutation.sync\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950807 2017] [:error] [pid 12503] Traceback (most recent call last):\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950824 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executor.py\", line 311, in resolve_or_error\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950835 2017] [:error] [pid 12503] return executor.execute(resolve_fn, source, info, **args)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950845 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executors/sync.py\", line 7, in execute\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950855 2017] [:error] [pid 12503] return fn(*args, **kwargs)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950865 2017] [:error] [pid 12503] File \"/opt/python/current/app/moirai/gql/sync.py\", line 23, in mutate\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950874 2017] [:error] [pid 12503] state = record.store_transactions(access_token)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950885 2017] [:error] [pid 12503] File \"/opt/python/current/app/moirai/db/user_record.py\", line 43, in store_transactions\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950894 2017] [:error] [pid 12503] token=access_token, since=last_updated)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950904 2017] [:error] [pid 12503] File \"/opt/python/current/app/moirai/db/plaid_connection.py\", line 48, in get_transactions_and_accounts\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950914 2017] [:error] [pid 12503] return self._get_transactions(token=token, since=since)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950934 2017] [:error] [pid 12503] response = self._client.Transactions.get(token, START_DATE, self._end_date, offset=len(transactions))\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950944 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/api/transactions.py\", line 49, in get\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950954 2017] [:error] [pid 12503] \"options\": options,\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950963 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/client.py\", line 83, in post\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950973 2017] [:error] [pid 12503] return self._post(path, post_data)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950983 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/client.py\", line 101, in _post\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.950993 2017] [:error] [pid 12503] timeout=self.timeout\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951002 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/plaid/requester.py\", line 33, in http_request\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951012 2017] [:error] [pid 12503] response_body = json.loads(response.text)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951021 2017] [:error] [pid 12503] File \"/usr/lib64/python3.4/json/__init__.py\", line 318, in loads\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951031 2017] [:error] [pid 12503] return _default_decoder.decode(s)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951040 2017] [:error] [pid 12503] File \"/usr/lib64/python3.4/json/decoder.py\", line 343, in decode\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951050 2017] [:error] [pid 12503] obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951060 2017] [:error] [pid 12503] File \"/usr/lib64/python3.4/json/decoder.py\", line 361, in raw_decode\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951069 2017] [:error] [pid 12503] raise ValueError(errmsg(\"Expecting value\", s, err.value)) from None\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951084 2017] [:error] [pid 12503] ValueError: Expecting value: line 1 column 1 (char 0)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.951105 2017] [:error] [pid 12503]\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957345 2017] [:error] [pid 12503] Traceback (most recent call last):\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957380 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executor.py\", line 330, in complete_value_catching_error\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957856 2017] [:error] [pid 12503] exe_context, return_type, field_asts, info, result)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.957885 2017] [:error] [pid 12503] File \"/opt/python/run/venv/local/lib/python3.4/site-packages/graphql/execution/executor.py\", line 383, in complete_value\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.958301 2017] [:error] [pid 12503] raise GraphQLLocatedError(field_asts, original_error=result)\r\nDec 07 04:12:44pm ip-172-30-1-22 error_log : [Thu Dec 07 16:33:42.958356 2017] [:error] [pid 12503] graphql.error.located_error.GraphQLLocatedError: Expecting value: line 1 column 1 (char 0)\r\n```\r\n\r\nPlaid is trying to call `json.loads` on `response.text`, which is apparently ''. \r\n\r\nI'm using plaid-python version 2.0.2.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/106", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/106/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/106/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/106/events", "html_url": "https://github.com/plaid/plaid-python/issues/106", "id": 268180906, "node_id": "MDU6SXNzdWUyNjgxODA5MDY=", "number": 106, "title": "HTTP request helper parses response as JSON without checking for errors", "user": {"login": "felixc", "id": 25445, "node_id": "MDQ6VXNlcjI1NDQ1", "avatar_url": "https://avatars1.githubusercontent.com/u/25445?v=4", "gravatar_id": "", "url": "https://api.github.com/users/felixc", "html_url": "https://github.com/felixc", "followers_url": "https://api.github.com/users/felixc/followers", "following_url": "https://api.github.com/users/felixc/following{/other_user}", "gists_url": "https://api.github.com/users/felixc/gists{/gist_id}", "starred_url": "https://api.github.com/users/felixc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/felixc/subscriptions", "organizations_url": "https://api.github.com/users/felixc/orgs", "repos_url": "https://api.github.com/users/felixc/repos", "events_url": "https://api.github.com/users/felixc/events{/privacy}", "received_events_url": "https://api.github.com/users/felixc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, {"login": "joyzheng", "id": 1304895, "node_id": "MDQ6VXNlcjEzMDQ4OTU=", "avatar_url": "https://avatars1.githubusercontent.com/u/1304895?v=4", "gravatar_id": "", "url": "https://api.github.com/users/joyzheng", "html_url": "https://github.com/joyzheng", "followers_url": "https://api.github.com/users/joyzheng/followers", "following_url": "https://api.github.com/users/joyzheng/following{/other_user}", "gists_url": "https://api.github.com/users/joyzheng/gists{/gist_id}", "starred_url": "https://api.github.com/users/joyzheng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/joyzheng/subscriptions", "organizations_url": "https://api.github.com/users/joyzheng/orgs", "repos_url": "https://api.github.com/users/joyzheng/repos", "events_url": "https://api.github.com/users/joyzheng/events{/privacy}", "received_events_url": "https://api.github.com/users/joyzheng/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2017-10-24T20:49:38Z", "updated_at": "2017-12-05T15:45:04Z", "closed_at": "2017-12-05T02:10:06Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "The `http_request` helper method in `requester.py` unconditionally attempts to parse the response as JSON: https://github.com/plaid/plaid-python/blob/02db6f522b9381361272746123ac916616d48674/plaid/requester.py#L33\r\n\r\nBy \"unconditionally\" I mean that it doesn't first check the HTTP response status code, nor is the `json.loads` call wrapped in a try/except block that would allow it to handle failures.\r\n\r\nThis means that if you get a response like the following, you get a `JSONDecodeError`:\r\n\r\n```html\r\n<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n```\r\n\r\nIdeally, the method should either/both check the HTTP status code and/or catch exceptions from `json.loads`, and raise a custom exception as appropriate, without leaking the `JSONDecodeError`.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/103", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/103/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/103/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/103/events", "html_url": "https://github.com/plaid/plaid-python/issues/103", "id": 261335398, "node_id": "MDU6SXNzdWUyNjEzMzUzOTg=", "number": 103, "title": "New release", "user": {"login": "felixc", "id": 25445, "node_id": "MDQ6VXNlcjI1NDQ1", "avatar_url": "https://avatars1.githubusercontent.com/u/25445?v=4", "gravatar_id": "", "url": "https://api.github.com/users/felixc", "html_url": "https://github.com/felixc", "followers_url": "https://api.github.com/users/felixc/followers", "following_url": "https://api.github.com/users/felixc/following{/other_user}", "gists_url": "https://api.github.com/users/felixc/gists{/gist_id}", "starred_url": "https://api.github.com/users/felixc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/felixc/subscriptions", "organizations_url": "https://api.github.com/users/felixc/orgs", "repos_url": "https://api.github.com/users/felixc/repos", "events_url": "https://api.github.com/users/felixc/events{/privacy}", "received_events_url": "https://api.github.com/users/felixc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-09-28T14:17:40Z", "updated_at": "2017-10-24T23:41:01Z", "closed_at": "2017-10-24T23:41:01Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hi,\r\n\r\nThere have been a couple of bugfixes since the last release that would be good to incorporate into our system. Would it be possible to cut a new bugfix/minor release so we can upgrade? Thanks!\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/102", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/102/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/102/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/102/events", "html_url": "https://github.com/plaid/plaid-python/issues/102", "id": 261229430, "node_id": "MDU6SXNzdWUyNjEyMjk0MzA=", "number": 102, "title": "Dropping python 2.x support (tag  2.x compatible version?)", "user": {"login": "autoferrit", "id": 89895, "node_id": "MDQ6VXNlcjg5ODk1", "avatar_url": "https://avatars2.githubusercontent.com/u/89895?v=4", "gravatar_id": "", "url": "https://api.github.com/users/autoferrit", "html_url": "https://github.com/autoferrit", "followers_url": "https://api.github.com/users/autoferrit/followers", "following_url": "https://api.github.com/users/autoferrit/following{/other_user}", "gists_url": "https://api.github.com/users/autoferrit/gists{/gist_id}", "starred_url": "https://api.github.com/users/autoferrit/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/autoferrit/subscriptions", "organizations_url": "https://api.github.com/users/autoferrit/orgs", "repos_url": "https://api.github.com/users/autoferrit/repos", "events_url": "https://api.github.com/users/autoferrit/events{/privacy}", "received_events_url": "https://api.github.com/users/autoferrit/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 81623424, "node_id": "MDU6TGFiZWw4MTYyMzQyNA==", "url": "https://api.github.com/repos/plaid/plaid-python/labels/question", "name": "question", "color": "cc317c", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-09-28T08:11:05Z", "updated_at": "2017-12-05T15:45:41Z", "closed_at": "2017-12-05T15:45:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am curious to your opinion on dropping python 2.x support in this library. As it stands, python 2 will be End of Life on PyCon 2020. And python 3 usage has surpassed 2.x usage. Most libraries (and now django 2.0) is dropping support for python 2 and supporting 3.4+ (my preference is for 3.5+ for type annotations).\r\n\r\nAs in another issue I posted about adding async support, I would like to use more modern language features. Not supporting python 2.x will make that much easier. \r\n\r\nI know some people are probably using this with 2.x, so I expect some resistance with this. It is fine. I am still debating whether I want to make a dedicated async only fork of plaid-python, which would be easiest. Or to make a PR to this repo to add support for async but still need to keep python 2.x support.\r\n\r\nThis is why I have these 2 issues. I am willing to do much of the work for this. As otherwise, I will be forking it anyways.\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/99", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/99/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/99/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/99/events", "html_url": "https://github.com/plaid/plaid-python/issues/99", "id": 259160663, "node_id": "MDU6SXNzdWUyNTkxNjA2NjM=", "number": 99, "title": "no instituion_id returning with accounts", "user": {"login": "SchlegelThomas", "id": 1458527, "node_id": "MDQ6VXNlcjE0NTg1Mjc=", "avatar_url": "https://avatars3.githubusercontent.com/u/1458527?v=4", "gravatar_id": "", "url": "https://api.github.com/users/SchlegelThomas", "html_url": "https://github.com/SchlegelThomas", "followers_url": "https://api.github.com/users/SchlegelThomas/followers", "following_url": "https://api.github.com/users/SchlegelThomas/following{/other_user}", "gists_url": "https://api.github.com/users/SchlegelThomas/gists{/gist_id}", "starred_url": "https://api.github.com/users/SchlegelThomas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/SchlegelThomas/subscriptions", "organizations_url": "https://api.github.com/users/SchlegelThomas/orgs", "repos_url": "https://api.github.com/users/SchlegelThomas/repos", "events_url": "https://api.github.com/users/SchlegelThomas/events{/privacy}", "received_events_url": "https://api.github.com/users/SchlegelThomas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-09-20T13:20:59Z", "updated_at": "2017-12-05T16:26:06Z", "closed_at": "2017-12-05T16:26:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, making the migration to v2 - institution_id is documented in your api docs, but does not show up in the response for Accounts/get\r\n\r\nhttps://plaid.com/docs/api/#Accounts", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/97", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/97/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/97/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/97/events", "html_url": "https://github.com/plaid/plaid-python/issues/97", "id": 237985980, "node_id": "MDU6SXNzdWUyMzc5ODU5ODA=", "number": 97, "title": "ConnectionError when running Python Quickstart code ", "user": {"login": "syzhang88", "id": 8379968, "node_id": "MDQ6VXNlcjgzNzk5Njg=", "avatar_url": "https://avatars0.githubusercontent.com/u/8379968?v=4", "gravatar_id": "", "url": "https://api.github.com/users/syzhang88", "html_url": "https://github.com/syzhang88", "followers_url": "https://api.github.com/users/syzhang88/followers", "following_url": "https://api.github.com/users/syzhang88/following{/other_user}", "gists_url": "https://api.github.com/users/syzhang88/gists{/gist_id}", "starred_url": "https://api.github.com/users/syzhang88/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/syzhang88/subscriptions", "organizations_url": "https://api.github.com/users/syzhang88/orgs", "repos_url": "https://api.github.com/users/syzhang88/repos", "events_url": "https://api.github.com/users/syzhang88/events{/privacy}", "received_events_url": "https://api.github.com/users/syzhang88/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-06-22T21:58:32Z", "updated_at": "2017-12-05T16:25:58Z", "closed_at": "2017-12-05T16:25:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\n\r\nI get this error when trying to run the python quickstart code on this github. I also tried running the node version, which returned a 400 INVALID_REQUEST error, with error code INVALID_FIELD.\r\n\r\nSpecifically, here is the screenshot when I try to log in using user_good on sandbox mode:\r\n\r\n<img width=\"572\" alt=\"screen shot 2017-06-22 at 10 12 00 am\" src=\"https://user-images.githubusercontent.com/8379968/27457855-1b59b4f4-575b-11e7-899b-1eae5a495636.png\">\r\n\r\nDoes anyone know what could be the issue? Aside from adding my api keys, I have not modified the code. I have used pip to install all the relevant packages.\r\n\r\nThanks!\r\nSam\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/95", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/95/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/95/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/95/events", "html_url": "https://github.com/plaid/plaid-python/issues/95", "id": 231069276, "node_id": "MDU6SXNzdWUyMzEwNjkyNzY=", "number": 95, "title": "most _options params are not documented in the api package", "user": {"login": "zevaverbach", "id": 2838836, "node_id": "MDQ6VXNlcjI4Mzg4MzY=", "avatar_url": "https://avatars3.githubusercontent.com/u/2838836?v=4", "gravatar_id": "", "url": "https://api.github.com/users/zevaverbach", "html_url": "https://github.com/zevaverbach", "followers_url": "https://api.github.com/users/zevaverbach/followers", "following_url": "https://api.github.com/users/zevaverbach/following{/other_user}", "gists_url": "https://api.github.com/users/zevaverbach/gists{/gist_id}", "starred_url": "https://api.github.com/users/zevaverbach/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/zevaverbach/subscriptions", "organizations_url": "https://api.github.com/users/zevaverbach/orgs", "repos_url": "https://api.github.com/users/zevaverbach/repos", "events_url": "https://api.github.com/users/zevaverbach/events{/privacy}", "received_events_url": "https://api.github.com/users/zevaverbach/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-05-24T14:56:09Z", "updated_at": "2017-06-06T22:01:43Z", "closed_at": "2017-06-06T22:01:43Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "I'm happy to add those if you can provide API documentation for them:  For example, while there's an `_options` parameter for `Accounts.get`, there are no parameters documented for `accounts/get` [here](https://plaid.com/docs/api/#accounts).", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/93", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/93/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/93/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/93/events", "html_url": "https://github.com/plaid/plaid-python/issues/93", "id": 229184152, "node_id": "MDU6SXNzdWUyMjkxODQxNTI=", "number": 93, "title": "Clarify which \"Account ID\" is supposed to be used for Stripe integration", "user": {"login": "btubbs", "id": 171200, "node_id": "MDQ6VXNlcjE3MTIwMA==", "avatar_url": "https://avatars3.githubusercontent.com/u/171200?v=4", "gravatar_id": "", "url": "https://api.github.com/users/btubbs", "html_url": "https://github.com/btubbs", "followers_url": "https://api.github.com/users/btubbs/followers", "following_url": "https://api.github.com/users/btubbs/following{/other_user}", "gists_url": "https://api.github.com/users/btubbs/gists{/gist_id}", "starred_url": "https://api.github.com/users/btubbs/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/btubbs/subscriptions", "organizations_url": "https://api.github.com/users/btubbs/orgs", "repos_url": "https://api.github.com/users/btubbs/repos", "events_url": "https://api.github.com/users/btubbs/events{/privacy}", "received_events_url": "https://api.github.com/users/btubbs/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2017-05-16T22:12:50Z", "updated_at": "2017-05-17T17:46:22Z", "closed_at": "2017-05-17T17:46:22Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "It's unclear whether this is a Plaid account ID, or my own Stripe account ID, or the ID of a Stripe account that I have created for one of my users.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/89", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/89/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/89/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/89/events", "html_url": "https://github.com/plaid/plaid-python/issues/89", "id": 223962087, "node_id": "MDU6SXNzdWUyMjM5NjIwODc=", "number": 89, "title": "How to debug PlaidServerError", "user": {"login": "ksindi", "id": 2092714, "node_id": "MDQ6VXNlcjIwOTI3MTQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/2092714?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ksindi", "html_url": "https://github.com/ksindi", "followers_url": "https://api.github.com/users/ksindi/followers", "following_url": "https://api.github.com/users/ksindi/following{/other_user}", "gists_url": "https://api.github.com/users/ksindi/gists{/gist_id}", "starred_url": "https://api.github.com/users/ksindi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ksindi/subscriptions", "organizations_url": "https://api.github.com/users/ksindi/orgs", "repos_url": "https://api.github.com/users/ksindi/repos", "events_url": "https://api.github.com/users/ksindi/events{/privacy}", "received_events_url": "https://api.github.com/users/ksindi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-04-24T21:52:17Z", "updated_at": "2017-04-25T00:38:54Z", "closed_at": "2017-04-25T00:38:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "Using version (1.3.0). I started getting the error `PlaidServerError: An unexpected error has occurred on our systems; we've been notified and are looking into it!` when running `plaid_client.exchange_token(public_token)`. I'm not sure what's the cause of this error and would appreciate any suggestions as to what's happening. We started seeing this last weekend.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/86", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/86/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/86/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/86/events", "html_url": "https://github.com/plaid/plaid-python/issues/86", "id": 214120476, "node_id": "MDU6SXNzdWUyMTQxMjA0NzY=", "number": 86, "title": "Can't install using pip install", "user": {"login": "ioliverm", "id": 2285774, "node_id": "MDQ6VXNlcjIyODU3NzQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/2285774?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ioliverm", "html_url": "https://github.com/ioliverm", "followers_url": "https://api.github.com/users/ioliverm/followers", "following_url": "https://api.github.com/users/ioliverm/following{/other_user}", "gists_url": "https://api.github.com/users/ioliverm/gists{/gist_id}", "starred_url": "https://api.github.com/users/ioliverm/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ioliverm/subscriptions", "organizations_url": "https://api.github.com/users/ioliverm/orgs", "repos_url": "https://api.github.com/users/ioliverm/repos", "events_url": "https://api.github.com/users/ioliverm/events{/privacy}", "received_events_url": "https://api.github.com/users/ioliverm/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "joyzheng", "id": 1304895, "node_id": "MDQ6VXNlcjEzMDQ4OTU=", "avatar_url": "https://avatars1.githubusercontent.com/u/1304895?v=4", "gravatar_id": "", "url": "https://api.github.com/users/joyzheng", "html_url": "https://github.com/joyzheng", "followers_url": "https://api.github.com/users/joyzheng/followers", "following_url": "https://api.github.com/users/joyzheng/following{/other_user}", "gists_url": "https://api.github.com/users/joyzheng/gists{/gist_id}", "starred_url": "https://api.github.com/users/joyzheng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/joyzheng/subscriptions", "organizations_url": "https://api.github.com/users/joyzheng/orgs", "repos_url": "https://api.github.com/users/joyzheng/repos", "events_url": "https://api.github.com/users/joyzheng/events{/privacy}", "received_events_url": "https://api.github.com/users/joyzheng/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "joyzheng", "id": 1304895, "node_id": "MDQ6VXNlcjEzMDQ4OTU=", "avatar_url": "https://avatars1.githubusercontent.com/u/1304895?v=4", "gravatar_id": "", "url": "https://api.github.com/users/joyzheng", "html_url": "https://github.com/joyzheng", "followers_url": "https://api.github.com/users/joyzheng/followers", "following_url": "https://api.github.com/users/joyzheng/following{/other_user}", "gists_url": "https://api.github.com/users/joyzheng/gists{/gist_id}", "starred_url": "https://api.github.com/users/joyzheng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/joyzheng/subscriptions", "organizations_url": "https://api.github.com/users/joyzheng/orgs", "repos_url": "https://api.github.com/users/joyzheng/repos", "events_url": "https://api.github.com/users/joyzheng/events{/privacy}", "received_events_url": "https://api.github.com/users/joyzheng/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2017-03-14T16:00:37Z", "updated_at": "2017-03-14T18:42:34Z", "closed_at": "2017-03-14T18:30:26Z", "author_association": "NONE", "active_lock_reason": null, "body": "pip install plaid-python throws an exception saying:\r\n\r\nImportError: No module named 'requests'\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/78", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/78/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/78/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/78/events", "html_url": "https://github.com/plaid/plaid-python/issues/78", "id": 212909554, "node_id": "MDU6SXNzdWUyMTI5MDk1NTQ=", "number": 78, "title": "`requests` requirement too strict", "user": {"login": "glyph", "id": 716529, "node_id": "MDQ6VXNlcjcxNjUyOQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/716529?v=4", "gravatar_id": "", "url": "https://api.github.com/users/glyph", "html_url": "https://github.com/glyph", "followers_url": "https://api.github.com/users/glyph/followers", "following_url": "https://api.github.com/users/glyph/following{/other_user}", "gists_url": "https://api.github.com/users/glyph/gists{/gist_id}", "starred_url": "https://api.github.com/users/glyph/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/glyph/subscriptions", "organizations_url": "https://api.github.com/users/glyph/orgs", "repos_url": "https://api.github.com/users/glyph/repos", "events_url": "https://api.github.com/users/glyph/events{/privacy}", "received_events_url": "https://api.github.com/users/glyph/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-03-09T01:32:11Z", "updated_at": "2017-03-15T06:08:45Z", "closed_at": "2017-03-10T17:21:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "https://github.com/plaid/plaid-python/blob/master/setup.py#L20 uses an `==` constraint to pin `requests` to an exact version.  This prevents automatic security updates of `requests` on projects which depend on `plaid-python`, which seems like a problem.\r\n\r\nIn general, `setup.py` should be lenient and `requirements.txt` should be strict, as documented in Donald Stufft's [canonical article on the subject](https://caremad.io/posts/2013/07/setup-vs-requirement/).\r\n\r\nIs there a specific reason that this requirement is pinned?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/76", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/76/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/76/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/76/events", "html_url": "https://github.com/plaid/plaid-python/issues/76", "id": 205833483, "node_id": "MDU6SXNzdWUyMDU4MzM0ODM=", "number": 76, "title": "Readme misleading for App Engine requests", "user": {"login": "onejgordon", "id": 57584, "node_id": "MDQ6VXNlcjU3NTg0", "avatar_url": "https://avatars2.githubusercontent.com/u/57584?v=4", "gravatar_id": "", "url": "https://api.github.com/users/onejgordon", "html_url": "https://github.com/onejgordon", "followers_url": "https://api.github.com/users/onejgordon/followers", "following_url": "https://api.github.com/users/onejgordon/following{/other_user}", "gists_url": "https://api.github.com/users/onejgordon/gists{/gist_id}", "starred_url": "https://api.github.com/users/onejgordon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/onejgordon/subscriptions", "organizations_url": "https://api.github.com/users/onejgordon/orgs", "repos_url": "https://api.github.com/users/onejgordon/repos", "events_url": "https://api.github.com/users/onejgordon/events{/privacy}", "received_events_url": "https://api.github.com/users/onejgordon/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-02-07T09:36:34Z", "updated_at": "2017-03-14T15:13:55Z", "closed_at": "2017-03-14T15:13:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "On GAE plaid-python uses urlfetch, which returns a _URLFetchResult object. This object has no json() method.\r\n\r\nReadme should read (for the GAE case): \r\n\r\n```\r\nclient = Client(client_id='***', secret='***', access_token='usertoken')\r\nresponse = client.connect_get()\r\nif response.status_code == 200:\r\n    transactions = json.loads(response.content)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/74", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/74/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/74/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/74/events", "html_url": "https://github.com/plaid/plaid-python/issues/74", "id": 201420013, "node_id": "MDU6SXNzdWUyMDE0MjAwMTM=", "number": 74, "title": "Institution Listing", "user": {"login": "battery514", "id": 12558861, "node_id": "MDQ6VXNlcjEyNTU4ODYx", "avatar_url": "https://avatars2.githubusercontent.com/u/12558861?v=4", "gravatar_id": "", "url": "https://api.github.com/users/battery514", "html_url": "https://github.com/battery514", "followers_url": "https://api.github.com/users/battery514/followers", "following_url": "https://api.github.com/users/battery514/following{/other_user}", "gists_url": "https://api.github.com/users/battery514/gists{/gist_id}", "starred_url": "https://api.github.com/users/battery514/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/battery514/subscriptions", "organizations_url": "https://api.github.com/users/battery514/orgs", "repos_url": "https://api.github.com/users/battery514/repos", "events_url": "https://api.github.com/users/battery514/events{/privacy}", "received_events_url": "https://api.github.com/users/battery514/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-01-17T22:09:15Z", "updated_at": "2017-01-18T00:22:53Z", "closed_at": "2017-01-18T00:22:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "I pulled this code from the documentation:\r\n\r\n    # Pull 50 institutions that support both Auth and Connect\r\n    institutions = client.institutions(count=50, offset=0, products=[\"auth\",\"connect\"]).json()\r\n\r\nBut that results in the below error:\r\n\r\n    TypeError: institutions() got an unexpected keyword argument 'count'\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/65", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/65/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/65/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/65/events", "html_url": "https://github.com/plaid/plaid-python/issues/65", "id": 171692440, "node_id": "MDU6SXNzdWUxNzE2OTI0NDA=", "number": 65, "title": "What about restricting the date when pulling transactions?", "user": {"login": "ronenmagid", "id": 422707, "node_id": "MDQ6VXNlcjQyMjcwNw==", "avatar_url": "https://avatars0.githubusercontent.com/u/422707?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ronenmagid", "html_url": "https://github.com/ronenmagid", "followers_url": "https://api.github.com/users/ronenmagid/followers", "following_url": "https://api.github.com/users/ronenmagid/following{/other_user}", "gists_url": "https://api.github.com/users/ronenmagid/gists{/gist_id}", "starred_url": "https://api.github.com/users/ronenmagid/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ronenmagid/subscriptions", "organizations_url": "https://api.github.com/users/ronenmagid/orgs", "repos_url": "https://api.github.com/users/ronenmagid/repos", "events_url": "https://api.github.com/users/ronenmagid/events{/privacy}", "received_events_url": "https://api.github.com/users/ronenmagid/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-08-17T15:47:13Z", "updated_at": "2017-03-14T15:11:37Z", "closed_at": "2017-03-14T15:11:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "Do you have support for limiting the number of pulled transactions by what's available for the options parameter? e.g. {\"gte\": \"2016-08-17\"}. \n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/63", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/63/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/63/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/63/events", "html_url": "https://github.com/plaid/plaid-python/issues/63", "id": 168149923, "node_id": "MDU6SXNzdWUxNjgxNDk5MjM=", "number": 63, "title": "Options: lte and gte", "user": {"login": "angelafgao", "id": 20645800, "node_id": "MDQ6VXNlcjIwNjQ1ODAw", "avatar_url": "https://avatars3.githubusercontent.com/u/20645800?v=4", "gravatar_id": "", "url": "https://api.github.com/users/angelafgao", "html_url": "https://github.com/angelafgao", "followers_url": "https://api.github.com/users/angelafgao/followers", "following_url": "https://api.github.com/users/angelafgao/following{/other_user}", "gists_url": "https://api.github.com/users/angelafgao/gists{/gist_id}", "starred_url": "https://api.github.com/users/angelafgao/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/angelafgao/subscriptions", "organizations_url": "https://api.github.com/users/angelafgao/orgs", "repos_url": "https://api.github.com/users/angelafgao/repos", "events_url": "https://api.github.com/users/angelafgao/events{/privacy}", "received_events_url": "https://api.github.com/users/angelafgao/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2016-07-28T17:21:05Z", "updated_at": "2016-08-03T18:43:22Z", "closed_at": "2016-08-03T18:43:22Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am trying to pull transaction data from fixed dates, but I am not sure where to pass in the lte and gte. \n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/62", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/62/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/62/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/62/events", "html_url": "https://github.com/plaid/plaid-python/issues/62", "id": 167157915, "node_id": "MDU6SXNzdWUxNjcxNTc5MTU=", "number": 62, "title": "SSLError: EOF occurred in violation of protocol (_ssl.c:581)", "user": {"login": "chrismv48", "id": 2280920, "node_id": "MDQ6VXNlcjIyODA5MjA=", "avatar_url": "https://avatars3.githubusercontent.com/u/2280920?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chrismv48", "html_url": "https://github.com/chrismv48", "followers_url": "https://api.github.com/users/chrismv48/followers", "following_url": "https://api.github.com/users/chrismv48/following{/other_user}", "gists_url": "https://api.github.com/users/chrismv48/gists{/gist_id}", "starred_url": "https://api.github.com/users/chrismv48/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chrismv48/subscriptions", "organizations_url": "https://api.github.com/users/chrismv48/orgs", "repos_url": "https://api.github.com/users/chrismv48/repos", "events_url": "https://api.github.com/users/chrismv48/events{/privacy}", "received_events_url": "https://api.github.com/users/chrismv48/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2016-07-23T00:53:38Z", "updated_at": "2017-05-06T14:04:32Z", "closed_at": "2016-08-16T18:14:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "I get this error both when using the library to make API calls and when using the requests library directly: `SSLError: EOF occurred in violation of protocol (_ssl.c:581)`\n\nI am able to get a 200 response via curl and also when using the production api endpoint.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/61", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/61/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/61/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/61/events", "html_url": "https://github.com/plaid/plaid-python/issues/61", "id": 166622232, "node_id": "MDU6SXNzdWUxNjY2MjIyMzI=", "number": 61, "title": "Adding other banks to API", "user": {"login": "taylorfturner", "id": 17475807, "node_id": "MDQ6VXNlcjE3NDc1ODA3", "avatar_url": "https://avatars0.githubusercontent.com/u/17475807?v=4", "gravatar_id": "", "url": "https://api.github.com/users/taylorfturner", "html_url": "https://github.com/taylorfturner", "followers_url": "https://api.github.com/users/taylorfturner/followers", "following_url": "https://api.github.com/users/taylorfturner/following{/other_user}", "gists_url": "https://api.github.com/users/taylorfturner/gists{/gist_id}", "starred_url": "https://api.github.com/users/taylorfturner/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/taylorfturner/subscriptions", "organizations_url": "https://api.github.com/users/taylorfturner/orgs", "repos_url": "https://api.github.com/users/taylorfturner/repos", "events_url": "https://api.github.com/users/taylorfturner/events{/privacy}", "received_events_url": "https://api.github.com/users/taylorfturner/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-07-20T16:17:02Z", "updated_at": "2016-08-04T15:20:52Z", "closed_at": "2016-08-04T15:20:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is the below list exhaustive for banks to which I am able to connect? (Link to Plaid's list: (https://plaid.com/docs/api/#institution-overview)\n\nAmerican Express\nBank of America\nCapital One 360\nCharles Schwab\nChase\nCiti\nFidelity\nNavy Federal Credit Union\nPNC\nSunTrust\nTD Bank\nUS Bank\nUSAA\nWells Fargo\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/56", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/56/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/56/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/56/events", "html_url": "https://github.com/plaid/plaid-python/issues/56", "id": 140345817, "node_id": "MDU6SXNzdWUxNDAzNDU4MTc=", "number": 56, "title": "Income and Risk Support", "user": {"login": "bsgilber", "id": 12210444, "node_id": "MDQ6VXNlcjEyMjEwNDQ0", "avatar_url": "https://avatars1.githubusercontent.com/u/12210444?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bsgilber", "html_url": "https://github.com/bsgilber", "followers_url": "https://api.github.com/users/bsgilber/followers", "following_url": "https://api.github.com/users/bsgilber/following{/other_user}", "gists_url": "https://api.github.com/users/bsgilber/gists{/gist_id}", "starred_url": "https://api.github.com/users/bsgilber/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bsgilber/subscriptions", "organizations_url": "https://api.github.com/users/bsgilber/orgs", "repos_url": "https://api.github.com/users/bsgilber/repos", "events_url": "https://api.github.com/users/bsgilber/events{/privacy}", "received_events_url": "https://api.github.com/users/bsgilber/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-03-12T04:24:09Z", "updated_at": "2016-04-06T18:28:17Z", "closed_at": "2016-04-06T18:28:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am able to use the Plaid Link to authenticate and pull user data, but I am having trouble getting all the information that the API reference says is available.\n\nCurrently I can use:\n- info_get() to find personal information\n- auth_get() to find balances, account information\n- connect_get() for transaction information\n\nAm I just not seeing the documentation for risk and income or is that a WiP?\n\nThanks!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/55", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/55/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/55/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/55/events", "html_url": "https://github.com/plaid/plaid-python/issues/55", "id": 138853144, "node_id": "MDU6SXNzdWUxMzg4NTMxNDQ=", "number": 55, "title": "README Examples Don't Work", "user": {"login": "phoxelua", "id": 5024679, "node_id": "MDQ6VXNlcjUwMjQ2Nzk=", "avatar_url": "https://avatars2.githubusercontent.com/u/5024679?v=4", "gravatar_id": "", "url": "https://api.github.com/users/phoxelua", "html_url": "https://github.com/phoxelua", "followers_url": "https://api.github.com/users/phoxelua/followers", "following_url": "https://api.github.com/users/phoxelua/following{/other_user}", "gists_url": "https://api.github.com/users/phoxelua/gists{/gist_id}", "starred_url": "https://api.github.com/users/phoxelua/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/phoxelua/subscriptions", "organizations_url": "https://api.github.com/users/phoxelua/orgs", "repos_url": "https://api.github.com/users/phoxelua/repos", "events_url": "https://api.github.com/users/phoxelua/events{/privacy}", "received_events_url": "https://api.github.com/users/phoxelua/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-03-07T00:17:05Z", "updated_at": "2016-04-06T18:28:55Z", "closed_at": "2016-04-06T18:28:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Two README examples fail. One:\n\n``` python\nfrom plaid import Client\nfrom plaid import errors as plaid_errors\nfrom plaid.utils import json\n\n\nclient = Client()\ninstitutions = json.loads(client.institutions().content)\ncategories = json.loads(client.categories().content)\n```\n\nAnd it breaks cause the Client doesn't actually allow no params for `client_id` and `secret`. Even if I use a Client with a legitimate params, as below it will fail because of `json.loads` (see below).\n\nI also tried this example (with my actual client, username, password, etc):\n\n``` python\nfrom plaid import Client\nfrom plaid import errors as plaid_errors\nfrom plaid.utils import json\n\n\nclient = Client(client_id='***', secret='***')\naccount_type = 'bofa'\n\ntry:\n    response = client.connect(account_type, {\n     'username': '***',\n     'password': '***'\n    })\nexcept plaid_errors.PlaidError:\n     pass\nelse:\n    connect_data = json.loads(response.content)\n```\n\nThis works with a 200 but `response.content` is a byte object and not a string. So json.loads fails. This happens using both python's json library and plaid's json util. `response.text` and `response.json()` still give me what I want so there's a workaround.\n\nI'm using python 3.4 and it looks like you guys added support for that in the 1.10. \n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/54", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/54/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/54/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/54/events", "html_url": "https://github.com/plaid/plaid-python/issues/54", "id": 138594069, "node_id": "MDU6SXNzdWUxMzg1OTQwNjk=", "number": 54, "title": "Do not include MFA parameter in /step requests when a send_method is provided", "user": {"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-03-04T21:41:21Z", "updated_at": "2017-03-10T17:24:59Z", "closed_at": "2017-03-10T17:24:59Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "See https://github.com/plaid/plaid-python/blob/master/plaid/client.py#L201-L210:\n\n``` python\n        return http_request(\n            url,\n            method=method,\n            data=dict({\n                'type': account_type,\n                'mfa': mfa,\n                'options': json.dumps(options if options is not None else {}),\n            }, **credentials),\n            suppress_errors=self.suppress_http_errors\n        )\n```\n\nThe `mfa` parameter should not be included if `options.send_method` is present.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/49", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/49/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/49/events", "html_url": "https://github.com/plaid/plaid-python/issues/49", "id": 125088917, "node_id": "MDU6SXNzdWUxMjUwODg5MTc=", "number": 49, "title": "README contains erroneous code", "user": {"login": "tarkatronic", "id": 37809, "node_id": "MDQ6VXNlcjM3ODA5", "avatar_url": "https://avatars0.githubusercontent.com/u/37809?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tarkatronic", "html_url": "https://github.com/tarkatronic", "followers_url": "https://api.github.com/users/tarkatronic/followers", "following_url": "https://api.github.com/users/tarkatronic/following{/other_user}", "gists_url": "https://api.github.com/users/tarkatronic/gists{/gist_id}", "starred_url": "https://api.github.com/users/tarkatronic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tarkatronic/subscriptions", "organizations_url": "https://api.github.com/users/tarkatronic/orgs", "repos_url": "https://api.github.com/users/tarkatronic/repos", "events_url": "https://api.github.com/users/tarkatronic/events{/privacy}", "received_events_url": "https://api.github.com/users/tarkatronic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-01-06T01:12:37Z", "updated_at": "2016-04-27T18:49:43Z", "closed_at": "2016-04-27T18:49:43Z", "author_association": "NONE", "active_lock_reason": null, "body": "In the README, there is a section with the following code:\n\n``` python\nfrom plaid import Client\n\nclient = Client.config({\n    'url': 'https://tartan.plaid.com',\n    'suppress_http_errors': True,\n})\nresponse = client.connect('bofa', {\n    'username': '[something_invalid]',\n    'password': '***'\n})\n```\n\nHowever, this doesn't actually work properly, as `config()` doesn't return a Client instance. It would have to look more like:\n\n``` python\nfrom plaid import Client\n\nClient.config({\n    'url': 'https://tartan.plaid.com',\n    'suppress_http_errors': True,\n})\nclient = Client('test_id', 'test_secret')\nresponse = client.connect('bofa', {\n    'username': '[something_invalid]',\n    'password': '***'\n})\n```\n\nAlternatively, correct me if I'm wrong, but couldn't I just use:\n\n``` python\nfrom plaid import Client\n\nclient = Client('test_id', 'test_secret')\nclient.base_url = 'https://tartan.plaid.com'\nclient.suppress_http_errors = True\nresponse = client.connect('bofa', {\n    'username': '[something_invalid]',\n    'password': '***'\n})\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/46", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/46/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/46/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/46/events", "html_url": "https://github.com/plaid/plaid-python/issues/46", "id": 124840378, "node_id": "MDU6SXNzdWUxMjQ4NDAzNzg=", "number": 46, "title": "Support for institution search?", "user": {"login": "tarkatronic", "id": 37809, "node_id": "MDQ6VXNlcjM3ODA5", "avatar_url": "https://avatars0.githubusercontent.com/u/37809?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tarkatronic", "html_url": "https://github.com/tarkatronic", "followers_url": "https://api.github.com/users/tarkatronic/followers", "following_url": "https://api.github.com/users/tarkatronic/following{/other_user}", "gists_url": "https://api.github.com/users/tarkatronic/gists{/gist_id}", "starred_url": "https://api.github.com/users/tarkatronic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tarkatronic/subscriptions", "organizations_url": "https://api.github.com/users/tarkatronic/orgs", "repos_url": "https://api.github.com/users/tarkatronic/repos", "events_url": "https://api.github.com/users/tarkatronic/events{/privacy}", "received_events_url": "https://api.github.com/users/tarkatronic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-01-04T21:11:05Z", "updated_at": "2016-01-06T00:52:01Z", "closed_at": "2016-01-06T00:44:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "It appears there is no way to use this library to perform a search against Long Tail institutions. Was this excluded intentionally? If not, are there plans to support that? Is this something I would need to build myself?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/39", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/39/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/39/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/39/events", "html_url": "https://github.com/plaid/plaid-python/issues/39", "id": 120894617, "node_id": "MDU6SXNzdWUxMjA4OTQ2MTc=", "number": 39, "title": "add accountId parameter to exchange_token", "user": {"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-12-07T23:34:27Z", "updated_at": "2015-12-11T19:04:45Z", "closed_at": "2015-12-11T19:04:45Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/36", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/36/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/36/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/36/events", "html_url": "https://github.com/plaid/plaid-python/issues/36", "id": 119558725, "node_id": "MDU6SXNzdWUxMTk1NTg3MjU=", "number": 36, "title": "Support for pending transactions?", "user": {"login": "nicksergeant", "id": 27332, "node_id": "MDQ6VXNlcjI3MzMy", "avatar_url": "https://avatars2.githubusercontent.com/u/27332?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nicksergeant", "html_url": "https://github.com/nicksergeant", "followers_url": "https://api.github.com/users/nicksergeant/followers", "following_url": "https://api.github.com/users/nicksergeant/following{/other_user}", "gists_url": "https://api.github.com/users/nicksergeant/gists{/gist_id}", "starred_url": "https://api.github.com/users/nicksergeant/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nicksergeant/subscriptions", "organizations_url": "https://api.github.com/users/nicksergeant/orgs", "repos_url": "https://api.github.com/users/nicksergeant/repos", "events_url": "https://api.github.com/users/nicksergeant/events{/privacy}", "received_events_url": "https://api.github.com/users/nicksergeant/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2015-11-30T19:07:56Z", "updated_at": "2017-04-12T03:22:27Z", "closed_at": "2017-03-14T15:12:33Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "It seems support for pending transactions must pass through to the `/connect` endpoint as per the docs:\n\n![http://i.nick.sg/image/321k2Q0g353N/Image%202015-11-30%20at%202.05.46%20PM.png](http://i.nick.sg/image/321k2Q0g353N/Image%202015-11-30%20at%202.05.46%20PM.png)\n\nHowever, passing this option like this does not appear to return pending transactions:\n\n```\nresponse = client.connect('usaa', {\n    'username': 'user',\n    'password': 'pass',\n    'pin': '1234'\n}, options={\n    'pending': True\n})\n```\n\nThis Python lib seems to want the `pending` arg on `connect_get` here: https://github.com/plaid/plaid-python/blob/master/plaid/client.py#L390, but that doesn't appear to work, either.\n\nNot sure if this issue is with `plaid-python`'s implementation or an issue with the API.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/32", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/32/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/32/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/32/events", "html_url": "https://github.com/plaid/plaid-python/issues/32", "id": 108171902, "node_id": "MDU6SXNzdWUxMDgxNzE5MDI=", "number": 32, "title": "CI testing should be in place", "user": {"login": "pbernasconi", "id": 1716394, "node_id": "MDQ6VXNlcjE3MTYzOTQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/1716394?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pbernasconi", "html_url": "https://github.com/pbernasconi", "followers_url": "https://api.github.com/users/pbernasconi/followers", "following_url": "https://api.github.com/users/pbernasconi/following{/other_user}", "gists_url": "https://api.github.com/users/pbernasconi/gists{/gist_id}", "starred_url": "https://api.github.com/users/pbernasconi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pbernasconi/subscriptions", "organizations_url": "https://api.github.com/users/pbernasconi/orgs", "repos_url": "https://api.github.com/users/pbernasconi/repos", "events_url": "https://api.github.com/users/pbernasconi/events{/privacy}", "received_events_url": "https://api.github.com/users/pbernasconi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-09-24T17:02:37Z", "updated_at": "2015-09-29T16:03:42Z", "closed_at": "2015-09-29T16:03:42Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "It looks like this library has tests setup in place - but I can't find travis or circleci tests running anywhere.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/31", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/31/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/31/events", "html_url": "https://github.com/plaid/plaid-python/issues/31", "id": 106678714, "node_id": "MDU6SXNzdWUxMDY2Nzg3MTQ=", "number": 31, "title": "Schwab Support", "user": {"login": "sjohnson540", "id": 662544, "node_id": "MDQ6VXNlcjY2MjU0NA==", "avatar_url": "https://avatars2.githubusercontent.com/u/662544?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sjohnson540", "html_url": "https://github.com/sjohnson540", "followers_url": "https://api.github.com/users/sjohnson540/followers", "following_url": "https://api.github.com/users/sjohnson540/following{/other_user}", "gists_url": "https://api.github.com/users/sjohnson540/gists{/gist_id}", "starred_url": "https://api.github.com/users/sjohnson540/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sjohnson540/subscriptions", "organizations_url": "https://api.github.com/users/sjohnson540/orgs", "repos_url": "https://api.github.com/users/sjohnson540/repos", "events_url": "https://api.github.com/users/sjohnson540/events{/privacy}", "received_events_url": "https://api.github.com/users/sjohnson540/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-09-16T01:28:45Z", "updated_at": "2017-03-14T15:11:56Z", "closed_at": "2017-03-14T15:11:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello! I noticed on the reference guide, that `schwab` is listed as a supported institution, yet I get an error saying it is not supported using the python library and plain old curl. I just thought I would give the heads up so you can update your guide to avoid other confused users!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/27", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/27/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/27/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/27/events", "html_url": "https://github.com/plaid/plaid-python/issues/27", "id": 101741183, "node_id": "MDU6SXNzdWUxMDE3NDExODM=", "number": 27, "title": "Add complete /info support", "user": {"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-08-18T20:24:27Z", "updated_at": "2016-04-06T18:29:31Z", "closed_at": "2016-04-06T18:29:31Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/24", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/24/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/24/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/24/events", "html_url": "https://github.com/plaid/plaid-python/issues/24", "id": 91842193, "node_id": "MDU6SXNzdWU5MTg0MjE5Mw==", "number": 24, "title": "Bump requests version to 2.7.0", "user": {"login": "Bpless", "id": 573606, "node_id": "MDQ6VXNlcjU3MzYwNg==", "avatar_url": "https://avatars3.githubusercontent.com/u/573606?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Bpless", "html_url": "https://github.com/Bpless", "followers_url": "https://api.github.com/users/Bpless/followers", "following_url": "https://api.github.com/users/Bpless/following{/other_user}", "gists_url": "https://api.github.com/users/Bpless/gists{/gist_id}", "starred_url": "https://api.github.com/users/Bpless/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Bpless/subscriptions", "organizations_url": "https://api.github.com/users/Bpless/orgs", "repos_url": "https://api.github.com/users/Bpless/repos", "events_url": "https://api.github.com/users/Bpless/events{/privacy}", "received_events_url": "https://api.github.com/users/Bpless/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-06-29T15:52:11Z", "updated_at": "2015-06-29T16:00:01Z", "closed_at": "2015-06-29T16:00:01Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/22", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/22/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/22/events", "html_url": "https://github.com/plaid/plaid-python/issues/22", "id": 89627720, "node_id": "MDU6SXNzdWU4OTYyNzcyMA==", "number": 22, "title": "Add PUBLISHING.md to document the module's publish process", "user": {"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-06-19T18:21:41Z", "updated_at": "2017-10-23T21:02:12Z", "closed_at": "2017-10-23T21:02:12Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/18", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/18/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/18/events", "html_url": "https://github.com/plaid/plaid-python/issues/18", "id": 82179224, "node_id": "MDU6SXNzdWU4MjE3OTIyNA==", "number": 18, "title": "Add /exchange_token example to README.md", "user": {"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-05-29T00:02:03Z", "updated_at": "2015-06-05T18:54:25Z", "closed_at": "2015-06-05T18:54:25Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/13", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/13/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/13/events", "html_url": "https://github.com/plaid/plaid-python/issues/13", "id": 76378514, "node_id": "MDU6SXNzdWU3NjM3ODUxNA==", "number": 13, "title": "Add /exchange_token API endpoint", "user": {"login": "michaelckelly", "id": 1106237, "node_id": "MDQ6VXNlcjExMDYyMzc=", "avatar_url": "https://avatars1.githubusercontent.com/u/1106237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/michaelckelly", "html_url": "https://github.com/michaelckelly", "followers_url": "https://api.github.com/users/michaelckelly/followers", "following_url": "https://api.github.com/users/michaelckelly/following{/other_user}", "gists_url": "https://api.github.com/users/michaelckelly/gists{/gist_id}", "starred_url": "https://api.github.com/users/michaelckelly/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/michaelckelly/subscriptions", "organizations_url": "https://api.github.com/users/michaelckelly/orgs", "repos_url": "https://api.github.com/users/michaelckelly/repos", "events_url": "https://api.github.com/users/michaelckelly/events{/privacy}", "received_events_url": "https://api.github.com/users/michaelckelly/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-05-14T14:37:31Z", "updated_at": "2015-05-21T18:10:14Z", "closed_at": "2015-05-21T18:10:14Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "See [/exchange_token](https://github.com/plaid/link#exchange_token-endpoint) for endpoint specific docs.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/8", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/8/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/8/events", "html_url": "https://github.com/plaid/plaid-python/issues/8", "id": 61713087, "node_id": "MDU6SXNzdWU2MTcxMzA4Nw==", "number": 8, "title": "Update README sample", "user": {"login": "pamolloy", "id": 996930, "node_id": "MDQ6VXNlcjk5NjkzMA==", "avatar_url": "https://avatars0.githubusercontent.com/u/996930?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pamolloy", "html_url": "https://github.com/pamolloy", "followers_url": "https://api.github.com/users/pamolloy/followers", "following_url": "https://api.github.com/users/pamolloy/following{/other_user}", "gists_url": "https://api.github.com/users/pamolloy/gists{/gist_id}", "starred_url": "https://api.github.com/users/pamolloy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pamolloy/subscriptions", "organizations_url": "https://api.github.com/users/pamolloy/orgs", "repos_url": "https://api.github.com/users/pamolloy/repos", "events_url": "https://api.github.com/users/pamolloy/events{/privacy}", "received_events_url": "https://api.github.com/users/pamolloy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-03-14T23:25:54Z", "updated_at": "2015-06-05T18:57:21Z", "closed_at": "2015-06-05T18:57:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "I believe line 22 in the README.md should be `client.connect_step` instead of `client.step`.\n\nAlso the MFA isn't entirely clear to me. My BoA account was locked while trying to connect to it. I believe the following should support multiple security questions, but the answers kept being rejected. \n\n``` python\nif connect.ok:\n    response = json.loads(connect.content)\n    while response['mfa']:\n        answer = raw_input(response['mfa'][0][\"question\"] + \": \")\n        step = client.connect_step(account_type='bofa', mfa=answer)\n        reponse = step.content\n    if step.ok:\n        transactions = json.loads(step.content)\n```\n\nAlso, is there a difference between `Client.auth_step()` and `Client.connect_step()`?\n\nAnd finally `transactions = json.loads(step.content)` doesn't make sense to me. Wouldn't one need to call `Client.transactions()` to get a list of transactions?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/5", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/5/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/5/events", "html_url": "https://github.com/plaid/plaid-python/issues/5", "id": 48933364, "node_id": "MDU6SXNzdWU0ODkzMzM2NA==", "number": 5, "title": "Support /auth endpoint", "user": {"login": "pgorsira", "id": 1266295, "node_id": "MDQ6VXNlcjEyNjYyOTU=", "avatar_url": "https://avatars2.githubusercontent.com/u/1266295?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pgorsira", "html_url": "https://github.com/pgorsira", "followers_url": "https://api.github.com/users/pgorsira/followers", "following_url": "https://api.github.com/users/pgorsira/following{/other_user}", "gists_url": "https://api.github.com/users/pgorsira/gists{/gist_id}", "starred_url": "https://api.github.com/users/pgorsira/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pgorsira/subscriptions", "organizations_url": "https://api.github.com/users/pgorsira/orgs", "repos_url": "https://api.github.com/users/pgorsira/repos", "events_url": "https://api.github.com/users/pgorsira/events{/privacy}", "received_events_url": "https://api.github.com/users/pgorsira/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2014-11-15T21:30:46Z", "updated_at": "2015-01-07T20:12:40Z", "closed_at": "2015-01-07T20:12:40Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "It'd be great if I could use this library to register an auth user and grab their details.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/plaid/plaid-python/issues/4", "repository_url": "https://api.github.com/repos/plaid/plaid-python", "labels_url": "https://api.github.com/repos/plaid/plaid-python/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/plaid/plaid-python/issues/4/comments", "events_url": "https://api.github.com/repos/plaid/plaid-python/issues/4/events", "html_url": "https://github.com/plaid/plaid-python/issues/4", "id": 33246984, "node_id": "MDU6SXNzdWUzMzI0Njk4NA==", "number": 4, "title": "pypi release?", "user": {"login": "przerull", "id": 304209, "node_id": "MDQ6VXNlcjMwNDIwOQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/304209?v=4", "gravatar_id": "", "url": "https://api.github.com/users/przerull", "html_url": "https://github.com/przerull", "followers_url": "https://api.github.com/users/przerull/followers", "following_url": "https://api.github.com/users/przerull/following{/other_user}", "gists_url": "https://api.github.com/users/przerull/gists{/gist_id}", "starred_url": "https://api.github.com/users/przerull/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/przerull/subscriptions", "organizations_url": "https://api.github.com/users/przerull/orgs", "repos_url": "https://api.github.com/users/przerull/repos", "events_url": "https://api.github.com/users/przerull/events{/privacy}", "received_events_url": "https://api.github.com/users/przerull/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 81623424, "node_id": "MDU6TGFiZWw4MTYyMzQyNA==", "url": "https://api.github.com/repos/plaid/plaid-python/labels/question", "name": "question", "color": "cc317c", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2014-05-10T19:45:34Z", "updated_at": "2014-11-14T00:56:14Z", "closed_at": "2014-11-14T00:56:14Z", "author_association": "NONE", "active_lock_reason": null, "body": "Are there any plans to release this package on pypi?  I noticed that a [package exists](https://pypi.python.org/pypi/plaid-python/) out there but it does not have any distributions.\n", "performed_via_github_app": null, "score": 1.0}]}