{"total_count": 56, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/73", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/73/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/73/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/73/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/73", "id": 663227268, "node_id": "MDU6SXNzdWU2NjMyMjcyNjg=", "number": 73, "title": "trouble using PyKCS11 with libbeidpkcs11", "user": {"login": "linuxunderground", "id": 7894744, "node_id": "MDQ6VXNlcjc4OTQ3NDQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/7894744?v=4", "gravatar_id": "", "url": "https://api.github.com/users/linuxunderground", "html_url": "https://github.com/linuxunderground", "followers_url": "https://api.github.com/users/linuxunderground/followers", "following_url": "https://api.github.com/users/linuxunderground/following{/other_user}", "gists_url": "https://api.github.com/users/linuxunderground/gists{/gist_id}", "starred_url": "https://api.github.com/users/linuxunderground/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/linuxunderground/subscriptions", "organizations_url": "https://api.github.com/users/linuxunderground/orgs", "repos_url": "https://api.github.com/users/linuxunderground/repos", "events_url": "https://api.github.com/users/linuxunderground/events{/privacy}", "received_events_url": "https://api.github.com/users/linuxunderground/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-07-21T18:39:51Z", "updated_at": "2020-07-31T13:57:26Z", "closed_at": "2020-07-31T13:57:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: Gentoo linux\r\n* PyKCS11 version: 1.5.8\r\n* Python version: 3.8\r\n* PKCS#11 library used: libbeidpkcs11 version 5.0+\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nYou will find all the explanations here : [https://github.com/Fedict/eid-mw/issues/118](https://github.com/Fedict/eid-mw/issues/118)\r\n\r\nDescribe what _did_ happen.\r\nNo slots can be found (regardless of whether they have a token or not).\r\n\r\n#### Steps for reproducing this issue:\r\n\r\nSimple python script here [https://github.com/linuxunderground/eid-mw-sdk-python](https://github.com/linuxunderground/eid-mw-sdk-python) \r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/71", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/71/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/71/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/71/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/71", "id": 595975647, "node_id": "MDU6SXNzdWU1OTU5NzU2NDc=", "number": 71, "title": "Failed building wheel for PyKCS11", "user": {"login": "vraj72", "id": 46528087, "node_id": "MDQ6VXNlcjQ2NTI4MDg3", "avatar_url": "https://avatars2.githubusercontent.com/u/46528087?v=4", "gravatar_id": "", "url": "https://api.github.com/users/vraj72", "html_url": "https://github.com/vraj72", "followers_url": "https://api.github.com/users/vraj72/followers", "following_url": "https://api.github.com/users/vraj72/following{/other_user}", "gists_url": "https://api.github.com/users/vraj72/gists{/gist_id}", "starred_url": "https://api.github.com/users/vraj72/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/vraj72/subscriptions", "organizations_url": "https://api.github.com/users/vraj72/orgs", "repos_url": "https://api.github.com/users/vraj72/repos", "events_url": "https://api.github.com/users/vraj72/events{/privacy}", "received_events_url": "https://api.github.com/users/vraj72/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-04-07T15:56:18Z", "updated_at": "2020-04-07T17:02:40Z", "closed_at": "2020-04-07T17:02:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: ubuntu\r\n* PyKCS11 version:\r\n* Python version: 3\r\n* PKCS#11 library used:\r\n\r\n#### Please describe your issue in as much detail as possible:\r\n pip3 install PyKCS11\r\nCollecting PyKCS11\r\n  Using cached https://files.pythonhosted.org/packages/92/53/6655729684fafc171b86a307e2650010c09a3266d96f5907151d75a16d9f/PyKCS11-1.5.7.tar.gz\r\nBuilding wheels for collected packages: PyKCS11\r\n  Running setup.py bdist_wheel for PyKCS11 ... error\r\n  Complete output from command /usr/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-qajg73ni/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/tmprzdt0imcpip-wheel- --python-tag cp36:\r\n  running bdist_wheel\r\n  running build\r\n  running build_ext\r\n  building 'PyKCS11._LowLevel' extension\r\n  swigging src/pykcs11.i to src/pykcs11_wrap.cpp\r\n  swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i\r\n  unable to execute 'swig': No such file or directory\r\n  error: command 'swig' failed with exit status 1\r\n  \r\n  ----------------------------------------\r\n  Failed building wheel for PyKCS11\r\n  Running setup.py clean for PyKCS11\r\nFailed to build PyKCS11\r\nInstalling collected packages: PyKCS11\r\n  Running setup.py install for PyKCS11 ... error\r\n    Complete output from command /usr/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-qajg73ni/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-u1uyi6aa-record/install-record.txt --single-version-externally-managed --compile:\r\n    running install\r\n    running build\r\n    running build_ext\r\n    building 'PyKCS11._LowLevel' extension\r\n    swigging src/pykcs11.i to src/pykcs11_wrap.cpp\r\n    swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i\r\n    unable to execute 'swig': No such file or directory\r\n    error: command 'swig' failed with exit status 1\r\n    \r\n    ----------------------------------------\r\nCommand \"/usr/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-qajg73ni/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-u1uyi6aa-record/install-record.txt --single-version-externally-managed --compile\" failed with error code 1 in /tmp/pip-build-qajg73ni/PyKCS11/\r\n\r\n\r\n\r\nDescribe what you _expected_ should happen.\r\n\r\nDescribe what _did_ happen.\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1.  pip3 install PyKCS11\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/70", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/70/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/70/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/70/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/70", "id": 588919128, "node_id": "MDU6SXNzdWU1ODg5MTkxMjg=", "number": 70, "title": "No module named _LowLevel and Failed to install PyKCS11 1.5 via tar.gz", "user": {"login": "snny000", "id": 19207556, "node_id": "MDQ6VXNlcjE5MjA3NTU2", "avatar_url": "https://avatars2.githubusercontent.com/u/19207556?v=4", "gravatar_id": "", "url": "https://api.github.com/users/snny000", "html_url": "https://github.com/snny000", "followers_url": "https://api.github.com/users/snny000/followers", "following_url": "https://api.github.com/users/snny000/following{/other_user}", "gists_url": "https://api.github.com/users/snny000/gists{/gist_id}", "starred_url": "https://api.github.com/users/snny000/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/snny000/subscriptions", "organizations_url": "https://api.github.com/users/snny000/orgs", "repos_url": "https://api.github.com/users/snny000/repos", "events_url": "https://api.github.com/users/snny000/events{/privacy}", "received_events_url": "https://api.github.com/users/snny000/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-03-27T06:33:04Z", "updated_at": "2020-03-30T01:10:40Z", "closed_at": "2020-03-30T01:10:40Z", "author_association": "NONE", "active_lock_reason": null, "body": "\r\n* Operating system used: Centos7.5\r\n* PyKCS11 version: 1.5.7\r\n* Python version: python2.7\r\n* PKCS#11 library used: PyKCS11-1.5.7.tar.gz\r\nFailed to install PyKCS11 1.5.7 via python setup.py install.\r\n\r\n Steps for reproducing this issue:\r\n\r\n1. download the PyKCS11 1.5.7 lib by https://files.pythonhosted.org/packages/92/53/6655729684fafc171b86a307e2650010c09a3266d96f5907151d75a16d9f/PyKCS11-1.5.7.tar.gz\r\n2.  tar -zxvf PyKCS11-1.5.7.tar.gz\r\n3. cd PyKCS11-1.5.7\r\n4. python setup.py install\r\n\r\nresult:\r\n\r\nfrom PyKCS11 import *\r\n\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"PyKCS11/__init__.py\", line 20, in <module>\r\n    import PyKCS11.LowLevel\r\n  File \"PyKCS11/LowLevel.py\", line 21, in <module>\r\n    _LowLevel = swig_import_helper()\r\n  File \"PyKCS11/LowLevel.py\", line 20, in swig_import_helper\r\n    return importlib.import_module('_LowLevel')\r\n  File \"/usr/lib64/python2.7/importlib/__init__.py\", line 37, in import_module\r\n    __import__(name)\r\nImportError: No module named _LowLevel\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/69", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/69/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/69/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/69/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/69", "id": 579073262, "node_id": "MDU6SXNzdWU1NzkwNzMyNjI=", "number": 69, "title": "Fail to load .so in both in MAC & Ubuntu", "user": {"login": "applezhp", "id": 62041962, "node_id": "MDQ6VXNlcjYyMDQxOTYy", "avatar_url": "https://avatars1.githubusercontent.com/u/62041962?v=4", "gravatar_id": "", "url": "https://api.github.com/users/applezhp", "html_url": "https://github.com/applezhp", "followers_url": "https://api.github.com/users/applezhp/followers", "following_url": "https://api.github.com/users/applezhp/following{/other_user}", "gists_url": "https://api.github.com/users/applezhp/gists{/gist_id}", "starred_url": "https://api.github.com/users/applezhp/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/applezhp/subscriptions", "organizations_url": "https://api.github.com/users/applezhp/orgs", "repos_url": "https://api.github.com/users/applezhp/repos", "events_url": "https://api.github.com/users/applezhp/events{/privacy}", "received_events_url": "https://api.github.com/users/applezhp/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-03-11T07:55:12Z", "updated_at": "2020-03-15T12:59:18Z", "closed_at": "2020-03-11T10:27:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: MAC Catalina 10.15.2  & Ubuntu 16.04\r\n* PyKCS11 version: 1.5.7\r\n* Python version: Ubuntu 3.5 , Mac 3.7.4\r\n* PKCS#11 library used:\r\n_LowLevel.cpython-35m-x86_64-linux-gnu.so\r\n_LowLevel.cpython-37m-darwin.so\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nsrc/dyn_unix.c:76:SYS_dyn_GetAddress() C_GetFunctionList: dlsym(0x7fe0fd4310c0, C_GetFunctionList): symbol not found\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyKCS11/__init__.py\", line 484, in load\r\n    raise PyKCS11Error(rv, pkcs11dll_filename)\r\nPyKCS11.PyKCS11Error: C_GetFunctionList() not found (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyKCS11/_LowLevel.cpython-37m-darwin.so)\r\n#### Steps for reproducing this issue:\r\n1.  pip install PyKCS11\r\n2. import PyKCS11\r\n3. pkcs11 =PyKCS11.PyKCS11Lib()\r\n4. pkcs11.load('xxx.so')", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/68", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/68/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/68/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/68/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/68", "id": 540462014, "node_id": "MDU6SXNzdWU1NDA0NjIwMTQ=", "number": 68, "title": "Question - pyopenssl, requests, and this module together!", "user": {"login": "danizen", "id": 4966193, "node_id": "MDQ6VXNlcjQ5NjYxOTM=", "avatar_url": "https://avatars2.githubusercontent.com/u/4966193?v=4", "gravatar_id": "", "url": "https://api.github.com/users/danizen", "html_url": "https://github.com/danizen", "followers_url": "https://api.github.com/users/danizen/followers", "following_url": "https://api.github.com/users/danizen/following{/other_user}", "gists_url": "https://api.github.com/users/danizen/gists{/gist_id}", "starred_url": "https://api.github.com/users/danizen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/danizen/subscriptions", "organizations_url": "https://api.github.com/users/danizen/orgs", "repos_url": "https://api.github.com/users/danizen/repos", "events_url": "https://api.github.com/users/danizen/events{/privacy}", "received_events_url": "https://api.github.com/users/danizen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-12-19T17:47:40Z", "updated_at": "2020-01-02T19:51:39Z", "closed_at": "2020-01-02T19:51:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### What Works?\r\n\r\nPyKCS11 worked admirably for me subject to me knowledge and limitations.  I am able to itemize the X509 certificates, private keys, etc. on my NIH provided smart card, and one colleague on OS X can do the same having carefully installed opensc.\r\n\r\nThanks for providing this module.\r\n\r\n#### Since it works, what Feature do I want?\r\n\r\nI need to authenticate against an internal NIH web application that is secured using TLS and wants me (my users actually) to use a client certifcate on the smart card.  I'm looking for some advise on creating a mash-up between Python requests (or requests-toolbelt), pyopenssl, and this module.  \r\n\r\nSince openssl itself is sometimes compiled without PKCS11 support, it isn't clear this is even feasible using just Python.  I am filing this bug to peel the onion.\r\n\r\n#### Your system information\r\n\r\n* Operating system used: Windows 10\r\n* PyKCS11 version: 1.5.5\r\n* Python version: CPython 3.6.8\r\n* PKCS#11 library used: C:\\Program Files\\HID Global\\ActivClient\\acpkcs211.dll\r\n\r\nA friend using OS X Mojave is using opensc provided library in /Library/Frameworks/ac.ac4mac.pkcs11.framework/Versions/Current/Libraries/apkcs220.dylib\r\n\r\n__Describe what you _expected_ should happen__:\r\nI'm not looking for miracles here - I open issues on github because maybe there's a project somewhere that already does what I need to do, and I haven't found it yet.\r\n\r\n__Describe what _did_ happen__:\r\n\r\nDeveloper wonders in the shadow of the valley of night, trying pywin32, ctypes, anything to access the certificate on his smart card.  Developer ultimately succeeds in finding and using this module, only to realize he has to *implement* SSL based on a low-level library to find a solution.  Developer knows that this will ultimately lead to failure unless he can not only implement a solution of find the correct open source framework to which to contribute it.\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. Howl in darkness for a year\r\n2. Install and use PKCS#11 correctly\r\n3. Realize that the smart card's private key is still privately on the smart card, and so you won't get it done just by supplying certificate and keypair path to Python requests.\r\n4. Realize that even requests-toolbelt's class X509Adapter still requires access to the bytes of the request.\r\n5. Ask for help from experts in cryptography.\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/67", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/67/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/67/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/67/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/67", "id": 540232470, "node_id": "MDU6SXNzdWU1NDAyMzI0NzA=", "number": 67, "title": "Source of 1.5.5 is missing", "user": {"login": "ckoehn", "id": 532103, "node_id": "MDQ6VXNlcjUzMjEwMw==", "avatar_url": "https://avatars3.githubusercontent.com/u/532103?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ckoehn", "html_url": "https://github.com/ckoehn", "followers_url": "https://api.github.com/users/ckoehn/followers", "following_url": "https://api.github.com/users/ckoehn/following{/other_user}", "gists_url": "https://api.github.com/users/ckoehn/gists{/gist_id}", "starred_url": "https://api.github.com/users/ckoehn/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ckoehn/subscriptions", "organizations_url": "https://api.github.com/users/ckoehn/orgs", "repos_url": "https://api.github.com/users/ckoehn/repos", "events_url": "https://api.github.com/users/ckoehn/events{/privacy}", "received_events_url": "https://api.github.com/users/ckoehn/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-12-19T10:45:15Z", "updated_at": "2019-12-19T13:15:26Z", "closed_at": "2019-12-19T13:15:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "See https://pypi.org/project/PyKCS11/1.5.5/#files. \r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/66", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/66/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/66/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/66/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/66", "id": 539770481, "node_id": "MDU6SXNzdWU1Mzk3NzA0ODE=", "number": 66, "title": "Building 1.5.6 fail ", "user": {"login": "hc7", "id": 3115201, "node_id": "MDQ6VXNlcjMxMTUyMDE=", "avatar_url": "https://avatars2.githubusercontent.com/u/3115201?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hc7", "html_url": "https://github.com/hc7", "followers_url": "https://api.github.com/users/hc7/followers", "following_url": "https://api.github.com/users/hc7/following{/other_user}", "gists_url": "https://api.github.com/users/hc7/gists{/gist_id}", "starred_url": "https://api.github.com/users/hc7/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hc7/subscriptions", "organizations_url": "https://api.github.com/users/hc7/orgs", "repos_url": "https://api.github.com/users/hc7/repos", "events_url": "https://api.github.com/users/hc7/events{/privacy}", "received_events_url": "https://api.github.com/users/hc7/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-12-18T15:59:16Z", "updated_at": "2019-12-19T10:28:56Z", "closed_at": "2019-12-18T16:51:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: windows server 2016\r\n* PyKCS11 version: 1.5.6\r\n* Python version: 3.8\r\n* PKCS#11 library used:\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen.\r\n\r\nResource compiler **should** find resource.h also. \r\n\r\nDescribe what _did_ happen.\r\n\r\n  pykcs11.rc(3) : fatal error RC1015: cannot open include file 'resource.h'.\r\n  error: command 'C:\\\\Program Files (x86)\\\\Windows Kits\\\\10\\\\bin\\\\10.0.18362.0\\\\x86\\\\rc.exe' failed with exit status 1\r\nerror\r\n  ERROR: Failed building wheel for PyKCS11\r\n\r\n![image](https://user-images.githubusercontent.com/3115201/71101839-6e8afe00-21c8-11ea-9d98-03cafdb18e73.png)\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. pip wheel -v --wheel-dir=D:\\work --no-binary :all: PyKCS11\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/65", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/65/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/65/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/65/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/65", "id": 539611379, "node_id": "MDU6SXNzdWU1Mzk2MTEzNzk=", "number": 65, "title": "does not build since 1.5.4", "user": {"login": "hc7", "id": 3115201, "node_id": "MDQ6VXNlcjMxMTUyMDE=", "avatar_url": "https://avatars2.githubusercontent.com/u/3115201?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hc7", "html_url": "https://github.com/hc7", "followers_url": "https://api.github.com/users/hc7/followers", "following_url": "https://api.github.com/users/hc7/following{/other_user}", "gists_url": "https://api.github.com/users/hc7/gists{/gist_id}", "starred_url": "https://api.github.com/users/hc7/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hc7/subscriptions", "organizations_url": "https://api.github.com/users/hc7/orgs", "repos_url": "https://api.github.com/users/hc7/repos", "events_url": "https://api.github.com/users/hc7/events{/privacy}", "received_events_url": "https://api.github.com/users/hc7/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-12-18T11:04:28Z", "updated_at": "2019-12-18T13:59:42Z", "closed_at": "2019-12-18T13:59:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: windows server 2016\r\n* PyKCS11 version: 1.5.5\r\n* Python version: 3.8\r\n* PKCS#11 library used:\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen.\r\n\r\n  C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x86\\rc.exe -Isrc -Ic:\\python38\\include -Ic:\\python38\\include \"-IC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\include\" \"-IC:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /fobuild\\temp.win-amd64-3.8\\Release\\pykcs11.res pykcs11.rc\r\n\r\nCompile without errors.\r\n\r\nDescribe what _did_ happen.\r\n\r\n    C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x86\\rc.exe -Isrc -Ic:\\python38\\include -Ic:\\python38\\include \"-IC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\include\" \"-IC:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /fobuild\\temp.win-amd64-3.8\\Release\\pykcs11.res pykcs11.rc\r\n    Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384\r\n    Copyright (C) Microsoft Corporation.  All rights reserved.\r\n\r\n    fatal error RC1110: could not open pykcs11.rc\r\n    error: command 'C:\\\\Program Files (x86)\\\\Windows Kits\\\\10\\\\bin\\\\10.0.18362.0\\\\x86\\\\rc.exe' failed with exit status 1\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. pip install -v pykcs11==1.5.5\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/64", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/64/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/64/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/64/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/64", "id": 503878159, "node_id": "MDU6SXNzdWU1MDM4NzgxNTk=", "number": 64, "title": "Getting poor performance for bulk tokenization", "user": {"login": "mxmujeeb2", "id": 56182285, "node_id": "MDQ6VXNlcjU2MTgyMjg1", "avatar_url": "https://avatars0.githubusercontent.com/u/56182285?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mxmujeeb2", "html_url": "https://github.com/mxmujeeb2", "followers_url": "https://api.github.com/users/mxmujeeb2/followers", "following_url": "https://api.github.com/users/mxmujeeb2/following{/other_user}", "gists_url": "https://api.github.com/users/mxmujeeb2/gists{/gist_id}", "starred_url": "https://api.github.com/users/mxmujeeb2/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mxmujeeb2/subscriptions", "organizations_url": "https://api.github.com/users/mxmujeeb2/orgs", "repos_url": "https://api.github.com/users/mxmujeeb2/repos", "events_url": "https://api.github.com/users/mxmujeeb2/events{/privacy}", "received_events_url": "https://api.github.com/users/mxmujeeb2/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-10-08T07:34:00Z", "updated_at": "2019-10-08T12:01:00Z", "closed_at": "2019-10-08T12:01:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n# * Operating system used: Windows 10 64bit\r\n# * PyKCS11 version: 1.5.5\r\n# * Python version: 3.6\r\n# * PKCS#11 library used: nCipher\\nfast\\toolkits\\pkcs11\\cknfast-64.dll\r\n\r\n# I have a situation where there are files of 7 - 8 million rows with 200 column csv delimited with \"%@$\" . I have to ONLY tokenize the 2nd column  which has a 20digit number for all the 7 - 8 million rows. I am using below code but I am getting very poor performance for tokenization. The tokenization rate is: -\r\n# SOFTHSM: 3500(tokens/s)   \r\n# NCipherHSM : 1500(tokens/s)  \r\n\r\n# I dont know if i am implementing the pykcs11 library in a wrong way or if there is a better way to bulk push data (array or list etc)  to tokenize quickly because the NCIPHER device i am connected has the capability of tokenizing almost 12000 - 14000 tokens/s and i am not able to get the intended performance. Atleast If i do a local AES 128 bit tokenization using pycryptodome library I am getting almost 12000 - 13000 tokens/s rate. Please advise : \r\n\r\n```\r\nfrom PyKCS11 import *\r\nimport os\r\nfrom ctypes import *\r\nimport binascii\r\nfrom Cryptodome.Util.Padding import pad, unpad\r\nfrom base64 import b64decode\r\nfrom base64 import b64encode\r\nfrom Cryptodome.Cipher import AES\r\n\r\nmode = PyKCS11.CKM_AES_CBC\r\niv = b'This is an IV456'\r\nkeyLabel = \"TestAESKey1\"\r\nmechanism = PyKCS11.Mechanism(mode, iv)\r\nkey = session.findObjects(\r\n    [(PyKCS11.CKA_CLASS, PyKCS11.CKO_SECRET_KEY), (PyKCS11.CKA_LABEL, keyLabel)]\r\n)[0]\r\n\r\ndef TokenizeNCipher( key, mode, iv, message):\r\n\tpadedEncoded = pad(message.encode('utf8'), AES.block_size)  # i need to do padding if the input MSG is not 16 OR 32 bit\r\n\tciphertext = session.encrypt(key, padedEncoded, mechanism)\r\n\tTMessage = b64encode(bytes(tuple(ciphertext))).decode(\"utf-8\")  # the tokenized value should be alphanumeric not too long string to store\r\n\treturn TMessage\r\n\r\n\r\n\r\nwith open(OriginalFileName, 'r') as Originalfile:\r\n\twith open(TokenizedFileName, 'w') as TokenizedFile:\r\n\t\tfor line in Originalfile:\r\n\t\t\tarray1 = line.split(\"%@$\")    # this is a delimited file with 200 columns\r\n\t\t\tarray1[1]=TokenizeNCipher(key, mode, iv, array1[1].strip())   # only 1st column needs to get tokenized\r\n\t\t\tnewLine ='%@$'.join(array1)\r\n\t\t\tTokenizedFile.write(newLine)\t\t# i only updated the 1st column with the tokenized value\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/63", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/63/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/63/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/63/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/63", "id": 502909033, "node_id": "MDU6SXNzdWU1MDI5MDkwMzM=", "number": 63, "title": "LoadLibrary() failed with error 126: The specified module could not be found", "user": {"login": "mxmujeeb2", "id": 56182285, "node_id": "MDQ6VXNlcjU2MTgyMjg1", "avatar_url": "https://avatars0.githubusercontent.com/u/56182285?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mxmujeeb2", "html_url": "https://github.com/mxmujeeb2", "followers_url": "https://api.github.com/users/mxmujeeb2/followers", "following_url": "https://api.github.com/users/mxmujeeb2/following{/other_user}", "gists_url": "https://api.github.com/users/mxmujeeb2/gists{/gist_id}", "starred_url": "https://api.github.com/users/mxmujeeb2/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mxmujeeb2/subscriptions", "organizations_url": "https://api.github.com/users/mxmujeeb2/orgs", "repos_url": "https://api.github.com/users/mxmujeeb2/repos", "events_url": "https://api.github.com/users/mxmujeeb2/events{/privacy}", "received_events_url": "https://api.github.com/users/mxmujeeb2/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2019-10-05T03:19:35Z", "updated_at": "2019-10-06T14:48:24Z", "closed_at": "2019-10-06T13:38:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: Windows\r\n* PyKCS11 version: latest\r\n* Python version:  3.6\r\n* PKCS#11 library used: cknfast\r\n\r\ni have loaded the cknfast64 bit library in the environment variable. Then i wrote just 2 lines of code as below\r\n\r\npkcs11 = PyKCS11Lib()\r\npkcs11.load()\r\n\r\nit gave me the error:\r\n\r\nLTraceback (most recent call last):\r\n  File \"E:\\DATA-WIDE\\DATAWIDE SOLUTION\\python\\pkcs.py\", line 10, in <module>\r\noadLibrary() failed with error 126: The specified module could not be found.\r\n\r\n    pkcs11.load()\r\n  File \"C:\\Users\\md\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\PyKCS11\\__init__.py\", line 483, in load\r\n    raise PyKCS11Error(-1, pkcs11dll_filename)\r\nPyKCS11.PyKCS11Error: Load (\"C:\\Program Files (x86)\\nCipher\\nfast\\toolkits\\pkcs11\\cknfast-64.dll\")\r\n[Finished in 0.2s with exit code 1]\r\n[shell_cmd: python -u \"E:\\DATA-WIDE\\DATAWIDE SOLUTION\\python\\pkcs.py\"]\r\n[dir: E:\\DATA-WIDE\\DATAWIDE SOLUTION\\python]\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/62", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/62/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/62/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/62/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/62", "id": 475968059, "node_id": "MDU6SXNzdWU0NzU5NjgwNTk=", "number": 62, "title": "Fail to install by sudo pip install PyKCS11==1.5.5", "user": {"login": "sepulm01", "id": 33760447, "node_id": "MDQ6VXNlcjMzNzYwNDQ3", "avatar_url": "https://avatars3.githubusercontent.com/u/33760447?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sepulm01", "html_url": "https://github.com/sepulm01", "followers_url": "https://api.github.com/users/sepulm01/followers", "following_url": "https://api.github.com/users/sepulm01/following{/other_user}", "gists_url": "https://api.github.com/users/sepulm01/gists{/gist_id}", "starred_url": "https://api.github.com/users/sepulm01/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sepulm01/subscriptions", "organizations_url": "https://api.github.com/users/sepulm01/orgs", "repos_url": "https://api.github.com/users/sepulm01/repos", "events_url": "https://api.github.com/users/sepulm01/events{/privacy}", "received_events_url": "https://api.github.com/users/sepulm01/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-08-02T02:33:22Z", "updated_at": "2019-08-02T15:22:15Z", "closed_at": "2019-08-02T15:12:33Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: Ubuntu 18.04.2 LTS\r\n* PyKCS11 version: 1.5.5\r\n* Python version: 3.6.8\r\n* PKCS#11 library used: ?\r\n\r\n#### Please describe your issue in as much detail as possible:\r\n I try to use :\r\nsudo pip3 install PyKCS11==1.5.5. I've install in my personal computer , but when to replicate the installation on Google VM I couldn't.\r\nbest regards.\r\n\r\nDescribe what you _expected_ should happen.\r\n\r\nDescribe what _did_ happen.\r\n\r\nCollecting PyKCS11==1.5.5\r\n  Downloading https://files.pythonhosted.org/packages/f6/a0/2800ff56c0b3856d1af410f8494836672339d7566d975a62bf81a4ad5716/PyKCS11-1.5.5.tar.gz (72kB)\r\n     |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 81kB 3.6MB/s \r\nBuilding wheels for collected packages: PyKCS11\r\n  Building wheel for PyKCS11 (setup.py) ... error\r\n  ERROR: Command errored out with exit status 1:\r\n   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /tmp/pip-wheel-exjwa9at --python-tag cp36\r\n       cwd: /tmp/pip-install-5cd9rxsk/PyKCS11/\r\n  Complete output (8 lines):\r\n  running bdist_wheel\r\n  running build\r\n  running build_ext\r\n  building 'PyKCS11._LowLevel' extension\r\n  swigging src/pykcs11.i to src/pykcs11_wrap.cpp\r\n  swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i\r\n  unable to execute 'swig': No such file or directory\r\n  error: command 'swig' failed with exit status 1\r\n  ----------------------------------------\r\n  ERROR: Failed building wheel for PyKCS11\r\n  Running setup.py clean for PyKCS11\r\nFailed to build PyKCS11\r\nInstalling collected packages: PyKCS11\r\n  Running setup.py install for PyKCS11 ... error\r\n    ERROR: Command errored out with exit status 1:\r\n     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-awbz8nrq/install-record.txt --single-version-externally-managed --compile\r\n         cwd: /tmp/pip-install-5cd9rxsk/PyKCS11/\r\n    Complete output (8 lines):\r\n    running install\r\n    running build\r\n    running build_ext\r\n    building 'PyKCS11._LowLevel' extension\r\n    swigging src/pykcs11.i to src/pykcs11_wrap.cpp\r\n    swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i\r\n    unable to execute 'swig': No such file or directory\r\n    error: command 'swig' failed with exit status 1\r\n    ----------------------------------------\r\nERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-5cd9rxsk/PyKCS11/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-awbz8nrq/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.\r\n\r\n\r\n\r\n\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. sudo pip3 install PyKCS11==1.5.5\r\n2. \r\n3. \r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/61", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/61/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/61/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/61/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/61", "id": 468062061, "node_id": "MDU6SXNzdWU0NjgwNjIwNjE=", "number": 61, "title": "CKR_USER_NOT_LOGGED_IN - Inspite of correct PIN", "user": {"login": "supreetd21", "id": 20113408, "node_id": "MDQ6VXNlcjIwMTEzNDA4", "avatar_url": "https://avatars3.githubusercontent.com/u/20113408?v=4", "gravatar_id": "", "url": "https://api.github.com/users/supreetd21", "html_url": "https://github.com/supreetd21", "followers_url": "https://api.github.com/users/supreetd21/followers", "following_url": "https://api.github.com/users/supreetd21/following{/other_user}", "gists_url": "https://api.github.com/users/supreetd21/gists{/gist_id}", "starred_url": "https://api.github.com/users/supreetd21/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/supreetd21/subscriptions", "organizations_url": "https://api.github.com/users/supreetd21/orgs", "repos_url": "https://api.github.com/users/supreetd21/repos", "events_url": "https://api.github.com/users/supreetd21/events{/privacy}", "received_events_url": "https://api.github.com/users/supreetd21/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 5, "created_at": "2019-07-15T10:54:10Z", "updated_at": "2019-08-28T19:32:17Z", "closed_at": "2019-08-28T19:32:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used:\r\nMacOS Mojave 10.14.4\r\n\r\n* PyKCS11 version:\r\n1.5.5\r\n\r\n* Python version:\r\nPython 2.7.10\r\n\r\n* PKCS#11 library used:\r\n/Library/OpenSC/lib/opensc-pkcs11.so\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen.\r\n\r\nI am trying to sign my CSR using a YubiKey 5.\r\nOn executing samples/getinfo.py. I get the following result.\r\n```\r\ncryptokiVersion: 2.20\r\nflags:\r\nlibraryDescription: OpenSC smartcard framework\r\nlibraryVersion: 0.19\r\nmanufacturerID: OpenSC Project\r\nAvailable Slots: 1 [0]\r\n\r\nSlot 1/1 (number 0):\r\n firmwareVersion: 0.00\r\n flags: CKF_TOKEN_PRESENT, CKF_REMOVABLE_DEVICE, CKF_HW_SLOT\r\n hardwareVersion: 5.18\r\n manufacturerID: Yubico\r\n slotDescription: Yubico Yubikey 4 OTP+U2F+CCID\r\n SessionInfo\r\n  flags: CKF_SERIAL_SESSION\r\n  slotID: 0\r\n  state: CKS_RO_PUBLIC_SESSION\r\n  ulDeviceError: 0\r\n TokenInfo\r\n  firmwareVersion: 0.0\r\n  flags: CKF_RNG, CKF_LOGIN_REQUIRED, CKF_TOKEN_INITIALIZED, CKF_USER_PIN_INITIALIZED\r\n  hardwareVersion: 0.0\r\n  label: supreetdeshpande\r\n  manufacturerID: piv_II\r\n  model: PKCS#15 emulated\r\n  serialNumber: 9bf84dc101dab7f7\r\n  ulFreePrivateMemory: -1\r\n  ulFreePublicMemory: -1\r\n  ulMaxPinLen: 8\r\n  ulMaxRwSessionCount: 0\r\n  ulMaxSessionCount: 0\r\n  ulMinPinLen: 4\r\n  ulRwSessionCount: 0\r\n  ulSessionCount: 0\r\n  ulTotalPrivateMemory: -1\r\n  ulTotalPublicMemory: -1\r\n  utcTime:\r\n```\r\n\r\n#### Steps for reproducing this issue:\r\nOn executing signature.py (I have added my Private Key into the PIV slot for the Yubikey through their GUI tool)\r\nI get the following error:\r\n`Traceback (most recent call last):\r\n  File \"signature.py\", line 40, in <module>\r\n    signature = session.sign(privKey, binascii.unhexlify(toSign), mechanism)\r\n  File \"/Library/Python/2.7/site-packages/PyKCS11/__init__.py\", line 1086, in sign\r\n    raise PyKCS11Error(rv)\r\nPyKCS11.PyKCS11Error: CKR_USER_NOT_LOGGED_IN (0x00000101)`\r\n\r\nCKR_USER_NOT_LOGGED_IN -I have given the correct PIN as the samples/getinfo.py worked well.\r\nCould you help me with the usual reason for such an error?\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/60", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/60/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/60/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/60/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/60", "id": 457957326, "node_id": "MDU6SXNzdWU0NTc5NTczMjY=", "number": 60, "title": "Manufacturer not displayed correctly for Rainbow Token", "user": {"login": "hdan1", "id": 5407241, "node_id": "MDQ6VXNlcjU0MDcyNDE=", "avatar_url": "https://avatars1.githubusercontent.com/u/5407241?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hdan1", "html_url": "https://github.com/hdan1", "followers_url": "https://api.github.com/users/hdan1/followers", "following_url": "https://api.github.com/users/hdan1/following{/other_user}", "gists_url": "https://api.github.com/users/hdan1/gists{/gist_id}", "starred_url": "https://api.github.com/users/hdan1/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hdan1/subscriptions", "organizations_url": "https://api.github.com/users/hdan1/orgs", "repos_url": "https://api.github.com/users/hdan1/repos", "events_url": "https://api.github.com/users/hdan1/events{/privacy}", "received_events_url": "https://api.github.com/users/hdan1/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 537984180, "node_id": "MDU6TGFiZWw1Mzc5ODQxODA=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/invalid", "name": "invalid", "color": "e6e6e6", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 5, "created_at": "2019-06-19T11:26:58Z", "updated_at": "2019-06-20T13:27:42Z", "closed_at": "2019-06-20T13:27:28Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used:  Windows 10 PRO x64\r\n* PyKCS11 version: 1.5.5\r\n* Python version: 3.6\r\n* PKCS#11 library used: eTPKCS11.dll (Cryptoki 2.20, SafeNet eToken 10.0)\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nI am trying to access information on a Rainbow Tech token, model 330.\r\nWhen I use OpenSC tools for windows, for the manufacturer field I get \"\u00a9Rainbow Tech.\", when I use the library to get the manufacturer I only get \"Rainbow Tech.\", so there is a character missing. I have tried both all the samples, the result is the same.\r\n\r\nAny ideas why it skips the first character ?\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/59", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/59/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/59/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/59/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/59", "id": 455732472, "node_id": "MDU6SXNzdWU0NTU3MzI0NzI=", "number": 59, "title": "ModuleNotFoundError: No module named 'PyKCS11._LowLevel' (resolved, just go out of the directory)", "user": {"login": "Neywiny", "id": 12035198, "node_id": "MDQ6VXNlcjEyMDM1MTk4", "avatar_url": "https://avatars2.githubusercontent.com/u/12035198?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Neywiny", "html_url": "https://github.com/Neywiny", "followers_url": "https://api.github.com/users/Neywiny/followers", "following_url": "https://api.github.com/users/Neywiny/following{/other_user}", "gists_url": "https://api.github.com/users/Neywiny/gists{/gist_id}", "starred_url": "https://api.github.com/users/Neywiny/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Neywiny/subscriptions", "organizations_url": "https://api.github.com/users/Neywiny/orgs", "repos_url": "https://api.github.com/users/Neywiny/repos", "events_url": "https://api.github.com/users/Neywiny/events{/privacy}", "received_events_url": "https://api.github.com/users/Neywiny/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2019-06-13T13:09:35Z", "updated_at": "2019-06-13T13:24:26Z", "closed_at": "2019-06-13T13:23:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: Ubuntu 18.04\r\n* PyKCS11 version: whatever is most recent at this time\r\n* Python version: 3.6 and 2.7.15\r\n* PKCS#11 library used: most recent at this time\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nIn trying to import the module after building and installing (with sudo) I get\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/dylan/Documents/smartcard/PyKCS11/PyKCS11/LowLevel.py\", line 14, in swig_import_helper\r\n    return importlib.import_module(mname)\r\n  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\r\nModuleNotFoundError: No module named 'PyKCS11._LowLevel'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"/home/user/Documents/smartcard/PyKCS11/PyKCS11/__init__.py\", line 20, in <module>\r\n    import PyKCS11.LowLevel\r\n  File \"/home/user/Documents/smartcard/PyKCS11/PyKCS11/LowLevel.py\", line 17, in <module>\r\n    _LowLevel = swig_import_helper()\r\n  File \"/home/user/Documents/smartcard/PyKCS11/PyKCS11/LowLevel.py\", line 16, in swig_import_helper\r\n    return importlib.import_module('_LowLevel')\r\n  File \"/usr/lib/python3.6/importlib/__init__.py\", line 126, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\nModuleNotFoundError: No module named '_LowLevel'\r\n```\r\n\r\nI saw [this post](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741329) but the guy fixed it without saying how. Same error exists with 3.6 and 2.7.15. I've tried 'make rebuild' and build/install again, same thing.\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. clone repo\r\n2. install repo\r\n3. import module\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/58", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/58/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/58/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/58/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/58", "id": 446943652, "node_id": "MDU6SXNzdWU0NDY5NDM2NTI=", "number": 58, "title": "softhsm 2.5 support", "user": {"login": "jasperpppp", "id": 8730535, "node_id": "MDQ6VXNlcjg3MzA1MzU=", "avatar_url": "https://avatars3.githubusercontent.com/u/8730535?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jasperpppp", "html_url": "https://github.com/jasperpppp", "followers_url": "https://api.github.com/users/jasperpppp/followers", "following_url": "https://api.github.com/users/jasperpppp/following{/other_user}", "gists_url": "https://api.github.com/users/jasperpppp/gists{/gist_id}", "starred_url": "https://api.github.com/users/jasperpppp/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jasperpppp/subscriptions", "organizations_url": "https://api.github.com/users/jasperpppp/orgs", "repos_url": "https://api.github.com/users/jasperpppp/repos", "events_url": "https://api.github.com/users/jasperpppp/events{/privacy}", "received_events_url": "https://api.github.com/users/jasperpppp/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-05-22T05:48:30Z", "updated_at": "2019-05-22T23:29:50Z", "closed_at": "2019-05-22T23:29:50Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used:\r\n* PyKCS11 version: 1.5.3\r\n* Python version: 3.7\r\n* PKCS#11 library used:\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen.\r\nAll unit tests pass\r\n\r\nDescribe what _did_ happen.\r\nUnit test test_getMechanismList failing using softhsm-2.5.0.\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. Run tests\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/57", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/57/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/57/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/57/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/57", "id": 444030676, "node_id": "MDU6SXNzdWU0NDQwMzA2NzY=", "number": 57, "title": "Library loading fails with Python 3.6 + Django 2.2.1", "user": {"login": "xzr", "id": 2156119, "node_id": "MDQ6VXNlcjIxNTYxMTk=", "avatar_url": "https://avatars0.githubusercontent.com/u/2156119?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xzr", "html_url": "https://github.com/xzr", "followers_url": "https://api.github.com/users/xzr/followers", "following_url": "https://api.github.com/users/xzr/following{/other_user}", "gists_url": "https://api.github.com/users/xzr/gists{/gist_id}", "starred_url": "https://api.github.com/users/xzr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xzr/subscriptions", "organizations_url": "https://api.github.com/users/xzr/orgs", "repos_url": "https://api.github.com/users/xzr/repos", "events_url": "https://api.github.com/users/xzr/events{/privacy}", "received_events_url": "https://api.github.com/users/xzr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 8, "created_at": "2019-05-14T17:13:42Z", "updated_at": "2019-05-15T13:50:24Z", "closed_at": "2019-05-15T13:13:16Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: Ubuntu 18.04 x64\r\n* PyKCS11 version: 1.5.3\r\n* Python version: 3.6.7\r\n* PKCS#11 library used: /usr/lib/softhsm/libsofthsm2.so\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen.\r\nLibrary loads\r\n\r\nDescribe what _did_ happen.\r\nLibrary fails to load with:\r\n\r\n  File \"/home/xzr/code/app/venv/lib/python3.6/site-packages/PyKCS11/__init__.py\", line 483, in load\r\n    raise PyKCS11Error(-1, pkcs11dll_filename)\r\n\r\nThis might be a PEBCAK issue, but so far I haven't been able to figure out what's wrong. I did play around with different input types for the library path string (and finally landed on lib_path.encode('ascii', 'ignore').decode('ascii') which in my opinion should produce the right kind of input for the underlying lowlevel library.\r\n\r\nNot expecting a straight answer or anything. Mostly welcoming any ideas for debug. The error from the lowlevel parts is not particularly helpful.\r\n\r\nThe library loading seems to work fine if I cut django out of the equation.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/56", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/56/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/56/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/56/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/56", "id": 440187411, "node_id": "MDU6SXNzdWU0NDAxODc0MTE=", "number": 56, "title": "Segmentation fault with eToken (CKA_WRAP_TEMPLATE makes SAC to crash)", "user": {"login": "rhoerbe", "id": 4348479, "node_id": "MDQ6VXNlcjQzNDg0Nzk=", "avatar_url": "https://avatars1.githubusercontent.com/u/4348479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rhoerbe", "html_url": "https://github.com/rhoerbe", "followers_url": "https://api.github.com/users/rhoerbe/followers", "following_url": "https://api.github.com/users/rhoerbe/following{/other_user}", "gists_url": "https://api.github.com/users/rhoerbe/gists{/gist_id}", "starred_url": "https://api.github.com/users/rhoerbe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rhoerbe/subscriptions", "organizations_url": "https://api.github.com/users/rhoerbe/orgs", "repos_url": "https://api.github.com/users/rhoerbe/repos", "events_url": "https://api.github.com/users/rhoerbe/events{/privacy}", "received_events_url": "https://api.github.com/users/rhoerbe/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 537984180, "node_id": "MDU6TGFiZWw1Mzc5ODQxODA=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/invalid", "name": "invalid", "color": "e6e6e6", "default": true, "description": null}, {"id": 537984182, "node_id": "MDU6TGFiZWw1Mzc5ODQxODI=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/wontfix", "name": "wontfix", "color": "ffffff", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 17, "created_at": "2019-05-03T19:25:32Z", "updated_at": "2019-08-26T08:15:21Z", "closed_at": "2019-07-29T21:40:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: Centos 7.6.1810 in docker Image; Docker Host same OS version\r\n* PyKCS11 version: 1.5.5\r\n* Python version: 2.7.5 (same result with 3.6)\r\n* PKCS#11 library used: libeToken.so.9.1.7 (Safenet eToken 5110)\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nAction: The calling program needs to sign some XML It load the library, but fails with SIGSEGV after connecting to the token.\r\nThe same calling program succeeds when using a Nitrokey HSM with _opensc-pkcs11.so._\r\n\r\nI think that pykcs11 should raise an exception instead of crashing, but I am not sure if the culprit is actually the libeToken.\r\n[valgrind.log](https://github.com/LudovicRousseau/PyKCS11/files/3143313/valgrind.log)\r\n\r\n#### Steps for reproducing this issue:\r\n\r\nThe source repo is https://github.com/identinetics/pyff branch mdsplit. A docker image is available on request. But the anaysis of the attached valgrind log might provide a first hint; however I am not skilled in analyzing C-extensions.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/54", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/54/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/54/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/54/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/54", "id": 423628982, "node_id": "MDU6SXNzdWU0MjM2Mjg5ODI=", "number": 54, "title": "HMAC general error", "user": {"login": "MasterMeng", "id": 18085008, "node_id": "MDQ6VXNlcjE4MDg1MDA4", "avatar_url": "https://avatars3.githubusercontent.com/u/18085008?v=4", "gravatar_id": "", "url": "https://api.github.com/users/MasterMeng", "html_url": "https://github.com/MasterMeng", "followers_url": "https://api.github.com/users/MasterMeng/followers", "following_url": "https://api.github.com/users/MasterMeng/following{/other_user}", "gists_url": "https://api.github.com/users/MasterMeng/gists{/gist_id}", "starred_url": "https://api.github.com/users/MasterMeng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/MasterMeng/subscriptions", "organizations_url": "https://api.github.com/users/MasterMeng/orgs", "repos_url": "https://api.github.com/users/MasterMeng/repos", "events_url": "https://api.github.com/users/MasterMeng/events{/privacy}", "received_events_url": "https://api.github.com/users/MasterMeng/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-03-21T09:10:10Z", "updated_at": "2019-03-21T11:17:42Z", "closed_at": "2019-03-21T11:17:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "* Operating system used: ubuntu 18.04\r\n* PyKCS11 version: 1.5.3\r\n* Python version: python3.7.2\r\n* PKCS#11 library used: opencryptoki 3.11 --- soft token\r\n\r\nIn my project,I need to use hmac to sign some thing.So I use PyKCS11 to general a hmac key,like this:\r\nhmacTem = [\r\n    (CKA_CLASS, CKO_SECRET_KEY),\r\n    (CKA_KEY_TYPE, CKK_AES),\r\n    (CKA_TOKEN, CK_TRUE),\r\n    (CKA_PRIVATE, CK_FALSE),\r\n    (CKA_SIGN, CK_FALSE),\r\n    (CKA_VERIFY, CK_FALSE),\r\n    (CKA_VALUE_LEN, 32),\r\n    (CKA_LABEL, \"TestAESKey\"),\r\n]\r\n\r\nhmac = session.generateKey(hmacTem, Mechanism(CKM_SHA256_HMAC, None))\r\n\r\nThen I got this error:PyKCS11.PyKCS11Error: CKR_MECHANISM_INVALID (0x00000070)\r\n\r\nCan I tell me where I`m wrong?\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/53", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/53/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/53/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/53/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/53", "id": 422109306, "node_id": "MDU6SXNzdWU0MjIxMDkzMDY=", "number": 53, "title": "CKR_MECHANISM_INVALID when use wrapKey", "user": {"login": "MasterMeng", "id": 18085008, "node_id": "MDQ6VXNlcjE4MDg1MDA4", "avatar_url": "https://avatars3.githubusercontent.com/u/18085008?v=4", "gravatar_id": "", "url": "https://api.github.com/users/MasterMeng", "html_url": "https://github.com/MasterMeng", "followers_url": "https://api.github.com/users/MasterMeng/followers", "following_url": "https://api.github.com/users/MasterMeng/following{/other_user}", "gists_url": "https://api.github.com/users/MasterMeng/gists{/gist_id}", "starred_url": "https://api.github.com/users/MasterMeng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/MasterMeng/subscriptions", "organizations_url": "https://api.github.com/users/MasterMeng/orgs", "repos_url": "https://api.github.com/users/MasterMeng/repos", "events_url": "https://api.github.com/users/MasterMeng/events{/privacy}", "received_events_url": "https://api.github.com/users/MasterMeng/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-03-18T09:16:43Z", "updated_at": "2019-03-18T11:43:53Z", "closed_at": "2019-03-18T11:43:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "* Operating system used: Ubuntu18.04\r\n* PyKCS11 version: 1.5.3\r\n* Python version: 3.7.2\r\nWhen I used the func:wrapKey to wrap a key with CKM_DES3_CBC_PAD, I got the error: CKR_MECHANISM_INVALID\r\nI also used CKM_DES3_ECB CKM_AES_CBC, they returned the same error: CKR_MECHANISM_INVALID", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/52", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/52/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/52/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/52/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/52", "id": 420551776, "node_id": "MDU6SXNzdWU0MjA1NTE3NzY=", "number": 52, "title": "Not able to initialize Yubikey token", "user": {"login": "kalyank23", "id": 34736945, "node_id": "MDQ6VXNlcjM0NzM2OTQ1", "avatar_url": "https://avatars0.githubusercontent.com/u/34736945?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kalyank23", "html_url": "https://github.com/kalyank23", "followers_url": "https://api.github.com/users/kalyank23/followers", "following_url": "https://api.github.com/users/kalyank23/following{/other_user}", "gists_url": "https://api.github.com/users/kalyank23/gists{/gist_id}", "starred_url": "https://api.github.com/users/kalyank23/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kalyank23/subscriptions", "organizations_url": "https://api.github.com/users/kalyank23/orgs", "repos_url": "https://api.github.com/users/kalyank23/repos", "events_url": "https://api.github.com/users/kalyank23/events{/privacy}", "received_events_url": "https://api.github.com/users/kalyank23/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2019-03-13T15:05:52Z", "updated_at": "2019-03-13T20:21:25Z", "closed_at": "2019-03-13T20:21:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/51", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/51/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/51/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/51/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/51", "id": 420329313, "node_id": "MDU6SXNzdWU0MjAzMjkzMTM=", "number": 51, "title": "Error installing PyKCS11 with pip install", "user": {"login": "kalyank23", "id": 34736945, "node_id": "MDQ6VXNlcjM0NzM2OTQ1", "avatar_url": "https://avatars0.githubusercontent.com/u/34736945?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kalyank23", "html_url": "https://github.com/kalyank23", "followers_url": "https://api.github.com/users/kalyank23/followers", "following_url": "https://api.github.com/users/kalyank23/following{/other_user}", "gists_url": "https://api.github.com/users/kalyank23/gists{/gist_id}", "starred_url": "https://api.github.com/users/kalyank23/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kalyank23/subscriptions", "organizations_url": "https://api.github.com/users/kalyank23/orgs", "repos_url": "https://api.github.com/users/kalyank23/repos", "events_url": "https://api.github.com/users/kalyank23/events{/privacy}", "received_events_url": "https://api.github.com/users/kalyank23/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 537984180, "node_id": "MDU6TGFiZWw1Mzc5ODQxODA=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/invalid", "name": "invalid", "color": "e6e6e6", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2019-03-13T05:55:25Z", "updated_at": "2019-03-13T14:35:47Z", "closed_at": "2019-03-13T14:35:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used:\r\n* PyKCS11 version: 1.5.3\r\n* Python version: 2.7.16\r\n* PKCS#11 library used: Not applicable\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen.\r\nPyKCS11 would have installed successfully with pip install\r\n\r\nDescribe what _did_ happen.\r\nGetting error as:\r\n\r\nsrc/pykcs11_wrap.cpp(13610) : error C2065: 'SWIGTYPE_p_std__vectorT_unsigned_char_std__allocatorT_unsigned_char_t_t' : undeclared identifier\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1.  Install https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266\r\n2. And then run pip install PyKCS11\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/49", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/49/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/49/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/49", "id": 407334233, "node_id": "MDU6SXNzdWU0MDczMzQyMzM=", "number": 49, "title": "Support for CK_GCM_PARAMS", "user": {"login": "someshi", "id": 2360284, "node_id": "MDQ6VXNlcjIzNjAyODQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/2360284?v=4", "gravatar_id": "", "url": "https://api.github.com/users/someshi", "html_url": "https://github.com/someshi", "followers_url": "https://api.github.com/users/someshi/followers", "following_url": "https://api.github.com/users/someshi/following{/other_user}", "gists_url": "https://api.github.com/users/someshi/gists{/gist_id}", "starred_url": "https://api.github.com/users/someshi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/someshi/subscriptions", "organizations_url": "https://api.github.com/users/someshi/orgs", "repos_url": "https://api.github.com/users/someshi/repos", "events_url": "https://api.github.com/users/someshi/events{/privacy}", "received_events_url": "https://api.github.com/users/someshi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-02-06T16:59:19Z", "updated_at": "2019-05-28T13:38:24Z", "closed_at": "2019-05-28T13:38:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "The .i file includes CKM_AES_GCM but not the corresponding CK_GCM_PARAMS structure to use the GCM mechanism.\r\n\r\nSample code using CK_GCM_PARAMS\r\nhttps://github.com/aws-samples/aws-cloudhsm-pkcs11-examples/blob/481f533cc61f0aa4deee42712746932e508b243b/src/encrypt/gcm.c \r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/46", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/46/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/46/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/46/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/46", "id": 402225966, "node_id": "MDU6SXNzdWU0MDIyMjU5NjY=", "number": 46, "title": "Use setuptools", "user": {"login": "fzonneveld", "id": 9437091, "node_id": "MDQ6VXNlcjk0MzcwOTE=", "avatar_url": "https://avatars0.githubusercontent.com/u/9437091?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fzonneveld", "html_url": "https://github.com/fzonneveld", "followers_url": "https://api.github.com/users/fzonneveld/followers", "following_url": "https://api.github.com/users/fzonneveld/following{/other_user}", "gists_url": "https://api.github.com/users/fzonneveld/gists{/gist_id}", "starred_url": "https://api.github.com/users/fzonneveld/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fzonneveld/subscriptions", "organizations_url": "https://api.github.com/users/fzonneveld/orgs", "repos_url": "https://api.github.com/users/fzonneveld/repos", "events_url": "https://api.github.com/users/fzonneveld/events{/privacy}", "received_events_url": "https://api.github.com/users/fzonneveld/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-01-23T12:53:57Z", "updated_at": "2019-02-08T10:42:18Z", "closed_at": "2019-02-08T10:42:18Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "With setuptools we can create wheels.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/45", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/45/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/45/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/45", "id": 401895038, "node_id": "MDU6SXNzdWU0MDE4OTUwMzg=", "number": 45, "title": "CKA_UNWRAP_TEMPLATE", "user": {"login": "alfredgamulo", "id": 616089, "node_id": "MDQ6VXNlcjYxNjA4OQ==", "avatar_url": "https://avatars0.githubusercontent.com/u/616089?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alfredgamulo", "html_url": "https://github.com/alfredgamulo", "followers_url": "https://api.github.com/users/alfredgamulo/followers", "following_url": "https://api.github.com/users/alfredgamulo/following{/other_user}", "gists_url": "https://api.github.com/users/alfredgamulo/gists{/gist_id}", "starred_url": "https://api.github.com/users/alfredgamulo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alfredgamulo/subscriptions", "organizations_url": "https://api.github.com/users/alfredgamulo/orgs", "repos_url": "https://api.github.com/users/alfredgamulo/repos", "events_url": "https://api.github.com/users/alfredgamulo/events{/privacy}", "received_events_url": "https://api.github.com/users/alfredgamulo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 14, "created_at": "2019-01-22T18:27:09Z", "updated_at": "2019-04-18T06:27:19Z", "closed_at": "2019-04-18T06:27:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "* PyKCS11 version: 1.5.3\r\n* Python version: 3.6.7\r\n\r\nI'm trying to create an RSA keypair with an UNWRAP_TEMPLATE. I was wondering if you can provide an example? I am getting an error on trying to create it, code pasted below:\r\n\r\n```\r\n    rsa_mechanism = Mechanism(CKM_RSA_X9_31_KEY_PAIR_GEN, None)\r\n    CKA_UNWRAP_TEMPLATE = 1073742354\r\n    unwrap_template = ((CKA_EXTRACTABLE, CK_FALSE),)\r\n    public_label = \"RSA_public_key\"\r\n    public_template = [\r\n        (CKA_CLASS, CKO_PUBLIC_KEY),\r\n        (CKA_TOKEN, CK_TRUE),\r\n        (CKA_MODULUS_BITS, 2048),\r\n        (CKA_PUBLIC_EXPONENT, (0x01, 0x00, 0x01)),\r\n        (CKA_ENCRYPT, CK_TRUE),\r\n        (CKA_VERIFY, CK_TRUE),\r\n        (CKA_VERIFY_RECOVER, CK_TRUE),\r\n        (CKA_WRAP, CK_TRUE),\r\n        (CKA_LABEL, public_label)\r\n    ]\r\n    private_label = \"RSA_private_key\"\r\n    private_template = [\r\n        (CKA_TOKEN, CK_TRUE),\r\n        (CKA_DECRYPT, CK_TRUE),\r\n        (CKA_SIGN, CK_TRUE),\r\n        (CKA_SIGN_RECOVER, CK_TRUE),\r\n        (CKA_UNWRAP, CK_TRUE),\r\n        (CKA_UNWRAP_TEMPLATE, unwrap_template),\r\n        (CKA_LABEL, private_label)\r\n    ]\r\n    pub_key, pri_key = pkcs11.generate_key_pair(rsa_mechanism, public_template, private_template)\r\n```\r\nThe error I'm seeing as follows:\r\n```\r\nself = <PyKCS11.LowLevel.CK_ATTRIBUTE_SMART; proxy of <Swig Object of type 'vector< CK_ATTRIBUTE_SMART >::value_type *' at 0x7facac2baed0> >\r\nargs = (1073742354, ((354, 0),))\r\n\r\n>   def SetBin(self, *args): return _LowLevel.CK_ATTRIBUTE_SMART_SetBin(self, *args)\r\nE   TypeError: in method 'CK_ATTRIBUTE_SMART_SetBin', argument 3 of type 'std::vector< unsigned char > const &'\r\n\r\n/usr/local/lib64/python3.6/site-packages/PyKCS11/LowLevel.py:1365: TypeError\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/44", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/44/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/44/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/44", "id": 400735048, "node_id": "MDU6SXNzdWU0MDA3MzUwNDg=", "number": 44, "title": "CKR_TOKEN_NOT_PRESENT", "user": {"login": "edsonitk", "id": 25555558, "node_id": "MDQ6VXNlcjI1NTU1NTU4", "avatar_url": "https://avatars3.githubusercontent.com/u/25555558?v=4", "gravatar_id": "", "url": "https://api.github.com/users/edsonitk", "html_url": "https://github.com/edsonitk", "followers_url": "https://api.github.com/users/edsonitk/followers", "following_url": "https://api.github.com/users/edsonitk/following{/other_user}", "gists_url": "https://api.github.com/users/edsonitk/gists{/gist_id}", "starred_url": "https://api.github.com/users/edsonitk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/edsonitk/subscriptions", "organizations_url": "https://api.github.com/users/edsonitk/orgs", "repos_url": "https://api.github.com/users/edsonitk/repos", "events_url": "https://api.github.com/users/edsonitk/events{/privacy}", "received_events_url": "https://api.github.com/users/edsonitk/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-01-18T13:56:54Z", "updated_at": "2019-01-21T18:25:55Z", "closed_at": "2019-01-18T14:34:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "windows 7\r\nPyKCS11 1.5.3\r\nPython 2.7.10\r\nPYKCS11LIB==aetpkss1.dll\r\n\r\nError executing the following code:\r\n\r\nfrom PyKCS11 import *\r\npkcs11 = PyKCS11Lib()\r\npkcs11.load()\r\nslot = pkcs11.getSlotList(tokenPresent=True)[0]\r\n\r\n\r\nsession = pkcs11.openSession(slot, PyKCS11.CKF_RW_SESSION)\r\n\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Python27\\lib\\site-packages\\PyKCS11\\__init__.py\", line 627, in openSes\r\nsion\r\n    raise PyKCS11Error(rv)\r\nPyKCS11.PyKCS11Error: CKR_TOKEN_NOT_RECOGNIZED (0x000000E1)\r\n>>> session = pkcs11.openSession(52482, PyKCS11.CKF_RW_SESSION)\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Python27\\lib\\site-packages\\PyKCS11\\__init__.py\", line 627, in openSes\r\nsion\r\n    raise PyKCS11Error(rv)\r\nPyKCS11.PyKCS11Error: CKR_TOKEN_NOT_PRESENT (0x000000E0)\r\n\r\nNote: Certificate validated on some sites\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/43", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/43/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/43/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/43/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/43", "id": 400727430, "node_id": "MDU6SXNzdWU0MDA3Mjc0MzA=", "number": 43, "title": "Elliptic curve key creation", "user": {"login": "xzr", "id": 2156119, "node_id": "MDQ6VXNlcjIxNTYxMTk=", "avatar_url": "https://avatars0.githubusercontent.com/u/2156119?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xzr", "html_url": "https://github.com/xzr", "followers_url": "https://api.github.com/users/xzr/followers", "following_url": "https://api.github.com/users/xzr/following{/other_user}", "gists_url": "https://api.github.com/users/xzr/gists{/gist_id}", "starred_url": "https://api.github.com/users/xzr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xzr/subscriptions", "organizations_url": "https://api.github.com/users/xzr/orgs", "repos_url": "https://api.github.com/users/xzr/repos", "events_url": "https://api.github.com/users/xzr/events{/privacy}", "received_events_url": "https://api.github.com/users/xzr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-01-18T13:35:47Z", "updated_at": "2019-04-08T14:11:04Z", "closed_at": "2019-04-08T14:11:04Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used: Ubuntu 18.04 x64\r\n* PyKCS11 version: 1.4.2\r\n* Python version: Python 2.7.15rc1\r\n* PKCS#11 library used: /usr/lib/softhsm/libsofthsm2.so\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nHey,\r\n\r\nI'm implementing ECDSA key support for an application that uses PyKCS11 to hook into a HSM. \r\n\r\nLooking into the example code, I couldn't find a mention about EC key creation.\r\n\r\nGoing through the PKCS#11 docs, I think I can figure out how to get a key created, but won't be too pythonic. (Particular painpoint being defining the CKA_EC_PARAMS, curve etc).\r\n\r\nSo I guess this breaks down to 2 points:\r\n1. Am I just not finding some example or utility function to ease the process a bit or do those not exist?\r\n2. EC examples would be very helpful \r\n\r\nI'll continue with my implementation and can probably contribute an example if none exists currently, but just wanted to get a discussion going about it.\r\n\r\nAlso, thanks for the great work on the library. It has made my life a lot easier :)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/42", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/42/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/42/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/42/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/42", "id": 381261792, "node_id": "MDU6SXNzdWUzODEyNjE3OTI=", "number": 42, "title": "Understanding how to use PyKCS11 for a MFA/SAML interface login", "user": {"login": "synergiator", "id": 1834666, "node_id": "MDQ6VXNlcjE4MzQ2NjY=", "avatar_url": "https://avatars3.githubusercontent.com/u/1834666?v=4", "gravatar_id": "", "url": "https://api.github.com/users/synergiator", "html_url": "https://github.com/synergiator", "followers_url": "https://api.github.com/users/synergiator/followers", "following_url": "https://api.github.com/users/synergiator/following{/other_user}", "gists_url": "https://api.github.com/users/synergiator/gists{/gist_id}", "starred_url": "https://api.github.com/users/synergiator/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/synergiator/subscriptions", "organizations_url": "https://api.github.com/users/synergiator/orgs", "repos_url": "https://api.github.com/users/synergiator/repos", "events_url": "https://api.github.com/users/synergiator/events{/privacy}", "received_events_url": "https://api.github.com/users/synergiator/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-11-15T17:19:41Z", "updated_at": "2018-11-15T17:25:40Z", "closed_at": "2018-11-15T17:25:40Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used:\r\nLinux Xubuntu 18.04\r\n* PyKCS11 version: 1.5.3\r\n* Python version: 2.7.15rc1\r\n* PKCS#11 library used:\r\n/usr/local/lib/libcvP11.so (that is, a card with STARCOS 3.2)\r\n\r\n#### Please describe your issue in as much detail as possible:\r\n\r\nWhat I am actually going to do, is to enable users for a SAML login with MFA to get security credentials. Specifically, I've found a Go implementation of the ADFS interface (link below), but they seem not to support MFA. \r\n\r\nIn first step, I am going to use PyKCS11 to extract the public certificate chain from the MFA device, but how would it be possible to use PyKCS11 for the login?\r\nhttps://github.com/wernerb/aws-adfs", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/41", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/41/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/41/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/41", "id": 381260083, "node_id": "MDU6SXNzdWUzODEyNjAwODM=", "number": 41, "title": "Clarification how to export public certificates based on dumpit.py", "user": {"login": "synergiator", "id": 1834666, "node_id": "MDQ6VXNlcjE4MzQ2NjY=", "avatar_url": "https://avatars3.githubusercontent.com/u/1834666?v=4", "gravatar_id": "", "url": "https://api.github.com/users/synergiator", "html_url": "https://github.com/synergiator", "followers_url": "https://api.github.com/users/synergiator/followers", "following_url": "https://api.github.com/users/synergiator/following{/other_user}", "gists_url": "https://api.github.com/users/synergiator/gists{/gist_id}", "starred_url": "https://api.github.com/users/synergiator/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/synergiator/subscriptions", "organizations_url": "https://api.github.com/users/synergiator/orgs", "repos_url": "https://api.github.com/users/synergiator/repos", "events_url": "https://api.github.com/users/synergiator/events{/privacy}", "received_events_url": "https://api.github.com/users/synergiator/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-11-15T17:15:19Z", "updated_at": "2018-11-15T17:26:12Z", "closed_at": "2018-11-15T17:26:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* Operating system used:\r\nLinux Xubuntu 18.04\r\n* PyKCS11 version: 1.5.3\r\n* Python version: 2.7.15rc1\r\n* PKCS#11 library used:\r\n/usr/local/lib/libcvP11.so (that is, a card with STARCOS 3.2)\r\n\r\nIf I need to have only public certificates in their base64 form, would be the proper approach to remove dump() calls from dumpit.py?\r\n\r\nSide note: thank you very much for this library!\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/40", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/40/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/40/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/40/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/40", "id": 368513967, "node_id": "MDU6SXNzdWUzNjg1MTM5Njc=", "number": 40, "title": "Can't run sample scripts using the LowLevel library", "user": {"login": "ohadm2", "id": 13061670, "node_id": "MDQ6VXNlcjEzMDYxNjcw", "avatar_url": "https://avatars0.githubusercontent.com/u/13061670?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ohadm2", "html_url": "https://github.com/ohadm2", "followers_url": "https://api.github.com/users/ohadm2/followers", "following_url": "https://api.github.com/users/ohadm2/following{/other_user}", "gists_url": "https://api.github.com/users/ohadm2/gists{/gist_id}", "starred_url": "https://api.github.com/users/ohadm2/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ohadm2/subscriptions", "organizations_url": "https://api.github.com/users/ohadm2/orgs", "repos_url": "https://api.github.com/users/ohadm2/repos", "events_url": "https://api.github.com/users/ohadm2/events{/privacy}", "received_events_url": "https://api.github.com/users/ohadm2/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2018-10-10T06:37:25Z", "updated_at": "2018-10-12T13:47:00Z", "closed_at": "2018-10-12T13:47:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "################## My system information ###############\r\n\r\n* Operating system used: Windows 10 (build 1803)\r\n* PyKCS11 version: 1.5.2\r\n* Python version: 3.7\r\n* PKCS#11 library used: PyKCS11.LowLevel\r\n\r\n###################################################\r\n\r\nHi. \r\n\r\nFirst of all, I want to say thank you for that great module!\r\n\r\nAs for my problem, I am simply trying to run one of your LowLevel sample scripts (test.py in particular) and I fail.\r\n\r\nThe error message is related to UTF-8 encoding problem.\r\n\r\nAfter doing further investigation it seems like the problem resides in the call to the function \"GetLabel\".\r\n\r\nPlease see the attached picture for more details (note that I'm using Athena's driver to access the smartcard).\r\n\r\nCan you please help me figure out this problem?\r\n\r\nThanks!\r\n\r\n![decode-err](https://user-images.githubusercontent.com/13061670/46717264-f3e35c00-cc6f-11e8-9da2-4c97a16e009d.PNG)\r\n\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/39", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/39/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/39/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/39/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/39", "id": 360191987, "node_id": "MDU6SXNzdWUzNjAxOTE5ODc=", "number": 39, "title": "PyKCS11 with Aladdin R.D. tokens", "user": {"login": "Goblenus", "id": 16175474, "node_id": "MDQ6VXNlcjE2MTc1NDc0", "avatar_url": "https://avatars0.githubusercontent.com/u/16175474?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Goblenus", "html_url": "https://github.com/Goblenus", "followers_url": "https://api.github.com/users/Goblenus/followers", "following_url": "https://api.github.com/users/Goblenus/following{/other_user}", "gists_url": "https://api.github.com/users/Goblenus/gists{/gist_id}", "starred_url": "https://api.github.com/users/Goblenus/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Goblenus/subscriptions", "organizations_url": "https://api.github.com/users/Goblenus/orgs", "repos_url": "https://api.github.com/users/Goblenus/repos", "events_url": "https://api.github.com/users/Goblenus/events{/privacy}", "received_events_url": "https://api.github.com/users/Goblenus/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-09-14T07:42:11Z", "updated_at": "2018-09-14T09:33:17Z", "closed_at": "2018-09-14T09:33:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### System information\r\n\r\n* Operating system used: Windows 10 Pro 10.0.17134\r\n* PyKCS11 version: 1.5.2\r\n* Python version: 3.7.0\r\n* PKCS#11 library used: jcPKCS11-2.dll (Aladdin R.D.)\r\n\r\n#### Details:\r\nHello\r\n\r\nI want to use PyKCS11 with [JaCarta PKI/\u0413\u041e\u0421\u0422](https://www.aladdin-rd.ru/catalog/jacarta-pki-gost/index). But they has some specific methods in their PKCS#11 such as `JC_PKI_SetComplexity`. How can I invoke them using PyKCS11.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/37", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/37/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/37/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/37/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/37", "id": 332783280, "node_id": "MDU6SXNzdWUzMzI3ODMyODA=", "number": 37, "title": "UnicodeDecodeError with Rutoken ECP after library update ", "user": {"login": "nekolyanich", "id": 752305, "node_id": "MDQ6VXNlcjc1MjMwNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/752305?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nekolyanich", "html_url": "https://github.com/nekolyanich", "followers_url": "https://api.github.com/users/nekolyanich/followers", "following_url": "https://api.github.com/users/nekolyanich/following{/other_user}", "gists_url": "https://api.github.com/users/nekolyanich/gists{/gist_id}", "starred_url": "https://api.github.com/users/nekolyanich/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nekolyanich/subscriptions", "organizations_url": "https://api.github.com/users/nekolyanich/orgs", "repos_url": "https://api.github.com/users/nekolyanich/repos", "events_url": "https://api.github.com/users/nekolyanich/events{/privacy}", "received_events_url": "https://api.github.com/users/nekolyanich/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2018-06-15T13:53:26Z", "updated_at": "2018-06-19T20:46:44Z", "closed_at": "2018-06-19T20:46:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "* Operating system used: Linux x64\r\n* PyKCS11 version: 1.5.2\r\n* Python version: 3.6\r\n* PKCS#11 library used: librtpkcs11ecp.so\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen\r\nI have Rutoken ECP. \r\nBefore last library update (with auto string decoding) on v1.4.4 token_info was:\r\n```\r\n(Pdb) pp token_info.to_dict()\r\n{'firmwareVersion': (23, 2),\r\n 'flags': ['CKF_RNG',\r\n           'CKF_LOGIN_REQUIRED',\r\n           'CKF_USER_PIN_INITIALIZED',\r\n           'CKF_TOKEN_INITIALIZED',\r\n           'CKF_SO_PIN_TO_BE_CHANGED'],\r\n 'hardwareVersion': (20, 5),\r\n 'label': b'Rutoken ECP <no label>          ',\r\n 'manufacturerID': b'Aktiv Co.                       ',\r\n 'model': b'Rutoken ECP     ',\r\n 'serialNumber': b'37354ce9        ',\r\n 'ulFreePrivateMemory': 60032,\r\n 'ulFreePublicMemory': 60032,\r\n 'ulMaxPinLen': 32,\r\n 'ulMaxRwSessionCount': 0,\r\n 'ulMaxSessionCount': 0,\r\n 'ulMinPinLen': 6,\r\n 'ulRwSessionCount': 0,\r\n 'ulSessionCount': 0,\r\n 'ulTotalPrivateMemory': 65536,\r\n 'ulTotalPublicMemory': 65536,\r\n 'utcTime': b'versionr.\\x00\\x00\\x00\\xda\\x07_c'}\r\n\r\n```\r\n\r\n### Describe what _did_ happen.\r\n\r\nOn v1.5.2 it raise:\r\n \r\n`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte`\r\n\r\nI've modify a bit you code for ignore errors:\r\n\r\n```\r\n diff --git a/src/pykcs11.i b/src/pykcs11.i\r\nindex f15b023..8eac4be 100644\r\n--- a/src/pykcs11.i\r\n+++ b/src/pykcs11.i\r\n@@ -58,7 +58,7 @@ using namespace std;\r\n   #ifdef Py_USING_UNICODE\r\n    $result = PyBytes_FromStringAndSize((const char*)($1.m_str.c_str()),(int)($1.m_str.size()));\r\n   #else\r\n-   $result = PyUnicode_FromStringAndSize((const char*)($1.m_str.c_str()),(int)($1.m_str.size()));\r\n+   $result = PyUnicode_Decode((const char*)($1.m_str.c_str()),(int)($1.m_str.size()), \"utf-8\", \"ignore\");\r\n   #endif\r\n }\r\n```\r\nAnd it works for me now:\r\n```\r\n(Pdb) pp token_info.to_dict()\r\n{'firmwareVersion': (23, 2),\r\n 'flags': ['CKF_RNG',\r\n           'CKF_LOGIN_REQUIRED',\r\n           'CKF_USER_PIN_INITIALIZED',\r\n           'CKF_TOKEN_INITIALIZED',\r\n           'CKF_SO_PIN_TO_BE_CHANGED'],\r\n 'hardwareVersion': (20, 5),\r\n 'label': 'Rutoken ECP <no label>          ',\r\n 'manufacturerID': 'Aktiv Co.                       ',\r\n 'model': 'Rutoken ECP     ',\r\n 'serialNumber': '37354ce9        ',\r\n 'ulFreePrivateMemory': 60032,\r\n 'ulFreePublicMemory': 60032,\r\n 'ulMaxPinLen': 32,\r\n 'ulMaxRwSessionCount': 0,\r\n 'ulMaxSessionCount': 0,\r\n 'ulMinPinLen': 6,\r\n 'ulRwSessionCount': 0,\r\n 'ulSessionCount': 0,\r\n 'ulTotalPrivateMemory': 65536,\r\n 'ulTotalPublicMemory': 65536,\r\n 'utcTime': 'j\\x01|\\x01\\x01}\\x02|\\x02s\\x1et\\x02d\\x01'}\r\n```\r\nCan you make this behavior in upstream?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/36", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/36/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/36/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/36/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/36", "id": 328546847, "node_id": "MDU6SXNzdWUzMjg1NDY4NDc=", "number": 36, "title": "PyKCS11.PyKCS11Error: CKR_OBJECT_HANDLE_INVALID", "user": {"login": "krash84", "id": 9379087, "node_id": "MDQ6VXNlcjkzNzkwODc=", "avatar_url": "https://avatars2.githubusercontent.com/u/9379087?v=4", "gravatar_id": "", "url": "https://api.github.com/users/krash84", "html_url": "https://github.com/krash84", "followers_url": "https://api.github.com/users/krash84/followers", "following_url": "https://api.github.com/users/krash84/following{/other_user}", "gists_url": "https://api.github.com/users/krash84/gists{/gist_id}", "starred_url": "https://api.github.com/users/krash84/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/krash84/subscriptions", "organizations_url": "https://api.github.com/users/krash84/orgs", "repos_url": "https://api.github.com/users/krash84/repos", "events_url": "https://api.github.com/users/krash84/events{/privacy}", "received_events_url": "https://api.github.com/users/krash84/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 537984180, "node_id": "MDU6TGFiZWw1Mzc5ODQxODA=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/invalid", "name": "invalid", "color": "e6e6e6", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "LudovicRousseau", "id": 398496, "node_id": "MDQ6VXNlcjM5ODQ5Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/398496?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LudovicRousseau", "html_url": "https://github.com/LudovicRousseau", "followers_url": "https://api.github.com/users/LudovicRousseau/followers", "following_url": "https://api.github.com/users/LudovicRousseau/following{/other_user}", "gists_url": "https://api.github.com/users/LudovicRousseau/gists{/gist_id}", "starred_url": "https://api.github.com/users/LudovicRousseau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LudovicRousseau/subscriptions", "organizations_url": "https://api.github.com/users/LudovicRousseau/orgs", "repos_url": "https://api.github.com/users/LudovicRousseau/repos", "events_url": "https://api.github.com/users/LudovicRousseau/events{/privacy}", "received_events_url": "https://api.github.com/users/LudovicRousseau/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 9, "created_at": "2018-06-01T14:42:31Z", "updated_at": "2018-10-08T10:26:22Z", "closed_at": "2018-06-19T20:49:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: 1.4.4\r\n* Python version: 2.7\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nHello!\r\nI am trying to sign \"hello world\" with the following code (based on https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/signature.py)\r\n```\r\nkeyID = (49,)\r\nprivate_keys = hSession.findObjects([\r\n     (PyKCS11.CKA_CLASS, PyKCS11.CKO_PRIVATE_KEY),\r\n     (PyKCS11.CKA_ID, keyID)\r\n])\r\npriv_key = private_keys[0]\r\nmech = PyKCS11.Mechanism(PyKCS11.CKM_GOSTR3410, None)\r\nto_sign = '48656c6c6f20776f726c640d0a'\r\nsigned_data = session.sign(priv_key, binascii.unhexlify(to_sign), mech)\r\n```\r\n\r\nThis gives me:\r\n`PyKCS11.PyKCS11Error: CKR_OBJECT_HANDLE_INVALID (0x00000082)`\r\n\r\nIf I change mech to `PyKCS11.Mechanism(PyKCS11.CKM_SHA1_RSA_PKCS, None)` then I get:\r\n`PyKCS11.PyKCS11Error: CKR_KEY_TYPE_INCONSISTENT (0x00000063)`\r\n\r\nIs it a problem with private key?\r\n\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/35", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/35/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/35/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/35/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/35", "id": 316332789, "node_id": "MDU6SXNzdWUzMTYzMzI3ODk=", "number": 35, "title": "Error compiling in Ubuntu 16.04", "user": {"login": "evandrojr", "id": 939608, "node_id": "MDQ6VXNlcjkzOTYwOA==", "avatar_url": "https://avatars0.githubusercontent.com/u/939608?v=4", "gravatar_id": "", "url": "https://api.github.com/users/evandrojr", "html_url": "https://github.com/evandrojr", "followers_url": "https://api.github.com/users/evandrojr/followers", "following_url": "https://api.github.com/users/evandrojr/following{/other_user}", "gists_url": "https://api.github.com/users/evandrojr/gists{/gist_id}", "starred_url": "https://api.github.com/users/evandrojr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/evandrojr/subscriptions", "organizations_url": "https://api.github.com/users/evandrojr/orgs", "repos_url": "https://api.github.com/users/evandrojr/repos", "events_url": "https://api.github.com/users/evandrojr/events{/privacy}", "received_events_url": "https://api.github.com/users/evandrojr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-04-20T16:27:03Z", "updated_at": "2018-04-20T20:28:53Z", "closed_at": "2018-04-20T20:28:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: latestest\r\n* Python version: 3.5\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nShould compile PkKCS11, error:\r\n\r\n% make build     \r\npython setup.py build\r\nrunning build\r\nrunning build_ext\r\nbuilding 'PyKCS11._LowLevel' extension\r\nswigging src/pykcs11.i to src/pykcs11_wrap.cpp\r\nswig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i\r\nx86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/ck_attribute_smart.cpp -o build/temp.linux-x86_64-2.7/src/ck_attribute_smart.o\r\ncc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++\r\nx86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/pkcs11lib.cpp -o build/temp.linux-x86_64-2.7/src/pkcs11lib.o\r\ncc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++\r\nx86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/pykcs11string.cpp -o build/temp.linux-x86_64-2.7/src/pykcs11string.o\r\ncc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++\r\nx86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/utility.cpp -o build/temp.linux-x86_64-2.7/src/utility.o\r\ncc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++\r\nx86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/local/include -I/usr/include/python2.7 -c src/pykcs11_wrap.cpp -o build/temp.linux-x86_64-2.7/src/pykcs11_wrap.o\r\ncc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++\r\nsrc/pykcs11_wrap.cpp:171:21: fatal error: Python.h: No such file or directory\r\ncompilation terminated.\r\nerror: command 'x86_64-linux-gnu-gcc' failed with exit status 1\r\nMakefile:12: recipe for target 'build-stamp' failed\r\nmake: *** [build-stamp] Error 1\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. Download master PyKCS11 from github\r\n2. Run: make build     ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/34", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/34/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/34/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/34", "id": 313294228, "node_id": "MDU6SXNzdWUzMTMyOTQyMjg=", "number": 34, "title": "pip install on windows 7 says \"Don't know how to compile StdAfx.h\"", "user": {"login": "lsaffre", "id": 4406823, "node_id": "MDQ6VXNlcjQ0MDY4MjM=", "avatar_url": "https://avatars0.githubusercontent.com/u/4406823?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lsaffre", "html_url": "https://github.com/lsaffre", "followers_url": "https://api.github.com/users/lsaffre/followers", "following_url": "https://api.github.com/users/lsaffre/following{/other_user}", "gists_url": "https://api.github.com/users/lsaffre/gists{/gist_id}", "starred_url": "https://api.github.com/users/lsaffre/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lsaffre/subscriptions", "organizations_url": "https://api.github.com/users/lsaffre/orgs", "repos_url": "https://api.github.com/users/lsaffre/repos", "events_url": "https://api.github.com/users/lsaffre/events{/privacy}", "received_events_url": "https://api.github.com/users/lsaffre/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-04-11T12:04:19Z", "updated_at": "2018-04-11T12:15:10Z", "closed_at": "2018-04-11T12:15:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n* PyKCS11 version: 1.0.4\r\n* Python version: 3.6.5 and 2.7.14\r\n* Windows 7 (64 bit)\r\nI am trying to install PyKCS11 on a Windows machine and I get the following output:\r\n```\r\nCollecting pkcs11\r\n  Using cached pkcs11-1.0.4.zip\r\nInstalling collected packages: pkcs11\r\n  Running setup.py install for pkcs11: started\r\n    Running setup.py install for pkcs11: finished with status 'error'\r\n    Complete output from command F:\\ANWPROG\\Python\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\Steve\\\\AppData\\\\Local\\\\Temp\\\\pip-build-shuy5bke\\\\pkcs11\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-1xokykx9-record\\install-record.txt --single-version-externally-managed --compile:\r\n    running install\r\n    running build\r\n    running build_ext\r\n    building 'pkcs11' extension\r\n    error: Don't know how to compile StdAfx.h\r\n    ----------------------------------------\r\n```\r\nI have installed Visual Studio and swigwin. I tried with both Python 2 and 3. \r\nAny ideas?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/33", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/33/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/33/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/33", "id": 313192014, "node_id": "MDU6SXNzdWUzMTMxOTIwMTQ=", "number": 33, "title": "initPin is not working, typo", "user": {"login": "fzonneveld", "id": 9437091, "node_id": "MDQ6VXNlcjk0MzcwOTE=", "avatar_url": "https://avatars0.githubusercontent.com/u/9437091?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fzonneveld", "html_url": "https://github.com/fzonneveld", "followers_url": "https://api.github.com/users/fzonneveld/followers", "following_url": "https://api.github.com/users/fzonneveld/following{/other_user}", "gists_url": "https://api.github.com/users/fzonneveld/gists{/gist_id}", "starred_url": "https://api.github.com/users/fzonneveld/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fzonneveld/subscriptions", "organizations_url": "https://api.github.com/users/fzonneveld/orgs", "repos_url": "https://api.github.com/users/fzonneveld/repos", "events_url": "https://api.github.com/users/fzonneveld/events{/privacy}", "received_events_url": "https://api.github.com/users/fzonneveld/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-04-11T06:42:03Z", "updated_at": "2018-04-11T16:38:43Z", "closed_at": "2018-04-11T13:35:27Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: 1.5.1\r\n* Python version: 3.5.2\r\n\r\n#### Please describe your issue in as much detail as possible:\r\ninitPin uses pin method parameter, not present.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/32", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/32/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/32/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/32/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/32", "id": 308946219, "node_id": "MDU6SXNzdWUzMDg5NDYyMTk=", "number": 32, "title": "pip 1.5.0 package install breaks", "user": {"login": "rday", "id": 118789, "node_id": "MDQ6VXNlcjExODc4OQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/118789?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rday", "html_url": "https://github.com/rday", "followers_url": "https://api.github.com/users/rday/followers", "following_url": "https://api.github.com/users/rday/following{/other_user}", "gists_url": "https://api.github.com/users/rday/gists{/gist_id}", "starred_url": "https://api.github.com/users/rday/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rday/subscriptions", "organizations_url": "https://api.github.com/users/rday/orgs", "repos_url": "https://api.github.com/users/rday/repos", "events_url": "https://api.github.com/users/rday/events{/privacy}", "received_events_url": "https://api.github.com/users/rday/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-03-27T12:24:11Z", "updated_at": "2018-03-30T09:40:59Z", "closed_at": "2018-03-30T09:40:31Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: 1.5.0\r\n* Python version: 3.6.2\r\n* Os: ALinux\r\n\r\n#### Please describe your issue in as much detail as possible:\r\n\r\nWhen using pip to upgrade to the PyKCS11 1.5.0 package on Linux, I noticed a few errors around the LowLevel library. When examining the previous PyPI package(1.4.4), it looks like the LowLevel module and the pykcs11_wrap.cpp code are included in the package. This is not the case with the 1.5.0 package.\r\n\r\nThe pip installation appears to succeed, but I am unable to import the PyKCS11 library.\r\n\r\nAre there new install steps, or could this be a bad pip package?\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n```\r\n(py-env) [ec2-user@ip-172-31-31-126 la]$ pip --no-cache-dir -v install PyKCS11\r\nCollecting PyKCS11\r\n  1 location(s) to search for versions of PyKCS11:\r\n  * https://pypi.python.org/simple/pykcs11/\r\n  Getting page https://pypi.python.org/simple/pykcs11/\r\n  Starting new HTTPS connection (1): pypi.python.org\r\n  https://pypi.python.org:443 \"GET /simple/pykcs11/ HTTP/1.1\" 200 1439\r\n  Analyzing links from page https://pypi.python.org/simple/pykcs11/\r\n    Skipping link https://pypi.python.org/packages/e9/f4/e5b42ab9f9049cbb8849aa6c9add3adff8889798c87cf9edb8ff4d4e6e45/PyKCS11-1.1.1.win32-py2.4.exe#md5=4778e61316b9e209684ac057f70d90d6 (from https://pypi.python.org/simple/pykcs11/); unsupported archive format: .exe\r\n    Found link https://pypi.python.org/packages/28/1e/091d5fcba391eaac36edb26826be92c72b4ae5b3e25f6379de5401f3b335/PyKCS11-1.1.1.zip#md5=3481059ab83f49d2caf30201c995ae1f (from https://pypi.python.org/simple/pykcs11/), version: 1.1.1\r\n    Found link https://pypi.python.org/packages/ab/11/cc2a85f528e3bf5e39a1da889070bf797fcf010eb2de9b581cdc49488a23/PyKCS11-1.2.0.tar.gz#md5=cd06a0e9e0f80f176066befd08505b1a (from https://pypi.python.org/simple/pykcs11/), version: 1.2.0\r\n    Skipping link https://pypi.python.org/packages/7f/0e/64dded7d29a84b34bd42cb83ce7a4aeb1e5cb02a23742d676c1b19e54241/PyKCS11-1.2.0.win32-py2.4.exe#md5=a2ac5c274f798838cd6c6ed3bdb92cec (from https://pypi.python.org/simple/pykcs11/); unsupported archive format: .exe\r\n    Found link https://pypi.python.org/packages/25/1c/8dfba4d52784c282df072887c5eaf5ee7077e1acdbe8cbd7692e32a33e86/PyKCS11-1.2.1.tar.gz#md5=f1be0bcef765a36e4362342c5df49eef (from https://pypi.python.org/simple/pykcs11/), version: 1.2.1\r\n    Skipping link https://pypi.python.org/packages/e8/ed/500105a37d79846d3077b118dc691707d85866a56ebd76c03fe2aa8605cd/PyKCS11-1.2.1.win32-py2.4.exe#md5=9e176dc678ed76e00f26a34e4ebfc034 (from https://pypi.python.org/simple/pykcs11/); unsupported archive format: .exe\r\n    Skipping link https://pypi.python.org/packages/57/cb/37896a4607c81d7351a2d40be720e68088c3e13b2a4ffbe76ea276398d86/PyKCS11-1.2.1.win32-py2.5.exe#md5=9b9c2aba1d16ab993ee5b9e60dd00942 (from https://pypi.python.org/simple/pykcs11/); unsupported archive format: .exe\r\n    Found link https://pypi.python.org/packages/7c/d7/2ccbf18ef020545933b096a035973146138f8a830272a0a555ae258ad8fb/PyKCS11-1.2.4.tar.gz#md5=39f85ed9e30719819ede4db5345996d0 (from https://pypi.python.org/simple/pykcs11/), version: 1.2.4\r\n    Found link https://pypi.python.org/packages/e5/a4/02b2836103348d38abb793ed2461386dd2c7e652a03a6e295ce569e0ca19/PyKCS11-1.3.0.tar.gz#md5=db1dffd14ed7f5860a2403b0097b6933 (from https://pypi.python.org/simple/pykcs11/), version: 1.3.0\r\n    Found link https://pypi.python.org/packages/70/97/ee9cefcd6052ae436be2b91efa59610421a1e917506e01aaf29cb3727ad4/PyKCS11-1.3.1.tar.gz#md5=e7690765736025888ecbce70229d2064 (from https://pypi.python.org/simple/pykcs11/), version: 1.3.1\r\n    Found link https://pypi.python.org/packages/c6/db/5e3ad4c6f24795844f4550cd8bdacf54f4061840613de81f0267a05692dc/PyKCS11-1.3.2.tar.gz#md5=7a90264871449e522558fddc1bf9f94f (from https://pypi.python.org/simple/pykcs11/), version: 1.3.2\r\n    Found link https://pypi.python.org/packages/5f/e2/61fd2636d6e4629600ce677139c5d4582a6d3f774bbc7e7a8ca94a7ec50a/PyKCS11-1.3.3.tar.gz#md5=c8d74043a97aef4fdfe1cbd527069c01 (from https://pypi.python.org/simple/pykcs11/), version: 1.3.3\r\n    Found link https://pypi.python.org/packages/c4/91/55ca0aa59d56c59b895a0cc48ee53495f609057e494571d331c34868fd38/PyKCS11-1.4.0.tar.gz#md5=2ef21e296b9b4e330f7adce8d89cc95b (from https://pypi.python.org/simple/pykcs11/), version: 1.4.0\r\n    Found link https://pypi.python.org/packages/6f/ab/23c358a6e6af5e396fb8817e2da05a489891d3d20a103e34f8a56180a395/PyKCS11-1.4.1.tar.gz#md5=b0f2c1dda012a64a2376aca2bcd4afb3 (from https://pypi.python.org/simple/pykcs11/), version: 1.4.1\r\n    Found link https://pypi.python.org/packages/f6/94/2e09d543049afa4b14f9f2820a2a4f297ff4e33ff64b1092ed7961f93a4c/PyKCS11-1.4.2.tar.gz#md5=cd39e136bb0b2341f07e029a6b0b9a99 (from https://pypi.python.org/simple/pykcs11/), version: 1.4.2\r\n    Found link https://pypi.python.org/packages/17/0e/0cf98fe7e2509b81f484d724f875934627fba7b00ac1af96b81bc6b193c2/PyKCS11-1.4.3.tar.gz#md5=d3141d75154c89afbf230280f28ef24f (from https://pypi.python.org/simple/pykcs11/), version: 1.4.3\r\n    Found link https://pypi.python.org/packages/6e/65/2421a94aa553cda9d3b6580f9d49e6d58625545cd650f09dbdd68e19f394/PyKCS11-1.4.4.tar.gz#md5=cdf42fc3c5a28dca05ffb2ffd1ea085b (from https://pypi.python.org/simple/pykcs11/), version: 1.4.4\r\n    Found link https://pypi.python.org/packages/7c/9b/22725f013616b9613e015d4206aca006204b9f448100f803c15c7e99ab15/PyKCS11-1.5.0.tar.gz#md5=73c914613a3be3f04df6737cbf02b507 (from https://pypi.python.org/simple/pykcs11/), version: 1.5.0\r\n  Using version 1.5.0 (newest of versions: 1.1.1, 1.2.0, 1.2.1, 1.2.4, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0)\r\n  https://pypi.python.org:443 \"GET /packages/7c/9b/22725f013616b9613e015d4206aca006204b9f448100f803c15c7e99ab15/PyKCS11-1.5.0.tar.gz HTTP/1.1\" 200 63667\r\n  Downloading PyKCS11-1.5.0.tar.gz (63kB)\r\n  Downloading from URL https://pypi.python.org/packages/7c/9b/22725f013616b9613e015d4206aca006204b9f448100f803c15c7e99ab15/PyKCS11-1.5.0.tar.gz#md5=73c914613a3be3f04df6737cbf02b507 (from https://pypi.python.org/simple/pykcs11/)\r\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 71kB 15.9MB/s \r\n  Running setup.py (path:/tmp/pip-build-qcwilyw4/PyKCS11/setup.py) egg_info for package PyKCS11\r\n    Running command python setup.py egg_info\r\n    running egg_info\r\n    creating pip-egg-info/PyKCS11.egg-info\r\n    writing pip-egg-info/PyKCS11.egg-info/PKG-INFO\r\n    writing dependency_links to pip-egg-info/PyKCS11.egg-info/dependency_links.txt\r\n    writing top-level names to pip-egg-info/PyKCS11.egg-info/top_level.txt\r\n    writing manifest file 'pip-egg-info/PyKCS11.egg-info/SOURCES.txt'\r\n    warning: manifest_maker: standard file '-c' not found\r\n\r\n    file PyKCS11/LowLevel.py (for module PyKCS11.LowLevel) not found\r\n    reading manifest file 'pip-egg-info/PyKCS11.egg-info/SOURCES.txt'\r\n    writing manifest file 'pip-egg-info/PyKCS11.egg-info/SOURCES.txt'\r\n  Source in /tmp/pip-build-qcwilyw4/PyKCS11 has version 1.5.0, which satisfies requirement PyKCS11 from https://pypi.python.org/packages/7c/9b/22725f013616b9613e015d4206aca006204b9f448100f803c15c7e99ab15/PyKCS11-1.5.0.tar.gz#md5=73c914613a3be3f04df6737cbf02b507\r\nInstalling collected packages: PyKCS11\r\n  Running setup.py install for PyKCS11 ...     Running command /home/ec2-user/py-env/bin/python3.6 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-qcwilyw4/PyKCS11/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-ni7_l6ig-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/py-env/include/site/python3.6/PyKCS11\r\n    running install\r\n    running build\r\n    running build_py\r\n    file PyKCS11/LowLevel.py (for module PyKCS11.LowLevel) not found\r\n    creating build\r\n    creating build/lib.linux-x86_64-3.6\r\n    creating build/lib.linux-x86_64-3.6/PyKCS11\r\n    copying PyKCS11/__init__.py -> build/lib.linux-x86_64-3.6/PyKCS11\r\n    file PyKCS11/LowLevel.py (for module PyKCS11.LowLevel) not found\r\n    running build_ext\r\n    building 'PyKCS11._LowLevel' extension\r\n    swigging src/pykcs11.i to src/pykcs11_wrap.cpp\r\n    swig -python -c++ -o src/pykcs11_wrap.cpp src/pykcs11.i\r\n    creating build/temp.linux-x86_64-3.6\r\n    creating build/temp.linux-x86_64-3.6/src\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/include -I/home/ec2-user/py-env/include -I/home/ec2-user/py362/include/python3.6m -c src/ck_attribute_smart.cpp -o build/temp.linux-x86_64-3.6/src/ck_attribute_smart.o\r\n    cc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++ [enabled by default]\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/include -I/home/ec2-user/py-env/include -I/home/ec2-user/py362/include/python3.6m -c src/pkcs11lib.cpp -o build/temp.linux-x86_64-3.6/src/pkcs11lib.o\r\n    cc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++ [enabled by default]\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/include -I/home/ec2-user/py-env/include -I/home/ec2-user/py362/include/python3.6m -c src/pykcs11string.cpp -o build/temp.linux-x86_64-3.6/src/pykcs11string.o\r\n    cc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++ [enabled by default]\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/include -I/home/ec2-user/py-env/include -I/home/ec2-user/py362/include/python3.6m -c src/utility.cpp -o build/temp.linux-x86_64-3.6/src/utility.o\r\n    cc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++ [enabled by default]\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/include -I/home/ec2-user/py-env/include -I/home/ec2-user/py362/include/python3.6m -c src/pykcs11_wrap.cpp -o build/temp.linux-x86_64-3.6/src/pykcs11_wrap.o\r\n    cc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++ [enabled by default]\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/include -I/home/ec2-user/py-env/include -I/home/ec2-user/py362/include/python3.6m -c src/pykcs11.cpp -o build/temp.linux-x86_64-3.6/src/pykcs11.o\r\n    cc1plus: warning: command line option \u2018-Wstrict-prototypes\u2019 is valid for C/ObjC but not for C++ [enabled by default]\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/include -I/home/ec2-user/py-env/include -I/home/ec2-user/py362/include/python3.6m -c src/dyn_unix.c -o build/temp.linux-x86_64-3.6/src/dyn_unix.o\r\n    g++ -pthread -shared build/temp.linux-x86_64-3.6/src/ck_attribute_smart.o build/temp.linux-x86_64-3.6/src/pkcs11lib.o build/temp.linux-x86_64-3.6/src/pykcs11string.o build/temp.linux-x86_64-3.6/src/utility.o build/temp.linux-x86_64-3.6/src/pykcs11_wrap.o build/temp.linux-x86_64-3.6/src/pykcs11.o build/temp.linux-x86_64-3.6/src/dyn_unix.o -L/usr/local/lib -o build/lib.linux-x86_64-3.6/PyKCS11/_LowLevel.cpython-36m-x86_64-linux-gnu.so\r\n    running install_lib\r\n    creating /home/ec2-user/py-env/lib/python3.6/site-packages/PyKCS11\r\n    copying build/lib.linux-x86_64-3.6/PyKCS11/_LowLevel.cpython-36m-x86_64-linux-gnu.so -> /home/ec2-user/py-env/lib/python3.6/site-packages/PyKCS11\r\n    copying build/lib.linux-x86_64-3.6/PyKCS11/__init__.py -> /home/ec2-user/py-env/lib/python3.6/site-packages/PyKCS11\r\n    byte-compiling /home/ec2-user/py-env/lib/python3.6/site-packages/PyKCS11/__init__.py to __init__.cpython-36.pyc\r\n    running install_egg_info\r\n    running egg_info\r\n    creating PyKCS11.egg-info\r\n    writing PyKCS11.egg-info/PKG-INFO\r\n    writing dependency_links to PyKCS11.egg-info/dependency_links.txt\r\n    writing top-level names to PyKCS11.egg-info/top_level.txt\r\n    writing manifest file 'PyKCS11.egg-info/SOURCES.txt'\r\n    warning: manifest_maker: standard file '-c' not found\r\n\r\n    file PyKCS11/LowLevel.py (for module PyKCS11.LowLevel) not found\r\n    reading manifest file 'PyKCS11.egg-info/SOURCES.txt'\r\n    writing manifest file 'PyKCS11.egg-info/SOURCES.txt'\r\n    Copying PyKCS11.egg-info to /home/ec2-user/py-env/lib/python3.6/site-packages/PyKCS11-1.5.0-py3.6.egg-info\r\n    running install_scripts\r\n    file PyKCS11/LowLevel.py (for module PyKCS11.LowLevel) not found\r\n    writing list of installed files to '/tmp/pip-ni7_l6ig-record/install-record.txt'\r\ndone\r\n  Removing source in /tmp/pip-build-qcwilyw4/PyKCS11\r\nSuccessfully installed PyKCS11-1.5.0\r\nCleaning up...\r\n(py-env) [ec2-user@ip-172-31-31-126 la]$ python\r\nPython 3.6.2 (default, Sep  1 2017, 16:56:32) \r\n[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import PyKCS11\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/ec2-user/py-env/lib/python3.6/site-packages/PyKCS11/__init__.py\", line 20, in <module>\r\n    import PyKCS11.LowLevel\r\nModuleNotFoundError: No module named 'PyKCS11.LowLevel'\r\n>>> quit()\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/31", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/31/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/31/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/31", "id": 308306187, "node_id": "MDU6SXNzdWUzMDgzMDYxODc=", "number": 31, "title": "Update PyPi Release", "user": {"login": "mon", "id": 3398021, "node_id": "MDQ6VXNlcjMzOTgwMjE=", "avatar_url": "https://avatars0.githubusercontent.com/u/3398021?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mon", "html_url": "https://github.com/mon", "followers_url": "https://api.github.com/users/mon/followers", "following_url": "https://api.github.com/users/mon/following{/other_user}", "gists_url": "https://api.github.com/users/mon/gists{/gist_id}", "starred_url": "https://api.github.com/users/mon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mon/subscriptions", "organizations_url": "https://api.github.com/users/mon/orgs", "repos_url": "https://api.github.com/users/mon/repos", "events_url": "https://api.github.com/users/mon/events{/privacy}", "received_events_url": "https://api.github.com/users/mon/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-03-24T22:57:10Z", "updated_at": "2018-03-26T19:39:41Z", "closed_at": "2018-03-26T19:39:41Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Lots of good commits since the last release, could you push a new version?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/27", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/27/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/27/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/27/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/27", "id": 293272107, "node_id": "MDU6SXNzdWUyOTMyNzIxMDc=", "number": 27, "title": "Trustkey Token on Linux. Testing with  ", "user": {"login": "mndar", "id": 10995098, "node_id": "MDQ6VXNlcjEwOTk1MDk4", "avatar_url": "https://avatars3.githubusercontent.com/u/10995098?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mndar", "html_url": "https://github.com/mndar", "followers_url": "https://api.github.com/users/mndar/followers", "following_url": "https://api.github.com/users/mndar/following{/other_user}", "gists_url": "https://api.github.com/users/mndar/gists{/gist_id}", "starred_url": "https://api.github.com/users/mndar/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mndar/subscriptions", "organizations_url": "https://api.github.com/users/mndar/orgs", "repos_url": "https://api.github.com/users/mndar/repos", "events_url": "https://api.github.com/users/mndar/events{/privacy}", "received_events_url": "https://api.github.com/users/mndar/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2018-01-31T18:54:54Z", "updated_at": "2018-02-02T07:57:46Z", "closed_at": "2018-02-02T07:57:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: 1.3.2-1\r\n* Python version: 3\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nThank you for your help so far LudovicRousseau.\r\nReferring to https://github.com/LudovicRousseau/CCID/issues/43 for usb token Trustkey (Watchdata token)\r\nI installed the drivers from the manufacturer's website and it installs pcscd_wd.\r\nI found a library in the binaries libwdpkcs_TRUSTKEY.so\r\nThis is the result of the executiion\r\n\r\n$ _PYKCS11LIB=/usr/lib/WatchData/TRUSTKEY/lib/libwdpkcs_TRUSTKEY.so python getinfo.py_\r\ncryptokiVersion: 2.10 \r\nflags:  \r\nlibraryDescription: PKCS#11 cryptoki module          \r\nlibraryVersion: 1.0\r\nmanufacturerID: WatchData  \r\nAvailable Slots: 3 [1, 2, 3]\r\nSlot n.: 1\r\n firmwareVersion: 1.00 \r\n flags: CKF_REMOVABLE_DEVICE, CKF_HW_SLOT \r\n hardwareVersion: 1.00 \r\n manufacturerID: Watchdata Technologies Pte.Ltd \r\n slotDescription: WatchData IC CARD Reader/Writer 0                                \r\n SessionInfo Error: CKR_SLOT_ID_INVALID (0x00000003)\r\nSlot n.: 2\r\n firmwareVersion: 1.00 \r\n flags: CKF_REMOVABLE_DEVICE, CKF_HW_SLOT \r\n hardwareVersion: 1.00 \r\n manufacturerID: Watchdata Technologies Pte.Ltd \r\n slotDescription: WatchData IC CARD Reader/Writer 1                                \r\n SessionInfo Error: CKR_SLOT_ID_INVALID (0x00000003)\r\nSlot n.: 3\r\n firmwareVersion: 1.00 \r\n flags: CKF_REMOVABLE_DEVICE, CKF_HW_SLOT \r\n hardwareVersion: 1.00 \r\n manufacturerID: Watchdata Technologies Pte.Ltd \r\n slotDescription: WatchData IC CARD Reader/Writer 2                                \r\n SessionInfo Error: CKR_SLOT_ID_INVALID (0x00000003)\r\n\r\nAre these errors normal or do they indicate some missing implementation?\r\n\r\nThere's also a library libpkcs11wrapper.so distributed with the binary only driver package.\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1.  Download Linux drivers from http://trustkeytoken.co.in/ . Unpack the zip and install\r\napt-get install /disks/storage/downloads/TrustKey_linux/wdtokentool-trustkey_3.4.3-1_all.deb\r\n\r\n2. Run getinfo.py\r\n$ _PYKCS11LIB=/usr/lib/WatchData/TRUSTKEY/lib/libwdpkcs_TRUSTKEY.so python getinfo.py_\r\n\r\nNote:\r\nThis only works with driver distributed by the manufacturer, which as you said in the referred issue, is a modification of your CCID driver. I have emailed the manufacturer for the source code of the driver.\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/26", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/26/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/26/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/26/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/26", "id": 287192000, "node_id": "MDU6SXNzdWUyODcxOTIwMDA=", "number": 26, "title": "Session.sign will fill the memory and cause a SIGABRT when data argument is a very big integer", "user": {"login": "gonccalo", "id": 5223817, "node_id": "MDQ6VXNlcjUyMjM4MTc=", "avatar_url": "https://avatars3.githubusercontent.com/u/5223817?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gonccalo", "html_url": "https://github.com/gonccalo", "followers_url": "https://api.github.com/users/gonccalo/followers", "following_url": "https://api.github.com/users/gonccalo/following{/other_user}", "gists_url": "https://api.github.com/users/gonccalo/gists{/gist_id}", "starred_url": "https://api.github.com/users/gonccalo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gonccalo/subscriptions", "organizations_url": "https://api.github.com/users/gonccalo/orgs", "repos_url": "https://api.github.com/users/gonccalo/repos", "events_url": "https://api.github.com/users/gonccalo/events{/privacy}", "received_events_url": "https://api.github.com/users/gonccalo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-01-09T18:50:31Z", "updated_at": "2018-01-11T14:39:32Z", "closed_at": "2018-01-11T14:39:32Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: 1.4.4\r\n* Python version: 3.6.4\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nWhen calling the `session.sign(key, data)` function if the `data` argument is a integer then a `ckbytelist` will be created using `ckbytelist(data)` [[1]](https://github.com/LudovicRousseau/PyKCS11/blob/f332518d4f61ba301e39e4ecc03d6ba5ca0f8410/PyKCS11/__init__.py#L1039), this will create a `ckbytelist` of size `data`[[2]](https://github.com/LudovicRousseau/PyKCS11/blob/f332518d4f61ba301e39e4ecc03d6ba5ca0f8410/PyKCS11/__init__.py#L77) so if `data` is a very big number the process will crash with \r\n```\r\nterminate called after throwing an instance of 'std::bad_alloc'\r\n  what():  std::bad_alloc\r\n\r\nProcess finished with exit code 134 (interrupted by signal 6: SIGABRT)\r\n```\r\n#### Steps for reproducing this issue:\r\n\r\nI can reproduce the error with\r\n```python\r\nimport PyKCS11\r\nif __name__ == '__main__':\r\n    bignum = 24401231876787445786723\r\n    print(bignum.bit_length())\r\n    pk = PyKCS11.PyKCS11Lib()\r\n    pk.load(\"libpteidpkcs11.so\")\r\n    slots = pk.getSlotList()\r\n    if len(slots) < 1:\r\n        exit()\r\n    session = pk.openSession(slots[0])\r\n    key = session.findObjects(template=((PyKCS11.CKA_LABEL, \"CITIZEN AUTHENTICATION KEY\"),\r\n                                             (PyKCS11.CKA_CLASS, PyKCS11.CKO_PRIVATE_KEY),\r\n                                             (PyKCS11.CKA_KEY_TYPE, PyKCS11.CKK_RSA)))[0]\r\n    mec = PyKCS11.Mechanism(PyKCS11.CKM_SHA1_RSA_PKCS, \"\")\r\n    signed = session.sign(key, bignum, mec)\r\n    print(signed)\r\n```\r\n \r\nTo fix this maybe you can check if `data` is a integer in the sign function and convert it to a byte array or just throw an exception.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/25", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/25/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/25/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/25", "id": 276519577, "node_id": "MDU6SXNzdWUyNzY1MTk1Nzc=", "number": 25, "title": "Problem invoking RSA_PSS_Mechanism()", "user": {"login": "esuzukiaws", "id": 27483314, "node_id": "MDQ6VXNlcjI3NDgzMzE0", "avatar_url": "https://avatars1.githubusercontent.com/u/27483314?v=4", "gravatar_id": "", "url": "https://api.github.com/users/esuzukiaws", "html_url": "https://github.com/esuzukiaws", "followers_url": "https://api.github.com/users/esuzukiaws/followers", "following_url": "https://api.github.com/users/esuzukiaws/following{/other_user}", "gists_url": "https://api.github.com/users/esuzukiaws/gists{/gist_id}", "starred_url": "https://api.github.com/users/esuzukiaws/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/esuzukiaws/subscriptions", "organizations_url": "https://api.github.com/users/esuzukiaws/orgs", "repos_url": "https://api.github.com/users/esuzukiaws/repos", "events_url": "https://api.github.com/users/esuzukiaws/events{/privacy}", "received_events_url": "https://api.github.com/users/esuzukiaws/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2017-11-24T05:44:52Z", "updated_at": "2018-05-18T09:35:02Z", "closed_at": "2018-05-18T09:35:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: 1.4.4\r\n* Python version: 3.4.3\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen and what _did_ happen.\r\n\r\nI have created a script that signs data using the CKM_SHA*_RSA_PKCS_PSS mechanisms. Since these mechanisms require an structure to be configured, I'm configuring them using RSA_PSS_Mechanism like this:\r\n\r\n```python\r\nif (not args.mechanism) or (args.mechanism == \"CKM_SHA1_RSA_PKCS_PSS\"):`\r\n    mecha = CKM_SHA1_RSA_PKCS_PSS`\r\n    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA_1, mgf=CKG_MGF1_SHA1, sLen=20)`\r\nelif args.mechanism == \"CKM_SHA224_RSA_PKCS_PSS\":\r\n    mecha = CKM_SHA224_RSA_PKCS_PSS\r\n    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA224, mgf=CKG_MGF1_SHA224, sLen=20)\r\nelif args.mechanism == \"CKM_SHA256_RSA_PKCS_PSS\":\r\n    mecha = CKM_SHA256_RSA_PKCS_PSS\r\n    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA256, mgf=CKG_MGF1_SHA256, sLen=20)\r\nelif args.mechanism == \"CKM_SHA384_RSA_PKCS_PSS\":\r\n    mecha = CKM_SHA384_RSA_PKCS_PSS\r\n    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA384, mgf=CKG_MGF1_SHA384, sLen=20)\r\nelif args.mechanism == \"CKM_SHA512_RSA_PKCS_PSS\":\r\n    mecha = CKM_SHA512_RSA_PKCS_PSS\r\n    mecha_parameters = RSA_PSS_Mechanism(CKM_SHA512, mgf=CKG_MGF1_SHA512, sLen=20)\r\nelse:\r\n    print(\"An invalid mechanism was specified. Aborting...\")\r\n    sys.exit(1)\r\n```\r\nThen, I effectively sign the data like this:\r\n\r\n```python\r\nsignature = sess.sign(privateKey, data, Mechanism(mecha, mecha_parameters))\r\n```\r\n\r\nWhen I run the script, it gives me an error like this:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"./sign_data_using_RSA_PKCS_PSS_algorithms.py\", line 113, in <module>\r\n    signature = sess.sign(privateKey, data, Mechanism(mecha, mecha_parameters))\r\n  File \"/home/ec2-user/.local/lib/python3.4/site-packages/PyKCS11/__init__.py\", line 723, in __init__\r\n    self._param = ckbytelist(param)\r\n  File \"/home/ec2-user/.local/lib/python3.4/site-packages/PyKCS11/__init__.py\", line 112, in __init__\r\n    raise PyKCS11.PyKCS11Error(-3, text=type(data))\r\nPyKCS11.PyKCS11Error: Unknown format (<class 'PyKCS11.RSA_PSS_Mechanism'>)\r\n```\r\n\r\nAm I doing anything wrong?\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/24", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/24/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/24/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/24/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/24", "id": 270712152, "node_id": "MDU6SXNzdWUyNzA3MTIxNTI=", "number": 24, "title": "error when installing PykCS11 with pip on a win7 64bit", "user": {"login": "kazacube-hsmaiti", "id": 32460729, "node_id": "MDQ6VXNlcjMyNDYwNzI5", "avatar_url": "https://avatars1.githubusercontent.com/u/32460729?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kazacube-hsmaiti", "html_url": "https://github.com/kazacube-hsmaiti", "followers_url": "https://api.github.com/users/kazacube-hsmaiti/followers", "following_url": "https://api.github.com/users/kazacube-hsmaiti/following{/other_user}", "gists_url": "https://api.github.com/users/kazacube-hsmaiti/gists{/gist_id}", "starred_url": "https://api.github.com/users/kazacube-hsmaiti/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kazacube-hsmaiti/subscriptions", "organizations_url": "https://api.github.com/users/kazacube-hsmaiti/orgs", "repos_url": "https://api.github.com/users/kazacube-hsmaiti/repos", "events_url": "https://api.github.com/users/kazacube-hsmaiti/events{/privacy}", "received_events_url": "https://api.github.com/users/kazacube-hsmaiti/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 537984179, "node_id": "MDU6TGFiZWw1Mzc5ODQxNzk=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/help%20wanted", "name": "help wanted", "color": "128A0C", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 13, "created_at": "2017-11-02T16:07:54Z", "updated_at": "2018-09-14T09:18:50Z", "closed_at": "2018-09-14T09:18:50Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version:1.4.4\r\n* Python version:2.7\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nDescribe what you _expected_ should happen and what _did_ happen.\r\nI tried to install PyKsc11 on a windows7 64bit using pip\r\nbut i got this error: \r\n\"\"\"\"\"\"\"\"\r\n**error c2039 'data' is not a member of std::vector with \r\n[\r\n_Ty= unsigned char\r\n]**\r\n\"\"\"\"\"\"\"\"\r\ni'm using python 2.7 with a Microsoft Visual C++ Compiler v9. \r\n#### Steps for reproducing this issue:\r\n\r\n1. pip install Pykcs11\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/22", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/22/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/22/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/22", "id": 268354667, "node_id": "MDU6SXNzdWUyNjgzNTQ2Njc=", "number": 22, "title": "(py3) C_Login pin should accept bytes", "user": {"login": "mon", "id": 3398021, "node_id": "MDQ6VXNlcjMzOTgwMjE=", "avatar_url": "https://avatars0.githubusercontent.com/u/3398021?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mon", "html_url": "https://github.com/mon", "followers_url": "https://api.github.com/users/mon/followers", "following_url": "https://api.github.com/users/mon/following{/other_user}", "gists_url": "https://api.github.com/users/mon/gists{/gist_id}", "starred_url": "https://api.github.com/users/mon/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mon/subscriptions", "organizations_url": "https://api.github.com/users/mon/orgs", "repos_url": "https://api.github.com/users/mon/repos", "events_url": "https://api.github.com/users/mon/events{/privacy}", "received_events_url": "https://api.github.com/users/mon/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-10-25T11:01:17Z", "updated_at": "2017-11-07T08:37:45Z", "closed_at": "2017-11-07T08:37:45Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Python 3.6.1, Win32.\r\nMy dongle pin is derived from a hash and is thus binary. In python 3, none of the decoders I tried a) work without hitting invalid chars or b) provide the correct login pin to the Cryptoki library.\r\n\r\nAttempting to pass bytes results in:\r\n```    session.login(pin, CKU_USER)\r\n  File \"C:\\Python36\\lib\\site-packages\\PyKCS11\\__init__.py\", line 901, in login\r\n    rv = self.lib.C_Login(self.session, user_type, pin)\r\n  File \"C:\\Python36\\lib\\site-packages\\PyKCS11\\LowLevel.py\", line 1789, in C_Login\r\n    return _LowLevel.CPKCS11Lib_C_Login(self, hSession, userType, pPin)\r\nTypeError: in method 'CPKCS11Lib_C_Login', argument 4 of type 'char *'\r\n```\r\nNote that this works fine in Python 2.\r\n\r\nI'm not sure how to modify the declarations to treat `bytes` as a `char*`", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/21", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/21/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/21/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/21/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/21", "id": 260986018, "node_id": "MDU6SXNzdWUyNjA5ODYwMTg=", "number": 21, "title": "X509 Certificate import issue/question", "user": {"login": "xzr", "id": 2156119, "node_id": "MDQ6VXNlcjIxNTYxMTk=", "avatar_url": "https://avatars0.githubusercontent.com/u/2156119?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xzr", "html_url": "https://github.com/xzr", "followers_url": "https://api.github.com/users/xzr/followers", "following_url": "https://api.github.com/users/xzr/following{/other_user}", "gists_url": "https://api.github.com/users/xzr/gists{/gist_id}", "starred_url": "https://api.github.com/users/xzr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xzr/subscriptions", "organizations_url": "https://api.github.com/users/xzr/orgs", "repos_url": "https://api.github.com/users/xzr/repos", "events_url": "https://api.github.com/users/xzr/events{/privacy}", "received_events_url": "https://api.github.com/users/xzr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-09-27T14:01:59Z", "updated_at": "2017-09-27T16:18:38Z", "closed_at": "2017-09-27T16:18:38Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: 1.4.2\r\n* Python version: 2.7.12\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nHi, I was following the example described in https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/genkeypair_import_cert.py\r\n\r\nI'm currently using SoftHSM2 for testing, but the end result will be running against a Safenet HSM. \r\n\r\nI've followed the steps in the example, created a certificate using pyca/cryptography and converting that with PyASN1. However it seems that the certificate doesn't get created on the token.\r\n\r\nKey creation and signing the certificate with the key seems to work fine.\r\n\r\nIs the certificate supposed to get stored on the token when the template is created?\r\nOr maybe there's a function call I'm missing here? \r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/18", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/18/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/18/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/18", "id": 258918307, "node_id": "MDU6SXNzdWUyNTg5MTgzMDc=", "number": 18, "title": "C_Unwrap SIGTERM with Thales nShield ", "user": {"login": "maestrx", "id": 6150459, "node_id": "MDQ6VXNlcjYxNTA0NTk=", "avatar_url": "https://avatars0.githubusercontent.com/u/6150459?v=4", "gravatar_id": "", "url": "https://api.github.com/users/maestrx", "html_url": "https://github.com/maestrx", "followers_url": "https://api.github.com/users/maestrx/followers", "following_url": "https://api.github.com/users/maestrx/following{/other_user}", "gists_url": "https://api.github.com/users/maestrx/gists{/gist_id}", "starred_url": "https://api.github.com/users/maestrx/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/maestrx/subscriptions", "organizations_url": "https://api.github.com/users/maestrx/orgs", "repos_url": "https://api.github.com/users/maestrx/repos", "events_url": "https://api.github.com/users/maestrx/events{/privacy}", "received_events_url": "https://api.github.com/users/maestrx/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-09-19T18:26:41Z", "updated_at": "2017-09-20T22:11:30Z", "closed_at": "2017-09-20T21:11:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: PyKCS11-1.4.3\r\n* Python version: python-2.7.5-58.el7.x86_64\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nWhen doing C_Unwrap with 3DES key using handle (previously unwrapped in HSM) and DES2 key provided as input I get SIGTERM. When debuggin this issue with gdb I am getting this trace:\r\n\r\nProgram received signal SIGSEGV, Segmentation fault.\r\n_[Switching to Thread 0x7fffee91d700 (LWP 8849)]\r\nunwrap_secret (sess=0x7fffe8003240, realslot=0x7b40d0, wrappingkeyobjdata=0xa75aa641, pMechanism=0x7fffe800a650, mechdata=0x0, pWrappedKey=0xc <Address 0xc out of bounds>, ulWrappedKeyLen=16,\r\n    pTemplate=0x7fffe800e2c0, ulAttributeCount=15, phKey=0x7fffee91be58) at ../keymanunwrap.c:614\r\n614     ../keymanunwrap.c: No such file or directory._\r\n\r\nI interpret it as if the python wrapper over the PKCS so library(LowLevel.so) would not be able to properly pass the pointer to the pWrappedKey, as the value passed (0xc) does not look like a valid pointer :)\r\n#### Steps for reproducing this issue:\r\n\r\nI can provide you with the python code I used, I  cannot provide you with Thales HSM's nor the Thales PKCS libraries. I'm willing to collaborate with debugging of this issue.\r\n\r\nBTW: Thanks for this great project, I was looking to implement it using ctypes, but your code is saving plenty of headaches and time :) Great job done mate :)\r\n\r\nThanks\r\nVit", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/16", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/16/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/16/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/16", "id": 250767930, "node_id": "MDU6SXNzdWUyNTA3Njc5MzA=", "number": 16, "title": "CKR_ARGUMENTS_BAD When Running rsa_encrypt.py", "user": {"login": "jordan-wright", "id": 1317288, "node_id": "MDQ6VXNlcjEzMTcyODg=", "avatar_url": "https://avatars3.githubusercontent.com/u/1317288?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jordan-wright", "html_url": "https://github.com/jordan-wright", "followers_url": "https://api.github.com/users/jordan-wright/followers", "following_url": "https://api.github.com/users/jordan-wright/following{/other_user}", "gists_url": "https://api.github.com/users/jordan-wright/gists{/gist_id}", "starred_url": "https://api.github.com/users/jordan-wright/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jordan-wright/subscriptions", "organizations_url": "https://api.github.com/users/jordan-wright/orgs", "repos_url": "https://api.github.com/users/jordan-wright/repos", "events_url": "https://api.github.com/users/jordan-wright/events{/privacy}", "received_events_url": "https://api.github.com/users/jordan-wright/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-08-16T21:37:47Z", "updated_at": "2017-08-16T22:37:38Z", "closed_at": "2017-08-16T22:11:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: master\r\n* Python version: 3.6.2\r\n\r\n#### Please describe your issue in as much detail as possible:\r\n\r\n*Expected* \r\n\r\nWhen I run the `rsa_encrypt.py` script using SoftHSM as the backend HSM emulator, I expect to see the test string successfully encrypted using the `RSAOAEPMechanism` mechanism.\r\n\r\n*Results*\r\n\r\nI receive the following Traceback:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"rsa_encrypt.py\", line 60, in <module>\r\n    ciphertext = session.encrypt(pubKey, pt, mech)\r\n  File \"/usr/local/lib/python3.6/site-packages/PyKCS11/__init__.py\", line 1092, in encrypt\r\n    raise PyKCS11Error(rv)\r\nPyKCS11.PyKCS11Error: CKR_ARGUMENTS_BAD (0x00000007)\r\n```\r\n\r\nIt's unclear what's causing the error. At first, I thought that maybe it'd be a bad parameter when setting up the mechanism, but that _seems_ fine.\r\n\r\n#### Steps for reproducing this issue:\r\n\r\nFor reference, I'm using [this Docker](https://hub.docker.com/r/bruienne/pykcs11_softhsm2/) image we created which installs Python, SoftHSM, and PyKSC11 from the master branch.\r\n\r\n1. Setup SoftHSM with a PIN\r\n\r\n```\r\nsofthsm2-util --init-token --slot 0 --label test --pin 1234\r\n```\r\n\r\n2. Execute `rsa_encrypt.py`\r\n\r\nAs a note, if we remove the `RSAOAEPMechanism` mechanism and instead rely on the default `MechanismRSAPKCS1`, it works just fine.\r\n\r\nAny help would be greatly appreciated!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/15", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/15/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/15/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/15", "id": 240419330, "node_id": "MDU6SXNzdWUyNDA0MTkzMzA=", "number": 15, "title": "run_test.py is not packaged in the release tarball", "user": {"login": "Jakuje", "id": 2694489, "node_id": "MDQ6VXNlcjI2OTQ0ODk=", "avatar_url": "https://avatars3.githubusercontent.com/u/2694489?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Jakuje", "html_url": "https://github.com/Jakuje", "followers_url": "https://api.github.com/users/Jakuje/followers", "following_url": "https://api.github.com/users/Jakuje/following{/other_user}", "gists_url": "https://api.github.com/users/Jakuje/gists{/gist_id}", "starred_url": "https://api.github.com/users/Jakuje/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Jakuje/subscriptions", "organizations_url": "https://api.github.com/users/Jakuje/orgs", "repos_url": "https://api.github.com/users/Jakuje/repos", "events_url": "https://api.github.com/users/Jakuje/events{/privacy}", "received_events_url": "https://api.github.com/users/Jakuje/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-07-04T13:21:35Z", "updated_at": "2017-07-04T20:09:08Z", "closed_at": "2017-07-04T20:09:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n* PyKCS11 version: 1.4.3\r\n* Python version: 2.7.13\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nThe latest tarball downloaded from sourceforge\r\nhttps://sourceforge.net/projects/pkcs11wrap/files/pykcs11/pykcs11-1.4.3/\r\n```\r\n$ tar -t -f PyKCS11-1.4.3.tar.gz  | grep run_test\r\n[no result]\r\n```\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. Download the tarball from SF\r\n2. List the files tar -t -f PyKCS11-1.4.3.tar.gz  | grep run_test\r\n3. See there is no `run_test.py` file\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/14", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/14/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/14/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/14/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/14", "id": 237260421, "node_id": "MDU6SXNzdWUyMzcyNjA0MjE=", "number": 14, "title": "signing with CKM_RSA_PKCS_PSS fails with \"Segmentation fault\"", "user": {"login": "l-g-s", "id": 29577008, "node_id": "MDQ6VXNlcjI5NTc3MDA4", "avatar_url": "https://avatars3.githubusercontent.com/u/29577008?v=4", "gravatar_id": "", "url": "https://api.github.com/users/l-g-s", "html_url": "https://github.com/l-g-s", "followers_url": "https://api.github.com/users/l-g-s/followers", "following_url": "https://api.github.com/users/l-g-s/following{/other_user}", "gists_url": "https://api.github.com/users/l-g-s/gists{/gist_id}", "starred_url": "https://api.github.com/users/l-g-s/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/l-g-s/subscriptions", "organizations_url": "https://api.github.com/users/l-g-s/orgs", "repos_url": "https://api.github.com/users/l-g-s/repos", "events_url": "https://api.github.com/users/l-g-s/events{/privacy}", "received_events_url": "https://api.github.com/users/l-g-s/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-06-20T15:53:15Z", "updated_at": "2017-06-22T19:38:41Z", "closed_at": "2017-06-22T19:38:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "#### Your system information\r\n\r\n* PyKCS11 version: nCipher PKCS#11 2.19.1, cryptokiVersion: 2.1\r\n* Python version: 2.7.6\r\n\r\n#### Please describe your issue in as much detail as possible:\r\nI was trying to sign some data using a RSA-4096 key and **CKM_RSA_PKCS_PSS** as mechanism but calling of sign() function aborts with a \"Segmentation fault\":\r\n\r\n```\r\ndata = \"a932d16a6b0a383b873aa73e7bbe56631924775abd69e8ec5265d5719a4df37d9300f3217aaf078139b4fbe403c3800e\" # SHA-384 of a file\r\nsignature = session.sign(privKey, binascii.unhexlify(data), PyKCS11.Mechanism(PyKCS11.CKM_RSA_PKCS_PSS)) \r\n```\r\n\r\nThe behavior is the same for all CKM_RSA_PKCS_PSS mechanisms (e.g. also for CKM_SHA384_RSA_PKCS_PSS) although they get listed for the selected slot by getMechanismList(). \r\n\r\nUsing a \"regular\" CKM_RSA_PKCS mechanism returns the signature as expected -- it only fails when PSS padding is involved.\r\n\r\nAccording to the API it should be possible to provide specific parameters for a mechanism but I'm not sure how to properly make the call:\r\n\r\n`mechanism = PyKCS11.Mechanism(PyKCS11.CKM_RSA_PKCS_PSS, param=(PyKCS11.CKM_SHA384, PyKCS11.CKG_MGF1_SHA384, 48))`\r\n\r\n...fails with \"ValueError: byte must be in range(0, 256)\" (as CKM_SHA384 equals 608). \r\nI noticed that LowLevel.py defines a class \"CK_RSA_PKCS_OAEP_PARAMS\" (with attributes \"hashAlg\", \"mgf\" and others) but I couldn't find a class for \"CK_RSA_PKCS_PSS_PARAMS\" (with expected attributes \"hashAlg\", \"mgf\" and \"sLen\".\r\n\r\n**Could it be that support for PSS is missing or is it me who's using it wrong?**\r\n\r\n#### Steps for reproducing this issue:\r\n\r\n1. get list of available slots: getSlotList()\r\n2. read slot info to find a slot with CKF_TOKEN_PRESENT: getSlotInfo(slot)\r\n3. open appropriate session: session = pkcs11.openSession(slot, PyKCS11.CKF_SERIAL_SESSION)\r\n4. find CKO_PRIVATE_KEY object: privKey = session.findObjects(...)[0]\r\n5. call signing function as described above\r\n\r\nBest Regards\r\nLars", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/13", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/13/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/13/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/13", "id": 233884974, "node_id": "MDU6SXNzdWUyMzM4ODQ5NzQ=", "number": 13, "title": "Support CK_INVALID_HANDLE as hKey parameter of C_EncryptInit", "user": {"login": "31z4", "id": 3657959, "node_id": "MDQ6VXNlcjM2NTc5NTk=", "avatar_url": "https://avatars2.githubusercontent.com/u/3657959?v=4", "gravatar_id": "", "url": "https://api.github.com/users/31z4", "html_url": "https://github.com/31z4", "followers_url": "https://api.github.com/users/31z4/followers", "following_url": "https://api.github.com/users/31z4/following{/other_user}", "gists_url": "https://api.github.com/users/31z4/gists{/gist_id}", "starred_url": "https://api.github.com/users/31z4/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/31z4/subscriptions", "organizations_url": "https://api.github.com/users/31z4/orgs", "repos_url": "https://api.github.com/users/31z4/repos", "events_url": "https://api.github.com/users/31z4/events{/privacy}", "received_events_url": "https://api.github.com/users/31z4/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-06-06T13:04:39Z", "updated_at": "2017-06-07T05:01:06Z", "closed_at": "2017-06-07T05:01:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "Now `C_EncryptInit` expects only `CK_OBJECT_HANDLE` instance as its `hKey` paramterer. But some vendors implementations allow and expect `CK_INVALID_HANDLE ` there. Supporting it would be great!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/12", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/12/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/12/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/12", "id": 228710718, "node_id": "MDU6SXNzdWUyMjg3MTA3MTg=", "number": 12, "title": "Session over scriptruntime", "user": {"login": "jonas99y", "id": 17616996, "node_id": "MDQ6VXNlcjE3NjE2OTk2", "avatar_url": "https://avatars0.githubusercontent.com/u/17616996?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jonas99y", "html_url": "https://github.com/jonas99y", "followers_url": "https://api.github.com/users/jonas99y/followers", "following_url": "https://api.github.com/users/jonas99y/following{/other_user}", "gists_url": "https://api.github.com/users/jonas99y/gists{/gist_id}", "starred_url": "https://api.github.com/users/jonas99y/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jonas99y/subscriptions", "organizations_url": "https://api.github.com/users/jonas99y/orgs", "repos_url": "https://api.github.com/users/jonas99y/repos", "events_url": "https://api.github.com/users/jonas99y/events{/privacy}", "received_events_url": "https://api.github.com/users/jonas99y/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-05-15T13:14:28Z", "updated_at": "2017-05-15T16:02:55Z", "closed_at": "2017-05-15T16:02:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is it somehow possible to keep a session object form pkcs11.openSession( ) over the runtime of a script?\r\nSo the session.login is only called once.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/11", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/11/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/11/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/11", "id": 228602745, "node_id": "MDU6SXNzdWUyMjg2MDI3NDU=", "number": 11, "title": "CKR_FUNCTION_NOT_SUPPORTED error", "user": {"login": "mlakewood", "id": 663390, "node_id": "MDQ6VXNlcjY2MzM5MA==", "avatar_url": "https://avatars0.githubusercontent.com/u/663390?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mlakewood", "html_url": "https://github.com/mlakewood", "followers_url": "https://api.github.com/users/mlakewood/followers", "following_url": "https://api.github.com/users/mlakewood/following{/other_user}", "gists_url": "https://api.github.com/users/mlakewood/gists{/gist_id}", "starred_url": "https://api.github.com/users/mlakewood/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mlakewood/subscriptions", "organizations_url": "https://api.github.com/users/mlakewood/orgs", "repos_url": "https://api.github.com/users/mlakewood/repos", "events_url": "https://api.github.com/users/mlakewood/events{/privacy}", "received_events_url": "https://api.github.com/users/mlakewood/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-05-15T04:18:38Z", "updated_at": "2017-05-15T16:05:59Z", "closed_at": "2017-05-15T16:05:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi all,\r\n\r\nIm using a YubiKey with a PIV on it and when using this library it seems to be able to get at the YubiKey but then fails with something like this.\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"test.py\", line 58, in <module>\r\n    (pubKey, privKey) = session.generateKeyPair(pubTemplate, privTemplate)\r\n  File \"/Users/mlakewood/projects/yubi_key/venv/lib/python3.5/site-packages/PyKCS11/__init__.py\", line 1321, in generateKeyPair\r\n    raise PyKCS11Error(rv)\r\nPyKCS11.PyKCS11Error: CKR_FUNCTION_NOT_SUPPORTED (0x00000054)\r\n```\r\n\r\nI've tried both the encrypt.py sample and the generate.py sample and both as soon as they try to do some kind of cryptography fail with the above. Interestingly it will accept the PIN, so the communication is there.\r\n\r\nAny help would be greatly appreciated.\r\n\r\nCheers\r\n\r\nMark", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/10", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/10/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/10/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/10", "id": 227358096, "node_id": "MDU6SXNzdWUyMjczNTgwOTY=", "number": 10, "title": "Slot list empty using Luna SA PKCS#11 lib", "user": {"login": "xzr", "id": 2156119, "node_id": "MDQ6VXNlcjIxNTYxMTk=", "avatar_url": "https://avatars0.githubusercontent.com/u/2156119?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xzr", "html_url": "https://github.com/xzr", "followers_url": "https://api.github.com/users/xzr/followers", "following_url": "https://api.github.com/users/xzr/following{/other_user}", "gists_url": "https://api.github.com/users/xzr/gists{/gist_id}", "starred_url": "https://api.github.com/users/xzr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xzr/subscriptions", "organizations_url": "https://api.github.com/users/xzr/orgs", "repos_url": "https://api.github.com/users/xzr/repos", "events_url": "https://api.github.com/users/xzr/events{/privacy}", "received_events_url": "https://api.github.com/users/xzr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2017-05-09T12:59:03Z", "updated_at": "2017-05-09T16:55:51Z", "closed_at": "2017-05-09T14:40:50Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hi, I'm running into a problem where I'm not able to retrieve the slot list through PyKCS11 when using the PKCS#11 library provided by Safenet Luna SA HSM. \r\n\r\nUsing pkcs11-tool from the OpenSC project and loading up the lib, the call works fine and all slots get listed. \r\n\r\nWhen I do the same with PyKCS11 I get an empty list in return.\r\n\r\nI used pkcs11-spy library to debug the issue and I've attached the log comparison\r\n\r\n```\r\nPyKCS#11\r\n\r\n*************** OpenSC PKCS#11 spy *****************\r\nLoaded: \"/usr/safenet/lunaclient/lib/libCryptoki2_64.so\"\r\n\r\n0: C_GetFunctionList\r\n2017-05-09 15:47:33.415\r\nReturned:  0 CKR_OK\r\n\r\n1: C_GetInfo\r\n2017-05-09 15:47:33.415\r\n[out] pInfo: \r\n      cryptokiVersion:         2.20\r\n      manufacturerID:         ' SafeNet, Inc.                  '\r\n      flags:                   0\r\n      libraryDescription:     ' Chrystoki                      '\r\n      libraryVersion:          5.1\r\nReturned:  0 CKR_OK\r\n\r\n2: C_GetSlotList\r\n2017-05-09 15:49:28.662\r\n[in] tokenPresent = 0x0\r\n[out] pSlotList: \r\n[out] *pulCount = 0x0\r\nReturned:  0 CKR_OK\r\n\r\n\r\n\r\n\r\n\r\npkcs11-tool\r\n\r\n*************** OpenSC PKCS#11 spy *****************\r\nLoaded: \"/usr/safenet/lunaclient/lib/libCryptoki2_64.so\"\r\n\r\n0: C_GetFunctionList\r\n2017-05-09 15:40:37.891\r\nReturned:  0 CKR_OK\r\n\r\n1: C_Initialize\r\n2017-05-09 15:40:37.891\r\n[in] pInitArgs = (nil)\r\nReturned:  0 CKR_OK\r\n\r\n2: C_GetSlotList\r\n2017-05-09 15:40:38.959\r\n[in] tokenPresent = 0x0\r\n[out] pSlotList: \r\nCount is 4\r\n[out] *pulCount = 0x4\r\nReturned:  0 CKR_OK\r\n\r\n3: C_GetSlotList\r\n2017-05-09 15:40:38.959\r\n[in] tokenPresent = 0x0\r\n[out] pSlotList: \r\nSlot 0\r\nSlot 1\r\nSlot 2\r\nSlot 3\r\n[out] *pulCount = 0x4\r\nReturned:  0 CKR_OK\r\n```\r\nIt would seem that the library in question requires C_Initialize to be called, before the library can be queried. Is there a way I can instruct PyKCS11 to make that call (didn't find it in the api at least)?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/9", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/9/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/9/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/9", "id": 225354062, "node_id": "MDU6SXNzdWUyMjUzNTQwNjI=", "number": 9, "title": "AES CBC encryption issue", "user": {"login": "alxnik", "id": 2570042, "node_id": "MDQ6VXNlcjI1NzAwNDI=", "avatar_url": "https://avatars1.githubusercontent.com/u/2570042?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alxnik", "html_url": "https://github.com/alxnik", "followers_url": "https://api.github.com/users/alxnik/followers", "following_url": "https://api.github.com/users/alxnik/following{/other_user}", "gists_url": "https://api.github.com/users/alxnik/gists{/gist_id}", "starred_url": "https://api.github.com/users/alxnik/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alxnik/subscriptions", "organizations_url": "https://api.github.com/users/alxnik/orgs", "repos_url": "https://api.github.com/users/alxnik/repos", "events_url": "https://api.github.com/users/alxnik/events{/privacy}", "received_events_url": "https://api.github.com/users/alxnik/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 537984179, "node_id": "MDU6TGFiZWw1Mzc5ODQxNzk=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/help%20wanted", "name": "help wanted", "color": "128A0C", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 17, "created_at": "2017-04-30T21:00:22Z", "updated_at": "2017-06-05T13:32:21Z", "closed_at": "2017-06-05T13:32:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\nI'm trying to work with AES CBC (and GCM) encryption using the following code. No matter what I try, I cannot pass the IV to the encrypting function, instead I always get \"TypeError: unsupported CK_MECHANISM Parameter type.\". I have tried passing a string object, a byte object as well as a list of single bytes. Size doesn't seem to matter.\r\n\r\nAny ideas?\r\n\r\n```\r\nAESKeyTemplate =  [\r\n        (CKA_CLASS, CKO_SECRET_KEY),\r\n        (CKA_KEY_TYPE, CKK_AES),\r\n        (CKA_TOKEN, CK_TRUE),\r\n        (CKA_PRIVATE, CK_FALSE),\r\n        (CKA_ENCRYPT, CK_TRUE),\r\n        (CKA_DECRYPT, CK_TRUE),\r\n        (CKA_SIGN, CK_FALSE),\r\n        (CKA_VERIFY, CK_FALSE),\r\n        (CKA_VALUE_LEN, 32),\r\n        (CKA_LABEL, \"TestAESKey\"),\r\n        (CKA_ID, (0x01,))\r\n    ]\r\n\r\nAESKey = session.generateKey(AESKeyTemplate)\r\n\r\nsession.encrypt(AESKey, Data, PyKCS11.Mechanism(CKM_AES_CBC, '1234567812345678'))\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/8", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/8/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/8/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/8", "id": 225187721, "node_id": "MDU6SXNzdWUyMjUxODc3MjE=", "number": 8, "title": "init_token low level sample fails at C_Login(SO)", "user": {"login": "DavidTWhite", "id": 136652, "node_id": "MDQ6VXNlcjEzNjY1Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/136652?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DavidTWhite", "html_url": "https://github.com/DavidTWhite", "followers_url": "https://api.github.com/users/DavidTWhite/followers", "following_url": "https://api.github.com/users/DavidTWhite/following{/other_user}", "gists_url": "https://api.github.com/users/DavidTWhite/gists{/gist_id}", "starred_url": "https://api.github.com/users/DavidTWhite/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DavidTWhite/subscriptions", "organizations_url": "https://api.github.com/users/DavidTWhite/orgs", "repos_url": "https://api.github.com/users/DavidTWhite/repos", "events_url": "https://api.github.com/users/DavidTWhite/events{/privacy}", "received_events_url": "https://api.github.com/users/DavidTWhite/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-04-28T20:41:15Z", "updated_at": "2017-04-28T20:52:04Z", "closed_at": "2017-04-28T20:52:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "Output: \r\n\r\nLoad of /usr/lib/pkcs11/libopencryptoki.so: True\r\nC_GetInfo: 0x0\r\nLibrary manufacturerID: IBM                             \r\nC_GetSlotList(NULL): 0x0\r\n\tAvailable Slots: 2\r\n\tC_SlotInfo(): 0x0\r\n\tC_GetTokenInfo(): 0x0\r\n\t\tTokenInfo: Label=IBM PKCS#11 TPM Token           , ManufacturerID=IBM Corp.                       \r\n\t\tTokenInfo: flags=0x880045, Model=TPM v1.1 Token  \r\n\tC_InitToken(): 0xa0\r\n\tC_GetTokenInfo(): 0x0\r\n\t\tTokenInfo: Label=IBM PKCS#11 TPM Token           , ManufacturerID=IBM Corp.                       \r\n\t\tTokenInfo: flags=0x880045, Model=TPM v1.1 Token  \r\n\tC_OpenSession(): 0x0\r\n\t\tSession:<PyKCS11.LowLevel.CK_SESSION_HANDLE; proxy of <Swig Object of type 'CK_SESSION_HANDLE *' at 0xb771a7e8> >\r\n\tC_GetSessionInfo(): 0x0\r\n\t\tSessionInfo: state=0x2, flags=0x6\r\n\tC_Login(SO): 0xa0\r\n\tC_InitPIN(): 0x101\r\n\tC_Logout(SO): 0x101\r\n\tC_GetTokenInfo(): 0x0\r\n\t\tTokenInfo: Label=IBM PKCS#11 TPM Token           , ManufacturerID=IBM Corp.                       \r\n\t\tTokenInfo: flags=0x980045, Model=TPM v1.1 Token  \r\nC_Login(USER): 0x102\r\nC_Logout(USER): 0x101\r\nC_CloseSession(): 0x0\r\nC_Finalize(): 0x0\r\nTrue\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/6", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/6/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/6/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/6", "id": 209395822, "node_id": "MDU6SXNzdWUyMDkzOTU4MjI=", "number": 6, "title": "Don't install on GNU/Linux", "user": {"login": "RastaDill", "id": 12989870, "node_id": "MDQ6VXNlcjEyOTg5ODcw", "avatar_url": "https://avatars0.githubusercontent.com/u/12989870?v=4", "gravatar_id": "", "url": "https://api.github.com/users/RastaDill", "html_url": "https://github.com/RastaDill", "followers_url": "https://api.github.com/users/RastaDill/followers", "following_url": "https://api.github.com/users/RastaDill/following{/other_user}", "gists_url": "https://api.github.com/users/RastaDill/gists{/gist_id}", "starred_url": "https://api.github.com/users/RastaDill/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/RastaDill/subscriptions", "organizations_url": "https://api.github.com/users/RastaDill/orgs", "repos_url": "https://api.github.com/users/RastaDill/repos", "events_url": "https://api.github.com/users/RastaDill/events{/privacy}", "received_events_url": "https://api.github.com/users/RastaDill/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-02-22T09:24:07Z", "updated_at": "2017-02-26T22:10:29Z", "closed_at": "2017-02-26T22:10:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello. I'm trying install PyKCS11 on GNU/Linux, but when i do 'make build':\r\nsrc/pykcs11_wrap.cpp:171:21: \u0444\u0430\u0442\u0430\u043b\u044c\u043d\u0430\u044f \u043e\u0448\u0438\u0431\u043a\u0430: Python.h: \u041d\u0435\u0442 \u0442\u0430\u043a\u043e\u0433\u043e \u0444\u0430\u0439\u043b\u0430 \u0438\u043b\u0438 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430\r\n # include <Python.h>\r\n                     ^\r\n\u043a\u043e\u043c\u043f\u0438\u043b\u044f\u0446\u0438\u044f \u043f\u0440\u0435\u0440\u0432\u0430\u043d\u0430.\r\nerror: command 'gcc' failed with exit status 1\r\nMakefile:11: \u043e\u0448\u0438\u0431\u043a\u0430 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f \u0440\u0435\u0446\u0435\u043f\u0442\u0430 \u0434\u043b\u044f \u0446\u0435\u043b\u0438 \u00abbuild-stamp\u00bb\r\nmake: *** [build-stamp] \u041e\u0448\u0438\u0431\u043a\u0430 1\r\n\r\nI think this bug only Windows. How fixed this?\r\nThanks.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/5", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/5/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/5/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/5", "id": 208793825, "node_id": "MDU6SXNzdWUyMDg3OTM4MjU=", "number": 5, "title": "Support C_EncryptUpdate, etc in high-level API", "user": {"login": "danni", "id": 129472, "node_id": "MDQ6VXNlcjEyOTQ3Mg==", "avatar_url": "https://avatars3.githubusercontent.com/u/129472?v=4", "gravatar_id": "", "url": "https://api.github.com/users/danni", "html_url": "https://github.com/danni", "followers_url": "https://api.github.com/users/danni/followers", "following_url": "https://api.github.com/users/danni/following{/other_user}", "gists_url": "https://api.github.com/users/danni/gists{/gist_id}", "starred_url": "https://api.github.com/users/danni/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/danni/subscriptions", "organizations_url": "https://api.github.com/users/danni/orgs", "repos_url": "https://api.github.com/users/danni/repos", "events_url": "https://api.github.com/users/danni/events{/privacy}", "received_events_url": "https://api.github.com/users/danni/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 537984178, "node_id": "MDU6TGFiZWw1Mzc5ODQxNzg=", "url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-02-20T06:25:15Z", "updated_at": "2018-05-18T11:23:26Z", "closed_at": "2018-05-18T11:23:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "When doing large, symmetric encryptions it would be handy to have a method that consumed a generator and output a generator fed through C_EncryptUpdate/C_EncryptFinal etc.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/4", "repository_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11", "labels_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/4/comments", "events_url": "https://api.github.com/repos/LudovicRousseau/PyKCS11/issues/4/events", "html_url": "https://github.com/LudovicRousseau/PyKCS11/issues/4", "id": 208793367, "node_id": "MDU6SXNzdWUyMDg3OTMzNjc=", "number": 4, "title": "getSlotList() doesn't accept tokenPresent", "user": {"login": "danni", "id": 129472, "node_id": "MDQ6VXNlcjEyOTQ3Mg==", "avatar_url": "https://avatars3.githubusercontent.com/u/129472?v=4", "gravatar_id": "", "url": "https://api.github.com/users/danni", "html_url": "https://github.com/danni", "followers_url": "https://api.github.com/users/danni/followers", "following_url": "https://api.github.com/users/danni/following{/other_user}", "gists_url": "https://api.github.com/users/danni/gists{/gist_id}", "starred_url": "https://api.github.com/users/danni/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/danni/subscriptions", "organizations_url": "https://api.github.com/users/danni/orgs", "repos_url": "https://api.github.com/users/danni/repos", "events_url": "https://api.github.com/users/danni/events{/privacy}", "received_events_url": "https://api.github.com/users/danni/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-02-20T06:21:43Z", "updated_at": "2017-02-27T10:09:06Z", "closed_at": "2017-02-27T10:09:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "It would be useful to be able to request the `tokenPresent` parameter for `getSlotList()`", "performed_via_github_app": null, "score": 1.0}]}