{"total_count": 44, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/pympler/pympler/issues/113", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/113/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/113/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/113/events", "html_url": "https://github.com/pympler/pympler/issues/113", "id": 665125956, "node_id": "MDU6SXNzdWU2NjUxMjU5NTY=", "number": 113, "title": "Python3 support?", "user": {"login": "apiszcz", "id": 1430861, "node_id": "MDQ6VXNlcjE0MzA4NjE=", "avatar_url": "https://avatars2.githubusercontent.com/u/1430861?v=4", "gravatar_id": "", "url": "https://api.github.com/users/apiszcz", "html_url": "https://github.com/apiszcz", "followers_url": "https://api.github.com/users/apiszcz/followers", "following_url": "https://api.github.com/users/apiszcz/following{/other_user}", "gists_url": "https://api.github.com/users/apiszcz/gists{/gist_id}", "starred_url": "https://api.github.com/users/apiszcz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/apiszcz/subscriptions", "organizations_url": "https://api.github.com/users/apiszcz/orgs", "repos_url": "https://api.github.com/users/apiszcz/repos", "events_url": "https://api.github.com/users/apiszcz/events{/privacy}", "received_events_url": "https://api.github.com/users/apiszcz/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-24T12:09:22Z", "updated_at": "2020-07-25T10:40:11Z", "closed_at": "2020-07-25T10:40:11Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is python3 supported, import works, get_objects returns values. summary.summarize cause program to terminate with no messages. Thanks for creating this capability.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/107", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/107/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/107/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/107/events", "html_url": "https://github.com/pympler/pympler/issues/107", "id": 595813284, "node_id": "MDU6SXNzdWU1OTU4MTMyODQ=", "number": 107, "title": "django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library", "user": {"login": "zengoma", "id": 6479268, "node_id": "MDQ6VXNlcjY0NzkyNjg=", "avatar_url": "https://avatars1.githubusercontent.com/u/6479268?v=4", "gravatar_id": "", "url": "https://api.github.com/users/zengoma", "html_url": "https://github.com/zengoma", "followers_url": "https://api.github.com/users/zengoma/followers", "following_url": "https://api.github.com/users/zengoma/following{/other_user}", "gists_url": "https://api.github.com/users/zengoma/gists{/gist_id}", "starred_url": "https://api.github.com/users/zengoma/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/zengoma/subscriptions", "organizations_url": "https://api.github.com/users/zengoma/orgs", "repos_url": "https://api.github.com/users/zengoma/repos", "events_url": "https://api.github.com/users/zengoma/events{/privacy}", "received_events_url": "https://api.github.com/users/zengoma/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-04-07T11:57:36Z", "updated_at": "2020-05-24T07:57:55Z", "closed_at": "2020-05-24T07:57:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Django: v3.05\r\nPython: v3.7.4\r\n\r\n```shell\r\ndjango.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:\r\nadmin_list\r\nadmin_modify\r\nadmin_urls\r\ncache\r\ndebugger_tags\r\ndjmoney\r\nhighlighting\r\ni18n\r\nindent_text\r\nl10n\r\nlog\r\nrest_framework\r\nstatic\r\nsyntax_color\r\ntruncate_letters\r\ntz\r\nwidont\r\n[07/Apr/2020 13:26:07] \"GET /__debug__/render_panel/?store_id=a2d2b2bce44743b083f9d38f41c5bd74&panel_id=MemoryPanel HTTP/1.1\" 500 275650\r\n```\r\nThe following error is due to the fact that `{% load static from staticfiles %}` must be replaced with `{% load_static %}` over here in order to support Django 3.0\r\n\r\nhttps://github.com/pympler/pympler/blob/bfc2f957831c96a39acedba25fb0da99c5a37805/pympler/templates/memory_panel.html#L1", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/104", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/104/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/104/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/104/events", "html_url": "https://github.com/pympler/pympler/issues/104", "id": 551091917, "node_id": "MDU6SXNzdWU1NTEwOTE5MTc=", "number": 104, "title": "ERROR in test_background_monitoring (tracker.test_classtracker.SnapshotTestCase) with Python 3.9.0a2", "user": {"login": "rathann", "id": 5873507, "node_id": "MDQ6VXNlcjU4NzM1MDc=", "avatar_url": "https://avatars0.githubusercontent.com/u/5873507?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rathann", "html_url": "https://github.com/rathann", "followers_url": "https://api.github.com/users/rathann/followers", "following_url": "https://api.github.com/users/rathann/following{/other_user}", "gists_url": "https://api.github.com/users/rathann/gists{/gist_id}", "starred_url": "https://api.github.com/users/rathann/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rathann/subscriptions", "organizations_url": "https://api.github.com/users/rathann/orgs", "repos_url": "https://api.github.com/users/rathann/repos", "events_url": "https://api.github.com/users/rathann/events{/privacy}", "received_events_url": "https://api.github.com/users/rathann/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-01-16T22:27:33Z", "updated_at": "2020-01-28T19:27:39Z", "closed_at": "2020-01-28T19:27:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\n======================================================================\r\nERROR: test_background_monitoring (tracker.test_classtracker.SnapshotTestCase)\r\nTest background monitoring.\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/builddir/build/BUILD/Pympler-0.8/test/tracker/test_classtracker.py\", line 237, in test_background_monitoring\r\n    self.tracker.stop_periodic_snapshots()\r\n  File \"/builddir/build/BUILDROOT/python-Pympler-0.8-1.fc32.x86_64/usr/lib/python3.9/site-packages/pympler/classtracker.py\", line 514, in stop_periodic_snapshots\r\n    if self._periodic_thread and self._periodic_thread.isAlive():\r\nAttributeError: 'PeriodicThread' object has no attribute 'isAlive'\r\n\r\n======================================================================\r\nERROR: test_background_monitoring (tracker.test_classtracker.SnapshotTestCase)\r\nTest background monitoring.\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/builddir/build/BUILD/Pympler-0.8/test/tracker/test_classtracker.py\", line 151, in tearDown\r\n    self.tracker.stop_periodic_snapshots()\r\n  File \"/builddir/build/BUILDROOT/python-Pympler-0.8-1.fc32.x86_64/usr/lib/python3.9/site-packages/pympler/classtracker.py\", line 514, in stop_periodic_snapshots\r\n    if self._periodic_thread and self._periodic_thread.isAlive():\r\nAttributeError: 'PeriodicThread' object has no attribute 'isAlive'\r\n```\r\n\r\nSee https://docs.python.org/3.9/whatsnew/3.9.html#removed\r\n\r\n\"The `isAlive()` method of `threading.Thread` has been removed. It was deprecated since Python 3.8. Use `is_alive()` instead.\"\r\n\r\nThis was found in early testing of Python 3.9 in Fedora rawhide: https://bugzilla.redhat.com/show_bug.cgi?id=1791963 .", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/102", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/102/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/102/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/102/events", "html_url": "https://github.com/pympler/pympler/issues/102", "id": 492710401, "node_id": "MDU6SXNzdWU0OTI3MTA0MDE=", "number": 102, "title": "test_generator (asizeof.test_asizeof.TypesTest) fails with Python 3.8.0b4", "user": {"login": "rathann", "id": 5873507, "node_id": "MDQ6VXNlcjU4NzM1MDc=", "avatar_url": "https://avatars0.githubusercontent.com/u/5873507?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rathann", "html_url": "https://github.com/rathann", "followers_url": "https://api.github.com/users/rathann/followers", "following_url": "https://api.github.com/users/rathann/following{/other_user}", "gists_url": "https://api.github.com/users/rathann/gists{/gist_id}", "starred_url": "https://api.github.com/users/rathann/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rathann/subscriptions", "organizations_url": "https://api.github.com/users/rathann/orgs", "repos_url": "https://api.github.com/users/rathann/repos", "events_url": "https://api.github.com/users/rathann/events{/privacy}", "received_events_url": "https://api.github.com/users/rathann/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-09-12T10:07:08Z", "updated_at": "2019-11-10T21:57:04Z", "closed_at": "2019-11-10T21:57:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\n$ python3 test/runtest.py -pre-install -verbose 4 test/asizeof\r\nPython 3.8.0b4 (default, Aug 30 2019, 00:00:00) \r\n64-bit [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]\r\n\r\nTest dirs: ['test/asizeof']\r\n\r\ntest_all (asizeof.test_asizeof.AsizeofDemos)\r\nTest all=True example ... ok\r\ntest_basic (asizeof.test_asizeof.AsizeofDemos)\r\nTest basic examples ... ok\r\ntest_class (asizeof.test_asizeof.AsizeofDemos)\r\nTest class and instance examples ... ok\r\ntest_code (asizeof.test_asizeof.AsizeofDemos)\r\nTest code examples ... ok\r\ntest_dict (asizeof.test_asizeof.AsizeofDemos)\r\nTest dict and UserDict examples ... ok\r\ntest_generator (asizeof.test_asizeof.AsizeofDemos)\r\nTest generator examples ... ok\r\ntest_globals (asizeof.test_asizeof.AsizeofDemos)\r\nTest globals examples ... ok\r\ntest_iterator (asizeof.test_asizeof.AsizeofDemos)\r\nTest iterator examples ... ok\r\ntest_locals (asizeof.test_asizeof.AsizeofDemos)\r\nTest locals examples ... ok\r\ntest_long (asizeof.test_asizeof.AsizeofDemos)\r\nTest int and long examples ... ok\r\ntest_pairs (asizeof.test_asizeof.AsizeofDemos)\r\nTest key pair examples ... ok\r\ntest_slots (asizeof.test_asizeof.AsizeofDemos)\r\nTest slots examples ... ok\r\ntest_stack (asizeof.test_asizeof.AsizeofDemos)\r\nTest stack examples ... ok\r\ntest_sys_mods (asizeof.test_asizeof.AsizeofDemos)\r\nTest sys.modules examples ... ok\r\ntest_typedefs (asizeof.test_asizeof.AsizeofDemos)\r\nTest showing all basic _typedefs ... ok\r\ntest_adict (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.adict() ... ok\r\ntest_asized (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.asized() ... ok\r\ntest_asized_detail (asizeof.test_asizeof.FunctionTest) ... ok\r\ntest_asized_format (asizeof.test_asizeof.FunctionTest)\r\nTest Asized.format(depth=x) ... ok\r\ntest_asizeof (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.asizeof() ... ok\r\ntest_asizer (asizeof.test_asizeof.FunctionTest)\r\nTest Asizer properties. ... ok\r\ntest_asizer_limit (asizeof.test_asizeof.FunctionTest)\r\nTest limit setting for Asizer. ... ok\r\ntest_asizesof (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.asizesof() ... ok\r\ntest_basicsize (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.basicsize() ... ok\r\ntest_exclude_types (asizeof.test_asizeof.FunctionTest)\r\nTest Asizer.exclude_types(). ... ok\r\ntest_itemsize (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.itemsize() ... ok\r\ntest_leng (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.leng() ... ok\r\ntest_private_slots (asizeof.test_asizeof.FunctionTest) ... ok\r\ntest_refs (asizeof.test_asizeof.FunctionTest)\r\nTest asizeof.refs() ... ok\r\ntest_array (asizeof.test_asizeof.TypesTest) ... ok\r\ntest_classes (asizeof.test_asizeof.TypesTest)\r\nTest sizing class objects and instances ... ok\r\ntest_closure (asizeof.test_asizeof.TypesTest)\r\nTest sizing closures. ... ok\r\ntest_enumerate (asizeof.test_asizeof.TypesTest)\r\nTest sizing enumerators. ... ok\r\ntest_exception (asizeof.test_asizeof.TypesTest)\r\nTest sizing exceptions. ... ok\r\ntest_generator (asizeof.test_asizeof.TypesTest)\r\nTest integrity of sized generator ... FAIL\r\ntest_ignore_frame (asizeof.test_asizeof.TypesTest)\r\nTest whether reference cycles are created ... ok\r\ntest_methods (asizeof.test_asizeof.TypesTest)\r\nTest sizing methods and functions ... ok\r\ntest_namedtuple (asizeof.test_asizeof.TypesTest)\r\nTest values are included but namedtuple __dict__ isn't. ... ok\r\ntest_numpy_array (asizeof.test_asizeof.TypesTest)\r\nTest sizing numpy arrays. ... ok\r\ntest_os_stat (asizeof.test_asizeof.TypesTest)\r\nTest sizing os.stat and os.statvfs objects. ... ok\r\ntest_special_objects (asizeof.test_asizeof.TypesTest)\r\nTest sizing special objects. ... ok\r\ntest_weakref (asizeof.test_asizeof.TypesTest)\r\nTest sizing weak references. ... ok\r\n\r\n======================================================================\r\nFAIL: test_generator (asizeof.test_asizeof.TypesTest)\r\nTest integrity of sized generator\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/builddir/build/BUILD/Pympler-0.7/test/asizeof/test_asizeof.py\", line 78, in test_generator\r\n    self.assertEqual(s1, s2)\r\nAssertionError: 1000 != 1168\r\n\r\n----------------------------------------------------------------------\r\nRan 42 tests in 1.958s\r\n\r\nFAILED (failures=1)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/101", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/101/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/101/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/101/events", "html_url": "https://github.com/pympler/pympler/issues/101", "id": 469764457, "node_id": "MDU6SXNzdWU0Njk3NjQ0NTc=", "number": 101, "title": "asizeof does not properly size Shapely geometries", "user": {"login": "kannes", "id": 7661092, "node_id": "MDQ6VXNlcjc2NjEwOTI=", "avatar_url": "https://avatars3.githubusercontent.com/u/7661092?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kannes", "html_url": "https://github.com/kannes", "followers_url": "https://api.github.com/users/kannes/followers", "following_url": "https://api.github.com/users/kannes/following{/other_user}", "gists_url": "https://api.github.com/users/kannes/gists{/gist_id}", "starred_url": "https://api.github.com/users/kannes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kannes/subscriptions", "organizations_url": "https://api.github.com/users/kannes/orgs", "repos_url": "https://api.github.com/users/kannes/repos", "events_url": "https://api.github.com/users/kannes/events{/privacy}", "received_events_url": "https://api.github.com/users/kannes/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-07-18T13:17:20Z", "updated_at": "2019-07-22T09:01:43Z", "closed_at": "2019-07-22T09:01:43Z", "author_association": "NONE", "active_lock_reason": null, "body": "Now I don't know if \"C objects\" are in scope of this wonderful project but since numpy is explicitly mentioned I thought I could really use it on any other module.\r\n\r\nI would love to use it for some memory investigations in a project using the https://github.com/Toblerity/Shapely module. *From what I know* that uses GEOS in the background which is a C library. \r\n\r\n```\r\n>>> from pympler import asizeof\r\n>>> from shapely.geometry import Point, MultiPoint\r\n>>> point = Point(0, 0)\r\n>>> asizeof.asizeof(point)\r\n440\r\n>>> many_points = [Point(0, 0) for _ in range(1000)]\r\n>>> asizeof.asizeof(many_points)\r\n209264\r\n>>> multipoint = MultiPoint(many_points)  # aggregate the 1000 points in one multi-geometry\r\n>>> asizeof.asizeof(multipoint)\r\n440\r\n```\r\n\r\nThe actual memory used for the `multipoint` object should be closer to the size of the `many_points` object. It definitely can't be 440 bytes.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/98", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/98/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/98/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/98/events", "html_url": "https://github.com/pympler/pympler/issues/98", "id": 454797266, "node_id": "MDU6SXNzdWU0NTQ3OTcyNjY=", "number": 98, "title": "summarize seems to cut off type string ending", "user": {"login": "laundmo", "id": 24855949, "node_id": "MDQ6VXNlcjI0ODU1OTQ5", "avatar_url": "https://avatars2.githubusercontent.com/u/24855949?v=4", "gravatar_id": "", "url": "https://api.github.com/users/laundmo", "html_url": "https://github.com/laundmo", "followers_url": "https://api.github.com/users/laundmo/followers", "following_url": "https://api.github.com/users/laundmo/following{/other_user}", "gists_url": "https://api.github.com/users/laundmo/gists{/gist_id}", "starred_url": "https://api.github.com/users/laundmo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/laundmo/subscriptions", "organizations_url": "https://api.github.com/users/laundmo/orgs", "repos_url": "https://api.github.com/users/laundmo/repos", "events_url": "https://api.github.com/users/laundmo/events{/privacy}", "received_events_url": "https://api.github.com/users/laundmo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2019-06-11T16:46:48Z", "updated_at": "2019-11-10T21:57:04Z", "closed_at": "2019-11-10T21:57:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "when using summarize together with muppy.get_objects() on python 3.6, the summarize result seems to cut off type strings.\r\n\r\nfor example a normal type string representation should look like this: `<class 'str'>` but when using summary.summarize i get `<class 'str` with the `'>` missing.\r\n\r\nalthough this may not seem like a important issue, it is very confusing to someone expecting a complete type string. \r\n\r\npersonally i spent 30 minutes searching through my own code until figuring out that \r\n1. this is done by summarize for some reason\r\n2. none of the actuall type name is cut off (afaik)\r\n\r\ni would try to fix this myself but i cant seem to find where this cut off happens.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/97", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/97/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/97/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/97/events", "html_url": "https://github.com/pympler/pympler/issues/97", "id": 445200296, "node_id": "MDU6SXNzdWU0NDUyMDAyOTY=", "number": 97, "title": "dict not included in SummaryTracker.print_diff()", "user": {"login": "daveisfera", "id": 1686193, "node_id": "MDQ6VXNlcjE2ODYxOTM=", "avatar_url": "https://avatars3.githubusercontent.com/u/1686193?v=4", "gravatar_id": "", "url": "https://api.github.com/users/daveisfera", "html_url": "https://github.com/daveisfera", "followers_url": "https://api.github.com/users/daveisfera/followers", "following_url": "https://api.github.com/users/daveisfera/following{/other_user}", "gists_url": "https://api.github.com/users/daveisfera/gists{/gist_id}", "starred_url": "https://api.github.com/users/daveisfera/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/daveisfera/subscriptions", "organizations_url": "https://api.github.com/users/daveisfera/orgs", "repos_url": "https://api.github.com/users/daveisfera/repos", "events_url": "https://api.github.com/users/daveisfera/events{/privacy}", "received_events_url": "https://api.github.com/users/daveisfera/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2019-05-16T23:27:11Z", "updated_at": "2019-11-12T19:54:08Z", "closed_at": "2019-11-12T19:54:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "`dict` variables and the values inside of them are not output when calling `print_diff()` with a `SummaryTracker`. Here's an example that demonstrates the behavior:\r\n\r\n```\r\nfrom pympler import tracker\r\nfrom datetime import datetime\r\n\r\ntr = tracker.SummaryTracker()\r\nprint('start')\r\ntr.print_diff()\r\n\r\nprint('empty list')\r\nlist_test = []\r\ntr.print_diff()\r\n\r\nprint('add to list')\r\nlist_test.append(datetime.now())\r\ntr.print_diff()\r\n\r\nprint('empty dict')\r\ndict_test = {}\r\ntr.print_diff()\r\n\r\nprint('add to dict')\r\ndict_test['test'] = datetime.now()\r\ntr.print_diff()\r\n```\r\n\r\nTested with 2.7.15 and 3.7.2 and neither output the any information about `dict`", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/96", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/96/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/96/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/96/events", "html_url": "https://github.com/pympler/pympler/issues/96", "id": 441164007, "node_id": "MDU6SXNzdWU0NDExNjQwMDc=", "number": 96, "title": "Compatibility with Django debug toolbar 2(?)", "user": {"login": "therefromhere", "id": 197540, "node_id": "MDQ6VXNlcjE5NzU0MA==", "avatar_url": "https://avatars2.githubusercontent.com/u/197540?v=4", "gravatar_id": "", "url": "https://api.github.com/users/therefromhere", "html_url": "https://github.com/therefromhere", "followers_url": "https://api.github.com/users/therefromhere/followers", "following_url": "https://api.github.com/users/therefromhere/following{/other_user}", "gists_url": "https://api.github.com/users/therefromhere/gists{/gist_id}", "starred_url": "https://api.github.com/users/therefromhere/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/therefromhere/subscriptions", "organizations_url": "https://api.github.com/users/therefromhere/orgs", "repos_url": "https://api.github.com/users/therefromhere/repos", "events_url": "https://api.github.com/users/therefromhere/events{/privacy}", "received_events_url": "https://api.github.com/users/therefromhere/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2019-05-07T10:43:05Z", "updated_at": "2019-11-12T19:57:00Z", "closed_at": "2019-11-12T19:57:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Just a heads up, Django debug toolbar is changing how panels are processed to be more like new-style middleware, presumably for an upcoming 2.0 release (and also dropping Python 2 support).\r\n\r\nAs a result, Pympler panel is broken vs current Django debug toolbar master, it hits this error \"'NoneType' object has no attribute 'get'\" because `debug_toolbar/middleware.py` expects process_request to return a response object.\r\n\r\nUsing:\r\n\r\ndjango debug toolbar master (https://github.com/jazzband/django-debug-toolbar/commit/b650a33bb02651903540d726704a9143c73eda0a)\r\nPympler==0.7\r\nDjango==2.2.1\r\n\r\nSee simple example project that hits the bug on all requests: https://github.com/therefromhere/ddt_pympler_bug_example\r\n\r\nNote that this doesn't affect the released version of Django debug toolbar yet.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/83", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/83/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/83/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/83/events", "html_url": "https://github.com/pympler/pympler/issues/83", "id": 397308008, "node_id": "MDU6SXNzdWUzOTczMDgwMDg=", "number": 83, "title": "How to get the size of all the objects including class instances?", "user": {"login": "Seraphli", "id": 1586755, "node_id": "MDQ6VXNlcjE1ODY3NTU=", "avatar_url": "https://avatars1.githubusercontent.com/u/1586755?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Seraphli", "html_url": "https://github.com/Seraphli", "followers_url": "https://api.github.com/users/Seraphli/followers", "following_url": "https://api.github.com/users/Seraphli/following{/other_user}", "gists_url": "https://api.github.com/users/Seraphli/gists{/gist_id}", "starred_url": "https://api.github.com/users/Seraphli/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Seraphli/subscriptions", "organizations_url": "https://api.github.com/users/Seraphli/orgs", "repos_url": "https://api.github.com/users/Seraphli/repos", "events_url": "https://api.github.com/users/Seraphli/events{/privacy}", "received_events_url": "https://api.github.com/users/Seraphli/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2019-01-09T10:34:44Z", "updated_at": "2019-01-15T17:09:19Z", "closed_at": "2019-01-10T02:57:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "I test the following code, and the summary is incorrect. `a` use about 0.8G memory but the summary doesn't contain this information.\r\n```\r\nfrom pympler import muppy, summary, asizeof\r\nimport numpy as np\r\n\r\n\r\nclass A(object):\r\n    def __init__(self):\r\n        self.a = np.empty((10000, 44, 44, 9, 5), dtype=np.uint8)\r\n\r\n\r\n_sum = summary.summarize(muppy.get_objects(include_frames=True))\r\nsummary.print_(_sum)\r\na = A()\r\nprint(asizeof.asizeof(a) / 1024 / 1024 / 1024)\r\n_sum = summary.summarize(muppy.get_objects(include_frames=True))\r\nsummary.print_(_sum)\r\n\r\n```\r\n\r\nOutput:\r\n```\r\n                               types |   # objects |   total size\r\n==================================== | =========== | ============\r\n                         <class 'str |       17530 |      3.12 MB\r\n                        <class 'dict |        2625 |      1.49 MB\r\n                        <class 'code |        6004 |    847.42 KB\r\n                        <class 'type |         712 |    726.35 KB\r\n                         <class 'set |         579 |    196.66 KB\r\n          <class 'wrapper_descriptor |        2140 |    167.19 KB\r\n                       <class 'tuple |        2308 |    153.36 KB\r\n                     <class 'weakref |        1519 |    118.67 KB\r\n                        <class 'list |         695 |    109.71 KB\r\n           <class 'method_descriptor |        1291 |     90.77 KB\r\n  <class 'builtin_function_or_method |        1258 |     88.45 KB\r\n                 <class 'abc.ABCMeta |          81 |     78.57 KB\r\n           <class 'getset_descriptor |         976 |     68.62 KB\r\n                         <class 'int |        2032 |     57.10 KB\r\n                 function (__init__) |         338 |     44.89 KB\r\n0.8113685846328735\r\n                               types |   # objects |   total size\r\n==================================== | =========== | ============\r\n                         <class 'str |       21855 |      3.42 MB\r\n                        <class 'dict |        2626 |      1.49 MB\r\n                        <class 'code |        5999 |    846.72 KB\r\n                        <class 'type |         712 |    726.35 KB\r\n                        <class 'list |        4814 |    499.12 KB\r\n                         <class 'set |         579 |    196.66 KB\r\n          <class 'wrapper_descriptor |        2140 |    167.19 KB\r\n                       <class 'tuple |        2287 |    151.31 KB\r\n                     <class 'weakref |        1519 |    118.67 KB\r\n           <class 'method_descriptor |        1291 |     90.77 KB\r\n  <class 'builtin_function_or_method |        1258 |     88.45 KB\r\n                 <class 'abc.ABCMeta |          81 |     78.57 KB\r\n                         <class 'int |        2779 |     77.52 KB\r\n           <class 'getset_descriptor |         976 |     68.62 KB\r\n                 function (__init__) |         338 |     44.89 KB\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/81", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/81/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/81/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/81/events", "html_url": "https://github.com/pympler/pympler/issues/81", "id": 389039552, "node_id": "MDU6SXNzdWUzODkwMzk1NTI=", "number": 81, "title": "is there an existing way to measure memory use by stack frame?", "user": {"login": "zzzeek", "id": 128223, "node_id": "MDQ6VXNlcjEyODIyMw==", "avatar_url": "https://avatars0.githubusercontent.com/u/128223?v=4", "gravatar_id": "", "url": "https://api.github.com/users/zzzeek", "html_url": "https://github.com/zzzeek", "followers_url": "https://api.github.com/users/zzzeek/followers", "following_url": "https://api.github.com/users/zzzeek/following{/other_user}", "gists_url": "https://api.github.com/users/zzzeek/gists{/gist_id}", "starred_url": "https://api.github.com/users/zzzeek/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/zzzeek/subscriptions", "organizations_url": "https://api.github.com/users/zzzeek/orgs", "repos_url": "https://api.github.com/users/zzzeek/repos", "events_url": "https://api.github.com/users/zzzeek/events{/privacy}", "received_events_url": "https://api.github.com/users/zzzeek/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-12-09T16:33:13Z", "updated_at": "2018-12-11T22:08:31Z", "closed_at": "2018-12-11T22:07:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi there -\r\n\r\npympler is my go-to memory profiler when I am doing that sort of thing.   We have an internal long-running application that folks are having trouble identifying where large memory growth is occurring, and my usual bag of tricks e.g. with pympler, which is using a signal handler to dump out a report of current memory use, is not helping them because the objects that are taking up all the room are just dictionaries that are part of an overall caching system used by the library, e.g. there's no specific class or object we can point towards as the culprit.  \r\n\r\nSo I saw this [blog post](https://info.cloudquant.com/2018/12/numpyleaks/) that is identifying Python memory leaks by linking memory growth to actual stack frames, using some C-level tool called memleax.   They built a custom C module to identify the growth from the memleax side, then send a signal to a handler in Python to identify a callstack.      But looking at this, it seems to me that the complexity of building a C++ library to wrap around some external tool like that (also `memleax` seems to be superseded by `libleak` anyway) to track callstacks is unnecessary, because Python already has sys.settrace().   We can do what memleax does inside the Python process itself, which is, identify callstacks where memory is allocated and then wasn't released some fixed time later.\r\n\r\nthe basic idea is that instead of the usual emphasis on \"find which kinds of classes / objects are using the most memory\", we are instead looking for particular callstacks that are using the most memory and importantly not freeing it up after some interval that we can configure.\r\n\r\nif a tool used sys.settrace() to intercept all frames as they occur, then stored every unit of a program's call stacks inside of a tree structure (e.g. each node in the tree stores the path to a source file and a line number, and the parent of the node is the node that called it), then used pympler to count the memory use of all the objects attached to that specific frame and its descendants (this part might be the hard part where I'm looking for input), we'd have a memory tally for every line of code.  Then if memory has grown for the past N minutes on a particular frame that has not been recovered (each node of the tree would store its last N minutes of memory growth / shrinkage), we dump out that stack to the console.    \r\n\r\nThe idea is this would let us run a program with this extra background thread turned on, and we could literally watch it show us specific source lines that are responsible for memory growth.  since after all what we really need when we are profiling memory are places in the source code that are buggy.\r\n\r\ndoes this make sense and if so has this been done?   or am I inhaling too much eggnog", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/74", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/74/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/74/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/74/events", "html_url": "https://github.com/pympler/pympler/issues/74", "id": 361029965, "node_id": "MDU6SXNzdWUzNjEwMjk5NjU=", "number": 74, "title": "deprecation warning in pympler/asizeof.py", "user": {"login": "wumpus", "id": 2142266, "node_id": "MDQ6VXNlcjIxNDIyNjY=", "avatar_url": "https://avatars1.githubusercontent.com/u/2142266?v=4", "gravatar_id": "", "url": "https://api.github.com/users/wumpus", "html_url": "https://github.com/wumpus", "followers_url": "https://api.github.com/users/wumpus/followers", "following_url": "https://api.github.com/users/wumpus/following{/other_user}", "gists_url": "https://api.github.com/users/wumpus/gists{/gist_id}", "starred_url": "https://api.github.com/users/wumpus/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/wumpus/subscriptions", "organizations_url": "https://api.github.com/users/wumpus/orgs", "repos_url": "https://api.github.com/users/wumpus/repos", "events_url": "https://api.github.com/users/wumpus/events{/privacy}", "received_events_url": "https://api.github.com/users/wumpus/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-09-17T20:26:37Z", "updated_at": "2019-04-06T16:56:25Z", "closed_at": "2019-04-06T16:56:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "/home/lindahl/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pympler/asizeof.py:259: DeprecationWarning: unicode_internal codec has been deprecated\r\n  u = u.encode('unicode-internal')  # see .../Lib/test/test_sys.py\r\n\r\nhttps://docs.python.org/3/library/codecs.html says\r\n\r\nDeprecated since version 3.3: This representation is obsoleted by PEP 393.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/69", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/69/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/69/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/69/events", "html_url": "https://github.com/pympler/pympler/issues/69", "id": 337415914, "node_id": "MDU6SXNzdWUzMzc0MTU5MTQ=", "number": 69, "title": "Wrong results when measuring object that uses __slots__?", "user": {"login": "ivoanjo", "id": 2785847, "node_id": "MDQ6VXNlcjI3ODU4NDc=", "avatar_url": "https://avatars2.githubusercontent.com/u/2785847?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ivoanjo", "html_url": "https://github.com/ivoanjo", "followers_url": "https://api.github.com/users/ivoanjo/followers", "following_url": "https://api.github.com/users/ivoanjo/following{/other_user}", "gists_url": "https://api.github.com/users/ivoanjo/gists{/gist_id}", "starred_url": "https://api.github.com/users/ivoanjo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ivoanjo/subscriptions", "organizations_url": "https://api.github.com/users/ivoanjo/orgs", "repos_url": "https://api.github.com/users/ivoanjo/repos", "events_url": "https://api.github.com/users/ivoanjo/events{/privacy}", "received_events_url": "https://api.github.com/users/ivoanjo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 19, "created_at": "2018-07-02T08:25:45Z", "updated_at": "2018-09-02T11:22:19Z", "closed_at": "2018-09-02T11:22:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello there, and thanks for Pympler!\r\n\r\nWhile doing a few experiments on a class that uses `__slots__` to reduce memory footprint I ran into a few unexpected results.\r\n\r\nTestcase:\r\n\r\n```python\r\nimport sys\r\nprint(sys.version)\r\nfrom pympler import asizeof\r\n\r\nSLOTS = (\"foo\", \"bar\")\r\n\r\nclass Foo(object):\r\n  __slots__ = SLOTS\r\n\r\n  def __init__(self):\r\n    self.foo = SLOTS\r\n    self.bar = SLOTS\r\n\r\nprint(asizeof.asized(Foo(), detail=1).format())\r\nprint(\"Same object? \" + str(Foo().__slots__ is SLOTS))\r\n```\r\n\r\nResults:\r\n\r\n```\r\n3.6.5 (default, Jun 20 2018, 09:33:17) \r\n[GCC 5.4.0 20160609]\r\n<__main__.Foo object at 0x7f143841ac88> size=304 flat=56\r\n    foo size=176 flat=64\r\n    __slots__ size=72 flat=72\r\n    __class__ size=0 flat=0\r\n    bar size=0 flat=0\r\nSame object? True\r\n```\r\n\r\nThree things seem to be wrong in this case:\r\n\r\n* the flat size of `__slots__` is 8 bytes more than the object itself\r\n* the total size of the `Foo` instance does not account for the fact that `foo` and `__slots__` are pointing at the same object\r\n* the flat size of `__slots__` is shown to be the same as the size\r\n\r\nThus, whereas I would expect in this case the total size to be 56 + 176, pympler reports it as 56 + 176 + 72.\r\n\r\nI was able to validate similar results with Python 2.7, so it doesn't seem to be something that may be off in any specific version.\r\n\r\nIs this a pympler bug, or am I missing some important detail on how `__slots__` are actually implemented that causes this?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/67", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/67/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/67/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/67/events", "html_url": "https://github.com/pympler/pympler/issues/67", "id": 328442350, "node_id": "MDU6SXNzdWUzMjg0NDIzNTA=", "number": 67, "title": "Cannot import process due to empty line in /proc/self/status", "user": {"login": "dnlsng", "id": 1486231, "node_id": "MDQ6VXNlcjE0ODYyMzE=", "avatar_url": "https://avatars1.githubusercontent.com/u/1486231?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dnlsng", "html_url": "https://github.com/dnlsng", "followers_url": "https://api.github.com/users/dnlsng/followers", "following_url": "https://api.github.com/users/dnlsng/following{/other_user}", "gists_url": "https://api.github.com/users/dnlsng/gists{/gist_id}", "starred_url": "https://api.github.com/users/dnlsng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dnlsng/subscriptions", "organizations_url": "https://api.github.com/users/dnlsng/orgs", "repos_url": "https://api.github.com/users/dnlsng/repos", "events_url": "https://api.github.com/users/dnlsng/events{/privacy}", "received_events_url": "https://api.github.com/users/dnlsng/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-06-01T09:16:38Z", "updated_at": "2018-09-01T12:45:26Z", "closed_at": "2018-09-01T12:29:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "Trying to import process is failing after updating the kernel on Ubuntu 16.04\r\n\r\n```\r\n$ python3 -c 'from pympler import process'                                                 \r\nTraceback (most recent call last):                                                                                                          \r\n  File \"<string>\", line 1, in <module>                                                                                                      \r\n  File \"/usr/local/lib/python3.5/dist-packages/pympler/process.py\", line 192, in <module>                                                   \r\n    if _ProcessMemoryInfoProc().update():  # pragma: no branch                                                                              \r\n  File \"/usr/local/lib/python3.5/dist-packages/pympler/process.py\", line 63, in __init__                                                    \r\n    self.available = self.update()                                                                                                          \r\n  File \"/usr/local/lib/python3.5/dist-packages/pympler/process.py\", line 147, in update                                                     \r\n    key, value = entry.split(':', 1)                                                                                                        \r\nValueError: not enough values to unpack (expected 2, got 1)\r\n```\r\n```\r\n$ uname -a\r\nLinux prdonkey002 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux\r\n```\r\nThere is now an empty line in the output of `/proc/self/status`. Should empty lines should be ignored?\r\n```\r\n$ cat /proc/self/status\r\nName:   cat\r\nState:  R (running)\r\nTgid:   7428\r\nNgid:   0\r\nPid:    7428\r\nPPid:   4375\r\nTracerPid:      0\r\nUid:    10037   10037   10037   10037\r\nGid:    10037   10037   10037   10037\r\nFDSize: 256\r\nGroups: 10008 10015 10037 20004 35012 35017\r\nNStgid: 7428\r\nNSpid:  7428\r\nNSpgid: 7428\r\nNSsid:  4375\r\nVmPeak:   123504 kB\r\nVmSize:   123504 kB\r\nVmLck:         0 kB\r\nVmPin:         0 kB\r\nVmHWM:       720 kB\r\nVmRSS:       720 kB\r\nVmData:      320 kB\r\nVmStk:       132 kB\r\nVmExe:        48 kB\r\nVmLib:      1944 kB\r\nVmPTE:        44 kB\r\nVmPMD:        12 kB\r\nVmSwap:        0 kB\r\nHugetlbPages:          0 kB\r\nThreads:        1\r\nSigQ:   0/1030577\r\nSigPnd: 0000000000000000\r\nShdPnd: 0000000000000000\r\nSigBlk: 0000000000000000\r\nSigIgn: 0000000000000000\r\nSigCgt: 0000000000000000\r\nCapInh: 0000000000000000\r\nCapPrm: 0000000000000000\r\nCapEff: 0000000000000000\r\nCapBnd: 0000003fffffffff\r\nCapAmb: 0000000000000000\r\nSeccomp:        0\r\n\r\nSpeculation_Store_Bypass:       vulnerable\r\nCpus_allowed:   ffff\r\nCpus_allowed_list:      0-15\r\nMems_allowed:   00000000,00000003\r\nMems_allowed_list:      0-1\r\nvoluntary_ctxt_switches:        0\r\nnonvoluntary_ctxt_switches:     1\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/62", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/62/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/62/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/62/events", "html_url": "https://github.com/pympler/pympler/issues/62", "id": 292200959, "node_id": "MDU6SXNzdWUyOTIyMDA5NTk=", "number": 62, "title": "AttributeError: 'module' object has no attribute '__name__'", "user": {"login": "precious", "id": 128728, "node_id": "MDQ6VXNlcjEyODcyOA==", "avatar_url": "https://avatars2.githubusercontent.com/u/128728?v=4", "gravatar_id": "", "url": "https://api.github.com/users/precious", "html_url": "https://github.com/precious", "followers_url": "https://api.github.com/users/precious/followers", "following_url": "https://api.github.com/users/precious/following{/other_user}", "gists_url": "https://api.github.com/users/precious/gists{/gist_id}", "starred_url": "https://api.github.com/users/precious/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/precious/subscriptions", "organizations_url": "https://api.github.com/users/precious/orgs", "repos_url": "https://api.github.com/users/precious/repos", "events_url": "https://api.github.com/users/precious/events{/privacy}", "received_events_url": "https://api.github.com/users/precious/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-01-28T12:31:31Z", "updated_at": "2018-02-11T08:13:55Z", "closed_at": "2018-02-11T08:13:55Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "In some rare cases it's possible that module object has not attribute `__name__` and the next exception is raised:\r\n```\r\nn [44]: summary.print_(summary.summarize(muppy.get_objects()))\r\n---------------------------------------------------------------------------\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-44-f303f4aef1bc> in <module>()\r\n----> 1 summary.print_(summary.summarize(muppy.get_objects()))\r\n\r\n/usr/lib/python2.7/site-packages/pympler/summary.py in summarize(objects)\r\n    118     total_size = {}\r\n    119     for o in objects:\r\n--> 120         otype = _repr(o)\r\n    121         if otype in count:\r\n    122             count[otype] += 1\r\n\r\n/usr/lib/python2.7/site-packages/pympler/summary.py in _repr(o, verbosity)\r\n    274         if len(representations[t]) < verbosity:\r\n    275             verbosity = len(representations[t]) - 1\r\n--> 276         res = representations[t][verbosity](o)\r\n    277\r\n    278     res = address.sub('', res)\r\n\r\n/usr/lib/python2.7/site-packages/pympler/summary.py in <lambda>(m)\r\n     95     ]\r\n     96     representations[list] = _list\r\n---> 97     module = [lambda m: \"module(%s)\" % m.__name__]\r\n     98     representations[types.ModuleType] = module\r\n     99     _set = [\r\n\r\nAttributeError: 'module' object has no attribute '__name__'\r\n```\r\n\r\nSteps to reproduce:\r\n```\r\nIn [1]: %run test_file.py  # excute any file here\r\n\r\nIn [2]: import gc\r\n\r\nIn [3]: nameless_modules = [o for o in gc.get_objects() if type(o).__name__ == 'module' and not hasattr(o, '__name__')]\r\n\r\nIn [4]: nameless_modules\r\nOut[4]: [<module '?' (built-in)>]\r\n\r\nIn [5]: m = nameless_modules[0]\r\n\r\nIn [6]: m.__name__\r\n---------------------------------------------------------------------------\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-6-c3d23904167a> in <module>()\r\n----> 1 m.__name__\r\n\r\nAttributeError: 'module' object has no attribute '__name__'\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/55", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/55/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/55/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/55/events", "html_url": "https://github.com/pympler/pympler/issues/55", "id": 249138614, "node_id": "MDU6SXNzdWUyNDkxMzg2MTQ=", "number": 55, "title": "KeyError: <class 'django.template.base.Template'>", "user": {"login": "markddavidoff", "id": 1360543, "node_id": "MDQ6VXNlcjEzNjA1NDM=", "avatar_url": "https://avatars3.githubusercontent.com/u/1360543?v=4", "gravatar_id": "", "url": "https://api.github.com/users/markddavidoff", "html_url": "https://github.com/markddavidoff", "followers_url": "https://api.github.com/users/markddavidoff/followers", "following_url": "https://api.github.com/users/markddavidoff/following{/other_user}", "gists_url": "https://api.github.com/users/markddavidoff/gists{/gist_id}", "starred_url": "https://api.github.com/users/markddavidoff/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/markddavidoff/subscriptions", "organizations_url": "https://api.github.com/users/markddavidoff/orgs", "repos_url": "https://api.github.com/users/markddavidoff/repos", "events_url": "https://api.github.com/users/markddavidoff/events{/privacy}", "received_events_url": "https://api.github.com/users/markddavidoff/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2017-08-09T19:37:43Z", "updated_at": "2018-09-02T11:17:35Z", "closed_at": "2018-09-02T11:17:35Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\nTraceback (most recent call last):\r\n  File \"/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py\", line 85, in run\r\n    self.result = application(self.environ, self.start_response)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py\", line 63, in __call__\r\n    return self.application(environ, start_response)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py\", line 157, in __call__\r\n    response = self.get_response(request)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/base.py\", line 124, in get_response\r\n    response = self._middleware_chain(request)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/exception.py\", line 43, in inner\r\n    response = response_for_exception(request, exc)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/exception.py\", line 93, in response_for_exception\r\n    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/exception.py\", line 139, in handle_uncaught_exception\r\n    return debug.technical_500_response(request, *exc_info)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/views/debug.py\", line 84, in technical_500_response\r\n    html = reporter.get_traceback_html()\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/views/debug.py\", line 326, in get_traceback_html\r\n    t = DEBUG_ENGINE.from_string(TECHNICAL_500_TEMPLATE)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/template/engine.py\", line 155, in from_string\r\n    return Template(template_code, engine=self)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py\", line 335, in <lambda>\r\n    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py\", line 310, in _tracker\r\n    _observer_.init(_self_, *args, **kwds)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py\", line 335, in <lambda>\r\n    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py\", line 310, in _tracker\r\n    _observer_.init(_self_, *args, **kwds)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py\", line 335, in <lambda>\r\n    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py\", line 310, in _tracker\r\n    _observer_.init(_self_, *args, **kwds)\r\n  File \"/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py\", line 335, in <lambda>\r\n    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),\r\nKeyError: <class 'django.template.base.Template'>\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/54", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/54/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/54/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/54/events", "html_url": "https://github.com/pympler/pympler/issues/54", "id": 239675633, "node_id": "MDU6SXNzdWUyMzk2NzU2MzM=", "number": 54, "title": "Broken link for documentation", "user": {"login": "tmcclintock", "id": 10226392, "node_id": "MDQ6VXNlcjEwMjI2Mzky", "avatar_url": "https://avatars2.githubusercontent.com/u/10226392?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tmcclintock", "html_url": "https://github.com/tmcclintock", "followers_url": "https://api.github.com/users/tmcclintock/followers", "following_url": "https://api.github.com/users/tmcclintock/following{/other_user}", "gists_url": "https://api.github.com/users/tmcclintock/gists{/gist_id}", "starred_url": "https://api.github.com/users/tmcclintock/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tmcclintock/subscriptions", "organizations_url": "https://api.github.com/users/tmcclintock/orgs", "repos_url": "https://api.github.com/users/tmcclintock/repos", "events_url": "https://api.github.com/users/tmcclintock/events{/privacy}", "received_events_url": "https://api.github.com/users/tmcclintock/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-06-30T04:40:01Z", "updated_at": "2018-02-11T08:52:11Z", "closed_at": "2018-02-11T08:52:11Z", "author_association": "NONE", "active_lock_reason": null, "body": "On the front page this link is given to direct people to documentation: http://packages.python.org/Pympler/\r\n\r\nAs of this posting the link is broken.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/49", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/49/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/49/events", "html_url": "https://github.com/pympler/pympler/issues/49", "id": 214804384, "node_id": "MDU6SXNzdWUyMTQ4MDQzODQ=", "number": 49, "title": "REL: new release?", "user": {"login": "CJ-Wright", "id": 6740689, "node_id": "MDQ6VXNlcjY3NDA2ODk=", "avatar_url": "https://avatars3.githubusercontent.com/u/6740689?v=4", "gravatar_id": "", "url": "https://api.github.com/users/CJ-Wright", "html_url": "https://github.com/CJ-Wright", "followers_url": "https://api.github.com/users/CJ-Wright/followers", "following_url": "https://api.github.com/users/CJ-Wright/following{/other_user}", "gists_url": "https://api.github.com/users/CJ-Wright/gists{/gist_id}", "starred_url": "https://api.github.com/users/CJ-Wright/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/CJ-Wright/subscriptions", "organizations_url": "https://api.github.com/users/CJ-Wright/orgs", "repos_url": "https://api.github.com/users/CJ-Wright/repos", "events_url": "https://api.github.com/users/CJ-Wright/events{/privacy}", "received_events_url": "https://api.github.com/users/CJ-Wright/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-03-16T18:53:18Z", "updated_at": "2017-03-23T21:18:24Z", "closed_at": "2017-03-23T21:18:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "Would it be possible to put out a new release?\r\nIt seems some bugs were fixed that would be very helpful to have tagged.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/48", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/48/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/48/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/48/events", "html_url": "https://github.com/pympler/pympler/issues/48", "id": 212554730, "node_id": "MDU6SXNzdWUyMTI1NTQ3MzA=", "number": 48, "title": "test fails during conda-build", "user": {"login": "CJ-Wright", "id": 6740689, "node_id": "MDQ6VXNlcjY3NDA2ODk=", "avatar_url": "https://avatars3.githubusercontent.com/u/6740689?v=4", "gravatar_id": "", "url": "https://api.github.com/users/CJ-Wright", "html_url": "https://github.com/CJ-Wright", "followers_url": "https://api.github.com/users/CJ-Wright/followers", "following_url": "https://api.github.com/users/CJ-Wright/following{/other_user}", "gists_url": "https://api.github.com/users/CJ-Wright/gists{/gist_id}", "starred_url": "https://api.github.com/users/CJ-Wright/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/CJ-Wright/subscriptions", "organizations_url": "https://api.github.com/users/CJ-Wright/orgs", "repos_url": "https://api.github.com/users/CJ-Wright/repos", "events_url": "https://api.github.com/users/CJ-Wright/events{/privacy}", "received_events_url": "https://api.github.com/users/CJ-Wright/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-03-07T20:50:58Z", "updated_at": "2017-03-24T14:29:06Z", "closed_at": "2017-03-24T14:29:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "I keep getting the following error during the conda build\r\n```python\r\nFAIL: test_flatsize_vs_getsizeof (asizeof.test_asizeof.AsizeofTest)\r\nTest asizeof.flatsize() vs sys.getsizeof()\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/staged-recipes/build_artefacts/pympler_1488917080907/test_tmp/test/asizeof/test_asizeof.py\", line 82, in test_flatsize_vs_getsizeof\r\n    n, e = test_flatsize(failf=self._failf)  # stdf=sys.stderr)\r\n  File \"/staged-recipes/build_artefacts/pympler_1488917080907/test_tmp/test/asizeof/test_asizeof.py\", line 63, in test_flatsize\r\n    a, s, asizeof._nameof(type(o)), _repr(o))\r\n  File \"/staged-recipes/build_artefacts/pympler_1488917080907/test_tmp/test/asizeof/test_asizeof.py\", line 76, in _failf\r\n    self.fail(fmt % args)\r\nAssertionError: 904 vs 984 for type: <class 'asizeof.test_asizeof.T'>\r\n```\r\nCan someone tell me what is going wrong?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/47", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/47/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/47/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/47/events", "html_url": "https://github.com/pympler/pympler/issues/47", "id": 209394235, "node_id": "MDU6SXNzdWUyMDkzOTQyMzU=", "number": 47, "title": "latest release: 2 tests fails", "user": {"login": "Trophime", "id": 1309311, "node_id": "MDQ6VXNlcjEzMDkzMTE=", "avatar_url": "https://avatars3.githubusercontent.com/u/1309311?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Trophime", "html_url": "https://github.com/Trophime", "followers_url": "https://api.github.com/users/Trophime/followers", "following_url": "https://api.github.com/users/Trophime/following{/other_user}", "gists_url": "https://api.github.com/users/Trophime/gists{/gist_id}", "starred_url": "https://api.github.com/users/Trophime/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Trophime/subscriptions", "organizations_url": "https://api.github.com/users/Trophime/orgs", "repos_url": "https://api.github.com/users/Trophime/repos", "events_url": "https://api.github.com/users/Trophime/events{/privacy}", "received_events_url": "https://api.github.com/users/Trophime/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-02-22T09:17:20Z", "updated_at": "2018-02-11T08:14:19Z", "closed_at": "2018-02-11T08:14:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "Just to let you know that 2 tests fail beside the problem with gui test for latest release when building as a package in Debian/testing\r\n\r\n```\r\ntest.muppy.test_tracker (unittest.loader.ModuleImportFailure) ... ERROR\r\n\r\n======================================================================\r\nERROR: test_flatsize_vs_getsizeof (test.asizeof.test_asizeof.AsizeofTest)\r\nTest asizeof.flatsize() vs sys.getsizeof()\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"test/asizeof/test_asizeof.py\", line 82, in test_flatsize_vs_getsizeof\r\n    n, e = test_flatsize(failf=self._failf)  # stdf=sys.stderr)\r\n  File \"test/asizeof/test_asizeof.py\", line 31, in test_flatsize\r\n    t.append(v.type())\r\n  File \"/usr/lib/python2.7/unittest/main.py\", line 95, in __init__\r\n    self.runTests()\r\n  File \"/usr/lib/python2.7/unittest/main.py\", line 234, in runTests\r\n    sys.exit(not self.result.wasSuccessful())\r\nSystemExit: True\r\n\r\n======================================================================\r\nERROR: test.muppy.test_tracker (unittest.loader.ModuleImportFailure)\r\n----------------------------------------------------------------------\r\nImportError: Failed to import test module: test.muppy.test_tracker\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python2.7/unittest/loader.py\", line 254, in _find_tests\r\n    module = self._get_module_from_name(name)\r\n  File \"/usr/lib/python2.7/unittest/loader.py\", line 232, in _get_module_from_name\r\n    __import__(name)\r\n  File \"test/muppy/test_tracker.py\", line 8, in <module>\r\n    from testutils import disable\r\nImportError: No module named testutils\r\n\r\n\r\n----------------------------------------------------------------------\r\nRan 101 tests in 170.602s\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/46", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/46/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/46/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/46/events", "html_url": "https://github.com/pympler/pympler/issues/46", "id": 209380261, "node_id": "MDU6SXNzdWUyMDkzODAyNjE=", "number": 46, "title": "installation get stucks when performing tests", "user": {"login": "Trophime", "id": 1309311, "node_id": "MDQ6VXNlcjEzMDkzMTE=", "avatar_url": "https://avatars3.githubusercontent.com/u/1309311?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Trophime", "html_url": "https://github.com/Trophime", "followers_url": "https://api.github.com/users/Trophime/followers", "following_url": "https://api.github.com/users/Trophime/following{/other_user}", "gists_url": "https://api.github.com/users/Trophime/gists{/gist_id}", "starred_url": "https://api.github.com/users/Trophime/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Trophime/subscriptions", "organizations_url": "https://api.github.com/users/Trophime/orgs", "repos_url": "https://api.github.com/users/Trophime/repos", "events_url": "https://api.github.com/users/Trophime/events{/privacy}", "received_events_url": "https://api.github.com/users/Trophime/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-02-22T08:09:18Z", "updated_at": "2017-04-03T09:07:20Z", "closed_at": "2017-04-03T09:07:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\nI would like to use pympler and eventually package it for Debian/Ubuntu.\r\nTrying to create the package, it gets stuck while performing tests:\r\n```\r\nTest if reference cycles can be viewed. ...\r\n```\r\n\r\ndoes this require something special?\r\nBest", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/41", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/41/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/41/events", "html_url": "https://github.com/pympler/pympler/issues/41", "id": 181255343, "node_id": "MDU6SXNzdWUxODEyNTUzNDM=", "number": 41, "title": "pympler incompatible with tensorflow", "user": {"login": "vladfi1", "id": 691536, "node_id": "MDQ6VXNlcjY5MTUzNg==", "avatar_url": "https://avatars0.githubusercontent.com/u/691536?v=4", "gravatar_id": "", "url": "https://api.github.com/users/vladfi1", "html_url": "https://github.com/vladfi1", "followers_url": "https://api.github.com/users/vladfi1/followers", "following_url": "https://api.github.com/users/vladfi1/following{/other_user}", "gists_url": "https://api.github.com/users/vladfi1/gists{/gist_id}", "starred_url": "https://api.github.com/users/vladfi1/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/vladfi1/subscriptions", "organizations_url": "https://api.github.com/users/vladfi1/orgs", "repos_url": "https://api.github.com/users/vladfi1/repos", "events_url": "https://api.github.com/users/vladfi1/events{/privacy}", "received_events_url": "https://api.github.com/users/vladfi1/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2016-10-05T20:20:15Z", "updated_at": "2017-03-26T22:12:21Z", "closed_at": "2017-03-26T22:12:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "It seems that pympler doesn't work with [tensorflow](https://www.tensorflow.org/), a popular deep learning toolkit. I suspect this has something to do with tensorflow being a python binding to a C++ implementation.\n\n```\n>>> import tensorflow\n>>> from pympler.tracker import SummaryTracker\n>>> tracker = SummaryTracker()\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/home/vlad/.local/lib/python3.5/site-packages/pympler/tracker.py\", line 45, in __init__\n    self.s0 = summary.summarize(muppy.get_objects())\n  File \"/home/vlad/.local/lib/python3.5/site-packages/pympler/muppy.py\", line 37, in get_objects\n    tmp = [o for o in tmp if not isframe(o)]\n  File \"/home/vlad/.local/lib/python3.5/site-packages/pympler/muppy.py\", line 37, in <listcomp>\n    tmp = [o for o in tmp if not isframe(o)]\n  File \"/usr/lib/python3.5/inspect.py\", line 239, in isframe\n    return isinstance(object, types.FrameType)\nReferenceError: weakly-referenced object no longer exists\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/37", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/37/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/37/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/37/events", "html_url": "https://github.com/pympler/pympler/issues/37", "id": 158348932, "node_id": "MDU6SXNzdWUxNTgzNDg5MzI=", "number": 37, "title": "use system bottle", "user": {"login": "rathann", "id": 5873507, "node_id": "MDQ6VXNlcjU4NzM1MDc=", "avatar_url": "https://avatars0.githubusercontent.com/u/5873507?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rathann", "html_url": "https://github.com/rathann", "followers_url": "https://api.github.com/users/rathann/followers", "following_url": "https://api.github.com/users/rathann/following{/other_user}", "gists_url": "https://api.github.com/users/rathann/gists{/gist_id}", "starred_url": "https://api.github.com/users/rathann/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rathann/subscriptions", "organizations_url": "https://api.github.com/users/rathann/orgs", "repos_url": "https://api.github.com/users/rathann/repos", "events_url": "https://api.github.com/users/rathann/events{/privacy}", "received_events_url": "https://api.github.com/users/rathann/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2016-06-03T11:41:38Z", "updated_at": "2017-03-23T21:53:20Z", "closed_at": "2017-03-23T21:53:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "Pympler includes bottle (in `pympler/util/bottle.py`). I patched it to use system-wide bottle module and it seems to work fine (at least the tests pass). Please consider adding support for using the system version of bottle.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/36", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/36/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/36/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/36/events", "html_url": "https://github.com/pympler/pympler/issues/36", "id": 150963749, "node_id": "MDU6SXNzdWUxNTA5NjM3NDk=", "number": 36, "title": "asizeof does not properly size numpy arrays", "user": {"login": "Paul-E", "id": 4206484, "node_id": "MDQ6VXNlcjQyMDY0ODQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/4206484?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Paul-E", "html_url": "https://github.com/Paul-E", "followers_url": "https://api.github.com/users/Paul-E/followers", "following_url": "https://api.github.com/users/Paul-E/following{/other_user}", "gists_url": "https://api.github.com/users/Paul-E/gists{/gist_id}", "starred_url": "https://api.github.com/users/Paul-E/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Paul-E/subscriptions", "organizations_url": "https://api.github.com/users/Paul-E/orgs", "repos_url": "https://api.github.com/users/Paul-E/repos", "events_url": "https://api.github.com/users/Paul-E/events{/privacy}", "received_events_url": "https://api.github.com/users/Paul-E/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-04-25T19:51:21Z", "updated_at": "2016-10-05T07:55:10Z", "closed_at": "2016-10-03T15:22:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "Although numpy is not a part of the python standard library, it is a part of many python developer's standard toolkits. Therefore it seems like it would be useful to properly size numpy arrays. Currently asizeof does not properly size numpy arrays. eg:\n\n```\n>>> import numpy as np\n>>> from pympler import asizeof\n>>> example = np.arange(1000)\n>>> asizeof.asizeof(example)\n80\n```\n\nClearly, an array of 1000 values should take more than 80 bytes of memory.\nFortunately numpy arrays have an \"nbytes\" property that indicates their size, thus\n\n```\n>>> example.nbytes\n8000\n```\n\nIt may be possible to get an accurate idea of numpy array memory usage using this property.\n\nI ran these commands in Python 3.4 with pympler 0.4.3\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/35", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/35/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/35/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/35/events", "html_url": "https://github.com/pympler/pympler/issues/35", "id": 150961265, "node_id": "MDU6SXNzdWUxNTA5NjEyNjU=", "number": 35, "title": "asizeof does not properly size namedtuples", "user": {"login": "Paul-E", "id": 4206484, "node_id": "MDQ6VXNlcjQyMDY0ODQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/4206484?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Paul-E", "html_url": "https://github.com/Paul-E", "followers_url": "https://api.github.com/users/Paul-E/followers", "following_url": "https://api.github.com/users/Paul-E/following{/other_user}", "gists_url": "https://api.github.com/users/Paul-E/gists{/gist_id}", "starred_url": "https://api.github.com/users/Paul-E/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Paul-E/subscriptions", "organizations_url": "https://api.github.com/users/Paul-E/orgs", "repos_url": "https://api.github.com/users/Paul-E/repos", "events_url": "https://api.github.com/users/Paul-E/events{/privacy}", "received_events_url": "https://api.github.com/users/Paul-E/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-04-25T19:42:35Z", "updated_at": "2016-09-04T16:17:23Z", "closed_at": "2016-09-04T16:12:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "If I run asizeof on a normal tuple, I get the following:\n\n```\n>>> from pympler import asizeof\n>>> asizeof.asizeof(list(range(1000)), \"foo\")\n41160\n```\n\nIf I create a named tuple and run asizeof on that object, I don't get the correct size:\n\n```\n>>> from pympler import asizeof\n>>> from collections import namedtuple\n>>> TestTuple = namedtuple(\"TestTuple\", [\"a\", \"b\"])\n>>> asizeof.asizeof(TestTuple(list(range(1000)), \"foo\"))\n120\n```\n\nI believe asizeof should be returning roughly the same values for these calls.\n\nThis output was produced on Python 3.4 using pympler 0.4.3. Perhaps this is related to #10?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/34", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/34/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/34/events", "html_url": "https://github.com/pympler/pympler/issues/34", "id": 144907311, "node_id": "MDU6SXNzdWUxNDQ5MDczMTE=", "number": 34, "title": "Unable to do \"import pympler.muppy\" on PyPy due to AttributeError", "user": {"login": "sakurai-youhei", "id": 721858, "node_id": "MDQ6VXNlcjcyMTg1OA==", "avatar_url": "https://avatars3.githubusercontent.com/u/721858?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sakurai-youhei", "html_url": "https://github.com/sakurai-youhei", "followers_url": "https://api.github.com/users/sakurai-youhei/followers", "following_url": "https://api.github.com/users/sakurai-youhei/following{/other_user}", "gists_url": "https://api.github.com/users/sakurai-youhei/gists{/gist_id}", "starred_url": "https://api.github.com/users/sakurai-youhei/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sakurai-youhei/subscriptions", "organizations_url": "https://api.github.com/users/sakurai-youhei/orgs", "repos_url": "https://api.github.com/users/sakurai-youhei/repos", "events_url": "https://api.github.com/users/sakurai-youhei/events{/privacy}", "received_events_url": "https://api.github.com/users/sakurai-youhei/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-03-31T13:47:54Z", "updated_at": "2016-04-03T09:05:22Z", "closed_at": "2016-04-01T17:39:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "_0.4.3: pympler doesn't work on PyPy_\n\n```\n[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c \"import pympler.muppy\"\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"/opt/pypy/site-packages/pympler/muppy.py\", line 15, in <module>\n    from pympler.asizeof import _Py_TPFLAGS_HAVE_GC\n  File \"/opt/pypy/site-packages/pympler/asizeof.py\", line 206, in <module>\n    _sizeof_Cdigit = long.__itemsize__\nAttributeError: type object 'long' has no attribute '__itemsize__'\n[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy --version\nPython 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Nov 19 2015, 13:36:43)\n[PyPy 4.0.1 with GCC 4.9.2]\n[ec2-user@i-89b56b16 ~]$ git clone https://github.com/pympler/pympler.git\nCloning into 'pympler'...\nremote: Counting objects: 2499, done.\nremote: Compressing objects: 100% (25/25), done.\nremote: Total 2499 (delta 7), reused 0 (delta 0), pack-reused 2473\nReceiving objects: 100% (2499/2499), 975.76 KiB | 558.00 KiB/s, done.\nResolving deltas: 100% (1395/1395), done.\nChecking connectivity... done.\n[ec2-user@i-89b56b16 ~]$ cd pympler/\n[ec2-user@i-89b56b16 pympler]$ /opt/pypy/bin/pypy setup.py try\nrunning try\n/opt/pypy/bin/pypy test/runtest.py -pre-install -verbose 3\nPython 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Nov 19 2015, 13:36:43)\n64-bit [PyPy 4.0.1 with GCC 4.9.2]\n\nTraceback (most recent call last):\n  File \"test/runtest.py\", line 136, in <module>\n    tst, all = suite(dirs, clean=clean, pre=pre, verbose=verbose)\n  File \"test/runtest.py\", line 70, in suite\n    mod = __import__(test, globals(), locals(), [mod])\n  File \"/home/ec2-user/pympler/test/muppy/test_muppy.py\", line 6, in <module>\n    import pympler.muppy\n  File \"/home/ec2-user/pympler/pympler/muppy.py\", line 15, in <module>\n    from pympler.asizeof import _Py_TPFLAGS_HAVE_GC\n  File \"/home/ec2-user/pympler/pympler/asizeof.py\", line 206, in <module>\n    _sizeof_Cdigit = long.__itemsize__\nAttributeError: type object 'long' has no attribute '__itemsize__'\n```\n\n_0.4.2: pympler works on PyPy_\n\n```\n[ec2-user@i-89b56b16 ~]$ sudo /opt/pypy/bin/pypy -m pip install pympler==0.4.2\nCollecting pympler==0.4.2\nInstalling collected packages: pympler\n  Found existing installation: Pympler 0.4.3\n    Uninstalling Pympler-0.4.3:\n      Successfully uninstalled Pympler-0.4.3\nSuccessfully installed pympler-0.4.2\n[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c \"import pympler.muppy\"\n```\n\n_`__itemsize__` is not available in PyPy_\n\n```\n[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c \"print dir(long)\"\n['__abs__', '__add__', '__and__', '__class__', '__coerce__', '__delattr__', '__div__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__hex__', '__index__', '__init__', '__int__', '__invert__', '__le__', '__long__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'bit_length', 'conjugate', 'denominator', 'imag', 'numerator', 'real']\n```\n\n_FYI:_ https://mail.python.org/pipermail/pypy-dev/2010-December/006610.html but `sys.getsizeof` doesn't seem to be a solution...\n\n```\n[ec2-user@i-89b56b16 ~]$ /opt/pypy/bin/pypy -c \"import sys; sys.getsizeof(long)\"\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nTypeError: sys.getsizeof() not implemented on PyPy\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/33", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/33/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/33/events", "html_url": "https://github.com/pympler/pympler/issues/33", "id": 144497103, "node_id": "MDU6SXNzdWUxNDQ0OTcxMDM=", "number": 33, "title": "ValueError: max() arg is an empty sequence", "user": {"login": "gbtami", "id": 479964, "node_id": "MDQ6VXNlcjQ3OTk2NA==", "avatar_url": "https://avatars1.githubusercontent.com/u/479964?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gbtami", "html_url": "https://github.com/gbtami", "followers_url": "https://api.github.com/users/gbtami/followers", "following_url": "https://api.github.com/users/gbtami/following{/other_user}", "gists_url": "https://api.github.com/users/gbtami/gists{/gist_id}", "starred_url": "https://api.github.com/users/gbtami/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gbtami/subscriptions", "organizations_url": "https://api.github.com/users/gbtami/orgs", "repos_url": "https://api.github.com/users/gbtami/repos", "events_url": "https://api.github.com/users/gbtami/events{/privacy}", "received_events_url": "https://api.github.com/users/gbtami/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2016-03-30T08:05:44Z", "updated_at": "2016-03-31T07:05:31Z", "closed_at": "2016-03-31T07:05:31Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "If I call HtmlStats.create_html() without calling tracker create_snapshot() before it I get:\n\nTraceback (most recent call last):\n  File \"/home/tamas/pychess/lib/pychess/ic/ICLounge.py\", line 1447, in on_filter_button_toggled\n    HtmlStats(tracker=self.lounge.tracker).create_html('profile.html')\n  File \"/usr/local/lib/python2.7/dist-packages/pympler/classtracker_stats.py\", line 737, in create_html\n    self.charts['snapshots'] = self.create_snapshot_chart(fn)\n  File \"/usr/local/lib/python2.7/dist-packages/pympler/classtracker_stats.py\", line 655, in create_snapshot_chart\n    if max(pct) > 3.0:\nValueError: max() arg is an empty sequence\n\n(produced with 0.4.2 on Ubuntu 16.04)\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/31", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/31/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/31/events", "html_url": "https://github.com/pympler/pympler/issues/31", "id": 142131325, "node_id": "MDU6SXNzdWUxNDIxMzEzMjU=", "number": 31, "title": "Pympler django integration doesn't work with django 1.9", "user": {"login": "benjyw", "id": 512764, "node_id": "MDQ6VXNlcjUxMjc2NA==", "avatar_url": "https://avatars2.githubusercontent.com/u/512764?v=4", "gravatar_id": "", "url": "https://api.github.com/users/benjyw", "html_url": "https://github.com/benjyw", "followers_url": "https://api.github.com/users/benjyw/followers", "following_url": "https://api.github.com/users/benjyw/following{/other_user}", "gists_url": "https://api.github.com/users/benjyw/gists{/gist_id}", "starred_url": "https://api.github.com/users/benjyw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/benjyw/subscriptions", "organizations_url": "https://api.github.com/users/benjyw/orgs", "repos_url": "https://api.github.com/users/benjyw/repos", "events_url": "https://api.github.com/users/benjyw/events{/privacy}", "received_events_url": "https://api.github.com/users/benjyw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-03-20T05:30:22Z", "updated_at": "2016-03-22T08:13:31Z", "closed_at": "2016-03-20T23:13:05Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "I've submitted a fix at https://github.com/pympler/pympler/pull/30. \n\nThanks!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/29", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/29/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/29/events", "html_url": "https://github.com/pympler/pympler/issues/29", "id": 133952727, "node_id": "MDU6SXNzdWUxMzM5NTI3Mjc=", "number": 29, "title": "pympler segfault when aerospike loaded", "user": {"login": "tigran-a", "id": 2544843, "node_id": "MDQ6VXNlcjI1NDQ4NDM=", "avatar_url": "https://avatars1.githubusercontent.com/u/2544843?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tigran-a", "html_url": "https://github.com/tigran-a", "followers_url": "https://api.github.com/users/tigran-a/followers", "following_url": "https://api.github.com/users/tigran-a/following{/other_user}", "gists_url": "https://api.github.com/users/tigran-a/gists{/gist_id}", "starred_url": "https://api.github.com/users/tigran-a/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tigran-a/subscriptions", "organizations_url": "https://api.github.com/users/tigran-a/orgs", "repos_url": "https://api.github.com/users/tigran-a/repos", "events_url": "https://api.github.com/users/tigran-a/events{/privacy}", "received_events_url": "https://api.github.com/users/tigran-a/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-02-16T11:17:15Z", "updated_at": "2016-04-01T17:46:24Z", "closed_at": "2016-04-01T17:46:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, crossposting this issue https://github.com/aerospike/aerospike-client-python/issues/106 here: \n\nIn short:  pip install aerospike pympler, then  \n\n```\nIn [1]: from pympler import tracker\nIn [2]: import aerospike\nIn [3]: tr = tracker.SummaryTracker()\nSegmentation fault (core dumped)\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/24", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/24/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/24/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/24/events", "html_url": "https://github.com/pympler/pympler/issues/24", "id": 120195678, "node_id": "MDU6SXNzdWUxMjAxOTU2Nzg=", "number": 24, "title": "AttributeError: __flags__ using muppy", "user": {"login": "jmilloy", "id": 1051972, "node_id": "MDQ6VXNlcjEwNTE5NzI=", "avatar_url": "https://avatars1.githubusercontent.com/u/1051972?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jmilloy", "html_url": "https://github.com/jmilloy", "followers_url": "https://api.github.com/users/jmilloy/followers", "following_url": "https://api.github.com/users/jmilloy/following{/other_user}", "gists_url": "https://api.github.com/users/jmilloy/gists{/gist_id}", "starred_url": "https://api.github.com/users/jmilloy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jmilloy/subscriptions", "organizations_url": "https://api.github.com/users/jmilloy/orgs", "repos_url": "https://api.github.com/users/jmilloy/repos", "events_url": "https://api.github.com/users/jmilloy/events{/privacy}", "received_events_url": "https://api.github.com/users/jmilloy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2015-12-03T15:24:51Z", "updated_at": "2015-12-14T21:58:05Z", "closed_at": "2015-12-14T17:17:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "I confirmed that I can use muppy or a tracker with the expected results in a simple case. But when I import my library, I get an `AttributeError` when using muppy. It is not informative enough for me to figure out what aspect of my library is causing the problem.\n\n```\nfrom pympler import muppy\nimport <my library>\nobjs = muppy.get_objects()\n```\n\nThis code gives the following exception\n\n```\nTraceback (most recent call last):\n  File \"/home/jmilloy/test.py\", line 5, in <module>\n    objs = muppy.get_objects()\n  File \"/usr/local/lib/python2.7/dist-packages/pympler/muppy.py\", line 45, in get_objects\n    if not _is_containerobject(ref):\n  File \"/usr/local/lib/python2.7/dist-packages/pympler/muppy.py\", line 246, in _is_containerobject\n    if type(o).__flags__ & __TPFLAGS_HAVE_GC == 0:\nAttributeError: __flags__\n```\n\nYou won't be able to reproduce because I can't give you access to my library, but maybe we can figure out what's causing it. Have you seen this before?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/23", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/23/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/23/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/23/events", "html_url": "https://github.com/pympler/pympler/issues/23", "id": 103115240, "node_id": "MDU6SXNzdWUxMDMxMTUyNDA=", "number": 23, "title": "why is asizeof 1000 times slower than hash function?", "user": {"login": "denfromufa", "id": 7870949, "node_id": "MDQ6VXNlcjc4NzA5NDk=", "avatar_url": "https://avatars1.githubusercontent.com/u/7870949?v=4", "gravatar_id": "", "url": "https://api.github.com/users/denfromufa", "html_url": "https://github.com/denfromufa", "followers_url": "https://api.github.com/users/denfromufa/followers", "following_url": "https://api.github.com/users/denfromufa/following{/other_user}", "gists_url": "https://api.github.com/users/denfromufa/gists{/gist_id}", "starred_url": "https://api.github.com/users/denfromufa/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/denfromufa/subscriptions", "organizations_url": "https://api.github.com/users/denfromufa/orgs", "repos_url": "https://api.github.com/users/denfromufa/repos", "events_url": "https://api.github.com/users/denfromufa/events{/privacy}", "received_events_url": "https://api.github.com/users/denfromufa/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-08-25T20:54:54Z", "updated_at": "2015-12-12T21:49:20Z", "closed_at": "2015-12-12T21:49:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "https://groups.google.com/forum/#!topic/sympy/slKi02rzXVE\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/22", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/22/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/22/events", "html_url": "https://github.com/pympler/pympler/issues/22", "id": 98924087, "node_id": "MDU6SXNzdWU5ODkyNDA4Nw==", "number": 22, "title": "FAIL: test_flatsize_vs_getsizeof (asizeof.test_asizeof.AsizeofTest)", "user": {"login": "jlec", "id": 79732, "node_id": "MDQ6VXNlcjc5NzMy", "avatar_url": "https://avatars0.githubusercontent.com/u/79732?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jlec", "html_url": "https://github.com/jlec", "followers_url": "https://api.github.com/users/jlec/followers", "following_url": "https://api.github.com/users/jlec/following{/other_user}", "gists_url": "https://api.github.com/users/jlec/gists{/gist_id}", "starred_url": "https://api.github.com/users/jlec/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jlec/subscriptions", "organizations_url": "https://api.github.com/users/jlec/orgs", "repos_url": "https://api.github.com/users/jlec/repos", "events_url": "https://api.github.com/users/jlec/events{/privacy}", "received_events_url": "https://api.github.com/users/jlec/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2015-08-04T09:09:41Z", "updated_at": "2016-10-01T17:56:47Z", "closed_at": "2016-10-01T17:56:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\nFAIL: test_flatsize_vs_getsizeof (asizeof.test_asizeof.AsizeofTest)\nTest asizeof.flatsize() vs sys.getsizeof()\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/var/tmp/portage/dev-python/pympler-0.4.2/work/Pympler-0.4.2/test/asizeof/test_asizeof.py\", line 82, in test_flatsize_vs_getsizeof\n    n, e = test_flatsize(failf=self._failf)  # stdf=sys.stderr)\n  File \"/var/tmp/portage/dev-python/pympler-0.4.2/work/Pympler-0.4.2/test/asizeof/test_asizeof.py\", line 63, in test_flatsize\n    a, s, asizeof._nameof(type(o)), _repr(o))\n  File \"/var/tmp/portage/dev-python/pympler-0.4.2/work/Pympler-0.4.2/test/asizeof/test_asizeof.py\", line 76, in _failf\n    self.fail(fmt % args)\nAssertionError: 904 vs 944 for type: <class 'weakref.KeyedRef'>\n\n----------------------------------------------------------------------\n```\n\nwith pympler and python2.7\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/21", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/21/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/21/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/21/events", "html_url": "https://github.com/pympler/pympler/issues/21", "id": 96760047, "node_id": "MDU6SXNzdWU5Njc2MDA0Nw==", "number": 21, "title": "NameError in MemoryPanel: cnt is not defined", "user": {"login": "relekang", "id": 476364, "node_id": "MDQ6VXNlcjQ3NjM2NA==", "avatar_url": "https://avatars3.githubusercontent.com/u/476364?v=4", "gravatar_id": "", "url": "https://api.github.com/users/relekang", "html_url": "https://github.com/relekang", "followers_url": "https://api.github.com/users/relekang/followers", "following_url": "https://api.github.com/users/relekang/following{/other_user}", "gists_url": "https://api.github.com/users/relekang/gists{/gist_id}", "starred_url": "https://api.github.com/users/relekang/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/relekang/subscriptions", "organizations_url": "https://api.github.com/users/relekang/orgs", "repos_url": "https://api.github.com/users/relekang/repos", "events_url": "https://api.github.com/users/relekang/events{/privacy}", "received_events_url": "https://api.github.com/users/relekang/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-07-23T08:24:11Z", "updated_at": "2015-07-26T21:16:33Z", "closed_at": "2015-07-26T21:16:33Z", "author_association": "NONE", "active_lock_reason": null, "body": "Using pympler with debug toolbar raises the following error:\n\n```\nException Type: NameError at /__debug__/render_panel/\nException Value: name 'cnt' is not defined\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/20", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/20/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/20/events", "html_url": "https://github.com/pympler/pympler/issues/20", "id": 88671916, "node_id": "MDU6SXNzdWU4ODY3MTkxNg==", "number": 20, "title": "asizeof seems to ignore private __attr style variables within slots", "user": {"login": "ddodt", "id": 10000138, "node_id": "MDQ6VXNlcjEwMDAwMTM4", "avatar_url": "https://avatars0.githubusercontent.com/u/10000138?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ddodt", "html_url": "https://github.com/ddodt", "followers_url": "https://api.github.com/users/ddodt/followers", "following_url": "https://api.github.com/users/ddodt/following{/other_user}", "gists_url": "https://api.github.com/users/ddodt/gists{/gist_id}", "starred_url": "https://api.github.com/users/ddodt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ddodt/subscriptions", "organizations_url": "https://api.github.com/users/ddodt/orgs", "repos_url": "https://api.github.com/users/ddodt/repos", "events_url": "https://api.github.com/users/ddodt/events{/privacy}", "received_events_url": "https://api.github.com/users/ddodt/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-06-16T09:22:36Z", "updated_at": "2015-07-10T20:32:33Z", "closed_at": "2015-07-10T20:32:33Z", "author_association": "NONE", "active_lock_reason": null, "body": "the `_dir2` routine fails to recognize slot attributes in `__attr` private variable style, which are mangled as `_<ClassName>__attr` by python\n\nadding\n\n```\n                if a[:2]==\"__\" : a= '_'+c.__name__+a\n```\n\nas line 354, seems to fix issue for me.\n[this isn't displayed correctly I compare the first to chars to 'underscore''underscore' and if true use the c name attribute to emulate the mangling done by python. And yeah I guess this is, because this is not the place for code, but I'm not a regular, and would just like to document a bug and a one-line fix.]\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/19", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/19/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/19/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/19/events", "html_url": "https://github.com/pympler/pympler/issues/19", "id": 65383007, "node_id": "MDU6SXNzdWU2NTM4MzAwNw==", "number": 19, "title": "failures=2 in testsuite of pympler-0.3.1 under python3.4", "user": {"login": "idella", "id": 1655078, "node_id": "MDQ6VXNlcjE2NTUwNzg=", "avatar_url": "https://avatars2.githubusercontent.com/u/1655078?v=4", "gravatar_id": "", "url": "https://api.github.com/users/idella", "html_url": "https://github.com/idella", "followers_url": "https://api.github.com/users/idella/followers", "following_url": "https://api.github.com/users/idella/following{/other_user}", "gists_url": "https://api.github.com/users/idella/gists{/gist_id}", "starred_url": "https://api.github.com/users/idella/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/idella/subscriptions", "organizations_url": "https://api.github.com/users/idella/orgs", "repos_url": "https://api.github.com/users/idella/repos", "events_url": "https://api.github.com/users/idella/events{/privacy}", "received_events_url": "https://api.github.com/users/idella/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-03-31T07:05:27Z", "updated_at": "2015-04-08T12:40:10Z", "closed_at": "2015-04-08T12:40:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "with deps installed\n\n``` bash\n/path/to//Pympler-0.3.1/ $ python3.4 setup.py try\n\n======================================================================\nFAIL: test_uncollectable (gui.test_garbage.GarbageTestCase)\nTest uncollectable object tracking.\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/test/gui/test_garbage.py\", line 226, in test_uncollectable\n    self.assertEqual(len(genemy), 1)\nAssertionError: 0 != 1\n\n======================================================================\nFAIL: test_flatsize_vs_getsizeof (asizeof.test_asizeof.AsizeofTest)\nTest asizeof.flatsize() vs sys.getsizeof()\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/test/asizeof/test_asizeof.py\", line 26, in test_flatsize_vs_getsizeof\n    n, e = f(failf=self._failf)  # stdf=sys.stderr)\n  File \"/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/pympler/asizeof.py\", line 2276, in test_flatsize\n    a, s, _nameof(type(o)), _repr(o))\n  File \"/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/test/asizeof/test_asizeof.py\", line 17, in _failf\n    self.fail(fmt % args)\nAssertionError: 104 vs 616 for deque: deque([])\n\n----------------------------------------------------------------------\nRan 114 tests in 17.571s\n\nFAILED (failures=2)\n```\n\nalso acquired the same output by use of python3.4 -m unittest discover.  They pass under py3.3\n\nCan you replicate?  Do you require any further info?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/17", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/17/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/17/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/17/events", "html_url": "https://github.com/pympler/pympler/issues/17", "id": 56495619, "node_id": "MDU6SXNzdWU1NjQ5NTYxOQ==", "number": 17, "title": "non-free Highcharts JS is preventing Pympler from inclusion in Fedora", "user": {"login": "rathann", "id": 5873507, "node_id": "MDQ6VXNlcjU4NzM1MDc=", "avatar_url": "https://avatars0.githubusercontent.com/u/5873507?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rathann", "html_url": "https://github.com/rathann", "followers_url": "https://api.github.com/users/rathann/followers", "following_url": "https://api.github.com/users/rathann/following{/other_user}", "gists_url": "https://api.github.com/users/rathann/gists{/gist_id}", "starred_url": "https://api.github.com/users/rathann/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rathann/subscriptions", "organizations_url": "https://api.github.com/users/rathann/orgs", "repos_url": "https://api.github.com/users/rathann/repos", "events_url": "https://api.github.com/users/rathann/events{/privacy}", "received_events_url": "https://api.github.com/users/rathann/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2015-02-04T08:40:24Z", "updated_at": "2015-04-15T08:55:26Z", "closed_at": "2015-03-21T18:35:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "Dear developers,\nplease replace pympler/templates/highcharts.js with an alternative that has a free license. Otherwise Pympler cannot be submitted for inclusion in Fedora, which I'm trying to do.\n\nSee https://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses_3 .\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/16", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/16/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/16/events", "html_url": "https://github.com/pympler/pympler/issues/16", "id": 54859477, "node_id": "MDU6SXNzdWU1NDg1OTQ3Nw==", "number": 16, "title": "asizeof() gives incorrect values if list has the same items", "user": {"login": "ysakasin", "id": 4254002, "node_id": "MDQ6VXNlcjQyNTQwMDI=", "avatar_url": "https://avatars1.githubusercontent.com/u/4254002?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ysakasin", "html_url": "https://github.com/ysakasin", "followers_url": "https://api.github.com/users/ysakasin/followers", "following_url": "https://api.github.com/users/ysakasin/following{/other_user}", "gists_url": "https://api.github.com/users/ysakasin/gists{/gist_id}", "starred_url": "https://api.github.com/users/ysakasin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ysakasin/subscriptions", "organizations_url": "https://api.github.com/users/ysakasin/orgs", "repos_url": "https://api.github.com/users/ysakasin/repos", "events_url": "https://api.github.com/users/ysakasin/events{/privacy}", "received_events_url": "https://api.github.com/users/ysakasin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2015-01-20T09:15:33Z", "updated_at": "2015-02-02T01:19:53Z", "closed_at": "2015-01-29T20:26:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello, contributions.\n\nI met the situation, such as:\n\n```\nPython 3.4.1 (default, Oct 15 2014, 13:28:30) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> from pympler.asizeof import asizeof\n>>> asizeof([1, 2, 3])\n184\n>>> asizeof([1, 1, 2])\n152\n```\n\nI use ea8c2bd9a310647e74304ae6e64cf2c2839d5632\n\nI expected that `asizeof([1, 2, 3])` and `asizeof([1, 1, 2])` give the same values.\nIs it specification ? or bug?\nAttention : I'm python biginner.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/15", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/15/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/15/events", "html_url": "https://github.com/pympler/pympler/issues/15", "id": 54776143, "node_id": "MDU6SXNzdWU1NDc3NjE0Mw==", "number": 15, "title": "\"error: option --user not recognized\" when trying to do a user-specific installation", "user": {"login": "geo909", "id": 7989227, "node_id": "MDQ6VXNlcjc5ODkyMjc=", "avatar_url": "https://avatars3.githubusercontent.com/u/7989227?v=4", "gravatar_id": "", "url": "https://api.github.com/users/geo909", "html_url": "https://github.com/geo909", "followers_url": "https://api.github.com/users/geo909/followers", "following_url": "https://api.github.com/users/geo909/following{/other_user}", "gists_url": "https://api.github.com/users/geo909/gists{/gist_id}", "starred_url": "https://api.github.com/users/geo909/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/geo909/subscriptions", "organizations_url": "https://api.github.com/users/geo909/orgs", "repos_url": "https://api.github.com/users/geo909/repos", "events_url": "https://api.github.com/users/geo909/events{/privacy}", "received_events_url": "https://api.github.com/users/geo909/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-01-19T15:20:00Z", "updated_at": "2017-10-06T22:55:58Z", "closed_at": "2015-01-29T20:23:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\n\nI am trying to use pympler 0.3.1 in my school's server computer, which has python 2.6.6. I see the following in Pympler's README file:\n\n> 2.b) For a user-specific*\\* installation run:\n> \n>    python setup.py --user install\n\nSo I first run `python setup.py try` which is succesful (output here:http://pastebin.com/V3FCi5JV).\nThen I run\n\n```\n[x@y Pympler-0.3.1]$ python setup.py build\nrunning build\nrunning build_py\n```\n\nBut in the last step I have an error:\n\n```\n[x@y Pympler-0.3.1]$ python setup.py --user install\nusage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n   or: setup.py --help [cmd1 cmd2 ...]\n   or: setup.py --help-commands\n   or: setup.py cmd --help\n\nerror: option --user not recognized\n\n```\n\nAny ideas why I get this error? \n\nSome info about the system:\n\n```\nLSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch\nDistributor ID: Scientific\nDescription:    Scientific Linux release 6.6 (Carbon)\nRelease:        6.6\nCodename:       Carbon\n```\n\n```\n[x@y Pympler-0.3.1]$ python --version\nPython 2.6.6\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/11", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/11/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/11/events", "html_url": "https://github.com/pympler/pympler/issues/11", "id": 40840920, "node_id": "MDU6SXNzdWU0MDg0MDkyMA==", "number": 11, "title": "ClassTracker should detach classes when deleted", "user": {"login": "Pankrat", "id": 281391, "node_id": "MDQ6VXNlcjI4MTM5MQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/281391?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Pankrat", "html_url": "https://github.com/Pankrat", "followers_url": "https://api.github.com/users/Pankrat/followers", "following_url": "https://api.github.com/users/Pankrat/following{/other_user}", "gists_url": "https://api.github.com/users/Pankrat/gists{/gist_id}", "starred_url": "https://api.github.com/users/Pankrat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Pankrat/subscriptions", "organizations_url": "https://api.github.com/users/Pankrat/orgs", "repos_url": "https://api.github.com/users/Pankrat/repos", "events_url": "https://api.github.com/users/Pankrat/events{/privacy}", "received_events_url": "https://api.github.com/users/Pankrat/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 15629410, "node_id": "MDU6TGFiZWwxNTYyOTQxMA==", "url": "https://api.github.com/repos/pympler/pympler/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-08-21T19:44:43Z", "updated_at": "2015-12-12T21:50:50Z", "closed_at": "2015-12-12T21:50:50Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/10", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/10/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/10/events", "html_url": "https://github.com/pympler/pympler/issues/10", "id": 39362738, "node_id": "MDU6SXNzdWUzOTM2MjczOA==", "number": 10, "title": "asizeof() gives incorrect values for the memory consumption of named tuples.", "user": {"login": "ceridwen", "id": 8268008, "node_id": "MDQ6VXNlcjgyNjgwMDg=", "avatar_url": "https://avatars1.githubusercontent.com/u/8268008?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ceridwen", "html_url": "https://github.com/ceridwen", "followers_url": "https://api.github.com/users/ceridwen/followers", "following_url": "https://api.github.com/users/ceridwen/following{/other_user}", "gists_url": "https://api.github.com/users/ceridwen/gists{/gist_id}", "starred_url": "https://api.github.com/users/ceridwen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ceridwen/subscriptions", "organizations_url": "https://api.github.com/users/ceridwen/orgs", "repos_url": "https://api.github.com/users/ceridwen/repos", "events_url": "https://api.github.com/users/ceridwen/events{/privacy}", "received_events_url": "https://api.github.com/users/ceridwen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-08-03T03:49:06Z", "updated_at": "2015-01-29T20:25:48Z", "closed_at": "2015-01-29T20:25:48Z", "author_association": "NONE", "active_lock_reason": null, "body": "From the documentation for the collections module:\n\n\"Named tuple instances do not have per-instance dictionaries, so they are lightweight and require no more memory than regular tuples.\"\n\n```\nPython 3.4.0 (default, Apr 11 2014, 13:05:11) \n[GCC 4.8.2] on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import pympler.asizeof\n>>> import collections\n>>> Point = collections.namedtuple('Point', ['x', 'y'])\n>>> p = Point(11, y=22)\n>>> p\nPoint(x=11, y=22)\n>>> pympler.asizeof.asizeof(p)\n1440\n>>> t = 11, 22\n>>> t\n(11, 22)\n>>> pympler.asizeof.asizeof(t)\n128\n```\n\nI haven't been able to figure out the reason for the discrepancy.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/8", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/8/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/8/events", "html_url": "https://github.com/pympler/pympler/issues/8", "id": 28361956, "node_id": "MDU6SXNzdWUyODM2MTk1Ng==", "number": 8, "title": "pympler.asizeof does not size closures correctly.", "user": {"login": "csilvers", "id": 1445223, "node_id": "MDQ6VXNlcjE0NDUyMjM=", "avatar_url": "https://avatars3.githubusercontent.com/u/1445223?v=4", "gravatar_id": "", "url": "https://api.github.com/users/csilvers", "html_url": "https://github.com/csilvers", "followers_url": "https://api.github.com/users/csilvers/followers", "following_url": "https://api.github.com/users/csilvers/following{/other_user}", "gists_url": "https://api.github.com/users/csilvers/gists{/gist_id}", "starred_url": "https://api.github.com/users/csilvers/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/csilvers/subscriptions", "organizations_url": "https://api.github.com/users/csilvers/orgs", "repos_url": "https://api.github.com/users/csilvers/repos", "events_url": "https://api.github.com/users/csilvers/events{/privacy}", "received_events_url": "https://api.github.com/users/csilvers/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2014-02-26T19:32:08Z", "updated_at": "2014-03-06T18:01:27Z", "closed_at": "2014-03-06T18:01:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "pympler does not look into func_closure correctly, causing it to miss memory that may be owned by a closure.  Here is a simple repro case:\n\n  import pympler.asizeof as sz\n  cp = lambda x: lambda: x\n  fn = cp([1] \\* 40000)\n  cell = fn.func_closure[0]\n  sz.asizeof(cell)   # returns 0, should return 160072 (on 32-bit machine)\n\nThis causes sz.asizeof(fn, code=True) to be something like 560 rather than 160000.\n\nThe problem is that pympler does not have special-casing for the 'cell' type, which is where python encodes data that is held by a closure.\n\nHere is a patch that fixes this, at least in my tests.  There is an aspect of cargo-culting here, so I'm not sure the fix is totally correct, but it works on the above test case, at least.\n\nhttps://gist.github.com/csilvers/9236595\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/5", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/5/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/5/events", "html_url": "https://github.com/pympler/pympler/issues/5", "id": 13770413, "node_id": "MDU6SXNzdWUxMzc3MDQxMw==", "number": 5, "title": "Streambrowser doesn't print tree", "user": {"login": "pedru-de-huere", "id": 4294472, "node_id": "MDQ6VXNlcjQyOTQ0NzI=", "avatar_url": "https://avatars2.githubusercontent.com/u/4294472?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pedru-de-huere", "html_url": "https://github.com/pedru-de-huere", "followers_url": "https://api.github.com/users/pedru-de-huere/followers", "following_url": "https://api.github.com/users/pedru-de-huere/following{/other_user}", "gists_url": "https://api.github.com/users/pedru-de-huere/gists{/gist_id}", "starred_url": "https://api.github.com/users/pedru-de-huere/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pedru-de-huere/subscriptions", "organizations_url": "https://api.github.com/users/pedru-de-huere/orgs", "repos_url": "https://api.github.com/users/pedru-de-huere/repos", "events_url": "https://api.github.com/users/pedru-de-huere/events{/privacy}", "received_events_url": "https://api.github.com/users/pedru-de-huere/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 15629408, "node_id": "MDU6TGFiZWwxNTYyOTQwOA==", "url": "https://api.github.com/repos/pympler/pympler/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2013-04-29T17:08:12Z", "updated_at": "2013-05-11T13:34:24Z", "closed_at": "2013-05-11T13:34:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "refbrowser.py\n\n`if tree is None:\n     self._print(self.root, '', '')`\nno tree is printed, only the root\n\nmaybe `get_tree()` instead of `self.root` ??\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/4", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/4/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/4/events", "html_url": "https://github.com/pympler/pympler/issues/4", "id": 13770315, "node_id": "MDU6SXNzdWUxMzc3MDMxNQ==", "number": 4, "title": "Python 3.x Tkinter import fails", "user": {"login": "pedru-de-huere", "id": 4294472, "node_id": "MDQ6VXNlcjQyOTQ0NzI=", "avatar_url": "https://avatars2.githubusercontent.com/u/4294472?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pedru-de-huere", "html_url": "https://github.com/pedru-de-huere", "followers_url": "https://api.github.com/users/pedru-de-huere/followers", "following_url": "https://api.github.com/users/pedru-de-huere/following{/other_user}", "gists_url": "https://api.github.com/users/pedru-de-huere/gists{/gist_id}", "starred_url": "https://api.github.com/users/pedru-de-huere/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pedru-de-huere/subscriptions", "organizations_url": "https://api.github.com/users/pedru-de-huere/orgs", "repos_url": "https://api.github.com/users/pedru-de-huere/repos", "events_url": "https://api.github.com/users/pedru-de-huere/events{/privacy}", "received_events_url": "https://api.github.com/users/pedru-de-huere/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 15629408, "node_id": "MDU6TGFiZWwxNTYyOTQwOA==", "url": "https://api.github.com/repos/pympler/pympler/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2013-04-29T17:05:53Z", "updated_at": "2013-05-11T13:39:10Z", "closed_at": "2013-05-11T13:39:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "refbrowser.py:\n\n`import Tkinter as _Tkinter`\nfails in python3.x since the name changed\n\n`import tkinter as _Tkinter`\nworks\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/2", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/2/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/2/events", "html_url": "https://github.com/pympler/pympler/issues/2", "id": 12930469, "node_id": "MDU6SXNzdWUxMjkzMDQ2OQ==", "number": 2, "title": "No support for alternative output targets like logging", "user": {"login": "deemoowoor", "id": 406092, "node_id": "MDQ6VXNlcjQwNjA5Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/406092?v=4", "gravatar_id": "", "url": "https://api.github.com/users/deemoowoor", "html_url": "https://github.com/deemoowoor", "followers_url": "https://api.github.com/users/deemoowoor/followers", "following_url": "https://api.github.com/users/deemoowoor/following{/other_user}", "gists_url": "https://api.github.com/users/deemoowoor/gists{/gist_id}", "starred_url": "https://api.github.com/users/deemoowoor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/deemoowoor/subscriptions", "organizations_url": "https://api.github.com/users/deemoowoor/orgs", "repos_url": "https://api.github.com/users/deemoowoor/repos", "events_url": "https://api.github.com/users/deemoowoor/events{/privacy}", "received_events_url": "https://api.github.com/users/deemoowoor/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 15629410, "node_id": "MDU6TGFiZWwxNTYyOTQxMA==", "url": "https://api.github.com/repos/pympler/pympler/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "Pankrat", "id": 281391, "node_id": "MDQ6VXNlcjI4MTM5MQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/281391?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Pankrat", "html_url": "https://github.com/Pankrat", "followers_url": "https://api.github.com/users/Pankrat/followers", "following_url": "https://api.github.com/users/Pankrat/following{/other_user}", "gists_url": "https://api.github.com/users/Pankrat/gists{/gist_id}", "starred_url": "https://api.github.com/users/Pankrat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Pankrat/subscriptions", "organizations_url": "https://api.github.com/users/Pankrat/orgs", "repos_url": "https://api.github.com/users/Pankrat/repos", "events_url": "https://api.github.com/users/Pankrat/events{/privacy}", "received_events_url": "https://api.github.com/users/Pankrat/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "Pankrat", "id": 281391, "node_id": "MDQ6VXNlcjI4MTM5MQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/281391?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Pankrat", "html_url": "https://github.com/Pankrat", "followers_url": "https://api.github.com/users/Pankrat/followers", "following_url": "https://api.github.com/users/Pankrat/following{/other_user}", "gists_url": "https://api.github.com/users/Pankrat/gists{/gist_id}", "starred_url": "https://api.github.com/users/Pankrat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Pankrat/subscriptions", "organizations_url": "https://api.github.com/users/Pankrat/orgs", "repos_url": "https://api.github.com/users/Pankrat/repos", "events_url": "https://api.github.com/users/Pankrat/events{/privacy}", "received_events_url": "https://api.github.com/users/Pankrat/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2013-04-08T16:01:08Z", "updated_at": "2013-04-09T09:39:51Z", "closed_at": "2013-04-09T09:39:51Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Pympler currently seems to assume that all the memory profiling would be done in an environment where `print` statements make sense.\n\nIn my case I wanted to write a periodic memory usage dump to a log to keep track of memory utilization over longer term on a Twisted-based server application and found that pympler did not allow me to do that out of the box -- I had to copy & rewrite `pympler.summary.print_` function to return an list of formatted lines instead of printing them straight out with `print`.\n\nAs you see, it's extremely easy to fix. Take standard `traceback` module for example. It has both `print_stack` and `format_stack` methods. Same with standard library `pprint` module (`pprint` and `pformat`). With `format_` method (optionally implemented as a generator), `print_` could even be reduced to a couple of lines.\n\n I'm aware of `print` to logging redirection option, but it's not good in my case, because it doesn't allow to fine tune the actual output of logs, like the standard `logging` module does. And it's very important.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pympler/pympler/issues/1", "repository_url": "https://api.github.com/repos/pympler/pympler", "labels_url": "https://api.github.com/repos/pympler/pympler/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/pympler/pympler/issues/1/comments", "events_url": "https://api.github.com/repos/pympler/pympler/issues/1/events", "html_url": "https://github.com/pympler/pympler/issues/1", "id": 9495508, "node_id": "MDU6SXNzdWU5NDk1NTA4", "number": 1, "title": "sys.maxunicode >= (1 << (_sizeof_Cunicode << 3)) causes assertion failure", "user": {"login": "mattferrin", "id": 2746787, "node_id": "MDQ6VXNlcjI3NDY3ODc=", "avatar_url": "https://avatars3.githubusercontent.com/u/2746787?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mattferrin", "html_url": "https://github.com/mattferrin", "followers_url": "https://api.github.com/users/mattferrin/followers", "following_url": "https://api.github.com/users/mattferrin/following{/other_user}", "gists_url": "https://api.github.com/users/mattferrin/gists{/gist_id}", "starred_url": "https://api.github.com/users/mattferrin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mattferrin/subscriptions", "organizations_url": "https://api.github.com/users/mattferrin/orgs", "repos_url": "https://api.github.com/users/mattferrin/repos", "events_url": "https://api.github.com/users/mattferrin/events{/privacy}", "received_events_url": "https://api.github.com/users/mattferrin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2012-12-24T03:04:13Z", "updated_at": "2012-12-30T01:05:36Z", "closed_at": "2012-12-30T00:33:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "sys.maxunicode >= (1 << (_sizeof_Cunicode << 3)) \ncauses assertion failure.\n\nUsing: \nfrom pympler.asizeof import asizeof \nraises the error. \n\nFollowed these instructions:\n1. Build the Pympler package:\n    python setup.py build\n2.a) For a system-wide installation run:\n    python setup.py install\n2.b) For a user-specific*\\* installation run:\n    python setup.py --user install\n3) Test the installed Pympler package:\n    python setup.py test\nAnd, included a command window filled with the test results. \n![maxunicode](https://f.cloud.github.com/assets/2746787/29406/005b6a02-4d75-11e2-82c5-c90c789c4fb2.png)\n", "performed_via_github_app": null, "score": 1.0}]}