{"total_count": 8, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/tiran/pysha3/issues/23", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/23/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/23/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/23/events", "html_url": "https://github.com/tiran/pysha3/issues/23", "id": 555075461, "node_id": "MDU6SXNzdWU1NTUwNzU0NjE=", "number": 23, "title": "unsupported hash type sha3_256", "user": {"login": "fastchain", "id": 13186708, "node_id": "MDQ6VXNlcjEzMTg2NzA4", "avatar_url": "https://avatars0.githubusercontent.com/u/13186708?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fastchain", "html_url": "https://github.com/fastchain", "followers_url": "https://api.github.com/users/fastchain/followers", "following_url": "https://api.github.com/users/fastchain/following{/other_user}", "gists_url": "https://api.github.com/users/fastchain/gists{/gist_id}", "starred_url": "https://api.github.com/users/fastchain/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fastchain/subscriptions", "organizations_url": "https://api.github.com/users/fastchain/orgs", "repos_url": "https://api.github.com/users/fastchain/repos", "events_url": "https://api.github.com/users/fastchain/events{/privacy}", "received_events_url": "https://api.github.com/users/fastchain/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-01-25T11:42:23Z", "updated_at": "2020-01-25T11:54:28Z", "closed_at": "2020-01-25T11:54:28Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\nAfter installation according the manual I get this with  new() function:\r\n\r\n```\r\nPython 2.7.16 (default, Mar 11 2019, 18:59:25) \r\n[GCC 8.2.1 20181127] on linux2\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import hashlib\r\n>>> \r\n>>> import sha3\r\n>>> hashlib.new('sha3_256')\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/usr/lib64/python2.7/hashlib.py\", line 130, in __hash_new\r\n    return __get_builtin_constructor(name)(string)\r\n  File \"/usr/lib64/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\r\n    raise ValueError('unsupported hash type ' + name)\r\nValueError: unsupported hash type sha3_256\r\n>>> hashlib\r\n<module 'hashlib' from '/usr/lib64/python2.7/hashlib.pyc'>\r\n>>> dir(hashlib)\r\n['__all__', '__builtins__', '__doc__', '__file__', '__get_builtin_constructor', '__name__', '__package__', '_hashlib', 'algorithms', 'algorithms_available', 'algorithms_guaranteed', 'md5', 'new', 'pbkdf2_hmac', 'sha1', 'sha224', 'sha256', 'sha384', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'sha512', 'shake_128', 'shake_256']\r\n>>> dir(hashlib.algorithms)\r\n['__add__', '__class__', '__contains__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getslice__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']\r\n>>> hashlib.algorithms\r\n('md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512')\r\n>>> hashlib.algorithms_available\r\nset(['sha3-512', 'shake128', 'sha3-384', 'sha3-256', 'sha512-224', 'blake2s256', 'shake256', 'blake2b512', 'md4', 'md5', 'sha1', 'sha224', 'sm3', 'sha512-256', 'mdc2', 'sha3-224', 'sha384', 'md5-sha1', 'sha256', 'sha512', 'ripemd160', 'whirlpool'])\r\n>>> \r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/tiran/pysha3/issues/20", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/20/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/20/events", "html_url": "https://github.com/tiran/pysha3/issues/20", "id": 311075230, "node_id": "MDU6SXNzdWUzMTEwNzUyMzA=", "number": 20, "title": "Compilation issue installing pysha3 on windows", "user": {"login": "mikera", "id": 212007, "node_id": "MDQ6VXNlcjIxMjAwNw==", "avatar_url": "https://avatars0.githubusercontent.com/u/212007?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mikera", "html_url": "https://github.com/mikera", "followers_url": "https://api.github.com/users/mikera/followers", "following_url": "https://api.github.com/users/mikera/following{/other_user}", "gists_url": "https://api.github.com/users/mikera/gists{/gist_id}", "starred_url": "https://api.github.com/users/mikera/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mikera/subscriptions", "organizations_url": "https://api.github.com/users/mikera/orgs", "repos_url": "https://api.github.com/users/mikera/repos", "events_url": "https://api.github.com/users/mikera/events{/privacy}", "received_events_url": "https://api.github.com/users/mikera/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-04-04T03:44:53Z", "updated_at": "2018-04-04T07:19:21Z", "closed_at": "2018-04-04T06:53:11Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nI'm trying to install pysha3 on windows using the following:\r\n\r\n`pip install sha3`\r\n\r\nI get the following error:\r\n\r\n``\r\nC:\\Users\\Mike\\git\\ProtoKeeper>pip install sha3\r\nCollecting sha3\r\n  Using cached sha3-0.2.1.tar.gz\r\nInstalling collected packages: sha3\r\n  Running setup.py install for sha3 ... error\r\n    Complete output from command c:\\prog\\python\\python36-32\\python.exe -u -c \"import setuptools, tokenize;__file__='C:\\\\Users\\\\Mike\\\\AppData\\\\Local\\\\Temp\\\\pip-build-_gzd3oe7\\\\sha3\\\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record C:\\Users\\Mike\\AppData\\Local\\Temp\\pip-3vd4i04y-record\\install-record.txt --single-version-externally-managed --compile:\r\n    running install\r\n    running build\r\n    running build_py\r\n    creating build\r\n    creating build\\lib.win32-3.6\r\n    creating build\\lib.win32-3.6\\sha3\r\n    copying sha3\\__init__.py -> build\\lib.win32-3.6\\sha3\r\n    running build_ext\r\n    building '_sha3' extension\r\n    creating build\\temp.win32-3.6\r\n    creating build\\temp.win32-3.6\\Release\r\n    creating build\\temp.win32-3.6\\Release\\src\r\n    creating build\\temp.win32-3.6\\Release\\src\\64\r\n    C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x86\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc/ -Isrc/64 -Ic:\\prog\\python\\python36-32\\include -Ic:\\prog\\python\\python36-32\\include \"-IC:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\include\" \"-IC:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\ucrt\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\shared\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\um\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\winrt\" \"-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.16299.0\\cppwinrt\" /Tcsha3.c /Fobuild\\temp.win32-3.6\\Release\\sha3.obj\r\n    sha3.c\r\n    sha3.c(33): error C2016: C requires that a struct or union has at least one member\r\n    error: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2017\\\\BuildTools\\\\VC\\\\Tools\\\\MSVC\\\\14.13.26128\\\\bin\\\\HostX86\\\\x86\\\\cl.exe' failed with exit status 2``\r\n\r\nAm I doing something wrong or is this a bug?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/tiran/pysha3/issues/15", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/15/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/15/events", "html_url": "https://github.com/tiran/pysha3/issues/15", "id": 280723273, "node_id": "MDU6SXNzdWUyODA3MjMyNzM=", "number": 15, "title": "pysha3 uses private 'pystrhex.h' API", "user": {"login": "mgorny", "id": 110765, "node_id": "MDQ6VXNlcjExMDc2NQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/110765?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mgorny", "html_url": "https://github.com/mgorny", "followers_url": "https://api.github.com/users/mgorny/followers", "following_url": "https://api.github.com/users/mgorny/following{/other_user}", "gists_url": "https://api.github.com/users/mgorny/gists{/gist_id}", "starred_url": "https://api.github.com/users/mgorny/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mgorny/subscriptions", "organizations_url": "https://api.github.com/users/mgorny/orgs", "repos_url": "https://api.github.com/users/mgorny/repos", "events_url": "https://api.github.com/users/mgorny/events{/privacy}", "received_events_url": "https://api.github.com/users/mgorny/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-12-09T14:18:36Z", "updated_at": "2017-12-09T17:12:16Z", "closed_at": "2017-12-09T16:53:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "According to PyPy upstream (https://bitbucket.org/pypy/pypy/issues/2687/pypy3-is-missing-pystrhexh-breaking-pysha3) pystrhex.h is a private API of CPython and should not be used in the extensions. I would therefore suggest removing the conditional that uses it and always use the local implementation.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/tiran/pysha3/issues/8", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/8/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/8/events", "html_url": "https://github.com/tiran/pysha3/issues/8", "id": 243023514, "node_id": "MDU6SXNzdWUyNDMwMjM1MTQ=", "number": 8, "title": "keccak seems to be missing from package", "user": {"login": "MichaelJFlynn", "id": 2887500, "node_id": "MDQ6VXNlcjI4ODc1MDA=", "avatar_url": "https://avatars0.githubusercontent.com/u/2887500?v=4", "gravatar_id": "", "url": "https://api.github.com/users/MichaelJFlynn", "html_url": "https://github.com/MichaelJFlynn", "followers_url": "https://api.github.com/users/MichaelJFlynn/followers", "following_url": "https://api.github.com/users/MichaelJFlynn/following{/other_user}", "gists_url": "https://api.github.com/users/MichaelJFlynn/gists{/gist_id}", "starred_url": "https://api.github.com/users/MichaelJFlynn/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/MichaelJFlynn/subscriptions", "organizations_url": "https://api.github.com/users/MichaelJFlynn/orgs", "repos_url": "https://api.github.com/users/MichaelJFlynn/repos", "events_url": "https://api.github.com/users/MichaelJFlynn/events{/privacy}", "received_events_url": "https://api.github.com/users/MichaelJFlynn/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 366700067, "node_id": "MDU6TGFiZWwzNjY3MDAwNjc=", "url": "https://api.github.com/repos/tiran/pysha3/labels/invalid", "name": "invalid", "color": "e6e6e6", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-07-14T15:02:20Z", "updated_at": "2017-07-31T02:34:03Z", "closed_at": "2017-07-18T11:41:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "In the readme: \r\n\r\n```\r\n  >>> import sha3\r\n  >>> k = sha3.keccak_512()\r\n  >>> k.update(b\"data\")\r\n  >>> k.hexdigest()\r\n'1065aceeded3a5e4412e2187e919bffeadf815f5bd73d37fe00d384fe29f55f08462fdabe1007b993ce5b8119630e7db93101d9425d6e352e22ffe3dcb56b825'\r\n\r\n```\r\nHowever, when I do this on my machine:\r\n\r\n```\r\n>>> import sha3\r\n>>> k = sha3.keccak_512()\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nAttributeError: 'module' object has no attribute 'keccak_512'\r\n```\r\n\r\nAlso looking a `dir(sha3)` I see nothing with \"keccak\"\r\n\r\n```\r\n>>> dir(sha3)\r\n['SHA3224', 'SHA3256', 'SHA3384', 'SHA3512', 'SHAKE128', 'SHAKE256', '_SHA3Base'\\\r\n, '_SHAKEBase', '__all__', '__author__', '__builtins__', '__doc__', '__file__', \\\r\n'__name__', '__package__', '__path__', '__version__', '_sha3', 'binascii', 'copy\\\r\n', 'hashlib', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'shake128', 'shake\\\r\n256']\r\n```\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/tiran/pysha3/issues/7", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/7/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/7/events", "html_url": "https://github.com/tiran/pysha3/issues/7", "id": 238862954, "node_id": "MDU6SXNzdWUyMzg4NjI5NTQ=", "number": 7, "title": "Linux wheels", "user": {"login": "ulope", "id": 55078, "node_id": "MDQ6VXNlcjU1MDc4", "avatar_url": "https://avatars0.githubusercontent.com/u/55078?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ulope", "html_url": "https://github.com/ulope", "followers_url": "https://api.github.com/users/ulope/followers", "following_url": "https://api.github.com/users/ulope/following{/other_user}", "gists_url": "https://api.github.com/users/ulope/gists{/gist_id}", "starred_url": "https://api.github.com/users/ulope/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ulope/subscriptions", "organizations_url": "https://api.github.com/users/ulope/orgs", "repos_url": "https://api.github.com/users/ulope/repos", "events_url": "https://api.github.com/users/ulope/events{/privacy}", "received_events_url": "https://api.github.com/users/ulope/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2017-06-27T14:05:22Z", "updated_at": "2017-07-18T12:55:09Z", "closed_at": "2017-07-18T12:55:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "It would be awesome if you could also provide Linux [\"manylinux1\" wheels](https://github.com/pypa/manylinux). \r\n\r\nThis is [relatively easy to do on travis-ci](https://github.com/pypa/python-manylinux-demo).", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/tiran/pysha3/issues/6", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/6/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/6/events", "html_url": "https://github.com/tiran/pysha3/issues/6", "id": 235074732, "node_id": "MDU6SXNzdWUyMzUwNzQ3MzI=", "number": 6, "title": "README PyPi Type-o", "user": {"login": "brad-anton", "id": 1035793, "node_id": "MDQ6VXNlcjEwMzU3OTM=", "avatar_url": "https://avatars0.githubusercontent.com/u/1035793?v=4", "gravatar_id": "", "url": "https://api.github.com/users/brad-anton", "html_url": "https://github.com/brad-anton", "followers_url": "https://api.github.com/users/brad-anton/followers", "following_url": "https://api.github.com/users/brad-anton/following{/other_user}", "gists_url": "https://api.github.com/users/brad-anton/gists{/gist_id}", "starred_url": "https://api.github.com/users/brad-anton/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/brad-anton/subscriptions", "organizations_url": "https://api.github.com/users/brad-anton/orgs", "repos_url": "https://api.github.com/users/brad-anton/repos", "events_url": "https://api.github.com/users/brad-anton/events{/privacy}", "received_events_url": "https://api.github.com/users/brad-anton/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-06-11T15:57:47Z", "updated_at": "2017-07-18T11:42:11Z", "closed_at": "2017-07-18T11:42:11Z", "author_association": "NONE", "active_lock_reason": null, "body": "The README and PyPi page make reference `sha3_228()`, this looks like a type-o, should be `sha3_224()`\r\n\r\n```\r\n>>> import hashlib\r\n>>> import sha3\r\n>>> s = hashlib.sha3_228()\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nAttributeError: 'module' object has no attribute 'sha3_228'\r\n>>> s = hashlib.sha3_224()\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/tiran/pysha3/issues/4", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/4/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/4/events", "html_url": "https://github.com/tiran/pysha3/issues/4", "id": 204856050, "node_id": "MDU6SXNzdWUyMDQ4NTYwNTA=", "number": 4, "title": "Keccak implementations missing when installed from pip", "user": {"login": "sohkai", "id": 4166642, "node_id": "MDQ6VXNlcjQxNjY2NDI=", "avatar_url": "https://avatars2.githubusercontent.com/u/4166642?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sohkai", "html_url": "https://github.com/sohkai", "followers_url": "https://api.github.com/users/sohkai/followers", "following_url": "https://api.github.com/users/sohkai/following{/other_user}", "gists_url": "https://api.github.com/users/sohkai/gists{/gist_id}", "starred_url": "https://api.github.com/users/sohkai/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sohkai/subscriptions", "organizations_url": "https://api.github.com/users/sohkai/orgs", "repos_url": "https://api.github.com/users/sohkai/repos", "events_url": "https://api.github.com/users/sohkai/events{/privacy}", "received_events_url": "https://api.github.com/users/sohkai/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-02-02T12:10:34Z", "updated_at": "2017-02-03T09:59:27Z", "closed_at": "2017-02-03T09:23:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "The following error comes up when trying to import `sha3` on Python 3.6, after using pip to install `pysha3` (both 1.0.0 and 1.0.1):\r\n\r\n```python\r\nPython 3.6.0 (default, Feb  2 2017, 12:13:44)\r\n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import sha3\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/Users/Brett/.pyenv/versions/bigchaindb-3.6/lib/python3.6/site-packages/sha3.py\", line 8, in <module>\r\n    from _sha3 import keccak_224, keccak_256, keccak_384, keccak_512\r\nImportError: cannot import name 'keccak_224'\r\n```\r\n\r\nInspecting an imported `_sha3`:\r\n\r\n```python\r\n>>> import _sha3\r\n>>> dir(_sha3)\r\n['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'implementation', 'keccakopt', 'sha3_224', 'sha3_256', 'sha3_384', 'sha3_512', 'shake_128', 'shake_256']\r\n```\r\n\r\n(So everything but the keccak implementations is available)\r\n\r\nTo install, I used a normal pip install:\r\n\r\n```bash\r\npip install pysha3\r\n```\r\n\r\nThis happens on native OSX (10.11), macOS (10.12), and on a docker container running the [official 3.6 alpine image](https://hub.docker.com/_/python/).\r\n\r\nI'm not sure what's going on, since it looks like the [`PY_WITH_KECCAK` flag is defined](https://github.com/tiran/pysha3/blob/master/setup.py#L76), but maybe it's not getting built with it?\r\n\r\n--------\r\n\r\nEverything works fine on 3.5.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/tiran/pysha3/issues/2", "repository_url": "https://api.github.com/repos/tiran/pysha3", "labels_url": "https://api.github.com/repos/tiran/pysha3/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/tiran/pysha3/issues/2/comments", "events_url": "https://api.github.com/repos/tiran/pysha3/issues/2/events", "html_url": "https://github.com/tiran/pysha3/issues/2", "id": 198909443, "node_id": "MDU6SXNzdWUxOTg5MDk0NDM=", "number": 2, "title": "Issues with pypi page", "user": {"login": "ssadler", "id": 125019, "node_id": "MDQ6VXNlcjEyNTAxOQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/125019?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ssadler", "html_url": "https://github.com/ssadler", "followers_url": "https://api.github.com/users/ssadler/followers", "following_url": "https://api.github.com/users/ssadler/following{/other_user}", "gists_url": "https://api.github.com/users/ssadler/gists{/gist_id}", "starred_url": "https://api.github.com/users/ssadler/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ssadler/subscriptions", "organizations_url": "https://api.github.com/users/ssadler/orgs", "repos_url": "https://api.github.com/users/ssadler/repos", "events_url": "https://api.github.com/users/ssadler/events{/privacy}", "received_events_url": "https://api.github.com/users/ssadler/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-01-05T09:21:45Z", "updated_at": "2017-01-24T12:15:15Z", "closed_at": "2017-01-24T12:15:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\n\r\nThere appears to be two issues with the pysha3 page on pypi:\r\n\r\n* The homepage is set to github.org instead of github.com, didn't load for me, and\r\n* The changelog advertises 1.1.0 and doesn't advertise 1.0.0, which is the latest version I could install.\r\n\r\nCheers", "performed_via_github_app": null, "score": 1.0}]}