{"total_count": 31, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/48", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/48/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/48/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/48/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/48", "id": 624366561, "node_id": "MDU6SXNzdWU2MjQzNjY1NjE=", "number": 48, "title": "Missing @medatadata[beat]", "user": {"login": "bngsudheer", "id": 33030, "node_id": "MDQ6VXNlcjMzMDMw", "avatar_url": "https://avatars2.githubusercontent.com/u/33030?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bngsudheer", "html_url": "https://github.com/bngsudheer", "followers_url": "https://api.github.com/users/bngsudheer/followers", "following_url": "https://api.github.com/users/bngsudheer/following{/other_user}", "gists_url": "https://api.github.com/users/bngsudheer/gists{/gist_id}", "starred_url": "https://api.github.com/users/bngsudheer/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bngsudheer/subscriptions", "organizations_url": "https://api.github.com/users/bngsudheer/orgs", "repos_url": "https://api.github.com/users/bngsudheer/repos", "events_url": "https://api.github.com/users/bngsudheer/events{/privacy}", "received_events_url": "https://api.github.com/users/bngsudheer/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2020-05-25T15:29:47Z", "updated_at": "2020-06-06T11:00:18Z", "closed_at": "2020-06-06T11:00:17Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "This is when using the beats protocol.\r\n\r\nI followed the common output pattern in logstsash:\r\n```\r\noutput {\r\n  elasticsearch {\r\n    hosts => [\"http://192.168.1.5:9200\"]\r\n    index => \"%{[@metadata][beat]}-%{+YYYY.MM.dd}\"\r\n  }\r\n}\r\n\r\n```\r\nIt seems `@metadata` is missing, therefore `@metadata[beat]` is missing. This configuration in logstash results in indexes like `  \"%{[@metadata][beat]}-2020.05.25\"`.\r\n\r\nI would expect the index name to be something like my_beat_name-2020.05.25 for a standard output to elasticsearch.\r\n\r\nIt would be useful to add an example configuration in logstash pipeline to send data to elasticsearch.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/47", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/47/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/47/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/47/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/47", "id": 578616799, "node_id": "MDU6SXNzdWU1Nzg2MTY3OTk=", "number": 47, "title": "TCP/Beats transport should be queuing", "user": {"login": "jesusch", "id": 2362798, "node_id": "MDQ6VXNlcjIzNjI3OTg=", "avatar_url": "https://avatars1.githubusercontent.com/u/2362798?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jesusch", "html_url": "https://github.com/jesusch", "followers_url": "https://api.github.com/users/jesusch/followers", "following_url": "https://api.github.com/users/jesusch/following{/other_user}", "gists_url": "https://api.github.com/users/jesusch/gists{/gist_id}", "starred_url": "https://api.github.com/users/jesusch/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jesusch/subscriptions", "organizations_url": "https://api.github.com/users/jesusch/orgs", "repos_url": "https://api.github.com/users/jesusch/repos", "events_url": "https://api.github.com/users/jesusch/events{/privacy}", "received_events_url": "https://api.github.com/users/jesusch/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2020-03-10T14:22:56Z", "updated_at": "2020-07-05T12:25:06Z", "closed_at": "2020-07-05T12:25:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "While using this Handler with no TCP or Beats Listener running it creates an exception when it's not able to connect to the remote endpoint.\r\n\r\nHaving either in memory or sqlite queuing in place I'd assume this lib should try to reconnect (using backoff) and try to async deliver log records?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/45", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/45/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/45/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/45", "id": 563827573, "node_id": "MDU6SXNzdWU1NjM4Mjc1NzM=", "number": 45, "title": "LogstashFormatter is not working with StreamHandler", "user": {"login": "sarg", "id": 193264, "node_id": "MDQ6VXNlcjE5MzI2NA==", "avatar_url": "https://avatars1.githubusercontent.com/u/193264?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sarg", "html_url": "https://github.com/sarg", "followers_url": "https://api.github.com/users/sarg/followers", "following_url": "https://api.github.com/users/sarg/following{/other_user}", "gists_url": "https://api.github.com/users/sarg/gists{/gist_id}", "starred_url": "https://api.github.com/users/sarg/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sarg/subscriptions", "organizations_url": "https://api.github.com/users/sarg/orgs", "repos_url": "https://api.github.com/users/sarg/repos", "events_url": "https://api.github.com/users/sarg/events{/privacy}", "received_events_url": "https://api.github.com/users/sarg/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-02-12T08:13:47Z", "updated_at": "2020-02-26T23:57:49Z", "closed_at": "2020-02-26T23:57:49Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "I need to output logstash formatted records to stdout for further processing via external tools. When I do it like:\r\n```python\r\nch = logging.StreamHandler(stream=sys.stdout)\r\nch.setFormatter(LogstashFormatter())\r\n```\r\n\r\nI get errors that `write` method accepts `str` and not `bytes`.\r\n\r\nHere is excerpt from `Formatter` docstring:\r\n```\r\n    Formatter instances are used to convert a LogRecord to text.\r\n```\r\n\r\nSeems that conversion to bytes is already handled in [transport](https://github.com/eht16/python-logstash-async/blob/d8b36c111d7e0f4680fca48fa25a4d150ecdb3d2/logstash_async/transport.py#L68), so I suggest to remove another one from `Formatter`.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/44", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/44/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/44/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/44", "id": 495316860, "node_id": "MDU6SXNzdWU0OTUzMTY4NjA=", "number": 44, "title": "filebeat", "user": {"login": "jordotech", "id": 485972, "node_id": "MDQ6VXNlcjQ4NTk3Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/485972?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jordotech", "html_url": "https://github.com/jordotech", "followers_url": "https://api.github.com/users/jordotech/followers", "following_url": "https://api.github.com/users/jordotech/following{/other_user}", "gists_url": "https://api.github.com/users/jordotech/gists{/gist_id}", "starred_url": "https://api.github.com/users/jordotech/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jordotech/subscriptions", "organizations_url": "https://api.github.com/users/jordotech/orgs", "repos_url": "https://api.github.com/users/jordotech/repos", "events_url": "https://api.github.com/users/jordotech/events{/privacy}", "received_events_url": "https://api.github.com/users/jordotech/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-09-18T15:58:38Z", "updated_at": "2019-09-21T14:55:58Z", "closed_at": "2019-09-21T13:24:50Z", "author_association": "NONE", "active_lock_reason": null, "body": "After experimenting with this app it dawned on me - this is what filebeat is for.  Filebeat lives on the server you're shipping logs FROM and operates on an interval so it does not interfere with request times, etc. \r\n\r\nSo my question is why is it preferable to store messages in a sqlite db and async ship them as opposed to using filebeat?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/43", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/43/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/43/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/43/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/43", "id": 490038656, "node_id": "MDU6SXNzdWU0OTAwMzg2NTY=", "number": 43, "title": "Django settings vs manually logging- what am I missing?", "user": {"login": "jordotech", "id": 485972, "node_id": "MDQ6VXNlcjQ4NTk3Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/485972?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jordotech", "html_url": "https://github.com/jordotech", "followers_url": "https://api.github.com/users/jordotech/followers", "following_url": "https://api.github.com/users/jordotech/following{/other_user}", "gists_url": "https://api.github.com/users/jordotech/gists{/gist_id}", "starred_url": "https://api.github.com/users/jordotech/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jordotech/subscriptions", "organizations_url": "https://api.github.com/users/jordotech/orgs", "repos_url": "https://api.github.com/users/jordotech/repos", "events_url": "https://api.github.com/users/jordotech/events{/privacy}", "received_events_url": "https://api.github.com/users/jordotech/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-09-05T22:27:24Z", "updated_at": "2020-07-05T12:25:37Z", "closed_at": "2020-07-05T12:25:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hopefully it's something obvious that I'm missing but I am unable to get this working with Django logging settings but programmatically sending a message does work.  Maybe you can see something before I do a deep dive into the internals.\r\n\r\nI have logging enabled so I can see when messages are received to my remote logstash server.\r\n\r\nsettings.py:\r\n```\r\nLOGGING = {\r\n    'version': 1,\r\n    'formatters': {\r\n        'logstash': {\r\n                  '()': 'logstash_async.formatter.LogstashFormatter',\r\n                  'message_type': 'django',\r\n              },\r\n    },\r\n    'handlers': {\r\n        'logstash': {\r\n                  'level': 'DEBUG',\r\n                  'class': 'logstash_async.handler.AsynchronousLogstashHandler',\r\n                  'formatter': 'logstash',\r\n                  'transport': 'logstash_async.transport.TcpTransport',\r\n                  'host': 'myelkserver.com',\r\n                  'port': 1026,\r\n                  'database_path': './logstash.db',  # same results if None\r\n              },\r\n    },\r\n    'loggers': {\r\n        'logstash': {\r\n                  'handlers': ['logstash'],\r\n                  'level': 'DEBUG',\r\n                  'propagate': True, \r\n              },\r\n    }\r\n}\r\n```\r\n\r\n```\r\n>>>import logging\r\n>>>logger = logging.getLogger(\"logstash\")\r\n>>>logger.debug('hello')  # no message is sent to remote\r\n```\r\n\r\nThe following works which makes no sense to me, any ideas?\r\n\r\n```\r\nfrom logstash_async.handler import AsynchronousLogstashHandler\r\nfrom logstash_async.transport import TcpTransport\r\nfrom logstash_async.formatter import DjangoLogstashFormatter\r\n\r\nlgr = logging.getLogger()\r\nformatter = DjangoLogstashFormatter(message_type='django')\r\nhandler = AsynchronousLogstashHandler('myelkserver.com', 1026, database_path='./logstash.db', transport=TcpTransport)\r\nhandler.setFormatter(formatter)\r\nlgr.addHandler(handler)\r\nlgr.debug('test123') # this is received by remote\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/42", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/42/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/42/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/42/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/42", "id": 463832259, "node_id": "MDU6SXNzdWU0NjM4MzIyNTk=", "number": 42, "title": "Exception with simple usage", "user": {"login": "CameronNemo", "id": 3212452, "node_id": "MDQ6VXNlcjMyMTI0NTI=", "avatar_url": "https://avatars1.githubusercontent.com/u/3212452?v=4", "gravatar_id": "", "url": "https://api.github.com/users/CameronNemo", "html_url": "https://github.com/CameronNemo", "followers_url": "https://api.github.com/users/CameronNemo/followers", "following_url": "https://api.github.com/users/CameronNemo/following{/other_user}", "gists_url": "https://api.github.com/users/CameronNemo/gists{/gist_id}", "starred_url": "https://api.github.com/users/CameronNemo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/CameronNemo/subscriptions", "organizations_url": "https://api.github.com/users/CameronNemo/orgs", "repos_url": "https://api.github.com/users/CameronNemo/repos", "events_url": "https://api.github.com/users/CameronNemo/events{/privacy}", "received_events_url": "https://api.github.com/users/CameronNemo/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 360442469, "node_id": "MDU6TGFiZWwzNjA0NDI0Njk=", "url": "https://api.github.com/repos/eht16/python-logstash-async/labels/bug", "name": "bug", "color": "ee0701", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "eht16", "id": 617017, "node_id": "MDQ6VXNlcjYxNzAxNw==", "avatar_url": "https://avatars3.githubusercontent.com/u/617017?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eht16", "html_url": "https://github.com/eht16", "followers_url": "https://api.github.com/users/eht16/followers", "following_url": "https://api.github.com/users/eht16/following{/other_user}", "gists_url": "https://api.github.com/users/eht16/gists{/gist_id}", "starred_url": "https://api.github.com/users/eht16/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eht16/subscriptions", "organizations_url": "https://api.github.com/users/eht16/orgs", "repos_url": "https://api.github.com/users/eht16/repos", "events_url": "https://api.github.com/users/eht16/events{/privacy}", "received_events_url": "https://api.github.com/users/eht16/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "eht16", "id": 617017, "node_id": "MDQ6VXNlcjYxNzAxNw==", "avatar_url": "https://avatars3.githubusercontent.com/u/617017?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eht16", "html_url": "https://github.com/eht16", "followers_url": "https://api.github.com/users/eht16/followers", "following_url": "https://api.github.com/users/eht16/following{/other_user}", "gists_url": "https://api.github.com/users/eht16/gists{/gist_id}", "starred_url": "https://api.github.com/users/eht16/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eht16/subscriptions", "organizations_url": "https://api.github.com/users/eht16/orgs", "repos_url": "https://api.github.com/users/eht16/repos", "events_url": "https://api.github.com/users/eht16/events{/privacy}", "received_events_url": "https://api.github.com/users/eht16/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 2, "created_at": "2019-07-03T15:56:19Z", "updated_at": "2019-07-03T21:29:23Z", "closed_at": "2019-07-03T20:52:46Z", "author_association": "NONE", "active_lock_reason": null, "body": "```py\r\nimport logging\r\n\r\nfrom logstash_async.handler import AsynchronousLogstashHandler\r\nfrom logstash_async.transport import BeatsTransport\r\n\r\nlgr = logging.getLogger()\r\nlgr.addHandler(AsynchronousLogstashHandler('10.222.0.20', 5056, database_path=None, transport=BeatsTransport))\r\nlgr.error('fnord')\r\n```\r\n\r\n```\r\n2019-07-03 08:55:45: exception: An error occurred while sending events: send() missing 1 required positional argument: 'events'\r\nTraceback (most recent call last):\r\n  File \"/Users/cameronnemo/docs/elk/py-logstash-demo/venv/lib/python3.7/site-packages/logstash_async/worker.py\", line 118, in _fetch_events\r\n    self._fetch_event()\r\n  File \"/Users/cameronnemo/docs/elk/py-logstash-demo/venv/lib/python3.7/site-packages/logstash_async/worker.py\", line 140, in _fetch_event\r\n    self._event = self._queue.get(block=False)\r\n  File \"/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py\", line 167, in get\r\n    raise Empty\r\n_queue.Empty\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/cameronnemo/docs/elk/py-logstash-demo/venv/lib/python3.7/site-packages/logstash_async/worker.py\", line 224, in _flush_queued_events\r\n    self._send_events(events)\r\n  File \"/Users/cameronnemo/docs/elk/py-logstash-demo/venv/lib/python3.7/site-packages/logstash_async/worker.py\", line 255, in _send_events\r\n    self._transport.send(events, use_logging=use_logging)\r\nTypeError: send() missing 1 required positional argument: 'events'\r\n\r\n2019-07-03 08:55:45: error: Error on closing transport: close() missing 1 required positional argument: 'self'\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/41", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/41/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/41/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/41", "id": 461197888, "node_id": "MDU6SXNzdWU0NjExOTc4ODg=", "number": 41, "title": "[request] multiple hosts support", "user": {"login": "CameronNemo", "id": 3212452, "node_id": "MDQ6VXNlcjMyMTI0NTI=", "avatar_url": "https://avatars1.githubusercontent.com/u/3212452?v=4", "gravatar_id": "", "url": "https://api.github.com/users/CameronNemo", "html_url": "https://github.com/CameronNemo", "followers_url": "https://api.github.com/users/CameronNemo/followers", "following_url": "https://api.github.com/users/CameronNemo/following{/other_user}", "gists_url": "https://api.github.com/users/CameronNemo/gists{/gist_id}", "starred_url": "https://api.github.com/users/CameronNemo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/CameronNemo/subscriptions", "organizations_url": "https://api.github.com/users/CameronNemo/orgs", "repos_url": "https://api.github.com/users/CameronNemo/repos", "events_url": "https://api.github.com/users/CameronNemo/events{/privacy}", "received_events_url": "https://api.github.com/users/CameronNemo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-06-26T21:51:29Z", "updated_at": "2019-06-29T10:12:33Z", "closed_at": "2019-06-29T10:12:33Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello, and thank you for your well maintained fork.\r\n\r\nOne benefit of using something like filebeat is that it can fall back to a backup logstash host when the first one defined is unavailable. Do you have any recommendations on how to add this type of feature here, allowing for multiple host/port combos to be specified for the same log handler?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/40", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/40/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/40/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/40/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/40", "id": 447149229, "node_id": "MDU6SXNzdWU0NDcxNDkyMjk=", "number": 40, "title": "Message field is JSON-decoded when switching to BeatsTransport ", "user": {"login": "icamys", "id": 6891299, "node_id": "MDQ6VXNlcjY4OTEyOTk=", "avatar_url": "https://avatars1.githubusercontent.com/u/6891299?v=4", "gravatar_id": "", "url": "https://api.github.com/users/icamys", "html_url": "https://github.com/icamys", "followers_url": "https://api.github.com/users/icamys/followers", "following_url": "https://api.github.com/users/icamys/following{/other_user}", "gists_url": "https://api.github.com/users/icamys/gists{/gist_id}", "starred_url": "https://api.github.com/users/icamys/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/icamys/subscriptions", "organizations_url": "https://api.github.com/users/icamys/orgs", "repos_url": "https://api.github.com/users/icamys/repos", "events_url": "https://api.github.com/users/icamys/events{/privacy}", "received_events_url": "https://api.github.com/users/icamys/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-05-22T13:50:25Z", "updated_at": "2019-05-22T15:16:04Z", "closed_at": "2019-05-22T15:16:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "First of all I would like to thank you for this package.\r\n\r\nHere's the issue: when I use default TcpTransport, the message field arrives to elastic as a regular string in json format:\r\n\r\n![image](https://user-images.githubusercontent.com/6891299/58179412-d3bd5600-7cb0-11e9-8117-0445ed376c7c.png)\r\n\r\nWhen I switch to BeatsTransport, the message field is parsed to the document root and I get this kind of data in kibana (parsed fields are selected with blue color):\r\n\r\n![image](https://user-images.githubusercontent.com/6891299/58179670-51816180-7cb1-11e9-9384-e30c58d2442b.png)\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/38", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/38/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/38/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/38/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/38", "id": 437778276, "node_id": "MDU6SXNzdWU0Mzc3NzgyNzY=", "number": 38, "title": "Too many open files", "user": {"login": "xNinjaKittyx", "id": 1697670, "node_id": "MDQ6VXNlcjE2OTc2NzA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1697670?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xNinjaKittyx", "html_url": "https://github.com/xNinjaKittyx", "followers_url": "https://api.github.com/users/xNinjaKittyx/followers", "following_url": "https://api.github.com/users/xNinjaKittyx/following{/other_user}", "gists_url": "https://api.github.com/users/xNinjaKittyx/gists{/gist_id}", "starred_url": "https://api.github.com/users/xNinjaKittyx/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xNinjaKittyx/subscriptions", "organizations_url": "https://api.github.com/users/xNinjaKittyx/orgs", "repos_url": "https://api.github.com/users/xNinjaKittyx/repos", "events_url": "https://api.github.com/users/xNinjaKittyx/events{/privacy}", "received_events_url": "https://api.github.com/users/xNinjaKittyx/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2019-04-26T17:45:20Z", "updated_at": "2019-05-16T20:37:50Z", "closed_at": "2019-05-16T20:37:50Z", "author_association": "NONE", "active_lock_reason": null, "body": "So, sometimes when logstash is down, our long running scripts will report the normal queue.Empty + connectionError.\r\n\r\nThis is fine, however, when running with pytest, pytest will create an XML file at the end of the test, which fails due to do \"Too many open files\"\r\n\r\nAre failed socket connections somehow lingering for long periods of time?\r\n\r\nI also noticed that after long period of failing to connect to logstash, the sqlite3 connections failed (I'm assuming it's because of too many open sockets)\r\n\r\n```\r\nerror\t26-Apr-2019 02:44:43\t20190426 02:44:43|worke:[ERROR] - Log processing error (queue size: 1031): unable to open database file\r\nerror\t26-Apr-2019 02:44:43\tTraceback (most recent call last):\r\nerror\t26-Apr-2019 02:44:43\t  File \"/home.local/build/.local/share/virtualenvs/<redacted>-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py\", line 145, in _process_event\r\nerror\t26-Apr-2019 02:44:43\t    self._write_event_to_database()\r\nerror\t26-Apr-2019 02:44:43\t  File \"/home.local/build/.local/share/virtualenvs/<redacted>-rYeAsF95/lib/python3.6/site-packages/logstash_async/worker.py\", line 195, in _write_event_to_database\r\nerror\t26-Apr-2019 02:44:43\t    self._database.add_event(self._event)\r\nerror\t26-Apr-2019 02:44:43\t  File \"/home.local/build/.local/share/virtualenvs/<redacted>-rYeAsF95/lib/python3.6/site-packages/logstash_async/database.py\", line 94, in add_event\r\nerror\t26-Apr-2019 02:44:43\t    connection.execute(query, (event, False))\r\nerror\t26-Apr-2019 02:44:43\tsqlite3.OperationalError: unable to open database file\r\n```\r\n\r\nLooking at the code, I think this could be fixed by using a connection pool, rather than creating new connections everytime. It would be nice if there was a way to configure this to use a connection pool rather than creating new connections every time.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/37", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/37/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/37/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/37/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/37", "id": 437769581, "node_id": "MDU6SXNzdWU0Mzc3Njk1ODE=", "number": 37, "title": "Option to ignore logstash async connection failures", "user": {"login": "xNinjaKittyx", "id": 1697670, "node_id": "MDQ6VXNlcjE2OTc2NzA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1697670?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xNinjaKittyx", "html_url": "https://github.com/xNinjaKittyx", "followers_url": "https://api.github.com/users/xNinjaKittyx/followers", "following_url": "https://api.github.com/users/xNinjaKittyx/following{/other_user}", "gists_url": "https://api.github.com/users/xNinjaKittyx/gists{/gist_id}", "starred_url": "https://api.github.com/users/xNinjaKittyx/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xNinjaKittyx/subscriptions", "organizations_url": "https://api.github.com/users/xNinjaKittyx/orgs", "repos_url": "https://api.github.com/users/xNinjaKittyx/repos", "events_url": "https://api.github.com/users/xNinjaKittyx/events{/privacy}", "received_events_url": "https://api.github.com/users/xNinjaKittyx/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-04-26T17:21:20Z", "updated_at": "2019-04-26T17:23:03Z", "closed_at": "2019-04-26T17:23:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is there a way so that we can keep a program running even if it's unable to connect to logstash?\r\n\r\nI'm talking about a scenario where logstash was up and running, then stopped, resulting in a crash on the script because logstash was down.\r\n\r\nI'm writing a script that logstash uptime isn't that important, but the script needs to continue running regardless.\r\n\r\nEven if logstash-async logger stops sending logfiles after disconnecting, that's ok too.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/36", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/36/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/36/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/36/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/36", "id": 430019116, "node_id": "MDU6SXNzdWU0MzAwMTkxMTY=", "number": 36, "title": "Why do you add '\\n' to each log line? ", "user": {"login": "melonux", "id": 48902925, "node_id": "MDQ6VXNlcjQ4OTAyOTI1", "avatar_url": "https://avatars1.githubusercontent.com/u/48902925?v=4", "gravatar_id": "", "url": "https://api.github.com/users/melonux", "html_url": "https://github.com/melonux", "followers_url": "https://api.github.com/users/melonux/followers", "following_url": "https://api.github.com/users/melonux/following{/other_user}", "gists_url": "https://api.github.com/users/melonux/gists{/gist_id}", "starred_url": "https://api.github.com/users/melonux/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/melonux/subscriptions", "organizations_url": "https://api.github.com/users/melonux/orgs", "repos_url": "https://api.github.com/users/melonux/repos", "events_url": "https://api.github.com/users/melonux/events{/privacy}", "received_events_url": "https://api.github.com/users/melonux/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2019-04-06T10:09:40Z", "updated_at": "2019-04-14T09:37:56Z", "closed_at": "2019-04-14T09:37:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "https://github.com/eht16/python-logstash-async/blob/6bae7fbcb5be06f6b72db9b526fc6597061a0d29/logstash_async/handler.py#L134\r\n\r\nIt makes the outputs of StreamHandler and yours are not identical. Would you please remove it?\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/35", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/35/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/35/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/35/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/35", "id": 426860515, "node_id": "MDU6SXNzdWU0MjY4NjA1MTU=", "number": 35, "title": "Events stored in the DB is sent before ", "user": {"login": "JonasKs", "id": 5310116, "node_id": "MDQ6VXNlcjUzMTAxMTY=", "avatar_url": "https://avatars0.githubusercontent.com/u/5310116?v=4", "gravatar_id": "", "url": "https://api.github.com/users/JonasKs", "html_url": "https://github.com/JonasKs", "followers_url": "https://api.github.com/users/JonasKs/followers", "following_url": "https://api.github.com/users/JonasKs/following{/other_user}", "gists_url": "https://api.github.com/users/JonasKs/gists{/gist_id}", "starred_url": "https://api.github.com/users/JonasKs/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/JonasKs/subscriptions", "organizations_url": "https://api.github.com/users/JonasKs/orgs", "repos_url": "https://api.github.com/users/JonasKs/repos", "events_url": "https://api.github.com/users/JonasKs/events{/privacy}", "received_events_url": "https://api.github.com/users/JonasKs/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-03-29T07:52:06Z", "updated_at": "2019-04-01T16:53:21Z", "closed_at": "2019-03-31T11:22:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "If Logstash crashes, `python-logstash-async` is working perfectly, the events get stored in the sqlite database. How ever, when restarting the Logstash container, the connection is established, sent and deleted from the database instantly, but the Logstash is not ready to handle them. All the stored messages is then lost.\r\n\r\nMy workaround will be to have health checks before allowing traffic in to the container. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/34", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/34/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/34/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/34", "id": 406795144, "node_id": "MDU6SXNzdWU0MDY3OTUxNDQ=", "number": 34, "title": "Random Timeouts", "user": {"login": "suvari3V", "id": 10109803, "node_id": "MDQ6VXNlcjEwMTA5ODAz", "avatar_url": "https://avatars1.githubusercontent.com/u/10109803?v=4", "gravatar_id": "", "url": "https://api.github.com/users/suvari3V", "html_url": "https://github.com/suvari3V", "followers_url": "https://api.github.com/users/suvari3V/followers", "following_url": "https://api.github.com/users/suvari3V/following{/other_user}", "gists_url": "https://api.github.com/users/suvari3V/gists{/gist_id}", "starred_url": "https://api.github.com/users/suvari3V/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/suvari3V/subscriptions", "organizations_url": "https://api.github.com/users/suvari3V/orgs", "repos_url": "https://api.github.com/users/suvari3V/repos", "events_url": "https://api.github.com/users/suvari3V/events{/privacy}", "received_events_url": "https://api.github.com/users/suvari3V/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-02-05T13:59:45Z", "updated_at": "2020-07-05T12:34:37Z", "closed_at": "2020-07-05T12:34:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am experiencing timeout exceptions from time to time like\r\n\r\n```\r\n19/02/05 13:49:53 - ERROR - An error occurred while sending events: timed out\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py\", line 118, in _fetch_events\r\n    self._fetch_event()\r\n  File \"/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py\", line 140, in _fetch_event\r\n    self._event = self._queue.get(block=False)\r\n  File \"/usr/lib/python3.7/queue.py\", line 167, in get\r\n    raise Empty\r\n_queue.Empty\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py\", line 224, in _flush_queued_events\r\n    self._send_events(events)\r\n  File \"/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py\", line 255, in _send_events\r\n    self._transport.send(events, use_logging=use_logging)\r\n  File \"/usr/local/lib/python3.7/dist-packages/logstash_async/transport.py\", line 37, in send\r\n    self._send(events)\r\n  File \"/usr/local/lib/python3.7/dist-packages/logstash_async/transport.py\", line 54, in _send\r\n    self._send_via_socket(event)\r\n  File \"/usr/local/lib/python3.7/dist-packages/logstash_async/transport.py\", line 136, in _send_via_socket\r\n    self._sock.sendall(data_to_send)\r\nsocket.timeout: timed out\r\n```\r\nCould you suggest?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/33", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/33/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/33/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/33", "id": 401846522, "node_id": "MDU6SXNzdWU0MDE4NDY1MjI=", "number": 33, "title": "Lost messages if process after process quit", "user": {"login": "suvari3V", "id": 10109803, "node_id": "MDQ6VXNlcjEwMTA5ODAz", "avatar_url": "https://avatars1.githubusercontent.com/u/10109803?v=4", "gravatar_id": "", "url": "https://api.github.com/users/suvari3V", "html_url": "https://github.com/suvari3V", "followers_url": "https://api.github.com/users/suvari3V/followers", "following_url": "https://api.github.com/users/suvari3V/following{/other_user}", "gists_url": "https://api.github.com/users/suvari3V/gists{/gist_id}", "starred_url": "https://api.github.com/users/suvari3V/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/suvari3V/subscriptions", "organizations_url": "https://api.github.com/users/suvari3V/orgs", "repos_url": "https://api.github.com/users/suvari3V/repos", "events_url": "https://api.github.com/users/suvari3V/events{/privacy}", "received_events_url": "https://api.github.com/users/suvari3V/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-01-22T16:27:26Z", "updated_at": "2020-07-05T12:26:29Z", "closed_at": "2020-07-05T12:26:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\n\r\nI am running an API where I am logging some data to Logstash.\r\nIt seems that there are lots of lost messages if process quit and messages are still not send to Logstash.\r\nIf I set 30 secs sleep at the end of the process to test if is alright but it does not work otherwise.\r\n\r\nI assume that for LRP it is going to work perfectly fine but what is happening if process is created and exits soon?\r\n\r\nI am using following:\r\n- ELK 6.4.3\r\n- Ubuntu 18.04\r\n- Python 3.7.1\r\n\r\nCould you suggest how to workaround it?\r\n\r\nThanks", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/31", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/31/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/31/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/31", "id": 365370268, "node_id": "MDU6SXNzdWUzNjUzNzAyNjg=", "number": 31, "title": "Big database prevents treating events", "user": {"login": "mzominy", "id": 41467340, "node_id": "MDQ6VXNlcjQxNDY3MzQw", "avatar_url": "https://avatars1.githubusercontent.com/u/41467340?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mzominy", "html_url": "https://github.com/mzominy", "followers_url": "https://api.github.com/users/mzominy/followers", "following_url": "https://api.github.com/users/mzominy/following{/other_user}", "gists_url": "https://api.github.com/users/mzominy/gists{/gist_id}", "starred_url": "https://api.github.com/users/mzominy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mzominy/subscriptions", "organizations_url": "https://api.github.com/users/mzominy/orgs", "repos_url": "https://api.github.com/users/mzominy/repos", "events_url": "https://api.github.com/users/mzominy/events{/privacy}", "received_events_url": "https://api.github.com/users/mzominy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-10-01T09:09:43Z", "updated_at": "2019-01-05T16:47:24Z", "closed_at": "2019-01-05T16:47:23Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, thanks for the great work on the lib!\r\n\r\nIf the database gets too big, (witnessed with 30k lines of big logs (about 1k chars each)), there is a timeout on the connection when sending logs to logstash with TCP. The timeout creates an exception preventing the logs from being removed from the local database, although **logstash still streats the logs he receives before the timeout!**\r\n\r\nThis got us stuck in a loop of the same logs being processed by logstash over and over again! We avoided the problem by adding a 'LIMIT 100' on the query that gets the logs out of the DB, it works because it fits our data and connection. Maybe a cleaner fix would be to try with the whole database and if you get a 'timeout' try with a smaller portion of the DB and etc. until you can finally send your logs.\r\n\r\nI don't need a fix, it's to let you and other users know of the issue.\r\n\r\nRegards.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/30", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/30/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/30/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/30", "id": 365368729, "node_id": "MDU6SXNzdWUzNjUzNjg3Mjk=", "number": 30, "title": "Can't create several handlers with different databases", "user": {"login": "mzominy", "id": 41467340, "node_id": "MDQ6VXNlcjQxNDY3MzQw", "avatar_url": "https://avatars1.githubusercontent.com/u/41467340?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mzominy", "html_url": "https://github.com/mzominy", "followers_url": "https://api.github.com/users/mzominy/followers", "following_url": "https://api.github.com/users/mzominy/following{/other_user}", "gists_url": "https://api.github.com/users/mzominy/gists{/gist_id}", "starred_url": "https://api.github.com/users/mzominy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mzominy/subscriptions", "organizations_url": "https://api.github.com/users/mzominy/orgs", "repos_url": "https://api.github.com/users/mzominy/repos", "events_url": "https://api.github.com/users/mzominy/events{/privacy}", "received_events_url": "https://api.github.com/users/mzominy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-10-01T09:05:07Z", "updated_at": "2018-12-31T14:55:33Z", "closed_at": "2018-12-31T14:55:33Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, thanks for the great work on the lib!\r\n\r\nThe below code opening two different databases won't work.\r\n\r\nI don't need a fix, it's to let you and other users know of the issue.\r\n\r\n```\r\nimport logging\r\nimport sys\r\nfrom logstash_async.handler import AsynchronousLogstashHandler\r\n\r\ntest_logger1 = logging.getLogger('python-logstash-logger')\r\ntest_logger1.setLevel(logging.INFO)\r\ntest_logger1.addHandler(AsynchronousLogstashHandler(\r\n    'nowhere.test.com',\r\n    5002,\r\n    database_path='handler_1.sqlite',\r\n))\r\n\r\ntest_logger1.info('logger1')\r\n\r\n\r\ntest_logger2 = logging.getLogger('python-logstash-logger2')\r\ntest_logger2.setLevel(logging.INFO)\r\ntest_logger2.addHandler(AsynchronousLogstashHandler(\r\n    'nowhere.test.com',\r\n    5000,\r\n    database_path='handler_2.sqlite',\r\n))\r\n\r\ntest_logger2.info('logger2')  # goes into first database\r\n```\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/29", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/29/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/29/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/29", "id": 332349617, "node_id": "MDU6SXNzdWUzMzIzNDk2MTc=", "number": 29, "title": "Cant't send tags as 1st level of document", "user": {"login": "manthanBhayani", "id": 40265683, "node_id": "MDQ6VXNlcjQwMjY1Njgz", "avatar_url": "https://avatars3.githubusercontent.com/u/40265683?v=4", "gravatar_id": "", "url": "https://api.github.com/users/manthanBhayani", "html_url": "https://github.com/manthanBhayani", "followers_url": "https://api.github.com/users/manthanBhayani/followers", "following_url": "https://api.github.com/users/manthanBhayani/following{/other_user}", "gists_url": "https://api.github.com/users/manthanBhayani/gists{/gist_id}", "starred_url": "https://api.github.com/users/manthanBhayani/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/manthanBhayani/subscriptions", "organizations_url": "https://api.github.com/users/manthanBhayani/orgs", "repos_url": "https://api.github.com/users/manthanBhayani/repos", "events_url": "https://api.github.com/users/manthanBhayani/events{/privacy}", "received_events_url": "https://api.github.com/users/manthanBhayani/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-06-14T10:48:45Z", "updated_at": "2018-06-26T11:43:34Z", "closed_at": "2018-06-16T11:54:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\nI am sending logs to ELK and i want to send some extrainfo without extra fields mentions while logging message. I want to send environment name with all messages but not able to send it, is there any central place where I can set.\r\n\r\nbelow is my config file.\r\n\r\n`# loggers\r\n[loggers]\r\nkeys = root\r\n\r\n[logger_root]\r\nname = python-app\r\nlevel = INFO\r\nhandlers = console,logstash,file\r\npropagate = 1\r\nqualname = root\r\n\r\n[handlers]\r\nkeys = console,logstash,file\r\n\r\n[handler_console]\r\nclass = StreamHandler\r\nlevel = NOTSET\r\nformatter = console\r\nargs = (sys.stdout,)\r\n\r\n[handler_logstash]\r\nclass = logstash_async.handler.AsynchronousLogstashHandler\r\nlevel = NOTSET\r\nformatter = logstash\r\nargs = ('%(host)s', %(port)s, '%(database_path)s', '%(transport)s',%(enable)s)\r\ntransport = logstash_async.transport.UdpTransport\r\nhost = 10.10.0.19\r\nport = 9563\r\nenable = True\r\ndatabase_path = \r\n\r\n[handler_file]\r\nclass : logging.handlers.RotatingFileHandler\r\nlevel : NOTSET\r\nformatter: file\r\nargs = ('%(filename)s','a','%(maxBytes)s','%(backupCount)s',None,0)\r\nfilename: /var/log/es-streaming-transporter/transporter.log\r\nmaxBytes: 1024\r\nbackupCount: 3\r\n\r\n[formatters]\r\nkeys = console,logstash,file\r\n\r\n[formatter_console]\r\nformat = [%(asctime)s][%(module)s][%(levelname)s] %(message)s\r\n\r\n[formatter_file]\r\nformat = [%(asctime)s][%(module)s][%(levelname)s] %(message)s\r\n\r\n[formatter_logstash]\r\nclass = logstash_async.formatter.LogstashFormatter\r\n\r\nformat = python-logstash\r\nstyle = True`", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/28", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/28/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/28/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/28/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/28", "id": 327961335, "node_id": "MDU6SXNzdWUzMjc5NjEzMzU=", "number": 28, "title": "message_type not being set", "user": {"login": "marciogarcianubeliu", "id": 36043027, "node_id": "MDQ6VXNlcjM2MDQzMDI3", "avatar_url": "https://avatars3.githubusercontent.com/u/36043027?v=4", "gravatar_id": "", "url": "https://api.github.com/users/marciogarcianubeliu", "html_url": "https://github.com/marciogarcianubeliu", "followers_url": "https://api.github.com/users/marciogarcianubeliu/followers", "following_url": "https://api.github.com/users/marciogarcianubeliu/following{/other_user}", "gists_url": "https://api.github.com/users/marciogarcianubeliu/gists{/gist_id}", "starred_url": "https://api.github.com/users/marciogarcianubeliu/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/marciogarcianubeliu/subscriptions", "organizations_url": "https://api.github.com/users/marciogarcianubeliu/orgs", "repos_url": "https://api.github.com/users/marciogarcianubeliu/repos", "events_url": "https://api.github.com/users/marciogarcianubeliu/events{/privacy}", "received_events_url": "https://api.github.com/users/marciogarcianubeliu/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-05-31T01:31:28Z", "updated_at": "2018-06-04T21:26:33Z", "closed_at": "2018-06-04T19:11:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have a Django Server, I was using python-logstash with UDP, now I change my script to use this one with SSL, it's working pretty well, but the message_type is not being set.\r\n\r\nI tried everything, I can see all the values being set in the config, but in Logstash I'm still seeing python-logstash as type.\r\n\r\nAnything I can do to solve this?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/23", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/23/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/23/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/23/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/23", "id": 309853804, "node_id": "MDU6SXNzdWUzMDk4NTM4MDQ=", "number": 23, "title": "Clarify documentation for extra dictionaries", "user": {"login": "shidarin", "id": 5846610, "node_id": "MDQ6VXNlcjU4NDY2MTA=", "avatar_url": "https://avatars1.githubusercontent.com/u/5846610?v=4", "gravatar_id": "", "url": "https://api.github.com/users/shidarin", "html_url": "https://github.com/shidarin", "followers_url": "https://api.github.com/users/shidarin/followers", "following_url": "https://api.github.com/users/shidarin/following{/other_user}", "gists_url": "https://api.github.com/users/shidarin/gists{/gist_id}", "starred_url": "https://api.github.com/users/shidarin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shidarin/subscriptions", "organizations_url": "https://api.github.com/users/shidarin/orgs", "repos_url": "https://api.github.com/users/shidarin/repos", "events_url": "https://api.github.com/users/shidarin/events{/privacy}", "received_events_url": "https://api.github.com/users/shidarin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-03-29T18:16:05Z", "updated_at": "2018-04-15T13:23:00Z", "closed_at": "2018-04-15T13:23:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Reading the documentation, I initially thought I could simply pass an extra kwarg to AsynchronousLogstashHandler:\r\n\r\n\"You can also specify an additional extra dictionary in the logging configuration with static values like the application name, environment, etc. These values will be merged with any extra dictionary items passed in the logging call into the configured extra prefix.\"\r\n\r\nBut the [docs](http://python-logstash-async.readthedocs.io/en/latest/usage.html) must mean the Logging File Config. They don't mention using a LoggingAdapter- which is the other way I know of to do this. It'd be neat to have an example of this in the docs, since I think adding extras to the Logger as a whole is a use case just as large as adding them to individual calls.\r\n\r\nThanks for your work on python-logstash-async!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/22", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/22/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/22/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/22", "id": 298312168, "node_id": "MDU6SXNzdWUyOTgzMTIxNjg=", "number": 22, "title": "Logs have not been sent in high rate ", "user": {"login": "nnehdi", "id": 13899995, "node_id": "MDQ6VXNlcjEzODk5OTk1", "avatar_url": "https://avatars1.githubusercontent.com/u/13899995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nnehdi", "html_url": "https://github.com/nnehdi", "followers_url": "https://api.github.com/users/nnehdi/followers", "following_url": "https://api.github.com/users/nnehdi/following{/other_user}", "gists_url": "https://api.github.com/users/nnehdi/gists{/gist_id}", "starred_url": "https://api.github.com/users/nnehdi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nnehdi/subscriptions", "organizations_url": "https://api.github.com/users/nnehdi/orgs", "repos_url": "https://api.github.com/users/nnehdi/repos", "events_url": "https://api.github.com/users/nnehdi/events{/privacy}", "received_events_url": "https://api.github.com/users/nnehdi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-02-19T15:19:32Z", "updated_at": "2020-07-05T12:34:02Z", "closed_at": "2020-07-05T12:34:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "Our system logs with more that 10,000 logs/Sec and with this rate logs are not sent in logstash. When we check caching database file size we understand that it is increasing with time and its size gets more than 1 gigs.\r\nWhat can we do about it? Is there any config about it? Is it possibe that it's logstash overloading problem?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/21", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/21/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/21/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/21/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/21", "id": 294075087, "node_id": "MDU6SXNzdWUyOTQwNzUwODc=", "number": 21, "title": "ConnectionRefusedError: [Errno 111] Connection refused", "user": {"login": "SalahAdDin", "id": 5034215, "node_id": "MDQ6VXNlcjUwMzQyMTU=", "avatar_url": "https://avatars2.githubusercontent.com/u/5034215?v=4", "gravatar_id": "", "url": "https://api.github.com/users/SalahAdDin", "html_url": "https://github.com/SalahAdDin", "followers_url": "https://api.github.com/users/SalahAdDin/followers", "following_url": "https://api.github.com/users/SalahAdDin/following{/other_user}", "gists_url": "https://api.github.com/users/SalahAdDin/gists{/gist_id}", "starred_url": "https://api.github.com/users/SalahAdDin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/SalahAdDin/subscriptions", "organizations_url": "https://api.github.com/users/SalahAdDin/orgs", "repos_url": "https://api.github.com/users/SalahAdDin/repos", "events_url": "https://api.github.com/users/SalahAdDin/events{/privacy}", "received_events_url": "https://api.github.com/users/SalahAdDin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-02-03T02:21:38Z", "updated_at": "2018-02-03T02:27:53Z", "closed_at": "2018-02-03T02:27:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, finally i'm getting this working, it was a hard way but i have it.\r\n\r\nUnfortunatelly i have a problem with it:\r\n```bash\r\nxprende.blog     | Traceback (most recent call last):\r\nxprende.blog     |   File \"/usr/local/lib/python3.6/site-packages/logstash_async/worker.py\", line 118, in _fetch_events\r\nxprende.blog     |     self._fetch_event()\r\nxprende.blog     |   File \"/usr/local/lib/python3.6/site-packages/logstash_async/worker.py\", line 140, in _fetch_event\r\nxprende.blog     |     self._event = self._queue.get(block=False)\r\nxprende.blog     |   File \"/usr/local/lib/python3.6/queue.py\", line 161, in get\r\nxprende.blog     |     raise Empty\r\nxprende.blog     | queue.Empty\r\nxprende.blog     | \r\nxprende.blog     | During handling of the above exception, another exception occurred:\r\nxprende.blog     | \r\nxprende.blog     | Traceback (most recent call last):\r\nxprende.blog     |   File \"/usr/local/lib/python3.6/site-packages/logstash_async/worker.py\", line 223, in _flush_queued_events\r\nxprende.blog     |     self._send_events(events)\r\nxprende.blog     |   File \"/usr/local/lib/python3.6/site-packages/logstash_async/worker.py\", line 253, in _send_events\r\nxprende.blog     |     self._transport.send(events)\r\nxprende.blog     |   File \"/usr/local/lib/python3.6/site-packages/logstash_async/transport.py\", line 28, in send\r\nxprende.blog     |     self._create_socket()\r\nxprende.blog     |   File \"/usr/local/lib/python3.6/site-packages/logstash_async/transport.py\", line 94, in _create_socket\r\nxprende.blog     |     sock.connect((self._host, self._port))\r\nxprende.blog     | ConnectionRefusedError: [Errno 111] Connection refused\r\n```\r\n\r\nAs you can see, the socket can't connect with `logstash`, but i can't understand why.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/20", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/20/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/20/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/20", "id": 294072199, "node_id": "MDU6SXNzdWUyOTQwNzIxOTk=", "number": 20, "title": "Gunicorn logging support", "user": {"login": "SalahAdDin", "id": 5034215, "node_id": "MDQ6VXNlcjUwMzQyMTU=", "avatar_url": "https://avatars2.githubusercontent.com/u/5034215?v=4", "gravatar_id": "", "url": "https://api.github.com/users/SalahAdDin", "html_url": "https://github.com/SalahAdDin", "followers_url": "https://api.github.com/users/SalahAdDin/followers", "following_url": "https://api.github.com/users/SalahAdDin/following{/other_user}", "gists_url": "https://api.github.com/users/SalahAdDin/gists{/gist_id}", "starred_url": "https://api.github.com/users/SalahAdDin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/SalahAdDin/subscriptions", "organizations_url": "https://api.github.com/users/SalahAdDin/orgs", "repos_url": "https://api.github.com/users/SalahAdDin/repos", "events_url": "https://api.github.com/users/SalahAdDin/events{/privacy}", "received_events_url": "https://api.github.com/users/SalahAdDin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-02-03T01:46:24Z", "updated_at": "2018-02-11T23:46:35Z", "closed_at": "2018-02-05T08:07:43Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, \r\nI just came to this package because the original isn't working very well.\r\n\r\nI wan't to know if i can use this package for log `gunicorn`.\r\n\r\nI did the next config file:\r\n```\r\n[loggers]\r\nkeys=root, logstash.error, logstash.access\r\n\r\n[handlers]\r\nkeys=console , logstash\r\n\r\n[formatters]\r\nkeys=generic, access, json\r\n\r\n[logger_root]\r\nlevel=INFO\r\nhandlers=console\r\n\r\n[logger_logstash.error]\r\nlevel=INFO\r\nhandlers=logstash\r\npropagate=1\r\nqualname=gunicorn.error\r\n\r\n[logger_logstash.access]\r\nlevel=INFO\r\nhandlers=logstash\r\npropagate=0\r\nqualname=gunicorn.access\r\n\r\n[handler_console]\r\nclass=StreamHandler\r\nformatter=generic\r\nargs=(sys.stdout, )\r\n\r\n[handler_logstash]\r\nclass=logstash_async.handler.AsynchronousLogstashHandler\r\nformatter=json\r\nversion=1\r\nargs=('logstash',5959, 'logstash.db')\r\n\r\n[formatter_generic]\r\nformat=%(asctime)s [%(process)d] [%(levelname)s] %(message)s\r\ndatefmt=%Y-%m-%d %H:%M:%S\r\nclass=logging.Formatter\r\n\r\n[formatter_access]\r\nformat=%(message)s\r\nclass=logging.Formatter\r\n\r\n[formatter_json]\r\nclass=pythonjsonlogger.jsonlogger.JsonFormatter\r\n```\r\n\r\nAs you can see i only change the `logstash` handler by this handler and i added the missing argument `data_base`.\r\n\r\nCan you make some documentation about it?\r\n\r\nThank you.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/17", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/17/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/17/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/17/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/17", "id": 283241677, "node_id": "MDU6SXNzdWUyODMyNDE2Nzc=", "number": 17, "title": "logstash-async ignoring formatter options", "user": {"login": "kostrahb", "id": 8557957, "node_id": "MDQ6VXNlcjg1NTc5NTc=", "avatar_url": "https://avatars0.githubusercontent.com/u/8557957?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kostrahb", "html_url": "https://github.com/kostrahb", "followers_url": "https://api.github.com/users/kostrahb/followers", "following_url": "https://api.github.com/users/kostrahb/following{/other_user}", "gists_url": "https://api.github.com/users/kostrahb/gists{/gist_id}", "starred_url": "https://api.github.com/users/kostrahb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kostrahb/subscriptions", "organizations_url": "https://api.github.com/users/kostrahb/orgs", "repos_url": "https://api.github.com/users/kostrahb/repos", "events_url": "https://api.github.com/users/kostrahb/events{/privacy}", "received_events_url": "https://api.github.com/users/kostrahb/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-12-19T14:08:51Z", "updated_at": "2017-12-22T10:45:20Z", "closed_at": "2017-12-21T14:58:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have encountered a problem, logstash logger seems to totally ignore formatter options when I create my own formatter with custom options. To be precise I can pass formatter to logger (It might be a little bit obscure way but I was inspired by logstash-async implementation itself) and as it prints correct value it seems to became part of logger. But on the other side, in logstash I can only see the default `\"type\" => \"python-logstash\"` in the message. \r\n```\r\n#!/usr/bin/python\r\n\r\nimport logging\r\nimport sys\r\nfrom logstash_async.handler import AsynchronousLogstashHandler\r\nfrom logstash_async.formatter import LogstashFormatter\r\n\r\nhost = 'localhost'\r\nport = 5959\r\n\r\ntest_logger = logging.getLogger('test')\r\n\r\ntest_formatter = LogstashFormatter(message_type='abcd', tags=None, fqdn=False, extra_prefix='new', extra=None)\r\ntest_logger.formatter = test_formatter\r\n\r\ntest_logger.setLevel(logging.INFO)\r\ntest_logger.addHandler(AsynchronousLogstashHandler(\r\n    host, port, database_path='logstash.db'))\r\n\r\nprint test_logger.formatter._message_type\r\n\r\ntest_logger.warning('Test logstash warning message.')\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/16", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/16/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/16/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/16", "id": 281434765, "node_id": "MDU6SXNzdWUyODE0MzQ3NjU=", "number": 16, "title": "Jus wanted to say, Thanks", "user": {"login": "merqurio", "id": 1485056, "node_id": "MDQ6VXNlcjE0ODUwNTY=", "avatar_url": "https://avatars2.githubusercontent.com/u/1485056?v=4", "gravatar_id": "", "url": "https://api.github.com/users/merqurio", "html_url": "https://github.com/merqurio", "followers_url": "https://api.github.com/users/merqurio/followers", "following_url": "https://api.github.com/users/merqurio/following{/other_user}", "gists_url": "https://api.github.com/users/merqurio/gists{/gist_id}", "starred_url": "https://api.github.com/users/merqurio/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/merqurio/subscriptions", "organizations_url": "https://api.github.com/users/merqurio/orgs", "repos_url": "https://api.github.com/users/merqurio/repos", "events_url": "https://api.github.com/users/merqurio/events{/privacy}", "received_events_url": "https://api.github.com/users/merqurio/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-12-12T15:52:34Z", "updated_at": "2017-12-13T23:48:06Z", "closed_at": "2017-12-13T23:48:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "This is just what we were looking for. Thanks for sharing \ud83d\udc4d ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/14", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/14/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/14/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/14/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/14", "id": 266658698, "node_id": "MDU6SXNzdWUyNjY2NTg2OTg=", "number": 14, "title": "Add module to extras", "user": {"login": "szechyjs", "id": 847739, "node_id": "MDQ6VXNlcjg0NzczOQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/847739?v=4", "gravatar_id": "", "url": "https://api.github.com/users/szechyjs", "html_url": "https://github.com/szechyjs", "followers_url": "https://api.github.com/users/szechyjs/followers", "following_url": "https://api.github.com/users/szechyjs/following{/other_user}", "gists_url": "https://api.github.com/users/szechyjs/gists{/gist_id}", "starred_url": "https://api.github.com/users/szechyjs/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/szechyjs/subscriptions", "organizations_url": "https://api.github.com/users/szechyjs/orgs", "repos_url": "https://api.github.com/users/szechyjs/repos", "events_url": "https://api.github.com/users/szechyjs/events{/privacy}", "received_events_url": "https://api.github.com/users/szechyjs/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "eht16", "id": 617017, "node_id": "MDQ6VXNlcjYxNzAxNw==", "avatar_url": "https://avatars3.githubusercontent.com/u/617017?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eht16", "html_url": "https://github.com/eht16", "followers_url": "https://api.github.com/users/eht16/followers", "following_url": "https://api.github.com/users/eht16/following{/other_user}", "gists_url": "https://api.github.com/users/eht16/gists{/gist_id}", "starred_url": "https://api.github.com/users/eht16/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eht16/subscriptions", "organizations_url": "https://api.github.com/users/eht16/orgs", "repos_url": "https://api.github.com/users/eht16/repos", "events_url": "https://api.github.com/users/eht16/events{/privacy}", "received_events_url": "https://api.github.com/users/eht16/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "eht16", "id": 617017, "node_id": "MDQ6VXNlcjYxNzAxNw==", "avatar_url": "https://avatars3.githubusercontent.com/u/617017?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eht16", "html_url": "https://github.com/eht16", "followers_url": "https://api.github.com/users/eht16/followers", "following_url": "https://api.github.com/users/eht16/following{/other_user}", "gists_url": "https://api.github.com/users/eht16/gists{/gist_id}", "starred_url": "https://api.github.com/users/eht16/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eht16/subscriptions", "organizations_url": "https://api.github.com/users/eht16/orgs", "repos_url": "https://api.github.com/users/eht16/repos", "events_url": "https://api.github.com/users/eht16/events{/privacy}", "received_events_url": "https://api.github.com/users/eht16/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2017-10-18T22:11:12Z", "updated_at": "2017-10-21T14:01:20Z", "closed_at": "2017-10-21T13:57:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "How can I add the `module` attribute to the default extras?\r\n\r\nhttps://docs.python.org/2/library/logging.html#logrecord-attributes", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/13", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/13/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/13/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/13", "id": 265293095, "node_id": "MDU6SXNzdWUyNjUyOTMwOTU=", "number": 13, "title": "Manually send shutdown event or customize constants", "user": {"login": "d1skort", "id": 5669713, "node_id": "MDQ6VXNlcjU2Njk3MTM=", "avatar_url": "https://avatars0.githubusercontent.com/u/5669713?v=4", "gravatar_id": "", "url": "https://api.github.com/users/d1skort", "html_url": "https://github.com/d1skort", "followers_url": "https://api.github.com/users/d1skort/followers", "following_url": "https://api.github.com/users/d1skort/following{/other_user}", "gists_url": "https://api.github.com/users/d1skort/gists{/gist_id}", "starred_url": "https://api.github.com/users/d1skort/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/d1skort/subscriptions", "organizations_url": "https://api.github.com/users/d1skort/orgs", "repos_url": "https://api.github.com/users/d1skort/repos", "events_url": "https://api.github.com/users/d1skort/events{/privacy}", "received_events_url": "https://api.github.com/users/d1skort/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-10-13T13:41:17Z", "updated_at": "2017-10-22T13:23:09Z", "closed_at": "2017-10-22T13:23:09Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hi!\r\n\r\nFirst of all, I want to say thank you for your library. It helps me a lot :)\r\n\r\nBut I have some problem here: sometimes I want to manually push all messages from database to logstash\r\n\r\nMaybe, ability to customize constants (from constants.py) would help me, idk\r\n\r\nI can do PR, if you say me, what solution the better, by your opinion", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/11", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/11/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/11/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/11", "id": 254741870, "node_id": "MDU6SXNzdWUyNTQ3NDE4NzA=", "number": 11, "title": "Memory cache with timeout", "user": {"login": "loganasherjones", "id": 3633332, "node_id": "MDQ6VXNlcjM2MzMzMzI=", "avatar_url": "https://avatars0.githubusercontent.com/u/3633332?v=4", "gravatar_id": "", "url": "https://api.github.com/users/loganasherjones", "html_url": "https://github.com/loganasherjones", "followers_url": "https://api.github.com/users/loganasherjones/followers", "following_url": "https://api.github.com/users/loganasherjones/following{/other_user}", "gists_url": "https://api.github.com/users/loganasherjones/gists{/gist_id}", "starred_url": "https://api.github.com/users/loganasherjones/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/loganasherjones/subscriptions", "organizations_url": "https://api.github.com/users/loganasherjones/orgs", "repos_url": "https://api.github.com/users/loganasherjones/repos", "events_url": "https://api.github.com/users/loganasherjones/events{/privacy}", "received_events_url": "https://api.github.com/users/loganasherjones/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-09-01T20:18:21Z", "updated_at": "2017-10-21T14:24:53Z", "closed_at": "2017-10-21T14:24:53Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hey! First, thanks so much for this library. \r\n\r\nI would like to implement a backend that does not persist to disk. I'm thinking of doing this by adding a TTL on the messages along with some new config values. If I did this and submitted a PR, would you be interested in accepting it?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/10", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/10/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/10/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/10", "id": 252175875, "node_id": "MDU6SXNzdWUyNTIxNzU4NzU=", "number": 10, "title": "Is this lib fork-safe?", "user": {"login": "xsren", "id": 4971925, "node_id": "MDQ6VXNlcjQ5NzE5MjU=", "avatar_url": "https://avatars0.githubusercontent.com/u/4971925?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xsren", "html_url": "https://github.com/xsren", "followers_url": "https://api.github.com/users/xsren/followers", "following_url": "https://api.github.com/users/xsren/following{/other_user}", "gists_url": "https://api.github.com/users/xsren/gists{/gist_id}", "starred_url": "https://api.github.com/users/xsren/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xsren/subscriptions", "organizations_url": "https://api.github.com/users/xsren/orgs", "repos_url": "https://api.github.com/users/xsren/repos", "events_url": "https://api.github.com/users/xsren/events{/privacy}", "received_events_url": "https://api.github.com/users/xsren/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-08-23T06:38:18Z", "updated_at": "2017-08-24T00:46:25Z", "closed_at": "2017-08-23T22:03:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello! Can I use this log handler in multi processing program in UNIX/LINUX system?\r\n\r\nThanks for your great job!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/8", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/8/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/8/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/8", "id": 243937101, "node_id": "MDU6SXNzdWUyNDM5MzcxMDE=", "number": 8, "title": " all non-ASCII characters in the output escaped with \\uXXXX sequence", "user": {"login": "DanGion", "id": 30260253, "node_id": "MDQ6VXNlcjMwMjYwMjUz", "avatar_url": "https://avatars1.githubusercontent.com/u/30260253?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DanGion", "html_url": "https://github.com/DanGion", "followers_url": "https://api.github.com/users/DanGion/followers", "following_url": "https://api.github.com/users/DanGion/following{/other_user}", "gists_url": "https://api.github.com/users/DanGion/gists{/gist_id}", "starred_url": "https://api.github.com/users/DanGion/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DanGion/subscriptions", "organizations_url": "https://api.github.com/users/DanGion/orgs", "repos_url": "https://api.github.com/users/DanGion/repos", "events_url": "https://api.github.com/users/DanGion/events{/privacy}", "received_events_url": "https://api.github.com/users/DanGion/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-07-19T06:39:57Z", "updated_at": "2017-07-23T10:55:30Z", "closed_at": "2017-07-23T10:55:30Z", "author_association": "NONE", "active_lock_reason": null, "body": "See https://github.com/eht16/python-logstash-async/pull/9", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/5", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/5/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/5/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/5", "id": 223451460, "node_id": "MDU6SXNzdWUyMjM0NTE0NjA=", "number": 5, "title": "The default value for database_path doesn't work", "user": {"login": "leifurhauks", "id": 5378335, "node_id": "MDQ6VXNlcjUzNzgzMzU=", "avatar_url": "https://avatars1.githubusercontent.com/u/5378335?v=4", "gravatar_id": "", "url": "https://api.github.com/users/leifurhauks", "html_url": "https://github.com/leifurhauks", "followers_url": "https://api.github.com/users/leifurhauks/followers", "following_url": "https://api.github.com/users/leifurhauks/following{/other_user}", "gists_url": "https://api.github.com/users/leifurhauks/gists{/gist_id}", "starred_url": "https://api.github.com/users/leifurhauks/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/leifurhauks/subscriptions", "organizations_url": "https://api.github.com/users/leifurhauks/orgs", "repos_url": "https://api.github.com/users/leifurhauks/repos", "events_url": "https://api.github.com/users/leifurhauks/events{/privacy}", "received_events_url": "https://api.github.com/users/leifurhauks/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-04-21T17:46:10Z", "updated_at": "2017-05-06T14:16:42Z", "closed_at": "2017-05-06T14:16:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "The default value for database_path, `:memory:`, currently doesn't work with this library because every connection to `:memory:` creates a separate in-memory database. I suggest either providing a generic filename for an on-disk database file, such as `log_event_queue.sqlite3`, or making the `database_path` argument to `AsynchronousLogstashHandler` required.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/eht16/python-logstash-async/issues/3", "repository_url": "https://api.github.com/repos/eht16/python-logstash-async", "labels_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/3/comments", "events_url": "https://api.github.com/repos/eht16/python-logstash-async/issues/3/events", "html_url": "https://github.com/eht16/python-logstash-async/issues/3", "id": 203339362, "node_id": "MDU6SXNzdWUyMDMzMzkzNjI=", "number": 3, "title": "python3 cross compatibility and django=1.8", "user": {"login": "ornoone", "id": 5380232, "node_id": "MDQ6VXNlcjUzODAyMzI=", "avatar_url": "https://avatars1.githubusercontent.com/u/5380232?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ornoone", "html_url": "https://github.com/ornoone", "followers_url": "https://api.github.com/users/ornoone/followers", "following_url": "https://api.github.com/users/ornoone/following{/other_user}", "gists_url": "https://api.github.com/users/ornoone/gists{/gist_id}", "starred_url": "https://api.github.com/users/ornoone/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ornoone/subscriptions", "organizations_url": "https://api.github.com/users/ornoone/orgs", "repos_url": "https://api.github.com/users/ornoone/repos", "events_url": "https://api.github.com/users/ornoone/events{/privacy}", "received_events_url": "https://api.github.com/users/ornoone/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-01-26T10:38:15Z", "updated_at": "2017-05-06T14:15:58Z", "closed_at": "2017-05-06T14:14:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "hi, i am experiencing some bug while using the DjangoLogstashFormatter with django 1.8 and python 3.4. \r\n\r\nit seem that this lib is not compatible with either one by 2 at least two lines : \r\n\r\n> logstash_async/formatter.py:235  ``extra_fields['req_uri'] = request.get_raw_uri()``\r\n\r\nbut django WSGIRequest object has no `get_raw_uri()` in version 1.8 (LTS). I propose to skip this extra_fields for later versions.\r\n\r\n> logstash_async/formatter.py:236: ``extra_fields['req_user'] = unicode(request.user) if request.user else ''``\r\n\r\nyou use unicode, which is a 2.7 only string type. you can either import six or do a try: except ImportError for string types to be cross compatible.\r\n\r\nthis is the only 2 things a saw for now, but I will keep investigating.\r\n\r\nit is a best practice to support from current LTS to current stable for your app. that's why I speak about 1.8... \r\nhttps://www.djangoproject.com/download/#supported-versions\r\n\r\nIf you want to be python3 compatible and LTS compatible, I can eagerly do a PR to fix all thing a found and build some unittests to check it all. \r\n\r\n", "performed_via_github_app": null, "score": 1.0}]}