{"total_count": 495, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/504", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/504/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/504/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/504/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/504", "id": 683593669, "node_id": "MDU6SXNzdWU2ODM1OTM2Njk=", "number": 504, "title": "FLASK", "user": {"login": "Rushil-Sharma", "id": 68117666, "node_id": "MDQ6VXNlcjY4MTE3NjY2", "avatar_url": "https://avatars2.githubusercontent.com/u/68117666?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Rushil-Sharma", "html_url": "https://github.com/Rushil-Sharma", "followers_url": "https://api.github.com/users/Rushil-Sharma/followers", "following_url": "https://api.github.com/users/Rushil-Sharma/following{/other_user}", "gists_url": "https://api.github.com/users/Rushil-Sharma/gists{/gist_id}", "starred_url": "https://api.github.com/users/Rushil-Sharma/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Rushil-Sharma/subscriptions", "organizations_url": "https://api.github.com/users/Rushil-Sharma/orgs", "repos_url": "https://api.github.com/users/Rushil-Sharma/repos", "events_url": "https://api.github.com/users/Rushil-Sharma/events{/privacy}", "received_events_url": "https://api.github.com/users/Rushil-Sharma/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-08-21T14:15:58Z", "updated_at": "2020-08-21T14:15:58Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "hey i am new to python and am 7 yars old\r\n-----\r\ncan someone help me with this thing called ```flask```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/503", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/503/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/503/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/503/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/503", "id": 683485218, "node_id": "MDU6SXNzdWU2ODM0ODUyMTg=", "number": 503, "title": "can someone help me ", "user": {"login": "Rushil-Sharma", "id": 68117666, "node_id": "MDQ6VXNlcjY4MTE3NjY2", "avatar_url": "https://avatars2.githubusercontent.com/u/68117666?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Rushil-Sharma", "html_url": "https://github.com/Rushil-Sharma", "followers_url": "https://api.github.com/users/Rushil-Sharma/followers", "following_url": "https://api.github.com/users/Rushil-Sharma/following{/other_user}", "gists_url": "https://api.github.com/users/Rushil-Sharma/gists{/gist_id}", "starred_url": "https://api.github.com/users/Rushil-Sharma/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Rushil-Sharma/subscriptions", "organizations_url": "https://api.github.com/users/Rushil-Sharma/orgs", "repos_url": "https://api.github.com/users/Rushil-Sharma/repos", "events_url": "https://api.github.com/users/Rushil-Sharma/events{/privacy}", "received_events_url": "https://api.github.com/users/Rushil-Sharma/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-08-21T11:10:18Z", "updated_at": "2020-08-21T11:10:18Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "  File \"jarvis_main_code.py\", line 49, in <module>\r\n    Listen()\r\n  File \"jarvis_main_code.py\", line 35, in Listen\r\n    with sr.Microphone as source :\r\nAttributeError: __enter__\r\n___________someone plz help____________", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/502", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/502/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/502/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/502/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/502", "id": 683130218, "node_id": "MDU6SXNzdWU2ODMxMzAyMTg=", "number": 502, "title": "Azure Voice Recognition API - Access Denied", "user": {"login": "hankp46", "id": 19395891, "node_id": "MDQ6VXNlcjE5Mzk1ODkx", "avatar_url": "https://avatars1.githubusercontent.com/u/19395891?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hankp46", "html_url": "https://github.com/hankp46", "followers_url": "https://api.github.com/users/hankp46/followers", "following_url": "https://api.github.com/users/hankp46/following{/other_user}", "gists_url": "https://api.github.com/users/hankp46/gists{/gist_id}", "starred_url": "https://api.github.com/users/hankp46/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hankp46/subscriptions", "organizations_url": "https://api.github.com/users/hankp46/orgs", "repos_url": "https://api.github.com/users/hankp46/repos", "events_url": "https://api.github.com/users/hankp46/events{/privacy}", "received_events_url": "https://api.github.com/users/hankp46/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2020-08-20T22:18:56Z", "updated_at": "2020-08-21T23:56:36Z", "closed_at": "2020-08-21T14:20:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to run ther microphone_recognition.py with the Azure APiI\r\nI modified the _init.py_ script to add the Azure Function\r\nScript is as follows:\r\n`#!/usr/bin/env python3\r\nimport speech_recognition as sr\r\n\r\nr = sr.Recognizer()\r\nwith sr.Microphone() as source:\r\n    print(\"Say something!\")\r\n    audio = r.listen(source)\r\n\r\nAZURE_SPEECH_KEY = \"32  character key\"  # Microsoft Speech API keys 32-character lowercase hexadecimal strings\\\r\n\r\ntry:\r\n    print(\"Microsoft Azure Speech thinks you said \" + r.recognize_azure(audio, key=AZURE_SPEECH_KEY))\r\nexcept sr.UnknownValueError:\r\n    print(\"Microsoft Azure Speech could not understand audio\")\r\nexcept sr.RequestError as e:\r\n    print(\"Could not request results from Microsoft Azure Speech service; {0}\".format(e))\r\n\r\n`\r\nObviously blanked out key. But I copied directly from my Azure Portal.\r\n\r\nResults were:\r\n\r\n**Could not request results from Microsoft Azure Speech service; credential request failed: Access Denied**\r\n\r\nI added a line to init_py to print out my key and it print out correctly", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/501", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/501/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/501/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/501/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/501", "id": 677638795, "node_id": "MDU6SXNzdWU2Nzc2Mzg3OTU=", "number": 501, "title": "Audio file passed with BytesIO is not supported", "user": {"login": "Cioscos", "id": 36228780, "node_id": "MDQ6VXNlcjM2MjI4Nzgw", "avatar_url": "https://avatars2.githubusercontent.com/u/36228780?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Cioscos", "html_url": "https://github.com/Cioscos", "followers_url": "https://api.github.com/users/Cioscos/followers", "following_url": "https://api.github.com/users/Cioscos/following{/other_user}", "gists_url": "https://api.github.com/users/Cioscos/gists{/gist_id}", "starred_url": "https://api.github.com/users/Cioscos/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Cioscos/subscriptions", "organizations_url": "https://api.github.com/users/Cioscos/orgs", "repos_url": "https://api.github.com/users/Cioscos/repos", "events_url": "https://api.github.com/users/Cioscos/events{/privacy}", "received_events_url": "https://api.github.com/users/Cioscos/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-08-12T12:08:24Z", "updated_at": "2020-08-12T12:08:24Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I want to pass to AudioFile a BytesIO. Now because my file is an ogg and speech_recognition doesn't support ogg, I convert it to wav and then I give it as argoument. This is the code:\r\n\r\n```Python\r\ndownloaded_file = file.download_as_bytearray()\r\nfinal_file = io.BytesIO()\r\n\r\nrecording = AudioSegment.from_ogg(io.BytesIO(downloaded_file))\r\nrecording.export(final_file, format='wav')\r\n\r\nwith sr.AudioFile(final_file) as source:\r\n    audio = r.record(source)\r\n```\r\nTo convert, I use the Pydub library.\r\n\r\nThis is the traceback:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/speech_recognition/__init__.py\", line 203, in __enter__\r\n    self.audio_reader = wave.open(self.filename_or_fileobject, \"rb\")\r\n  File \"/usr/lib/python3.6/wave.py\", line 499, in open\r\n    return Wave_read(f)\r\n  File \"/usr/lib/python3.6/wave.py\", line 163, in __init__\r\n    self.initfp(f)\r\n  File \"/usr/lib/python3.6/wave.py\", line 128, in initfp\r\n    self._file = Chunk(file, bigendian = 0)\r\n  File \"/usr/lib/python3.6/chunk.py\", line 63, in __init__\r\n    raise EOFError\r\nEOFError\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/speech_recognition/__init__.py\", line 208, in __enter__\r\n    self.audio_reader = aifc.open(self.filename_or_fileobject, \"rb\")\r\n  File \"/usr/lib/python3.6/aifc.py\", line 913, in open\r\n    return Aifc_read(f)\r\n  File \"/usr/lib/python3.6/aifc.py\", line 358, in __init__\r\n    self.initfp(f)\r\n  File \"/usr/lib/python3.6/aifc.py\", line 314, in initfp\r\n    chunk = Chunk(file)\r\n  File \"/usr/lib/python3.6/chunk.py\", line 63, in __init__\r\n    raise EOFError\r\nEOFError\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/speech_recognition/__init__.py\", line 234, in __enter__\r\n    self.audio_reader = aifc.open(aiff_file, \"rb\")\r\n  File \"/usr/lib/python3.6/aifc.py\", line 913, in open\r\n    return Aifc_read(f)\r\n  File \"/usr/lib/python3.6/aifc.py\", line 358, in __init__\r\n    self.initfp(f)\r\n  File \"/usr/lib/python3.6/aifc.py\", line 314, in initfp\r\n    chunk = Chunk(file)\r\n  File \"/usr/lib/python3.6/chunk.py\", line 63, in __init__\r\n    raise EOFError\r\nEOFError\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py\", line 353, in process_update\r\n    self.dispatch_error(update, e)\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py\", line 522, in dispatch_error\r\n    callback(update, CallbackContext.from_error(update, error, self))\r\n  File \"lovelace.py\", line 27, in error_callback\r\n    raise context.error\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py\", line 340, in process_update\r\n    handler.handle_update(update, self, check, context)\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/telegram/ext/handler.py\", line 119, in handle_update\r\n    return self.callback(update, context)\r\n  File \"lovelace.py\", line 182, in speech_to_text\r\n    with sr.AudioFile(final_file) as source:\r\n  File \"/home/claudio/PycharmProjects/lovelace-bot/venv/lib/python3.6/site-packages/speech_recognition/__init__.py\", line 236, in __enter__\r\n    raise ValueError(\"Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format\")\r\n```\r\nWhat I do wrong?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/500", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/500/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/500/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/500/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/500", "id": 676989522, "node_id": "MDU6SXNzdWU2NzY5ODk1MjI=", "number": 500, "title": "@Dave234322 there\u2019s probably configuration in pycharm that you need to do to point to the correct Python installation. Try to run it from the terminal and see if you get the same thing. If you do you probably need to install pip.", "user": {"login": "kaushal1222333", "id": 59066565, "node_id": "MDQ6VXNlcjU5MDY2NTY1", "avatar_url": "https://avatars2.githubusercontent.com/u/59066565?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kaushal1222333", "html_url": "https://github.com/kaushal1222333", "followers_url": "https://api.github.com/users/kaushal1222333/followers", "following_url": "https://api.github.com/users/kaushal1222333/following{/other_user}", "gists_url": "https://api.github.com/users/kaushal1222333/gists{/gist_id}", "starred_url": "https://api.github.com/users/kaushal1222333/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kaushal1222333/subscriptions", "organizations_url": "https://api.github.com/users/kaushal1222333/orgs", "repos_url": "https://api.github.com/users/kaushal1222333/repos", "events_url": "https://api.github.com/users/kaushal1222333/events{/privacy}", "received_events_url": "https://api.github.com/users/kaushal1222333/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-08-11T15:48:58Z", "updated_at": "2020-08-11T15:53:22Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "speech recognition is not working", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/499", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/499/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/499/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/499/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/499", "id": 674260535, "node_id": "MDU6SXNzdWU2NzQyNjA1MzU=", "number": 499, "title": "What is Google Speech Recognition?", "user": {"login": "gtsoumis", "id": 22564635, "node_id": "MDQ6VXNlcjIyNTY0NjM1", "avatar_url": "https://avatars2.githubusercontent.com/u/22564635?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gtsoumis", "html_url": "https://github.com/gtsoumis", "followers_url": "https://api.github.com/users/gtsoumis/followers", "following_url": "https://api.github.com/users/gtsoumis/following{/other_user}", "gists_url": "https://api.github.com/users/gtsoumis/gists{/gist_id}", "starred_url": "https://api.github.com/users/gtsoumis/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gtsoumis/subscriptions", "organizations_url": "https://api.github.com/users/gtsoumis/orgs", "repos_url": "https://api.github.com/users/gtsoumis/repos", "events_url": "https://api.github.com/users/gtsoumis/events{/privacy}", "received_events_url": "https://api.github.com/users/gtsoumis/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-08-06T12:04:03Z", "updated_at": "2020-08-06T12:04:03Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I know this is not exactly an issue, but I haven't been able to find some relevant information by myself. I've been using speech recognition for my dissertation, and now I'm writing up the report, and I want to have a small section on google recognition. So which API is it using? Is it what google calls \"web speech\"?\r\n\r\nThanks!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/498", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/498/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/498/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/498/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/498", "id": 670718935, "node_id": "MDU6SXNzdWU2NzA3MTg5MzU=", "number": 498, "title": "Speech Recognition not working", "user": {"login": "Dave234322", "id": 69074958, "node_id": "MDQ6VXNlcjY5MDc0OTU4", "avatar_url": "https://avatars3.githubusercontent.com/u/69074958?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Dave234322", "html_url": "https://github.com/Dave234322", "followers_url": "https://api.github.com/users/Dave234322/followers", "following_url": "https://api.github.com/users/Dave234322/following{/other_user}", "gists_url": "https://api.github.com/users/Dave234322/gists{/gist_id}", "starred_url": "https://api.github.com/users/Dave234322/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Dave234322/subscriptions", "organizations_url": "https://api.github.com/users/Dave234322/orgs", "repos_url": "https://api.github.com/users/Dave234322/repos", "events_url": "https://api.github.com/users/Dave234322/events{/privacy}", "received_events_url": "https://api.github.com/users/Dave234322/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-08-01T09:56:00Z", "updated_at": "2020-08-05T02:55:45Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I am trying to use speech recognition on python 3.8 i am fairly new to programming and i have tried multiple solution such as using pip to install pyaudio but it says \"Command 'pip' not found but there are 18 similar ones\" the code i am using is:\r\n\r\nimport speech_recognition as sr\r\n\r\nr = sr.Recognizer()\r\nwith sr.Microphone() as source:\r\n    print(\"Say something!\")\r\n    audio = r.listen(source)\r\n\r\ntry:\r\n    print(\"You said: \" + r.recognize_google(audio))\r\nexcept sr.UnknownValueError:\r\n    print(\"Google Speech Recognition could not understand audio\")\r\nexcept sr.RequestError as e:\r\n    print(\"Could not request results from Google Speech Recognition service; {0}\".format(e))\r\n\r\nthe error i get is:\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/isaac/.config/JetBrains/PyCharmCE2020.2/scratches/scratch.py\", line 5, in <module>\r\n    with sr.Microphone() as source:\r\n  File \"/usr/local/lib/python3.8/dist-packages/speech_recognition/__init__.py\", line 79, in __init__\r\n    self.pyaudio_module = self.get_pyaudio()\r\n  File \"/usr/local/lib/python3.8/dist-packages/speech_recognition/__init__.py\", line 110, in get_pyaudio\r\n    raise AttributeError(\"Could not find PyAudio; check installation\")\r\nAttributeError: Could not find PyAudio; check installation\r\n\r\nProcess finished with exit code 1\r\n\r\n\r\nI am using Ubuntu 20.04 and using the software pycharm ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/497", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/497/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/497/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/497/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/497", "id": 669782786, "node_id": "MDU6SXNzdWU2Njk3ODI3ODY=", "number": 497, "title": "Compatiblity", "user": {"login": "caue-alves", "id": 65175502, "node_id": "MDQ6VXNlcjY1MTc1NTAy", "avatar_url": "https://avatars2.githubusercontent.com/u/65175502?v=4", "gravatar_id": "", "url": "https://api.github.com/users/caue-alves", "html_url": "https://github.com/caue-alves", "followers_url": "https://api.github.com/users/caue-alves/followers", "following_url": "https://api.github.com/users/caue-alves/following{/other_user}", "gists_url": "https://api.github.com/users/caue-alves/gists{/gist_id}", "starred_url": "https://api.github.com/users/caue-alves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/caue-alves/subscriptions", "organizations_url": "https://api.github.com/users/caue-alves/orgs", "repos_url": "https://api.github.com/users/caue-alves/repos", "events_url": "https://api.github.com/users/caue-alves/events{/privacy}", "received_events_url": "https://api.github.com/users/caue-alves/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-31T12:48:47Z", "updated_at": "2020-07-31T12:48:47Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Please uptade the module to Python 3.8 versions\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/496", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/496/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/496/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/496/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/496", "id": 666755447, "node_id": "MDU6SXNzdWU2NjY3NTU0NDc=", "number": 496, "title": "wit.ai documentation returns 404", "user": {"login": "EdwardTheLegend", "id": 40855056, "node_id": "MDQ6VXNlcjQwODU1MDU2", "avatar_url": "https://avatars3.githubusercontent.com/u/40855056?v=4", "gravatar_id": "", "url": "https://api.github.com/users/EdwardTheLegend", "html_url": "https://github.com/EdwardTheLegend", "followers_url": "https://api.github.com/users/EdwardTheLegend/followers", "following_url": "https://api.github.com/users/EdwardTheLegend/following{/other_user}", "gists_url": "https://api.github.com/users/EdwardTheLegend/gists{/gist_id}", "starred_url": "https://api.github.com/users/EdwardTheLegend/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/EdwardTheLegend/subscriptions", "organizations_url": "https://api.github.com/users/EdwardTheLegend/orgs", "repos_url": "https://api.github.com/users/EdwardTheLegend/repos", "events_url": "https://api.github.com/users/EdwardTheLegend/events{/privacy}", "received_events_url": "https://api.github.com/users/EdwardTheLegend/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-28T04:37:59Z", "updated_at": "2020-07-28T04:37:59Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I was trying to go to https://wit.ai/docs but I got 404 same for everything else under docs", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/495", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/495/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/495/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/495/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/495", "id": 658311149, "node_id": "MDU6SXNzdWU2NTgzMTExNDk=", "number": 495, "title": "speech-recognition used to work when i have windows 1909 but when i upgrade 2004 it is not stopping microphone that it can register", "user": {"login": "Aaris-Kazi", "id": 40735215, "node_id": "MDQ6VXNlcjQwNzM1MjE1", "avatar_url": "https://avatars3.githubusercontent.com/u/40735215?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Aaris-Kazi", "html_url": "https://github.com/Aaris-Kazi", "followers_url": "https://api.github.com/users/Aaris-Kazi/followers", "following_url": "https://api.github.com/users/Aaris-Kazi/following{/other_user}", "gists_url": "https://api.github.com/users/Aaris-Kazi/gists{/gist_id}", "starred_url": "https://api.github.com/users/Aaris-Kazi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Aaris-Kazi/subscriptions", "organizations_url": "https://api.github.com/users/Aaris-Kazi/orgs", "repos_url": "https://api.github.com/users/Aaris-Kazi/repos", "events_url": "https://api.github.com/users/Aaris-Kazi/events{/privacy}", "received_events_url": "https://api.github.com/users/Aaris-Kazi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-16T15:34:43Z", "updated_at": "2020-07-16T15:36:41Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I have windows and i was working with a project it was working fine when i had 1909 but when i upgrade my windows its not working ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/494", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/494/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/494/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/494/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/494", "id": 657914512, "node_id": "MDU6SXNzdWU2NTc5MTQ1MTI=", "number": 494, "title": "installing pyaudio", "user": {"login": "Saishankar2001", "id": 66024735, "node_id": "MDQ6VXNlcjY2MDI0NzM1", "avatar_url": "https://avatars3.githubusercontent.com/u/66024735?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Saishankar2001", "html_url": "https://github.com/Saishankar2001", "followers_url": "https://api.github.com/users/Saishankar2001/followers", "following_url": "https://api.github.com/users/Saishankar2001/following{/other_user}", "gists_url": "https://api.github.com/users/Saishankar2001/gists{/gist_id}", "starred_url": "https://api.github.com/users/Saishankar2001/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Saishankar2001/subscriptions", "organizations_url": "https://api.github.com/users/Saishankar2001/orgs", "repos_url": "https://api.github.com/users/Saishankar2001/repos", "events_url": "https://api.github.com/users/Saishankar2001/events{/privacy}", "received_events_url": "https://api.github.com/users/Saishankar2001/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-16T07:10:08Z", "updated_at": "2020-07-16T07:11:04Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Steps to reproduce\r\n----------------\r\n\r\n1. (How do you make the issue happen? Does it happen every time you try it?)\r\n2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)\r\n\r\nimport speech_recognition as sr\r\nimport pyaudio\r\n\r\nr = sr.Recognizer()\r\n\r\nwith sr.Microphone() as source:\r\n    print(\"can u speak??\")\r\n    text = r.listen(source)\r\n\r\n    try:\r\n        recognised_text = r.recognize_google(text)\r\n        print(\"recognised text\")\r\n\r\n    except sr.UnknownValueError:\r\n        print(\"value error\")\r\n\r\n    except sr.RequestError as e:\r\n        print(\"request error\")\r\n\r\n\r\n3. (If there are any files, like audio recordings, don't forget to include them.)\r\n\r\nExpected behaviour:\r\nprogram should run successfully\r\n------------------\r\n\r\n(What did you expect to happen?)\r\n\r\nActual behaviour:\r\n in get_pyaudio\r\n  raise AttributeError(\"Could not find PyAudio; check installation\")\r\nAttributeError: Could not find PyAudio; check installation\r\n----------------\r\n\r\n(What happened instead? How is it different from what you expected?)\r\n\r\n```\r\n(If the library threw an exception, paste the full stack trace here)\r\n```\r\n\r\nSystem information\r\n------------------\r\n\r\n(Delete all the statements that don't apply.)\r\n\r\nMy **system** is <INSERT SYSTEM HERE>. (For example, \"Ubuntu 16.04 LTS x64\", \"Windows 10 x64\", or \"macOS Sierra\".)\r\n\r\nMy **Python version** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)\r\n\r\nMy **Pip version** is <INSERT VERSION HERE>. (You can check this by running `pip -V`.)\r\n\r\nMy **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c \"import speech_recognition as sr;print(sr.__version__)\"`.)\r\n\r\nMy **PyAudio library version** is <INSERT VERSION HERE> / I don't have PyAudio installed. (You can check this by running `python -c \"import pyaudio as p;print(p.__version__)\"`.)\r\n\r\nMy **microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_microphone_names())\"`.)\r\n\r\nMy **working microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_working_microphones())\"`.)\r\n\r\nI **installed PocketSphinx from** <INSERT SOURCE HERE>. (For example, from the Debian repositories, from Homebrew, or from the source code.)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/493", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/493/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/493/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/493/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/493", "id": 657910155, "node_id": "MDU6SXNzdWU2NTc5MTAxNTU=", "number": 493, "title": "installing pyaudio", "user": {"login": "Saishankar2001", "id": 66024735, "node_id": "MDQ6VXNlcjY2MDI0NzM1", "avatar_url": "https://avatars3.githubusercontent.com/u/66024735?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Saishankar2001", "html_url": "https://github.com/Saishankar2001", "followers_url": "https://api.github.com/users/Saishankar2001/followers", "following_url": "https://api.github.com/users/Saishankar2001/following{/other_user}", "gists_url": "https://api.github.com/users/Saishankar2001/gists{/gist_id}", "starred_url": "https://api.github.com/users/Saishankar2001/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Saishankar2001/subscriptions", "organizations_url": "https://api.github.com/users/Saishankar2001/orgs", "repos_url": "https://api.github.com/users/Saishankar2001/repos", "events_url": "https://api.github.com/users/Saishankar2001/events{/privacy}", "received_events_url": "https://api.github.com/users/Saishankar2001/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-16T07:04:46Z", "updated_at": "2020-07-16T07:05:35Z", "closed_at": "2020-07-16T07:05:35Z", "author_association": "NONE", "active_lock_reason": null, "body": "Steps to reproduce\r\n------------------\r\n\r\n1. (How do you make the issue happen? Does it happen every time you try it?)\r\n2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)\r\n3. (If there are any files, like audio recordings, don't forget to include them.)\r\n\r\nExpected behaviour\r\n------------------\r\n\r\n(What did you expect to happen?)\r\n\r\nActual behaviour\r\n----------------\r\n\r\n(What happened instead? How is it different from what you expected?)\r\n\r\n```\r\n(If the library threw an exception, paste the full stack trace here)\r\n```\r\n\r\nSystem information\r\n------------------\r\n\r\n(Delete all the statements that don't apply.)\r\n\r\nMy **system** is <INSERT SYSTEM HERE>. (For example, \"Ubuntu 16.04 LTS x64\", \"Windows 10 x64\", or \"macOS Sierra\".)\r\n\r\nMy **Python version** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)\r\n\r\nMy **Pip version** is <INSERT VERSION HERE>. (You can check this by running `pip -V`.)\r\n\r\nMy **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c \"import speech_recognition as sr;print(sr.__version__)\"`.)\r\n\r\nMy **PyAudio library version** is <INSERT VERSION HERE> / I don't have PyAudio installed. (You can check this by running `python -c \"import pyaudio as p;print(p.__version__)\"`.)\r\n\r\nMy **microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_microphone_names())\"`.)\r\n\r\nMy **working microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_working_microphones())\"`.)\r\n\r\nI **installed PocketSphinx from** <INSERT SOURCE HERE>. (For example, from the Debian repositories, from Homebrew, or from the source code.)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/492", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/492/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/492/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/492/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/492", "id": 654921547, "node_id": "MDU6SXNzdWU2NTQ5MjE1NDc=", "number": 492, "title": "OSError: [Errno -9999] Unanticipated host error", "user": {"login": "dongzizhu", "id": 38762574, "node_id": "MDQ6VXNlcjM4NzYyNTc0", "avatar_url": "https://avatars0.githubusercontent.com/u/38762574?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dongzizhu", "html_url": "https://github.com/dongzizhu", "followers_url": "https://api.github.com/users/dongzizhu/followers", "following_url": "https://api.github.com/users/dongzizhu/following{/other_user}", "gists_url": "https://api.github.com/users/dongzizhu/gists{/gist_id}", "starred_url": "https://api.github.com/users/dongzizhu/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dongzizhu/subscriptions", "organizations_url": "https://api.github.com/users/dongzizhu/orgs", "repos_url": "https://api.github.com/users/dongzizhu/repos", "events_url": "https://api.github.com/users/dongzizhu/events{/privacy}", "received_events_url": "https://api.github.com/users/dongzizhu/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-10T17:15:44Z", "updated_at": "2020-07-10T17:15:44Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "It's killing me that a simple example of pyaudio couldn't work. I'm trying to record my voice using pyaudio like this:\r\n```\r\nimport pyaudio\r\nimport wave\r\n\r\nCHUNK = 1024\r\nFORMAT = pyaudio.paInt16\r\nCHANNELS = 2\r\nRATE = 44100\r\nRECORD_SECONDS = 5\r\nWAVE_OUTPUT_FILENAME = \"output.wav\"\r\n\r\np = pyaudio.PyAudio()\r\n\r\nstream = p.open(format=FORMAT,\r\n                channels=CHANNELS,\r\n                rate=RATE,\r\n                input=True,\r\n                frames_per_buffer=CHUNK)\r\n\r\nprint(\"* recording\")\r\n\r\nframes = []\r\n\r\nfor i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):\r\n    data = stream.read(CHUNK)\r\n    frames.append(data)\r\n\r\nprint(\"* done recording\")\r\n\r\nstream.stop_stream()\r\nstream.close()\r\np.terminate()\r\n\r\nwf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')\r\nwf.setnchannels(CHANNELS)\r\nwf.setsampwidth(p.get_sample_size(FORMAT))\r\nwf.setframerate(RATE)\r\nwf.writeframes(b''.join(frames))\r\nwf.close()\r\n```\r\n\r\nthe error report like this:\r\nTraceback (most recent call last):\r\n  File \"D:/projects/recording/test.py\", line 17, in <module>\r\n    frames_per_buffer=CHUNK)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\pyaudio.py\", line 750, in open\r\n    stream = Stream(self, *args, **kwargs)\r\n  File \"C:\\Program Files\\Python36\\lib\\site-packages\\pyaudio.py\", line 441, in __init__\r\n    self._stream = pa.open(**arguments)\r\nOSError: [Errno -9999] Unanticipated host error\r\n\r\nThe strange thing is that this code work just fine on my other computer. I'm thinking maybe something's wrong with the mic. \r\nThanks so much!\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/491", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/491/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/491/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/491/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/491", "id": 654646230, "node_id": "MDU6SXNzdWU2NTQ2NDYyMzA=", "number": 491, "title": "Problem with microphone when using Speech Recognition", "user": {"login": "redrussianarmy", "id": 24498747, "node_id": "MDQ6VXNlcjI0NDk4NzQ3", "avatar_url": "https://avatars1.githubusercontent.com/u/24498747?v=4", "gravatar_id": "", "url": "https://api.github.com/users/redrussianarmy", "html_url": "https://github.com/redrussianarmy", "followers_url": "https://api.github.com/users/redrussianarmy/followers", "following_url": "https://api.github.com/users/redrussianarmy/following{/other_user}", "gists_url": "https://api.github.com/users/redrussianarmy/gists{/gist_id}", "starred_url": "https://api.github.com/users/redrussianarmy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/redrussianarmy/subscriptions", "organizations_url": "https://api.github.com/users/redrussianarmy/orgs", "repos_url": "https://api.github.com/users/redrussianarmy/repos", "events_url": "https://api.github.com/users/redrussianarmy/events{/privacy}", "received_events_url": "https://api.github.com/users/redrussianarmy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-07-10T09:24:51Z", "updated_at": "2020-07-10T09:24:51Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I have a Jetson Xavier, USB Microphone and Webcam having mic inside. Totaly, 2 mics. I am using Speech Recognition. When I try to use both webcam and usb mic, mic on webcam is taken by software as default. I want to use USB Mic when I plugged in both devices. I have found its device_index and I have written into software. However I have got an error as:\r\n\r\n **\"OSError: [Errno -9997] Invalid sample rate\"**\r\n\r\nThis is my microphone:\r\n\r\n**Microphone with name \"UAC 1.0 Microphone & HID-Mediak: USB Audio (hw:2,0)\" found for `Microphone(device_index=24)**\r\n\r\nI have tried to change sample rate to 44100. Error has disappeared but mic did not work.\r\n\r\nP.S.: USB Mic works normally when I plug in it alone. Code uses it as default. I have problem only when I have 2 connected devices.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/490", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/490/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/490/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/490/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/490", "id": 643006561, "node_id": "MDU6SXNzdWU2NDMwMDY1NjE=", "number": 490, "title": "discussion: Code quality issues with (some) fixes found", "user": {"login": "pnijhara", "id": 40136154, "node_id": "MDQ6VXNlcjQwMTM2MTU0", "avatar_url": "https://avatars0.githubusercontent.com/u/40136154?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pnijhara", "html_url": "https://github.com/pnijhara", "followers_url": "https://api.github.com/users/pnijhara/followers", "following_url": "https://api.github.com/users/pnijhara/following{/other_user}", "gists_url": "https://api.github.com/users/pnijhara/gists{/gist_id}", "starred_url": "https://api.github.com/users/pnijhara/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pnijhara/subscriptions", "organizations_url": "https://api.github.com/users/pnijhara/orgs", "repos_url": "https://api.github.com/users/pnijhara/repos", "events_url": "https://api.github.com/users/pnijhara/events{/privacy}", "received_events_url": "https://api.github.com/users/pnijhara/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-06-22T11:55:37Z", "updated_at": "2020-06-22T11:56:02Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I have forked the repo and ran DeepSource analysis on it by adding a `deepsource.toml` [file](https://github.com/pnijhara/speech_recognition/blob/pnijhara-patch-1/.deepsource.toml).\r\nWhere I found a total of around 100+ code quality issues.\r\n- Antipatterns: 19 (3 of which can be auto fixed)\r\n- Bug-risks: 5\r\n- Performance issues: 6 (5 of which can be auto fixed)\r\n- Security issues: 79 (65 of which can be auto fixed)\r\n\r\n## Expected behaviour\r\nBehaviour may remain same however, these fixes can improve the code quality of the project.\r\n\r\nIn all total number of issues are listed here - https://deepsource.io/gh/pnijhara/speech_recognition/issues/?category=recommended\r\n\r\nLink to `.deepsource.toml` configuration file that I have added to the forked repo for running DeepSource analysis can be found [here](https://github.com/pnijhara/speech_recognition/blob/pnijhara-patch-1/.deepsource.toml)\r\n\r\nWhich of these issues you would consider high priority, and which ones would you want to ignore or consider false-positive?\r\n\r\nI can send a PR with some fixes if you want.\r\nYou can also activate this analysis on your own, and have it triggered on each PR if you integrate DeepSource in the repo\r\n\r\nDisclaimer: I work for [DeepSource](https://deepsource.io)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/489", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/489/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/489/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/489/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/489", "id": 642313874, "node_id": "MDU6SXNzdWU2NDIzMTM4NzQ=", "number": 489, "title": "assert source.stream is not None, \"Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?\" AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?", "user": {"login": "AshishKumarsahoo123", "id": 53402323, "node_id": "MDQ6VXNlcjUzNDAyMzIz", "avatar_url": "https://avatars0.githubusercontent.com/u/53402323?v=4", "gravatar_id": "", "url": "https://api.github.com/users/AshishKumarsahoo123", "html_url": "https://github.com/AshishKumarsahoo123", "followers_url": "https://api.github.com/users/AshishKumarsahoo123/followers", "following_url": "https://api.github.com/users/AshishKumarsahoo123/following{/other_user}", "gists_url": "https://api.github.com/users/AshishKumarsahoo123/gists{/gist_id}", "starred_url": "https://api.github.com/users/AshishKumarsahoo123/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/AshishKumarsahoo123/subscriptions", "organizations_url": "https://api.github.com/users/AshishKumarsahoo123/orgs", "repos_url": "https://api.github.com/users/AshishKumarsahoo123/repos", "events_url": "https://api.github.com/users/AshishKumarsahoo123/events{/privacy}", "received_events_url": "https://api.github.com/users/AshishKumarsahoo123/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-06-20T05:35:03Z", "updated_at": "2020-06-20T05:35:03Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Steps to reproduce\r\n------------------\r\n\r\n1. (How do you make the issue happen? Does it happen every time you try it?)\r\n2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)\r\n3. (If there are any files, like audio recordings, don't forget to include them.)\r\n\r\nExpected behaviour\r\n------------------\r\n\r\n(What did you expect to happen?)\r\n\r\nActual behaviour\r\n----------------\r\n\r\n(What happened instead? How is it different from what you expected?)\r\n\r\n```\r\n(If the library threw an exception, paste the full stack trace here)\r\n```\r\n\r\nSystem information\r\n------------------\r\n\r\n(Delete all the statements that don't apply.)\r\n\r\nMy **system** is <INSERT SYSTEM HERE>. (For example, \"Ubuntu 16.04 LTS x64\", \"Windows 10 x64\", or \"macOS Sierra\".)\r\n\r\nMy **Python version** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)\r\n\r\nMy **Pip version** is <INSERT VERSION HERE>. (You can check this by running `pip -V`.)\r\n\r\nMy **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c \"import speech_recognition as sr;print(sr.__version__)\"`.)\r\n\r\nMy **PyAudio library version** is <INSERT VERSION HERE> / I don't have PyAudio installed. (You can check this by running `python -c \"import pyaudio as p;print(p.__version__)\"`.)\r\n\r\nMy **microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_microphone_names())\"`.)\r\n\r\nMy **working microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_working_microphones())\"`.)\r\n\r\nI **installed PocketSphinx from** <INSERT SOURCE HERE>. (For example, from the Debian repositories, from Homebrew, or from the source code.)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/488", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/488/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/488/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/488/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/488", "id": 630681197, "node_id": "MDU6SXNzdWU2MzA2ODExOTc=", "number": 488, "title": "Error for SpeechRecognition", "user": {"login": "ARQAMZz", "id": 63594415, "node_id": "MDQ6VXNlcjYzNTk0NDE1", "avatar_url": "https://avatars2.githubusercontent.com/u/63594415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ARQAMZz", "html_url": "https://github.com/ARQAMZz", "followers_url": "https://api.github.com/users/ARQAMZz/followers", "following_url": "https://api.github.com/users/ARQAMZz/following{/other_user}", "gists_url": "https://api.github.com/users/ARQAMZz/gists{/gist_id}", "starred_url": "https://api.github.com/users/ARQAMZz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ARQAMZz/subscriptions", "organizations_url": "https://api.github.com/users/ARQAMZz/orgs", "repos_url": "https://api.github.com/users/ARQAMZz/repos", "events_url": "https://api.github.com/users/ARQAMZz/events{/privacy}", "received_events_url": "https://api.github.com/users/ARQAMZz/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-06-04T09:54:59Z", "updated_at": "2020-06-08T12:34:43Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Hi Guys,\r\nI was trying to make this thing which typed whatever the user has spoken.But I keep geting an error.\r\nSomeone on STackOverflw told me that he ran my code and it worked fine.\r\nhttps://stackoverflow.com/questions/62178729/valueerror-for-pyaudio?noredirect=1#comment109991769_62178729\r\nFirst it was giving an error but when I changed it to this:\r\n ```\r\nimport speech_recognition as sr\r\n\r\nr = sr.Recognizer()\r\n\r\nwith sr.Microphone() as s:\r\n    r.adjust_for_ambient_noise(s)\r\n\r\n    while True:\r\n        print(\"Start Speaking\\n\")\r\n        audio = r.listen(s)\r\n        speech = r.recognize_google(audio, language = 'en-US')\r\n        print('Did you say: \\n', speech, show_all=True)\r\n```\r\nBut this leaves the line blank and cursor keeps blinking after the first print statement.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/487", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/487/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/487/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/487/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/487", "id": 624957564, "node_id": "MDU6SXNzdWU2MjQ5NTc1NjQ=", "number": 487, "title": "Audio Longer Than 1 min with Google Cloud", "user": {"login": "gminator", "id": 724922, "node_id": "MDQ6VXNlcjcyNDkyMg==", "avatar_url": "https://avatars2.githubusercontent.com/u/724922?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gminator", "html_url": "https://github.com/gminator", "followers_url": "https://api.github.com/users/gminator/followers", "following_url": "https://api.github.com/users/gminator/following{/other_user}", "gists_url": "https://api.github.com/users/gminator/gists{/gist_id}", "starred_url": "https://api.github.com/users/gminator/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gminator/subscriptions", "organizations_url": "https://api.github.com/users/gminator/orgs", "repos_url": "https://api.github.com/users/gminator/repos", "events_url": "https://api.github.com/users/gminator/events{/privacy}", "received_events_url": "https://api.github.com/users/gminator/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-05-26T15:08:17Z", "updated_at": "2020-05-26T15:08:17Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "HI, \r\n\r\nI'm getting the following error when using goolge cloud speech \r\n <HttpError 400 when requesting https://speech.googleapis.com/v1/speech:recognize?alt=json returned \"Sync input too long. For audio longer than 1 min use LongRunningRecognize with a 'uri' parameter.\">\r\n\r\nis there a way to specify LongRunningRecognize  as an option?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/486", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/486/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/486/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/486/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/486", "id": 623399629, "node_id": "MDU6SXNzdWU2MjMzOTk2Mjk=", "number": 486, "title": "Can I do recognition from numpy array?", "user": {"login": "PasaOpasen", "id": 45700689, "node_id": "MDQ6VXNlcjQ1NzAwNjg5", "avatar_url": "https://avatars2.githubusercontent.com/u/45700689?v=4", "gravatar_id": "", "url": "https://api.github.com/users/PasaOpasen", "html_url": "https://github.com/PasaOpasen", "followers_url": "https://api.github.com/users/PasaOpasen/followers", "following_url": "https://api.github.com/users/PasaOpasen/following{/other_user}", "gists_url": "https://api.github.com/users/PasaOpasen/gists{/gist_id}", "starred_url": "https://api.github.com/users/PasaOpasen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/PasaOpasen/subscriptions", "organizations_url": "https://api.github.com/users/PasaOpasen/orgs", "repos_url": "https://api.github.com/users/PasaOpasen/repos", "events_url": "https://api.github.com/users/PasaOpasen/events{/privacy}", "received_events_url": "https://api.github.com/users/PasaOpasen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-05-22T18:21:07Z", "updated_at": "2020-07-12T12:29:22Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I'm recording a numpy array `dt` and then writing it in .wav by code like this:\r\n```python\r\ndt = np.int16(dt/np.max(np.abs(dt)) * 32767)\r\nscipy.io.wavfile.write(\"tmp.wav\", samplerate, dt)\r\n```\r\nafter that I read it and recognize by code\r\n```python\r\nimport speech_recognition as sr\r\nr = sr.Recognizer()\r\nwith sr.AudioFile(\"tmp.wav\") as source:\r\n    audio_text = r.listen(source)\r\n    return r.recognize_google(audio_text, language = lang)\r\n```\r\n\r\nCan I do recognition from numpy array without using wav? Cuz it takes excess time \r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/485", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/485/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/485/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/485/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/485", "id": 621667700, "node_id": "MDU6SXNzdWU2MjE2Njc3MDA=", "number": 485, "title": "Oops! didnt catch that for every microphone", "user": {"login": "siddhantchimankar", "id": 50448021, "node_id": "MDQ6VXNlcjUwNDQ4MDIx", "avatar_url": "https://avatars0.githubusercontent.com/u/50448021?v=4", "gravatar_id": "", "url": "https://api.github.com/users/siddhantchimankar", "html_url": "https://github.com/siddhantchimankar", "followers_url": "https://api.github.com/users/siddhantchimankar/followers", "following_url": "https://api.github.com/users/siddhantchimankar/following{/other_user}", "gists_url": "https://api.github.com/users/siddhantchimankar/gists{/gist_id}", "starred_url": "https://api.github.com/users/siddhantchimankar/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/siddhantchimankar/subscriptions", "organizations_url": "https://api.github.com/users/siddhantchimankar/orgs", "repos_url": "https://api.github.com/users/siddhantchimankar/repos", "events_url": "https://api.github.com/users/siddhantchimankar/events{/privacy}", "received_events_url": "https://api.github.com/users/siddhantchimankar/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-05-20T10:58:11Z", "updated_at": "2020-05-20T10:58:11Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Steps to reproduce\r\n------------------\r\n\r\n1. (How do you make the issue happen? Does it happen every time you try it?)\r\n2. (Make sure to go into as much detail as needed to reproduce the issue. Posting your code here can help us resolve the problem much faster!)\r\n3. (If there are any files, like audio recordings, don't forget to include them.)\r\n\r\nExpected behaviour\r\n------------------\r\n\r\n(What did you expect to happen?)\r\n\r\nActual behaviour\r\n----------------\r\n\r\n(What happened instead? How is it different from what you expected?)\r\n\r\n```\r\n(If the library threw an exception, paste the full stack trace here)\r\n```\r\n\r\nSystem information\r\n------------------\r\n\r\n(Delete all the statements that don't apply.)\r\n\r\nMy **system** is <INSERT SYSTEM HERE>. (For example, \"Ubuntu 16.04 LTS x64\", \"Windows 10 x64\", or \"macOS Sierra\".)\r\n\r\nMy **Python version** is <INSERT VERSION HERE>. (You can check this by running `python -V`.)\r\n\r\nMy **Pip version** is <INSERT VERSION HERE>. (You can check this by running `pip -V`.)\r\n\r\nMy **SpeechRecognition library version** is <INSERT VERSION HERE>. (You can check this by running `python -c \"import speech_recognition as sr;print(sr.__version__)\"`.)\r\n\r\nMy **PyAudio library version** is <INSERT VERSION HERE> / I don't have PyAudio installed. (You can check this by running `python -c \"import pyaudio as p;print(p.__version__)\"`.)\r\n\r\nMy **microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_microphone_names())\"`.)\r\n\r\nMy **working microphones** are: (You can check this by running `python -c \"import speech_recognition as sr;print(sr.Microphone.list_working_microphones())\"`.)\r\n\r\nI **installed PocketSphinx from** <INSERT SOURCE HERE>. (For example, from the Debian repositories, from Homebrew, or from the source code.)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/484", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/484/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/484/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/484/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/484", "id": 621357028, "node_id": "MDU6SXNzdWU2MjEzNTcwMjg=", "number": 484, "title": "Upload i2s microphone data issue when adding line put data to firebase realtime. ", "user": {"login": "nghiadang391", "id": 59469404, "node_id": "MDQ6VXNlcjU5NDY5NDA0", "avatar_url": "https://avatars1.githubusercontent.com/u/59469404?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nghiadang391", "html_url": "https://github.com/nghiadang391", "followers_url": "https://api.github.com/users/nghiadang391/followers", "following_url": "https://api.github.com/users/nghiadang391/following{/other_user}", "gists_url": "https://api.github.com/users/nghiadang391/gists{/gist_id}", "starred_url": "https://api.github.com/users/nghiadang391/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nghiadang391/subscriptions", "organizations_url": "https://api.github.com/users/nghiadang391/orgs", "repos_url": "https://api.github.com/users/nghiadang391/repos", "events_url": "https://api.github.com/users/nghiadang391/events{/privacy}", "received_events_url": "https://api.github.com/users/nghiadang391/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-05-19T23:48:52Z", "updated_at": "2020-05-19T23:49:33Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Hi everyone,\r\nI am doing my project with I2s mic measure decibel then upload to Firebase pretty well but close to the end i face a really annoying issue.\r\nThe code run smooth and mesure quite accurate but when I add \"result=firebase.put(\"/Audio\",\"db\",kq) it ran in 2s and encounter error. I tried change the chunk and rate value but nothing happened.This is my code:\r\n#!/usr/bin/env python\r\nimport os, errno\r\nimport pyaudio\r\nimport spl_lib as spl\r\nfrom scipy.signal import lfilter\r\nimport numpy\r\nimport time\r\nnew_decibel = \"global\"\r\n\r\n\r\n## For web browser handling\r\n#from selenium import webdriver\r\nfrom firebase import firebase\r\nfirebase = firebase.FirebaseApplication(myurl,None)\r\n\r\n''' The following is similar to a basic CD quality\r\n   When CHUNK size is 4096 it routinely throws an IOError.\r\n   When it is set to 8192 it doesn't.\r\n   IOError happens due to the small CHUNK size\r\n\r\n   What is CHUNK? Let's say CHUNK = 4096\r\n   math.pow(2, 12) => RATE / CHUNK = 100ms = 0.1 sec\r\n'''\r\nCHUNK = 2048       # Use what you need\r\nFORMAT = pyaudio.paInt32    # 16 bit\r\nCHANNEL = 1    # 1 means mono. If stereo, put 2\r\n\r\n'''\r\nDifferent mics have different rates.\r\nFor example, Logitech HD 720p has rate 48000Hz\r\n'''\r\nRATE = 15000\r\n\r\nNUMERATOR, DENOMINATOR = spl.A_weighting(RATE)\r\n\r\n'''\r\nListen to mic\r\n'''\r\npa = pyaudio.PyAudio()\r\n\r\nstream = pa.open(format = FORMAT,\r\n                channels = CHANNEL,\r\n                rate = RATE,\r\n                input = True,\r\n                frames_per_buffer = CHUNK)\r\n    \r\n   \r\n    \r\n    \r\n    \r\n             \r\n\r\ndef update():\r\n        block = stream.read(CHUNK)\r\n        \r\n        decoded_block = numpy.frombuffer(block, dtype= 'Int32')\r\n                ## This is where you apply A-weighted filter\r\n        y = lfilter(NUMERATOR, DENOMINATOR, decoded_block)\r\n        new_decibel = 10*numpy.log10(spl.rms_flat(y))\r\n        \r\n        if new_decibel is not None:\r\n            kq = round(new_decibel,3) \r\n            print(kq)\r\n            \r\n        else:\r\n            stream.stop_stream()\r\n            stream.close()\r\n            pa.terminate()\r\n        firebase.put(\"/Audio\",\"db\", kq)\r\n        \r\nwhile True:\r\n    update()\r\n\r\nPlease help, I am appreciate you all.\r\nThanks for reading.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/483", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/483/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/483/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/483/events", "html_url": "https://github.com/Uberi/speech_recognition/pull/483", "id": 621200334, "node_id": "MDExOlB1bGxSZXF1ZXN0NDIwMjk1ODM3", "number": 483, "title": "update thread workers", "user": {"login": "AnksIndustries", "id": 43180246, "node_id": "MDQ6VXNlcjQzMTgwMjQ2", "avatar_url": "https://avatars3.githubusercontent.com/u/43180246?v=4", "gravatar_id": "", "url": "https://api.github.com/users/AnksIndustries", "html_url": "https://github.com/AnksIndustries", "followers_url": "https://api.github.com/users/AnksIndustries/followers", "following_url": "https://api.github.com/users/AnksIndustries/following{/other_user}", "gists_url": "https://api.github.com/users/AnksIndustries/gists{/gist_id}", "starred_url": "https://api.github.com/users/AnksIndustries/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/AnksIndustries/subscriptions", "organizations_url": "https://api.github.com/users/AnksIndustries/orgs", "repos_url": "https://api.github.com/users/AnksIndustries/repos", "events_url": "https://api.github.com/users/AnksIndustries/events{/privacy}", "received_events_url": "https://api.github.com/users/AnksIndustries/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-05-19T18:39:36Z", "updated_at": "2020-05-19T18:39:36Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/Uberi/speech_recognition/pulls/483", "html_url": "https://github.com/Uberi/speech_recognition/pull/483", "diff_url": "https://github.com/Uberi/speech_recognition/pull/483.diff", "patch_url": "https://github.com/Uberi/speech_recognition/pull/483.patch"}, "body": "works in windows and not tested in other environment\r\n\r\nadded sample rate and chunk size\r\nadded adjust_for_ambient_noise to remove noise\r\nand it works", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/482", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/482/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/482/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/482/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/482", "id": 617026015, "node_id": "MDU6SXNzdWU2MTcwMjYwMTU=", "number": 482, "title": "RequestError: recognition request failed: Bad Request", "user": {"login": "NapsYork", "id": 28992122, "node_id": "MDQ6VXNlcjI4OTkyMTIy", "avatar_url": "https://avatars1.githubusercontent.com/u/28992122?v=4", "gravatar_id": "", "url": "https://api.github.com/users/NapsYork", "html_url": "https://github.com/NapsYork", "followers_url": "https://api.github.com/users/NapsYork/followers", "following_url": "https://api.github.com/users/NapsYork/following{/other_user}", "gists_url": "https://api.github.com/users/NapsYork/gists{/gist_id}", "starred_url": "https://api.github.com/users/NapsYork/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/NapsYork/subscriptions", "organizations_url": "https://api.github.com/users/NapsYork/orgs", "repos_url": "https://api.github.com/users/NapsYork/repos", "events_url": "https://api.github.com/users/NapsYork/events{/privacy}", "received_events_url": "https://api.github.com/users/NapsYork/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-05-12T23:18:27Z", "updated_at": "2020-08-10T04:20:25Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "My code worked yesterday perfectly. Today I woke up and went to run the python script again and suddenly I was getting hit with \"Bad Request\" errors every time I tried to run it. I even went on another computer to do a quick transcription of an audio file using different code and I still got the same error.\r\n \r\n![Error_Capture](https://user-images.githubusercontent.com/28992122/81754852-89b71c80-948d-11ea-86b4-c8d4c770b397.PNG)\r\n\r\nI haven't the slightest clue whats going on. Was I blocked for sending too many requests? Its been stressing me out and I would appreciate any help anyone can give me. Thank you.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/481", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/481/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/481/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/481/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/481", "id": 613309918, "node_id": "MDU6SXNzdWU2MTMzMDk5MTg=", "number": 481, "title": "Speech recognition most of the time getting stuck at r.listen()", "user": {"login": "andydexter", "id": 26439807, "node_id": "MDQ6VXNlcjI2NDM5ODA3", "avatar_url": "https://avatars3.githubusercontent.com/u/26439807?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andydexter", "html_url": "https://github.com/andydexter", "followers_url": "https://api.github.com/users/andydexter/followers", "following_url": "https://api.github.com/users/andydexter/following{/other_user}", "gists_url": "https://api.github.com/users/andydexter/gists{/gist_id}", "starred_url": "https://api.github.com/users/andydexter/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andydexter/subscriptions", "organizations_url": "https://api.github.com/users/andydexter/orgs", "repos_url": "https://api.github.com/users/andydexter/repos", "events_url": "https://api.github.com/users/andydexter/events{/privacy}", "received_events_url": "https://api.github.com/users/andydexter/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-05-06T13:14:02Z", "updated_at": "2020-06-08T12:37:51Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Steps to reproduce\r\n------------------\r\n\r\nWhen I run the example program using r.listen() for pyaudio, sometimes it runs the first time but then, after I interrupt the program and run it again, it gets stuck on r.listen(). I inputed my device index on the microphone class. I got it working with a program that only listens once and then ends, and it worked the first couple of times, but each time the time it took for the listen() function to end increased. The only thing I can think that I can try is to close the microphone stream because it might still be in use after the program is interrupted, but I'm not sure what to call for that. Also I would assume that it's supposed to close automatically after the `with `statement? I use a webcam as my microphone and tried it with arecord and it works fine. \r\nMy code:\r\n```\r\nimport speech_recognition as sr\r\n# obtain audio from the microphone\r\nr = sr.Recognizer()\r\nwhile True:\r\n    with sr.Microphone(device_index=2) as source:\r\n        print(\"Say something!\")\r\n        audio = r.listen(source)\r\n    # recognize speech using Google Speech Recognition\r\n    try:\r\n        # for testing purposes, we're just using the default API key\r\n        # to use another API key, use `r.recognize_google(audio, key=\"GOOGLE_SPEECH_RECOGNITION_API_KEY\")`\r\n        # instead of `r.recognize_google(audio)`\r\n        print(\"recognising\")\r\n        recognised=r.recognize_google(audio, key=\"my key\")\r\n\r\n        #recognised=input()\r\n\r\n        print(\"Google Speech Recognition thinks you said \" + recognised)\r\n        request=keywordidentifier(recognised)\r\n        if not request==-1:\r\n            print(functionidentifier(request))\r\n\r\n    except sr.UnknownValueError:\r\n        print(\"Google Speech Recognition could not understand audio\")\r\n    except sr.RequestError as e:\r\n        print(\"Could not request results from Google Speech Recognition service; {0}\".format(e))\r\n```\r\n\r\n\r\nExpected behaviour\r\n------------------\r\n\r\nI tried to talk to the webcam, and as I said it sometimes worked, but most of the times I would leave it for a couple minutes and it wouldn't end the listen() function.\r\n\r\nActual behaviour\r\n----------------\r\n\r\nWhen I run this code in the terminal, this is the output:\r\n```\r\nExpression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924\r\nExpression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM front\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround21\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround21\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround40\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround41\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround50\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround51\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM surround71\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM spdif\r\nALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'\r\nALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory\r\nALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM spdif\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline\r\nALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline\r\nExpression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924\r\nSay something!\r\n```\r\n\r\nSystem information\r\n------------------\r\n\r\n(Delete all the statements that don't apply.)\r\n\r\nMy **system** is Raspbian GNU/Linux 10 (buster)\r\n\r\nMy **Python version** is Python 3.7.3\r\n\r\nMy **Pip version** is pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.7)\r\n\r\nMy **SpeechRecognition library version** is 3.8.1\r\n\r\nMy **PyAudio library version** is 0.2.11\r\n\r\nMy **microphones** are: ['bcm2835 ALSA: IEC958/HDMI (hw:0,1)', 'bcm2835 ALSA: IEC958/HDMI1 (hw:0,2)', 'USB Device 0x46d:0x825: Audio (hw:1,0)', 'dmix']\r\nMy **working microphones** are: 'USB Device 0x46d:0x825: Audio (hw:1,0)' device_index=2\r\n\r\nI'm using a raspberry pi 2 model B v1.1", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/480", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/480/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/480/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/480/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/480", "id": 610580798, "node_id": "MDU6SXNzdWU2MTA1ODA3OTg=", "number": 480, "title": "feature_request(docs): Languages, pricing and limits of speech recognition engines/API", "user": {"login": "Kristinita", "id": 17247677, "node_id": "MDQ6VXNlcjE3MjQ3Njc3", "avatar_url": "https://avatars2.githubusercontent.com/u/17247677?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Kristinita", "html_url": "https://github.com/Kristinita", "followers_url": "https://api.github.com/users/Kristinita/followers", "following_url": "https://api.github.com/users/Kristinita/following{/other_user}", "gists_url": "https://api.github.com/users/Kristinita/gists{/gist_id}", "starred_url": "https://api.github.com/users/Kristinita/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Kristinita/subscriptions", "organizations_url": "https://api.github.com/users/Kristinita/orgs", "repos_url": "https://api.github.com/users/Kristinita/repos", "events_url": "https://api.github.com/users/Kristinita/events{/privacy}", "received_events_url": "https://api.github.com/users/Kristinita/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-05-01T05:51:31Z", "updated_at": "2020-05-01T05:51:31Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### 1. Summary\n\nIt would be nice, if to SpeechRecognition documentation would be added links to these parameters of each [**speech recognition engines/API**](https://github.com/Uberi/speech_recognition#speechrecognition):\n\n1. Languages by supporting engine/API\n1. Pricing\n1. Limits of free plan (if exists)\n\n### 2. Argumentation\n\n#### 2.1. Common cause\n\nSaving a users time.\n\n#### 2.2. Details\n\nFor example, I searched free (and, if possible, open source) speech recognition engine/API, that support Russian language. I was forced to manually search, which engine/API meets these requirements. It took a hour of my time. If information on supported languages, pricing and limits would be in the SpeechRecognition documentation, I would save an hour of my time.\n\nSpeechRecognition has [**thousands downloads per day**](https://pypistats.org/packages/speechrecognition). Perhaps many users, like me, have spent a lot of their time to search for the required engine/API parameters.\n\nThanks.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/479", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/479/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/479/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/479/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/479", "id": 608190076, "node_id": "MDU6SXNzdWU2MDgxOTAwNzY=", "number": 479, "title": "how to give a audio numpy array as input for recognition?", "user": {"login": "abinramapuram", "id": 6545099, "node_id": "MDQ6VXNlcjY1NDUwOTk=", "avatar_url": "https://avatars1.githubusercontent.com/u/6545099?v=4", "gravatar_id": "", "url": "https://api.github.com/users/abinramapuram", "html_url": "https://github.com/abinramapuram", "followers_url": "https://api.github.com/users/abinramapuram/followers", "following_url": "https://api.github.com/users/abinramapuram/following{/other_user}", "gists_url": "https://api.github.com/users/abinramapuram/gists{/gist_id}", "starred_url": "https://api.github.com/users/abinramapuram/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/abinramapuram/subscriptions", "organizations_url": "https://api.github.com/users/abinramapuram/orgs", "repos_url": "https://api.github.com/users/abinramapuram/repos", "events_url": "https://api.github.com/users/abinramapuram/events{/privacy}", "received_events_url": "https://api.github.com/users/abinramapuram/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-04-28T10:05:31Z", "updated_at": "2020-04-28T10:05:31Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I have a numpy array of an audio file which is read by scipy.io.wavefile.read. How to give this array directly to the recognition api without using sr.Audiofile and r.record(source)?\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/478", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/478/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/478/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/478/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/478", "id": 598764915, "node_id": "MDU6SXNzdWU1OTg3NjQ5MTU=", "number": 478, "title": "Currently voice recognition accurate rate is worse then Jan even using same *.wav file ", "user": {"login": "tliang2017", "id": 25678745, "node_id": "MDQ6VXNlcjI1Njc4NzQ1", "avatar_url": "https://avatars2.githubusercontent.com/u/25678745?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tliang2017", "html_url": "https://github.com/tliang2017", "followers_url": "https://api.github.com/users/tliang2017/followers", "following_url": "https://api.github.com/users/tliang2017/following{/other_user}", "gists_url": "https://api.github.com/users/tliang2017/gists{/gist_id}", "starred_url": "https://api.github.com/users/tliang2017/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tliang2017/subscriptions", "organizations_url": "https://api.github.com/users/tliang2017/orgs", "repos_url": "https://api.github.com/users/tliang2017/repos", "events_url": "https://api.github.com/users/tliang2017/events{/privacy}", "received_events_url": "https://api.github.com/users/tliang2017/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-04-13T08:54:23Z", "updated_at": "2020-08-09T01:51:25Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Steps to reproduce\r\n------------------\r\n1. I found voice recognition result has some difference with result from about 3 month ago.\r\nI use one same file for recognition. -- file see as in attachment\r\n\r\nExpected behaviour\r\n------------------\r\n- Server will return: \"939 popsicle button on the headset if the code on your phone is for 73939 have the call button on the headset if the code\" -- same as I got the result on Jan 16, 2020, the accurate rate is very good\r\n\r\nActual behaviour\r\n----------------\r\n- Server return result is:\r\n\"939 tap the call button on the headset if the code on your phone is 499 button on the headset if the\"\r\n-- this is a lot of difference with the result that I got on  Jan 16, 2020, and for this time recognition result missing some numbers. I have try a lot of files, all have same observation.\r\nIs it any change on back end server to make this issue happen?\r\n\r\n```\r\n\r\nSystem information\r\n------------------\r\ncomments: \r\nCould you help to have a look? \r\nThanks in advance\r\n\r\naudio file see as in below link:\r\n\r\n[Record_Wave-2020-01-16_09_22_36.zip](https://github.com/Uberi/speech_recognition/files/4468754/Record_Wave-2020-01-16_09_22_36.zip)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/477", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/477/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/477/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/477/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/477", "id": 595514747, "node_id": "MDU6SXNzdWU1OTU1MTQ3NDc=", "number": 477, "title": "Julius", "user": {"login": "MikeyBeez", "id": 14264000, "node_id": "MDQ6VXNlcjE0MjY0MDAw", "avatar_url": "https://avatars0.githubusercontent.com/u/14264000?v=4", "gravatar_id": "", "url": "https://api.github.com/users/MikeyBeez", "html_url": "https://github.com/MikeyBeez", "followers_url": "https://api.github.com/users/MikeyBeez/followers", "following_url": "https://api.github.com/users/MikeyBeez/following{/other_user}", "gists_url": "https://api.github.com/users/MikeyBeez/gists{/gist_id}", "starred_url": "https://api.github.com/users/MikeyBeez/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/MikeyBeez/subscriptions", "organizations_url": "https://api.github.com/users/MikeyBeez/orgs", "repos_url": "https://api.github.com/users/MikeyBeez/repos", "events_url": "https://api.github.com/users/MikeyBeez/events{/privacy}", "received_events_url": "https://api.github.com/users/MikeyBeez/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-04-07T00:46:11Z", "updated_at": "2020-04-20T12:30:39Z", "closed_at": "2020-04-20T12:30:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm hoping to use the Julius STT engine and the word \"Julius\" as a wake word.  I have Juius running.  Checking the issues on the Julius Github page shows how to fix their installation issues.  It produces the following output:\r\n\r\npass1_best: <s> julius </s>\r\npass1_best_wordseq: <s> julius </s>\r\npass1_best_phonemeseq: sil | jh uw l y ah s | sil\r\npass1_best_score: 107.246803\r\n### Recognition: 2nd pass (RL heuristic best-first)\r\nSTAT: 00 _default: 18500 generated, 4081 pushed, 344 nodes popped in 102\r\nsentence1: <s> julius </s>\r\nwseq1: <s> julius </s>\r\nphseq1: sil | jh uw l y ah s | sil\r\ncmscore1: 0.764 0.673 1.000\r\nscore1: 89.203560\r\nInternalError: CMN_realtime_update: param->samplenum != c->now.framenum\r\n\r\nIt can correctly identified \"Julius\" over and over.  So that should make a great offline wake word.\r\n\r\nI'm not sure how to parse out the word however to kick off speech_recognition using gTTS.  I know this is not an issue with speech_recognition, but it could make a good addition; so that the microphone isn't sending to Google all the time.\r\n\r\nI hope I'm not being a pain.  Sorry if this is totally inappropriate.  I can't use snowboy because I'm on Ubuntu 18.04.\r\n  I can use any version of python in a virtual environment -- probably using conda.\r\n\r\nMy **SpeechRecognition library version** is 3.8.1\r\n\r\nMy **PyAudio library version** is 0.2.11\r\n\r\nALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave\r\n['HDA NVidia: HDMI 0 (hw:0,3)', 'HDA NVidia: HDMI 1 (hw:0,7)', 'HDA NVidia: HDMI 2 (hw:0,8)', 'HD-Audio Generic: ALCS1200A Analog (hw:1,0)', 'HD-Audio Generic: ALCS1200A Digital (hw:1,1)', 'HD-Audio Generic: ALCS1200A Alt Analog (hw:1,2)', 'USB Device 0x46d:0x823: Audio (hw:2,0)', 'hdmi', 'pulse', 'default']     \r\n\r\nBTW, here's the link to my installation video for Julius:  https://www.youtube.com/watch?v=A-oNmgJ7qcw\r\n\r\nThank you", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/476", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/476/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/476/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/476/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/476", "id": 594523011, "node_id": "MDU6SXNzdWU1OTQ1MjMwMTE=", "number": 476, "title": "SSL: CERTIFICATE_VERIFY_FAILED ", "user": {"login": "ddi98", "id": 43742625, "node_id": "MDQ6VXNlcjQzNzQyNjI1", "avatar_url": "https://avatars3.githubusercontent.com/u/43742625?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ddi98", "html_url": "https://github.com/ddi98", "followers_url": "https://api.github.com/users/ddi98/followers", "following_url": "https://api.github.com/users/ddi98/following{/other_user}", "gists_url": "https://api.github.com/users/ddi98/gists{/gist_id}", "starred_url": "https://api.github.com/users/ddi98/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ddi98/subscriptions", "organizations_url": "https://api.github.com/users/ddi98/orgs", "repos_url": "https://api.github.com/users/ddi98/repos", "events_url": "https://api.github.com/users/ddi98/events{/privacy}", "received_events_url": "https://api.github.com/users/ddi98/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-04-05T15:46:47Z", "updated_at": "2020-04-05T15:46:47Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "hi, when i try to connect with recognize_ibm, i get the following error:\r\n\r\nCould not request results from IBM Speech to Text service; recognition connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)\r\n\r\nhow do I disable verification of the ssl certificate? thank you very much", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/Uberi/speech_recognition/issues/475", "repository_url": "https://api.github.com/repos/Uberi/speech_recognition", "labels_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/475/labels{/name}", "comments_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/475/comments", "events_url": "https://api.github.com/repos/Uberi/speech_recognition/issues/475/events", "html_url": "https://github.com/Uberi/speech_recognition/issues/475", "id": 590036738, "node_id": "MDU6SXNzdWU1OTAwMzY3Mzg=", "number": 475, "title": " speech_recognition.AudioFile(mfile)  error?", "user": {"login": "ucas010", "id": 50656998, "node_id": "MDQ6VXNlcjUwNjU2OTk4", "avatar_url": "https://avatars1.githubusercontent.com/u/50656998?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ucas010", "html_url": "https://github.com/ucas010", "followers_url": "https://api.github.com/users/ucas010/followers", "following_url": "https://api.github.com/users/ucas010/following{/other_user}", "gists_url": "https://api.github.com/users/ucas010/gists{/gist_id}", "starred_url": "https://api.github.com/users/ucas010/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ucas010/subscriptions", "organizations_url": "https://api.github.com/users/ucas010/orgs", "repos_url": "https://api.github.com/users/ucas010/repos", "events_url": "https://api.github.com/users/ucas010/events{/privacy}", "received_events_url": "https://api.github.com/users/ucas010/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-03-30T06:45:59Z", "updated_at": "2020-03-30T06:45:59Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "hi,dear,\r\nI got the audio from video with ffmpeg,\r\nbut I have tried mp3,wav,flac format,ant the error is always here.\r\n```\r\nTraceback (most recent call last):\r\n  File \"D:/python36/new/speech_recongition_.py\", line 12, in <module>\r\n    with speech_recognition.AudioFile(mfile) as source:\r\n  File \"D:\\python36\\lib\\site-packages\\speech_recognition\\__init__.py\", line 236, in __enter__\r\n    raise ValueError(\"Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format\")\r\nValueError: Audio file could not be read as PCM WAV, AIFF/AIFF-C, or Native FLAC; check if file is corrupted or in another format\r\n```\r\ncould you please help me ?\r\nthx\r\n\r\n\r\nMy **system** is , \"Windows 10 x64\u201c\r\nMy **Python version** is <python3.6.8>.\r\nMy **Pip version** is <20.0.2>. \r\nMy **SpeechRecognition library version** is <3.8.1>. \r\nMy **PyAudio library version** is <0.2.11> \r\n\r\nMy **microphones** are: No\r\nMy **working microphones** are: No\r\n\r\nI **installed PocketSphinx from** <what's this ?how to install ?>.\r\n", "performed_via_github_app": null, "score": 1.0}]}