{"total_count": 43, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/fastai/fastprogress/issues/65", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/65/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/65/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/65/events", "html_url": "https://github.com/fastai/fastprogress/issues/65", "id": 628775812, "node_id": "MDU6SXNzdWU2Mjg3NzU4MTI=", "number": 65, "title": "Use of figsize kwarg causes error in console but not notebook", "user": {"login": "danielpcox", "id": 56411, "node_id": "MDQ6VXNlcjU2NDEx", "avatar_url": "https://avatars0.githubusercontent.com/u/56411?v=4", "gravatar_id": "", "url": "https://api.github.com/users/danielpcox", "html_url": "https://github.com/danielpcox", "followers_url": "https://api.github.com/users/danielpcox/followers", "following_url": "https://api.github.com/users/danielpcox/following{/other_user}", "gists_url": "https://api.github.com/users/danielpcox/gists{/gist_id}", "starred_url": "https://api.github.com/users/danielpcox/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/danielpcox/subscriptions", "organizations_url": "https://api.github.com/users/danielpcox/orgs", "repos_url": "https://api.github.com/users/danielpcox/repos", "events_url": "https://api.github.com/users/danielpcox/events{/privacy}", "received_events_url": "https://api.github.com/users/danielpcox/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2020-06-01T22:45:47Z", "updated_at": "2020-08-20T02:33:09Z", "closed_at": "2020-08-20T02:33:09Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "I have a traceback complaining of an unexpected kwarg 'figsize' when running outside of a notebook, but not when running in a notebook, or even when running in nbdev_test_nbs.\r\n\r\nI think I can see what's up: [According to these lines](https://github.com/fastai/fastprogress/blob/master/fastprogress/fastprogress.py#L292), the master_bar is a completely different class when running in the console versus when running in a notebook, and the update_graph method has a different signature. More precisely, it doesn't take **kwargs. My use of update_graph looks like this:\r\n\r\n```\r\nbar.update_graph(plot, figsize=(10,5))\r\n```\r\n\r\nFull traceback:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.7/threading.py\", line 917, in _bootstrap_inner\r\n    self.run()\r\n  File \"/usr/local/lib/python3.7/threading.py\", line 865, in run\r\n    self._target(*self._args, **self._kwargs)\r\n  File \"/app/lad/anomalies.py\", line 120, in _train\r\n    self.models[service].train(data_path=data_path, epochs=epochs, reporter=reporter)\r\n  File \"/app/lad/model.py\", line 410, in train\r\n    reporter=reporter)\r\n  File \"/app/lad/model.py\", line 344, in train\r\n    vis(mb,len_dataloader,epoch-start_epoch,i,[train_losses,val_losses])\r\n  File \"/app/lad/model.py\", line 288, in vis\r\n    bar.update_graph(plot, figsize=(10,5))\r\nTypeError: update_graph() got an unexpected keyword argument 'figsize'\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/63", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/63/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/63/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/63/events", "html_url": "https://github.com/fastai/fastprogress/issues/63", "id": 620285093, "node_id": "MDU6SXNzdWU2MjAyODUwOTM=", "number": 63, "title": "Master bar not showing in console", "user": {"login": "tcapelle", "id": 18441985, "node_id": "MDQ6VXNlcjE4NDQxOTg1", "avatar_url": "https://avatars0.githubusercontent.com/u/18441985?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tcapelle", "html_url": "https://github.com/tcapelle", "followers_url": "https://api.github.com/users/tcapelle/followers", "following_url": "https://api.github.com/users/tcapelle/following{/other_user}", "gists_url": "https://api.github.com/users/tcapelle/gists{/gist_id}", "starred_url": "https://api.github.com/users/tcapelle/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tcapelle/subscriptions", "organizations_url": "https://api.github.com/users/tcapelle/orgs", "repos_url": "https://api.github.com/users/tcapelle/repos", "events_url": "https://api.github.com/users/tcapelle/events{/privacy}", "received_events_url": "https://api.github.com/users/tcapelle/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-05-18T15:06:06Z", "updated_at": "2020-05-18T15:13:38Z", "closed_at": "2020-05-18T15:13:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "The master bar is not showing on console.\r\n```python\r\nbar = master_bar(range(10))\r\nfor e in bar:\r\n    for i in progress_bar(range(10), parent=bar):\r\n        sleep(0.05)\r\n```\r\nOn the notebook I get what I want, but not on the terminal.\r\n![image](https://user-images.githubusercontent.com/18441985/82228626-a76f0080-9929-11ea-8fdb-c4957a5b708e.png)\r\nBut on console only get the child bar:\r\n![image](https://user-images.githubusercontent.com/18441985/82228724-ca99b000-9929-11ea-8fa7-4d96b9b4f022.png)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/61", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/61/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/61/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/61/events", "html_url": "https://github.com/fastai/fastprogress/issues/61", "id": 604607250, "node_id": "MDU6SXNzdWU2MDQ2MDcyNTA=", "number": 61, "title": "Progress Bar on Pycharm?", "user": {"login": "bomcon123456", "id": 20278911, "node_id": "MDQ6VXNlcjIwMjc4OTEx", "avatar_url": "https://avatars0.githubusercontent.com/u/20278911?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bomcon123456", "html_url": "https://github.com/bomcon123456", "followers_url": "https://api.github.com/users/bomcon123456/followers", "following_url": "https://api.github.com/users/bomcon123456/following{/other_user}", "gists_url": "https://api.github.com/users/bomcon123456/gists{/gist_id}", "starred_url": "https://api.github.com/users/bomcon123456/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bomcon123456/subscriptions", "organizations_url": "https://api.github.com/users/bomcon123456/orgs", "repos_url": "https://api.github.com/users/bomcon123456/repos", "events_url": "https://api.github.com/users/bomcon123456/events{/privacy}", "received_events_url": "https://api.github.com/users/bomcon123456/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-04-22T09:34:42Z", "updated_at": "2020-04-23T01:55:31Z", "closed_at": "2020-04-23T01:55:31Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi I'm currently using Pycharm to run remote jupyter server, but when I'm training (using fastai2), the progress bar simply grey and not running at all (the train still ran and finished)\r\nThank you!\r\n![\u1ea3nh](https://user-images.githubusercontent.com/20278911/79966111-230a9880-84b7-11ea-8a6f-e467fa334c7f.png)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/60", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/60/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/60/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/60/events", "html_url": "https://github.com/fastai/fastprogress/issues/60", "id": 600489603, "node_id": "MDU6SXNzdWU2MDA0ODk2MDM=", "number": 60, "title": "AttributeError: 'NBMasterBar' object has no attribute 'out'", "user": {"login": "jayesh0vasudeva", "id": 42416623, "node_id": "MDQ6VXNlcjQyNDE2NjIz", "avatar_url": "https://avatars1.githubusercontent.com/u/42416623?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jayesh0vasudeva", "html_url": "https://github.com/jayesh0vasudeva", "followers_url": "https://api.github.com/users/jayesh0vasudeva/followers", "following_url": "https://api.github.com/users/jayesh0vasudeva/following{/other_user}", "gists_url": "https://api.github.com/users/jayesh0vasudeva/gists{/gist_id}", "starred_url": "https://api.github.com/users/jayesh0vasudeva/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jayesh0vasudeva/subscriptions", "organizations_url": "https://api.github.com/users/jayesh0vasudeva/orgs", "repos_url": "https://api.github.com/users/jayesh0vasudeva/repos", "events_url": "https://api.github.com/users/jayesh0vasudeva/events{/privacy}", "received_events_url": "https://api.github.com/users/jayesh0vasudeva/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-04-15T18:06:04Z", "updated_at": "2020-04-15T18:11:13Z", "closed_at": "2020-04-15T18:11:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "from the 10_nlp.ipynb, trying to fine tune the language model\r\n>>>  learn.fit_one_cycle(1, 2e-2)\r\n\r\n---------------------------------------------------------------------------\r\nAssertionError                            Traceback (most recent call last)\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)\r\n    187             try:\r\n--> 188                 self._do_begin_fit(n_epoch)\r\n    189                 for epoch in range(n_epoch):\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in _do_begin_fit(self, n_epoch)\r\n    159     def _do_begin_fit(self, n_epoch):\r\n--> 160         self.n_epoch,self.loss = n_epoch,tensor(0.);         self('begin_fit')\r\n    161 \r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in __call__(self, event_name)\r\n    123 \r\n--> 124     def __call__(self, event_name): L(event_name).map(self._call_one)\r\n    125     def _call_one(self, event_name):\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in map(self, f, *args, **kwargs)\r\n    371              else f.__getitem__)\r\n--> 372         return self._new(map(g, self))\r\n    373 \r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in _new(self, items, *args, **kwargs)\r\n    322     def _xtra(self): return None\r\n--> 323     def _new(self, items, *args, **kwargs): return type(self)(items, *args, use_list=None, **kwargs)\r\n    324     def __getitem__(self, idx): return self._get(idx) if is_indexer(idx) else L(self._get(idx), use_list=None)\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in __call__(cls, x, *args, **kwargs)\r\n     40 \r\n---> 41         res = super().__call__(*((x,) + args), **kwargs)\r\n     42         res._newchk = 0\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in __init__(self, items, use_list, match, *rest)\r\n    313         if (use_list is not None) or not _is_array(items):\r\n--> 314             items = list(items) if use_list else _listify(items)\r\n    315         if match is not None:\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in _listify(o)\r\n    249     if isinstance(o, str) or _is_array(o): return [o]\r\n--> 250     if is_iter(o): return list(o)\r\n    251     return [o]\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in __call__(self, *args, **kwargs)\r\n    215         fargs = [args[x.i] if isinstance(x, _Arg) else x for x in self.pargs] + args[self.maxi+1:]\r\n--> 216         return self.fn(*fargs, **kwargs)\r\n    217 \r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in _call_one(self, event_name)\r\n    126         assert hasattr(event, event_name)\r\n--> 127         [cb(event_name) for cb in sort_by_run(self.cbs)]\r\n    128 \r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in <listcomp>(.0)\r\n    126         assert hasattr(event, event_name)\r\n--> 127         [cb(event_name) for cb in sort_by_run(self.cbs)]\r\n    128 \r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/callback/core.py in __call__(self, event_name)\r\n     23                (self.run_valid and not getattr(self, 'training', False)))\r\n---> 24         if self.run and _run: getattr(self, event_name, noop)()\r\n     25         if event_name=='after_fit': self.run=True #Reset self.run to True at each end of fit\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/callback/fp16.py in begin_fit(self)\r\n     83     def begin_fit(self):\r\n---> 84         assert self.dls.device.type == 'cuda', \"Mixed-precision training requires a GPU, remove the call `to_fp16`\"\r\n     85         if self.learn.opt is None: self.learn.create_opt()\r\n\r\nAssertionError: Mixed-precision training requires a GPU, remove the call `to_fp16`\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-33-07c3fbbfd15e> in <module>\r\n----> 1 learn.fit_one_cycle(1, 2e-2)\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/callback/schedule.py in fit_one_cycle(self, n_epoch, lr_max, div, div_final, pct_start, wd, moms, cbs, reset_opt)\r\n    110     scheds = {'lr': combined_cos(pct_start, lr_max/div, lr_max, lr_max/div_final),\r\n    111               'mom': combined_cos(pct_start, *(self.moms if moms is None else moms))}\r\n--> 112     self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)\r\n    113 \r\n    114 # Cell\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)\r\n    196 \r\n    197             except CancelFitException:             self('after_cancel_fit')\r\n--> 198             finally:                               self('after_fit')\r\n    199 \r\n    200     def validate(self, ds_idx=1, dl=None, cbs=None):\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in __call__(self, event_name)\r\n    122     def ordered_cbs(self, event): return [cb for cb in sort_by_run(self.cbs) if hasattr(cb, event)]\r\n    123 \r\n--> 124     def __call__(self, event_name): L(event_name).map(self._call_one)\r\n    125     def _call_one(self, event_name):\r\n    126         assert hasattr(event, event_name)\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in map(self, f, *args, **kwargs)\r\n    370              else f.format if isinstance(f,str)\r\n    371              else f.__getitem__)\r\n--> 372         return self._new(map(g, self))\r\n    373 \r\n    374     def filter(self, f, negate=False, **kwargs):\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in _new(self, items, *args, **kwargs)\r\n    321     @property\r\n    322     def _xtra(self): return None\r\n--> 323     def _new(self, items, *args, **kwargs): return type(self)(items, *args, use_list=None, **kwargs)\r\n    324     def __getitem__(self, idx): return self._get(idx) if is_indexer(idx) else L(self._get(idx), use_list=None)\r\n    325     def copy(self): return self._new(self.items.copy())\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in __call__(cls, x, *args, **kwargs)\r\n     39             return x\r\n     40 \r\n---> 41         res = super().__call__(*((x,) + args), **kwargs)\r\n     42         res._newchk = 0\r\n     43         return res\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in __init__(self, items, use_list, match, *rest)\r\n    312         if items is None: items = []\r\n    313         if (use_list is not None) or not _is_array(items):\r\n--> 314             items = list(items) if use_list else _listify(items)\r\n    315         if match is not None:\r\n    316             if is_coll(match): match = len(match)\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in _listify(o)\r\n    248     if isinstance(o, list): return o\r\n    249     if isinstance(o, str) or _is_array(o): return [o]\r\n--> 250     if is_iter(o): return list(o)\r\n    251     return [o]\r\n    252 \r\n\r\n/opt/conda/lib/python3.7/site-packages/fastcore/foundation.py in __call__(self, *args, **kwargs)\r\n    214             if isinstance(v,_Arg): kwargs[k] = args.pop(v.i)\r\n    215         fargs = [args[x.i] if isinstance(x, _Arg) else x for x in self.pargs] + args[self.maxi+1:]\r\n--> 216         return self.fn(*fargs, **kwargs)\r\n    217 \r\n    218 # Cell\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in _call_one(self, event_name)\r\n    125     def _call_one(self, event_name):\r\n    126         assert hasattr(event, event_name)\r\n--> 127         [cb(event_name) for cb in sort_by_run(self.cbs)]\r\n    128 \r\n    129     def _bn_bias_state(self, with_bias): return bn_bias_params(self.model, with_bias).map(self.opt.state)\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/learner.py in <listcomp>(.0)\r\n    125     def _call_one(self, event_name):\r\n    126         assert hasattr(event, event_name)\r\n--> 127         [cb(event_name) for cb in sort_by_run(self.cbs)]\r\n    128 \r\n    129     def _bn_bias_state(self, with_bias): return bn_bias_params(self.model, with_bias).map(self.opt.state)\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/callback/core.py in __call__(self, event_name)\r\n     22         _run = (event_name not in _inner_loop or (self.run_train and getattr(self, 'training', True)) or\r\n     23                (self.run_valid and not getattr(self, 'training', False)))\r\n---> 24         if self.run and _run: getattr(self, event_name, noop)()\r\n     25         if event_name=='after_fit': self.run=True #Reset self.run to True at each end of fit\r\n     26 \r\n\r\n/opt/conda/lib/python3.7/site-packages/fastai2/callback/progress.py in after_fit(self)\r\n     37     def after_fit(self):\r\n     38         if getattr(self, 'mbar', False):\r\n---> 39             self.mbar.on_iter_end()\r\n     40             delattr(self, 'mbar')\r\n     41         self.learn.logger = self.old_logger\r\n\r\n/opt/conda/lib/python3.7/site-packages/fastprogress/fastprogress.py in on_iter_end(self)\r\n    155             total_time = format_time(time.time() - self.main_bar.start_t)\r\n    156             self.text = f'Total time: {total_time} <p>' + self.text\r\n--> 157         self.out.update(HTML(self.text))\r\n    158 \r\n    159     def add_child(self, child):\r\n\r\nAttributeError: 'NBMasterBar' object has no attribute 'out'", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/58", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/58/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/58/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/58/events", "html_url": "https://github.com/fastai/fastprogress/issues/58", "id": 595259409, "node_id": "MDU6SXNzdWU1OTUyNTk0MDk=", "number": 58, "title": "ImportError: cannot import name 'master_bar'", "user": {"login": "BlockchainRev", "id": 47613687, "node_id": "MDQ6VXNlcjQ3NjEzNjg3", "avatar_url": "https://avatars0.githubusercontent.com/u/47613687?v=4", "gravatar_id": "", "url": "https://api.github.com/users/BlockchainRev", "html_url": "https://github.com/BlockchainRev", "followers_url": "https://api.github.com/users/BlockchainRev/followers", "following_url": "https://api.github.com/users/BlockchainRev/following{/other_user}", "gists_url": "https://api.github.com/users/BlockchainRev/gists{/gist_id}", "starred_url": "https://api.github.com/users/BlockchainRev/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/BlockchainRev/subscriptions", "organizations_url": "https://api.github.com/users/BlockchainRev/orgs", "repos_url": "https://api.github.com/users/BlockchainRev/repos", "events_url": "https://api.github.com/users/BlockchainRev/events{/privacy}", "received_events_url": "https://api.github.com/users/BlockchainRev/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-04-06T16:35:24Z", "updated_at": "2020-04-06T16:37:19Z", "closed_at": "2020-04-06T16:37:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "`---------------------------------------------------------------------------\r\nImportError                               Traceback (most recent call last)\r\n<ipython-input-7-283c0d40bede> in <module>\r\n----> 1 from fastai.vision import *\r\n      2 from fastai.metrics import error_rate\r\n\r\n~\\Anaconda3\\envs\\fastai\\lib\\site-packages\\fastai\\__init__.py in <module>\r\n----> 1 from .basic_train import *\r\n      2 from .callback import *\r\n      3 #from .callbacks import *\r\n      4 from .core import *\r\n      5 from .basic_data import *\r\n\r\n~\\Anaconda3\\envs\\fastai\\lib\\site-packages\\fastai\\basic_train.py in <module>\r\n      1 \"Provides basic training and validation with `Learner`\"\r\n----> 2 from .torch_core import *\r\n      3 from .basic_data import *\r\n      4 from .callback import *\r\n      5 \r\n\r\n~\\Anaconda3\\envs\\fastai\\lib\\site-packages\\fastai\\torch_core.py in <module>\r\n      1 \"Utility functions to help deal with tensors\"\r\n----> 2 from .imports.torch import *\r\n      3 from .core import *\r\n      4 \r\n      5 AffineMatrix = Tensor\r\n\r\n~\\Anaconda3\\envs\\fastai\\lib\\site-packages\\fastai\\imports\\__init__.py in <module>\r\n----> 1 from .core import *\r\n      2 from .torch import *\r\n\r\n~\\Anaconda3\\envs\\fastai\\lib\\site-packages\\fastai\\imports\\core.py in <module>\r\n     13 from dataclasses import dataclass, field\r\n     14 from enum import Enum, IntEnum\r\n---> 15 from fastprogress import master_bar, progress_bar\r\n     16 from functools import partial, reduce, singledispatch\r\n     17 from pdb import set_trace\r\n\r\nImportError: cannot import name 'master_bar'\r\n`\r\nWhat's happening?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/54", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/54/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/54/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/54/events", "html_url": "https://github.com/fastai/fastprogress/issues/54", "id": 577255540, "node_id": "MDU6SXNzdWU1NzcyNTU1NDA=", "number": 54, "title": "AttributeError: 'NBMasterBar' object has no attribute 'out'", "user": {"login": "AlkaSaliss", "id": 33458274, "node_id": "MDQ6VXNlcjMzNDU4Mjc0", "avatar_url": "https://avatars0.githubusercontent.com/u/33458274?v=4", "gravatar_id": "", "url": "https://api.github.com/users/AlkaSaliss", "html_url": "https://github.com/AlkaSaliss", "followers_url": "https://api.github.com/users/AlkaSaliss/followers", "following_url": "https://api.github.com/users/AlkaSaliss/following{/other_user}", "gists_url": "https://api.github.com/users/AlkaSaliss/gists{/gist_id}", "starred_url": "https://api.github.com/users/AlkaSaliss/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/AlkaSaliss/subscriptions", "organizations_url": "https://api.github.com/users/AlkaSaliss/orgs", "repos_url": "https://api.github.com/users/AlkaSaliss/repos", "events_url": "https://api.github.com/users/AlkaSaliss/events{/privacy}", "received_events_url": "https://api.github.com/users/AlkaSaliss/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-03-07T01:44:42Z", "updated_at": "2020-03-28T13:31:46Z", "closed_at": "2020-03-28T13:31:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "When using `learner.fit_flat_cos(n_epochs, cbs=[SaveModelCallback(path)])` it throws the exception\r\nHowever when used without the callback, it works with no error\r\n\r\nfast_progress version = `fastprogress-0.2.2`\r\n\r\nAny idea of what is causing this bug ?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/52", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/52/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/52/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/52/events", "html_url": "https://github.com/fastai/fastprogress/issues/52", "id": 566160127, "node_id": "MDU6SXNzdWU1NjYxNjAxMjc=", "number": 52, "title": "ImportError: 'master_bar' from 'fastprogress'", "user": {"login": "fuad3600", "id": 36115265, "node_id": "MDQ6VXNlcjM2MTE1MjY1", "avatar_url": "https://avatars2.githubusercontent.com/u/36115265?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fuad3600", "html_url": "https://github.com/fuad3600", "followers_url": "https://api.github.com/users/fuad3600/followers", "following_url": "https://api.github.com/users/fuad3600/following{/other_user}", "gists_url": "https://api.github.com/users/fuad3600/gists{/gist_id}", "starred_url": "https://api.github.com/users/fuad3600/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fuad3600/subscriptions", "organizations_url": "https://api.github.com/users/fuad3600/orgs", "repos_url": "https://api.github.com/users/fuad3600/repos", "events_url": "https://api.github.com/users/fuad3600/events{/privacy}", "received_events_url": "https://api.github.com/users/fuad3600/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-02-17T09:17:16Z", "updated_at": "2020-02-17T11:59:30Z", "closed_at": "2020-02-17T11:59:30Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nI am trying to import fastai and getting this error:\r\n\r\nfrom fastai.imports import *\r\nTraceback (most recent call last):\r\n\r\n  File \"<ipython-input-7-9f9378ae0f2a>\", line 1, in <module>\r\n    from fastai.imports import *\r\n\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\fastai\\__init__.py\", line 1, in <module>\r\n    from .basic_train import *\r\n\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\fastai\\basic_train.py\", line 2, in <module>\r\n    from .torch_core import *\r\n\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\fastai\\torch_core.py\", line 2, in <module>\r\n    from .imports.torch import *\r\n\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\fastai\\imports\\__init__.py\", line 1, in <module>\r\n    from .core import *\r\n\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\fastai\\imports\\core.py\", line 15, in <module>\r\n    from fastprogress import master_bar, progress_bar\r\n\r\nImportError: cannot import name 'master_bar' from 'fastprogress' (C:\\ProgramData\\Anaconda3\\lib\\site-packages\\fastprogress\\__init__.py)\r\n\r\nI am using anaconda (spyder) and I have installed fastai and fastprogress with following codes from anaconda prompt\r\nconda install -c fastai fastprogress \r\nconda install -c fastai fastai\r\n\r\nAny suggestions? Thank you in advance.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/51", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/51/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/51/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/51/events", "html_url": "https://github.com/fastai/fastprogress/issues/51", "id": 561585299, "node_id": "MDU6SXNzdWU1NjE1ODUyOTk=", "number": 51, "title": "Unexpected kwarg Auto-update TypeError on Colab (Python 3.6)", "user": {"login": "eduguiu", "id": 10409014, "node_id": "MDQ6VXNlcjEwNDA5MDE0", "avatar_url": "https://avatars3.githubusercontent.com/u/10409014?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eduguiu", "html_url": "https://github.com/eduguiu", "followers_url": "https://api.github.com/users/eduguiu/followers", "following_url": "https://api.github.com/users/eduguiu/following{/other_user}", "gists_url": "https://api.github.com/users/eduguiu/gists{/gist_id}", "starred_url": "https://api.github.com/users/eduguiu/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eduguiu/subscriptions", "organizations_url": "https://api.github.com/users/eduguiu/orgs", "repos_url": "https://api.github.com/users/eduguiu/repos", "events_url": "https://api.github.com/users/eduguiu/events{/privacy}", "received_events_url": "https://api.github.com/users/eduguiu/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-02-07T11:36:14Z", "updated_at": "2020-03-28T16:13:17Z", "closed_at": "2020-03-28T13:32:48Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,  \r\n\r\nwhile going through the course-v3/dl2 notebooks (from 09c onwards) on Google Colab, found this bug. \r\nTypeError: init() got an unexpected keyword argument 'auto_update'\r\n\r\nThe origin looks like to be a lack of \"auto_update\" kwargs. \r\n\r\n\r\n![imatge](https://user-images.githubusercontent.com/10409014/74148503-e2181d00-4c05-11ea-8314-64924121fbed.png)\r\n\r\nCommenting the \"auto-update=False \" is enought to bypass the error. \r\n\r\n![imatge](https://user-images.githubusercontent.com/10409014/74026338-42108880-49a6-11ea-835b-b21497aaf87a.png)\r\n\r\nI've checked the installed version of fastprogress and it happens to be 0.2.2\r\n\r\nThanks,\r\n\r\nEd\r\n\r\n\r\n---------------------------------------------------------------------------\r\n\r\nTypeError                                 Traceback (most recent call last)\r\n\r\n<ipython-input-183-36204b60e23f> in <module>()\r\n----> 1 learn.fit(40, cbsched)\r\n\r\n5 frames\r\n\r\n/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09b.py in fit(self, epochs, cbs, reset_opt)\r\n     69             self.do_begin_fit(epochs)\r\n     70             for epoch in range(epochs):\r\n---> 71                 self.do_begin_epoch(epoch)\r\n     72                 if not self('begin_epoch'): self.all_batches()\r\n     73 \r\n\r\n/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09b.py in do_begin_epoch(self, epoch)\r\n     58     def do_begin_epoch(self, epoch):\r\n     59         self.epoch,self.dl = epoch,self.data.train_dl\r\n---> 60         return self('begin_epoch')\r\n     61 \r\n     62     def fit(self, epochs, cbs=None, reset_opt=False):\r\n\r\n/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09b.py in __call__(self, cb_name)\r\n     90         res = False\r\n     91         assert cb_name in self.ALL_CBS\r\n---> 92         for cb in sorted(self.cbs, key=lambda x: x._order): res = cb(cb_name) and res\r\n     93         return res\r\n     94 \r\n\r\n/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_05b.py in __call__(self, cb_name)\r\n     19     def __call__(self, cb_name):\r\n     20         f = getattr(self, cb_name, None)\r\n---> 21         if f and f(): return True\r\n     22         return False\r\n     23 \r\n\r\n/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09c.py in begin_epoch(self)\r\n     45     def after_fit(self): self.mbar.on_iter_end()\r\n     46     def after_batch(self): self.pb.update(self.iter)\r\n---> 47     def begin_epoch   (self): self.set_pb()\r\n     48     def begin_validate(self): self.set_pb()\r\n     49 \r\n\r\n/content/drive/My Drive/colab/course-v3/nbs/dl2/exp/nb_09c.py in set_pb(self)\r\n     49 \r\n     50     def set_pb(self):\r\n---> 51         self.pb = progress_bar(self.dl, parent=self.mbar, auto_update=False)\r\n     52         self.mbar.update(self.epoch)\r\n\r\nTypeError: __init__() got an unexpected keyword argument 'auto_update'\r\n--------------------------------------------------\r\n\r\n\r\n\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/50", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/50/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/50/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/50/events", "html_url": "https://github.com/fastai/fastprogress/issues/50", "id": 558648427, "node_id": "MDU6SXNzdWU1NTg2NDg0Mjc=", "number": 50, "title": "AttributeError: 'NBMasterBar' object has no attribute 'first_bar'", "user": {"login": "sayakpaul", "id": 22957388, "node_id": "MDQ6VXNlcjIyOTU3Mzg4", "avatar_url": "https://avatars3.githubusercontent.com/u/22957388?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sayakpaul", "html_url": "https://github.com/sayakpaul", "followers_url": "https://api.github.com/users/sayakpaul/followers", "following_url": "https://api.github.com/users/sayakpaul/following{/other_user}", "gists_url": "https://api.github.com/users/sayakpaul/gists{/gist_id}", "starred_url": "https://api.github.com/users/sayakpaul/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sayakpaul/subscriptions", "organizations_url": "https://api.github.com/users/sayakpaul/orgs", "repos_url": "https://api.github.com/users/sayakpaul/repos", "events_url": "https://api.github.com/users/sayakpaul/events{/privacy}", "received_events_url": "https://api.github.com/users/sayakpaul/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-02-02T05:58:30Z", "updated_at": "2020-03-05T03:44:54Z", "closed_at": "2020-03-05T03:44:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "Trying out the following example on Colab:\r\n\r\n```\r\nfrom fastprogress.fastprogress import master_bar, progress_bar\r\nfrom time import sleep\r\nmb = master_bar(range(10))\r\nfor i in mb:\r\n    for j in progress_bar(range(100), parent=mb):\r\n        sleep(0.01)\r\n        mb.child.comment = f'second bar stat'\r\n    mb.first_bar.comment = f'first bar stat'\r\n    mb.write(f'Finished loop {i}.')\r\n```\r\n\r\nThrows: *AttributeError: 'NBMasterBar' object has no attribute 'first_bar'*. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/49", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/49/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/49/events", "html_url": "https://github.com/fastai/fastprogress/issues/49", "id": 557361632, "node_id": "MDU6SXNzdWU1NTczNjE2MzI=", "number": 49, "title": "TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'", "user": {"login": "imayachita", "id": 3615586, "node_id": "MDQ6VXNlcjM2MTU1ODY=", "avatar_url": "https://avatars0.githubusercontent.com/u/3615586?v=4", "gravatar_id": "", "url": "https://api.github.com/users/imayachita", "html_url": "https://github.com/imayachita", "followers_url": "https://api.github.com/users/imayachita/followers", "following_url": "https://api.github.com/users/imayachita/following{/other_user}", "gists_url": "https://api.github.com/users/imayachita/gists{/gist_id}", "starred_url": "https://api.github.com/users/imayachita/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/imayachita/subscriptions", "organizations_url": "https://api.github.com/users/imayachita/orgs", "repos_url": "https://api.github.com/users/imayachita/repos", "events_url": "https://api.github.com/users/imayachita/events{/privacy}", "received_events_url": "https://api.github.com/users/imayachita/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-01-30T09:19:20Z", "updated_at": "2020-03-28T13:33:13Z", "closed_at": "2020-03-28T13:33:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi there,\r\nI got an error \r\n\r\n```\r\nFile \"/home/venv/lib/python3.7/site-packages/fastprogress/fastprogress.py\", line 264, in add_child\r\n    self.child.prefix = f'Epoch {self.main_bar.last_v+1}/{self.main_bar.total} :'\r\nTypeError: unsupported operand type(s) for +: 'NoneType' and 'int'\r\n```\r\n\r\nI solved it by commenting that particular line. But, is there any better workaround for this? Because the workaround I did means that I have to change the script in the installation.\r\n\r\nThanks!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/48", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/48/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/48/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/48/events", "html_url": "https://github.com/fastai/fastprogress/issues/48", "id": 553219491, "node_id": "MDU6SXNzdWU1NTMyMTk0OTE=", "number": 48, "title": "Missing GitHub Release artifacts since v0.1.22", "user": {"login": "andersy005", "id": 13301940, "node_id": "MDQ6VXNlcjEzMzAxOTQw", "avatar_url": "https://avatars2.githubusercontent.com/u/13301940?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andersy005", "html_url": "https://github.com/andersy005", "followers_url": "https://api.github.com/users/andersy005/followers", "following_url": "https://api.github.com/users/andersy005/following{/other_user}", "gists_url": "https://api.github.com/users/andersy005/gists{/gist_id}", "starred_url": "https://api.github.com/users/andersy005/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andersy005/subscriptions", "organizations_url": "https://api.github.com/users/andersy005/orgs", "repos_url": "https://api.github.com/users/andersy005/repos", "events_url": "https://api.github.com/users/andersy005/events{/privacy}", "received_events_url": "https://api.github.com/users/andersy005/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-01-21T23:52:16Z", "updated_at": "2020-01-27T19:06:15Z", "closed_at": "2020-01-27T19:06:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "Thank you for this awesome package! \r\n\r\n\r\nWhile working on `fastprogress` recipe for conda-forge in https://github.com/conda-forge/staged-recipes/pull/10658, I noticed some discrepancies between releases on GitHub and the ones available on PyPI. GitHub Release artifacts aren't available since v0.1.22 (November):\r\n\r\n- GitHub Releases\r\n![Screen Shot 2020-01-21 at 4 37 51 PM](https://user-images.githubusercontent.com/13301940/72852659-7c6eeb80-3c6c-11ea-8b2f-2a7878ee1a01.png)\r\n\r\n- PyPI Releases\r\n![Screen Shot 2020-01-21 at 4 30 46 PM](https://user-images.githubusercontent.com/13301940/72852660-7c6eeb80-3c6c-11ea-9903-f95f7a055a9b.png)\r\n\r\nI am wondering if these missing artifacts are available somewhere else? I am asking because I had a hard time building the conda-forge package for `fastprogress` using the `tarbar` from PyPI. \r\n\r\nThank you! \r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/47", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/47/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/47/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/47/events", "html_url": "https://github.com/fastai/fastprogress/issues/47", "id": 552319578, "node_id": "MDU6SXNzdWU1NTIzMTk1Nzg=", "number": 47, "title": "got an unexpected keyword argument 'flush'", "user": {"login": "attibalazs", "id": 1638454, "node_id": "MDQ6VXNlcjE2Mzg0NTQ=", "avatar_url": "https://avatars0.githubusercontent.com/u/1638454?v=4", "gravatar_id": "", "url": "https://api.github.com/users/attibalazs", "html_url": "https://github.com/attibalazs", "followers_url": "https://api.github.com/users/attibalazs/followers", "following_url": "https://api.github.com/users/attibalazs/following{/other_user}", "gists_url": "https://api.github.com/users/attibalazs/gists{/gist_id}", "starred_url": "https://api.github.com/users/attibalazs/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/attibalazs/subscriptions", "organizations_url": "https://api.github.com/users/attibalazs/orgs", "repos_url": "https://api.github.com/users/attibalazs/repos", "events_url": "https://api.github.com/users/attibalazs/events{/privacy}", "received_events_url": "https://api.github.com/users/attibalazs/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-01-20T14:03:50Z", "updated_at": "2020-03-28T13:33:37Z", "closed_at": "2020-03-28T13:33:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\n  File \"C:\\Anaconda\\envs\\fv\\lib\\site-packages\\fastprogress\\fastprogress.py\", line 247, in on_update\r\n    if printing(): WRITER_FN(to_write, end=end, flush=FLUSH)\r\nTypeError: log_fastai_msg() got an unexpected keyword argument 'flush'\r\n```\r\nhi,\r\nany ideas why i am getting this error ?\r\n\r\nif i try it out in the console it works, but when i run my fastai code i get the error.\r\n\r\n```\r\nWRITER_FN = print\r\nWRITER_FN(\"hello\", flush=True)\r\n\r\n```\r\nthe above two lines work for me in a python console.\r\n\r\nthanks!\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/45", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/45/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/45/events", "html_url": "https://github.com/fastai/fastprogress/issues/45", "id": 544214633, "node_id": "MDU6SXNzdWU1NDQyMTQ2MzM=", "number": 45, "title": "ImportError: cannot import name 'master_bar' in v0.2.1", "user": {"login": "amaiya", "id": 47191980, "node_id": "MDQ6VXNlcjQ3MTkxOTgw", "avatar_url": "https://avatars1.githubusercontent.com/u/47191980?v=4", "gravatar_id": "", "url": "https://api.github.com/users/amaiya", "html_url": "https://github.com/amaiya", "followers_url": "https://api.github.com/users/amaiya/followers", "following_url": "https://api.github.com/users/amaiya/following{/other_user}", "gists_url": "https://api.github.com/users/amaiya/gists{/gist_id}", "starred_url": "https://api.github.com/users/amaiya/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/amaiya/subscriptions", "organizations_url": "https://api.github.com/users/amaiya/orgs", "repos_url": "https://api.github.com/users/amaiya/repos", "events_url": "https://api.github.com/users/amaiya/events{/privacy}", "received_events_url": "https://api.github.com/users/amaiya/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2019-12-31T15:35:32Z", "updated_at": "2020-07-17T01:43:22Z", "closed_at": "2019-12-31T15:46:32Z", "author_association": "NONE", "active_lock_reason": null, "body": "V0.2.1 of fastprogress released a couple of days ago seems to cause errors when importing `master_bar` and `progress_bar`:\r\n\r\n```\r\n>>> from fastprogress import master_bar, progress_bar\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nImportError: cannot import name 'master_bar'\r\n```\r\n\r\nTested on a fresh Ubuntu 18.04 install.\r\n\r\nAs a workaround, users need to downgrade:  `pip3 install fastprogress==0.1.22`\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/44", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/44/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/44/events", "html_url": "https://github.com/fastai/fastprogress/issues/44", "id": 543152800, "node_id": "MDU6SXNzdWU1NDMxNTI4MDA=", "number": 44, "title": "VersionConflict in fastprogress", "user": {"login": "reichaves", "id": 23701514, "node_id": "MDQ6VXNlcjIzNzAxNTE0", "avatar_url": "https://avatars3.githubusercontent.com/u/23701514?v=4", "gravatar_id": "", "url": "https://api.github.com/users/reichaves", "html_url": "https://github.com/reichaves", "followers_url": "https://api.github.com/users/reichaves/followers", "following_url": "https://api.github.com/users/reichaves/following{/other_user}", "gists_url": "https://api.github.com/users/reichaves/gists{/gist_id}", "starred_url": "https://api.github.com/users/reichaves/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/reichaves/subscriptions", "organizations_url": "https://api.github.com/users/reichaves/orgs", "repos_url": "https://api.github.com/users/reichaves/repos", "events_url": "https://api.github.com/users/reichaves/events{/privacy}", "received_events_url": "https://api.github.com/users/reichaves/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2019-12-28T12:54:37Z", "updated_at": "2019-12-29T21:11:25Z", "closed_at": "2019-12-28T14:51:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please, I'm using Google Colab and Python3:\r\n\r\n```\r\n!curl -s https://course.fast.ai/setup/colab | bash\r\nimport warnings\r\nwarnings.filterwarnings('ignore')\r\nfrom fastai.vision import *\r\nfrom fastai.metrics import error_rate\r\nimport fastai\r\nprint(f'fastai: {fastai.__version__}')\r\nprint(f'cuda: {torch.cuda.is_available()}')\r\n\r\nI have this error of VersionConflict:\r\n---------------------------------------------------------------------------\r\nVersionConflict                           Traceback (most recent call last)\r\n<ipython-input-17-01736c3668f8> in <module>()\r\n      1 import warnings\r\n      2 warnings.filterwarnings('ignore')\r\n----> 3 from fastai.vision import *\r\n      4 from fastai.metrics import error_rate\r\n      5 import fastai\r\n\r\n7 frames\r\n/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)\r\n    789                 # Oops, the \"best\" so far conflicts with a dependency\r\n    790                 dependent_req = required_by[req]\r\n--> 791                 raise VersionConflict(dist, req).with_context(dependent_req)\r\n    792 \r\n    793             # push the new requirements onto the stack\r\n\r\nVersionConflict: (fastprogress 0.1.22 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('fastprogress>=0.2.1'))\r\n\r\n```\r\nDoes anyone know the reason?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/43", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/43/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/43/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/43/events", "html_url": "https://github.com/fastai/fastprogress/issues/43", "id": 538782641, "node_id": "MDU6SXNzdWU1Mzg3ODI2NDE=", "number": 43, "title": "fastprogress in console mode locks up emacs", "user": {"login": "rpgoldman", "id": 3274, "node_id": "MDQ6VXNlcjMyNzQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/3274?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rpgoldman", "html_url": "https://github.com/rpgoldman", "followers_url": "https://api.github.com/users/rpgoldman/followers", "following_url": "https://api.github.com/users/rpgoldman/following{/other_user}", "gists_url": "https://api.github.com/users/rpgoldman/gists{/gist_id}", "starred_url": "https://api.github.com/users/rpgoldman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rpgoldman/subscriptions", "organizations_url": "https://api.github.com/users/rpgoldman/orgs", "repos_url": "https://api.github.com/users/rpgoldman/repos", "events_url": "https://api.github.com/users/rpgoldman/events{/privacy}", "received_events_url": "https://api.github.com/users/rpgoldman/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-12-17T01:42:02Z", "updated_at": "2020-03-28T13:35:14Z", "closed_at": "2020-03-28T13:35:14Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am using fastprogress through emacs -- using emacs's inferior-python-mode and elpy.  When I invoke a function (through PyMC3) that uses fastprogress, it takes over input to the editor until the python call using fastprogress terminates.  Also, it takes the current cursor and pulls it out of whatever editor buffer it was in and puts it into the interactive python buffer.\r\n\r\nMy guess is that this has something to do with the way that fp is writing its output to the console.  Is it perhaps sending characters to it one at a time to write the progress bar?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/42", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/42/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/42/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/42/events", "html_url": "https://github.com/fastai/fastprogress/issues/42", "id": 524817301, "node_id": "MDU6SXNzdWU1MjQ4MTczMDE=", "number": 42, "title": "Error on colab, with fastai2, @ learn.fit_one_cycle(4)", "user": {"login": "sri9s", "id": 12706804, "node_id": "MDQ6VXNlcjEyNzA2ODA0", "avatar_url": "https://avatars3.githubusercontent.com/u/12706804?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sri9s", "html_url": "https://github.com/sri9s", "followers_url": "https://api.github.com/users/sri9s/followers", "following_url": "https://api.github.com/users/sri9s/following{/other_user}", "gists_url": "https://api.github.com/users/sri9s/gists{/gist_id}", "starred_url": "https://api.github.com/users/sri9s/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sri9s/subscriptions", "organizations_url": "https://api.github.com/users/sri9s/orgs", "repos_url": "https://api.github.com/users/sri9s/repos", "events_url": "https://api.github.com/users/sri9s/events{/privacy}", "received_events_url": "https://api.github.com/users/sri9s/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2019-11-19T07:06:38Z", "updated_at": "2020-01-29T15:19:07Z", "closed_at": "2019-11-19T14:33:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "AttributeError: \u2018NBMasterBar\u2019 object has no attribute \u2018out\u2019\r\nAttributeError: \u2018NBMasterBar\u2019 object has no attribute \u2018start_t\u2019\r\n\r\nHelp me out!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/41", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/41/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/41/events", "html_url": "https://github.com/fastai/fastprogress/issues/41", "id": 518536414, "node_id": "MDU6SXNzdWU1MTg1MzY0MTQ=", "number": 41, "title": "AttributeError: 'NoneType' object has no attribute 'update' using Python 3.7", "user": {"login": "zivanfi", "id": 20930533, "node_id": "MDQ6VXNlcjIwOTMwNTMz", "avatar_url": "https://avatars1.githubusercontent.com/u/20930533?v=4", "gravatar_id": "", "url": "https://api.github.com/users/zivanfi", "html_url": "https://github.com/zivanfi", "followers_url": "https://api.github.com/users/zivanfi/followers", "following_url": "https://api.github.com/users/zivanfi/following{/other_user}", "gists_url": "https://api.github.com/users/zivanfi/gists{/gist_id}", "starred_url": "https://api.github.com/users/zivanfi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/zivanfi/subscriptions", "organizations_url": "https://api.github.com/users/zivanfi/orgs", "repos_url": "https://api.github.com/users/zivanfi/repos", "events_url": "https://api.github.com/users/zivanfi/events{/privacy}", "received_events_url": "https://api.github.com/users/zivanfi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 17, "created_at": "2019-11-06T15:14:10Z", "updated_at": "2020-01-12T18:27:59Z", "closed_at": "2019-11-07T15:28:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "Issue #20 already described this problem for Python versions pre-3.7, but for me it also happens in Python 3.7. Even the history of issue #24 (which just bumped the version requirement) shows that the connection between the Python version and the bug is uncertain.\r\n\r\nSystem info:\r\n\r\n<details> \r\n  <summary>(click triangle on the left to expand/collapse)</summary>\r\n  <p>\r\n\r\n```text\r\n=== Software === \r\npython        : 3.7.3\r\nfastai        : 1.0.59\r\nfastprogress  : 0.1.21\r\ntorch         : 1.3.0\r\nnvidia driver : 418.40\r\ntorch cuda    : 10.1.243 / is **Not available** \r\n\r\n=== Hardware === \r\nnvidia gpus   : 1\r\nHave 1 GPU(s), but torch can't use them (check nvidia driver) \r\n\r\n=== Environment === \r\nplatform      : Linux-4.14.133-113.112.amzn2.x86_64-x86_64-with-Ubuntu-18.04-bionic\r\ndistro        : #1 SMP Tue Jul 30 18:29:50 UTC 2019\r\nconda env     : python3.6\r\npython        : /usr/bin/python3.7\r\nsys.path      : \r\n/usr/lib/python37.zip\r\n/usr/lib/python3.7\r\n/usr/lib/python3.7/lib-dynload\r\n/home/username/.local/lib/python3.7/site-packages\r\n/home/username/.conda/envs/python3.7/lib/python3.7/site-packages\r\n/usr/local/lib/python3.7/dist-packages\r\n/usr/lib/python3/dist-packages\r\n/opt/cloudera/parcels/CDH/lib/spark/python\r\n/home/username/.ipython\r\n```\r\n  </p>\r\n</details>\r\n\r\nStack trace:\r\n\r\n<details> \r\n  <summary>(click triangle on the left to expand/collapse)</summary>\r\n  <p>\r\n\r\n```\r\n/home/username/.local/lib/python3.7/site-packages/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, final_div, wd, callbacks, tot_epochs, start_epoch)\r\n     21     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor, pct_start=pct_start,\r\n     22                                        final_div=final_div, tot_epochs=tot_epochs, start_epoch=start_epoch))\r\n---> 23     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)\r\n     24 \r\n     25 def fit_fc(learn:Learner, tot_epochs:int=1, lr:float=defaults.lr,  moms:Tuple[float,float]=(0.95,0.85), start_pct:float=0.72,\r\n\r\n/home/username/.local/lib/python3.7/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)\r\n    198         else: self.opt.lr,self.opt.wd = lr,wd\r\n    199         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(callbacks)\r\n--> 200         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)\r\n    201 \r\n    202     def create_opt(self, lr:Floats, wd:Floats=0.)->None:\r\n\r\n/home/username/.local/lib/python3.7/site-packages/fastai/basic_train.py in fit(epochs, learn, callbacks, metrics)\r\n     97             cb_handler.set_dl(learn.data.train_dl)\r\n     98             cb_handler.on_epoch_begin()\r\n---> 99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):\r\n    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)\r\n    101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)\r\n\r\n/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)\r\n    157     def __init__(self, gen, total=None, display=True, leave=True, parent=None, auto_update=True):\r\n    158         self.progress = html_progress_bar(0, len(gen) if total is None else total, \"\")\r\n--> 159         super().__init__(gen, total, display, leave, parent, auto_update)\r\n    160 \r\n    161     def on_iter_begin(self):\r\n\r\n/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)\r\n     55         else:\r\n     56             self.leave,self.display=False,False\r\n---> 57             parent.add_child(self)\r\n     58         self.comment = ''\r\n     59         if not self.auto_update:\r\n\r\n/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in add_child(self, child)\r\n    207         self.child = child\r\n    208         self.inner_dict['pb2'] = self.child.progress\r\n--> 209         self.show()\r\n    210 \r\n    211     def show(self):\r\n\r\n/home/username/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py in show(self)\r\n    214         to_show = [name for name in self.order if name in self.inner_dict.keys()]\r\n    215         self.html_code = '\\n'.join([self.inner_dict[n] for n in to_show])\r\n--> 216         self.out.update(HTML(self.html_code))\r\n    217 \r\n    218     def write(self, line, table=False):\r\n\r\nAttributeError: 'NoneType' object has no attribute 'update'\r\n```\r\n  </p>\r\n</details>\r\n\r\nI may be mistaken, but it seems to me that:\r\n- `self.out` is only set in `NBMasterBar.on_iter_begin`, but `NBMasterBar.show` may try use it regardless.\r\n- `NBMasterBar.show` can be called by `NBMasterBar.add_child`, which happens from `ProgressBar.__init__` as `parent.add_child(self)`.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/39", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/39/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/39/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/39/events", "html_url": "https://github.com/fastai/fastprogress/issues/39", "id": 512134170, "node_id": "MDU6SXNzdWU1MTIxMzQxNzA=", "number": 39, "title": "Updating a multiprocess progress_bar", "user": {"login": "fonnesbeck", "id": 81476, "node_id": "MDQ6VXNlcjgxNDc2", "avatar_url": "https://avatars3.githubusercontent.com/u/81476?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fonnesbeck", "html_url": "https://github.com/fonnesbeck", "followers_url": "https://api.github.com/users/fonnesbeck/followers", "following_url": "https://api.github.com/users/fonnesbeck/following{/other_user}", "gists_url": "https://api.github.com/users/fonnesbeck/gists{/gist_id}", "starred_url": "https://api.github.com/users/fonnesbeck/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fonnesbeck/subscriptions", "organizations_url": "https://api.github.com/users/fonnesbeck/orgs", "repos_url": "https://api.github.com/users/fonnesbeck/repos", "events_url": "https://api.github.com/users/fonnesbeck/events{/privacy}", "received_events_url": "https://api.github.com/users/fonnesbeck/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-10-24T19:22:33Z", "updated_at": "2019-12-10T16:25:53Z", "closed_at": "2019-12-10T16:25:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to replace a `tqdm` progress bar with a `fastprogress` bar. However, its not clear how to implement it for multiprocessing. Since `gen` is a required argument there does not seem to be an obvious way to allow processes to update the bar. Any instructions, or a pointer to an example, would be helpful. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/38", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/38/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/38/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/38/events", "html_url": "https://github.com/fastai/fastprogress/issues/38", "id": 507666870, "node_id": "MDU6SXNzdWU1MDc2NjY4NzA=", "number": 38, "title": "ZeroDivisionError for `progress_bar` in Console for empty iterables", "user": {"login": "nvs-abhilash", "id": 15072945, "node_id": "MDQ6VXNlcjE1MDcyOTQ1", "avatar_url": "https://avatars0.githubusercontent.com/u/15072945?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nvs-abhilash", "html_url": "https://github.com/nvs-abhilash", "followers_url": "https://api.github.com/users/nvs-abhilash/followers", "following_url": "https://api.github.com/users/nvs-abhilash/following{/other_user}", "gists_url": "https://api.github.com/users/nvs-abhilash/gists{/gist_id}", "starred_url": "https://api.github.com/users/nvs-abhilash/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nvs-abhilash/subscriptions", "organizations_url": "https://api.github.com/users/nvs-abhilash/orgs", "repos_url": "https://api.github.com/users/nvs-abhilash/repos", "events_url": "https://api.github.com/users/nvs-abhilash/events{/privacy}", "received_events_url": "https://api.github.com/users/nvs-abhilash/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-10-16T07:26:19Z", "updated_at": "2019-10-17T04:16:40Z", "closed_at": "2019-10-17T04:16:40Z", "author_association": "NONE", "active_lock_reason": null, "body": "Progress Bar is failing for empty iterables in console.\r\n\r\nIt works fine in notebook:\r\n![image](https://user-images.githubusercontent.com/15072945/66897505-c2d10080-f014-11e9-84e9-9e515e087f41.png)\r\n\r\n\r\nBut in Console it doesn't work:\r\n![image](https://user-images.githubusercontent.com/15072945/66897608-f7dd5300-f014-11e9-8372-edfa81144b65.png)\r\n\r\n\r\nCode snippet used:\r\n```python\r\nimport fastprogress\r\nfrom fastprogress import progress_bar, master_bar\r\nfastprogress.__version__\r\n\r\n# I have a variable length list, which can also be empty\r\n\r\nvariable_len_list = [] # special case of empty lisy\r\n\r\nfor x in variable_len_list:\r\n    # do some compute\r\n    sleep(10)\r\n\r\nfor x in master_bar(variable_len_list):\r\n    # do some compute\r\n    sleep(10)\r\n\r\nfor x in progress_bar(variable_len_list):\r\n    # do some compute\r\n    sleep(10)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/37", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/37/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/37/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/37/events", "html_url": "https://github.com/fastai/fastprogress/issues/37", "id": 501307441, "node_id": "MDU6SXNzdWU1MDEzMDc0NDE=", "number": 37, "title": "UnicodeEncodeError: 'latin-1' codec can't encode character '\\u2588'", "user": {"login": "alberduris", "id": 7073086, "node_id": "MDQ6VXNlcjcwNzMwODY=", "avatar_url": "https://avatars3.githubusercontent.com/u/7073086?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alberduris", "html_url": "https://github.com/alberduris", "followers_url": "https://api.github.com/users/alberduris/followers", "following_url": "https://api.github.com/users/alberduris/following{/other_user}", "gists_url": "https://api.github.com/users/alberduris/gists{/gist_id}", "starred_url": "https://api.github.com/users/alberduris/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alberduris/subscriptions", "organizations_url": "https://api.github.com/users/alberduris/orgs", "repos_url": "https://api.github.com/users/alberduris/repos", "events_url": "https://api.github.com/users/alberduris/events{/privacy}", "received_events_url": "https://api.github.com/users/alberduris/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-10-02T06:43:15Z", "updated_at": "2019-10-02T15:19:45Z", "closed_at": "2019-10-02T14:52:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am using Fast-bert, which uses _fastprogress_ under the hood, an encountered an encoding issue while running a script from a _CentOS Linux_ server terminal.\r\n\r\nPlease note that this same issue is referred in #21, and the workaround of setting the `LC_ALL `environment variable to `C.UTF-8` does not work, but it works to set it to `en_US.UTF-8`.\r\n\r\n`$ setenv LC_ALL en_US.UTF-8`\r\n\r\nAnyway, I think this should be solved, as this is just a temporal workaround (you have to set it again every day) and it is a simple encoding error which is severely breaking other libraries which depends on _fastprogress_. \r\n\r\nThis is the full traceback, but in summary the problem is the `'\\u2588'` (_full-block_) character, which is used to fill the progress bar.\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"Train-FastBert.py\", line 92, in <module>\r\n    tr_manager.train(data_holder)\r\n  File \"/gscratch2/users/ablanco061/PhD_workspace/MIMICOsa_workspace/scripts/fast-bert/train/tr_bin/train_manager.py\", line 20, in train\r\n    self.custom_model.learner.fit(data_holder.epochs, data_holder.learning_rate, validate=True)\r\n  File \"/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fast_bert/learner_cls.py\", line 276, in fit\r\n    for step, batch in enumerate(progress_bar(train_dataloader, parent=pbar)):\r\n  File \"/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py\", line 75, in __iter__\r\n    if self.auto_update: self.update(i+1)\r\n  File \"/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py\", line 92, in update\r\n    self.update_bar(val)\r\n  File \"/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py\", line 104, in update_bar\r\n    else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')\r\n  File \"/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py\", line 274, in on_update\r\n    if printing(): WRITER_FN(to_write, end = '\\r')\r\nUnicodeEncodeError: 'latin-1' codec can't encode character '\\u2588' in position 14: ordinal not in range(256)\r\n```\r\n\r\nI guess that a potencial solution could be checking the encoding which the user has and selecting the corresponding fill character (one that does not cause an encoding error)\r\n\r\nIf you need something else in order to fix the error, please count on me. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/33", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/33/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/33/events", "html_url": "https://github.com/fastai/fastprogress/issues/33", "id": 451329492, "node_id": "MDU6SXNzdWU0NTEzMjk0OTI=", "number": 33, "title": "Support for JupyterLab", "user": {"login": "H4dr1en", "id": 16240134, "node_id": "MDQ6VXNlcjE2MjQwMTM0", "avatar_url": "https://avatars3.githubusercontent.com/u/16240134?v=4", "gravatar_id": "", "url": "https://api.github.com/users/H4dr1en", "html_url": "https://github.com/H4dr1en", "followers_url": "https://api.github.com/users/H4dr1en/followers", "following_url": "https://api.github.com/users/H4dr1en/following{/other_user}", "gists_url": "https://api.github.com/users/H4dr1en/gists{/gist_id}", "starred_url": "https://api.github.com/users/H4dr1en/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/H4dr1en/subscriptions", "organizations_url": "https://api.github.com/users/H4dr1en/orgs", "repos_url": "https://api.github.com/users/H4dr1en/repos", "events_url": "https://api.github.com/users/H4dr1en/events{/privacy}", "received_events_url": "https://api.github.com/users/H4dr1en/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-06-03T07:22:18Z", "updated_at": "2019-06-04T14:27:12Z", "closed_at": "2019-06-04T14:27:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, is fastprogress officially supporting Jupyter Lab?\r\nFor now, calling progress_bar doesn't show the bar:\r\n\r\n![image](https://user-images.githubusercontent.com/16240134/58783307-e4d76280-85e0-11e9-8b28-4a740b6aa48c.png)\r\n\r\nIf no, it would be good to integrate it to Jupyter Lab as more and more people are shifting to Lab.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/32", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/32/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/32/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/32/events", "html_url": "https://github.com/fastai/fastprogress/issues/32", "id": 439079330, "node_id": "MDU6SXNzdWU0MzkwNzkzMzA=", "number": 32, "title": "name 'HTML' is not defined", "user": {"login": "tuzhucheng", "id": 2687996, "node_id": "MDQ6VXNlcjI2ODc5OTY=", "avatar_url": "https://avatars3.githubusercontent.com/u/2687996?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tuzhucheng", "html_url": "https://github.com/tuzhucheng", "followers_url": "https://api.github.com/users/tuzhucheng/followers", "following_url": "https://api.github.com/users/tuzhucheng/following{/other_user}", "gists_url": "https://api.github.com/users/tuzhucheng/gists{/gist_id}", "starred_url": "https://api.github.com/users/tuzhucheng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tuzhucheng/subscriptions", "organizations_url": "https://api.github.com/users/tuzhucheng/orgs", "repos_url": "https://api.github.com/users/tuzhucheng/repos", "events_url": "https://api.github.com/users/tuzhucheng/events{/privacy}", "received_events_url": "https://api.github.com/users/tuzhucheng/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-05-01T06:19:31Z", "updated_at": "2020-03-28T13:35:57Z", "closed_at": "2020-03-28T13:35:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I'm trying to run the following from fast.ai v3 lesson 3 IMDB notebook:\r\n\r\n```py\r\ndata_lm = TextDataBunch.from_csv(path, 'texts.csv')\r\n```\r\n\r\nI get the following error:\r\n\r\n```\r\n/opt/conda/lib/python3.7/site-packages/fastprogress/fastprogress.py in on_iter_begin(self)\r\n    160 \r\n    161     def on_iter_begin(self):\r\n--> 162         if self.display: self.out = display(HTML(self.progress), display_id=True)\r\n    163         self.is_active=True\r\n    164 \r\n\r\nNameError: name 'HTML' is not defined\r\n```\r\n\r\nHere are the library versions:\r\n* fastai-1.0.52\r\n* fastprogress-0.1.21\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/31", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/31/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/31/events", "html_url": "https://github.com/fastai/fastprogress/issues/31", "id": 429017153, "node_id": "MDU6SXNzdWU0MjkwMTcxNTM=", "number": 31, "title": "null self.out in `if self.display: self.out.update(HTML(self.progress))`", "user": {"login": "8enmann", "id": 1021104, "node_id": "MDQ6VXNlcjEwMjExMDQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/1021104?v=4", "gravatar_id": "", "url": "https://api.github.com/users/8enmann", "html_url": "https://github.com/8enmann", "followers_url": "https://api.github.com/users/8enmann/followers", "following_url": "https://api.github.com/users/8enmann/following{/other_user}", "gists_url": "https://api.github.com/users/8enmann/gists{/gist_id}", "starred_url": "https://api.github.com/users/8enmann/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/8enmann/subscriptions", "organizations_url": "https://api.github.com/users/8enmann/orgs", "repos_url": "https://api.github.com/users/8enmann/repos", "events_url": "https://api.github.com/users/8enmann/events{/privacy}", "received_events_url": "https://api.github.com/users/8enmann/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-04-03T23:27:24Z", "updated_at": "2019-04-03T23:41:27Z", "closed_at": "2019-04-03T23:29:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "```py\r\nsrc = ItemLists(path, TextList(train_tok, path=path, processor=processor),\r\n                TextList(valid_tok, path=path, processor=processor))\r\nsrc = src.label_for_lm()\r\n```\r\nProduces this error:\r\n```\r\n---------------------------------------------------------------------------\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-11-f14467f55f2d> in <module>()\r\n      4 src = ItemLists(path, TextList(train_tok, path=path, processor=processor),\r\n      5                 TextList(valid_tok, path=path, processor=processor))\r\n----> 6 src = src.label_for_lm()\r\n      7 if test_tok is not None: src.add_test(TextList(test_tok, path=path))\r\n      8 text_data = src.databunch()\r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in _inner(*args, **kwargs)\r\n    466             self.valid = fv(*args, from_item_lists=True, **kwargs)\r\n    467             self.__class__ = LabelLists\r\n--> 468             self.process()\r\n    469             return self\r\n    470         return _inner\r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in process(self)\r\n    520         \"Process the inner datasets.\"\r\n    521         xp,yp = self.get_processors()\r\n--> 522         for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)\r\n    523         #progress_bar clear the outputs so in some case warnings issued during processing disappear.\r\n    524         for ds in self.lists:\r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in process(self, xp, yp, name)\r\n    697                     p.warns = []\r\n    698                 self.x,self.y = self.x[~filt],self.y[~filt]\r\n--> 699         self.x.process(xp)\r\n    700         return self\r\n    701 \r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in process(self, processor)\r\n     73         if processor is not None: self.processor = processor\r\n     74         self.processor = listify(self.processor)\r\n---> 75         for p in self.processor: p.process(self)\r\n     76         return self\r\n     77 \r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastai/text/data.py in process(self, ds)\r\n    290         ds.items = _join_texts(ds.items, self.mark_fields, self.include_bos, self.include_eos)\r\n    291         tokens = []\r\n--> 292         for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):\r\n    293             tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])\r\n    294         ds.items = tokens\r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)\r\n     62     def __iter__(self):\r\n     63         self.on_iter_begin()\r\n---> 64         self.update(0)\r\n     65         try:\r\n     66             for i,o in enumerate(self._gen):\r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in update(self, val)\r\n     77             self.pred_t = 0\r\n     78             self.last_v,self.wait_for = 0,1\r\n---> 79             self.update_bar(0)\r\n     80         elif val >= self.last_v + self.wait_for or val == self.total:\r\n     81             cur_t = time()\r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in update_bar(self, val)\r\n     96             warn(\"Your generator is empty.\")\r\n     97             self.on_update(0, '100% [0/0]')\r\n---> 98         else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')\r\n     99 \r\n    100 \r\n\r\n/Users/ben/anaconda3/lib/python3.6/site-packages/fastprogress/fastprogress.py in on_update(self, val, text, interrupted)\r\n    167     def on_update(self, val, text, interrupted=False):\r\n    168         self.progress = html_progress_bar(val, self.total, text, interrupted)\r\n--> 169         if self.display: self.out.update(HTML(self.progress))\r\n    170         elif self.parent is not None: self.parent.show()\r\n    171 \r\n\r\nAttributeError: 'NoneType' object has no attribute 'update'\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/30", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/30/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/30/events", "html_url": "https://github.com/fastai/fastprogress/issues/30", "id": 421569350, "node_id": "MDU6SXNzdWU0MjE1NjkzNTA=", "number": 30, "title": "Console progress bar takes two lines instead of one lines", "user": {"login": "ivicts", "id": 19903139, "node_id": "MDQ6VXNlcjE5OTAzMTM5", "avatar_url": "https://avatars0.githubusercontent.com/u/19903139?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ivicts", "html_url": "https://github.com/ivicts", "followers_url": "https://api.github.com/users/ivicts/followers", "following_url": "https://api.github.com/users/ivicts/following{/other_user}", "gists_url": "https://api.github.com/users/ivicts/gists{/gist_id}", "starred_url": "https://api.github.com/users/ivicts/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ivicts/subscriptions", "organizations_url": "https://api.github.com/users/ivicts/orgs", "repos_url": "https://api.github.com/users/ivicts/repos", "events_url": "https://api.github.com/users/ivicts/events{/privacy}", "received_events_url": "https://api.github.com/users/ivicts/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-03-15T15:16:04Z", "updated_at": "2019-03-18T13:26:54Z", "closed_at": "2019-03-18T13:26:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "![image](https://user-images.githubusercontent.com/19903139/54441635-21c95100-4778-11e9-83ff-4a2e34dba21c.png)\r\n\r\nIs this a bug or a feature?\r\nI am not sure why I got two lines of the progress bar in my codes. I have tried running the Examples.ipynb and it only has one line for the console progress bar.\r\n\r\nHow to make it display only on one line instead of two?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/29", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/29/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/29/events", "html_url": "https://github.com/fastai/fastprogress/issues/29", "id": 419069889, "node_id": "MDU6SXNzdWU0MTkwNjk4ODk=", "number": 29, "title": "Encountered this error", "user": {"login": "pranaypratyush", "id": 10587083, "node_id": "MDQ6VXNlcjEwNTg3MDgz", "avatar_url": "https://avatars3.githubusercontent.com/u/10587083?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pranaypratyush", "html_url": "https://github.com/pranaypratyush", "followers_url": "https://api.github.com/users/pranaypratyush/followers", "following_url": "https://api.github.com/users/pranaypratyush/following{/other_user}", "gists_url": "https://api.github.com/users/pranaypratyush/gists{/gist_id}", "starred_url": "https://api.github.com/users/pranaypratyush/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pranaypratyush/subscriptions", "organizations_url": "https://api.github.com/users/pranaypratyush/orgs", "repos_url": "https://api.github.com/users/pranaypratyush/repos", "events_url": "https://api.github.com/users/pranaypratyush/events{/privacy}", "received_events_url": "https://api.github.com/users/pranaypratyush/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-03-09T13:07:22Z", "updated_at": "2019-03-09T15:24:01Z", "closed_at": "2019-03-09T15:24:01Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\nTraceback (most recent call last):                                                                                       \r\n  File \"depth_fast.py\", line 82, in <module>\r\n    ftrain.fit_one_cycle(main_model, 1)\r\n  File \"/home/pranay/anaconda3/lib/python3.6/site-packages/fastai/train.py\", line 22, in fit_one_cycle\r\n    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)\r\n  File \"/home/pranay/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py\", line 191, in fit\r\n    callbacks=self.callbacks+callbacks)\r\n  File \"/home/pranay/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py\", line 92, in fit\r\n    for xb,yb in progress_bar(data.train_dl, parent=pbar):\r\nValueError: too many values to unpack (expected 2)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/28", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/28/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/28/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/28/events", "html_url": "https://github.com/fastai/fastprogress/issues/28", "id": 416275684, "node_id": "MDU6SXNzdWU0MTYyNzU2ODQ=", "number": 28, "title": "Change the size of the figure", "user": {"login": "teristam", "id": 3406709, "node_id": "MDQ6VXNlcjM0MDY3MDk=", "avatar_url": "https://avatars0.githubusercontent.com/u/3406709?v=4", "gravatar_id": "", "url": "https://api.github.com/users/teristam", "html_url": "https://github.com/teristam", "followers_url": "https://api.github.com/users/teristam/followers", "following_url": "https://api.github.com/users/teristam/following{/other_user}", "gists_url": "https://api.github.com/users/teristam/gists{/gist_id}", "starred_url": "https://api.github.com/users/teristam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/teristam/subscriptions", "organizations_url": "https://api.github.com/users/teristam/orgs", "repos_url": "https://api.github.com/users/teristam/repos", "events_url": "https://api.github.com/users/teristam/events{/privacy}", "received_events_url": "https://api.github.com/users/teristam/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-03-01T20:55:13Z", "updated_at": "2019-03-05T20:02:13Z", "closed_at": "2019-03-05T20:02:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "Currently the size of the update graph is fixed, is there any way to change the size of the figure, or better yet, allow us to run arbitrary plot function? Thanks!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/27", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/27/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/27/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/27/events", "html_url": "https://github.com/fastai/fastprogress/issues/27", "id": 415680038, "node_id": "MDU6SXNzdWU0MTU2ODAwMzg=", "number": 27, "title": "Passing pymongo query to progress_bar", "user": {"login": "ecatkins", "id": 8319226, "node_id": "MDQ6VXNlcjgzMTkyMjY=", "avatar_url": "https://avatars3.githubusercontent.com/u/8319226?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ecatkins", "html_url": "https://github.com/ecatkins", "followers_url": "https://api.github.com/users/ecatkins/followers", "following_url": "https://api.github.com/users/ecatkins/following{/other_user}", "gists_url": "https://api.github.com/users/ecatkins/gists{/gist_id}", "starred_url": "https://api.github.com/users/ecatkins/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ecatkins/subscriptions", "organizations_url": "https://api.github.com/users/ecatkins/orgs", "repos_url": "https://api.github.com/users/ecatkins/repos", "events_url": "https://api.github.com/users/ecatkins/events{/privacy}", "received_events_url": "https://api.github.com/users/ecatkins/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-02-28T15:27:36Z", "updated_at": "2019-03-01T14:22:20Z", "closed_at": "2019-03-01T14:22:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "Trying to pass a pymongo query to progress_bar results in the error below. I can fix this by passing my pymongo query in as a list i.e. `progress_bar(list(x))` \r\n\r\nBut would it be possible/desirable to handle this coercion internally to fastprogress?\r\n\r\n```\r\n/opt/anaconda3/lib/python3.7/site-packages/fastprogress/fastprogress.py in __init__(self, gen, total, display, leave, parent, auto_update)\r\n    144 class NBProgressBar(ProgressBar):\r\n    145     def __init__(self, gen, total=None, display=True, leave=True, parent=None, auto_update=True):\r\n--> 146         self.progress = html_progress_bar(0, len(gen) if total is None else total, \"\")\r\n    147         super().__init__(gen, total, display, leave, parent, auto_update)\r\n    148 \r\n\r\nTypeError: object of type 'Cursor' has no len()\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/26", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/26/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/26/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/26/events", "html_url": "https://github.com/fastai/fastprogress/issues/26", "id": 411701682, "node_id": "MDU6SXNzdWU0MTE3MDE2ODI=", "number": 26, "title": "Not working in jupyter console", "user": {"login": "levinas", "id": 1056733, "node_id": "MDQ6VXNlcjEwNTY3MzM=", "avatar_url": "https://avatars3.githubusercontent.com/u/1056733?v=4", "gravatar_id": "", "url": "https://api.github.com/users/levinas", "html_url": "https://github.com/levinas", "followers_url": "https://api.github.com/users/levinas/followers", "following_url": "https://api.github.com/users/levinas/following{/other_user}", "gists_url": "https://api.github.com/users/levinas/gists{/gist_id}", "starred_url": "https://api.github.com/users/levinas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/levinas/subscriptions", "organizations_url": "https://api.github.com/users/levinas/orgs", "repos_url": "https://api.github.com/users/levinas/repos", "events_url": "https://api.github.com/users/levinas/events{/privacy}", "received_events_url": "https://api.github.com/users/levinas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 16, "created_at": "2019-02-19T01:11:18Z", "updated_at": "2020-03-28T13:36:58Z", "closed_at": "2020-03-28T13:36:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is there a way to get console behavior in Jupyter console?  Currently it just says <IPython.core.display.HTML object>\r\n\r\n```\r\nJupyter console 6.0.0\r\n\r\nPython 3.7.1 (default, Dec 14 2018, 19:28:38)\r\nType 'copyright', 'credits' or 'license' for more information\r\nIPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.\r\n\r\nIn [1]: get_ipython().__class__.__name__\r\nOut[1]: 'ZMQInteractiveShell'\r\n\r\nIn [2]: from fastprogress import master_bar, progress_bar\r\n      : from time import sleep\r\n      : mb = master_bar(range(10))\r\n      : for i in mb:\r\n      :     for j in progress_bar(range(100), parent=mb):\r\n      :         sleep(0.01)\r\n      :\r\n<IPython.core.display.HTML object>\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/25", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/25/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/25/events", "html_url": "https://github.com/fastai/fastprogress/issues/25", "id": 410195835, "node_id": "MDU6SXNzdWU0MTAxOTU4MzU=", "number": 25, "title": "New example for file downloads", "user": {"login": "mindej", "id": 1636250, "node_id": "MDQ6VXNlcjE2MzYyNTA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1636250?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mindej", "html_url": "https://github.com/mindej", "followers_url": "https://api.github.com/users/mindej/followers", "following_url": "https://api.github.com/users/mindej/following{/other_user}", "gists_url": "https://api.github.com/users/mindej/gists{/gist_id}", "starred_url": "https://api.github.com/users/mindej/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mindej/subscriptions", "organizations_url": "https://api.github.com/users/mindej/orgs", "repos_url": "https://api.github.com/users/mindej/repos", "events_url": "https://api.github.com/users/mindej/events{/privacy}", "received_events_url": "https://api.github.com/users/mindej/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-02-14T09:05:20Z", "updated_at": "2020-03-28T13:37:52Z", "closed_at": "2020-03-28T13:37:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "It would be nice to have an example for file download.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/23", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/23/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/23/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/23/events", "html_url": "https://github.com/fastai/fastprogress/issues/23", "id": 393916885, "node_id": "MDU6SXNzdWUzOTM5MTY4ODU=", "number": 23, "title": "Interactive demo for `fastprogress` code examples", "user": {"login": "martinzugnoni", "id": 1155573, "node_id": "MDQ6VXNlcjExNTU1NzM=", "avatar_url": "https://avatars1.githubusercontent.com/u/1155573?v=4", "gravatar_id": "", "url": "https://api.github.com/users/martinzugnoni", "html_url": "https://github.com/martinzugnoni", "followers_url": "https://api.github.com/users/martinzugnoni/followers", "following_url": "https://api.github.com/users/martinzugnoni/following{/other_user}", "gists_url": "https://api.github.com/users/martinzugnoni/gists{/gist_id}", "starred_url": "https://api.github.com/users/martinzugnoni/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/martinzugnoni/subscriptions", "organizations_url": "https://api.github.com/users/martinzugnoni/orgs", "repos_url": "https://api.github.com/users/martinzugnoni/repos", "events_url": "https://api.github.com/users/martinzugnoni/events{/privacy}", "received_events_url": "https://api.github.com/users/martinzugnoni/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-12-24T18:05:58Z", "updated_at": "2019-02-22T05:17:04Z", "closed_at": "2019-02-22T05:17:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello @fastai!\r\n\r\nI've been trying `fastprogress` recently and found it really interesting. We are also thinking about adding it to our curriculum at https://rmotr.com/ (co-founder and teacher here). It improves the UX a lot while working with long running training processes.\r\n\r\nWhile looking at the code examples in the README file I thought it would be great to provide some interactive demo that people can use to play with the library before committing to download and install it locally.\r\n\r\n> A demo is worth a thousand words \ud83d\ude09\r\n\r\nI spent a few minutes compiling `fastprogress` examples into a Jupyter Notebook file, and adapted it in a way that we can open it with a small service we have at RMOTR to launch Jupyter environments online. Note that `fastprogress` (and other libraries like `numpy`) are already installed when the env is loaded, so people can start using it right away.\r\n\r\nThe result is what you can see in my fork of the repo (see the new \"Demo\" section):\r\nhttps://github.com/martinzugnoni/fastprogress\r\n\r\nDo you think that having such interactive demo would help people to know and use `fastprogress`?\r\nLet's use this issue as a kick off to start a discussion. Nothing here is written in stone and we can change everything as you wish.\r\n\r\nI hope you like it, and I truly appreciate any feedback.\r\n\r\nthanks.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/22", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/22/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/22/events", "html_url": "https://github.com/fastai/fastprogress/issues/22", "id": 390153067, "node_id": "MDU6SXNzdWUzOTAxNTMwNjc=", "number": 22, "title": "Reloading of Browser looses all of the output in  jupyter notebook ", "user": {"login": "manugarri", "id": 3670355, "node_id": "MDQ6VXNlcjM2NzAzNTU=", "avatar_url": "https://avatars2.githubusercontent.com/u/3670355?v=4", "gravatar_id": "", "url": "https://api.github.com/users/manugarri", "html_url": "https://github.com/manugarri", "followers_url": "https://api.github.com/users/manugarri/followers", "following_url": "https://api.github.com/users/manugarri/following{/other_user}", "gists_url": "https://api.github.com/users/manugarri/gists{/gist_id}", "starred_url": "https://api.github.com/users/manugarri/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/manugarri/subscriptions", "organizations_url": "https://api.github.com/users/manugarri/orgs", "repos_url": "https://api.github.com/users/manugarri/repos", "events_url": "https://api.github.com/users/manugarri/events{/privacy}", "received_events_url": "https://api.github.com/users/manugarri/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-12-12T10:11:23Z", "updated_at": "2020-03-28T13:38:12Z", "closed_at": "2020-03-28T13:38:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "Using the fastai library, I am using a computing EC2 machine with a jupyter notebook to train models using fastai lib.\r\n\r\nHowever, when I reload the notebook, the cells that where running while I closed the browser tab do not display any output.\r\n\r\nIs there any way to fix this? Maybe setting some top level config in the notebook to revert to the console output?\r\n\r\nIm using Ubuntu 18.04 LTS chrome. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/21", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/21/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/21/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/21/events", "html_url": "https://github.com/fastai/fastprogress/issues/21", "id": 382547709, "node_id": "MDU6SXNzdWUzODI1NDc3MDk=", "number": 21, "title": "UnicodeEncodeError ascii' codec can't encode characters", "user": {"login": "mattmcclean", "id": 788855, "node_id": "MDQ6VXNlcjc4ODg1NQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/788855?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mattmcclean", "html_url": "https://github.com/mattmcclean", "followers_url": "https://api.github.com/users/mattmcclean/followers", "following_url": "https://api.github.com/users/mattmcclean/following{/other_user}", "gists_url": "https://api.github.com/users/mattmcclean/gists{/gist_id}", "starred_url": "https://api.github.com/users/mattmcclean/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mattmcclean/subscriptions", "organizations_url": "https://api.github.com/users/mattmcclean/orgs", "repos_url": "https://api.github.com/users/mattmcclean/repos", "events_url": "https://api.github.com/users/mattmcclean/events{/privacy}", "received_events_url": "https://api.github.com/users/mattmcclean/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2018-11-20T08:19:08Z", "updated_at": "2019-10-18T20:47:03Z", "closed_at": "2018-12-10T22:01:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "Am trying to run a training job using fastai in a Docker container (not Jupyter notebook) and getting a `UnicodeEncodeError` in the `fastprogress` library. Am running `fastprogress` version 0.1.15, `fastai` version 1.0.28 with Python v3.6.\r\n\r\nFull stack trace includes the following:\r\n\r\n```\r\nalgo-1-3QNM9_1_51756cf5708d | Called _train method with model arch: resnet34, batch size: 64, image size: 224, epochs: 4\r\nalgo-1-3QNM9_1_51756cf5708d | Getting training data from dir: /opt/ml/input/data/training\r\nalgo-1-3QNM9_1_51756cf5708d | Model architecture is resnet34\r\nalgo-1-3QNM9_1_51756cf5708d | Creating pretrained conv net\r\nalgo-1-3QNM9_1_51756cf5708d | Downloading: \"https://download.pytorch.org/models/resnet34-333f7ec4.pth\" to /root/.torch/models/resnet34-333f7ec4.pth\r\n100% 87306240/87306240 [00:01<00:00, 70374700.25it/s]\r\nalgo-1-3QNM9_1_51756cf5708d | Fit four cycles\r\nalgo-1-3QNM9_1_51756cf5708d | epoch  train_loss  valid_loss  accuracy\r\n/usr/local/lib/python3.6/dist-packages/PIL/Image.py:953: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images\r\nalgo-1-3QNM9_1_51756cf5708d |   'to RGBA images')\r\nTraceback (most recent call last):                                                              \r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\r\nalgo-1-3QNM9_1_51756cf5708d |     \"__main__\", mod_spec)\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\r\nalgo-1-3QNM9_1_51756cf5708d |     exec(code, run_globals)\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/opt/ml/code/shirts.py\", line 152, in <module>\r\nalgo-1-3QNM9_1_51756cf5708d |     _train(parser.parse_args())\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/opt/ml/code/shirts.py\", line 66, in _train\r\nalgo-1-3QNM9_1_51756cf5708d |     learn.fit_one_cycle(4)\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastai/train.py\", line 20, in fit_one_cycle\r\nalgo-1-3QNM9_1_51756cf5708d |     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastai/basic_train.py\", line 162, in fit\r\nalgo-1-3QNM9_1_51756cf5708d |     callbacks=self.callbacks+callbacks)\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastai/basic_train.py\", line 94, in fit\r\nalgo-1-3QNM9_1_51756cf5708d |     raise e\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastai/basic_train.py\", line 82, in fit\r\nalgo-1-3QNM9_1_51756cf5708d |     for xb,yb in progress_bar(data.train_dl, parent=pbar):\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastprogress/fastprogress.py\", line 67, in __iter__\r\nalgo-1-3QNM9_1_51756cf5708d |     if self.auto_update: self.update(i+1)\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastprogress/fastprogress.py\", line 85, in update\r\nalgo-1-3QNM9_1_51756cf5708d |     self.update_bar(val)\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastprogress/fastprogress.py\", line 97, in update_bar\r\nalgo-1-3QNM9_1_51756cf5708d |     else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')\r\nalgo-1-3QNM9_1_51756cf5708d |   File \"/usr/local/lib/python3.6/dist-packages/fastprogress/fastprogress.py\", line 262, in on_update\r\nalgo-1-3QNM9_1_51756cf5708d |     if printing(): WRITER_FN(to_write, end = '\\r')\r\nalgo-1-3QNM9_1_51756cf5708d | UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-15: ordinal not in range(128)\r\nalgo-1-3QNM9_1_51756cf5708d | 2018-11-20 08:10:39,646 sagemaker-containers ERROR    ExecuteUserScriptError:\r\nalgo-1-3QNM9_1_51756cf5708d | Command \"/usr/local/bin/python -m shirts --batch-size 64 --epochs 4\"\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/20", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/20/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/20/events", "html_url": "https://github.com/fastai/fastprogress/issues/20", "id": 382153131, "node_id": "MDU6SXNzdWUzODIxNTMxMzE=", "number": 20, "title": "AttributeError: 'NoneType' object has no attribute 'update'", "user": {"login": "liamflynn1989", "id": 7057430, "node_id": "MDQ6VXNlcjcwNTc0MzA=", "avatar_url": "https://avatars3.githubusercontent.com/u/7057430?v=4", "gravatar_id": "", "url": "https://api.github.com/users/liamflynn1989", "html_url": "https://github.com/liamflynn1989", "followers_url": "https://api.github.com/users/liamflynn1989/followers", "following_url": "https://api.github.com/users/liamflynn1989/following{/other_user}", "gists_url": "https://api.github.com/users/liamflynn1989/gists{/gist_id}", "starred_url": "https://api.github.com/users/liamflynn1989/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/liamflynn1989/subscriptions", "organizations_url": "https://api.github.com/users/liamflynn1989/orgs", "repos_url": "https://api.github.com/users/liamflynn1989/repos", "events_url": "https://api.github.com/users/liamflynn1989/events{/privacy}", "received_events_url": "https://api.github.com/users/liamflynn1989/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2018-11-19T10:38:58Z", "updated_at": "2020-05-02T16:08:20Z", "closed_at": "2018-11-19T12:06:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "Running the example from https://pypi.org/project/fastprogress/ below:\r\n\r\n```\r\nfrom fastprogress import master_bar, progress_bar\r\nfrom time import sleep\r\nmb = master_bar(range(10))\r\nfor i in mb:\r\n    for j in progress_bar(range(100), parent=mb):\r\n        sleep(0.01)\r\n        mb.child.comment = f'second bar stat'\r\n    mb.first_bar.comment = f'first bar stat'\r\n    mb.write(f'Finished loop {i}.')\r\n    #mb.update_graph(graphs, x_bounds, y_bounds)\r\n```\r\n\r\nreturns the error:\r\n\r\n`AttributeError: 'NoneType' object has no attribute 'update'`\r\n\r\nI have tried this on both a Mac and PC running Python 3.6.1\r\n\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/19", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/19/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/19/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/19/events", "html_url": "https://github.com/fastai/fastprogress/issues/19", "id": 382071118, "node_id": "MDU6SXNzdWUzODIwNzExMTg=", "number": 19, "title": "Can not continue to see the message using table = False written in progress runtime", "user": {"login": "newfyu", "id": 43229758, "node_id": "MDQ6VXNlcjQzMjI5NzU4", "avatar_url": "https://avatars2.githubusercontent.com/u/43229758?v=4", "gravatar_id": "", "url": "https://api.github.com/users/newfyu", "html_url": "https://github.com/newfyu", "followers_url": "https://api.github.com/users/newfyu/followers", "following_url": "https://api.github.com/users/newfyu/following{/other_user}", "gists_url": "https://api.github.com/users/newfyu/gists{/gist_id}", "starred_url": "https://api.github.com/users/newfyu/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/newfyu/subscriptions", "organizations_url": "https://api.github.com/users/newfyu/orgs", "repos_url": "https://api.github.com/users/newfyu/repos", "events_url": "https://api.github.com/users/newfyu/events{/privacy}", "received_events_url": "https://api.github.com/users/newfyu/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-11-19T06:13:47Z", "updated_at": "2018-11-20T14:22:17Z", "closed_at": "2018-11-20T14:22:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\nfrom fastprogress import master_bar, progress_bar\r\nfrom time import sleep\r\nmb = master_bar(range(10))\r\nfor i in mb:\r\n    for j in progress_bar(range(100), parent=mb):\r\n        sleep(0.01)\r\n        mb.child.comment = f'second bar stat'\r\n    mb.first_bar.comment = f'first bar stat'\r\n    mb.write(f'no_table{i}.') # This message cannot be displayed continuously at runtime\r\n    mb.write(f'use_table{i}',table=True)\r\n```\r\n\r\nIn the notebook\uff0cI tried to insert some messages with write() between the two progress bars, and the message written with table=False would be overwritten with the message written by table=True. While all can be displayed at the end of the run, but I can not continue to see the message using table = False written in progress runtime.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/18", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/18/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/18/events", "html_url": "https://github.com/fastai/fastprogress/issues/18", "id": 381521793, "node_id": "MDU6SXNzdWUzODE1MjE3OTM=", "number": 18, "title": "Not Working in VisualStudioCode/Python extension", "user": {"login": "loretoparisi", "id": 163333, "node_id": "MDQ6VXNlcjE2MzMzMw==", "avatar_url": "https://avatars3.githubusercontent.com/u/163333?v=4", "gravatar_id": "", "url": "https://api.github.com/users/loretoparisi", "html_url": "https://github.com/loretoparisi", "followers_url": "https://api.github.com/users/loretoparisi/followers", "following_url": "https://api.github.com/users/loretoparisi/following{/other_user}", "gists_url": "https://api.github.com/users/loretoparisi/gists{/gist_id}", "starred_url": "https://api.github.com/users/loretoparisi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/loretoparisi/subscriptions", "organizations_url": "https://api.github.com/users/loretoparisi/orgs", "repos_url": "https://api.github.com/users/loretoparisi/repos", "events_url": "https://api.github.com/users/loretoparisi/events{/privacy}", "received_events_url": "https://api.github.com/users/loretoparisi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2018-11-16T09:44:10Z", "updated_at": "2020-03-28T13:38:59Z", "closed_at": "2020-03-28T13:38:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "Since end of October, VisualStudioCode supports python, IPython and Jupyter Notebook - see [this](https://github.com/loretoparisi/jupyter-notebook-visualstudio-code-python) repo as an example. Now running the progress bar example\r\n\r\n```python\r\n#%%\r\nfrom fastprogress import master_bar, progress_bar\r\nfrom time import sleep\r\nmb = master_bar(range(10))\r\nfor i in mb:\r\n    for j in progress_bar(range(100), parent=mb):\r\n        sleep(0.01)\r\n        mb.child.comment = f'second bar stat'\r\n    mb.first_bar.comment = f'first bar stat'\r\n    mb.write(f'Finished loop {i}.')\r\n    #mb.update_graph(graphs, x_bounds, y_bounds)\r\n```\r\n\r\n\r\ndoes not properly update the UI, thus resulting in this output.\r\n\r\n<img width=\"1383\" alt=\"schermata 2018-11-16 alle 10 43 31\" src=\"https://user-images.githubusercontent.com/163333/48613591-7a383f80-e98c-11e8-87b9-05f55ba9f381.png\">\r\n\r\nThe animation is now showed in the UI basically. Runnable example is [here](https://github.com/loretoparisi/jupyter-notebook-visualstudio-code-python/blob/master/progressbar.py)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/16", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/16/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/16/events", "html_url": "https://github.com/fastai/fastprogress/issues/16", "id": 377397559, "node_id": "MDU6SXNzdWUzNzczOTc1NTk=", "number": 16, "title": "conversion of cuda tensors", "user": {"login": "simonm3", "id": 1199593, "node_id": "MDQ6VXNlcjExOTk1OTM=", "avatar_url": "https://avatars2.githubusercontent.com/u/1199593?v=4", "gravatar_id": "", "url": "https://api.github.com/users/simonm3", "html_url": "https://github.com/simonm3", "followers_url": "https://api.github.com/users/simonm3/followers", "following_url": "https://api.github.com/users/simonm3/following{/other_user}", "gists_url": "https://api.github.com/users/simonm3/gists{/gist_id}", "starred_url": "https://api.github.com/users/simonm3/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/simonm3/subscriptions", "organizations_url": "https://api.github.com/users/simonm3/orgs", "repos_url": "https://api.github.com/users/simonm3/repos", "events_url": "https://api.github.com/users/simonm3/events{/privacy}", "received_events_url": "https://api.github.com/users/simonm3/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-11-05T13:22:03Z", "updated_at": "2018-11-22T13:52:57Z", "closed_at": "2018-11-16T16:43:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am getting an error at the end of a fastai training loop.\r\n\r\n> can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.\r\n\r\nSeems a bit weird that pytorch does not just log a warning and do the conversion for you. However as they don't it would be useful to add \".cpu()\" in the progress bar or earlier. This is my stack trace:\r\n\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-9-a888de4df517> in <module>\r\n----> 1 learn.fit(1, lr=.01)\r\n\r\n<ipython-input-8-716d8867e71f> in fit(self, epochs, lr, callbacks)\r\n      8         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)\r\n      9         fit(epochs, self.model, self.loss_func, opt=self.opt, data=self.data, metrics=self.metrics,\r\n---> 10             callbacks=self.callbacks+callbacks)\r\n     11 \r\n     12 # create and fit model\r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)\r\n     87     except Exception as e:\r\n     88         exception = e\r\n---> 89         raise e\r\n     90     finally: cb_handler.on_train_end(exception)\r\n     91 \r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)\r\n     84                                        cb_handler=cb_handler, pbar=pbar)\r\n     85             else: val_loss=None\r\n---> 86             if cb_handler.on_epoch_end(val_loss): break\r\n     87     except Exception as e:\r\n     88         exception = e\r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/callback.py in on_epoch_end(self, val_loss)\r\n    250                 met.on_epoch_end(**self.state_dict)\r\n    251                 self.state_dict['last_metrics'].append(met.metric)\r\n--> 252         return np.any(self('epoch_end', False))\r\n    253 \r\n    254     def on_train_end(self, exception:Union[bool,Exception])->None:\r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/callback.py in __call__(self, cb_name, call_mets, **kwargs)\r\n    185         \"Call through to all of the `CallbakHandler` functions.\"\r\n    186         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]\r\n--> 187         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]\r\n    188 \r\n    189     def on_train_begin(self, epochs:int, pbar:PBar, metrics:MetricFuncList)->None:\r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/callback.py in <listcomp>(.0)\r\n    185         \"Call through to all of the `CallbakHandler` functions.\"\r\n    186         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]\r\n--> 187         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]\r\n    188 \r\n    189     def on_train_begin(self, epochs:int, pbar:PBar, metrics:MetricFuncList)->None:\r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/train.py in on_epoch_end(self, n_epochs, last_metrics, **kwargs)\r\n     55             x_bounds = (0, (n_epochs - len(rec.nb_batches)) * rec.nb_batches[-1] + len(rec.losses))\r\n     56             y_bounds = (0, max((max(Tensor(rec.losses)), max(Tensor(rec.val_losses)))))\r\n---> 57             rec.pbar.update_graph([(iters, rec.losses), (val_iter, rec.val_losses)], x_bounds, y_bounds)\r\n     58             return False\r\n     59 \r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/fastprogress/fastprogress.py in update_graph(self, graphs, x_bounds, y_bounds)\r\n    189         self.ax.legend(loc='upper right')\r\n    190         if x_bounds is not None: self.ax.set_xlim(*x_bounds)\r\n--> 191         if y_bounds is not None: self.ax.set_ylim(*y_bounds)\r\n    192         with self.out:\r\n    193             clear_output(wait=True)\r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/matplotlib/axes/_base.py in set_ylim(self, bottom, top, emit, auto, ymin, ymax)\r\n   3474                  'bottom=%s, top=%s') % (bottom, top), stacklevel=2)\r\n   3475 \r\n-> 3476         bottom, top = mtransforms.nonsingular(bottom, top, increasing=False)\r\n   3477 \r\n   3478         if self.get_yscale() == 'log':\r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/matplotlib/transforms.py in nonsingular(vmin, vmax, expander, tiny, increasing)\r\n   2887     \"\"\"\r\n   2888 \r\n-> 2889     if (not np.isfinite(vmin)) or (not np.isfinite(vmax)):\r\n   2890         return -expander, expander\r\n   2891 \r\n\r\n~/src/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/tensor.py in __array__(self, dtype)\r\n    430     def __array__(self, dtype=None):\r\n    431         if dtype is None:\r\n--> 432             return self.numpy()\r\n    433         else:\r\n    434             return self.numpy().astype(dtype, copy=False)\r\n\r\nTypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/11", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/11/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/11/events", "html_url": "https://github.com/fastai/fastprogress/issues/11", "id": 371873119, "node_id": "MDU6SXNzdWUzNzE4NzMxMTk=", "number": 11, "title": "Question: Hook to replace ConsoleProgressBar print statements", "user": {"login": "devforfu", "id": 6022009, "node_id": "MDQ6VXNlcjYwMjIwMDk=", "avatar_url": "https://avatars2.githubusercontent.com/u/6022009?v=4", "gravatar_id": "", "url": "https://api.github.com/users/devforfu", "html_url": "https://github.com/devforfu", "followers_url": "https://api.github.com/users/devforfu/followers", "following_url": "https://api.github.com/users/devforfu/following{/other_user}", "gists_url": "https://api.github.com/users/devforfu/gists{/gist_id}", "starred_url": "https://api.github.com/users/devforfu/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/devforfu/subscriptions", "organizations_url": "https://api.github.com/users/devforfu/orgs", "repos_url": "https://api.github.com/users/devforfu/repos", "events_url": "https://api.github.com/users/devforfu/events{/privacy}", "received_events_url": "https://api.github.com/users/devforfu/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-10-19T09:17:10Z", "updated_at": "2019-10-28T10:16:04Z", "closed_at": "2018-10-30T22:48:16Z", "author_association": "NONE", "active_lock_reason": null, "body": "It is not an issue per se, however, I wonder is it possible to modify `ConsoleProgressBar` class a bit to make possible to replace `print` calls with something like `self.write`, and allow to insert your own writer? \r\n\r\nI know that Python allows you to redirect `stdin` with a special context manager but it would be more suitable for one to use custom output method. Because, for example, if you're using logging, you need to do the work twice, i.e., setup logger, and redirect stream. And if the progress bar could be configurable, then you could just pass logger instance inside or something.\r\n\r\nI mean, something like this (shouldn't be _exactly_ this solution, of course):\r\n```python\r\nclass ConsoleProgressBar(ProgressBar):\r\n    length:int=50\r\n    fill:str='\u2588'\r\n\r\n    def __init__(self, gen, total=None, display=True, leave=True,\r\n                       parent=None, auto_update=True, writer_fn=print):\r\n\r\n        self.max_len,self.prefix = 0,''\r\n        super().__init__(gen, total, display, leave, parent, auto_update)\r\n        self.write = writer_fn\r\n\r\n    def on_iter_end(self):\r\n        if not self.leave and printing():\r\n            self.write(f'\\r{self.prefix}' + ' ' * (self.max_len - len(f'\\r{self.prefix}')), end = '\\r')\r\n\r\n    def on_update(self, val, text):\r\n        if self.display:\r\n            filled_len = int(self.length * val // self.total)\r\n            bar = self.fill * filled_len + '-' * (self.length - filled_len)\r\n            to_write = f'\\r{self.prefix} |{bar}| {text}'\r\n            if len(to_write) > self.max_len: self.max_len=len(to_write)\r\n            if printing(): self.write(to_write, end = '\\r')\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/9", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/9/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/9/events", "html_url": "https://github.com/fastai/fastprogress/issues/9", "id": 356343866, "node_id": "MDU6SXNzdWUzNTYzNDM4NjY=", "number": 9, "title": "f' String ' ERROR!!!!", "user": {"login": "Johnson-yue", "id": 10268274, "node_id": "MDQ6VXNlcjEwMjY4Mjc0", "avatar_url": "https://avatars0.githubusercontent.com/u/10268274?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Johnson-yue", "html_url": "https://github.com/Johnson-yue", "followers_url": "https://api.github.com/users/Johnson-yue/followers", "following_url": "https://api.github.com/users/Johnson-yue/following{/other_user}", "gists_url": "https://api.github.com/users/Johnson-yue/gists{/gist_id}", "starred_url": "https://api.github.com/users/Johnson-yue/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Johnson-yue/subscriptions", "organizations_url": "https://api.github.com/users/Johnson-yue/orgs", "repos_url": "https://api.github.com/users/Johnson-yue/repos", "events_url": "https://api.github.com/users/Johnson-yue/events{/privacy}", "received_events_url": "https://api.github.com/users/Johnson-yue/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-09-03T03:02:23Z", "updated_at": "2018-09-05T12:21:38Z", "closed_at": "2018-09-05T12:21:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "My python version is 3.5.2.  In my python,   all f'balabala ~'  is error.  it shows __invalid syntax__, so i can not run anything!!    I can replace f'string' with r'string', but why using f'string'?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/7", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/7/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/7/events", "html_url": "https://github.com/fastai/fastprogress/issues/7", "id": 354027159, "node_id": "MDU6SXNzdWUzNTQwMjcxNTk=", "number": 7, "title": "when progress completed progress_bar did not display 100 percent", "user": {"login": "Mengman", "id": 3922888, "node_id": "MDQ6VXNlcjM5MjI4ODg=", "avatar_url": "https://avatars0.githubusercontent.com/u/3922888?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Mengman", "html_url": "https://github.com/Mengman", "followers_url": "https://api.github.com/users/Mengman/followers", "following_url": "https://api.github.com/users/Mengman/following{/other_user}", "gists_url": "https://api.github.com/users/Mengman/gists{/gist_id}", "starred_url": "https://api.github.com/users/Mengman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Mengman/subscriptions", "organizations_url": "https://api.github.com/users/Mengman/orgs", "repos_url": "https://api.github.com/users/Mengman/repos", "events_url": "https://api.github.com/users/Mengman/events{/privacy}", "received_events_url": "https://api.github.com/users/Mengman/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-08-25T16:53:55Z", "updated_at": "2018-08-25T20:41:56Z", "closed_at": "2018-08-25T20:41:56Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "When use progress_bar only to display job progress, although job has completed but progress_bar may not display as 100 percent.\r\nAny idea how to fix it?\r\n\r\n![screenshot_2018-08-26 example](https://user-images.githubusercontent.com/3922888/44620634-68ce2280-a8ca-11e8-8cda-34c019f2b70b.png)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/6", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/6/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/6/events", "html_url": "https://github.com/fastai/fastprogress/issues/6", "id": 353042723, "node_id": "MDU6SXNzdWUzNTMwNDI3MjM=", "number": 6, "title": "Difference with tqdm", "user": {"login": "sekhavatosan", "id": 40194181, "node_id": "MDQ6VXNlcjQwMTk0MTgx", "avatar_url": "https://avatars1.githubusercontent.com/u/40194181?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sekhavatosan", "html_url": "https://github.com/sekhavatosan", "followers_url": "https://api.github.com/users/sekhavatosan/followers", "following_url": "https://api.github.com/users/sekhavatosan/following{/other_user}", "gists_url": "https://api.github.com/users/sekhavatosan/gists{/gist_id}", "starred_url": "https://api.github.com/users/sekhavatosan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sekhavatosan/subscriptions", "organizations_url": "https://api.github.com/users/sekhavatosan/orgs", "repos_url": "https://api.github.com/users/sekhavatosan/repos", "events_url": "https://api.github.com/users/sekhavatosan/events{/privacy}", "received_events_url": "https://api.github.com/users/sekhavatosan/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-08-22T17:02:11Z", "updated_at": "2018-08-23T06:52:33Z", "closed_at": "2018-08-23T06:52:33Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nThanks for your project. Would you please mention differences (implemented or planned) between fast_progress and [tqdm](https://pypi.python.org/pypi/tqdm) in README or somewhere?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/3", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/3/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/3/events", "html_url": "https://github.com/fastai/fastprogress/issues/3", "id": 352490811, "node_id": "MDU6SXNzdWUzNTI0OTA4MTE=", "number": 3, "title": "Plot placement", "user": {"login": "laol777", "id": 13363601, "node_id": "MDQ6VXNlcjEzMzYzNjAx", "avatar_url": "https://avatars2.githubusercontent.com/u/13363601?v=4", "gravatar_id": "", "url": "https://api.github.com/users/laol777", "html_url": "https://github.com/laol777", "followers_url": "https://api.github.com/users/laol777/followers", "following_url": "https://api.github.com/users/laol777/following{/other_user}", "gists_url": "https://api.github.com/users/laol777/gists{/gist_id}", "starred_url": "https://api.github.com/users/laol777/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/laol777/subscriptions", "organizations_url": "https://api.github.com/users/laol777/orgs", "repos_url": "https://api.github.com/users/laol777/repos", "events_url": "https://api.github.com/users/laol777/events{/privacy}", "received_events_url": "https://api.github.com/users/laol777/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-08-21T11:05:50Z", "updated_at": "2018-09-05T12:30:09Z", "closed_at": "2018-09-05T12:30:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is it possible to show plot above all other information?\r\nWhat I mean:\r\n________________\r\n|plot_____________|\r\n|plot_____________|\r\n|plot_____________|\r\nprogress bar1\r\nprogress bar2\r\n.....................", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/2", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/2/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/2/events", "html_url": "https://github.com/fastai/fastprogress/issues/2", "id": 352422009, "node_id": "MDU6SXNzdWUzNTI0MjIwMDk=", "number": 2, "title": "Undefined name: 'display' in ./fast_progress/fast_progress.py", "user": {"login": "cclauss", "id": 3709715, "node_id": "MDQ6VXNlcjM3MDk3MTU=", "avatar_url": "https://avatars3.githubusercontent.com/u/3709715?v=4", "gravatar_id": "", "url": "https://api.github.com/users/cclauss", "html_url": "https://github.com/cclauss", "followers_url": "https://api.github.com/users/cclauss/followers", "following_url": "https://api.github.com/users/cclauss/following{/other_user}", "gists_url": "https://api.github.com/users/cclauss/gists{/gist_id}", "starred_url": "https://api.github.com/users/cclauss/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/cclauss/subscriptions", "organizations_url": "https://api.github.com/users/cclauss/orgs", "repos_url": "https://api.github.com/users/cclauss/repos", "events_url": "https://api.github.com/users/cclauss/events{/privacy}", "received_events_url": "https://api.github.com/users/cclauss/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-08-21T07:45:03Z", "updated_at": "2018-08-21T08:17:17Z", "closed_at": "2018-08-21T08:17:16Z", "author_association": "NONE", "active_lock_reason": null, "body": "Probably just a missing import statement...\r\n\r\n[flake8](http://flake8.pycqa.org) testing of https://github.com/fastai/fast_progress on Python 3.7.0\r\n\r\n$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__\r\n```\r\n/home/travis/virtualenv/python3.7.0/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1\r\n  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')\r\n./fast_progress/fast_progress.py:92:26: F821 undefined name 'display'\r\n        if self.display: display(self.box)\r\n                         ^\r\n./fast_progress/fast_progress.py:116:30: F821 undefined name 'display'\r\n    def on_iter_begin(self): display(self.vbox)\r\n                             ^\r\n./fast_progress/fast_progress.py:140:13: F821 undefined name 'display'\r\n            display(self.ax.figure)\r\n            ^\r\n3     F821 undefined name 'display'\r\n3\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/fastai/fastprogress/issues/1", "repository_url": "https://api.github.com/repos/fastai/fastprogress", "labels_url": "https://api.github.com/repos/fastai/fastprogress/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/fastai/fastprogress/issues/1/comments", "events_url": "https://api.github.com/repos/fastai/fastprogress/issues/1/events", "html_url": "https://github.com/fastai/fastprogress/issues/1", "id": 352158841, "node_id": "MDU6SXNzdWUzNTIxNTg4NDE=", "number": 1, "title": "Google Colaboratory support", "user": {"login": "korakot", "id": 3155646, "node_id": "MDQ6VXNlcjMxNTU2NDY=", "avatar_url": "https://avatars3.githubusercontent.com/u/3155646?v=4", "gravatar_id": "", "url": "https://api.github.com/users/korakot", "html_url": "https://github.com/korakot", "followers_url": "https://api.github.com/users/korakot/followers", "following_url": "https://api.github.com/users/korakot/following{/other_user}", "gists_url": "https://api.github.com/users/korakot/gists{/gist_id}", "starred_url": "https://api.github.com/users/korakot/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/korakot/subscriptions", "organizations_url": "https://api.github.com/users/korakot/orgs", "repos_url": "https://api.github.com/users/korakot/repos", "events_url": "https://api.github.com/users/korakot/events{/privacy}", "received_events_url": "https://api.github.com/users/korakot/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-08-20T14:24:31Z", "updated_at": "2018-08-20T14:30:55Z", "closed_at": "2018-08-20T14:30:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I used `fast progress` in Google Colaboratory, I found this error\r\n```\r\n---------------------------------------------------------------------------\r\nModuleNotFoundError                       Traceback (most recent call last)\r\n<ipython-input-2-d93e865ab2ed> in <module>()\r\n----> 1 from fast_progress import master_bar, progress_bar\r\n      2 from time import sleep\r\n\r\n/content/fast_progress.py in <module>()\r\n      7 \r\n      8 if IN_NOTEBOOK:\r\n----> 9     from ipywidgets import widgets, IntProgress, HBox, HTML, VBox\r\n     10     from IPython.display import clear_output\r\n     11     from ipywidgets.widgets.interaction import show_inline_matplotlib_plots\r\n\r\nModuleNotFoundError: No module named 'ipywidgets'\r\n```\r\n\r\nSo, please also check that it's within Colab, and revert to console version.\r\nColab can display HTML just fine, and also allow JS<->Python communication.\r\nSo, someone can try to implement a Colab-specific version as well.", "performed_via_github_app": null, "score": 1.0}]}