{"total_count": 7, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/34", "repository_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer", "labels_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/34/comments", "events_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/34/events", "html_url": "https://github.com/googleapis/python-bigquery-datatransfer/issues/34", "id": 648491854, "node_id": "MDU6SXNzdWU2NDg0OTE4NTQ=", "number": 34, "title": "Warning: a recent release failed", "user": {"login": "failure-checker[bot]", "id": 58094317, "node_id": "MDM6Qm90NTgwOTQzMTc=", "avatar_url": "https://avatars2.githubusercontent.com/in/47470?v=4", "gravatar_id": "", "url": "https://api.github.com/users/failure-checker%5Bbot%5D", "html_url": "https://github.com/apps/failure-checker", "followers_url": "https://api.github.com/users/failure-checker%5Bbot%5D/followers", "following_url": "https://api.github.com/users/failure-checker%5Bbot%5D/following{/other_user}", "gists_url": "https://api.github.com/users/failure-checker%5Bbot%5D/gists{/gist_id}", "starred_url": "https://api.github.com/users/failure-checker%5Bbot%5D/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/failure-checker%5Bbot%5D/subscriptions", "organizations_url": "https://api.github.com/users/failure-checker%5Bbot%5D/orgs", "repos_url": "https://api.github.com/users/failure-checker%5Bbot%5D/repos", "events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/events{/privacy}", "received_events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/received_events", "type": "Bot", "site_admin": false}, "labels": [{"id": 1814755878, "node_id": "MDU6TGFiZWwxODE0NzU1ODc4", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/api:%20bigquerydatatransfer", "name": "api: bigquerydatatransfer", "color": "687555", "default": false, "description": "Issues related to the BigQuery Data Transfer Service API."}, {"id": 1814757840, "node_id": "MDU6TGFiZWwxODE0NzU3ODQw", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/type:%20process", "name": "type: process", "color": "c5def5", "default": false, "description": "A process-releated concern. May include testing, release, or the like."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-06-30T21:03:32Z", "updated_at": "2020-08-12T04:20:09Z", "closed_at": "2020-08-12T04:20:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "The release PR #23 is still in a pending state after several hours", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/18", "repository_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer", "labels_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/18/comments", "events_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/18/events", "html_url": "https://github.com/googleapis/python-bigquery-datatransfer/issues/18", "id": 576098574, "node_id": "MDU6SXNzdWU1NzYwOTg1NzQ=", "number": 18, "title": "Documentation for `name` param in get/delete transfer config very unclear", "user": {"login": "adamcunnington-gdt", "id": 41327127, "node_id": "MDQ6VXNlcjQxMzI3MTI3", "avatar_url": "https://avatars0.githubusercontent.com/u/41327127?v=4", "gravatar_id": "", "url": "https://api.github.com/users/adamcunnington-gdt", "html_url": "https://github.com/adamcunnington-gdt", "followers_url": "https://api.github.com/users/adamcunnington-gdt/followers", "following_url": "https://api.github.com/users/adamcunnington-gdt/following{/other_user}", "gists_url": "https://api.github.com/users/adamcunnington-gdt/gists{/gist_id}", "starred_url": "https://api.github.com/users/adamcunnington-gdt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/adamcunnington-gdt/subscriptions", "organizations_url": "https://api.github.com/users/adamcunnington-gdt/orgs", "repos_url": "https://api.github.com/users/adamcunnington-gdt/repos", "events_url": "https://api.github.com/users/adamcunnington-gdt/events{/privacy}", "received_events_url": "https://api.github.com/users/adamcunnington-gdt/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814755878, "node_id": "MDU6TGFiZWwxODE0NzU1ODc4", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/api:%20bigquerydatatransfer", "name": "api: bigquerydatatransfer", "color": "687555", "default": false, "description": "Issues related to the BigQuery Data Transfer Service API."}, {"id": 1814758063, "node_id": "MDU6TGFiZWwxODE0NzU4MDYz", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/type:%20docs", "name": "type: docs", "color": "0000A0", "default": false, "description": "Improvement to the documentation for an API."}], "state": "closed", "locked": false, "assignee": {"login": "shollyman", "id": 960486, "node_id": "MDQ6VXNlcjk2MDQ4Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/960486?v=4", "gravatar_id": "", "url": "https://api.github.com/users/shollyman", "html_url": "https://github.com/shollyman", "followers_url": "https://api.github.com/users/shollyman/followers", "following_url": "https://api.github.com/users/shollyman/following{/other_user}", "gists_url": "https://api.github.com/users/shollyman/gists{/gist_id}", "starred_url": "https://api.github.com/users/shollyman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shollyman/subscriptions", "organizations_url": "https://api.github.com/users/shollyman/orgs", "repos_url": "https://api.github.com/users/shollyman/repos", "events_url": "https://api.github.com/users/shollyman/events{/privacy}", "received_events_url": "https://api.github.com/users/shollyman/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "shollyman", "id": 960486, "node_id": "MDQ6VXNlcjk2MDQ4Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/960486?v=4", "gravatar_id": "", "url": "https://api.github.com/users/shollyman", "html_url": "https://github.com/shollyman", "followers_url": "https://api.github.com/users/shollyman/followers", "following_url": "https://api.github.com/users/shollyman/following{/other_user}", "gists_url": "https://api.github.com/users/shollyman/gists{/gist_id}", "starred_url": "https://api.github.com/users/shollyman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shollyman/subscriptions", "organizations_url": "https://api.github.com/users/shollyman/orgs", "repos_url": "https://api.github.com/users/shollyman/repos", "events_url": "https://api.github.com/users/shollyman/events{/privacy}", "received_events_url": "https://api.github.com/users/shollyman/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2020-03-05T09:09:47Z", "updated_at": "2020-03-06T21:11:18Z", "closed_at": "2020-03-06T21:11:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "The documentation describes that the first parameter to the get_transfer_config & delete_transfer_config methods should be \"name\". As far as I can tell, the name is the projects/foo/locations/foo/transferConfigs/unique-guid which is well, unique - how can this be obtained?! The only way you would have access to that unique ID is if you have access to the transfer config object in which case, you wouldn't need to get it!\r\n\r\nThe example shows that name can be generated from the classmethod, client.project_transfer_config_path.\r\n\r\nBut that classmethod wants \"transfer_config\" as a parameter which is circular and the documentation is [incredibly light](https://googleapis.dev/python/bigquerydatatransfer/latest/gapic/v1/api.html#google.cloud.bigquery_datatransfer_v1.DataTransferServiceClient.project_transfer_config_path).\r\n\r\nWhen I try passing the object that I ultimately send to create_transfer_config, it doesn't work.\r\n\r\nI can provide more detail if necessary but I'm hoping that someone is already aware of this and can either call out what i'm doing wrong and/or fix the documentation.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/17", "repository_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer", "labels_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/17/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/17/comments", "events_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/17/events", "html_url": "https://github.com/googleapis/python-bigquery-datatransfer/issues/17", "id": 576093157, "node_id": "MDU6SXNzdWU1NzYwOTMxNTc=", "number": 17, "title": "Support email notifications & pubsub for transfer configs when creating via python SDK", "user": {"login": "adamcunnington-gdt", "id": 41327127, "node_id": "MDQ6VXNlcjQxMzI3MTI3", "avatar_url": "https://avatars0.githubusercontent.com/u/41327127?v=4", "gravatar_id": "", "url": "https://api.github.com/users/adamcunnington-gdt", "html_url": "https://github.com/adamcunnington-gdt", "followers_url": "https://api.github.com/users/adamcunnington-gdt/followers", "following_url": "https://api.github.com/users/adamcunnington-gdt/following{/other_user}", "gists_url": "https://api.github.com/users/adamcunnington-gdt/gists{/gist_id}", "starred_url": "https://api.github.com/users/adamcunnington-gdt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/adamcunnington-gdt/subscriptions", "organizations_url": "https://api.github.com/users/adamcunnington-gdt/orgs", "repos_url": "https://api.github.com/users/adamcunnington-gdt/repos", "events_url": "https://api.github.com/users/adamcunnington-gdt/events{/privacy}", "received_events_url": "https://api.github.com/users/adamcunnington-gdt/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814755878, "node_id": "MDU6TGFiZWwxODE0NzU1ODc4", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/api:%20bigquerydatatransfer", "name": "api: bigquerydatatransfer", "color": "687555", "default": false, "description": "Issues related to the BigQuery Data Transfer Service API."}, {"id": 1814757803, "node_id": "MDU6TGFiZWwxODE0NzU3ODAz", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/type:%20feature%20request", "name": "type: feature request", "color": "c5def5", "default": false, "description": "\u2018Nice-to-have\u2019 improvement, new feature or different behavior or design."}], "state": "closed", "locked": false, "assignee": {"login": "shollyman", "id": 960486, "node_id": "MDQ6VXNlcjk2MDQ4Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/960486?v=4", "gravatar_id": "", "url": "https://api.github.com/users/shollyman", "html_url": "https://github.com/shollyman", "followers_url": "https://api.github.com/users/shollyman/followers", "following_url": "https://api.github.com/users/shollyman/following{/other_user}", "gists_url": "https://api.github.com/users/shollyman/gists{/gist_id}", "starred_url": "https://api.github.com/users/shollyman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shollyman/subscriptions", "organizations_url": "https://api.github.com/users/shollyman/orgs", "repos_url": "https://api.github.com/users/shollyman/repos", "events_url": "https://api.github.com/users/shollyman/events{/privacy}", "received_events_url": "https://api.github.com/users/shollyman/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "shollyman", "id": 960486, "node_id": "MDQ6VXNlcjk2MDQ4Ng==", "avatar_url": "https://avatars1.githubusercontent.com/u/960486?v=4", "gravatar_id": "", "url": "https://api.github.com/users/shollyman", "html_url": "https://github.com/shollyman", "followers_url": "https://api.github.com/users/shollyman/followers", "following_url": "https://api.github.com/users/shollyman/following{/other_user}", "gists_url": "https://api.github.com/users/shollyman/gists{/gist_id}", "starred_url": "https://api.github.com/users/shollyman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shollyman/subscriptions", "organizations_url": "https://api.github.com/users/shollyman/orgs", "repos_url": "https://api.github.com/users/shollyman/repos", "events_url": "https://api.github.com/users/shollyman/events{/privacy}", "received_events_url": "https://api.github.com/users/shollyman/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 2, "created_at": "2020-03-05T09:00:17Z", "updated_at": "2020-03-06T21:26:49Z", "closed_at": "2020-03-06T21:26:49Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please support the emailNotifications & pubsub options. Currently, when creating a Data Transfer run via python SDK, we can't programmatically manage notifications. I believe both the REST and gRPC apis expose this as an option.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/13", "repository_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer", "labels_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/13/comments", "events_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/13/events", "html_url": "https://github.com/googleapis/python-bigquery-datatransfer/issues/13", "id": 568370229, "node_id": "MDU6SXNzdWU1NjgzNzAyMjk=", "number": 13, "title": "BigQuery Data Transfer Notifications API Enablement", "user": {"login": "ccao93", "id": 26330759, "node_id": "MDQ6VXNlcjI2MzMwNzU5", "avatar_url": "https://avatars2.githubusercontent.com/u/26330759?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ccao93", "html_url": "https://github.com/ccao93", "followers_url": "https://api.github.com/users/ccao93/followers", "following_url": "https://api.github.com/users/ccao93/following{/other_user}", "gists_url": "https://api.github.com/users/ccao93/gists{/gist_id}", "starred_url": "https://api.github.com/users/ccao93/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ccao93/subscriptions", "organizations_url": "https://api.github.com/users/ccao93/orgs", "repos_url": "https://api.github.com/users/ccao93/repos", "events_url": "https://api.github.com/users/ccao93/events{/privacy}", "received_events_url": "https://api.github.com/users/ccao93/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814758072, "node_id": "MDU6TGFiZWwxODE0NzU4MDcy", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/:rotating_light:", "name": ":rotating_light:", "color": "FFFFFF", "default": false, "description": "This issue needs some love."}, {"id": 1814755878, "node_id": "MDU6TGFiZWwxODE0NzU1ODc4", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/api:%20bigquerydatatransfer", "name": "api: bigquerydatatransfer", "color": "687555", "default": false, "description": "Issues related to the BigQuery Data Transfer Service API."}, {"id": 1814758084, "node_id": "MDU6TGFiZWwxODE0NzU4MDg0", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/triage%20me", "name": "triage me", "color": "FF69B4", "default": false, "description": "I really want to be triaged."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 10, "created_at": "2020-02-20T15:12:47Z", "updated_at": "2020-03-09T16:51:16Z", "closed_at": "2020-03-09T16:51:16Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have been notified that the rollout for BigQuery Data Transfer Notifications API is completed. However, I'm still not able to set it up via `google.protobuf.json_format.ParseDict` & `bigquery_datatransfer_v1.types.TransferConfig()`. The error I got was:\r\n\r\n```\r\nMessage type \"google.cloud.bigquery.datatransfer.v1.TransferConfig\" has no field named \"notification_pubsub_topic\".\r\n Available Fields(except extensions): ['name', 'destinationDatasetId', 'displayName', 'dataSourceId', 'params', 'schedule', 'scheduleOptions', 'dataRefreshWindowDays', 'disabled', 'updateTime', 'nextRunTime', 'state', 'userId', 'datasetRegion']\r\n```\r\n\r\nMay I ask if there is any plan to add this field to `bigquery_datatransfer_v1.types.TransferConfig()`?\r\n\r\nThanks", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/12", "repository_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer", "labels_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/12/comments", "events_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/12/events", "html_url": "https://github.com/googleapis/python-bigquery-datatransfer/issues/12", "id": 568302454, "node_id": "MDU6SXNzdWU1NjgzMDI0NTQ=", "number": 12, "title": "Synthesis failed for python-bigquery-datatransfer", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814758072, "node_id": "MDU6TGFiZWwxODE0NzU4MDcy", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/:rotating_light:", "name": ":rotating_light:", "color": "FFFFFF", "default": false, "description": "This issue needs some love."}, {"id": 1814755878, "node_id": "MDU6TGFiZWwxODE0NzU1ODc4", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/api:%20bigquerydatatransfer", "name": "api: bigquerydatatransfer", "color": "687555", "default": false, "description": "Issues related to the BigQuery Data Transfer Service API."}, {"id": 1859982321, "node_id": "MDU6TGFiZWwxODU5OTgyMzIx", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814757921, "node_id": "MDU6TGFiZWwxODE0NzU3OTIx", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814757739, "node_id": "MDU6TGFiZWwxODE0NzU3NzM5", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-02-20T13:33:37Z", "updated_at": "2020-04-06T17:09:56Z", "closed_at": "2020-02-20T23:24:24Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-bigquery-datatransfer. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\nCloning into 'working_repo'...\nSwitched to branch 'autosynth'\nRunning synthtool\n['/tmpfs/src/git/autosynth/env/bin/python3', '-m', 'synthtool', 'synth.py', '--']\nsynthtool > Executing /tmpfs/src/git/autosynth/working_repo/synth.py.\nOn branch autosynth\nnothing to commit, working tree clean\nHEAD detached at FETCH_HEAD\nnothing to commit, working tree clean\nsynthtool > Ensuring dependencies.\nsynthtool > Pulling artman image.\nlatest: Pulling from googleapis/artman\nDigest: sha256:6aec9c34db0e4be221cdaf6faba27bdc07cfea846808b3d3b964dfce3a9a0f9b\nStatus: Image is up to date for googleapis/artman:latest\nsynthtool > Cloning googleapis.\nsynthtool > Running generator for google/cloud/bigquery/datatransfer/artman_bigquerydatatransfer.yaml.\nsynthtool > Generated code into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/bigquerydatatransfer-v1.\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/bigquery/datatransfer/v1/transfer.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/bigquerydatatransfer-v1/google/cloud/bigquery_datatransfer_v1/proto/transfer.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/bigquery/datatransfer/v1/datatransfer.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/bigquerydatatransfer-v1/google/cloud/bigquery_datatransfer_v1/proto/datatransfer.proto\nsynthtool > Placed proto files into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/bigquerydatatransfer-v1/google/cloud/bigquery_datatransfer_v1/proto.\nsynthtool > Replaced 'from google.cloud.bigquery.datatransfer_v1.proto' in google/cloud/bigquery_datatransfer_v1/proto/datatransfer_pb2.py.\nsynthtool > Replaced 'from google.cloud.bigquery.datatransfer_v1.proto' in google/cloud/bigquery_datatransfer_v1/proto/datatransfer_pb2_grpc.py.\nsynthtool > Replaced 'google-cloud-bigquerydatatransfer' in google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client.py.\nsynthtool > Replaced 'import google.api_core.gapic_v1.method\\n' in google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client.py.\n.coveragerc\n.flake8\n.github/CONTRIBUTING.md\n.github/ISSUE_TEMPLATE/bug_report.md\n.github/ISSUE_TEMPLATE/feature_request.md\n.github/ISSUE_TEMPLATE/support_request.md\n.github/PULL_REQUEST_TEMPLATE.md\n.github/release-please.yml\n.gitignore\n.kokoro/build.sh\n.kokoro/continuous/common.cfg\n.kokoro/continuous/continuous.cfg\n.kokoro/docs/common.cfg\n.kokoro/docs/docs.cfg\n.kokoro/presubmit/common.cfg\n.kokoro/presubmit/presubmit.cfg\n.kokoro/publish-docs.sh\n.kokoro/release.sh\n.kokoro/release/common.cfg\n.kokoro/release/release.cfg\n.kokoro/trampoline.sh\nCODE_OF_CONDUCT.md\nCONTRIBUTING.rst\nLICENSE\nMANIFEST.in\ndocs/_static/custom.css\ndocs/_templates/layout.html\ndocs/conf.py.j2\nnoxfile.py.j2\nrenovate.json\nsetup.cfg\nRunning session blacken\nCreating virtual environment (virtualenv) using python3.6 in .nox/blacken\npip install black==19.3b0\nError: pip is not installed into the virtualenv, it is located at /tmpfs/src/git/autosynth/env/bin/pip. Pass external=True into run() to explicitly allow this.\nSession blacken failed.\nsynthtool > Failed executing nox -s blacken:\n\nNone\nsynthtool > Wrote metadata to synth.metadata.\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 102, in <module>\n    main()\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 94, in main\n    spec.loader.exec_module(synth_module)  # type: ignore\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 205, in _call_with_frames_removed\n  File \"/tmpfs/src/git/autosynth/working_repo/synth.py\", line 68, in <module>\n    s.shell.run([\"nox\", \"-s\", \"blacken\"], hide_output=False)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 39, in run\n    raise exc\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 33, in run\n    encoding=\"utf-8\",\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py\", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['nox', '-s', 'blacken']' returned non-zero exit status 1.\n\nSynthesis failed\n\n```\n\nGoogle internal developers can see the full log [here](https://sponge/bc296324-7867-4eae-a113-8090e6bcc834).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/10", "repository_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer", "labels_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/10/comments", "events_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/10/events", "html_url": "https://github.com/googleapis/python-bigquery-datatransfer/issues/10", "id": 565719813, "node_id": "MDU6SXNzdWU1NjU3MTk4MTM=", "number": 10, "title": "BigQueryDatatransfer: create_transfer_config with authorization_code  throws  error '400 Request contains an invalid argument'", "user": {"login": "Rukeith", "id": 7069605, "node_id": "MDQ6VXNlcjcwNjk2MDU=", "avatar_url": "https://avatars3.githubusercontent.com/u/7069605?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Rukeith", "html_url": "https://github.com/Rukeith", "followers_url": "https://api.github.com/users/Rukeith/followers", "following_url": "https://api.github.com/users/Rukeith/following{/other_user}", "gists_url": "https://api.github.com/users/Rukeith/gists{/gist_id}", "starred_url": "https://api.github.com/users/Rukeith/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Rukeith/subscriptions", "organizations_url": "https://api.github.com/users/Rukeith/orgs", "repos_url": "https://api.github.com/users/Rukeith/repos", "events_url": "https://api.github.com/users/Rukeith/events{/privacy}", "received_events_url": "https://api.github.com/users/Rukeith/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814758072, "node_id": "MDU6TGFiZWwxODE0NzU4MDcy", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/:rotating_light:", "name": ":rotating_light:", "color": "FFFFFF", "default": false, "description": "This issue needs some love."}, {"id": 1814755878, "node_id": "MDU6TGFiZWwxODE0NzU1ODc4", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/api:%20bigquerydatatransfer", "name": "api: bigquerydatatransfer", "color": "687555", "default": false, "description": "Issues related to the BigQuery Data Transfer Service API."}, {"id": 1814758084, "node_id": "MDU6TGFiZWwxODE0NzU4MDg0", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/triage%20me", "name": "triage me", "color": "FF69B4", "default": false, "description": "I really want to be triaged."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-02-15T08:59:23Z", "updated_at": "2020-02-21T05:15:05Z", "closed_at": "2020-02-21T05:15:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "# My step\uff1a\r\n\r\n1. Get Authorization code\uff1aI use this URL to get auth code \r\n\r\n       https://www.gstatic.com/bigquerydatatransfer/oauthz/auth?clientId=<id from list data sources>&scope=https://www.googleapis.com/auth/adwords%20https://www.googleapis.com/auth/bigquery\r\n\r\n2. Create a service account with Project Owner\r\n3. Execute sample code\uff1a\r\n\r\n```\r\ndef run_quickstart():\r\n    from google.cloud import bigquery_datatransfer_v1\r\n    from google.protobuf.struct_pb2 import Struct\r\n\r\n    client = bigquery_datatransfer_v1.DataTransferServiceClient()\r\n\r\n    project = <project-id>\r\n    parent = client.location_path(project, 'us')\r\n    params = Struct()\r\n    params.update({\r\n        \"customer_id\": <customer-id>\r\n    })\r\n\r\n    transfer_config = {\r\n        \"destination_dataset_id\": \"test\",\r\n        \"display_name\": \"test\",\r\n        \"data_source_id\": \"adwords\",\r\n        \"params\": params\r\n    }\r\n\r\n    authorization_code = <authorization_code from step 1>\r\n    response = client.create_transfer_config(parent, transfer_config, authorization_code)\r\n    print(response)\r\n\r\nif __name__ == '__main__':\r\n    run_quickstart()\r\n```\r\n\r\nExpect\uff1aData transfer create\r\nBut I got the error\uff1a\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/project/lib/python3.7/site-packages/google/api_core/grpc_helpers.py\", line 57, in error_remapped_callable\r\n    return callable_(*args, **kwargs)\r\n  File \"/project/lib/python3.7/site-packages/grpc/_channel.py\", line 826, in __call__\r\n    return _end_unary_response_blocking(state, call, False, None)\r\n  File \"/project/lib/python3.7/site-packages/grpc/_channel.py\", line 729, in _end_unary_response_blocking\r\n    raise _InactiveRpcError(state)\r\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\r\n\tstatus = StatusCode.INVALID_ARGUMENT\r\n\tdetails = \"Request contains an invalid argument.\"\r\n\tdebug_error_string = \"{\"created\":\"@1581747953.387292000\",\"description\":\"Error received from peer ipv6:[2404:6800:4012:1::200a]:443\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1056,\"grpc_message\":\"Request contains an invalid argument.\",\"grpc_status\":3}\"\r\n>\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nTraceback (most recent call last):\r\n  File \"app.py\", line 49, in <module>\r\n    run_quickstart()\r\n  File \"app.py\", line 40, in run_quickstart\r\n    parent, transfer_config, authorization_code)\r\n  File \"/project/lib/python3.7/site-packages/google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client.py\", line 563, in create_transfer_config\r\n    request, retry=retry, timeout=timeout, metadata=metadata\r\n  File \"/project/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py\", line 143, in __call__\r\n    return wrapped_func(*args, **kwargs)\r\n  File \"/project/lib/python3.7/site-packages/google/api_core/retry.py\", line 286, in retry_wrapped_func\r\n    on_error=on_error,\r\n  File \"/project/lib/python3.7/site-packages/google/api_core/retry.py\", line 184, in retry_target\r\n    return target()\r\n  File \"/project/lib/python3.7/site-packages/google/api_core/timeout.py\", line 214, in func_with_timeout\r\n    return func(*args, **kwargs)\r\n  File \"/project/lib/python3.7/site-packages/google/api_core/grpc_helpers.py\", line 59, in error_remapped_callable\r\n    six.raise_from(exceptions.from_grpc_error(exc), exc)\r\n  File \"<string>\", line 3, in raise_from\r\ngoogle.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.\r\n\r\n```\r\n\r\nI couldn't find which step is wrong. Please kind to help me to figure it out.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/7", "repository_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer", "labels_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/7/comments", "events_url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/issues/7/events", "html_url": "https://github.com/googleapis/python-bigquery-datatransfer/issues/7", "id": 560701285, "node_id": "MDU6SXNzdWU1NjA3MDEyODU=", "number": 7, "title": "google-cloud-bigquery-datatransfer Readme code sample import does not work", "user": {"login": "gavin-haynes-grow", "id": 56007075, "node_id": "MDQ6VXNlcjU2MDA3MDc1", "avatar_url": "https://avatars2.githubusercontent.com/u/56007075?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gavin-haynes-grow", "html_url": "https://github.com/gavin-haynes-grow", "followers_url": "https://api.github.com/users/gavin-haynes-grow/followers", "following_url": "https://api.github.com/users/gavin-haynes-grow/following{/other_user}", "gists_url": "https://api.github.com/users/gavin-haynes-grow/gists{/gist_id}", "starred_url": "https://api.github.com/users/gavin-haynes-grow/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gavin-haynes-grow/subscriptions", "organizations_url": "https://api.github.com/users/gavin-haynes-grow/orgs", "repos_url": "https://api.github.com/users/gavin-haynes-grow/repos", "events_url": "https://api.github.com/users/gavin-haynes-grow/events{/privacy}", "received_events_url": "https://api.github.com/users/gavin-haynes-grow/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814755878, "node_id": "MDU6TGFiZWwxODE0NzU1ODc4", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/api:%20bigquerydatatransfer", "name": "api: bigquerydatatransfer", "color": "687555", "default": false, "description": "Issues related to the BigQuery Data Transfer Service API."}, {"id": 1814758063, "node_id": "MDU6TGFiZWwxODE0NzU4MDYz", "url": "https://api.github.com/repos/googleapis/python-bigquery-datatransfer/labels/type:%20docs", "name": "type: docs", "color": "0000A0", "default": false, "description": "Improvement to the documentation for an API."}], "state": "closed", "locked": false, "assignee": {"login": "IlyaFaer", "id": 26030071, "node_id": "MDQ6VXNlcjI2MDMwMDcx", "avatar_url": "https://avatars1.githubusercontent.com/u/26030071?v=4", "gravatar_id": "", "url": "https://api.github.com/users/IlyaFaer", "html_url": "https://github.com/IlyaFaer", "followers_url": "https://api.github.com/users/IlyaFaer/followers", "following_url": "https://api.github.com/users/IlyaFaer/following{/other_user}", "gists_url": "https://api.github.com/users/IlyaFaer/gists{/gist_id}", "starred_url": "https://api.github.com/users/IlyaFaer/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/IlyaFaer/subscriptions", "organizations_url": "https://api.github.com/users/IlyaFaer/orgs", "repos_url": "https://api.github.com/users/IlyaFaer/repos", "events_url": "https://api.github.com/users/IlyaFaer/events{/privacy}", "received_events_url": "https://api.github.com/users/IlyaFaer/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "IlyaFaer", "id": 26030071, "node_id": "MDQ6VXNlcjI2MDMwMDcx", "avatar_url": "https://avatars1.githubusercontent.com/u/26030071?v=4", "gravatar_id": "", "url": "https://api.github.com/users/IlyaFaer", "html_url": "https://github.com/IlyaFaer", "followers_url": "https://api.github.com/users/IlyaFaer/followers", "following_url": "https://api.github.com/users/IlyaFaer/following{/other_user}", "gists_url": "https://api.github.com/users/IlyaFaer/gists{/gist_id}", "starred_url": "https://api.github.com/users/IlyaFaer/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/IlyaFaer/subscriptions", "organizations_url": "https://api.github.com/users/IlyaFaer/orgs", "repos_url": "https://api.github.com/users/IlyaFaer/repos", "events_url": "https://api.github.com/users/IlyaFaer/events{/privacy}", "received_events_url": "https://api.github.com/users/IlyaFaer/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2020-02-05T21:11:31Z", "updated_at": "2020-03-04T17:20:24Z", "closed_at": "2020-03-04T17:20:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "With google-cloud-bigquery-datatransfer 0.4.1, python3.7.5, this import works:\r\n\r\n```\r\nimport google.cloud.bigquery_datatransfer_v1\r\n```\r\n\r\nbut the readme at https://github.com/googleapis/google-cloud-python/blob/master/bigquery_datatransfer/README.rst contains this, which does not work for me:\r\n\r\n```\r\nfrom google.cloud.bigquery import datatransfer_v1\r\n```\r\n\r\nIs something off for me or is the Readme just wrong? Looks like the import I'm using matches the actual directory structure as well as the tests.", "performed_via_github_app": null, "score": 1.0}]}