{"total_count": 61, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/pypa/readme_renderer/issues/167", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/167/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/167/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/167/events", "html_url": "https://github.com/pypa/readme_renderer/issues/167", "id": 641366021, "node_id": "MDU6SXNzdWU2NDEzNjYwMjE=", "number": 167, "title": "Add support for HTML in Mark Down (Requests.Py)", "user": {"login": "SimiCode", "id": 20975616, "node_id": "MDQ6VXNlcjIwOTc1NjE2", "avatar_url": "https://avatars3.githubusercontent.com/u/20975616?v=4", "gravatar_id": "", "url": "https://api.github.com/users/SimiCode", "html_url": "https://github.com/SimiCode", "followers_url": "https://api.github.com/users/SimiCode/followers", "following_url": "https://api.github.com/users/SimiCode/following{/other_user}", "gists_url": "https://api.github.com/users/SimiCode/gists{/gist_id}", "starred_url": "https://api.github.com/users/SimiCode/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/SimiCode/subscriptions", "organizations_url": "https://api.github.com/users/SimiCode/orgs", "repos_url": "https://api.github.com/users/SimiCode/repos", "events_url": "https://api.github.com/users/SimiCode/events{/privacy}", "received_events_url": "https://api.github.com/users/SimiCode/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122147, "node_id": "MDU6TGFiZWw4MzEyMjE0Nw==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2020-06-18T15:14:06Z", "updated_at": "2020-06-19T15:19:22Z", "closed_at": "2020-06-19T05:03:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "**Describe the bug**\r\nI wanted to file this as a requests issue but then I realized that since the library README shows well on github, Its expected to do the same on PyPi.\r\n\r\n\r\n**To Reproduce**\r\n[Requests Github](https://github.com/psf/requests)\r\n[Requests PyPI](https://pypi.org/project/requests/)\r\n\r\n\r\nSo What can we do to make sure that there is more support for multiple MarkDown Stylings? I'm willing to help with that.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/161", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/161/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/161/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/161/events", "html_url": "https://github.com/pypa/readme_renderer/issues/161", "id": 581134665, "node_id": "MDU6SXNzdWU1ODExMzQ2NjU=", "number": 161, "title": "Tests borked with pygments 2.4+", "user": {"login": "scarabeusiv", "id": 1055830, "node_id": "MDQ6VXNlcjEwNTU4MzA=", "avatar_url": "https://avatars1.githubusercontent.com/u/1055830?v=4", "gravatar_id": "", "url": "https://api.github.com/users/scarabeusiv", "html_url": "https://github.com/scarabeusiv", "followers_url": "https://api.github.com/users/scarabeusiv/followers", "following_url": "https://api.github.com/users/scarabeusiv/following{/other_user}", "gists_url": "https://api.github.com/users/scarabeusiv/gists{/gist_id}", "starred_url": "https://api.github.com/users/scarabeusiv/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/scarabeusiv/subscriptions", "organizations_url": "https://api.github.com/users/scarabeusiv/orgs", "repos_url": "https://api.github.com/users/scarabeusiv/repos", "events_url": "https://api.github.com/users/scarabeusiv/events{/privacy}", "received_events_url": "https://api.github.com/users/scarabeusiv/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-03-14T09:55:21Z", "updated_at": "2020-03-14T17:48:55Z", "closed_at": "2020-03-14T17:48:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "The clasification changed and pygments are now py3 based. That causes the fixtures to have different labels.\r\n\r\nTrivial patch fixing the failures: [pygments25.txt](https://github.com/pypa/readme_renderer/files/4332499/pygments25.txt)\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/156", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/156/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/156/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/156/events", "html_url": "https://github.com/pypa/readme_renderer/issues/156", "id": 457507166, "node_id": "MDU6SXNzdWU0NTc1MDcxNjY=", "number": 156, "title": "Status of markdown support", "user": {"login": "ulope", "id": 55078, "node_id": "MDQ6VXNlcjU1MDc4", "avatar_url": "https://avatars0.githubusercontent.com/u/55078?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ulope", "html_url": "https://github.com/ulope", "followers_url": "https://api.github.com/users/ulope/followers", "following_url": "https://api.github.com/users/ulope/following{/other_user}", "gists_url": "https://api.github.com/users/ulope/gists{/gist_id}", "starred_url": "https://api.github.com/users/ulope/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ulope/subscriptions", "organizations_url": "https://api.github.com/users/ulope/orgs", "repos_url": "https://api.github.com/users/ulope/repos", "events_url": "https://api.github.com/users/ulope/events{/privacy}", "received_events_url": "https://api.github.com/users/ulope/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-06-18T14:12:30Z", "updated_at": "2019-06-24T16:38:46Z", "closed_at": "2019-06-24T16:38:46Z", "author_association": "NONE", "active_lock_reason": null, "body": "The README claims that this module supports markdown:\r\nhttps://github.com/pypa/readme_renderer/blob/7bf7529296acfa7db0edf7914cb4571d691b63ee/README.rst#L6 \r\n#55 seems to support this. \r\nYet looking at the code there seems to be no way to actually invoke the markdown render check.\r\n\r\nIs that an oversight, or was markdown support removed again without updating the readme?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/154", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/154/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/154/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/154/events", "html_url": "https://github.com/pypa/readme_renderer/issues/154", "id": 453080490, "node_id": "MDU6SXNzdWU0NTMwODA0OTA=", "number": 154, "title": "Support math directive", "user": {"login": "texasaggie97", "id": 11483903, "node_id": "MDQ6VXNlcjExNDgzOTAz", "avatar_url": "https://avatars1.githubusercontent.com/u/11483903?v=4", "gravatar_id": "", "url": "https://api.github.com/users/texasaggie97", "html_url": "https://github.com/texasaggie97", "followers_url": "https://api.github.com/users/texasaggie97/followers", "following_url": "https://api.github.com/users/texasaggie97/following{/other_user}", "gists_url": "https://api.github.com/users/texasaggie97/gists{/gist_id}", "starred_url": "https://api.github.com/users/texasaggie97/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/texasaggie97/subscriptions", "organizations_url": "https://api.github.com/users/texasaggie97/orgs", "repos_url": "https://api.github.com/users/texasaggie97/repos", "events_url": "https://api.github.com/users/texasaggie97/events{/privacy}", "received_events_url": "https://api.github.com/users/texasaggie97/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-06-06T14:59:18Z", "updated_at": "2019-06-06T15:26:20Z", "closed_at": "2019-06-06T15:26:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "In #115 the underlying cause is that readme_renderer doesn't support `.. math::`. I'm not sure that that issue will explicitly cover adding support, so I am opening this one. If it would, feel free to close this one.\r\n\r\nI would like to use the same readme on readthedocs as well as using it for the long_description.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/153", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/153/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/153/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/153/events", "html_url": "https://github.com/pypa/readme_renderer/issues/153", "id": 448481035, "node_id": "MDU6SXNzdWU0NDg0ODEwMzU=", "number": 153, "title": "`twine check` passes, rst doesn't render on pypi", "user": {"login": "lzkelley", "id": 3839265, "node_id": "MDQ6VXNlcjM4MzkyNjU=", "avatar_url": "https://avatars0.githubusercontent.com/u/3839265?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lzkelley", "html_url": "https://github.com/lzkelley", "followers_url": "https://api.github.com/users/lzkelley/followers", "following_url": "https://api.github.com/users/lzkelley/following{/other_user}", "gists_url": "https://api.github.com/users/lzkelley/gists{/gist_id}", "starred_url": "https://api.github.com/users/lzkelley/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lzkelley/subscriptions", "organizations_url": "https://api.github.com/users/lzkelley/orgs", "repos_url": "https://api.github.com/users/lzkelley/repos", "events_url": "https://api.github.com/users/lzkelley/events{/privacy}", "received_events_url": "https://api.github.com/users/lzkelley/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-05-25T16:36:30Z", "updated_at": "2019-05-25T16:51:56Z", "closed_at": "2019-05-25T16:51:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "Similar to [this issue](https://github.com/pypa/readme_renderer/issues/115) my `twine check dist/*` command passes without any warnings or errors, but my `README.rst` is still failing to render on `pypi`: [test.pypi package here](https://test.pypi.org/project/kalepy/0.1.3b0/).  Unlike the linked issue, my readme doesn't use any math or external configuration files (etc).  I'm not sure what else to do to debug this...  any help appreciated, thanks!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/152", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/152/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/152/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/152/events", "html_url": "https://github.com/pypa/readme_renderer/issues/152", "id": 444549880, "node_id": "MDU6SXNzdWU0NDQ1NDk4ODA=", "number": 152, "title": "reStrustucturedText description error when language unknow, but valid rST", "user": {"login": "scopatz", "id": 320553, "node_id": "MDQ6VXNlcjMyMDU1Mw==", "avatar_url": "https://avatars2.githubusercontent.com/u/320553?v=4", "gravatar_id": "", "url": "https://api.github.com/users/scopatz", "html_url": "https://github.com/scopatz", "followers_url": "https://api.github.com/users/scopatz/followers", "following_url": "https://api.github.com/users/scopatz/following{/other_user}", "gists_url": "https://api.github.com/users/scopatz/gists{/gist_id}", "starred_url": "https://api.github.com/users/scopatz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/scopatz/subscriptions", "organizations_url": "https://api.github.com/users/scopatz/orgs", "repos_url": "https://api.github.com/users/scopatz/repos", "events_url": "https://api.github.com/users/scopatz/events{/privacy}", "received_events_url": "https://api.github.com/users/scopatz/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-05-15T14:12:45Z", "updated_at": "2019-05-15T17:34:47Z", "closed_at": "2019-05-15T17:14:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "**Describe the bug**\r\n\r\nIf the `description` keyword contains valid rST, such as:\r\n\r\n```rst\r\n.. code-block:: xonsh\r\n\r\n    $ACTIVITIES = ['tag']\r\n    $TAG_PUSH = False\r\n\r\n```\r\n\r\nPyPI will reject an upload of this source of this package with \r\n\r\n```\r\nUpload failed (400): The description failed to render in the default format of \r\nreStructuredText. See https://pypi.org/help/#description-content-type for more information.\r\n```\r\n\r\nThe package may be uploaded if the above snippet is changed to:\r\n\r\n```rst\r\n.. code-block:: sh\r\n\r\n    $ACTIVITIES = ['tag']\r\n    $TAG_PUSH = False\r\n\r\n```\r\n\r\n**Expected behavior**\r\n<!-- A clear and concise description of what you expected to happen -->\r\n\r\nPyPI should either not care about the language of the code-block or give a more correct / descriptive error message, since the original snippet *is* valid rST.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/151", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/151/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/151/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/151/events", "html_url": "https://github.com/pypa/readme_renderer/issues/151", "id": 443930977, "node_id": "MDU6SXNzdWU0NDM5MzA5Nzc=", "number": 151, "title": "correct way to validate using readme_renderer with an exit code", "user": {"login": "svenevs", "id": 5871461, "node_id": "MDQ6VXNlcjU4NzE0NjE=", "avatar_url": "https://avatars0.githubusercontent.com/u/5871461?v=4", "gravatar_id": "", "url": "https://api.github.com/users/svenevs", "html_url": "https://github.com/svenevs", "followers_url": "https://api.github.com/users/svenevs/followers", "following_url": "https://api.github.com/users/svenevs/following{/other_user}", "gists_url": "https://api.github.com/users/svenevs/gists{/gist_id}", "starred_url": "https://api.github.com/users/svenevs/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/svenevs/subscriptions", "organizations_url": "https://api.github.com/users/svenevs/orgs", "repos_url": "https://api.github.com/users/svenevs/repos", "events_url": "https://api.github.com/users/svenevs/events{/privacy}", "received_events_url": "https://api.github.com/users/svenevs/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-05-14T13:56:48Z", "updated_at": "2019-05-14T20:42:53Z", "closed_at": "2019-05-14T20:42:16Z", "author_association": "NONE", "active_lock_reason": null, "body": "It used to be `python setup.py check -r -s`, which still currently works, but says:\r\n\r\n```\r\nwarning: Check: This command has been deprecated. Use `twine check` instead: https://packaging.python.org/guides/making-a-pypi-friendly-readme#validating-restructuredtext-markup\r\n\r\nwarning: Check: The project's long_description is either missing or empty.\r\n```\r\n\r\nbut it fails my test (`tox`) which is good.  But if I run the suggested command:\r\n\r\n```console\r\n$ twine check dist/*\r\nChecking distribution ...whl\r\nwarning: `long_description_content_type` missing.  defaulting to `text/x-rst`.\r\nwarning: `long_description` missing.\r\nPassed\r\nChecking distribution ...tar.gz:\r\nwarning: `long_description_content_type` missing.  defaulting to `text/x-rst`.\r\nwarning: `long_description` missing.\r\nPassed\r\n$ echo $?\r\n0\r\n```\r\n\r\nIt is helpful to have a failing exit code on warnings somehow, specifically on the package artifacts.  `python -m readme_renderer invalid.rst` will give a non-zero exit code on invalid RST for example, but I parse my README and extract a couple of things, so I can't use that directly.\r\n\r\nI didn't know if this was a twine issue or an issue here...sorry if I chose the wrong repo!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/150", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/150/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/150/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/150/events", "html_url": "https://github.com/pypa/readme_renderer/issues/150", "id": 420082792, "node_id": "MDU6SXNzdWU0MjAwODI3OTI=", "number": 150, "title": "Bad hint in UserWarning in `markdown.py`", "user": {"login": "kamichal", "id": 9801087, "node_id": "MDQ6VXNlcjk4MDEwODc=", "avatar_url": "https://avatars1.githubusercontent.com/u/9801087?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kamichal", "html_url": "https://github.com/kamichal", "followers_url": "https://api.github.com/users/kamichal/followers", "following_url": "https://api.github.com/users/kamichal/following{/other_user}", "gists_url": "https://api.github.com/users/kamichal/gists{/gist_id}", "starred_url": "https://api.github.com/users/kamichal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kamichal/subscriptions", "organizations_url": "https://api.github.com/users/kamichal/orgs", "repos_url": "https://api.github.com/users/kamichal/repos", "events_url": "https://api.github.com/users/kamichal/events{/privacy}", "received_events_url": "https://api.github.com/users/kamichal/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-03-12T16:26:21Z", "updated_at": "2019-03-12T18:14:39Z", "closed_at": "2019-03-12T18:14:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "If readme-renderer[md] is not available such a confusing information is being printed:\r\n```\r\n/local/lib/python2.7/site-packages/readme_renderer/markdown.py:38: UserWarning: Markdown renderers are not available. Install 'readme_render[md]' to enable Markdown rendering.\r\n  warnings.warn(_EXTRA_WARNING)\r\n```\r\nBut there is no such package `readme_render[md]` in pypi:\r\n`No matching distribution found for readme_render[md]`\r\nIt contains two typos and should be corrected to `readme-renderer[md]`.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/147", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/147/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/147/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/147/events", "html_url": "https://github.com/pypa/readme_renderer/issues/147", "id": 397822157, "node_id": "MDU6SXNzdWUzOTc4MjIxNTc=", "number": 147, "title": "rst admonitions (warning, note, tip, ...) rendering", "user": {"login": "paugier", "id": 8842662, "node_id": "MDQ6VXNlcjg4NDI2NjI=", "avatar_url": "https://avatars0.githubusercontent.com/u/8842662?v=4", "gravatar_id": "", "url": "https://api.github.com/users/paugier", "html_url": "https://github.com/paugier", "followers_url": "https://api.github.com/users/paugier/followers", "following_url": "https://api.github.com/users/paugier/following{/other_user}", "gists_url": "https://api.github.com/users/paugier/gists{/gist_id}", "starred_url": "https://api.github.com/users/paugier/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/paugier/subscriptions", "organizations_url": "https://api.github.com/users/paugier/orgs", "repos_url": "https://api.github.com/users/paugier/repos", "events_url": "https://api.github.com/users/paugier/events{/privacy}", "received_events_url": "https://api.github.com/users/paugier/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-01-10T08:32:32Z", "updated_at": "2019-01-10T16:13:45Z", "closed_at": "2019-01-10T16:13:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "**What's the problem this feature will solve?**\r\n\r\nAdmonitions (http://docutils.sourceforge.net/docs/ref/rst/directives.html#specific-admonitions) in README.rst does not appear correctly on PyPI.\r\n\r\nFor an example see the first warning admonition at the beginning of this README.rst : https://pypi.org/project/transonic/\r\n\r\n**Describe the solution you'd like**\r\n\r\nIt would be great if admonitions were displayed correctly, similarly as on readthedocs, see the corresponding warning admonition in https://transonic.readthedocs.io\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/145", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/145/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/145/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/145/events", "html_url": "https://github.com/pypa/readme_renderer/issues/145", "id": 387956330, "node_id": "MDU6SXNzdWUzODc5NTYzMzA=", "number": 145, "title": "clean() returns None in its test", "user": {"login": "bowlofeggs", "id": 354506, "node_id": "MDQ6VXNlcjM1NDUwNg==", "avatar_url": "https://avatars2.githubusercontent.com/u/354506?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bowlofeggs", "html_url": "https://github.com/bowlofeggs", "followers_url": "https://api.github.com/users/bowlofeggs/followers", "following_url": "https://api.github.com/users/bowlofeggs/following{/other_user}", "gists_url": "https://api.github.com/users/bowlofeggs/gists{/gist_id}", "starred_url": "https://api.github.com/users/bowlofeggs/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bowlofeggs/subscriptions", "organizations_url": "https://api.github.com/users/bowlofeggs/orgs", "repos_url": "https://api.github.com/users/bowlofeggs/repos", "events_url": "https://api.github.com/users/bowlofeggs/events{/privacy}", "received_events_url": "https://api.github.com/users/bowlofeggs/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-12-05T21:36:42Z", "updated_at": "2018-12-05T23:05:31Z", "closed_at": "2018-12-05T22:55:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "I see a failing test on Fedora Rawhide:\r\n\r\n```\r\n$ py.test tests/test_clean.py                                                                                           \r\n========================================== test session starts ==========================================\r\nplatform linux2 -- Python 2.7.15, pytest-3.9.3, py-1.7.0, pluggy-0.8.0\r\nrootdir: /home/bowlofeggs/rpmbuild/BUILD/readme_renderer-24.0, inifile: pytest.ini\r\nplugins: cov-2.5.1, celery-4.2.1, backports.unittest-mock-1.2.1\r\ncollected 1 item                                                                                        \r\n\r\ntests/test_clean.py F                                                                             [100%]\r\n\r\n=============================================== FAILURES ================================================\r\n___________________________________________ test_invalid_link ___________________________________________\r\n\r\n    def test_invalid_link():\r\n>       assert clean('<a href=\"http://exam](ple.com\">foo</a>') == \"<a>foo</a>\"\r\nE       assert None == '<a>foo</a>'\r\nE        +  where None = clean('<a href=\"http://exam](ple.com\">foo</a>')\r\n\r\ntests/test_clean.py:5: AssertionError\r\n=========================================== warnings summary ============================================\r\n/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:272\r\n  /usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:272: PytestWarning: Module already imported so cannot be rewritten: backports                                                                     \r\n    self.config,\r\n\r\n-- Docs: https://docs.pytest.org/en/latest/warnings.html\r\n================================= 1 failed, 1 warnings in 0.08 seconds ==================================\r\n```\r\n\r\nIt does seem that ```clean()``` is not returning a ```str```:\r\n\r\n```\r\n$ python3\r\nPython 3.7.1 (default, Nov  5 2018, 09:51:25)\r\n[GCC 8.2.1 20181011 (Red Hat 8.2.1-4)] on linux\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> from readme_renderer.clean import clean\r\n>>> clean('<a href=\"http://exam](ple.com\">foo</a>')\r\n>>> \r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/142", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/142/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/142/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/142/events", "html_url": "https://github.com/pypa/readme_renderer/issues/142", "id": 382160194, "node_id": "MDU6SXNzdWUzODIxNjAxOTQ=", "number": 142, "title": "No need for a warning about markdown renderers", "user": {"login": "nedbat", "id": 23789, "node_id": "MDQ6VXNlcjIzNzg5", "avatar_url": "https://avatars1.githubusercontent.com/u/23789?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nedbat", "html_url": "https://github.com/nedbat", "followers_url": "https://api.github.com/users/nedbat/followers", "following_url": "https://api.github.com/users/nedbat/following{/other_user}", "gists_url": "https://api.github.com/users/nedbat/gists{/gist_id}", "starred_url": "https://api.github.com/users/nedbat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nedbat/subscriptions", "organizations_url": "https://api.github.com/users/nedbat/orgs", "repos_url": "https://api.github.com/users/nedbat/repos", "events_url": "https://api.github.com/users/nedbat/events{/privacy}", "received_events_url": "https://api.github.com/users/nedbat/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-11-19T10:57:28Z", "updated_at": "2019-03-18T19:38:33Z", "closed_at": "2019-03-18T19:38:32Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have no markdown files in my project, yet when I run \"twine check dist/*\", I get a warning about \"Markdown renderers are not available.\"  The code looks like it will already issue this warning if markdown is used, so why also issue it on import?  This just adds needless noise to projects that don't use markdown.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/135", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/135/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/135/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/135/events", "html_url": "https://github.com/pypa/readme_renderer/issues/135", "id": 374487427, "node_id": "MDU6SXNzdWUzNzQ0ODc0Mjc=", "number": 135, "title": "Officially support Python 3.7", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1105860907, "node_id": "MDU6TGFiZWwxMTA1ODYwOTA3", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/good%20first%20issue", "name": "good first issue", "color": "0e8a16", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-10-26T17:58:26Z", "updated_at": "2019-05-06T13:38:34Z", "closed_at": "2019-05-06T13:38:34Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "- [ ] Test against 3.7\r\n- [ ] Add Python 3.7 classifier", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/133", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/133/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/133/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/133/events", "html_url": "https://github.com/pypa/readme_renderer/issues/133", "id": 373985193, "node_id": "MDU6SXNzdWUzNzM5ODUxOTM=", "number": 133, "title": "Warning message says to install readme_render[md] but cmarkgfm must be installed", "user": {"login": "kpinc", "id": 3226082, "node_id": "MDQ6VXNlcjMyMjYwODI=", "avatar_url": "https://avatars3.githubusercontent.com/u/3226082?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kpinc", "html_url": "https://github.com/kpinc", "followers_url": "https://api.github.com/users/kpinc/followers", "following_url": "https://api.github.com/users/kpinc/following{/other_user}", "gists_url": "https://api.github.com/users/kpinc/gists{/gist_id}", "starred_url": "https://api.github.com/users/kpinc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kpinc/subscriptions", "organizations_url": "https://api.github.com/users/kpinc/orgs", "repos_url": "https://api.github.com/users/kpinc/repos", "events_url": "https://api.github.com/users/kpinc/events{/privacy}", "received_events_url": "https://api.github.com/users/kpinc/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 4, "created_at": "2018-10-25T14:46:18Z", "updated_at": "2018-10-28T17:49:35Z", "closed_at": "2018-10-28T17:49:35Z", "author_association": "NONE", "active_lock_reason": null, "body": "This is something of an FYI because I'm not clear on what is really supposed to happen.\r\n\r\nI tried running \"twine check\" and got a message that the README.rst could not be checked and that 'readme_render[md]' needed to be installed.  But it seems that what needs to be installed is cmarkgfm.\r\n\r\nThe message is coming from readme_renderer.  (Seemingly markdown.py line 28.)\r\n\r\nFWIW, setup.py does not install_requires cmarkgfm either.\r\n\r\nThanks for listening.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/129", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/129/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/129/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/129/events", "html_url": "https://github.com/pypa/readme_renderer/issues/129", "id": 372032763, "node_id": "MDU6SXNzdWUzNzIwMzI3NjM=", "number": 129, "title": "Make cmarkgfm an optional depedency", "user": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2018-10-19T16:40:18Z", "updated_at": "2018-10-22T19:13:35Z", "closed_at": "2018-10-22T19:13:35Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/128", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/128/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/128/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/128/events", "html_url": "https://github.com/pypa/readme_renderer/issues/128", "id": 370259107, "node_id": "MDU6SXNzdWUzNzAyNTkxMDc=", "number": 128, "title": "Remove dependency on `python-future`?", "user": {"login": "asottile", "id": 1810591, "node_id": "MDQ6VXNlcjE4MTA1OTE=", "avatar_url": "https://avatars3.githubusercontent.com/u/1810591?v=4", "gravatar_id": "", "url": "https://api.github.com/users/asottile", "html_url": "https://github.com/asottile", "followers_url": "https://api.github.com/users/asottile/followers", "following_url": "https://api.github.com/users/asottile/following{/other_user}", "gists_url": "https://api.github.com/users/asottile/gists{/gist_id}", "starred_url": "https://api.github.com/users/asottile/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/asottile/subscriptions", "organizations_url": "https://api.github.com/users/asottile/orgs", "repos_url": "https://api.github.com/users/asottile/repos", "events_url": "https://api.github.com/users/asottile/events{/privacy}", "received_events_url": "https://api.github.com/users/asottile/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 1104546113, "node_id": "MDU6TGFiZWwxMTA0NTQ2MTEz", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/help%20wanted", "name": "help wanted", "color": "2d52a3", "default": true, "description": ""}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-10-15T17:11:16Z", "updated_at": "2018-10-25T22:03:51Z", "closed_at": "2018-10-25T22:03:51Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "python-future is notorious for breaking modules which use `try: / except:` to import version specific modules: (a few examples from things I've encounted: [1](https://github.com/jmcgeheeiv/pyfakefs/pull/441#issue-221957790) [2](https://github.com/Yelp/yelp_clog/pull/18#issue-64272423))\r\n\r\nlet me know if you'd be interested in me making a PR along these lines -- it seems `future` is only being used for `html.escape` right now:\r\n\r\n```diff\r\ndiff --git a/readme_renderer/txt.py b/readme_renderer/txt.py\r\nindex 0c0c533..3218922 100644\r\n--- a/readme_renderer/txt.py\r\n+++ b/readme_renderer/txt.py\r\n@@ -13,10 +13,18 @@\r\n # limitations under the License.\r\n from __future__ import absolute_import, division, print_function\r\n \r\n-from html import escape as html_escape\r\n+import sys\r\n \r\n from .clean import clean\r\n \r\n+if sys.version_info >= (3,):\r\n+    from html import escape as html_escape\r\n+else:\r\n+    from cgi import escape\r\n+\r\n+    def html_escape(s):\r\n+        return escape(s, quote=True).replace(\"'\", '&#x27;')\r\n+\r\n \r\n def render(raw, **kwargs):\r\n     rendered = html_escape(raw).replace(\"\\n\", \"<br>\")\r\ndiff --git a/setup.py b/setup.py\r\nindex 5f2b64a..16fa18c 100644\r\n--- a/setup.py\r\n+++ b/setup.py\r\n@@ -63,7 +63,6 @@ setuptools.setup(\r\n         \"bleach>=2.1.0\",\r\n         \"cmarkgfm>=0.2.0\",\r\n         \"docutils>=0.13.1\",\r\n-        \"future\",\r\n         \"Pygments\",\r\n         \"six\",\r\n     ],\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/127", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/127/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/127/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/127/events", "html_url": "https://github.com/pypa/readme_renderer/issues/127", "id": 368292589, "node_id": "MDU6SXNzdWUzNjgyOTI1ODk=", "number": 127, "title": "Add command to check a file", "user": {"login": "merwok", "id": 635179, "node_id": "MDQ6VXNlcjYzNTE3OQ==", "avatar_url": "https://avatars0.githubusercontent.com/u/635179?v=4", "gravatar_id": "", "url": "https://api.github.com/users/merwok", "html_url": "https://github.com/merwok", "followers_url": "https://api.github.com/users/merwok/followers", "following_url": "https://api.github.com/users/merwok/following{/other_user}", "gists_url": "https://api.github.com/users/merwok/gists{/gist_id}", "starred_url": "https://api.github.com/users/merwok/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/merwok/subscriptions", "organizations_url": "https://api.github.com/users/merwok/orgs", "repos_url": "https://api.github.com/users/merwok/repos", "events_url": "https://api.github.com/users/merwok/events{/privacy}", "received_events_url": "https://api.github.com/users/merwok/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2018-10-09T16:22:02Z", "updated_at": "2018-10-09T19:09:42Z", "closed_at": "2018-10-09T19:09:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "I would like an entry-point to check a reST or markdown file.\r\n\r\n(I\u2019ve heard about twine check but it doesn\u2019t work for me due to flit-tox mismatch.)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/125", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/125/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/125/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/125/events", "html_url": "https://github.com/pypa/readme_renderer/issues/125", "id": 364531326, "node_id": "MDU6SXNzdWUzNjQ1MzEzMjY=", "number": 125, "title": "Missing git tags for releases", "user": {"login": "felixonmars", "id": 1006477, "node_id": "MDQ6VXNlcjEwMDY0Nzc=", "avatar_url": "https://avatars3.githubusercontent.com/u/1006477?v=4", "gravatar_id": "", "url": "https://api.github.com/users/felixonmars", "html_url": "https://github.com/felixonmars", "followers_url": "https://api.github.com/users/felixonmars/followers", "following_url": "https://api.github.com/users/felixonmars/following{/other_user}", "gists_url": "https://api.github.com/users/felixonmars/gists{/gist_id}", "starred_url": "https://api.github.com/users/felixonmars/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/felixonmars/subscriptions", "organizations_url": "https://api.github.com/users/felixonmars/orgs", "repos_url": "https://api.github.com/users/felixonmars/repos", "events_url": "https://api.github.com/users/felixonmars/events{/privacy}", "received_events_url": "https://api.github.com/users/felixonmars/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-09-27T15:26:41Z", "updated_at": "2018-09-27T15:47:01Z", "closed_at": "2018-09-27T15:47:01Z", "author_association": "NONE", "active_lock_reason": null, "body": "21.0 and 22.0 are seen on PyPI but not in git tags.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/124", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/124/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/124/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/124/events", "html_url": "https://github.com/pypa/readme_renderer/issues/124", "id": 363253822, "node_id": "MDU6SXNzdWUzNjMyNTM4MjI=", "number": 124, "title": "Switch to `cmarkgfm` now seems to require a compiler", "user": {"login": "raiderrobert", "id": 806571, "node_id": "MDQ6VXNlcjgwNjU3MQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/806571?v=4", "gravatar_id": "", "url": "https://api.github.com/users/raiderrobert", "html_url": "https://github.com/raiderrobert", "followers_url": "https://api.github.com/users/raiderrobert/followers", "following_url": "https://api.github.com/users/raiderrobert/following{/other_user}", "gists_url": "https://api.github.com/users/raiderrobert/gists{/gist_id}", "starred_url": "https://api.github.com/users/raiderrobert/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/raiderrobert/subscriptions", "organizations_url": "https://api.github.com/users/raiderrobert/orgs", "repos_url": "https://api.github.com/users/raiderrobert/repos", "events_url": "https://api.github.com/users/raiderrobert/events{/privacy}", "received_events_url": "https://api.github.com/users/raiderrobert/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-09-24T17:53:55Z", "updated_at": "2018-09-24T18:00:35Z", "closed_at": "2018-09-24T18:00:33Z", "author_association": "NONE", "active_lock_reason": null, "body": "The switch to `cmarkgfm` (on this commit, I think https://github.com/pypa/readme_renderer/commit/50d399cd6cc1cf45a780f9e9057b397c0cc14586 ) seems to require a compiler based on the message below.\r\n\r\nI'm running on a docker image without all those things installed, and I expect many others are too. \r\n\r\nERROR\r\n``` shell\r\nUsing Docker executor with image python:3.6-alpine3.8 ...\r\nPulling docker image python:3.6-alpine3.8 ...\r\nUsing docker image sha256:da04299043e37f3ac248a7045993ce5dc84bc08a163713331202b908096dce96 for python:3.6-alpine3.8 ...\r\nRunning on runner-71faaddd-project-42-concurrent-0 via 5eb10032be48...\r\n\r\n***SNIP***\r\n\r\n$ pip install -U setuptools wheel twine\r\nCollecting setuptools\r\n  Downloading https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl (569kB)\r\nRequirement already up-to-date: wheel in /usr/local/lib/python3.6/site-packages (0.31.1)\r\nCollecting twine\r\n  Downloading https://files.pythonhosted.org/packages/13/ad/4738f78528f4c47ef1fd145e929bc123f19b0a424d6847ce618365c2826e/twine-1.12.0-py2.py3-none-any.whl\r\nCollecting pkginfo>=1.4.2 (from twine)\r\n  Downloading https://files.pythonhosted.org/packages/a3/fe/f32a48d48f40a7209be9825fba2566cab92364787cf37de2e08300dd6ce7/pkginfo-1.4.2-py2.py3-none-any.whl\r\nCollecting requests!=2.15,!=2.16,>=2.5.0 (from twine)\r\n  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)\r\nCollecting tqdm>=4.14 (from twine)\r\n  Downloading https://files.pythonhosted.org/packages/79/43/19c9fee28110cd47f73e6bc596394337fe9f3e5825b4de402bbf30b3beb5/tqdm-4.26.0-py2.py3-none-any.whl (43kB)\r\nCollecting readme-renderer>=21.0 (from twine)\r\n  Downloading https://files.pythonhosted.org/packages/a8/a1/6f474ee3be067328e11faa3c6391823ceb687cabd54ac6801c8db346d6e4/readme_renderer-22.0-py2.py3-none-any.whl\r\nCollecting requests-toolbelt>=0.8.0 (from twine)\r\n  Downloading https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB)\r\nCollecting urllib3<1.24,>=1.21.1 (from requests!=2.15,!=2.16,>=2.5.0->twine)\r\n  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)\r\nCollecting chardet<3.1.0,>=3.0.2 (from requests!=2.15,!=2.16,>=2.5.0->twine)\r\n  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)\r\nCollecting certifi>=2017.4.17 (from requests!=2.15,!=2.16,>=2.5.0->twine)\r\n  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)\r\nCollecting idna<2.8,>=2.5 (from requests!=2.15,!=2.16,>=2.5.0->twine)\r\n  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)\r\nCollecting cmarkgfm>=0.2.0 (from readme-renderer>=21.0->twine)\r\n  Downloading https://files.pythonhosted.org/packages/e2/a3/4021fbc17c5afe7f307d14eba0d6899a8e66b351ab65649b1c89c50a836d/cmarkgfm-0.4.2.tar.gz (133kB)\r\n    Complete output from command python setup.py egg_info:\r\n    \r\n        No working compiler found, or bogus compiler options passed to\r\n        the compiler from Python's standard \"distutils\" module.  See\r\n        the error messages above.  Likely, the problem is not related\r\n        to CFFI but generic to the setup.py of any Python package that\r\n        tries to compile C code.  (Hints: on OS/X 10.8, for errors about\r\n        -mno-fused-madd see http://stackoverflow.com/questions/22313407/\r\n        Otherwise, see https://wiki.python.org/moin/CompLangPython or\r\n        the IRC channel #python on irc.freenode.net.)\r\n    Traceback (most recent call last):\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 154, in save_modules\r\n        yield saved\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 195, in setup_context\r\n        yield\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 250, in run_setup\r\n        _execfile(setup_script, ns)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 45, in _execfile\r\n        exec(code, globals, locals)\r\n      File \"/tmp/easy_install-qbnzeym8/cffi-1.11.5/setup.py\", line 142, in <module>\r\n      File \"/tmp/easy_install-qbnzeym8/cffi-1.11.5/setup.py\", line 77, in ask_supports_thread\r\n      File \"/tmp/easy_install-qbnzeym8/cffi-1.11.5/setup.py\", line 59, in no_working_compiler_found\r\n        cmdclass={\r\n    SystemExit: 1\r\n    \r\n    During handling of the above exception, another exception occurred:\r\n    \r\n    Traceback (most recent call last):\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 1141, in run_setup\r\n        run_setup(setup_script, args)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 253, in run_setup\r\n        raise\r\n      File \"/usr/local/lib/python3.6/contextlib.py\", line 99, in __exit__\r\n        self.gen.throw(type, value, traceback)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 195, in setup_context\r\n        yield\r\n      File \"/usr/local/lib/python3.6/contextlib.py\", line 99, in __exit__\r\n        self.gen.throw(type, value, traceback)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 166, in save_modules\r\n        saved_exc.resume()\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 141, in resume\r\n        six.reraise(type, exc, self._tb)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/_vendor/six.py\", line 685, in reraise\r\n        raise value.with_traceback(tb)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 154, in save_modules\r\n        yield saved\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 195, in setup_context\r\n        yield\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 250, in run_setup\r\n        _execfile(setup_script, ns)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/sandbox.py\", line 45, in _execfile\r\n        exec(code, globals, locals)\r\n      File \"/tmp/easy_install-qbnzeym8/cffi-1.11.5/setup.py\", line 142, in <module>\r\n      File \"/tmp/easy_install-qbnzeym8/cffi-1.11.5/setup.py\", line 77, in ask_supports_thread\r\n      File \"/tmp/easy_install-qbnzeym8/cffi-1.11.5/setup.py\", line 59, in no_working_compiler_found\r\n        cmdclass={\r\n    SystemExit: 1\r\n    \r\n    During handling of the above exception, another exception occurred:\r\n    \r\n    Traceback (most recent call last):\r\n      File \"<string>\", line 1, in <module>\r\n      File \"/tmp/pip-install-3krl0lcz/cmarkgfm/setup.py\", line 60, in <module>\r\n        'build_ext': custom_build_ext,\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/__init__.py\", line 139, in setup\r\n        _install_setup_requires(attrs)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/__init__.py\", line 134, in _install_setup_requires\r\n        dist.fetch_build_eggs(dist.setup_requires)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/dist.py\", line 514, in fetch_build_eggs\r\n        replace_conflicting=True,\r\n      File \"/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 777, in resolve\r\n        replace_conflicting=replace_conflicting\r\n      File \"/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 1060, in best_match\r\n        return self.obtain(req, installer)\r\n      File \"/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 1072, in obtain\r\n        return installer(requirement)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/dist.py\", line 581, in fetch_build_egg\r\n        return cmd.easy_install(req)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 676, in easy_install\r\n        return self.install_item(spec, dist.location, tmpdir, deps)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 702, in install_item\r\n        dists = self.install_eggs(spec, download, tmpdir)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 887, in install_eggs\r\n        return self.build_and_install(setup_script, setup_base)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 1155, in build_and_install\r\n        self.run_setup(setup_script, setup_base, args)\r\n      File \"/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py\", line 1143, in run_setup\r\n        raise DistutilsError(\"Setup script exited with %s\" % (v.args[0],))\r\n    distutils.errors.DistutilsError: Setup script exited with 1\r\n    \r\n    ----------------------------------------\r\nCommand \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-install-3krl0lcz/cmarkgfm/\r\nERROR: Job failed: exit code 1\r\n```\r\n\r\n**Solution/Work Around**\r\n\r\nMy current solution is to basically prevent using this commit with `twine` as the previous one worked just fine.\r\n\r\ngitlab.ci config\r\n``` \r\nimage:\r\n  python:3.6-alpine3.8\r\n\r\nstages:\r\n  - deploy\r\n\r\npackage:\r\n  stage: deploy\r\n  only:\r\n    - tags\r\n  script:\r\n    - pip install -r requirements/test.txt\r\n    - pip install -U setuptools wheel \"twine<1.12\"\r\n    - python setup.py bdist_wheel\r\n    - twine upload --repository-url https://pypi.example.com/simple/ dist/*\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/118", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/118/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/118/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/118/events", "html_url": "https://github.com/pypa/readme_renderer/issues/118", "id": 359598043, "node_id": "MDU6SXNzdWUzNTk1OTgwNDM=", "number": 118, "title": "this tools should install first build-requires from pep-517 before executing", "user": {"login": "gaborbernat", "id": 690238, "node_id": "MDQ6VXNlcjY5MDIzOA==", "avatar_url": "https://avatars1.githubusercontent.com/u/690238?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gaborbernat", "html_url": "https://github.com/gaborbernat", "followers_url": "https://api.github.com/users/gaborbernat/followers", "following_url": "https://api.github.com/users/gaborbernat/following{/other_user}", "gists_url": "https://api.github.com/users/gaborbernat/gists{/gist_id}", "starred_url": "https://api.github.com/users/gaborbernat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gaborbernat/subscriptions", "organizations_url": "https://api.github.com/users/gaborbernat/orgs", "repos_url": "https://api.github.com/users/gaborbernat/repos", "events_url": "https://api.github.com/users/gaborbernat/events{/privacy}", "received_events_url": "https://api.github.com/users/gaborbernat/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 17, "created_at": "2018-09-12T18:22:45Z", "updated_at": "2018-09-27T15:47:44Z", "closed_at": "2018-09-27T15:47:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "Otherwise, build extensions (e.g. setuptools-scm) cannot be interpreted (unless also fored in setup_requires). This package tries to look into ``setup.py`` so should first ensure it has ``build-requires``. \r\n\r\n```bash\r\n2018-09-12T17:48:42.0336128Z package-description runtests: commands[0] | python setup.py check -r -s\r\n2018-09-12T17:48:42.3094762Z running check\r\n2018-09-12T17:48:42.3112596Z /opt/hostedtoolcache/Python/3.7.0/x64/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'\r\n2018-09-12T17:48:42.3129581Z   warnings.warn(msg)\r\n2018-09-12T17:48:42.3145311Z warning: Check: missing required meta-data: version\r\n2018-09-12T17:48:42.3153240Z \r\n2018-09-12T17:48:42.9435964Z The project's long description is valid RST.\r\n2018-09-12T17:48:42.9454270Z error: Please correct your package.\r\n2018-09-12T17:48:43.0199465Z ERROR: InvocationError for command '/home/vsts/work/1/s/.tox/package-description/bin/python setup.py check -r -s' (exited with code 1)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/117", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/117/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/117/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/117/events", "html_url": "https://github.com/pypa/readme_renderer/issues/117", "id": 357503656, "node_id": "MDU6SXNzdWUzNTc1MDM2NTY=", "number": 117, "title": "docs: How to render a README file?", "user": {"login": "guettli", "id": 414336, "node_id": "MDQ6VXNlcjQxNDMzNg==", "avatar_url": "https://avatars3.githubusercontent.com/u/414336?v=4", "gravatar_id": "", "url": "https://api.github.com/users/guettli", "html_url": "https://github.com/guettli", "followers_url": "https://api.github.com/users/guettli/followers", "following_url": "https://api.github.com/users/guettli/following{/other_user}", "gists_url": "https://api.github.com/users/guettli/gists{/gist_id}", "starred_url": "https://api.github.com/users/guettli/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/guettli/subscriptions", "organizations_url": "https://api.github.com/users/guettli/orgs", "repos_url": "https://api.github.com/users/guettli/repos", "events_url": "https://api.github.com/users/guettli/events{/privacy}", "received_events_url": "https://api.github.com/users/guettli/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2018-09-06T05:42:29Z", "updated_at": "2018-09-22T20:11:06Z", "closed_at": "2018-09-06T10:42:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "Please tell us how to use the readme renderer.\r\n\r\nI don't understand the current docs I see at https://github.com/pypa/readme_renderer\r\n\r\nHow can I render a README which is called foo.rst? Is there no command line tool which I can call like this `readme_render foo.rst`?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/112", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/112/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/112/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/112/events", "html_url": "https://github.com/pypa/readme_renderer/issues/112", "id": 345447198, "node_id": "MDU6SXNzdWUzNDU0NDcxOTg=", "number": 112, "title": "Inconsistencies and problems in when images are rendered from RST", "user": {"login": "mila", "id": 118834, "node_id": "MDQ6VXNlcjExODgzNA==", "avatar_url": "https://avatars2.githubusercontent.com/u/118834?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mila", "html_url": "https://github.com/mila", "followers_url": "https://api.github.com/users/mila/followers", "following_url": "https://api.github.com/users/mila/following{/other_user}", "gists_url": "https://api.github.com/users/mila/gists{/gist_id}", "starred_url": "https://api.github.com/users/mila/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mila/subscriptions", "organizations_url": "https://api.github.com/users/mila/orgs", "repos_url": "https://api.github.com/users/mila/repos", "events_url": "https://api.github.com/users/mila/events{/privacy}", "received_events_url": "https://api.github.com/users/mila/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2018-07-28T13:07:46Z", "updated_at": "2018-09-18T15:04:09Z", "closed_at": "2018-09-18T15:04:08Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Investigating https://github.com/pypa/warehouse/issues/4023, I found multiple related problems:\r\n\r\n- HTML code for SVG images can be quite different from other image types.\r\n- For SVG, width and height are assigned to width=\"...\" and height=\"...\" attributes, so relative dimensions cannot work.\r\n- For non-SVG image types, width and height are ignored.\r\n- For SVG images, align=\"...\" attribute is set, which does not help with styling.\r\n- For non-SVG images, align is ignored.\r\n- For most images, alt=\"\" fallbacks to image URL, not for SVG.\r\n- Detection of SVG is broken, e.g. URL like `.../django-multi-gtfs.svg?branch=master` is not detected as SVG. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/109", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/109/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/109/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/109/events", "html_url": "https://github.com/pypa/readme_renderer/issues/109", "id": 328574709, "node_id": "MDU6SXNzdWUzMjg1NzQ3MDk=", "number": 109, "title": "Untraceable error", "user": {"login": "cefn", "id": 159819, "node_id": "MDQ6VXNlcjE1OTgxOQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/159819?v=4", "gravatar_id": "", "url": "https://api.github.com/users/cefn", "html_url": "https://github.com/cefn", "followers_url": "https://api.github.com/users/cefn/followers", "following_url": "https://api.github.com/users/cefn/following{/other_user}", "gists_url": "https://api.github.com/users/cefn/gists{/gist_id}", "starred_url": "https://api.github.com/users/cefn/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/cefn/subscriptions", "organizations_url": "https://api.github.com/users/cefn/orgs", "repos_url": "https://api.github.com/users/cefn/repos", "events_url": "https://api.github.com/users/cefn/events{/privacy}", "received_events_url": "https://api.github.com/users/cefn/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-06-01T16:00:10Z", "updated_at": "2018-06-02T12:27:50Z", "closed_at": "2018-06-01T22:44:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "I just ran the setup.py check on [my source](https://github.com/vgkits/vgkits-vanguard/blob/b9d769cd911ad685f0d900608fc49b0ff2b1145d/setup.py)\r\n\r\nIt resulted in the following mystifying error, which indicates no line, source or identifiable structure to investigate and fix...\r\n\r\n```\r\n$ python3 setup.py check -r -s\r\nrunning check\r\nwarning: Check: The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:\r\nline : Error: Anonymous hyperlink mismatch: 1 references but 0 targets.\r\nSee \"backrefs\" attribute for IDs.\r\n``` \r\n\r\nHow do I proceed to identify where and what the error actually is?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/108", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/108/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/108/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/108/events", "html_url": "https://github.com/pypa/readme_renderer/issues/108", "id": 327445979, "node_id": "MDU6SXNzdWUzMjc0NDU5Nzk=", "number": 108, "title": "RST accepted by readme_renderer, but failing to upload to PyPI", "user": {"login": "stuhood", "id": 46740, "node_id": "MDQ6VXNlcjQ2NzQw", "avatar_url": "https://avatars1.githubusercontent.com/u/46740?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stuhood", "html_url": "https://github.com/stuhood", "followers_url": "https://api.github.com/users/stuhood/followers", "following_url": "https://api.github.com/users/stuhood/following{/other_user}", "gists_url": "https://api.github.com/users/stuhood/gists{/gist_id}", "starred_url": "https://api.github.com/users/stuhood/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stuhood/subscriptions", "organizations_url": "https://api.github.com/users/stuhood/orgs", "repos_url": "https://api.github.com/users/stuhood/repos", "events_url": "https://api.github.com/users/stuhood/events{/privacy}", "received_events_url": "https://api.github.com/users/stuhood/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-05-29T18:57:25Z", "updated_at": "2018-05-29T19:04:19Z", "closed_at": "2018-05-29T19:04:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "On Friday night we saw a failure to upload to PyPI (https://github.com/pantsbuild/pants/issues/5874) with the following error:\r\n\r\n> HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/\r\n\r\nI've just confirmed that `readme_renderer.rst.render(..)` for [the relevant file](https://github.com/pantsbuild/pants/blob/master/src/python/pants/notes/master.rst) succeeds (although it takes a while to render).\r\n\r\n----\r\n\r\nAre there additional requirements for PyPI upload beyond what is applied by this package? Obviously the file is quite large, and my first \"guess and check\" approach was going to be to truncate it. But having this package fail reproducibly the same way PyPI would would help folks debugging upload issues.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/107", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/107/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/107/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/107/events", "html_url": "https://github.com/pypa/readme_renderer/issues/107", "id": 327147726, "node_id": "MDU6SXNzdWUzMjcxNDc3MjY=", "number": 107, "title": "Checking markdown READMEs exits with error, breaking pypi uploads", "user": {"login": "jstaf", "id": 7572993, "node_id": "MDQ6VXNlcjc1NzI5OTM=", "avatar_url": "https://avatars3.githubusercontent.com/u/7572993?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jstaf", "html_url": "https://github.com/jstaf", "followers_url": "https://api.github.com/users/jstaf/followers", "following_url": "https://api.github.com/users/jstaf/following{/other_user}", "gists_url": "https://api.github.com/users/jstaf/gists{/gist_id}", "starred_url": "https://api.github.com/users/jstaf/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jstaf/subscriptions", "organizations_url": "https://api.github.com/users/jstaf/orgs", "repos_url": "https://api.github.com/users/jstaf/repos", "events_url": "https://api.github.com/users/jstaf/events{/privacy}", "received_events_url": "https://api.github.com/users/jstaf/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-05-29T02:03:10Z", "updated_at": "2019-05-26T19:54:22Z", "closed_at": "2018-05-29T02:17:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "It looks like readme_renderer is improperly exiting with an error when reading markdown-formatted readme files (instead of exiting cleanly with exit code 0). This breaks all uploads to test.pypi.org and pypi.org that use markdown-formatted readmes.\r\n\r\n```\r\n$ python setup.py check -s -r\r\nrunning check\r\nwarning: Check: Not checking long description content type 'text/markdown', this command only checks 'text/x-rst'.\r\n\r\nerror: Please correct your package.\r\n$ echo $?\r\n1\r\n```\r\n\r\nSee https://github.com/pypa/warehouse/issues/4079 for more info.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/104", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/104/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/104/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/104/events", "html_url": "https://github.com/pypa/readme_renderer/issues/104", "id": 326838166, "node_id": "MDU6SXNzdWUzMjY4MzgxNjY=", "number": 104, "title": "Allow <caption> tag", "user": {"login": "twm", "id": 43662, "node_id": "MDQ6VXNlcjQzNjYy", "avatar_url": "https://avatars2.githubusercontent.com/u/43662?v=4", "gravatar_id": "", "url": "https://api.github.com/users/twm", "html_url": "https://github.com/twm", "followers_url": "https://api.github.com/users/twm/followers", "following_url": "https://api.github.com/users/twm/following{/other_user}", "gists_url": "https://api.github.com/users/twm/gists{/gist_id}", "starred_url": "https://api.github.com/users/twm/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/twm/subscriptions", "organizations_url": "https://api.github.com/users/twm/orgs", "repos_url": "https://api.github.com/users/twm/repos", "events_url": "https://api.github.com/users/twm/events{/privacy}", "received_events_url": "https://api.github.com/users/twm/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-05-27T18:27:48Z", "updated_at": "2018-05-28T16:30:52Z", "closed_at": "2018-05-28T16:30:52Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "The [defusedxml readme on pypi.org](https://pypi.org/project/defusedxml/#python-xml-libraries) has a raw `<caption>` tag in the HTML:\r\n\r\n![image](https://user-images.githubusercontent.com/43662/40589332-6c2c9f36-61a0-11e8-8f4a-bcb995e840bd.png)\r\n\r\nThe `<caption>` element is [safe](https://wiki.whatwg.org/wiki/Sanitization_rules#Acceptable_Elements), so it shouldn't be sanitized away like this. This is the markup I see on pypi.org:\r\n\r\n```html\r\n<h2><a href=#id9 rel=nofollow>Python XML Libraries</a></h2>\r\n\r\n&lt;caption&gt;vulnerabilities and features&lt;/caption&gt;\r\n<table><colgroup>\r\n<col>\r\n<col>\r\n<!-- ...\r\n```\r\n\r\nThe `<caption>` tag appears to be output by a [csv-table reST directive](https://github.com/tiran/defusedxml/blob/f2c7c35b25f80c08923be49ac1f81e9cf95bd2ae/README.txt#L180).", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/100", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/100/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/100/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/100/events", "html_url": "https://github.com/pypa/readme_renderer/issues/100", "id": 316583066, "node_id": "MDU6SXNzdWUzMTY1ODMwNjY=", "number": 100, "title": "Check misses raw directive", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2018-04-22T14:20:12Z", "updated_at": "2018-05-25T21:18:16Z", "closed_at": "2018-05-25T21:18:16Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "From https://github.com/pypa/warehouse/issues/3785, readme_renderer is not raising an error when the raw directive is present.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/96", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/96/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/96/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/96/events", "html_url": "https://github.com/pypa/readme_renderer/issues/96", "id": 315825632, "node_id": "MDU6SXNzdWUzMTU4MjU2MzI=", "number": 96, "title": "Python 3.5 new keywords, async and await, not syntax highlighted", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122147, "node_id": "MDU6TGFiZWw4MzEyMjE0Nw==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 8, "created_at": "2018-04-19T10:52:12Z", "updated_at": "2018-11-02T11:02:28Z", "closed_at": "2018-04-20T18:14:10Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "From https://github.com/pypa/warehouse/issues/3770:\r\n\r\n> See for instance https://pypi.org/project/influxdbpusher/\r\n>\r\n> It has code snippets  with `async def` and `await`, which are not being properly highlighted as keywords.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/94", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/94/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/94/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/94/events", "html_url": "https://github.com/pypa/readme_renderer/issues/94", "id": 314325176, "node_id": "MDU6SXNzdWUzMTQzMjUxNzY=", "number": 94, "title": "<p align=\"center\"> not respected", "user": {"login": "nschloe", "id": 181628, "node_id": "MDQ6VXNlcjE4MTYyOA==", "avatar_url": "https://avatars3.githubusercontent.com/u/181628?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nschloe", "html_url": "https://github.com/nschloe", "followers_url": "https://api.github.com/users/nschloe/followers", "following_url": "https://api.github.com/users/nschloe/following{/other_user}", "gists_url": "https://api.github.com/users/nschloe/gists{/gist_id}", "starred_url": "https://api.github.com/users/nschloe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nschloe/subscriptions", "organizations_url": "https://api.github.com/users/nschloe/orgs", "repos_url": "https://api.github.com/users/nschloe/repos", "events_url": "https://api.github.com/users/nschloe/events{/privacy}", "received_events_url": "https://api.github.com/users/nschloe/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2018-04-14T12:28:33Z", "updated_at": "2018-04-20T17:49:10Z", "closed_at": "2018-04-20T17:49:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "Compare [pygmsh on pypi](https://pypi.org/project/pygmsh/)\r\n![pp](https://user-images.githubusercontent.com/181628/38768202-0d7f638c-3ff0-11e8-9820-897d777ebaaa.png)\r\n\r\n and [on github]().\r\n![gh](https://user-images.githubusercontent.com/181628/38768203-11d25228-3ff0-11e8-9b89-9409b6e954b8.png)\r\n\r\nThe corresponding part in the README.md is\r\n```html\r\n<p align=\"center\">\r\n  <img src=\"https://nschloe.github.io/pygmsh/logo.png\" width=\"20%\">\r\n</p>\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/88", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/88/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/88/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/88/events", "html_url": "https://github.com/pypa/readme_renderer/issues/88", "id": 313818499, "node_id": "MDU6SXNzdWUzMTM4MTg0OTk=", "number": 88, "title": "Code blocks in markdown-encoded long_description do not render double quotes", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 0, "created_at": "2018-04-12T17:23:45Z", "updated_at": "2018-04-13T22:54:10Z", "closed_at": "2018-04-13T22:54:10Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "From https://github.com/pypa/warehouse/issues/3629:\r\n\r\n> e.g. docstrings at https://pypi.org/project/tempcase/0.1.0/\r\n>\r\n> I'm viewing from Ubuntu 16.04, Firefox 59.0.2\r\n>\r\n> ![](https://user-images.githubusercontent.com/8995328/38642158-3b600b1c-3da7-11e8-8268-0f379b69bd3c.png)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/87", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/87/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/87/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/87/events", "html_url": "https://github.com/pypa/readme_renderer/issues/87", "id": 313811280, "node_id": "MDU6SXNzdWUzMTM4MTEyODA=", "number": 87, "title": "Conflicting output", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 1, "created_at": "2018-04-12T17:00:02Z", "updated_at": "2018-04-13T17:10:02Z", "closed_at": "2018-04-13T17:10:02Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "When run on [this source distribution](https://files.pythonhosted.org/packages/e7/01/445b8626409505ef9ef4897cb727f3b89c11853440dd5ac3376c70eedab4/viewstate-0.4.1.tar.gz), the latest version of `readme_renderer` produces conflicting output, which indicates that the `long_description` is both valid RST, yet produces an error:\r\n\r\n```\r\n$ python setup.py check -r -s\r\nrunning check\r\nwarning: Check: :2: (WARNING/2) Title underline too short.\r\n\r\nwarning: Check:\r\n\r\nwarning: Check: ASP.NET View State Decoder\r\n\r\nwarning: Check: ======================\r\n\r\nwarning: Check: The project's long_description has invalid markup which will not be rendered on PyPI.\r\n\r\nThe project's long description is valid RST.\r\nerror: Please correct your package.\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/81", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/81/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/81/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/81/events", "html_url": "https://github.com/pypa/readme_renderer/issues/81", "id": 311005177, "node_id": "MDU6SXNzdWUzMTEwMDUxNzc=", "number": 81, "title": "Investigate whether we can raise an error if checking a Markdown description", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 0, "created_at": "2018-04-03T21:28:25Z", "updated_at": "2018-04-10T05:32:24Z", "closed_at": "2018-04-10T05:32:24Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "In #80 @jonparrott said:\r\n\r\n> Should we also consider throwing an outright error if -r is specified and the content-type is set to markdown? (We can do it in a separate bug/PR, just wanted to bring it up)\r\n\r\nI said:\r\n\r\n> That'd be great, but I don't think distutils provides a way to get arbitrary metadata fields, and it doesn't support `long_description_content_type` field yet either, so I'm not sure it would be possible.\r\n\r\nIt'd be great to investigate whether this is true or not.\r\n\r\nIt's worth mentioning here that distutils is unlikely to support anything beyond Metadata 1.1 (and we also need to be backwards-compatible with older versions of distutils).", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/79", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/79/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/79/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/79/events", "html_url": "https://github.com/pypa/readme_renderer/issues/79", "id": 310988253, "node_id": "MDU6SXNzdWUzMTA5ODgyNTM=", "number": 79, "title": "GFM list: Blankline required between heading and list", "user": {"login": "nnadeau", "id": 6395915, "node_id": "MDQ6VXNlcjYzOTU5MTU=", "avatar_url": "https://avatars2.githubusercontent.com/u/6395915?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nnadeau", "html_url": "https://github.com/nnadeau", "followers_url": "https://api.github.com/users/nnadeau/followers", "following_url": "https://api.github.com/users/nnadeau/following{/other_user}", "gists_url": "https://api.github.com/users/nnadeau/gists{/gist_id}", "starred_url": "https://api.github.com/users/nnadeau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nnadeau/subscriptions", "organizations_url": "https://api.github.com/users/nnadeau/orgs", "repos_url": "https://api.github.com/users/nnadeau/repos", "events_url": "https://api.github.com/users/nnadeau/events{/privacy}", "received_events_url": "https://api.github.com/users/nnadeau/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-04-03T20:33:56Z", "updated_at": "2018-04-03T20:51:29Z", "closed_at": "2018-04-03T20:51:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "# Expected\r\nThe following list without a blank space between the heading/list is valid GitHub Flavoured Markdown, according to the following parsers:\r\n- https://atom.io/packages/markdown-preview\r\n- This issue's input box \r\n\r\n```\r\n# Heading\r\n- Foo\r\n- Bar\r\n  - X\r\n  - Y\r\n```\r\n\r\n# Heading\r\n- Foo\r\n- Bar\r\n  - X\r\n  - Y\r\n\r\n# Actual\r\n```\r\npython3 setup.py check -r -s \r\n\r\nwarning: Check: :4: (ERROR/3) Unexpected indentation.\r\n\r\nwarning: Check: Invalid markup which will not be rendered on PyPI.\r\n\r\nerror: Please correct your package.\r\n```\r\n\r\n# Solutions\r\n- Adding a blank line under the heading\r\n```\r\n# Heading\r\n\r\n- Foo\r\n- Bar\r\n  - X\r\n  - Y\r\n```\r\n\r\n- Removing the indentation\r\n```\r\n# Heading\r\n- Foo\r\n- Bar\r\n- X\r\n- Y\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/78", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/78/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/78/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/78/events", "html_url": "https://github.com/pypa/readme_renderer/issues/78", "id": 310985497, "node_id": "MDU6SXNzdWUzMTA5ODU0OTc=", "number": 78, "title": "GFM table: Optional whitespace next to pipes", "user": {"login": "nnadeau", "id": 6395915, "node_id": "MDQ6VXNlcjYzOTU5MTU=", "avatar_url": "https://avatars2.githubusercontent.com/u/6395915?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nnadeau", "html_url": "https://github.com/nnadeau", "followers_url": "https://api.github.com/users/nnadeau/followers", "following_url": "https://api.github.com/users/nnadeau/following{/other_user}", "gists_url": "https://api.github.com/users/nnadeau/gists{/gist_id}", "starred_url": "https://api.github.com/users/nnadeau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nnadeau/subscriptions", "organizations_url": "https://api.github.com/users/nnadeau/orgs", "repos_url": "https://api.github.com/users/nnadeau/repos", "events_url": "https://api.github.com/users/nnadeau/events{/privacy}", "received_events_url": "https://api.github.com/users/nnadeau/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2018-04-03T20:25:45Z", "updated_at": "2018-04-03T20:50:42Z", "closed_at": "2018-04-03T20:50:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "# Expected\r\nThe following table without spaces between the pipes is valid GitHub Flavoured Markdown, according to the following parsers:\r\n- https://atom.io/packages/markdown-preview\r\n- This issue's input box \r\n\r\n```\r\n|Foo|Bar|\r\n|---|---|\r\n|FooFoo|BarBar|\r\n```\r\n\r\n|Foo|Bar|\r\n|---|---|\r\n|FooFoo|BarBar|\r\n\r\n# Actual\r\n```\r\npython3 setup.py check -r -s \r\n\r\nwarning: Check: :1: (ERROR/3) Undefined substitution referenced: \"Foo|Bar\".\r\n\r\nwarning: Check: Invalid markup which will not be rendered on PyPI.\r\n\r\nerror: Please correct your package.\r\n```\r\n\r\n# Solution\r\n- Adding spaces next to all the pipes stops the errors:\r\n```\r\n| Foo | Bar |\r\n| --- | --- |\r\n| FooFoo | BarBar |\r\n```\r\n\r\n| Foo | Bar |\r\n| --- | --- |\r\n| FooFoo | BarBar |\r\n\r\n- This issue probably stems from how the [GFM spec was interpreted](https://github.github.com/gfm/#tables-extension-), specifically: `[...] Spaces between pipes and cell content are trimmed [...]\r\n  - Spaces are optional", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/76", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/76/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/76/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/76/events", "html_url": "https://github.com/pypa/readme_renderer/issues/76", "id": 310924706, "node_id": "MDU6SXNzdWUzMTA5MjQ3MDY=", "number": 76, "title": "Allow `details` and `summary` tags", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-04-03T17:19:13Z", "updated_at": "2018-04-10T05:45:31Z", "closed_at": "2018-04-10T05:45:31Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "From: https://github.com/pypa/warehouse/issues/3539:\r\n\r\n>Thanks for adding markdown support!\r\n> \r\n>I just tried uploading one of my projects with the ``long_description_content_type='text/markdown'``. Overall it looks good (apart for the relative links, which I will need to fix manually). However, I noticed that the ``<details>`` tags aren't being rendered correctly. This might have to do with the quote blocks that I put inside of the HTML tags, but the page renders correctly on Github.\r\n>\r\n>Reference (see the ``FAQ`` section at the bottom):\r\n>\r\n>https://test.pypi.org/project/rtv/1.22.1.post1/\r\n>https://github.com/michael-lazar/rtv/blob/master/README.md#faq\r\n\r\nThis should be simple as adding the `details` and `summary` to `ALLOWED_TAGS`.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/75", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/75/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/75/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/75/events", "html_url": "https://github.com/pypa/readme_renderer/issues/75", "id": 310526774, "node_id": "MDU6SXNzdWUzMTA1MjY3NzQ=", "number": 75, "title": "Support Syntax Highlighting w/ GFM", "user": {"login": "di", "id": 294415, "node_id": "MDQ6VXNlcjI5NDQxNQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/294415?v=4", "gravatar_id": "", "url": "https://api.github.com/users/di", "html_url": "https://github.com/di", "followers_url": "https://api.github.com/users/di/followers", "following_url": "https://api.github.com/users/di/following{/other_user}", "gists_url": "https://api.github.com/users/di/gists{/gist_id}", "starred_url": "https://api.github.com/users/di/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/di/subscriptions", "organizations_url": "https://api.github.com/users/di/orgs", "repos_url": "https://api.github.com/users/di/repos", "events_url": "https://api.github.com/users/di/events{/privacy}", "received_events_url": "https://api.github.com/users/di/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2018-04-02T16:08:11Z", "updated_at": "2018-04-10T04:36:24Z", "closed_at": "2018-04-10T04:36:24Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "From https://github.com/pypa/warehouse/issues/3508:\r\n\r\n> GItHub has syntax highlighting for code blocks, PyPI has not.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/70", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/70/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/70/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/70/events", "html_url": "https://github.com/pypa/readme_renderer/issues/70", "id": 308719558, "node_id": "MDU6SXNzdWUzMDg3MTk1NTg=", "number": 70, "title": "Improve text encoding error message", "user": {"login": "lgh2", "id": 17437250, "node_id": "MDQ6VXNlcjE3NDM3MjUw", "avatar_url": "https://avatars0.githubusercontent.com/u/17437250?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lgh2", "html_url": "https://github.com/lgh2", "followers_url": "https://api.github.com/users/lgh2/followers", "following_url": "https://api.github.com/users/lgh2/following{/other_user}", "gists_url": "https://api.github.com/users/lgh2/gists{/gist_id}", "starred_url": "https://api.github.com/users/lgh2/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lgh2/subscriptions", "organizations_url": "https://api.github.com/users/lgh2/orgs", "repos_url": "https://api.github.com/users/lgh2/repos", "events_url": "https://api.github.com/users/lgh2/events{/privacy}", "received_events_url": "https://api.github.com/users/lgh2/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-03-26T20:16:29Z", "updated_at": "2018-03-26T20:45:34Z", "closed_at": "2018-03-26T20:45:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "Since [the only character encoding that package metadata supports is UTF-8](https://packaging.python.org/specifications/core-metadata/?highlight=encoding#description-content-type-optional), I tried testing readme_renderer with a file in ISO/IEC 8859 encoding as the `long_description`. I got the following error message: \r\n\r\n```Traceback (most recent call last):\r\n  File \"setup.py\", line 9, in <module>\r\n    long_description = f.read()\r\n  File \"/home/user/Python/Readme_GFM/venv/lib/python3.6/codecs.py\", line 698, in read\r\n    return self.reader.read(size)\r\n  File \"/home/user/Python/Readme_GFM/venv/lib/python3.6/codecs.py\", line 501, in read\r\n    newchars, decodedbytes = self.decode(data, self.errors)\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte\r\n```\r\nI think it would be helpful to trap this exception in readme_renderer and give the user a more helpful error message that clearly indicates that their file is not in UTF-8 encoding.  I'm pretty confident I can do this for the case in which readme_renderer is invoked on the command line, but I am not sure how trapping and re-raising this error will affect the rest of Warehouse when it uses readme_renderer. ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/144", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/144/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/144/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/144/events", "html_url": "https://github.com/pypa/readme_renderer/issues/144", "id": 385000789, "node_id": "MDU6SXNzdWUzODUwMDA3ODk=", "number": 144, "title": "reStructuredText header issue", "user": {"login": "dgasaway", "id": 566661, "node_id": "MDQ6VXNlcjU2NjY2MQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/566661?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dgasaway", "html_url": "https://github.com/dgasaway", "followers_url": "https://api.github.com/users/dgasaway/followers", "following_url": "https://api.github.com/users/dgasaway/following{/other_user}", "gists_url": "https://api.github.com/users/dgasaway/gists{/gist_id}", "starred_url": "https://api.github.com/users/dgasaway/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dgasaway/subscriptions", "organizations_url": "https://api.github.com/users/dgasaway/orgs", "repos_url": "https://api.github.com/users/dgasaway/repos", "events_url": "https://api.github.com/users/dgasaway/events{/privacy}", "received_events_url": "https://api.github.com/users/dgasaway/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2018-03-19T00:39:38Z", "updated_at": "2019-03-18T19:41:18Z", "closed_at": "2019-03-18T19:41:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "I was testing a new project (new to PyPI) by uploading to TestPyPI.  I have a README.rst file that is read into long_description.  The README looked fine in bitbucket, passed readme_renderer and rst-lint, but kept failing to render formatted in the project description on TestPyPI.  After tinkering for hours, I chopped up the file and kept adding more pieces until the failure came back, and it came down to a header that looked like this...\r\n\r\n```\r\nFrom Source\r\n-----------\r\n```\r\n\r\nAnd then I noticed that in the (unformatted) project description on TestPyPI, it would strangely render with a greater than symbol in front...\r\n\r\n```\r\n>From Source\r\n-----------\r\n```\r\nI made sure there were no special characters in that position in the file.  Deleted everything between this and the text before it.  Looked good.  Eventually, I just changed the header, and the problem went away.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/64", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/64/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/64/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/64/events", "html_url": "https://github.com/pypa/readme_renderer/issues/64", "id": 293678568, "node_id": "MDU6SXNzdWUyOTM2Nzg1Njg=", "number": 64, "title": "feature: notice if there is no long_description", "user": {"login": "brainwane", "id": 842790, "node_id": "MDQ6VXNlcjg0Mjc5MA==", "avatar_url": "https://avatars0.githubusercontent.com/u/842790?v=4", "gravatar_id": "", "url": "https://api.github.com/users/brainwane", "html_url": "https://github.com/brainwane", "followers_url": "https://api.github.com/users/brainwane/followers", "following_url": "https://api.github.com/users/brainwane/following{/other_user}", "gists_url": "https://api.github.com/users/brainwane/gists{/gist_id}", "starred_url": "https://api.github.com/users/brainwane/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/brainwane/subscriptions", "organizations_url": "https://api.github.com/users/brainwane/orgs", "repos_url": "https://api.github.com/users/brainwane/repos", "events_url": "https://api.github.com/users/brainwane/events{/privacy}", "received_events_url": "https://api.github.com/users/brainwane/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-02-01T20:49:45Z", "updated_at": "2018-03-30T20:59:05Z", "closed_at": "2018-03-30T20:59:05Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "We ought to warn the user about a problem if the `long_description` is entirely absent from `setup.py`.\r\n\r\nExample: https://github.com/rytilahti/python-miio/blob/21065f696c2167e86d72f90e660a14dcef573587/setup.py has no `long_description`. But when I run readme-renderer version 17.2 in the root of that repo, in a Python 3.5.3 virtualenv, doesn't speak up about an error:\r\n\r\n~~~\r\n$ python setup.py check -r -s\r\nrunning check\r\n$\r\n~~~\r\n\r\ncc @rytilahti", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/63", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/63/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/63/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/63/events", "html_url": "https://github.com/pypa/readme_renderer/issues/63", "id": 293676415, "node_id": "MDU6SXNzdWUyOTM2NzY0MTU=", "number": 63, "title": "feature: report success explicitly", "user": {"login": "brainwane", "id": 842790, "node_id": "MDQ6VXNlcjg0Mjc5MA==", "avatar_url": "https://avatars0.githubusercontent.com/u/842790?v=4", "gravatar_id": "", "url": "https://api.github.com/users/brainwane", "html_url": "https://github.com/brainwane", "followers_url": "https://api.github.com/users/brainwane/followers", "following_url": "https://api.github.com/users/brainwane/following{/other_user}", "gists_url": "https://api.github.com/users/brainwane/gists{/gist_id}", "starred_url": "https://api.github.com/users/brainwane/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/brainwane/subscriptions", "organizations_url": "https://api.github.com/users/brainwane/orgs", "repos_url": "https://api.github.com/users/brainwane/repos", "events_url": "https://api.github.com/users/brainwane/events{/privacy}", "received_events_url": "https://api.github.com/users/brainwane/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-02-01T20:42:23Z", "updated_at": "2018-04-10T05:34:29Z", "closed_at": "2018-04-10T05:34:29Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "Right now, when a check is successful:\r\n\r\n~~~\r\n$ python setup.py check -r -s\r\nrunning check\r\n$ \r\n~~~\r\n\r\nIt would be good to explicitly say something like \"Check successful\".", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/61", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/61/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/61/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/61/events", "html_url": "https://github.com/pypa/readme_renderer/issues/61", "id": 286839944, "node_id": "MDU6SXNzdWUyODY4Mzk5NDQ=", "number": 61, "title": "Include docinfo table", "user": {"login": "lelit", "id": 412797, "node_id": "MDQ6VXNlcjQxMjc5Nw==", "avatar_url": "https://avatars1.githubusercontent.com/u/412797?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lelit", "html_url": "https://github.com/lelit", "followers_url": "https://api.github.com/users/lelit/followers", "following_url": "https://api.github.com/users/lelit/following{/other_user}", "gists_url": "https://api.github.com/users/lelit/gists{/gist_id}", "starred_url": "https://api.github.com/users/lelit/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lelit/subscriptions", "organizations_url": "https://api.github.com/users/lelit/orgs", "repos_url": "https://api.github.com/users/lelit/repos", "events_url": "https://api.github.com/users/lelit/events{/privacy}", "received_events_url": "https://api.github.com/users/lelit/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122147, "node_id": "MDU6TGFiZWw4MzEyMjE0Nw==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 4, "created_at": "2018-01-08T18:24:36Z", "updated_at": "2018-05-14T16:23:57Z", "closed_at": "2018-05-14T16:18:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm used to put standard docinfo in my README.rst and thus in package's description.\r\n\r\nThe `rst.render()` function considers only the `fragment`, though, so that information does not appear on PyPI/Warehouse.\r\n\r\nTo trick it I indent the docinfo fields, so that they are rendered as a `<table>` within a `<blockquote>`: that works, but the result is somewhat ugly.\r\n\r\nWhat do you think about prepending the `docinfo` part, if present?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/59", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/59/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/59/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/59/events", "html_url": "https://github.com/pypa/readme_renderer/issues/59", "id": 286073786, "node_id": "MDU6SXNzdWUyODYwNzM3ODY=", "number": 59, "title": "PyPi only rendering first line of long_description", "user": {"login": "gdude2002", "id": 204153, "node_id": "MDQ6VXNlcjIwNDE1Mw==", "avatar_url": "https://avatars3.githubusercontent.com/u/204153?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gdude2002", "html_url": "https://github.com/gdude2002", "followers_url": "https://api.github.com/users/gdude2002/followers", "following_url": "https://api.github.com/users/gdude2002/following{/other_user}", "gists_url": "https://api.github.com/users/gdude2002/gists{/gist_id}", "starred_url": "https://api.github.com/users/gdude2002/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gdude2002/subscriptions", "organizations_url": "https://api.github.com/users/gdude2002/orgs", "repos_url": "https://api.github.com/users/gdude2002/repos", "events_url": "https://api.github.com/users/gdude2002/events{/privacy}", "received_events_url": "https://api.github.com/users/gdude2002/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2018-01-04T18:29:21Z", "updated_at": "2018-08-18T16:44:15Z", "closed_at": "2018-01-04T20:46:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "Yesterday, I published the [initial alpha of my project](https://pypi.org/project/melcloud/0.0.1/) on PyPi. This release has a correctly-rendered description.\r\n\r\nToday, I made some additions to the README and now PyPi is only rendering the first line in the file, regardless of what's actually there.\r\n\r\n* [Current PyPi Release](https://pypi.org/project/melcloud/0.0.3/)\r\n* [Current README](https://github.com/gdude2002/melcloud/blob/master/README.rst)\r\n\r\nI've checked my README both with `readme_renderer` via `setup.py check -r -s` and also using `restview`, and everything seems to be just fine. I'm using Python `3.6.1` when checking that way. Additionally, GitHub appears to be perfectly happy with the README.\r\n\r\nIs this a bug, or did I miss something obscure?\r\n\r\n---\r\n\r\nEDIT: `rstcheck` finds no errors either.\r\n  ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/57", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/57/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/57/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/57/events", "html_url": "https://github.com/pypa/readme_renderer/issues/57", "id": 280610998, "node_id": "MDU6SXNzdWUyODA2MTA5OTg=", "number": 57, "title": "`python setup.py check --restructuredtext` misses an error with python3.5", "user": {"login": "paternal", "id": 6587757, "node_id": "MDQ6VXNlcjY1ODc3NTc=", "avatar_url": "https://avatars0.githubusercontent.com/u/6587757?v=4", "gravatar_id": "", "url": "https://api.github.com/users/paternal", "html_url": "https://github.com/paternal", "followers_url": "https://api.github.com/users/paternal/followers", "following_url": "https://api.github.com/users/paternal/following{/other_user}", "gists_url": "https://api.github.com/users/paternal/gists{/gist_id}", "starred_url": "https://api.github.com/users/paternal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/paternal/subscriptions", "organizations_url": "https://api.github.com/users/paternal/orgs", "repos_url": "https://api.github.com/users/paternal/repos", "events_url": "https://api.github.com/users/paternal/events{/privacy}", "received_events_url": "https://api.github.com/users/paternal/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122150, "node_id": "MDU6TGFiZWw4MzEyMjE1MA==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/wontfix", "name": "wontfix", "color": "ea9d6e", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-12-08T20:42:00Z", "updated_at": "2017-12-10T20:46:11Z", "closed_at": "2017-12-10T20:46:11Z", "author_association": "NONE", "active_lock_reason": null, "body": "With commit 2d4fd7f7e9e768d4f09b04e463de3270323a0c2e of [this repo](https://framagit.org/spalax/papersize), I get:\r\n\r\n- python2.7, python3.6:\r\n\r\n  ~~~sh\r\n  $ python setup.py check --restructuredtext\r\n  running check\r\n  warning: Check: :2: (WARNING/2) Title underline too short.\r\n  \r\n  warning: Check:\r\n  \r\n  warning: Check: papersize \ud83d\udccf Paper size related tools\r\n  \r\n  warning: Check: ====================================\r\n  \r\n  warning: Check: Invalid markup which will not be rendered on PyPI.\r\n  ~~~\r\n\r\n- python3.5:\r\n\r\n  ~~~sh\r\n  $ python setup.py check --restructuredtext\r\n  running check\r\n  ~~~\r\n\r\nIn short: python3.5 does not see an error that is correctly raised with python2.7 and python3.6 (I did not test any other python version).\r\n\r\n-- Louis", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/56", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/56/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/56/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/56/events", "html_url": "https://github.com/pypa/readme_renderer/issues/56", "id": 270331758, "node_id": "MDU6SXNzdWUyNzAzMzE3NTg=", "number": 56, "title": "Registered as readme on PyPI", "user": {"login": "pradyunsg", "id": 3275593, "node_id": "MDQ6VXNlcjMyNzU1OTM=", "avatar_url": "https://avatars1.githubusercontent.com/u/3275593?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pradyunsg", "html_url": "https://github.com/pradyunsg", "followers_url": "https://api.github.com/users/pradyunsg/followers", "following_url": "https://api.github.com/users/pradyunsg/following{/other_user}", "gists_url": "https://api.github.com/users/pradyunsg/gists{/gist_id}", "starred_url": "https://api.github.com/users/pradyunsg/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pradyunsg/subscriptions", "organizations_url": "https://api.github.com/users/pradyunsg/orgs", "repos_url": "https://api.github.com/users/pradyunsg/repos", "events_url": "https://api.github.com/users/pradyunsg/events{/privacy}", "received_events_url": "https://api.github.com/users/pradyunsg/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-11-01T14:44:56Z", "updated_at": "2018-04-10T05:36:47Z", "closed_at": "2018-04-10T05:36:47Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "This package is registered as both `readme_renderer` and `readme` on PyPI.\r\n\r\nOne of them should probably be updated to say \"use the other\".\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/52", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/52/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/52/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/52/events", "html_url": "https://github.com/pypa/readme_renderer/issues/52", "id": 240127051, "node_id": "MDU6SXNzdWUyNDAxMjcwNTE=", "number": 52, "title": "Could the Distutils check generate an HTML document ?", "user": {"login": "Lucas-C", "id": 925560, "node_id": "MDQ6VXNlcjkyNTU2MA==", "avatar_url": "https://avatars1.githubusercontent.com/u/925560?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Lucas-C", "html_url": "https://github.com/Lucas-C", "followers_url": "https://api.github.com/users/Lucas-C/followers", "following_url": "https://api.github.com/users/Lucas-C/following{/other_user}", "gists_url": "https://api.github.com/users/Lucas-C/gists{/gist_id}", "starred_url": "https://api.github.com/users/Lucas-C/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Lucas-C/subscriptions", "organizations_url": "https://api.github.com/users/Lucas-C/orgs", "repos_url": "https://api.github.com/users/Lucas-C/repos", "events_url": "https://api.github.com/users/Lucas-C/events{/privacy}", "received_events_url": "https://api.github.com/users/Lucas-C/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122147, "node_id": "MDU6TGFiZWw4MzEyMjE0Nw==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-07-03T10:11:37Z", "updated_at": "2018-10-09T22:46:59Z", "closed_at": "2018-10-09T22:46:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nI tested it and this would just be a matter of adding the following at the end of https://github.com/pypa/readme_renderer/blob/master/readme_renderer/integration/distutils.py :\r\n```\r\nelse:\r\n    with open('long_description.html', 'w') as long_desc_file:\r\n        long_desc_file.write(markup)\r\n```\r\n\r\nNow, are you OK to add this feature ?\r\nI find it very useful to preview the description before uploading a package.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/47", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/47/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/47/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/47/events", "html_url": "https://github.com/pypa/readme_renderer/issues/47", "id": 212764045, "node_id": "MDU6SXNzdWUyMTI3NjQwNDU=", "number": 47, "title": "linkify unexpected keyword argument 'skip_pre'  ", "user": {"login": "pawamoy", "id": 3999221, "node_id": "MDQ6VXNlcjM5OTkyMjE=", "avatar_url": "https://avatars2.githubusercontent.com/u/3999221?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pawamoy", "html_url": "https://github.com/pawamoy", "followers_url": "https://api.github.com/users/pawamoy/followers", "following_url": "https://api.github.com/users/pawamoy/following{/other_user}", "gists_url": "https://api.github.com/users/pawamoy/gists{/gist_id}", "starred_url": "https://api.github.com/users/pawamoy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pawamoy/subscriptions", "organizations_url": "https://api.github.com/users/pawamoy/orgs", "repos_url": "https://api.github.com/users/pawamoy/repos", "events_url": "https://api.github.com/users/pawamoy/events{/privacy}", "received_events_url": "https://api.github.com/users/pawamoy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2017-03-08T15:21:16Z", "updated_at": "2017-03-09T14:13:45Z", "closed_at": "2017-03-08T18:05:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, I encountered this error today:\r\n\r\n```\r\ncheck runtests: commands[0] | python setup.py check --strict --metadata --restructuredtext\r\nrunning check\r\nTraceback (most recent call last):\r\n  File \"setup.py\", line 75, in <module>\r\n    extras_require={\r\n  File \"/usr/local/lib/python3.5/distutils/core.py\", line 148, in setup\r\n    dist.run_commands()\r\n  File \"/usr/local/lib/python3.5/distutils/dist.py\", line 955, in run_commands\r\n    self.run_command(cmd)\r\n  File \"/usr/local/lib/python3.5/distutils/dist.py\", line 974, in run_command\r\n    cmd_obj.run()\r\n  File \"/usr/local/lib/python3.5/distutils/command/check.py\", line 71, in run\r\n    self.check_restructuredtext()\r\n  File \"/media/pawamoy/Data/git/django-cs-models/.tox/check/lib/python3.5/site-packages/readme_renderer/integration/distutils.py\", line 30, in check_restructuredtext\r\n    markup = render(data, stream=stream)\r\n  File \"/media/pawamoy/Data/git/django-cs-models/.tox/check/lib/python3.5/site-packages/readme_renderer/rst.py\", line 121, in render\r\n    return clean(rendered)\r\n  File \"/media/pawamoy/Data/git/django-cs-models/.tox/check/lib/python3.5/site-packages/readme_renderer/clean.py\", line 77, in clean\r\n    parse_email=False,\r\nTypeError: linkify() got an unexpected keyword argument 'skip_pre'\r\n```\r\n\r\nHere are the versions of the packages I'm using:\r\n\r\n- check-manifest==0.35\r\n- docutils==0.13.1\r\n- readme-renderer==16.0\r\n- Pygments==2.2.0", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/45", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/45/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/45/events", "html_url": "https://github.com/pypa/readme_renderer/issues/45", "id": 194665332, "node_id": "MDU6SXNzdWUxOTQ2NjUzMzI=", "number": 45, "title": "IndexError pop from empty list with some image links", "user": {"login": "pawamoy", "id": 3999221, "node_id": "MDQ6VXNlcjM5OTkyMjE=", "avatar_url": "https://avatars2.githubusercontent.com/u/3999221?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pawamoy", "html_url": "https://github.com/pawamoy", "followers_url": "https://api.github.com/users/pawamoy/followers", "following_url": "https://api.github.com/users/pawamoy/following{/other_user}", "gists_url": "https://api.github.com/users/pawamoy/gists{/gist_id}", "starred_url": "https://api.github.com/users/pawamoy/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pawamoy/subscriptions", "organizations_url": "https://api.github.com/users/pawamoy/orgs", "repos_url": "https://api.github.com/users/pawamoy/repos", "events_url": "https://api.github.com/users/pawamoy/events{/privacy}", "received_events_url": "https://api.github.com/users/pawamoy/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-12-09T18:31:49Z", "updated_at": "2016-12-10T08:54:03Z", "closed_at": "2016-12-09T21:28:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, today I encountered two times the same error (see below). It seems that some links like\r\n`https://cloud.githubusercontent.com/assets/3999221/14685134/8cde04be-0733-11e6-8eda-b59f2e2fa6c3.png` are breaking stuff. Maybe it comes from a change on GitHub and not from readme_renderer because it was working well until now, with the same version.\r\n\r\nAny ideas?\r\n\r\n> Traceback (most recent call last):\r\n  File \"setup.py\", line 73, in <module>\r\n    extras_require={\r\n  File \"/usr/lib/python3.5/distutils/core.py\", line 148, in setup\r\n    dist.run_commands()\r\n  File \"/usr/lib/python3.5/distutils/dist.py\", line 955, in run_commands\r\n    self.run_command(cmd)\r\n  File \"/usr/lib/python3.5/distutils/dist.py\", line 974, in run_command\r\n    cmd_obj.run()\r\n  File \"/usr/lib/python3.5/distutils/command/check.py\", line 71, in run\r\n    self.check_restructuredtext()\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/readme_renderer/integration/distutils.py\", line 30, in check_restructuredtext\r\n    markup = render(data, stream=stream)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/readme_renderer/rst.py\", line 115, in render\r\n    parts = publish_parts(raw, writer=writer, settings_overrides=settings)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/core.py\", line 448, in publish_parts\r\n    enable_exit_status=enable_exit_status)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/core.py\", line 662, in publish_programmatically\r\n    output = pub.publish(enable_exit_status=enable_exit_status)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/core.py\", line 219, in publish\r\n    output = self.writer.write(self.document, self.destination)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/writers/__init__.py\", line 80, in write\r\n    self.translate()\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/writers/_html_base.py\", line 71, in translate\r\n    self.document.walkabout(visitor)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py\", line 174, in walkabout\r\n    if child.walkabout(visitor):\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py\", line 174, in walkabout\r\n    if child.walkabout(visitor):\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py\", line 174, in walkabout\r\n    if child.walkabout(visitor):\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py\", line 187, in walkabout\r\n    visitor.dispatch_departure(self)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/docutils/nodes.py\", line 1895, in dispatch_departure\r\n    return method(node)\r\n  File \"/media/pawantu/Data/git/django-suit-dashboard/.tox/check/lib/python3.5/site-packages/readme_renderer/rst.py\", line 48, in depart_image\r\n    self.body.append(self.context.pop())\r\nIndexError: pop from empty list", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/44", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/44/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/44/events", "html_url": "https://github.com/pypa/readme_renderer/issues/44", "id": 187654123, "node_id": "MDU6SXNzdWUxODc2NTQxMjM=", "number": 44, "title": "width tag not respected for images", "user": {"login": "nschloe", "id": 181628, "node_id": "MDQ6VXNlcjE4MTYyOA==", "avatar_url": "https://avatars3.githubusercontent.com/u/181628?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nschloe", "html_url": "https://github.com/nschloe", "followers_url": "https://api.github.com/users/nschloe/followers", "following_url": "https://api.github.com/users/nschloe/following{/other_user}", "gists_url": "https://api.github.com/users/nschloe/gists{/gist_id}", "starred_url": "https://api.github.com/users/nschloe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nschloe/subscriptions", "organizations_url": "https://api.github.com/users/nschloe/orgs", "repos_url": "https://api.github.com/users/nschloe/repos", "events_url": "https://api.github.com/users/nschloe/events{/privacy}", "received_events_url": "https://api.github.com/users/nschloe/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122145, "node_id": "MDU6TGFiZWw4MzEyMjE0NQ==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "theacodes", "id": 250995, "node_id": "MDQ6VXNlcjI1MDk5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/250995?v=4", "gravatar_id": "", "url": "https://api.github.com/users/theacodes", "html_url": "https://github.com/theacodes", "followers_url": "https://api.github.com/users/theacodes/followers", "following_url": "https://api.github.com/users/theacodes/following{/other_user}", "gists_url": "https://api.github.com/users/theacodes/gists{/gist_id}", "starred_url": "https://api.github.com/users/theacodes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/theacodes/subscriptions", "organizations_url": "https://api.github.com/users/theacodes/orgs", "repos_url": "https://api.github.com/users/theacodes/repos", "events_url": "https://api.github.com/users/theacodes/events{/privacy}", "received_events_url": "https://api.github.com/users/theacodes/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 2, "created_at": "2016-11-07T08:47:25Z", "updated_at": "2018-04-13T22:36:03Z", "closed_at": "2018-04-13T22:36:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "When including images like\r\n```rst\r\n.. figure:: https://nschloe.github.io/quadrature/circle.svg\r\n   :alt: \r\n   :width: 25.0%\r\n```\r\nthe width tag is not respected. See, e.g., [here](https://pypi.org/project/quadpy/).\r\n\r\n(The bug is also present in the on legacy, see [here](https://github.com/pypa/pypi-legacy/issues/547#issuecomment-258497814).)", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/40", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/40/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/40/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/40/events", "html_url": "https://github.com/pypa/readme_renderer/issues/40", "id": 124868382, "node_id": "MDU6SXNzdWUxMjQ4NjgzODI=", "number": 40, "title": "Fix `readme` release on pypi ", "user": {"login": "ionelmc", "id": 129501, "node_id": "MDQ6VXNlcjEyOTUwMQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/129501?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ionelmc", "html_url": "https://github.com/ionelmc", "followers_url": "https://api.github.com/users/ionelmc/followers", "following_url": "https://api.github.com/users/ionelmc/following{/other_user}", "gists_url": "https://api.github.com/users/ionelmc/gists{/gist_id}", "starred_url": "https://api.github.com/users/ionelmc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ionelmc/subscriptions", "organizations_url": "https://api.github.com/users/ionelmc/orgs", "repos_url": "https://api.github.com/users/ionelmc/repos", "events_url": "https://api.github.com/users/ionelmc/events{/privacy}", "received_events_url": "https://api.github.com/users/ionelmc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2016-01-05T00:19:44Z", "updated_at": "2016-01-05T12:56:41Z", "closed_at": "2016-01-05T09:26:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "The current \"fix\" for #26 is not very good and creates unnecessary churn on people to switch to a new package.\n\nA better way:\n- Make an \"alias package\". This package will depend on `readme_renderer` but it won't install any files.\n  \n  Eg:\n\n```\nfrom setuptools import setup\n\n\nsetup(\n    install_requires=['readme_renderer'],\n    name='readme',\n    platforms=['all'],\n    py_modules=['wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141'], # allows empty wheel to be created\n    version=\"0.8.0\",\n)  \n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/39", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/39/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/39/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/39/events", "html_url": "https://github.com/pypa/readme_renderer/issues/39", "id": 124844519, "node_id": "MDU6SXNzdWUxMjQ4NDQ1MTk=", "number": 39, "title": "Project name with dash instead of underscore?", "user": {"login": "reinout", "id": 121433, "node_id": "MDQ6VXNlcjEyMTQzMw==", "avatar_url": "https://avatars0.githubusercontent.com/u/121433?v=4", "gravatar_id": "", "url": "https://api.github.com/users/reinout", "html_url": "https://github.com/reinout", "followers_url": "https://api.github.com/users/reinout/followers", "following_url": "https://api.github.com/users/reinout/following{/other_user}", "gists_url": "https://api.github.com/users/reinout/gists{/gist_id}", "starred_url": "https://api.github.com/users/reinout/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/reinout/subscriptions", "organizations_url": "https://api.github.com/users/reinout/orgs", "repos_url": "https://api.github.com/users/reinout/repos", "events_url": "https://api.github.com/users/reinout/events{/privacy}", "received_events_url": "https://api.github.com/users/reinout/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-01-04T21:35:04Z", "updated_at": "2016-01-05T09:36:06Z", "closed_at": "2016-01-05T09:36:06Z", "author_association": "NONE", "active_lock_reason": null, "body": "Many projects, I believe, use a dash in their name and an underscore for the actual code.\n\nThat'd mean `readme-renderer` as a project name and `from readme_renderer import something` in code.\n\nThe rename hasn't been released yet, I believe, so there's still time to change it. Would this be an option?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/37", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/37/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/37/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/37/events", "html_url": "https://github.com/pypa/readme_renderer/issues/37", "id": 112968231, "node_id": "MDU6SXNzdWUxMTI5NjgyMzE=", "number": 37, "title": "Re (pyPi Issue 836) Lengthlimit on HTML generation", "user": {"login": "TonyFlury", "id": 15114356, "node_id": "MDQ6VXNlcjE1MTE0MzU2", "avatar_url": "https://avatars0.githubusercontent.com/u/15114356?v=4", "gravatar_id": "", "url": "https://api.github.com/users/TonyFlury", "html_url": "https://github.com/TonyFlury", "followers_url": "https://api.github.com/users/TonyFlury/followers", "following_url": "https://api.github.com/users/TonyFlury/following{/other_user}", "gists_url": "https://api.github.com/users/TonyFlury/gists{/gist_id}", "starred_url": "https://api.github.com/users/TonyFlury/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/TonyFlury/subscriptions", "organizations_url": "https://api.github.com/users/TonyFlury/orgs", "repos_url": "https://api.github.com/users/TonyFlury/repos", "events_url": "https://api.github.com/users/TonyFlury/events{/privacy}", "received_events_url": "https://api.github.com/users/TonyFlury/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-10-23T07:32:57Z", "updated_at": "2015-10-23T07:43:04Z", "closed_at": "2015-10-23T07:43:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have noted that there seems to be an undocumented length limit on the size of rst which can be translated to html. I initially attempted to use a large README.rst file (306 lines, 2769 words, 18315 characters) as the long description on PyPi, but that site (which uses your library) failed to render the rst file as HTML (github has no problem with the same rst file and renders it as valid HTML on both github and githug pages).\n\nIn contrast pyPi renders the long rst file as a simple flat text file - with no attempt to generate HTML.\n\nI have had to implement a much shorter summary.rst file in order to get the rst to render.\n\nI did report this fault on the pyPi issues list (#836) but I was told that they used this library and to report the issue here.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/35", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/35/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/35/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/35/events", "html_url": "https://github.com/pypa/readme_renderer/issues/35", "id": 105114663, "node_id": "MDU6SXNzdWUxMDUxMTQ2NjM=", "number": 35, "title": "readme.rst.render explodes on some inputs", "user": {"login": "alex", "id": 772, "node_id": "MDQ6VXNlcjc3Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/772?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alex", "html_url": "https://github.com/alex", "followers_url": "https://api.github.com/users/alex/followers", "following_url": "https://api.github.com/users/alex/following{/other_user}", "gists_url": "https://api.github.com/users/alex/gists{/gist_id}", "starred_url": "https://api.github.com/users/alex/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alex/subscriptions", "organizations_url": "https://api.github.com/users/alex/orgs", "repos_url": "https://api.github.com/users/alex/repos", "events_url": "https://api.github.com/users/alex/events{/privacy}", "received_events_url": "https://api.github.com/users/alex/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-09-06T20:03:33Z", "updated_at": "2015-09-11T11:45:06Z", "closed_at": "2015-09-11T11:45:06Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "Here's a failing test:\n\n``` py\n_______________________________ test_non_rst_001 _______________________________\n\n    def test_non_rst_001():\n>       assert render('[http://www.example.com](h)') == '<p>[http://www.example.com](h)</p>'\n\ntests/test_rst.py:47:\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nreadme/rst.py:122: in render\n    return clean(rendered)\nreadme/clean.py:77: in clean\n    parse_email=False,\n../../cryptography/site-packages/bleach/__init__.py:133: in linkify\n    forest = parser.parseFragment(text)\n../../cryptography/site-packages/html5lib/html5parser.py:253: in parseFragment\n    self._parse(stream, True, container=container, encoding=encoding)\n../../cryptography/site-packages/html5lib/html5parser.py:94: in _parse\n    self.mainLoop()\n../../cryptography/site-packages/html5lib/html5parser.py:166: in mainLoop\n    for token in self.normalizedTokens():\n../../cryptography/site-packages/html5lib/html5parser.py:222: in normalizedTokens\n    for token in self.tokenizer:\n../../cryptography/site-packages/html5lib/sanitizer.py:294: in __iter__\n    token = self.sanitize_token(token)\n../../cryptography/site-packages/html5lib/sanitizer.py:190: in sanitize_token\n    return self.allowed_token(token, token_type)\n../../cryptography/site-packages/html5lib/sanitizer.py:210: in allowed_token\n    uri = urlparse.urlparse(val_unescaped)\n../../../.pyenv/versions/pypy-2.6.1/lib-python/2.7/urlparse.py:143: in urlparse\n    tuple = urlsplit(url, scheme, allow_fragments)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nurl = '', scheme = 'http', allow_fragments = True\n\n    def urlsplit(url, scheme='', allow_fragments=True):\n        \"\"\"Parse a URL into 5 components:\n        <scheme>://<netloc>/<path>?<query>#<fragment>\n        Return a 5-tuple: (scheme, netloc, path, query, fragment).\n        Note that we don't break the components up in smaller bits\n        (e.g. netloc is a single string) and we don't expand % escapes.\"\"\"\n        allow_fragments = bool(allow_fragments)\n        key = url, scheme, allow_fragments, type(url), type(scheme)\n        cached = _parse_cache.get(key, None)\n        if cached:\n            return cached\n        if len(_parse_cache) >= MAX_CACHE_SIZE: # avoid runaway growth\n            clear_cache()\n        netloc = query = fragment = ''\n        i = url.find(':')\n        if i > 0:\n            if url[:i] == 'http': # optimize the common case\n                scheme = url[:i].lower()\n                url = url[i+1:]\n                if url[:2] == '//':\n                    netloc, url = _splitnetloc(url, 2)\n                    if (('[' in netloc and ']' not in netloc) or\n                            (']' in netloc and '[' not in netloc)):\n>                       raise ValueError(\"Invalid IPv6 URL\")\nE                       ValueError: Invalid IPv6 URL\n\n../../../.pyenv/versions/pypy-2.6.1/lib-python/2.7/urlparse.py:191: ValueError\n```\n\nI'm not sure if this is actually fixable in `readme`, but filing here to start with\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/34", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/34/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/34/events", "html_url": "https://github.com/pypa/readme_renderer/issues/34", "id": 103513747, "node_id": "MDU6SXNzdWUxMDM1MTM3NDc=", "number": 34, "title": "There's no changelog file", "user": {"login": "reinout", "id": 121433, "node_id": "MDQ6VXNlcjEyMTQzMw==", "avatar_url": "https://avatars0.githubusercontent.com/u/121433?v=4", "gravatar_id": "", "url": "https://api.github.com/users/reinout", "html_url": "https://github.com/reinout", "followers_url": "https://api.github.com/users/reinout/followers", "following_url": "https://api.github.com/users/reinout/following{/other_user}", "gists_url": "https://api.github.com/users/reinout/gists{/gist_id}", "starred_url": "https://api.github.com/users/reinout/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/reinout/subscriptions", "organizations_url": "https://api.github.com/users/reinout/orgs", "repos_url": "https://api.github.com/users/reinout/repos", "events_url": "https://api.github.com/users/reinout/events{/privacy}", "received_events_url": "https://api.github.com/users/reinout/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2015-08-27T13:48:27Z", "updated_at": "2016-01-04T20:41:41Z", "closed_at": "2016-01-04T20:41:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "There's no `CHANGES.rst`. I wanted to look up the change between 0.5/0.6 as 0.6 changed a method that zest.releaser used (see https://github.com/zestsoftware/zest.releaser/issues/123).\n\nI'll fix the actual problem on zest.releaser's end. The readme change itself looks logical. I _did_ want to mention the issue here, too, to make it known that there are other packages depending on readme now :-) So please don't move around the `render()` method too much.\n\n(zest.releaser is of course a mighty handy tool to release \"readme\" with, especially when you've got a changelog with version numbers to update, too :-) )\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/31", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/31/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/31/events", "html_url": "https://github.com/pypa/readme_renderer/issues/31", "id": 88513913, "node_id": "MDU6SXNzdWU4ODUxMzkxMw==", "number": 31, "title": "\"pip install readme\" fails on Windows + Miniconda", "user": {"login": "edisongustavo", "id": 234595, "node_id": "MDQ6VXNlcjIzNDU5NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/234595?v=4", "gravatar_id": "", "url": "https://api.github.com/users/edisongustavo", "html_url": "https://github.com/edisongustavo", "followers_url": "https://api.github.com/users/edisongustavo/followers", "following_url": "https://api.github.com/users/edisongustavo/following{/other_user}", "gists_url": "https://api.github.com/users/edisongustavo/gists{/gist_id}", "starred_url": "https://api.github.com/users/edisongustavo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/edisongustavo/subscriptions", "organizations_url": "https://api.github.com/users/edisongustavo/orgs", "repos_url": "https://api.github.com/users/edisongustavo/repos", "events_url": "https://api.github.com/users/edisongustavo/events{/privacy}", "received_events_url": "https://api.github.com/users/edisongustavo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2015-06-15T19:14:12Z", "updated_at": "2016-01-05T08:57:19Z", "closed_at": "2016-01-04T20:41:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to install the [restview library](https://pypi.python.org/pypi/restview) and it depends on the `readme` library.\n\nI'm getting this error though:\n\n```\nC:\\\n\u03bb pip install readme\nCollecting readme\n  Using cached readme-0.5.1-py2.py3-none-any.whl\nRequirement already satisfied (use --upgrade to upgrade): docutils in c:\\miniconda\\lib\\site-packages (from readme)\nRequirement already satisfied (use --upgrade to upgrade): Pygments in c:\\miniconda\\lib\\site-packages (from readme)\nRequirement already satisfied (use --upgrade to upgrade): six in c:\\miniconda\\lib\\site-packages (from readme)\nRequirement already satisfied (use --upgrade to upgrade): bleach in c:\\miniconda\\lib\\site-packages (from readme)\nRequirement already satisfied (use --upgrade to upgrade): html5lib>=0.999 in c:\\miniconda\\lib\\site-packages (from bleach->readme)\nInstalling collected packages: readme\nException:\nTraceback (most recent call last):\n  File \"C:\\Miniconda\\lib\\site-packages\\pip\\basecommand.py\", line 223, in main\n    status = self.run(options, args)\n  File \"C:\\Miniconda\\lib\\site-packages\\pip\\commands\\install.py\", line 297, in run\n    root=options.root_path,\n  File \"C:\\Miniconda\\lib\\site-packages\\pip\\req\\req_set.py\", line 622, in install\n    **kwargs\n  File \"C:\\Miniconda\\lib\\site-packages\\pip\\req\\req_install.py\", line 808, in install\n    self.move_wheel_files(self.source_dir, root=root)\n  File \"C:\\Miniconda\\lib\\site-packages\\pip\\req\\req_install.py\", line 1003, in move_wheel_files\n    isolated=self.isolated,\n  File \"C:\\Miniconda\\lib\\site-packages\\pip\\wheel.py\", line 339, in move_wheel_files\n    clobber(source, lib_dir, True)\n  File \"C:\\Miniconda\\lib\\site-packages\\pip\\wheel.py\", line 317, in clobber\n    shutil.copyfile(srcfile, destfile)\n  File \"C:\\Miniconda\\lib\\shutil.py\", line 83, in copyfile\n    with open(dst, 'wb') as fdst:\nIOError: [Errno 2] No such file or directory: 'C:\\\\Miniconda\\\\Lib\\\\site-packages\\\\readme\\\\clean.py'\n```\n\nThese are the versions of conda and pip that I'm using:\n\n```\nC:\\\n\u03bb conda -V\nconda 3.11.0-dirty\n\nC:\\\n\u03bb pip --version\npip 7.0.3 from C:\\Miniconda\\lib\\site-packages (python 2.7)\n```\n\nI'm using Windows 7 64 bits\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/30", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/30/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/30/events", "html_url": "https://github.com/pypa/readme_renderer/issues/30", "id": 83324888, "node_id": "MDU6SXNzdWU4MzMyNDg4OA==", "number": 30, "title": "rst.render. Possibility to return StringIO stream ?", "user": {"login": "Carreau", "id": 335567, "node_id": "MDQ6VXNlcjMzNTU2Nw==", "avatar_url": "https://avatars3.githubusercontent.com/u/335567?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Carreau", "html_url": "https://github.com/Carreau", "followers_url": "https://api.github.com/users/Carreau/followers", "following_url": "https://api.github.com/users/Carreau/following{/other_user}", "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}", "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions", "organizations_url": "https://api.github.com/users/Carreau/orgs", "repos_url": "https://api.github.com/users/Carreau/repos", "events_url": "https://api.github.com/users/Carreau/events{/privacy}", "received_events_url": "https://api.github.com/users/Carreau/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2015-06-01T05:31:00Z", "updated_at": "2018-04-11T19:31:43Z", "closed_at": "2018-04-10T05:52:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "Would it be possible to return the stream in the following function.\n\nhttps://github.com/pypa/readme/blob/master/readme/rst.py#L102-L121\nOr at least return what was written to the stream.\n\nYes, I can pass my own stream, and that's what I'm doing for now. \n\nAlternatively, if not, is there a reason not to pass `os.devnull` ?\n\n(can do a PR if one or the other seem acceptable)\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/29", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/29/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/29/events", "html_url": "https://github.com/pypa/readme_renderer/issues/29", "id": 81813518, "node_id": "MDU6SXNzdWU4MTgxMzUxOA==", "number": 29, "title": "not so useful output", "user": {"login": "gforcada", "id": 1155680, "node_id": "MDQ6VXNlcjExNTU2ODA=", "avatar_url": "https://avatars1.githubusercontent.com/u/1155680?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gforcada", "html_url": "https://github.com/gforcada", "followers_url": "https://api.github.com/users/gforcada/followers", "following_url": "https://api.github.com/users/gforcada/following{/other_user}", "gists_url": "https://api.github.com/users/gforcada/gists{/gist_id}", "starred_url": "https://api.github.com/users/gforcada/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gforcada/subscriptions", "organizations_url": "https://api.github.com/users/gforcada/orgs", "repos_url": "https://api.github.com/users/gforcada/repos", "events_url": "https://api.github.com/users/gforcada/events{/privacy}", "received_events_url": "https://api.github.com/users/gforcada/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 83122147, "node_id": "MDU6TGFiZWw4MzEyMjE0Nw==", "url": "https://api.github.com/repos/pypa/readme_renderer/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-05-28T07:54:37Z", "updated_at": "2018-04-13T22:53:14Z", "closed_at": "2018-04-13T22:53:14Z", "author_association": "NONE", "active_lock_reason": null, "body": "My setup.py looks like this:\n\n```\nlong_description = \"\"\"{0}\n{1}\n\n\nLICENSE\n=======\n\n{2}\n\"\"\".format(\n    open('README.rst').read(),\n    open('CHANGES.rst').read(),\n    open(os.path.join('docs', 'LICENSE.txt')).read(),\n)\n\nsetup(\n    ...\n    long_description=long_description,\n    ...\n)\n```\n\nRunning `python setup.py check -r -s` reports two errors:\n\n```\nrunning check\nwarning: check: Possible incomplete section title.\nTreating the overline as ordinary text because it's so short. (line 573)\n\nwarning: check: Possible incomplete section title.\nTreating the overline as ordinary text because it's so short. (line 573)\n\nerror: Please correct your package.\n```\n\nThe problem is that saying that line 573 is wrong is not so useful as there are three files involved on the long_description (`README.rst`, `CHANGES.rst` and `docs/LICENSE.txt`).\n\nIt would be so much more useful if the offending line(s) are shown, so searching for the error would be much more clear, in my case that was this header:\n\n```\n???\n\n---\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/28", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/28/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/28/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/28/events", "html_url": "https://github.com/pypa/readme_renderer/issues/28", "id": 80075985, "node_id": "MDU6SXNzdWU4MDA3NTk4NQ==", "number": 28, "title": "README doesn't render properly in Pypi", "user": {"login": "scls19fr", "id": 109167, "node_id": "MDQ6VXNlcjEwOTE2Nw==", "avatar_url": "https://avatars3.githubusercontent.com/u/109167?v=4", "gravatar_id": "", "url": "https://api.github.com/users/scls19fr", "html_url": "https://github.com/scls19fr", "followers_url": "https://api.github.com/users/scls19fr/followers", "following_url": "https://api.github.com/users/scls19fr/following{/other_user}", "gists_url": "https://api.github.com/users/scls19fr/gists{/gist_id}", "starred_url": "https://api.github.com/users/scls19fr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/scls19fr/subscriptions", "organizations_url": "https://api.github.com/users/scls19fr/orgs", "repos_url": "https://api.github.com/users/scls19fr/repos", "events_url": "https://api.github.com/users/scls19fr/events{/privacy}", "received_events_url": "https://api.github.com/users/scls19fr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-05-24T06:52:38Z", "updated_at": "2015-06-05T09:50:57Z", "closed_at": "2015-06-05T09:50:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\n\nI'm trying to publish a Python package\nhttps://pypi.python.org/pypi?:action=display&name=pandas_confusion&version=0.0.1\n\nCode is available here\nhttps://github.com/scls19fr/pandas_confusion\n\nbut README doesn't seems to be properly parsed by Pypi\n\nAny idea ?\n\nKind regards\n\nsee https://github.com/msabramo/setuptools-markdown/issues/5\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/27", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/27/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/27/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/27/events", "html_url": "https://github.com/pypa/readme_renderer/issues/27", "id": 63274776, "node_id": "MDU6SXNzdWU2MzI3NDc3Ng==", "number": 27, "title": "default role?", "user": {"login": "meejah", "id": 145599, "node_id": "MDQ6VXNlcjE0NTU5OQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/145599?v=4", "gravatar_id": "", "url": "https://api.github.com/users/meejah", "html_url": "https://github.com/meejah", "followers_url": "https://api.github.com/users/meejah/followers", "following_url": "https://api.github.com/users/meejah/following{/other_user}", "gists_url": "https://api.github.com/users/meejah/gists{/gist_id}", "starred_url": "https://api.github.com/users/meejah/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/meejah/subscriptions", "organizations_url": "https://api.github.com/users/meejah/orgs", "repos_url": "https://api.github.com/users/meejah/repos", "events_url": "https://api.github.com/users/meejah/events{/privacy}", "received_events_url": "https://api.github.com/users/meejah/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-03-20T17:59:06Z", "updated_at": "2018-04-10T05:45:13Z", "closed_at": "2018-04-10T05:45:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "Sphinx defaults to \"py:\" role, so e.g. \"meth:`pkg.foo`\" works, but this barfs on that and needs \"py:meth:`pkg.foo`\" instead. It would be nice if the default for Python packages was the Python role.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/26", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/26/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/26/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/26/events", "html_url": "https://github.com/pypa/readme_renderer/issues/26", "id": 57693213, "node_id": "MDU6SXNzdWU1NzY5MzIxMw==", "number": 26, "title": "\"readme\" name conflicts on case-insensitive filesystems", "user": {"login": "astraw", "id": 30176, "node_id": "MDQ6VXNlcjMwMTc2", "avatar_url": "https://avatars3.githubusercontent.com/u/30176?v=4", "gravatar_id": "", "url": "https://api.github.com/users/astraw", "html_url": "https://github.com/astraw", "followers_url": "https://api.github.com/users/astraw/followers", "following_url": "https://api.github.com/users/astraw/following{/other_user}", "gists_url": "https://api.github.com/users/astraw/gists{/gist_id}", "starred_url": "https://api.github.com/users/astraw/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/astraw/subscriptions", "organizations_url": "https://api.github.com/users/astraw/orgs", "repos_url": "https://api.github.com/users/astraw/repos", "events_url": "https://api.github.com/users/astraw/events{/privacy}", "received_events_url": "https://api.github.com/users/astraw/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2015-02-14T13:35:26Z", "updated_at": "2016-01-04T20:41:52Z", "closed_at": "2016-01-04T20:41:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "Executive summary: the package name \"readme\" conflicts with Python installed site-packages/README file on case-insensitive filesystems.\n\nI am using Anaconda, pip, Python 2 and Mac OS X including its HFS case-insensitive filesystem and I think the name `readme` conflicts with the file `site-packages/README`. Here's what I see:\n\n```\n$ pip install readme\nDownloading/unpacking readme\n  Downloading readme-0.5.1.tar.gz\n  Running setup.py egg_info for package readme\n\nDownloading/unpacking bleach (from readme)\n  Downloading bleach-1.4.1.tar.gz\n  Running setup.py egg_info for package bleach\n\nRequirement already satisfied (use --upgrade to upgrade): docutils in /Users/straw/anaconda/lib/python2.7/site-packages (from readme)\nRequirement already satisfied (use --upgrade to upgrade): Pygments in /Users/straw/anaconda/lib/python2.7/site-packages (from readme)\nRequirement already satisfied (use --upgrade to upgrade): six in /Users/straw/anaconda/lib/python2.7/site-packages (from readme)\nDownloading/unpacking html5lib>=0.999 (from bleach->readme)\n  Downloading html5lib-0.999.tar.gz (885kB): 885kB downloaded\n  Running setup.py egg_info for package html5lib\n\nInstalling collected packages: readme, bleach, html5lib\n  Running setup.py install for readme\n    error: could not create '/Users/straw/anaconda/lib/python2.7/site-packages/readme': File exists\n    Complete output from command /Users/straw/anaconda/bin/python -c \"import setuptools;__file__='/private/var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip_build_straw/readme/setup.py';exec(compile(open(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))\" install --record /var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip-z4pFRV-record/install-record.txt --single-version-externally-managed:\n    running install\n\nrunning build\n\nrunning build_py\n\ncreating build\n\ncreating build/lib\n\ncreating build/lib/readme\n\ncopying readme/__about__.py -> build/lib/readme\n\ncopying readme/__init__.py -> build/lib/readme\n\ncopying readme/clean.py -> build/lib/readme\n\ncopying readme/rst.py -> build/lib/readme\n\ncreating build/lib/readme/integration\n\ncopying readme/integration/__init__.py -> build/lib/readme/integration\n\ncopying readme/integration/distutils.py -> build/lib/readme/integration\n\nrunning install_lib\n\ncreating /Users/straw/anaconda/lib/python2.7/site-packages/readme\n\nerror: could not create '/Users/straw/anaconda/lib/python2.7/site-packages/readme': File exists\n\n----------------------------------------\nCleaning up...\nCommand /Users/straw/anaconda/bin/python -c \"import setuptools;__file__='/private/var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip_build_straw/readme/setup.py';exec(compile(open(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))\" install --record /var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip-z4pFRV-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/var/folders/vl/p8l6zqp91dd9z76sxq7hzttm0000gn/T/pip_build_straw/readme\nStoring complete log in /Users/straw/.pip/pip.log\n```\n\nAnd indeed `/Users/straw/anaconda/lib/python2.7/site-packages/readme` does exist with the contents:\n\n```\nThis directory exists so that 3rd party packages can be installed\nhere.  Read the source for site.py for more details.\n```\n\nI guess this is installed directly from the original Python source file `./Lib/site-packages/README`. Due to the case insensitivity of the file system, this causes a name clash.\n\nRemoving the original file allows pip install readme to complete successfully.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/24", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/24/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/24/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/24/events", "html_url": "https://github.com/pypa/readme_renderer/issues/24", "id": 56944835, "node_id": "MDU6SXNzdWU1Njk0NDgzNQ==", "number": 24, "title": "console_script entrypoint for testing", "user": {"login": "westurner", "id": 50891, "node_id": "MDQ6VXNlcjUwODkx", "avatar_url": "https://avatars2.githubusercontent.com/u/50891?v=4", "gravatar_id": "", "url": "https://api.github.com/users/westurner", "html_url": "https://github.com/westurner", "followers_url": "https://api.github.com/users/westurner/followers", "following_url": "https://api.github.com/users/westurner/following{/other_user}", "gists_url": "https://api.github.com/users/westurner/gists{/gist_id}", "starred_url": "https://api.github.com/users/westurner/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/westurner/subscriptions", "organizations_url": "https://api.github.com/users/westurner/orgs", "repos_url": "https://api.github.com/users/westurner/repos", "events_url": "https://api.github.com/users/westurner/events{/privacy}", "received_events_url": "https://api.github.com/users/westurner/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-02-08T09:03:41Z", "updated_at": "2015-02-23T16:51:14Z", "closed_at": "2015-02-23T16:50:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "A `console_script` entrypoint for a CLI main function would be helpful for testing.\n\ne.g.:\n\n```\nreadme ./setup.py\nreadme 'pkg_name'\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/7", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/7/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/7/events", "html_url": "https://github.com/pypa/readme_renderer/issues/7", "id": 51763482, "node_id": "MDU6SXNzdWU1MTc2MzQ4Mg==", "number": 7, "title": "Enable Travis CI", "user": {"login": "msabramo", "id": 305268, "node_id": "MDQ6VXNlcjMwNTI2OA==", "avatar_url": "https://avatars1.githubusercontent.com/u/305268?v=4", "gravatar_id": "", "url": "https://api.github.com/users/msabramo", "html_url": "https://github.com/msabramo", "followers_url": "https://api.github.com/users/msabramo/followers", "following_url": "https://api.github.com/users/msabramo/following{/other_user}", "gists_url": "https://api.github.com/users/msabramo/gists{/gist_id}", "starred_url": "https://api.github.com/users/msabramo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/msabramo/subscriptions", "organizations_url": "https://api.github.com/users/msabramo/orgs", "repos_url": "https://api.github.com/users/msabramo/repos", "events_url": "https://api.github.com/users/msabramo/events{/privacy}", "received_events_url": "https://api.github.com/users/msabramo/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2014-12-12T02:20:11Z", "updated_at": "2015-01-24T19:08:17Z", "closed_at": "2015-01-24T19:08:17Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "There is a [`.travis.yml`](https://github.com/pypa/readme/blob/master/.travis.yml) (added by me in #2 and merged by you in https://github.com/pypa/readme/commit/faaba210ec069205f9e00fc271ef3d5c8a7450c9) but https://travis-ci.org/pypa/readme does not work yet.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pypa/readme_renderer/issues/1", "repository_url": "https://api.github.com/repos/pypa/readme_renderer", "labels_url": "https://api.github.com/repos/pypa/readme_renderer/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/pypa/readme_renderer/issues/1/comments", "events_url": "https://api.github.com/repos/pypa/readme_renderer/issues/1/events", "html_url": "https://github.com/pypa/readme_renderer/issues/1", "id": 35115712, "node_id": "MDU6SXNzdWUzNTExNTcxMg==", "number": 1, "title": "Markdown support", "user": {"login": "methane", "id": 199592, "node_id": "MDQ6VXNlcjE5OTU5Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/199592?v=4", "gravatar_id": "", "url": "https://api.github.com/users/methane", "html_url": "https://github.com/methane", "followers_url": "https://api.github.com/users/methane/followers", "following_url": "https://api.github.com/users/methane/following{/other_user}", "gists_url": "https://api.github.com/users/methane/gists{/gist_id}", "starred_url": "https://api.github.com/users/methane/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/methane/subscriptions", "organizations_url": "https://api.github.com/users/methane/orgs", "repos_url": "https://api.github.com/users/methane/repos", "events_url": "https://api.github.com/users/methane/events{/privacy}", "received_events_url": "https://api.github.com/users/methane/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 12, "created_at": "2014-06-06T03:05:05Z", "updated_at": "2017-09-07T19:49:40Z", "closed_at": "2017-09-07T19:49:40Z", "author_association": "NONE", "active_lock_reason": null, "body": "Recent days, many python project have README in Markdown format.\n", "performed_via_github_app": null, "score": 1.0}]}